import type { Chapter } from "@/lib/types";

export const ch01: Chapter = {
  slug: "introduction-to-ai",
  num: 1,
  title: "Introduction to Artificial Intelligence",
  unit: "basics",
  unitName: "AI Foundations",
  marks: "Part B · Foundations",
  minutes: 16,
  blurb: "What AI actually is (and isn't), how it relates to machine learning and deep learning, and the three domains every AI project falls into.",
  bigIdea: "Artificial Intelligence is not magic and not a robot — it is a machine that improves at a task by learning from data, instead of being told every rule by hand.",
  syllabus: [
    "What is Artificial Intelligence", "AI, Machine Learning and Deep Learning",
    "What is not AI", "Applications of AI in daily life",
    "Domains of AI — Data, Computer Vision, Natural Language Processing",
    "AI ethics — bias, privacy and access",
  ],
  blocks: [
    { t: "h", text: "So what is Artificial Intelligence?" },
    { t: "p", html: "When a machine does something that would normally need human intelligence — understanding speech, recognising a face, recommending the next song, deciding the fastest route — we call it <strong>Artificial Intelligence</strong>." },
    { t: "p", html: "The key idea is <em>learning</em>. A traditional program follows fixed instructions a human wrote. An AI system is shown lots of <strong>data</strong> and figures out the pattern for itself, then uses that pattern to make decisions or predictions on data it has never seen before." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "AI is the ability of a machine to <strong>perform tasks that usually require human intelligence</strong> — such as learning, reasoning, problem-solving and decision-making — by learning from data." },

    { t: "h", text: "What is NOT AI" },
    { t: "p", html: "This is a favourite exam trap. A machine following a fixed set of rules is <em>automation</em>, not AI — however clever it looks." },
    { t: "compare",
      left: { title: "Not AI (just programmed rules)", items: [
        "A washing machine that runs for a set time you chose",
        "A calculator adding two numbers",
        "An automatic door that opens for any motion",
        "A TV remote changing channels",
      ] },
      right: { title: "AI (learns / adapts from data)", items: [
        "A phone that recognises your face to unlock",
        "A keyboard predicting your next word",
        "A streaming app recommending shows you'll like",
        "A car that learns to stay in its lane",
      ] } },
    { t: "note", kind: "trap", html: "The test is not “is it a machine doing something useful?” but <strong>“does it learn or improve from data?”</strong> If a human wrote down every rule and the machine never changes, it is not AI." },

    { t: "h", text: "AI, Machine Learning and Deep Learning" },
    { t: "p", html: "These three words get mixed up constantly. They are <strong>nested</strong> — each one sits inside the last, like boxes within boxes." },
    { t: "table", head: ["Term", "What it means", "Everyday example"], rows: [
      ["Artificial Intelligence (AI)", "The whole field — any machine that mimics human intelligence.", "A chatbot that answers your questions"],
      ["Machine Learning (ML)", "A part of AI where the machine learns patterns from data instead of being hard-coded.", "Spam filter that learns which emails are junk"],
      ["Deep Learning (DL)", "A part of ML that uses <em>neural networks</em> with many layers to learn very complex patterns.", "Recognising objects in a photo"],
    ] },
    { t: "note", kind: "memory", html: "Remember the nesting: <strong>AI ⊃ ML ⊃ DL</strong>. All deep learning is machine learning, and all machine learning is AI — but not the other way round." },

    { t: "h", text: "The three domains of AI" },
    { t: "p", html: "Almost every AI project works with one of three kinds of data. The board expects you to name all three and give an example of each." },
    { t: "list", ordered: true, items: [
      "<strong>Data Sciences</strong> — works with <em>numbers and records</em> (tables, statistics). Example: predicting tomorrow's sales from past data.",
      "<strong>Computer Vision (CV)</strong> — works with <em>images and video</em>. Example: face unlock, or a self-driving car spotting a pedestrian.",
      "<strong>Natural Language Processing (NLP)</strong> — works with <em>human language</em>, spoken or written. Example: Alexa, Google Translate, a chatbot.",
    ] },
    { t: "note", kind: "real", html: "Many real products combine domains. A video call that shows live subtitles uses <strong>NLP</strong> for the words and <strong>CV</strong> for reading lips or blurring your background." },

    { t: "h", text: "AI is everywhere already" },
    { t: "list", items: [
      "<strong>Maps</strong> predict traffic and the fastest route.",
      "<strong>Shopping and streaming</strong> recommend what you might want next.",
      "<strong>Banks</strong> flag unusual transactions as possible fraud.",
      "<strong>Healthcare</strong> helps read X-rays and scans.",
      "<strong>Phones</strong> — voice assistants, face unlock, smart photo search.",
    ] },

    { t: "h", text: "With great power — AI ethics" },
    { t: "p", html: "Because AI learns from data made by people, it can quietly copy human unfairness. Good AI is not just accurate — it is <strong>fair, private and transparent</strong>." },
    { t: "note", kind: "why", title: "The three ethics ideas to remember", html: "<strong>Bias</strong> — if the training data is one-sided, the AI will be too (e.g. a face system that works poorly for some groups). <strong>Privacy</strong> — AI needs data, but people's data must be protected and used with consent. <strong>Access</strong> — the benefits of AI should reach everyone, not only a few." },
    { t: "note", kind: "exam", html: "A common 2–3 mark question: “Give one example of AI bias and one way to reduce it.” Answer: a hiring tool trained mostly on male CVs may reject women; fix it by training on <strong>balanced, representative data</strong>." },
  ],
  examFocus: [
    "The learning-from-data definition of AI, stated in one clean sentence.",
    "AI vs automation — the “does it learn?” test, with a not-AI example.",
    "AI ⊃ ML ⊃ DL and what each layer adds.",
    "The three domains (Data, CV, NLP) with one example each.",
    "The three ethics ideas: bias, privacy and access.",
  ],
  flashcards: [
    { q: "Define Artificial Intelligence.", a: "The ability of a machine to perform tasks that usually need human intelligence — learning, reasoning, problem-solving and decision-making — by learning from data." },
    { q: "How is AI different from ordinary automation?", a: "Automation follows fixed rules a human wrote and never changes. AI learns patterns from data and can improve or adapt to new situations." },
    { q: "Give one example of something that is NOT AI, and why.", a: "A washing machine on a timer — it follows a fixed setting and does not learn from data, so it is automation, not AI." },
    { q: "How are AI, ML and DL related?", a: "They are nested: AI is the whole field, Machine Learning is a subset of AI that learns from data, and Deep Learning is a subset of ML that uses multi-layer neural networks. AI ⊃ ML ⊃ DL." },
    { q: "What is Machine Learning?", a: "A branch of AI in which a machine learns patterns from data and improves at a task with experience, instead of being explicitly programmed with every rule." },
    { q: "What is Deep Learning?", a: "A branch of Machine Learning that uses artificial neural networks with many layers to learn very complex patterns, such as recognising objects in images." },
    { q: "Name the three domains of AI.", a: "Data Sciences (numbers/records), Computer Vision (images/video), and Natural Language Processing (human language)." },
    { q: "Which AI domain would a self-driving car mostly use?", a: "Computer Vision — to see and identify roads, signs, cars and pedestrians from camera images." },
    { q: "Which AI domain powers a voice assistant like Alexa?", a: "Natural Language Processing (NLP) — understanding and responding to spoken human language." },
    { q: "What is bias in AI?", a: "When an AI system gives unfair results because it was trained on one-sided or unrepresentative data — e.g. a face system that works poorly for some groups." },
    { q: "Why is data privacy an AI ethics concern?", a: "AI needs large amounts of data, often personal, so that data must be collected with consent and protected from misuse." },
    { q: "Give two everyday applications of AI.", a: "Route/traffic prediction in maps, and content recommendations on streaming or shopping apps (also: face unlock, spam filters, fraud detection)." },
  ],
  quiz: [
    { q: "Which of these is the best definition of Artificial Intelligence?", options: ["Any machine that runs on electricity", "A machine that performs tasks needing human intelligence by learning from data", "A robot with arms and legs", "A very fast calculator"], answer: 1, why: "AI is about performing intelligence-like tasks (learning, reasoning, deciding) by learning from data — not about being a robot or being fast." },
    { q: "Which of the following is NOT an example of AI?", options: ["A spam filter that learns junk mail", "Face unlock on a phone", "A washing machine running for a preset time", "A show recommendation system"], answer: 2, why: "A preset timer follows a fixed rule and never learns — that is automation, not AI." },
    { q: "The correct relationship between the three terms is:", options: ["ML ⊃ AI ⊃ DL", "AI ⊃ ML ⊃ DL", "DL ⊃ ML ⊃ AI", "They are completely separate"], answer: 1, why: "AI is the largest field, Machine Learning sits inside it, and Deep Learning sits inside ML." },
    { q: "Deep Learning is based on:", options: ["Spreadsheets", "Artificial neural networks with many layers", "Fixed if-else rules", "Faster processors only"], answer: 1, why: "Deep Learning uses multi-layer artificial neural networks to learn complex patterns." },
    { q: "Recognising a face in a photograph belongs to which AI domain?", options: ["Natural Language Processing", "Data Sciences", "Computer Vision", "Statistics"], answer: 2, why: "Working with images and video is the Computer Vision domain." },
    { q: "A chatbot that understands typed questions mainly uses:", options: ["Computer Vision", "Natural Language Processing", "Data Sciences", "Robotics"], answer: 1, why: "Understanding human language (text or speech) is Natural Language Processing." },
    { q: "Predicting next month's sales from past sales figures is an example of:", options: ["Computer Vision", "Natural Language Processing", "Data Sciences", "Deep fake"], answer: 2, why: "Working with numbers and records to find patterns is the Data Sciences domain." },
    { q: "An AI hiring tool rejects most women because it learned from mostly male CVs. This is an example of:", options: ["Privacy loss", "AI bias", "Good accuracy", "Computer Vision"], answer: 1, why: "One-sided training data leads to unfair results — this is AI bias." },
    { q: "The main thing that makes a system 'AI' rather than ordinary software is that it:", options: ["Is expensive", "Learns or improves from data", "Runs on the internet", "Has a touchscreen"], answer: 1, why: "The defining feature of AI is learning/adapting from data, rather than following only hand-written rules." },
    { q: "Which is a genuine AI-ethics concern?", options: ["Making the app colourful", "Protecting the privacy of people's data", "Using a fast processor", "Adding more buttons"], answer: 1, why: "Privacy — collecting and protecting personal data responsibly — is a core AI-ethics issue, along with bias and fair access." },
  ],
  keyTopics: [
    { name: "Definition of AI (learning from data)", importance: "high", note: "Almost always a 1–2 mark question; state it precisely." },
    { name: "AI vs Machine Learning vs Deep Learning", importance: "high", note: "The nested AI ⊃ ML ⊃ DL relationship, with what each adds." },
    { name: "The three domains — Data, CV, NLP", importance: "high", note: "Name all three and give an example of each; classify a given application." },
    { name: "AI vs automation / what is not AI", importance: "medium", note: "The “does it learn from data?” test with an example." },
    { name: "AI ethics — bias, privacy, access", importance: "medium", note: "Define bias with an example and a fix; explain the privacy concern." },
    { name: "Everyday applications of AI", importance: "low", note: "List-based recall; useful in case-based questions." },
  ],
  written: [
    { q: "Define Artificial Intelligence.", marks: 1, kind: "short", importance: "high",
      answer: "Artificial Intelligence is the ability of a machine to perform tasks that normally require human intelligence — such as learning, reasoning, problem-solving and decision-making — by <strong>learning from data</strong>." },
    { q: "State one example of a machine that is NOT AI, and justify your answer.", marks: 1, kind: "short", importance: "medium",
      answer: "A washing machine running for a preset time is not AI, because it follows a <strong>fixed rule the user set</strong> and does not learn or adapt from data — that is automation, not AI." },
    { q: "Differentiate between Artificial Intelligence, Machine Learning and Deep Learning.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>AI</strong> is the whole field of machines mimicking human intelligence. <strong>Machine Learning</strong> is a subset of AI in which the machine learns patterns from data instead of being hard-coded. <strong>Deep Learning</strong> is a subset of ML that uses multi-layer neural networks for very complex patterns. They are nested: AI ⊃ ML ⊃ DL." },
    { q: "Name the three domains of AI and give one example of each.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Data Sciences</strong> — works with numbers/records, e.g. predicting sales from past data.<br><strong>Computer Vision (CV)</strong> — works with images/video, e.g. face unlock.<br><strong>Natural Language Processing (NLP)</strong> — works with human language, e.g. a voice assistant or translator." },
    { q: "What is meant by 'bias' in an AI system? Give an example and one way to reduce it.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Bias</strong> is when an AI gives unfair results because it learned from one-sided or unrepresentative data.<br><strong>Example:</strong> a hiring tool trained mostly on men's CVs may unfairly reject women.<br><strong>Fix:</strong> train it on <strong>balanced, representative data</strong> (and test it across different groups) so no group is disadvantaged." },
    { q: "'All Deep Learning is Machine Learning, but not all Machine Learning is Deep Learning.' Explain this statement.", marks: 2, kind: "short", importance: "medium",
      answer: "Deep Learning is a <em>subset</em> of Machine Learning — it is one particular way of doing ML, using multi-layer neural networks. So every Deep Learning method is an ML method. But ML also includes simpler techniques (like decision trees) that don't use deep neural networks, so not all ML is Deep Learning." },
    { q: "Explain, with examples, why not every automatic machine can be called Artificial Intelligence.", marks: 3, kind: "long", importance: "medium",
      answer: "A machine is AI only if it <strong>learns or adapts from data</strong>, not just because it works automatically.<br>• An automatic door or a timer-based washing machine follows <strong>fixed rules</strong> a human set — it never improves, so it is automation, not AI.<br>• A phone's face unlock or a spam filter <strong>learns patterns from data</strong> and improves, so it is AI.<br>The deciding test is: “Does it learn from data?” If no, it is ordinary automation." },
    { q: "Describe any three real-life applications of AI, mentioning the domain each one mainly uses.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>1. Navigation maps</strong> — predict traffic and the best route from huge amounts of past and live data. Domain: <em>Data Sciences</em>.<br><strong>2. Face unlock / self-driving cars</strong> — identify faces or road objects from camera images. Domain: <em>Computer Vision</em>.<br><strong>3. Voice assistants / translation apps</strong> — understand and respond to human language. Domain: <em>Natural Language Processing</em>.<br>Each learns from data rather than following fixed rules, which is what makes them AI. (Others: recommendations — Data Sciences; medical image reading — CV; chatbots — NLP.)" },
  ],
  assertionReason: [
    { assertion: "A washing machine that runs for a time the user sets is not an example of AI.",
      reason: "A system is called AI only if it learns or adapts from data, rather than just following fixed rules.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R is the correct reason: because the washing machine only follows a fixed setting and never learns from data, it is automation, not AI." },
    { assertion: "Deep Learning is a subset of Machine Learning.",
      reason: "Deep Learning uses multi-layer artificial neural networks, which are one technique within Machine Learning.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why DL sits inside ML — it is one ML technique based on neural networks." },
    { assertion: "AI systems can produce unfair results even when the code has no mistakes.",
      reason: "An AI learns from its training data, so biased or one-sided data leads to biased decisions.",
      answer: 0, importance: "medium",
      why: "Both true and R is the correct explanation: bias comes from the data the model learns from, not necessarily from buggy code." },
  ],
  caseStudies: [
    { title: "Sorting apps into AI and not-AI", importance: "high",
      source: "A student lists four things on her phone: (1) an alarm that rings at a time she sets, (2) a photo app that automatically groups pictures of the same person, (3) a keyboard that suggests her next word as she types, and (4) a torch that turns on when she taps a button.",
      parts: [
        { q: "Which two are examples of AI, and which two are not?", marks: 2, answer: "AI: the photo app (groups faces by learning) and the keyboard (predicts the next word from patterns). Not AI: the alarm and the torch — both follow fixed rules the user sets." },
        { q: "What single test did you use to decide?", marks: 1, answer: "Whether the system <strong>learns or improves from data</strong>. If it only follows fixed instructions, it is automation, not AI." },
        { q: "Which AI domain does the photo app mainly use?", marks: 1, answer: "Computer Vision — it works with images to recognise and group faces." },
      ] },
  ],
};
