import type { Chapter } from "@/lib/types";

export const ch02: Chapter = {
  slug: "ai-project-cycle",
  num: 2,
  title: "The AI Project Cycle",
  unit: "basics",
  unitName: "AI Foundations",
  marks: "Part B · Foundations",
  minutes: 18,
  blurb: "The five stages every AI project moves through — from scoping the problem with the 4Ws to acquiring data, exploring it, modelling and evaluating.",
  bigIdea: "You don't start an AI project by writing code. You start by understanding the problem — then let good data, not clever guessing, lead you to the answer.",
  syllabus: [
    "Stages of the AI Project Cycle",
    "Problem Scoping and the 4Ws Problem Canvas",
    "Data Acquisition", "Data Exploration",
    "Modelling — rule-based vs learning-based; supervised vs unsupervised",
    "Evaluation", "AI ethics and Sustainable Development Goals",
  ],
  blocks: [
    { t: "h", text: "The five stages" },
    { t: "p", html: "Every AI project follows the same path. Learn the order — the board often asks you to list the stages or place one correctly." },
    { t: "list", ordered: true, items: [
      "<strong>Problem Scoping</strong> — decide clearly what problem you are solving.",
      "<strong>Data Acquisition</strong> — gather the data you'll need.",
      "<strong>Data Exploration</strong> — look at the data and find patterns.",
      "<strong>Modelling</strong> — build the AI model that learns from the data.",
      "<strong>Evaluation</strong> — test how well the model actually works.",
    ] },
    { t: "note", kind: "memory", html: "A quick way to remember the order: <strong>S-A-E-M-E</strong> — <strong>S</strong>coping, <strong>A</strong>cquisition, <strong>E</strong>xploration, <strong>M</strong>odelling, <strong>E</strong>valuation." },

    { t: "h", text: "Stage 1 — Problem Scoping and the 4Ws" },
    { t: "p", html: "Before touching any data, you define the problem using the <strong>4Ws Problem Canvas</strong>. Getting this right is half the project." },
    { t: "table", head: ["W", "It asks…", "Example (a school wants to cut food waste)"], rows: [
      ["Who", "Who is affected by the problem?", "Students and the school canteen staff"],
      ["What", "What is the problem, and how do you know it exists?", "A lot of cooked food is thrown away daily; the canteen weighs the waste"],
      ["Where", "Where does the problem happen — the context?", "In the school canteen, at lunch time"],
      ["Why", "Why is it worth solving — what's the benefit?", "Saves money and reduces waste if we predict how much to cook"],
    ] },
    { t: "note", kind: "exam", html: "The four are <strong>Who, What, Where, Why</strong>. A frequent mistake is adding “When” or “How” — those are not part of the 4Ws Problem Canvas." },
    { t: "p", html: "The 4Ws lead to a single <strong>Problem Statement</strong>: “<em>Our canteen staff</em> (Who) have the problem that <em>too much food is wasted</em> (What) <em>at lunch time</em> (Where), and solving it would <em>save money and food</em> (Why).”" },

    { t: "h", text: "Stage 2 — Data Acquisition" },
    { t: "p", html: "Data is the fuel of AI. In this stage you collect the <strong>relevant, reliable and enough</strong> data the problem needs." },
    { t: "list", items: [
      "<strong>Features</strong> — the pieces of information you feed in (e.g. day of week, weather, number of students present).",
      "<strong>Sources</strong> — surveys, sensors, records, cameras, public datasets, APIs.",
      "The data must be <strong>authentic and unbiased</strong> — garbage in, garbage out.",
    ] },
    { t: "note", kind: "trap", html: "More data is not automatically better. Data that is <strong>relevant and representative</strong> beats a huge pile of noisy or one-sided data." },

    { t: "h", text: "Stage 3 — Data Exploration" },
    { t: "p", html: "Raw data is hard to understand as rows of numbers, so you <strong>visualise</strong> it — graphs, charts, plots — to spot patterns, trends and anything odd before building a model." },
    { t: "note", kind: "why", title: "Why explore before modelling?", html: "Visualising the data helps you notice trends (e.g. more waste on Mondays), catch errors, and decide which features actually matter — so the model you build later is aimed in the right direction." },

    { t: "h", text: "Stage 4 — Modelling" },
    { t: "p", html: "Now you build the <strong>model</strong> — the part that actually makes predictions. There are two broad approaches." },
    { t: "compare",
      left: { title: "Rule-based approach", items: [
        "A human writes the rules the machine follows",
        "The rules do not change on their own",
        "Good for simple, well-understood problems",
        "Example: “if temperature &gt; 38°C, flag as fever”",
      ] },
      right: { title: "Learning-based approach", items: [
        "The machine learns the rules from data itself",
        "It improves as it sees more data",
        "Needed for complex problems (images, language)",
        "This is Machine Learning",
      ] } },
    { t: "p", html: "Learning-based models split further by whether the training data is <strong>labelled</strong>:" },
    { t: "table", head: ["Type", "Data used", "It does…", "Example"], rows: [
      ["Supervised learning", "Labelled data (answers given)", "Learns to predict the label", "Sort emails into spam / not-spam"],
      ["Unsupervised learning", "Unlabelled data (no answers)", "Finds groups/patterns itself", "Group customers into similar types"],
    ] },
    { t: "note", kind: "idea", html: "Supervised learning has two flavours: <strong>classification</strong> (predict a category — spam or not) and <strong>regression</strong> (predict a number — tomorrow's temperature)." },

    { t: "h", text: "Stage 5 — Evaluation" },
    { t: "p", html: "Finally you check how good the model is by testing it on <strong>new data it has never seen</strong> — not the data it trained on. Testing on the training data would be like giving students the exact exam they practised." },
    { t: "note", kind: "trap", html: "Never judge a model only on the data it learned from. A model can memorise its training data and still fail on real, unseen data — so always evaluate on a separate test set." },

    { t: "h", text: "Doing it responsibly" },
    { t: "p", html: "Across every stage, keep <strong>ethics</strong> in mind — collect data with consent (privacy), check for <strong>bias</strong>, and aim to do good. Many AI projects are framed around the UN's <strong>Sustainable Development Goals (SDGs)</strong>, such as good health, quality education or clean water." },
  ],
  examFocus: [
    "The five stages in order (S-A-E-M-E).",
    "The 4Ws Problem Canvas — Who, What, Where, Why (not When/How).",
    "Why data must be relevant, reliable and unbiased.",
    "Rule-based vs learning-based modelling.",
    "Supervised vs unsupervised learning, with examples.",
    "Why a model is evaluated on new (unseen) data, not training data.",
  ],
  flashcards: [
    { q: "List the five stages of the AI Project Cycle in order.", a: "Problem Scoping → Data Acquisition → Data Exploration → Modelling → Evaluation." },
    { q: "What are the 4Ws of the Problem Canvas?", a: "Who (is affected), What (is the problem and its evidence), Where (the context), and Why (the benefit of solving it)." },
    { q: "What happens in the Problem Scoping stage?", a: "You clearly define the problem to be solved, usually using the 4Ws Problem Canvas, ending in a single problem statement." },
    { q: "What is Data Acquisition?", a: "Collecting the relevant, reliable and sufficient data needed for the project, from sources like surveys, sensors, records or public datasets." },
    { q: "What are 'features' in a dataset?", a: "The individual pieces of input information used to make a prediction, e.g. day of week, weather, or number of students present." },
    { q: "Why do we do Data Exploration?", a: "To visualise the data (graphs/charts) and find patterns, trends and errors before building a model, so we choose the right features." },
    { q: "Difference between rule-based and learning-based approaches?", a: "In rule-based, a human writes fixed rules; in learning-based, the machine learns the rules from data and improves with more of it (this is Machine Learning)." },
    { q: "Difference between supervised and unsupervised learning?", a: "Supervised learning trains on labelled data to predict a label; unsupervised learning uses unlabelled data to find groups or patterns itself." },
    { q: "What are classification and regression?", a: "Two kinds of supervised learning: classification predicts a category (spam/not-spam), regression predicts a number (tomorrow's temperature)." },
    { q: "Why must a model be tested on new, unseen data?", a: "Because a model can memorise its training data and still fail on real data; testing on separate data shows how well it truly generalises." },
    { q: "Give one reason data quality matters in AI.", a: "Biased or unreliable data leads to biased or wrong predictions — 'garbage in, garbage out'; data must be relevant and representative." },
    { q: "What are the SDGs in the context of AI?", a: "The UN Sustainable Development Goals — global goals (health, education, clean water, etc.) that many ethical AI projects aim to support." },
  ],
  quiz: [
    { q: "What is the correct order of the AI Project Cycle?", options: ["Data → Modelling → Scoping → Evaluation", "Problem Scoping → Data Acquisition → Data Exploration → Modelling → Evaluation", "Modelling → Evaluation → Data → Scoping", "Evaluation → Modelling → Scoping → Data"], answer: 1, why: "The cycle runs Scoping → Acquisition → Exploration → Modelling → Evaluation (S-A-E-M-E)." },
    { q: "The 4Ws Problem Canvas consists of:", options: ["Who, What, When, Why", "Who, What, Where, Why", "What, Where, When, How", "Who, Where, When, How"], answer: 1, why: "The four are Who, What, Where and Why — not When or How." },
    { q: "In the 4Ws, identifying who is affected by the problem is the:", options: ["What", "Where", "Who", "Why"], answer: 2, why: "'Who' identifies the stakeholders affected by the problem." },
    { q: "Collecting reliable, relevant data for the project happens in which stage?", options: ["Problem Scoping", "Data Acquisition", "Modelling", "Evaluation"], answer: 1, why: "Gathering the data is the Data Acquisition stage." },
    { q: "Visualising data with graphs to find patterns is part of:", options: ["Data Exploration", "Modelling", "Problem Scoping", "Evaluation"], answer: 0, why: "Exploring and visualising the data to spot patterns is Data Exploration." },
    { q: "Which is a learning-based (not rule-based) approach?", options: ["If temperature > 38°C, show 'fever'", "A machine learning to recognise cats from thousands of photos", "A fixed list of banned words", "A timer switching off a fan"], answer: 1, why: "Learning from many examples is a learning-based (Machine Learning) approach; the others are fixed human-written rules." },
    { q: "Sorting emails into 'spam' and 'not spam' using labelled examples is:", options: ["Unsupervised learning", "Supervised learning", "Rule-based only", "Data exploration"], answer: 1, why: "Training on labelled data to predict a label is supervised learning (specifically classification)." },
    { q: "Grouping customers into similar types without any labels is:", options: ["Supervised learning", "Regression", "Unsupervised learning", "Evaluation"], answer: 2, why: "Finding groups in unlabelled data is unsupervised learning (clustering)." },
    { q: "Predicting tomorrow's temperature (a number) is an example of:", options: ["Classification", "Regression", "Clustering", "Scoping"], answer: 1, why: "Predicting a continuous number is regression, a type of supervised learning." },
    { q: "A model should be evaluated using:", options: ["The same data it was trained on", "New data it has not seen before", "No data at all", "Only the problem statement"], answer: 1, why: "Testing on new, unseen data shows whether the model truly generalises rather than just memorising." },
  ],
  keyTopics: [
    { name: "The five stages in order", importance: "high", note: "List/sequence questions are very common — memorise S-A-E-M-E." },
    { name: "4Ws Problem Canvas", importance: "high", note: "Name the 4Ws and apply them to a given scenario; don't add When/How." },
    { name: "Supervised vs unsupervised learning", importance: "high", note: "Define both with examples; know classification vs regression." },
    { name: "Rule-based vs learning-based modelling", importance: "medium", note: "Distinguish with an example of each." },
    { name: "Data Acquisition & quality", importance: "medium", note: "Relevant, reliable, unbiased data; features and sources." },
    { name: "Why evaluate on unseen data", importance: "medium", note: "Training-data-only testing overstates performance." },
  ],
  written: [
    { q: "List the five stages of the AI Project Cycle in the correct order.", marks: 1, kind: "short", importance: "high",
      answer: "Problem Scoping → Data Acquisition → Data Exploration → Modelling → Evaluation." },
    { q: "What are the 4Ws of the Problem Canvas?", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Who</strong> (is affected), <strong>What</strong> (is the problem and its evidence), <strong>Where</strong> (the context/situation) and <strong>Why</strong> (the benefit of solving it)." },
    { q: "Differentiate between supervised and unsupervised learning, with one example each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Supervised learning</strong> uses <em>labelled</em> data (the answers are given) to learn to predict a label — e.g. classifying emails as spam / not-spam.<br><strong>Unsupervised learning</strong> uses <em>unlabelled</em> data and finds groups or patterns itself — e.g. grouping customers into similar types." },
    { q: "Differentiate between a rule-based and a learning-based approach to modelling.", marks: 2, kind: "short", importance: "medium",
      answer: "In a <strong>rule-based</strong> approach a human writes fixed rules that the machine follows, and they don't change on their own. In a <strong>learning-based</strong> approach the machine <strong>learns the rules from data</strong> and improves as it sees more — this is Machine Learning, needed for complex problems like images or language." },
    { q: "Apply the 4Ws Problem Canvas to this situation: a hospital's waiting room is always overcrowded in the mornings.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>Who:</strong> patients waiting and the hospital staff.<br><strong>What:</strong> the waiting room is overcrowded, seen from long waiting times and full seating in the mornings.<br><strong>Where:</strong> the out-patient waiting area, during morning hours.<br><strong>Why:</strong> solving it reduces patient discomfort and helps staff manage the crowd, e.g. by predicting busy times and spreading appointments." },
    { q: "Why is a model evaluated on new (unseen) data rather than the data it was trained on?", marks: 2, kind: "short", importance: "medium",
      answer: "Because a model can simply <strong>memorise</strong> its training data and score well on it while failing on real cases. Testing on separate, unseen data shows whether the model has truly <strong>learned to generalise</strong> — like judging students on a fresh exam, not the exact questions they practised." },
    { q: "Explain the five stages of the AI Project Cycle with a one-line description of each.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>1. Problem Scoping</strong> — define the problem clearly (using the 4Ws) and write a problem statement.<br><strong>2. Data Acquisition</strong> — gather relevant, reliable and sufficient data from suitable sources.<br><strong>3. Data Exploration</strong> — visualise the data to find patterns, trends and errors, and pick useful features.<br><strong>4. Modelling</strong> — build the model (rule-based or learning-based; supervised or unsupervised) that makes predictions.<br><strong>5. Evaluation</strong> — test the model on new, unseen data to measure how well it really performs." },
    { q: "Why must the data collected for an AI project be reliable and unbiased? Explain with an example.", marks: 3, kind: "long", importance: "medium",
      answer: "An AI model learns entirely from its data, so poor data leads to poor decisions — <strong>“garbage in, garbage out.”</strong> If the data is biased or one-sided, the model becomes biased too.<br><strong>Example:</strong> if a disease-detection model is trained only on adults, it may fail on children. Using <strong>relevant, representative and accurate</strong> data keeps the model fair and correct." },
  ],
  assertionReason: [
    { assertion: "Problem Scoping is the first stage of the AI Project Cycle.",
      reason: "You must clearly understand and define a problem before collecting data or building a model for it.",
      answer: 0, importance: "high",
      why: "Both are true and R is the correct reason — scoping the problem first ensures the rest of the project is aimed correctly." },
    { assertion: "Unsupervised learning finds patterns or groups in unlabelled data.",
      reason: "In unsupervised learning, the machine is given the correct answers (labels) during training.",
      answer: 2, importance: "high",
      why: "A is true — unsupervised learning works on unlabelled data to find groups/patterns. R is false: it is <em>supervised</em> learning that uses labelled answers, not unsupervised." },
    { assertion: "An AI model should be tested on data it has never seen before.",
      reason: "Testing only on training data can make a model look better than it really is.",
      answer: 0, importance: "medium",
      why: "Both true and R explains A: evaluating on unseen data reveals real performance, because a model may just memorise its training data." },
  ],
  caseStudies: [
    { title: "Scoping a real project", importance: "high",
      source: "A town's residents complain that the public buses are unpredictable — sometimes three arrive together, then none for an hour. The transport office has GPS records from every bus and wants to use AI to predict arrival times more accurately.",
      parts: [
        { q: "Write the 'Who' and 'What' of the 4Ws for this problem.", marks: 2, answer: "<strong>Who:</strong> the town's bus passengers (and the transport office). <strong>What:</strong> bus arrival times are unpredictable/bunched, shown by passenger complaints and the erratic GPS timing records." },
        { q: "Which type of data has already been acquired, and name one useful feature in it.", marks: 1, answer: "GPS records from the buses. A useful feature: each bus's location and timestamp (also time of day, route, traffic)." },
        { q: "Would predicting a bus's arrival time (a number) be classification or regression? Why?", marks: 1, answer: "<strong>Regression</strong> — because the output is a continuous number (minutes until arrival), not a category." },
      ] },
  ],
};
