import type { Chapter } from "@/lib/types";

export const ch03: Chapter = {
  slug: "advanced-modelling",
  num: 3,
  title: "Advanced Concepts of Modelling in AI",
  unit: "modelling",
  unitName: "Advanced Concepts of Modelling, Data & Python",
  marks: "Part B · Modelling",
  minutes: 20,
  blurb: "A deeper look at how AI models are built — the three flavours of learning-based modelling, and the neural networks that power deep learning.",
  bigIdea: "Modelling is just choosing the right way for a machine to learn a pattern — from labelled examples, from unlabelled data, or by trial and error — and neural networks are simply one powerful way to do that learning.",
  syllabus: [
    "Rule-based vs Learning-based approach (recap)",
    "Types of learning-based models — Supervised, Unsupervised, Reinforcement",
    "Supervised learning — Classification and Regression",
    "Unsupervised learning — Clustering and Dimensionality Reduction",
    "Reinforcement Learning — agent, environment, reward",
    "Neural Networks — neurons, input/hidden/output layers",
    "Why it is called 'Deep' Learning",
  ],
  blocks: [
    { t: "h", text: "Recap — rule-based vs learning-based" },
    { t: "p", html: "A model is the part of an AI system that actually makes the prediction. There are two broad ways to build one: write the rules yourself, or let the machine learn the rules from data." },
    { t: "compare",
      left: { title: "Rule-based approach", items: [
        "A human writes every rule by hand",
        "The rules never change on their own",
        "Works only for simple, well-defined problems",
        "Example: 'if attendance < 75%, mark as defaulter'",
      ] },
      right: { title: "Learning-based approach", items: [
        "The machine learns the rules from data",
        "It improves as it is shown more data",
        "Needed for complex problems — images, language, behaviour",
        "This is Machine Learning",
      ] } },
    { t: "note", kind: "memory", title: "This chapter is all about the right side", html: "Everything below — supervised, unsupervised, reinforcement and neural networks — is a different way of doing the <strong>learning-based</strong> approach." },

    { t: "h", text: "Three ways a machine can learn" },
    { t: "p", html: "Learning-based models are split by <strong>what data they get</strong> and <strong>how they learn from it</strong>." },
    { t: "table", head: ["Type", "What the data looks like", "What it learns to do", "Example"], rows: [
      ["Supervised learning", "Labelled — every example has the correct answer attached", "Predict the label for new, unseen inputs", "Given past emails marked spam/not-spam, classify a new email"],
      ["Unsupervised learning", "Unlabelled — no correct answers given", "Find hidden structure, groups or patterns on its own", "Group customers into similar types from their shopping habits"],
      ["Reinforcement learning", "No fixed dataset — the agent generates its own experience", "Learn the best action by trial and error, guided by rewards", "A robot learning to walk by being 'rewarded' each time it stays upright"],
    ] },
    { t: "note", kind: "memory", html: "Quick test to tell them apart: <strong>Are there labels?</strong> Yes → supervised. No, but there's data to group → unsupervised. No dataset at all, just trial-and-error with feedback → reinforcement." },

    { t: "h", text: "Supervised learning — classification and regression" },
    { t: "p", html: "Supervised learning always predicts something, using labelled training data. What it predicts decides which of the two sub-types it is." },
    { t: "table", head: ["Sub-type", "Predicts…", "Example"], rows: [
      ["Classification", "A category / class (a discrete label)", "Spam or not-spam; pass or fail; cat, dog or rabbit"],
      ["Regression", "A number (a continuous value)", "Tomorrow's temperature; a house's price; a student's marks"],
    ] },
    { t: "note", kind: "trap", html: "A common slip: predicting 'high / medium / low' risk is still <strong>classification</strong> (categories), even though it sounds like a measurement. If the output is a <em>number on a scale</em>, it's regression; if it's a <em>label/category</em>, it's classification." },

    { t: "h", text: "Unsupervised learning — clustering and dimensionality reduction" },
    { t: "p", html: "Unsupervised learning is given data with <strong>no correct answers</strong>. It has to make sense of the data by itself." },
    { t: "list", items: [
      "<strong>Clustering</strong> — group similar data points together without being told the groups in advance. Example: grouping shoppers into 'budget', 'regular' and 'premium' buyers based on spending patterns, without anyone labelling them first.",
      "<strong>Dimensionality reduction</strong> — a dataset can have too many features (columns) to handle easily; this technique <em>compresses</em> the data down to the few features that matter most, while keeping most of the useful information. Example: reducing hundreds of pixel values in a photo down to a handful of key measurements before feeding it to a model.",
    ] },
    { t: "note", kind: "why", title: "Why bother reducing dimensions?", html: "Fewer, more meaningful features make a model <strong>faster to train, easier to visualise, and less likely to get confused by irrelevant data</strong> — without throwing away what matters." },

    { t: "h", text: "Reinforcement learning" },
    { t: "p", html: "Reinforcement learning (RL) is different from the other two — there is no ready-made dataset. Instead, an <strong>agent</strong> interacts with an <strong>environment</strong>, tries actions, and learns from the <strong>rewards</strong> or <strong>penalties</strong> it receives." },
    { t: "steps", title: "The RL loop", steps: [
      "The <strong>agent</strong> observes the current situation (state) of the <strong>environment</strong>.",
      "It chooses an <strong>action</strong> to take.",
      "The environment responds with a new state and a <strong>reward</strong> (positive) or <strong>penalty</strong> (negative).",
      "The agent adjusts its behaviour to get more reward next time — and the loop repeats, millions of times.",
    ] },
    { t: "note", kind: "real", html: "Classic examples: a game-playing AI that learns by playing itself over and over (rewarded for winning), a robot that learns to walk (rewarded for staying balanced), or a self-driving car learning to drive smoothly (penalised for harsh braking)." },

    { t: "h", text: "Neural networks — the engine behind deep learning" },
    { t: "p", html: "An <strong>Artificial Neural Network (ANN)</strong> is a learning-based model loosely inspired by the neurons in a human brain. It is made of simple units called <strong>neurons</strong>, arranged in <strong>layers</strong>." },
    { t: "list", ordered: true, items: [
      "<strong>Input layer</strong> — receives the raw data (e.g. each pixel of an image, or each feature of a record).",
      "<strong>Hidden layer(s)</strong> — one or more layers in between that combine and transform the inputs, gradually learning more complex patterns at each layer.",
      "<strong>Output layer</strong> — produces the final answer (e.g. 'cat' or 'dog', or a predicted number).",
    ] },
    { t: "p", html: "Each neuron takes in values from the previous layer, multiplies them by learned <strong>weights</strong>, adds them up, and passes the result on — this is how the network gradually learns which inputs matter most." },
    { t: "note", kind: "exam", title: "Why is it called 'Deep' Learning?", html: "A neural network with <strong>many hidden layers</strong> (not just one) is called a <strong>deep neural network</strong> — and learning using such networks is <strong>Deep Learning</strong>. More hidden layers let the network learn more complex, abstract patterns, layer by layer." },
    { t: "note", kind: "idea", html: "A <strong>Convolutional Neural Network (CNN)</strong> is a special type of deep neural network built especially for images — it is the workhorse behind most Computer Vision tasks like face recognition and object detection." },

    { t: "h", text: "Choosing the right approach" },
    { t: "table", head: ["If you have…", "…and want to…", "Use"], rows: [
      ["Labelled data with categories to predict", "Sort new items into known categories", "Supervised — classification"],
      ["Labelled data with a number to predict", "Forecast a continuous value", "Supervised — regression"],
      ["Unlabelled data", "Discover natural groups or reduce noisy features", "Unsupervised — clustering / dimensionality reduction"],
      ["No dataset, but an environment to act in", "Learn the best strategy through trial and error", "Reinforcement learning"],
      ["Very complex patterns (images, speech, language)", "Learn deep, layered representations", "Neural networks / Deep Learning"],
    ] },
    { t: "note", kind: "trap", html: "Don't assume neural networks are a fourth type of learning — they are usually trained <strong>using</strong> supervised (or sometimes unsupervised/reinforcement) learning; they're a <em>model architecture</em>, not a separate learning category." },
  ],
  examFocus: [
    "Rule-based vs learning-based, with an example of each.",
    "Supervised vs unsupervised vs reinforcement learning — the labels/data test.",
    "Classification vs regression, with the 'category vs number' distinction.",
    "Clustering vs dimensionality reduction, with an example each.",
    "The reinforcement learning loop — agent, environment, action, reward.",
    "Neural network structure — input, hidden, output layers — and why 'deep' means many hidden layers.",
  ],
  flashcards: [
    { q: "What is the key difference between rule-based and learning-based modelling?", a: "In rule-based, a human writes fixed rules. In learning-based, the machine learns the rules itself from data and improves with more of it." },
    { q: "Name the three types of learning-based models.", a: "Supervised learning, Unsupervised learning, and Reinforcement learning." },
    { q: "What kind of data does supervised learning need?", a: "Labelled data — every training example already has the correct answer (label) attached." },
    { q: "Difference between classification and regression?", a: "Classification predicts a category/class (e.g. spam or not-spam); regression predicts a continuous number (e.g. tomorrow's temperature)." },
    { q: "What is clustering?", a: "An unsupervised technique that groups similar, unlabelled data points together without being told the groups in advance, e.g. grouping customers by shopping behaviour." },
    { q: "What is dimensionality reduction, and why use it?", a: "A technique that reduces the number of features in a dataset to the most important few, keeping the useful information while making the model faster and less confused by noise." },
    { q: "What is reinforcement learning?", a: "A type of learning where an agent interacts with an environment, takes actions, and learns the best behaviour through rewards and penalties, instead of a fixed labelled dataset." },
    { q: "Name the four parts of the reinforcement learning loop.", a: "Agent, environment, action, and reward (or penalty)." },
    { q: "What is a neural network, in one line?", a: "A learning-based model made of simple units (neurons) arranged in layers, loosely inspired by the human brain, that learns by adjusting weights." },
    { q: "Name the three types of layers in a neural network.", a: "Input layer, one or more hidden layers, and the output layer." },
    { q: "Why is it called 'Deep' Learning?", a: "Because the neural network has many hidden layers (not just one), letting it learn increasingly complex, layered patterns." },
    { q: "What is a CNN used for?", a: "A Convolutional Neural Network is a deep neural network specialised for images, widely used in Computer Vision tasks like face and object recognition." },
  ],
  quiz: [
    { q: "In a rule-based model, the rules are:", options: ["Learned automatically from data", "Written by a human and fixed", "Generated randomly", "Rewarded by an environment"], answer: 1, why: "Rule-based models follow fixed rules written by a human; they don't change on their own." },
    { q: "Which type of learning uses labelled data to predict an outcome?", options: ["Unsupervised learning", "Reinforcement learning", "Supervised learning", "Rule-based learning"], answer: 2, why: "Supervised learning trains on labelled data (inputs with known correct answers) to predict labels for new data." },
    { q: "Predicting whether a tumour is 'benign' or 'malignant' is an example of:", options: ["Regression", "Classification", "Clustering", "Reinforcement learning"], answer: 1, why: "The output is a category (benign/malignant), so this is classification, a type of supervised learning." },
    { q: "Predicting a car's resale price in rupees is an example of:", options: ["Classification", "Clustering", "Regression", "Dimensionality reduction"], answer: 2, why: "The output is a continuous number (price), which makes this a regression problem." },
    { q: "Grouping news articles into topics without being told the topics in advance is:", options: ["Classification", "Regression", "Clustering", "Reinforcement learning"], answer: 2, why: "Finding natural groups in unlabelled data is clustering, an unsupervised technique." },
    { q: "Reducing hundreds of image pixel features down to the few that matter most, before training a model, is called:", options: ["Regression", "Dimensionality reduction", "Classification", "Reward shaping"], answer: 1, why: "Compressing many features into the most useful few, while keeping the important information, is dimensionality reduction." },
    { q: "In reinforcement learning, an agent improves its behaviour mainly by:", options: ["Being given labelled examples", "Receiving rewards and penalties from the environment", "Reducing the number of features", "Following rules a programmer wrote", ], answer: 1, why: "Reinforcement learning is trial-and-error learning driven by rewards and penalties from the environment, not labelled data." },
    { q: "In a neural network, the layer that receives the raw data is the:", options: ["Output layer", "Hidden layer", "Input layer", "Reward layer"], answer: 2, why: "The input layer is where the raw data (e.g. pixels or features) enters the network." },
    { q: "A neural network is called 'deep' when it has:", options: ["Many hidden layers", "Only an input and output layer", "No neurons", "A single training example"], answer: 0, why: "Deep learning refers to neural networks with many hidden layers, allowing more complex pattern learning." },
    { q: "Which model type is best suited for recognising objects in photographs?", options: ["A simple rule-based if-else system", "A Convolutional Neural Network (CNN)", "Basic clustering", "A fixed lookup table"], answer: 1, why: "CNNs are deep neural networks specialised for image data, making them ideal for object recognition in Computer Vision." },
  ],
  keyTopics: [
    { name: "Rule-based vs learning-based (recap)", importance: "medium", note: "Quick 1–2 mark distinguish-with-example question." },
    { name: "Supervised, unsupervised, reinforcement learning", importance: "high", note: "Define all three and classify a given scenario into one of them." },
    { name: "Classification vs regression", importance: "high", note: "Category vs number — classify a given example correctly." },
    { name: "Clustering vs dimensionality reduction", importance: "medium", note: "Both are unsupervised but do different jobs; give an example of each." },
    { name: "Reinforcement learning loop", importance: "medium", note: "Name agent, environment, action, reward; give a real example." },
    { name: "Neural networks and 'deep' learning", importance: "high", note: "Layers (input/hidden/output) and why many hidden layers = deep learning." },
  ],
  written: [
    { q: "Differentiate between rule-based and learning-based approaches to modelling.", marks: 2, kind: "short", importance: "medium",
      answer: "In a <strong>rule-based</strong> approach, a human writes fixed rules that the machine follows and which do not change on their own. In a <strong>learning-based</strong> approach, the machine <strong>learns the rules from data</strong> and keeps improving as it sees more data — this is Machine Learning, needed for complex problems." },
    { q: "What is supervised learning? Name its two sub-types.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Supervised learning</strong> is a type of learning-based modelling where the machine is trained on <em>labelled</em> data (every example has the correct answer attached) to predict the label for new data. Its two sub-types are <strong>Classification</strong> (predicts a category) and <strong>Regression</strong> (predicts a number)." },
    { q: "Differentiate between classification and regression, with one example each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Classification</strong> predicts a discrete category or class, e.g. classifying an email as spam or not-spam. <strong>Regression</strong> predicts a continuous numeric value, e.g. predicting tomorrow's temperature." },
    { q: "What is unsupervised learning? Explain clustering with an example.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Unsupervised learning</strong> works on <em>unlabelled</em> data — there are no correct answers given — and the machine finds structure in the data by itself.<br><strong>Clustering</strong> is one such technique: it groups similar data points together without being told the groups in advance. Example: an online store grouping its customers into 'budget', 'regular' and 'premium' buyers based on spending patterns, without any predefined labels." },
    { q: "What is dimensionality reduction? Why is it useful?", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Dimensionality reduction</strong> is an unsupervised technique that reduces the number of features (columns) in a dataset to the few that matter most, while keeping most of the useful information.<br>It is useful because fewer, more meaningful features make a model <strong>faster to train and less likely to be confused</strong> by irrelevant or noisy data." },
    { q: "Explain reinforcement learning with the help of a suitable example.", marks: 3, kind: "long", importance: "high",
      answer: "In <strong>reinforcement learning</strong>, there is no fixed labelled dataset. Instead, an <strong>agent</strong> interacts with an <strong>environment</strong>: it observes the current state, takes an <strong>action</strong>, and receives a <strong>reward</strong> (or penalty) based on the result. Over many repeated attempts, the agent learns which actions lead to more reward.<br><strong>Example:</strong> a robot learning to walk is rewarded for each step it takes while staying balanced, and penalised if it falls — over time it learns a walking strategy purely from this trial-and-error feedback." },
    { q: "Describe the basic structure of an Artificial Neural Network.", marks: 3, kind: "long", importance: "high",
      answer: "An <strong>Artificial Neural Network (ANN)</strong> is made of simple units called <strong>neurons</strong>, organised into layers:<br>• The <strong>input layer</strong> receives the raw data (e.g. pixels of an image or features of a record).<br>• One or more <strong>hidden layers</strong> combine and transform this data, learning increasingly complex patterns.<br>• The <strong>output layer</strong> produces the final result, such as a predicted label or number.<br>Each neuron combines its inputs using learned <strong>weights</strong> and passes the result to the next layer." },
    { q: "Why is a neural network with many hidden layers called 'Deep Learning'? What advantage do extra layers give?", marks: 3, kind: "long", importance: "high",
      answer: "A neural network with <strong>only one or no hidden layer</strong> is a simple/shallow network, but one with <strong>many hidden layers</strong> is called a <strong>deep neural network</strong> — and learning using such a network is called <strong>Deep Learning</strong>.<br>Extra hidden layers let the network build up understanding <strong>layer by layer</strong> — early layers learn simple patterns (like edges in an image), and later layers combine these into more complex, abstract concepts (like recognising a whole face) — which lets deep networks handle far more complex tasks than a shallow one." },
    { q: "A hospital wants an AI system to (a) predict whether a scan shows a tumour or not, and (b) group patients into risk categories it discovers on its own from their health records. Identify the type of learning used in each case, with reasons.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>(a)</strong> Predicting tumour / no tumour from labelled past scans is <strong>supervised learning — classification</strong>, since the output is a known category and the training data has correct answers attached.<br><strong>(b)</strong> Grouping patients into risk categories that are not predefined, purely from patterns in their records, is <strong>unsupervised learning — clustering</strong>, since there are no labels and the machine discovers the groups itself." },
  ],
  assertionReason: [
    { assertion: "A model that predicts tomorrow's rainfall in millimetres is doing regression.",
      reason: "Regression is used when the predicted output is a continuous numeric value rather than a category.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why: rainfall in millimetres is a continuous number, which is exactly what regression predicts." },
    { assertion: "Clustering is a type of supervised learning.",
      reason: "Clustering groups unlabelled data into similar groups without being given the correct answers beforehand.",
      answer: 3, importance: "high",
      why: "A is false — clustering is unsupervised, not supervised, because it works on unlabelled data. R is true and correctly describes clustering." },
    { assertion: "In reinforcement learning, the agent needs a large labelled dataset before it can start learning.",
      reason: "Reinforcement learning agents learn through rewards and penalties received by interacting with an environment, not from pre-labelled examples.",
      answer: 3, importance: "medium",
      why: "A is false — reinforcement learning does not require a pre-labelled dataset. R is true and correctly explains why: the agent learns from trial-and-error feedback (rewards/penalties), not labelled data." },
    { assertion: "A neural network with several hidden layers can learn more complex patterns than one with a single hidden layer.",
      reason: "Extra hidden layers allow the network to build up understanding from simple to more abstract patterns, layer by layer.",
      answer: 0, importance: "medium",
      why: "Both are true, and R correctly explains A — more hidden layers let the network progressively combine simple patterns into complex, abstract ones, which is the basis of Deep Learning." },
  ],
  caseStudies: [
    { title: "Choosing the right modelling approach", importance: "high",
      source: "A school library has thousands of past borrowing records (student, book genre, date, whether returned late) and wants to build two AI features: (1) predict whether a given student will return a borrowed book late or on time, and (2) automatically discover natural groups of readers with similar borrowing habits, without deciding the groups in advance.",
      parts: [
        { q: "Which type of learning is best suited to feature (1), and why?", marks: 2, answer: "<strong>Supervised learning — classification</strong>. Past records already show whether a book was returned late or on time (a label), so the model can learn from these labelled examples to predict the category (late / on time) for a new borrowing." },
        { q: "Which type of learning is best suited to feature (2), and why?", marks: 2, answer: "<strong>Unsupervised learning — clustering</strong>. There are no predefined reader-group labels; the system must find natural groupings in the unlabelled borrowing data by itself." },
        { q: "If the library later wants an AI 'reading assistant' robot that learns, through trial and error, the best times to send return-reminders to maximise on-time returns, which approach fits best?", marks: 1, answer: "<strong>Reinforcement learning</strong> — the assistant would try different reminder timings (actions), receive feedback (reward when a book comes back on time), and gradually learn the best strategy." },
      ] },
    { title: "Reading a neural network diagram", importance: "medium",
      source: "A neural network is being built to recognise handwritten digits (0–9) from 28×28 pixel images. It has one layer that takes in all 784 pixel values, three layers in between that process the data, and a final layer with 10 outputs, one for each digit.",
      parts: [
        { q: "Name the three types of layers present in this network.", marks: 2, answer: "Input layer (784 pixel values), hidden layers (the three layers in between), and output layer (10 outputs, one per digit)." },
        { q: "Would this network be called a 'deep' neural network? Justify your answer.", marks: 1, answer: "Yes — it has <strong>multiple (three) hidden layers</strong>, which is what makes a neural network 'deep'." },
      ] },
  ],
};
