import type { Chapter } from "@/lib/types";

export const ch04: Chapter = {
  slug: "statistical-data",
  num: 4,
  title: "Statistical Data",
  unit: "modelling",
  unitName: "Advanced Concepts of Modelling, Data & Python",
  marks: "Part B · Modelling",
  minutes: 18,
  blurb: "How AI makes sense of numbers — types of data, the three measures of central tendency, spread, and picking the right chart to show a pattern.",
  bigIdea: "Before a machine can learn from data, a human has to understand it first — and statistics is simply the toolkit for summarising a pile of numbers into a few meaningful facts.",
  syllabus: [
    "Importance of Statistics in AI",
    "Types of data — Qualitative vs Quantitative, Discrete vs Continuous",
    "Measures of Central Tendency — Mean, Median, Mode",
    "Range",
    "Data Visualisation — Bar graph, Line graph, Pie chart, Scatter plot",
  ],
  blocks: [
    { t: "h", text: "Why does AI need statistics?" },
    { t: "p", html: "Every AI model is trained on data, and data on its own is just a pile of numbers. <strong>Statistics</strong> is the toolkit that turns that pile into a few meaningful facts — an average, a typical value, how spread out things are — which is exactly what a model needs before it can start finding patterns." },
    { t: "note", kind: "idea", html: "Statistics is used at almost every stage of the AI Project Cycle — to explore data (Data Exploration) and to check how well a model performed (Evaluation)." },

    { t: "h", text: "Types of data" },
    { t: "p", html: "Before summarising data, you need to know what kind it is. Data splits along two separate lines." },
    { t: "table", head: ["Split", "Type", "Meaning", "Example"], rows: [
      ["By nature", "Qualitative (categorical)", "Describes a quality — cannot be measured in numbers", "Favourite colour, blood group, pass/fail"],
      ["By nature", "Quantitative (numerical)", "Can be measured or counted as numbers", "Height, marks, number of siblings"],
      ["Within quantitative", "Discrete", "Countable — takes whole, separate values only", "Number of students in a class (can't be 23.5)"],
      ["Within quantitative", "Continuous", "Measurable — can take any value in a range", "Height, temperature, weight"],
    ] },
    { t: "note", kind: "trap", html: "A number does not automatically make data quantitative in the useful sense — a <strong>pin code</strong> or <strong>roll number</strong> is a number but is really used as a label (qualitative), since you would never 'average' two roll numbers." },

    { t: "h", text: "Measures of central tendency — mean, median, mode" },
    { t: "p", html: "These three numbers each try to answer the same question in a different way: <em>“What is a typical value in this data?”</em>" },
    { t: "list", items: [
      "<strong>Mean</strong> — the arithmetic average: add up all the values and divide by how many there are.",
      "<strong>Median</strong> — the middle value once the data is sorted in order (average of the two middle values if there is an even number of values).",
      "<strong>Mode</strong> — the value that occurs most often in the data.",
    ] },
    { t: "steps", title: "Worked example — shoe sizes of 9 students", intro: "Sizes recorded: 6, 7, 7, 8, 8, 8, 9, 9, 10 (already sorted, n = 9).", steps: [
      "<strong>Mean</strong> = (6+7+7+8+8+8+9+9+10) ÷ 9 = 72 ÷ 9 = <strong>8</strong>",
      "<strong>Median</strong> = the middle (5th) value in the sorted list of 9 = <strong>8</strong>",
      "<strong>Mode</strong> = the most frequent value = <strong>8</strong> (it appears 3 times)",
    ], answer: "Here mean = median = mode = 8, because the data is fairly symmetric around 8. This won't always happen — but when it does, it's a sign the data has no strong skew." },
    { t: "note", kind: "trap", title: "Median with an even number of values", html: "If there is an <strong>even</strong> number of values, sort them and average the two middle ones. Example: test scores 12, 15, 18, 20 (n = 4) → median = (15 + 18) ÷ 2 = <strong>16.5</strong>." },
    { t: "note", kind: "why", html: "The mean can be pulled by extreme values (outliers), while the median cannot. Example: incomes of ₹20,000, ₹22,000, ₹21,000 and ₹9,00,000 — the mean looks huge because of one outlier, but the median stays close to the typical income." },

    { t: "h", text: "Range — how spread out is the data?" },
    { t: "p", html: "The <strong>range</strong> measures how spread out a dataset is: <code>Range = Highest value − Lowest value</code>." },
    { t: "p", html: "For the shoe-size example above: Range = 10 − 6 = <strong>4</strong>. A small range means the values are close together; a large range means they're spread far apart." },

    { t: "h", text: "Data visualisation — telling the story" },
    { t: "p", html: "Rows of numbers are hard to read at a glance, so during Data Exploration we draw <strong>graphs</strong> to spot patterns quickly. Different charts suit different kinds of comparison." },
    { t: "table", head: ["Chart", "Best for", "Example"], rows: [
      ["Bar graph", "Comparing values across separate categories", "Number of students choosing each subject"],
      ["Line graph", "Showing a trend over time (continuous change)", "Temperature recorded every hour through the day"],
      ["Pie chart", "Showing each category's share of a whole (parts of 100%)", "Percentage of a school's students in each house"],
      ["Scatter plot", "Showing the relationship between two numeric variables", "Hours studied vs marks scored, for many students"],
    ] },
    { t: "note", kind: "exam", html: "A frequent question: “Which graph would you use to show X, and why?” Match the chart to the goal — <strong>categories → bar</strong>, <strong>trend over time → line</strong>, <strong>share of a whole → pie</strong>, <strong>relationship between two numbers → scatter</strong>." },
    { t: "note", kind: "memory", html: "Think of it as: bar = <em>compare</em>, line = <em>change over time</em>, pie = <em>share of the whole</em>, scatter = <em>relationship</em>." },
  ],
  examFocus: [
    "Why statistics matters for AI (summarising data before modelling).",
    "Qualitative vs quantitative, and discrete vs continuous data, with examples.",
    "Calculating mean, median and mode from a small dataset (including even-n median).",
    "Range as a measure of spread.",
    "Choosing the right chart (bar/line/pie/scatter) for a given scenario.",
  ],
  flashcards: [
    { q: "Why is statistics important in AI?", a: "It summarises raw data into meaningful facts (averages, typical values, spread) that are needed before a model can find patterns, and to evaluate model performance." },
    { q: "Difference between qualitative and quantitative data?", a: "Qualitative data describes a quality and cannot be measured numerically (e.g. blood group); quantitative data can be measured or counted as numbers (e.g. height)." },
    { q: "Difference between discrete and continuous data?", a: "Discrete data is countable and takes whole, separate values (e.g. number of students); continuous data can take any value in a range (e.g. height, temperature)." },
    { q: "Define mean.", a: "The arithmetic average — the sum of all values divided by the number of values." },
    { q: "Define median.", a: "The middle value of a dataset when sorted in order; for an even number of values, it's the average of the two middle values." },
    { q: "Define mode.", a: "The value that occurs most frequently in a dataset." },
    { q: "How do you calculate the range of a dataset?", a: "Range = Highest value − Lowest value; it measures how spread out the data is." },
    { q: "Why can the mean be misleading sometimes?", a: "A few extreme values (outliers) can pull the mean up or down, while the median stays close to the typical value — so median is often more reliable for skewed data." },
    { q: "Which chart best compares values across categories?", a: "A bar graph." },
    { q: "Which chart best shows a trend over time?", a: "A line graph." },
    { q: "Which chart shows each category's share of a whole?", a: "A pie chart." },
    { q: "Which chart shows the relationship between two numeric variables?", a: "A scatter plot." },
  ],
  quiz: [
    { q: "Which of these is an example of qualitative data?", options: ["Height in cm", "Blood group", "Number of siblings", "Marks scored"], answer: 1, why: "Blood group describes a quality/category and cannot be meaningfully measured or averaged as a number." },
    { q: "The number of cars sold by a showroom each month is:", options: ["Qualitative", "Continuous", "Discrete", "Not data"], answer: 2, why: "The number of cars is countable and takes only whole values, making it discrete quantitative data." },
    { q: "Height and weight are examples of:", options: ["Qualitative data", "Discrete data", "Continuous data", "Categorical data"], answer: 2, why: "Height and weight can take any value in a range (e.g. 152.4 cm), so they are continuous data." },
    { q: "For the data 4, 6, 6, 8, 10, the mean is:", options: ["6", "6.8", "7.2", "8"], answer: 1, why: "Mean = (4+6+6+8+10) ÷ 5 = 34 ÷ 5 = 6.8." },
    { q: "For the data 3, 5, 7, 9 (already sorted), the median is:", options: ["5", "6", "7", "9"], answer: 1, why: "With an even number of values (4), median = average of the two middle values = (5+7) ÷ 2 = 6." },
    { q: "For the data 2, 3, 3, 3, 5, 8, the mode is:", options: ["2", "3", "5", "8"], answer: 1, why: "3 appears most often (three times), so it is the mode." },
    { q: "The range of the dataset 12, 45, 20, 8, 33 is:", options: ["45", "8", "37", "53"], answer: 2, why: "Range = highest − lowest = 45 − 8 = 37." },
    { q: "A shop wants to show what percentage of its total sales came from each product category. The best chart is:", options: ["Line graph", "Scatter plot", "Pie chart", "Bar graph"], answer: 2, why: "A pie chart shows how categories share a whole (100%), which fits percentage-of-total data." },
    { q: "To show how a city's temperature changed hour by hour through a day, the best chart is:", options: ["Pie chart", "Line graph", "Bar graph", "Scatter plot"], answer: 1, why: "A line graph is best for showing a trend or change over a continuous variable like time." },
    { q: "To study the relationship between hours studied and marks scored by many students, the best chart is:", options: ["Bar graph", "Pie chart", "Scatter plot", "Line graph"], answer: 2, why: "A scatter plot shows the relationship/correlation between two numeric variables." },
  ],
  keyTopics: [
    { name: "Why statistics matters in AI", importance: "medium", note: "Short conceptual 1-mark question on its role in Data Exploration/Evaluation." },
    { name: "Qualitative vs quantitative; discrete vs continuous", importance: "high", note: "Classify given examples correctly; watch for numeric labels that are really qualitative." },
    { name: "Mean, median, mode", importance: "high", note: "Small numerical questions — compute from 4–9 data points, including even-n median." },
    { name: "Range", importance: "medium", note: "Simple highest − lowest calculation." },
    { name: "Choosing the right chart", importance: "high", note: "Match bar/line/pie/scatter to a described scenario, with reasoning." },
    { name: "Mean vs median with outliers", importance: "low", note: "Explain why median resists outliers better than mean." },
  ],
  written: [
    { q: "Why is statistics considered important in Artificial Intelligence?", marks: 1, kind: "short", importance: "medium",
      answer: "Statistics helps summarise large amounts of raw data into a few meaningful facts (like averages and spread), which is essential for exploring data and evaluating how well an AI model performs." },
    { q: "Differentiate between qualitative and quantitative data, with one example each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Qualitative data</strong> describes a quality and cannot be measured numerically, e.g. <em>blood group</em>. <strong>Quantitative data</strong> can be measured or counted as numbers, e.g. <em>height in cm</em>." },
    { q: "Differentiate between discrete and continuous data, with one example each.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Discrete data</strong> is countable and takes only whole, separate values, e.g. <em>number of students in a class</em>. <strong>Continuous data</strong> can take any value in a range, e.g. <em>a person's height</em>." },
    { q: "Find the mean, median and mode of the data: 5, 7, 7, 9, 12.", marks: 3, kind: "numerical", importance: "high",
      hint: "Sort the data first, then apply each formula in turn.",
      answer: "Sorted data (n = 5): 5, 7, 7, 9, 12.<br><strong>Mean</strong> = (5+7+7+9+12) ÷ 5 = 40 ÷ 5 = <strong>8</strong>.<br><strong>Median</strong> = middle (3rd) value = <strong>7</strong>.<br><strong>Mode</strong> = most frequent value = <strong>7</strong> (appears twice)." },
    { q: "Find the median of the data: 10, 14, 18, 22 (already sorted).", marks: 1, kind: "numerical", importance: "medium",
      answer: "With n = 4 (even), median = average of the 2nd and 3rd values = (14 + 18) ÷ 2 = <strong>16</strong>." },
    { q: "Calculate the range of the following marks out of 50: 32, 45, 28, 41, 19.", marks: 1, kind: "numerical", importance: "medium",
      answer: "Range = highest − lowest = 45 − 19 = <strong>26</strong>." },
    { q: "Why might the median be a better measure of 'typical value' than the mean for a dataset with outliers? Explain with an example.", marks: 2, kind: "short", importance: "low",
      answer: "The <strong>mean</strong> is affected by every value, so one very large or small outlier can pull it far from what is 'typical'. The <strong>median</strong> only depends on the middle position, so it resists outliers.<br><strong>Example:</strong> monthly incomes ₹20,000, ₹21,000, ₹22,000 and ₹9,00,000 — the mean is skewed high by the one large income, but the median (₹22,000) reflects the typical income better." },
    { q: "A school wants to show, in one chart, what fraction of its 800 students belong to each of its four houses. Which chart should it use, and why?", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>pie chart</strong>, because it is best suited to showing how categories (the four houses) share a whole (the total 800 students) as proportions/percentages." },
    { q: "Explain, with reasons, which graph (bar, line, pie or scatter) you would use for each of the following: (a) comparing the population of five cities, (b) showing a company's profit over the last 10 years, (c) checking if there's a relationship between study hours and exam marks.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>(a) Bar graph</strong> — comparing values across separate categories (five different cities) is exactly what a bar graph is for.<br><strong>(b) Line graph</strong> — showing how a value (profit) changes continuously over time (years) is best shown with a line graph.<br><strong>(c) Scatter plot</strong> — checking for a relationship/correlation between two numeric variables (study hours and marks) is best shown with a scatter plot." },
  ],
  assertionReason: [
    { assertion: "A student's roll number is an example of quantitative data.",
      reason: "Data is truly quantitative only if arithmetic operations like averaging are meaningful on it, and identifiers such as roll numbers are just labels even though they are written using digits.",
      answer: 3, importance: "medium",
      why: "A is false — a roll number is really a label (qualitative data), even though it looks numeric, since averaging two roll numbers is meaningless. R is a true, correct statement of the general principle." },
    { assertion: "For the dataset 5, 5, 5, 5, 8, the mean is greater than the mode.",
      reason: "The single high value of 8 pulls the mean above the most frequently occurring value.",
      answer: 0, importance: "medium",
      why: "Mean = (5+5+5+5+8) ÷ 5 = 28 ÷ 5 = 5.6, and mode = 5 (the most frequent value), so mean &gt; mode — A is true. R correctly explains why: the one higher value (8) pulls the mean up above the mode." },
    { assertion: "The median is less affected by extreme outlier values than the mean.",
      reason: "The median depends only on the position of the middle value(s), while the mean depends on the sum of all values.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains A — because the mean sums every value, one outlier shifts it a lot, while the median only looks at the middle position(s)." },
    { assertion: "A line graph is the most suitable way to display which subject is most popular among students in a class.",
      reason: "A line graph is designed to show how a value changes continuously, usually over time.",
      answer: 3, importance: "medium",
      why: "A is false — comparing popularity across separate subject categories needs a bar graph, not a line graph. R is true — line graphs do show continuous change, typically over time — so the scheme is A-false, R-true." },
  ],
  caseStudies: [
    { title: "Analysing class test scores", importance: "high",
      source: "The scores (out of 20) of 7 students in a class test are: 12, 15, 15, 18, 9, 15, 20.",
      parts: [
        { q: "Sort the data and find the median.", marks: 1, answer: "Sorted: 9, 12, 15, 15, 15, 18, 20 (n = 7). Median = the 4th value = <strong>15</strong>." },
        { q: "Find the mode of the data.", marks: 1, answer: "15 occurs three times, more than any other value, so the mode is <strong>15</strong>." },
        { q: "Calculate the mean of the data (round to two decimal places).", marks: 2, answer: "Mean = (9+12+15+15+15+18+20) ÷ 7 = 104 ÷ 7 ≈ <strong>14.86</strong>." },
        { q: "Find the range of the scores.", marks: 1, answer: "Range = highest − lowest = 20 − 9 = <strong>11</strong>." },
      ] },
    { title: "Picking the right chart", importance: "medium",
      source: "A fitness app collects, for each of its 500 users: (i) their daily step count over the last 30 days, (ii) what percentage of users prefer each of four workout types, and (iii) whether there's a relationship between hours slept and next-day step count.",
      parts: [
        { q: "Which chart suits (i), and why?", marks: 1, answer: "A <strong>line graph</strong> — it best shows how step count changes day by day (a trend over time)." },
        { q: "Which chart suits (ii), and why?", marks: 1, answer: "A <strong>pie chart</strong> — it best shows each workout type's share of the whole user base as percentages." },
        { q: "Which chart suits (iii), and why?", marks: 1, answer: "A <strong>scatter plot</strong> — it best reveals whether a relationship exists between two numeric variables: hours slept and next-day steps." },
      ] },
  ],
};
