import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "advanced-python",
  num: 5,
  title: "Advanced Python",
  unit: "modelling",
  unitName: "Advanced Concepts of Modelling, Data & Python",
  marks: "Part B · Modelling",
  minutes: 18,
  blurb: "The Python building blocks behind AI work — data types, lists/tuples/dictionaries, loops and functions — plus the libraries and notebooks that data scientists actually use.",
  bigIdea: "Python is the language AI is mostly written in because it reads almost like English and comes with ready-made libraries for handling data, numbers and charts — you rarely build the maths from scratch.",
  syllabus: [
    "Why Python for AI", "Variables and Data Types",
    "Lists, Tuples and Dictionaries",
    "Conditional statements and Loops", "Functions",
    "Python libraries — NumPy, Pandas, Matplotlib",
    "Jupyter Notebook",
  ],
  blocks: [
    { t: "h", text: "Why Python for AI?" },
    { t: "p", html: "Python is the most widely used language for AI and Data Science because its syntax is simple and close to plain English, and it comes with a huge collection of ready-made <strong>libraries</strong> for maths, data handling and visualisation — so you don't have to write everything from scratch." },
    { t: "note", kind: "idea", html: "A <strong>library</strong> is a collection of pre-written code (functions and tools) that you can import and reuse, instead of coding the same logic yourself every time." },

    { t: "h", text: "Variables and data types" },
    { t: "p", html: "A <strong>variable</strong> is a named container that stores a value, e.g. <code>age = 15</code>. Python decides the <strong>data type</strong> automatically from the value you store." },
    { t: "table", head: ["Data type", "Stores…", "Example"], rows: [
      ["int", "Whole numbers", "<code>marks = 92</code>"],
      ["float", "Decimal numbers", "<code>height = 5.6</code>"],
      ["str (string)", "Text, in quotes", "<code>name = 'Aisha'</code>"],
      ["bool", "True or False", "<code>is_passed = True</code>"],
    ] },
    { t: "note", kind: "trap", html: "Python is <strong>case-sensitive</strong> and does not need you to declare a type in advance — <code>Age</code> and <code>age</code> are treated as two completely different variables." },

    { t: "h", text: "Lists, tuples and dictionaries" },
    { t: "p", html: "Beyond single values, Python has built-in structures to hold many values together — each with its own rules." },
    { t: "table", head: ["Structure", "Written as", "Can it change (mutable)?", "Best for"], rows: [
      ["List", "<code>marks = [90, 85, 76]</code>", "Yes — items can be added, removed or changed", "A collection that may need updating"],
      ["Tuple", "<code>point = (10, 20)</code>", "No — fixed once created", "Data that should stay constant, e.g. coordinates"],
      ["Dictionary", "<code>student = {'name': 'Ravi', 'age': 15}</code>", "Yes — values can be changed via their keys", "Looking up a value by a meaningful key, not a position"],
    ] },
    { t: "note", kind: "memory", html: "Lists use <strong>square brackets</strong> <code>[ ]</code>, tuples use <strong>round brackets</strong> <code>( )</code>, and dictionaries use <strong>curly brackets</strong> <code>{ }</code> with <code>key: value</code> pairs." },

    { t: "h", text: "Conditional statements and loops" },
    { t: "p", html: "<strong>Conditional statements</strong> (<code>if</code> / <code>elif</code> / <code>else</code>) let a program take different actions depending on whether a condition is true — e.g. checking if marks are enough to pass." },
    { t: "p", html: "<strong>Loops</strong> repeat a block of code instead of writing it again and again. A <code>for</code> loop repeats a fixed number of times (e.g. once for each item in a list); a <code>while</code> loop repeats as long as a condition stays true." },
    { t: "note", kind: "why", title: "Why do AI programs need loops so much?", html: "Training and processing data means repeating the same steps over thousands or millions of rows — loops (or library functions that loop internally) are what make that practical instead of writing one line per data point." },

    { t: "h", text: "Functions" },
    { t: "p", html: "A <strong>function</strong> is a named, reusable block of code that performs one task. You define it once with <code>def</code>, and then <em>call</em> it as many times as needed, optionally passing in different <strong>parameters</strong> and getting back a <strong>return</strong> value." },
    { t: "note", kind: "idea", html: "Functions avoid repeating code and make programs easier to read, test and fix — a bug only needs to be corrected in one place." },

    { t: "h", text: "Key Python libraries for AI" },
    { t: "p", html: "Most real AI/data work in Python leans on three libraries again and again." },
    { t: "table", head: ["Library", "What it's for", "Typical use"], rows: [
      ["NumPy", "Fast operations on numbers, especially arrays (grids of numbers)", "Doing maths on thousands of values at once, efficiently"],
      ["Pandas", "Loading, cleaning and analysing tabular data (rows and columns)", "Reading a CSV/Excel file into a DataFrame and exploring it"],
      ["Matplotlib", "Drawing charts and graphs", "Plotting a bar graph, line graph or scatter plot of the data"],
    ] },
    { t: "note", kind: "exam", html: "A common 1-mark question: “Which library would you use to plot a graph?” → <strong>Matplotlib</strong>. “Which library handles tabular/spreadsheet-like data?” → <strong>Pandas</strong>. “Which library is built around fast array operations?” → <strong>NumPy</strong>." },

    { t: "h", text: "Jupyter Notebook" },
    { t: "p", html: "A <strong>Jupyter Notebook</strong> is the tool most Data Science and AI work is written in. It lets you write and run Python code in small chunks called <strong>cells</strong>, see the output right below each cell, and mix in formatted text, headings and images — all in one document." },
    { t: "note", kind: "real", html: "Notebooks are usually run through a distribution like <strong>Anaconda (via Anaconda Navigator)</strong>, which installs Python along with NumPy, Pandas, Matplotlib and Jupyter together, so you don't need to install each one separately." },
    { t: "note", kind: "trap", html: "A notebook cell can be a <strong>code cell</strong> (runs Python) or a <strong>markdown cell</strong> (formatted text/explanation) — mixing both is exactly why notebooks are preferred for exploring data step by step, unlike a plain script." },
  ],
  examFocus: [
    "Why Python is preferred for AI (simple syntax + ready-made libraries).",
    "Data types — int, float, str, bool — identifying the type of a given value.",
    "Lists vs tuples vs dictionaries — brackets used, mutability, and when to use each.",
    "The role of conditionals and loops, and why loops matter for processing data.",
    "What NumPy, Pandas and Matplotlib are each used for.",
    "What a Jupyter Notebook is and why it's used over a plain script.",
  ],
  flashcards: [
    { q: "Why is Python widely used for AI?", a: "Its syntax is simple and close to plain English, and it has ready-made libraries (NumPy, Pandas, Matplotlib, etc.) for maths, data and visualisation, so you rarely code things from scratch." },
    { q: "What is a variable in Python?", a: "A named container that stores a value, e.g. age = 15; Python decides its data type automatically from the value." },
    { q: "Name the four basic data types covered — with an example each.", a: "int (92), float (5.6), str/string ('Aisha'), bool (True/False)." },
    { q: "How is a list written, and can it change?", a: "With square brackets, e.g. [90, 85, 76]; yes, a list is mutable — items can be added, removed or changed." },
    { q: "How is a tuple different from a list?", a: "A tuple is written with round brackets, e.g. (10, 20), and is immutable — it cannot be changed once created; a list can be." },
    { q: "How is a dictionary written, and what is it good for?", a: "With curly brackets and key:value pairs, e.g. {'name': 'Ravi', 'age': 15}; it's good for looking up a value by a meaningful key instead of a position." },
    { q: "What do conditional statements (if/elif/else) do?", a: "They let a program take different actions depending on whether a condition is true or false." },
    { q: "What's the difference between a for loop and a while loop?", a: "A for loop repeats a fixed number of times (e.g. once per item in a list); a while loop repeats as long as a given condition remains true." },
    { q: "What is a function, and why use one?", a: "A named, reusable block of code that performs one task; it avoids repeating code and makes programs easier to read, test and fix." },
    { q: "What is NumPy mainly used for?", a: "Fast mathematical operations on arrays (grids of numbers), useful for doing maths on large amounts of data efficiently." },
    { q: "What is Pandas mainly used for?", a: "Loading, cleaning and analysing tabular (row-and-column) data, such as reading a CSV file into a DataFrame." },
    { q: "What is a Jupyter Notebook?", a: "A tool for writing and running Python code in small cells with the output shown right below, mixed with formatted text — widely used for AI/data science work." },
  ],
  quiz: [
    { q: "Which of these best explains why Python is popular for AI work?", options: ["It is the only language computers understand", "Its simple syntax and ready-made libraries reduce the need to code everything from scratch", "It cannot be used for anything except AI", "It does not need a computer to run"], answer: 1, why: "Python's easy-to-read syntax plus libraries like NumPy, Pandas and Matplotlib is exactly why it's preferred for AI/data work." },
    { q: "What data type would best store the value True?", options: ["int", "float", "str", "bool"], answer: 3, why: "True/False values are stored using the boolean (bool) data type." },
    { q: "The value 5.6 (a student's height in feet) should be stored as a:", options: ["int", "float", "str", "bool"], answer: 1, why: "5.6 is a decimal number, so it should be stored as a float." },
    { q: "Which of these is written as a Python list?", options: ["(10, 20, 30)", "[10, 20, 30]", "{10, 20, 30}", "10, 20, 30"], answer: 1, why: "Lists are written using square brackets [ ]." },
    { q: "Which data structure is immutable (cannot be changed after creation)?", options: ["List", "Dictionary", "Tuple", "All of the above are mutable"], answer: 2, why: "A tuple is fixed once created and cannot be changed, unlike lists and dictionaries." },
    { q: "A dictionary stores its data as:", options: ["A single value only", "Ordered positions starting at 0", "Key:value pairs", "Only numbers"], answer: 2, why: "A dictionary maps keys to values, e.g. {'name': 'Ravi', 'age': 15}, and values are looked up by key." },
    { q: "Which loop is best when you want to repeat an action exactly once for every item in a list?", options: ["while loop", "for loop", "if statement", "function"], answer: 1, why: "A for loop is designed to iterate over each item of a sequence like a list." },
    { q: "Which Python library is best suited for reading and analysing a CSV file as rows and columns?", options: ["Matplotlib", "NumPy", "Pandas", "Jupyter"], answer: 2, why: "Pandas is built for loading, cleaning and analysing tabular (row/column) data such as CSV files." },
    { q: "Which library would you use to draw a bar graph or scatter plot of your data?", options: ["Pandas", "Matplotlib", "NumPy", "Anaconda"], answer: 1, why: "Matplotlib is the library used for drawing charts and graphs in Python." },
  ],
  keyTopics: [
    { name: "Why Python for AI", importance: "low", note: "Short 1-mark reasoning question; mention syntax simplicity + libraries." },
    { name: "Data types (int, float, str, bool)", importance: "medium", note: "Identify the correct data type for a given value." },
    { name: "Lists, tuples, dictionaries", importance: "high", note: "Compare syntax, mutability, and when to use each; a favourite 2–3 mark question." },
    { name: "Conditionals and loops", importance: "medium", note: "Explain purpose of if/elif/else and for/while loops with an example use." },
    { name: "Functions", importance: "medium", note: "Define what a function is and why it's used (reuse, readability)." },
    { name: "NumPy, Pandas, Matplotlib, Jupyter", importance: "high", note: "Match each library/tool to its purpose — very commonly asked." },
  ],
  written: [
    { q: "What is a variable in Python? Give an example.", marks: 1, kind: "short", importance: "medium",
      answer: "A variable is a named container used to store a value, whose type Python decides automatically. Example: <code>marks = 92</code>." },
    { q: "Name any two data types in Python, with one example of each.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>int</strong> — stores whole numbers, e.g. <code>age = 15</code>. <strong>str</strong> — stores text, e.g. <code>name = 'Aisha'</code>. (Other valid types: float, bool.)" },
    { q: "Differentiate between a list and a tuple in Python.", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>list</strong> is written with square brackets, e.g. <code>[90, 85, 76]</code>, and is <em>mutable</em> — its items can be changed, added or removed. A <strong>tuple</strong> is written with round brackets, e.g. <code>(10, 20)</code>, and is <em>immutable</em> — it stays fixed once created." },
    { q: "What is a dictionary in Python? How is it different from a list?", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>dictionary</strong> stores data as <code>key: value</code> pairs in curly brackets, e.g. <code>{'name': 'Ravi', 'age': 15}</code>, and values are looked up by their <em>key</em>. A <strong>list</strong> stores values in order and looks them up by <em>position</em> (index), not by a meaningful name." },
    { q: "Differentiate between a for loop and a while loop.", marks: 2, kind: "short", importance: "medium",
      answer: "A <strong>for loop</strong> repeats a block of code a fixed number of times, typically once for each item in a sequence like a list. A <strong>while loop</strong> repeats a block of code as long as a given condition remains true, without a fixed number of repeats decided in advance." },
    { q: "What is a function in Python? State two advantages of using functions.", marks: 3, kind: "short", importance: "medium",
      answer: "A <strong>function</strong> is a named, reusable block of code, defined once using <code>def</code>, that performs a specific task and can be called multiple times with different inputs (parameters).<br><strong>Advantages:</strong> (1) it avoids writing the same code repeatedly, and (2) it makes programs easier to read, test and debug, since a fix needs to be made in only one place." },
    { q: "Name three important Python libraries used in AI/Data Science and state what each is used for.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>NumPy</strong> — fast mathematical operations on arrays of numbers.<br><strong>Pandas</strong> — loading, cleaning and analysing tabular (row/column) data.<br><strong>Matplotlib</strong> — drawing charts and graphs such as bar, line and scatter plots." },
    { q: "What is a Jupyter Notebook, and why is it preferred for AI/data science work over a plain Python script?", marks: 3, kind: "long", importance: "high",
      answer: "A <strong>Jupyter Notebook</strong> lets you write and run Python code in small, independent <strong>cells</strong>, with the output displayed immediately below each cell, and lets you mix in formatted <strong>markdown text</strong>, headings and images alongside the code.<br>It is preferred over a plain script because you can run and re-run one small step at a time (e.g. load data, then explore it, then plot it), see results instantly, and document your thinking in the same file — which makes it ideal for the step-by-step, exploratory nature of data and AI work." },
    { q: "Explain, with an example, why loops are especially important when working with data in AI programs.", marks: 2, kind: "short", importance: "low",
      answer: "AI programs often need to repeat the same operation on every row of a large dataset — checking, transforming or calculating something for thousands of records. A <strong>loop</strong> (a <code>for</code> loop, for instance) lets this be done with just a few lines of code instead of writing one line per record, which would be impossible for large datasets." },
  ],
  assertionReason: [
    { assertion: "A list in Python can have its elements changed after it is created.",
      reason: "Lists in Python are mutable, meaning their contents can be modified, added to, or removed.",
      answer: 0, importance: "high",
      why: "Both are true, and R is the correct explanation — lists are mutable by design, which is exactly why their elements can be changed after creation." },
    { assertion: "A tuple is generally used instead of a list when the data should never change.",
      reason: "Tuples are mutable, so their values can be updated freely at any time.",
      answer: 2, importance: "medium",
      why: "A is true — tuples suit data meant to stay fixed. R is false — tuples are actually immutable, not mutable, which is exactly why they're chosen for constant data." },
    { assertion: "Pandas is the Python library most suited for handling tabular, spreadsheet-like data.",
      reason: "Pandas provides structures such as the DataFrame, designed specifically for organising and analysing data in rows and columns.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains A — Pandas' DataFrame structure is exactly what makes it suited to tabular data." },
    { assertion: "A Jupyter Notebook can only contain Python code and cannot include any explanatory text.",
      reason: "Jupyter Notebooks support markdown cells alongside code cells, allowing formatted text, headings and images to be added.",
      answer: 3, importance: "medium",
      why: "A is false — notebooks can absolutely include explanatory text via markdown cells. R is true and describes exactly this feature, which is why the scheme is A-false, R-true." },
  ],
  caseStudies: [
    { title: "Choosing the right Python structure", importance: "high",
      source: "A student is building a small program to store class information: (1) the fixed (x, y) coordinates of a classroom's projector on a seating chart, (2) a running list of students' quiz scores that keeps getting new entries added through the term, and (3) each student's roll number linked to their name, so the name can be looked up quickly by roll number.",
      parts: [
        { q: "Which Python structure suits (1), and why?", marks: 1, answer: "A <strong>tuple</strong>, e.g. <code>(12, 8)</code> — the coordinates are fixed and should not change, and tuples are immutable." },
        { q: "Which Python structure suits (2), and why?", marks: 1, answer: "A <strong>list</strong>, e.g. <code>scores = [78, 85, 91]</code> — new scores need to be added over time, and lists are mutable." },
        { q: "Which Python structure suits (3), and why?", marks: 2, answer: "A <strong>dictionary</strong>, e.g. <code>{101: 'Meera', 102: 'Arjun'}</code> — it allows looking up a value (name) directly using a meaningful key (roll number), rather than a position." },
      ] },
    { title: "Picking the right library", importance: "medium",
      source: "A student is working on a small AI project in Python. She needs to: (1) read a CSV file of daily rainfall data into rows and columns for analysis, (2) quickly perform a mathematical operation across thousands of rainfall values at once, and (3) draw a line graph of rainfall over the year.",
      parts: [
        { q: "Which library should she use for task (1), and why?", marks: 1, answer: "<strong>Pandas</strong> — it is built for loading and analysing tabular (row/column) data such as a CSV file." },
        { q: "Which library should she use for task (2), and why?", marks: 1, answer: "<strong>NumPy</strong> — it is designed for fast mathematical operations on large arrays of numbers." },
        { q: "Which library should she use for task (3), and why?", marks: 1, answer: "<strong>Matplotlib</strong> — it is the library used for drawing charts and graphs, including line graphs." },
      ] },
  ],
};
