import type { Chapter } from "@/lib/types";

export const ch06: Chapter = {
  slug: "evaluating-models",
  num: 6,
  title: "Evaluating Models",
  unit: "evaluation",
  unitName: "Evaluating Models",
  marks: "Part B · Evaluation",
  minutes: 20,
  blurb: "How to actually check whether an AI model is good — the confusion matrix, and the four numbers (accuracy, precision, recall, F1) every board question expects you to compute.",
  bigIdea: "A model that never made a single prediction would still be 'right' about everything it refused to say. Evaluation is how we prove a model is genuinely useful — not just lucky, and not just fooled by lopsided data.",
  syllabus: [
    "Why evaluation is needed", "Training data vs Testing data",
    "The Confusion Matrix — True Positive, True Negative, False Positive, False Negative",
    "Accuracy, Precision, Recall and F1 Score — formulas and calculation",
    "Why accuracy alone can be misleading on imbalanced data",
  ],
  blocks: [
    { t: "h", text: "Why evaluate a model at all?" },
    { t: "p", html: "Building a model is only half the job. Before anyone trusts its predictions — on real patients, real emails, real loan applications — we need a fair, numeric way to answer: <strong>“how good is this model, really?”</strong> That is what the <strong>Evaluation</strong> stage of the AI Project Cycle does." },
    { t: "note", kind: "trap", html: "Never evaluate a model on the same data it was trained on. It can simply <em>memorise</em> the training data and score perfectly there while failing on new cases — like grading a student on the exact questions they revised. Always split the data into a <strong>training set</strong> (to learn from) and a separate <strong>testing set</strong> (to judge fairly, on data the model has never seen)." },

    { t: "h", text: "The Confusion Matrix" },
    { t: "p", html: "A <strong>confusion matrix</strong> is a table that compares what the model <em>predicted</em> against what actually happened. For a yes/no (two-class) problem it has four cells:" },
    { t: "table", head: ["Term", "Meaning"], rows: [
      ["True Positive (TP)", "Model predicted <strong>Yes</strong>, and the actual answer was <strong>Yes</strong> — a correct hit."],
      ["True Negative (TN)", "Model predicted <strong>No</strong>, and the actual answer was <strong>No</strong> — a correct miss."],
      ["False Positive (FP)", "Model predicted <strong>Yes</strong>, but the actual answer was <strong>No</strong> — a false alarm (also called a Type I error)."],
      ["False Negative (FN)", "Model predicted <strong>No</strong>, but the actual answer was <strong>Yes</strong> — a missed case (also called a Type II error)."],
    ] },
    { t: "note", kind: "memory", html: "Read each name backwards: the <strong>second</strong> word (Positive/Negative) is what the model <em>predicted</em>; the <strong>first</strong> word (True/False) tells you whether that prediction was <strong>correct</strong>. So a False Negative is a prediction of “Negative” that was <strong>wrong</strong> — the actual case was really positive." },

    { t: "h", text: "Worked example — a spam filter tested on 100 emails" },
    { t: "p", html: "Out of 100 test emails, 40 were actually spam and 60 were actually genuine (“ham”). The filter's results were:" },
    { t: "table", head: ["", "Predicted: Spam", "Predicted: Not Spam"], rows: [
      ["Actually Spam", "TP = 30", "FN = 10"],
      ["Actually Not Spam", "FP = 5", "TN = 55"],
    ] },
    { t: "note", kind: "exam", html: "Always check the totals first: <strong>30 + 10 + 5 + 55 = 100</strong> ✓ (matches the 100 emails). This quick check catches most silly arithmetic slips in the exam." },

    { t: "h", text: "Accuracy, Precision, Recall and F1 Score" },
    { t: "p", html: "These four numbers turn the confusion matrix into a single score. Learn all four formulas — the board frequently asks you to calculate two or three of them from a given matrix." },
    { t: "eq", caption: "The four evaluation formulas", lines: [
      "Accuracy = (TP + TN) / (TP + TN + FP + FN)",
      "Precision = TP / (TP + FP)",
      "Recall = TP / (TP + FN)",
      "F1 Score = 2 × (Precision × Recall) / (Precision + Recall)",
    ] },
    { t: "list", items: [
      "<strong>Accuracy</strong> — of all predictions, what fraction were correct overall.",
      "<strong>Precision</strong> — of everything the model <em>called</em> positive, what fraction really was positive. (Answers: “can I trust a positive prediction?”)",
      "<strong>Recall</strong> (also called Sensitivity) — of everything that was <em>actually</em> positive, what fraction did the model catch. (Answers: “does the model miss real cases?”)",
      "<strong>F1 Score</strong> — the harmonic mean of Precision and Recall; a single balanced score, useful when the two disagree.",
    ] },
    { t: "note", kind: "idea", title: "A shortcut for F1", html: "Because Precision = TP/(TP+FP) and Recall = TP/(TP+FN), the F1 formula simplifies to <strong>F1 = 2TP / (2TP + FP + FN)</strong> — often faster to compute directly from the confusion matrix." },

    { t: "h", text: "Verified calculation — using the spam filter example" },
    { t: "p", html: "From the table above: TP = 30, TN = 55, FP = 5, FN = 10." },
    { t: "eq", caption: "Step-by-step", lines: [
      "Accuracy = (30 + 55) / (30 + 55 + 5 + 10) = 85 / 100 = 0.85 = 85%",
      "Precision = 30 / (30 + 5) = 30 / 35 ≈ 0.857 = 85.7%",
      "Recall = 30 / (30 + 10) = 30 / 40 = 0.75 = 75%",
      "F1 = 2 × (0.857 × 0.75) / (0.857 + 0.75) = 2 × 30 / (2×30 + 5 + 10) = 60 / 75 = 0.8 = 80%",
    ] },
    { t: "note", kind: "why", title: "Reading the result", html: "Precision (85.7%) is higher than Recall (75%) here — the filter is fairly trustworthy when it flags spam, but it still lets 10 real spam emails slip into the inbox as False Negatives. F1 (80%) sits between the two, summarising the trade-off in one number." },

    { t: "h", text: "Why accuracy alone can mislead — the rare-disease trap" },
    { t: "p", html: "Accuracy looks reassuring but hides a trap when the classes are <strong>imbalanced</strong> — that is, one outcome is far rarer than the other." },
    { t: "p", html: "Suppose a disease affects only <strong>10 out of 1,000</strong> people tested. A lazy model that predicts <em>“no disease”</em> for absolutely everyone would score:" },
    { t: "eq", lines: [
      "TP = 0, FN = 10, FP = 0, TN = 990",
      "Accuracy = (0 + 990) / 1000 = 0.99 = 99%",
      "Recall = 0 / (0 + 10) = 0 = 0%",
    ] },
    { t: "note", kind: "trap", html: "99% accuracy sounds excellent — but the model caught <strong>zero</strong> of the actual patients (Recall = 0%). On imbalanced data like rare-disease screening or fraud detection, <strong>Recall (or F1)</strong> is a far more honest measure than Accuracy, because Accuracy can be gamed simply by always predicting the majority class." },

    { t: "h", text: "Exam recap" },
    { t: "note", kind: "exam", html: "Common question patterns: (1) given TP/TN/FP/FN, calculate any of the four metrics; (2) explain what a metric means in words; (3) given a scenario, say which metric matters most and why (Recall for disease/fraud detection where missing a case is costly; Precision when false alarms are costly, e.g. spam folder deleting real mail)." },
  ],
  examFocus: [
    "Why we test on unseen data, not training data.",
    "Definitions of TP, TN, FP, FN with a worked confusion matrix.",
    "The four formulas — Accuracy, Precision, Recall, F1 — and calculating each from given numbers.",
    "Why Accuracy is misleading on imbalanced data, and which metric to prefer instead.",
    "Choosing the 'right' metric for a given real-world scenario.",
  ],
  flashcards: [
    { q: "What is a confusion matrix?", a: "A table that compares a model's predictions against the actual outcomes, splitting results into True Positive, True Negative, False Positive and False Negative." },
    { q: "Define True Positive (TP).", a: "The model predicted 'Yes' (positive) and the actual answer was also 'Yes' — a correct positive prediction." },
    { q: "Define False Negative (FN).", a: "The model predicted 'No' (negative) but the actual answer was 'Yes' — a real positive case that was missed." },
    { q: "Define False Positive (FP).", a: "The model predicted 'Yes' (positive) but the actual answer was 'No' — a false alarm." },
    { q: "Give the formula for Accuracy.", a: "Accuracy = (TP + TN) / (TP + TN + FP + FN) — the fraction of all predictions that were correct." },
    { q: "Give the formula for Precision.", a: "Precision = TP / (TP + FP) — of everything predicted positive, the fraction that truly was positive." },
    { q: "Give the formula for Recall.", a: "Recall = TP / (TP + FN) — of everything that was actually positive, the fraction the model correctly caught." },
    { q: "Give the formula for F1 Score.", a: "F1 = 2 × (Precision × Recall) / (Precision + Recall) — the harmonic mean of Precision and Recall, balancing both." },
    { q: "Why can Accuracy be misleading?", a: "On imbalanced data, a model can score very high accuracy just by always predicting the majority class, while completely failing to catch the rare (minority) cases." },
    { q: "Which metric matters most for a rare-disease test, and why?", a: "Recall — because missing an actual patient (a False Negative) is far more costly than a false alarm; Recall directly measures how many real cases were caught." },
    { q: "Why must a model be tested on data separate from its training data?", a: "So we measure how well it performs on genuinely new cases, not how well it memorised the examples it already saw." },
    { q: "In the phrase 'False Negative', which word describes the model's prediction?", a: "'Negative' — the model predicted No; 'False' means that prediction turned out to be wrong (the actual case was really positive)." },
  ],
  quiz: [
    { q: "What is the purpose of a confusion matrix?", options: ["To confuse the reader with too many numbers", "To compare a model's predictions against the actual outcomes", "To store the training data", "To visualise an image"], answer: 1, why: "A confusion matrix organises predicted vs. actual outcomes into TP, TN, FP and FN so we can measure model performance." },
    { q: "The model predicted 'disease present' but the patient was actually healthy. This is a:", options: ["True Positive", "True Negative", "False Positive", "False Negative"], answer: 2, why: "Predicted positive, actual negative — a false alarm, which is a False Positive." },
    { q: "Given TP = 40, TN = 40, FP = 10, FN = 10, the Accuracy is:", options: ["50%", "40%", "90%", "80%"], answer: 3, why: "Accuracy = (40+40)/(40+40+10+10) = 80/100 = 80%." },
    { q: "Precision is defined as:", options: ["TP / (TP + FN)", "TP / (TP + FP)", "(TP+TN) / Total", "FP / (FP + TN)"], answer: 1, why: "Precision = TP / (TP + FP) — the fraction of predicted-positive cases that were genuinely positive." },
    { q: "Recall answers which question?", options: ["Can I trust a positive prediction?", "Of all the actual positives, how many did the model catch?", "How fast is the model?", "How big is the dataset?"], answer: 1, why: "Recall = TP / (TP + FN), measuring how many real positive cases were correctly identified." },
    { q: "F1 Score is best described as:", options: ["The sum of Precision and Recall", "The harmonic mean of Precision and Recall", "The same as Accuracy", "Always higher than Precision"], answer: 1, why: "F1 balances Precision and Recall using their harmonic mean, useful when the two metrics disagree." },
    { q: "A lazy model always predicts 'no disease' for a rare illness affecting 10 in 1,000 people. Its Accuracy and Recall are approximately:", options: ["99% Accuracy, 0% Recall", "0% Accuracy, 99% Recall", "50% Accuracy, 50% Recall", "99% Accuracy, 99% Recall"], answer: 0, why: "It gets all 990 healthy cases right (99% accuracy) but catches none of the 10 actual patients (0% recall) — showing accuracy can mislead on imbalanced data." },
    { q: "Why must a model be evaluated on a separate test set rather than its training data?", options: ["Testing data is always smaller", "The model may just memorise training data and appear better than it really is", "Training data is always wrong", "It saves computer memory"], answer: 1, why: "Evaluating on unseen data reveals true performance; testing on training data can hide overfitting/memorisation." },
    { q: "Using TP = 30, FP = 5, FN = 10, TN = 55, the Precision is approximately:", options: ["75%", "80%", "85.7%", "90%"], answer: 2, why: "Precision = 30 / (30+5) = 30/35 ≈ 85.7%." },
    { q: "Using the same data (TP=30, FP=5, FN=10, TN=55), the Recall is:", options: ["75%", "85.7%", "80%", "70%"], answer: 0, why: "Recall = 30 / (30+10) = 30/40 = 75%." },
  ],
  keyTopics: [
    { name: "Confusion matrix — TP, TN, FP, FN", importance: "high", note: "Almost every paper has a numerical based on this; know the definitions cold." },
    { name: "Accuracy formula and its limitation", importance: "high", note: "State the formula, and explain why it fails on imbalanced data." },
    { name: "Precision and Recall — meaning and formula", importance: "high", note: "Calculate from given values; explain in words which one matters when." },
    { name: "F1 Score", importance: "medium", note: "Formula and why it's used when Precision and Recall disagree." },
    { name: "Why evaluate on unseen (test) data", importance: "medium", note: "Short 1–2 mark conceptual question, often paired with the AI Project Cycle." },
    { name: "Choosing the right metric for a scenario", importance: "high", note: "Case-study style: which metric matters most for disease/fraud/spam, and why." },
  ],
  written: [
    { q: "What is a confusion matrix?", marks: 1, kind: "short", importance: "high",
      answer: "A table that compares a model's <strong>predicted</strong> outcomes against the <strong>actual</strong> outcomes, splitting results into True Positive, True Negative, False Positive and False Negative." },
    { q: "Define False Positive and False Negative.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>False Positive</strong> — the model predicted Yes, but the actual answer was No (a false alarm).<br><strong>False Negative</strong> — the model predicted No, but the actual answer was Yes (a missed case)." },
    { q: "Write the formulas for Accuracy and Precision.", marks: 2, kind: "short", importance: "high",
      answer: "Accuracy = (TP + TN) / (TP + TN + FP + FN)<br>Precision = TP / (TP + FP)" },
    { q: "A model tested on 100 samples gives TP = 40, TN = 30, FP = 20, FN = 10. Calculate its Accuracy.", marks: 3, kind: "numerical", importance: "high", hint: "First add all four values to confirm they total 100.",
      answer: "Total = 40+30+20+10 = 100 ✓<br>Accuracy = (TP+TN) / Total = (40+30) / 100 = 70/100 = <strong>70%</strong>." },
    { q: "For a quality-control test on 200 items, TP = 15, FN = 5, FP = 10, TN = 170. Calculate the Precision and Recall.", marks: 3, kind: "numerical", importance: "high", hint: "Precision uses FP; Recall uses FN.",
      answer: "Total check: 15+5+10+170 = 200 ✓<br>Precision = TP/(TP+FP) = 15/(15+10) = 15/25 = <strong>60%</strong><br>Recall = TP/(TP+FN) = 15/(15+5) = 15/20 = <strong>75%</strong>." },
    { q: "For the same quality-control data (TP=15, FN=5, FP=10, TN=170), calculate the Accuracy and the F1 Score.", marks: 5, kind: "numerical", importance: "high", hint: "Use Precision = 60% and Recall = 75% found earlier; F1 = 2PR/(P+R).",
      answer: "Accuracy = (TP+TN)/Total = (15+170)/200 = 185/200 = <strong>92.5%</strong><br>F1 = 2 × (Precision × Recall) / (Precision + Recall) = 2 × (0.6 × 0.75) / (0.6 + 0.75) = 2 × 0.45 / 1.35 = 0.9/1.35 ≈ <strong>66.7%</strong><br>Note the gap between the very high Accuracy (92.5%) and the lower F1 (66.7%) — F1 exposes that the model's positive predictions are less reliable than Accuracy alone suggests." },
    { q: "Why is the F1 Score useful when Precision and Recall give very different values?", marks: 2, kind: "short", importance: "medium",
      answer: "F1 is the <strong>harmonic mean</strong> of Precision and Recall, which stays close to whichever of the two is <em>lower</em>. So if either Precision or Recall is poor, the F1 score drops noticeably — giving one honest, balanced number instead of two numbers that might tell conflicting stories." },
    { q: "Explain, with a numerical example, why Accuracy alone can be a misleading metric for a rare-disease detection model.", marks: 5, kind: "long", importance: "high", hint: "Use a model that always predicts the majority class.",
      answer: "Accuracy simply measures the fraction of <em>all</em> predictions that were correct — it does not check whether the rare, important class was detected.<br><strong>Example:</strong> if only 10 out of 1,000 people actually have a disease, a model that lazily predicts “no disease” for everyone gets TP=0, FN=10, FP=0, TN=990.<br>Accuracy = (0+990)/1000 = <strong>99%</strong> — looks excellent.<br>Recall = 0/(0+10) = <strong>0%</strong> — it caught not a single real patient.<br>So on <strong>imbalanced data</strong>, high Accuracy can hide total failure on the minority class; Recall (or F1) should be trusted instead." },
    { q: "Why must an AI model always be evaluated on a testing set that is separate from its training set?", marks: 2, kind: "short", importance: "medium",
      answer: "A model can <strong>memorise</strong> its training data and score perfectly on it while still failing on new, real-world cases. Testing on a separate, unseen dataset shows how well the model has truly <strong>generalised</strong>, giving a fair measure of real performance." },
    { q: "In a spam filter, would you prioritise Precision or Recall if the biggest concern is important genuine emails being wrongly sent to the spam folder? Justify.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Precision</strong> — because a False Positive here means a genuine email is wrongly flagged as spam, and high Precision keeps False Positives low, protecting important genuine mail." },
  ],
  assertionReason: [
    { assertion: "Accuracy is always the single best metric to judge a classification model.",
      reason: "On a highly imbalanced dataset, a model can score very high accuracy while completely failing to detect the minority class.",
      answer: 3, importance: "high",
      why: "A is false — Accuracy is not always the best metric. R is true and is exactly the reason Accuracy can be misleading, so the correct choice is 'A false, R true'." },
    { assertion: "In a confusion matrix, the diagonal cells (TP and TN) represent the model's correct predictions.",
      reason: "The off-diagonal cells (FP and FN) represent the model's incorrect predictions, or 'confusions'.",
      answer: 1, importance: "medium",
      why: "Both statements are individually true, but R describes the off-diagonal cells — it does not explain why the diagonal cells specifically represent correct predictions, so R is not the correct explanation of A." },
    { assertion: "Recall is usually considered more important than Precision for a disease-screening test.",
      reason: "Recall measures how many of the actual positive (diseased) cases were correctly identified, and missing a true patient (a False Negative) can be dangerous.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains A: because missing a real patient is costly, catching as many actual positives as possible (high Recall) matters most in screening." },
    { assertion: "The F1 Score is calculated as the simple arithmetic mean (average) of Precision and Recall.",
      reason: "The F1 Score is the harmonic mean of Precision and Recall, which is more sensitive to a low value in either metric than a simple average would be.",
      answer: 3, importance: "medium",
      why: "A is false — F1 is the harmonic mean, not the arithmetic mean. R is a true and correct statement about how F1 is actually calculated." },
  ],
  caseStudies: [
    { title: "Evaluating a medical screening test", importance: "high",
      source: "A new screening test is run on 500 patients to check for a condition. Of these, 20 patients actually have the condition and 480 do not. The test's results are: True Positive = 18, False Negative = 2, False Positive = 30, True Negative = 450.",
      parts: [
        { q: "Verify the totals, then calculate the test's Accuracy and Recall.", marks: 2, answer: "Total = 18+2+30+450 = 500 ✓ (matches 500 patients).<br>Accuracy = (18+450)/500 = 468/500 = <strong>93.6%</strong><br>Recall = 18/(18+2) = 18/20 = <strong>90%</strong>." },
        { q: "Calculate the test's Precision. What does this value mean in plain words?", marks: 1, answer: "Precision = 18/(18+30) = 18/48 = <strong>37.5%</strong>. It means that out of every patient the test flags as positive, only about 37.5% actually have the condition — the rest (62.5%) are false alarms." },
        { q: "For this screening scenario, is a high Recall or a high Precision more important? Justify briefly.", marks: 1, answer: "A high <strong>Recall</strong> matters more — missing an actual patient (a False Negative) could delay life-saving treatment, which is far more serious than a false alarm that simply leads to a follow-up test." },
      ] },
  ],
};
