import type { Chapter } from "@/lib/types";

export const ch07: Chapter = {
  slug: "computer-vision",
  num: 7,
  title: "Computer Vision",
  unit: "domains",
  unitName: "Computer Vision & Natural Language Processing",
  marks: "Part B · Domains",
  minutes: 14,
  blurb: "How a computer 'sees' — turning an image into numbers, the three core Computer Vision tasks, and how a CNN learns to recognise what's in a picture.",
  bigIdea: "A computer never actually sees a photo the way you do — it only sees a huge grid of numbers. Computer Vision is the set of techniques that let a machine find meaning in that grid.",
  syllabus: [
    "What is Computer Vision", "How a computer sees an image — pixels, resolution",
    "Grayscale vs RGB images", "Image as a matrix of numbers",
    "Computer Vision tasks — classification, detection, segmentation",
    "Convolution, kernels and the idea of a CNN", "Applications of Computer Vision",
  ],
  blocks: [
    { t: "h", text: "What is Computer Vision?" },
    { t: "p", html: "<strong>Computer Vision (CV)</strong> is the domain of AI that lets machines gain understanding from <strong>digital images and videos</strong> — the same way our eyes and brain let us understand the world around us." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "Computer Vision is the field of AI that trains machines to <strong>identify and understand objects, scenes and people in images or video</strong>." },

    { t: "h", text: "How does a computer actually see an image?" },
    { t: "p", html: "A digital image is built from thousands (or millions) of tiny square dots called <strong>pixels</strong> ('picture elements'). Each pixel stores a number — or a small group of numbers — that tells the display exactly how bright and what colour to make that one dot." },
    { t: "table", head: ["Term", "Meaning"], rows: [
      ["Pixel", "The smallest single dot of a digital image; each one holds a colour/brightness value."],
      ["Resolution", "The number of pixels in the image, given as width × height — e.g. a 4×4 image has 16 pixels."],
      ["Grayscale image", "Each pixel has just <strong>one</strong> number, usually 0 (black) to 255 (white), with shades of grey in between."],
      ["RGB (colour) image", "Each pixel has <strong>three</strong> numbers — Red, Green and Blue intensity (each 0–255) — that mix to form its colour."],
    ] },
    { t: "note", kind: "memory", html: "A computer never sees a 'picture' — it sees a <strong>matrix (grid) of numbers</strong>. A grayscale image is one matrix of values; a colour (RGB) image is really <strong>three</strong> matrices stacked together, one each for Red, Green and Blue." },
    { t: "note", kind: "exam", html: "A frequent 1-mark question: “How many values does a single pixel of a colour image store?” Answer: <strong>three</strong> — one each for Red, Green and Blue." },

    { t: "h", text: "The three core Computer Vision tasks" },
    { t: "p", html: "Almost every CV application is really one of these three underlying tasks, done on an image." },
    { t: "table", head: ["Task", "It answers…", "Example"], rows: [
      ["Image Classification", "“What is the main object in this image?”", "Is this photo a cat or a dog?"],
      ["Object Detection", "“What objects are present, and where (bounding box) is each one?”", "Locating every car and pedestrian in a street photo"],
      ["Image Segmentation", "“Which exact pixels belong to each object?”", "Outlining the precise shape of a tumour in a medical scan"],
    ] },
    { t: "note", kind: "why", title: "Why the distinction matters", html: "Classification only names the whole image. Detection adds a location (a box). Segmentation is the most detailed — it labels every individual pixel, so it can trace an object's exact outline rather than just a box around it." },

    { t: "h", text: "Convolution, kernels and the idea of a CNN" },
    { t: "p", html: "To find patterns like edges, corners or textures, CV slides a small grid of numbers called a <strong>kernel</strong> (or <strong>filter</strong>) across the image, multiplying and adding values at each position. This operation is called <strong>convolution</strong>, and it highlights a specific feature wherever it appears in the image." },
    { t: "p", html: "A <strong>Convolutional Neural Network (CNN)</strong> is a deep-learning model built from many convolution layers stacked together. Early layers learn to detect simple features (edges, colours); deeper layers combine these into complex ones (eyes, wheels, faces) — until the network can recognise whole objects." },
    { t: "note", kind: "trap", html: "A CNN does not need a human to define what to look for. Unlike an old-style rule-based CV program (which needed a programmer to hand-code 'look for two round dark shapes for eyes'), a CNN <strong>learns which features matter directly from training images</strong>." },

    { t: "h", text: "Real-life applications of Computer Vision" },
    { t: "list", items: [
      "<strong>Face unlock</strong> on phones — recognising a specific face.",
      "<strong>Self-driving cars</strong> — detecting lanes, signs, pedestrians and other vehicles.",
      "<strong>Medical imaging</strong> — spotting tumours or fractures in X-rays and scans.",
      "<strong>Quality inspection</strong> in factories — automatically catching defective products on a conveyor belt.",
      "<strong>Optical Character Recognition (OCR)</strong> — reading printed or handwritten text from a photo.",
      "<strong>Augmented-reality filters</strong> — tracking a face in real time to place stickers or masks.",
    ] },

    { t: "h", text: "Exam recap" },
    { t: "note", kind: "exam", html: "A common trap: don't confuse Computer Vision (images/video) with Natural Language Processing (text/speech) — a question describing a camera, a photo or a video is CV; a question describing typed or spoken words is NLP." },
  ],
  examFocus: [
    "One-line definition of Computer Vision.",
    "Pixels, resolution, and grayscale vs RGB (how many numbers per pixel).",
    "An image as a matrix of numbers.",
    "The three CV tasks — classification, detection, segmentation — and telling them apart.",
    "The basic idea of convolution/kernels and what a CNN does.",
    "Real applications, and distinguishing CV questions from NLP questions.",
  ],
  flashcards: [
    { q: "Define Computer Vision.", a: "The domain of AI that trains machines to identify and understand objects, scenes and people in images or video." },
    { q: "What is a pixel?", a: "The smallest single dot of a digital image; it stores a number (or numbers) representing brightness/colour." },
    { q: "What is the resolution of an image?", a: "The number of pixels in the image, expressed as width × height, e.g. a 4×4 image has 16 pixels." },
    { q: "How many values does one pixel store in a grayscale image? In an RGB image?", a: "Grayscale: one value (0–255, black to white). RGB: three values — Red, Green and Blue, each 0–255." },
    { q: "How does a computer 'see' an image, mathematically?", a: "As a matrix (grid) of numbers — one matrix for grayscale, or three stacked matrices (R, G, B) for a colour image." },
    { q: "What does Image Classification do?", a: "Identifies the single main object/category present in an entire image, e.g. 'this is a cat'." },
    { q: "What does Object Detection do?", a: "Identifies what objects are present and marks the location of each with a bounding box." },
    { q: "What does Image Segmentation do?", a: "Labels every individual pixel to trace the exact shape/outline of each object, more precise than a bounding box." },
    { q: "What is a kernel (filter) in Computer Vision?", a: "A small grid of numbers slid across an image (convolution) to detect a specific feature such as an edge or texture." },
    { q: "What is a CNN?", a: "A Convolutional Neural Network — a deep-learning model built from convolution layers that learns to detect features directly from training images, from simple edges to complex objects." },
    { q: "Give two real applications of Computer Vision.", a: "Face unlock on phones, and object detection in self-driving cars (also: medical imaging, OCR, factory quality inspection, AR filters)." },
    { q: "How do you tell a CV question from an NLP question in the exam?", a: "CV deals with images/video (cameras, photos, scans); NLP deals with human language (typed or spoken text)." },
  ],
  quiz: [
    { q: "Computer Vision mainly deals with:", options: ["Spoken and written language", "Numbers and spreadsheets", "Images and video", "Sound waves only"], answer: 2, why: "Computer Vision is the AI domain that works with visual data — images and video." },
    { q: "The smallest single unit of a digital image is called a:", options: ["Byte", "Pixel", "Kernel", "Vector"], answer: 1, why: "A pixel ('picture element') is the smallest dot that makes up a digital image." },
    { q: "An image with resolution 4×4 has how many pixels?", options: ["4", "8", "16", "44"], answer: 2, why: "Resolution is width × height, so 4×4 = 16 pixels." },
    { q: "In a grayscale image, each pixel stores:", options: ["Three values (R, G, B)", "One value, typically 0 (black) to 255 (white)", "No numeric value", "Only the pixel's location"], answer: 1, why: "A grayscale pixel stores a single brightness value, usually from 0 to 255." },
    { q: "In an RGB colour image, each pixel stores:", options: ["One value", "Two values", "Three values (Red, Green, Blue)", "Ten values"], answer: 2, why: "Each RGB pixel stores three intensity values, one per colour channel, which mix to form its colour." },
    { q: "A computer represents any digital image mathematically as a:", options: ["Single word", "Sound wave", "Matrix (grid) of numbers", "List of names"], answer: 2, why: "An image is stored and processed as a matrix of pixel values." },
    { q: "Drawing a bounding box around every car in a street photo is an example of:", options: ["Image Classification", "Object Detection", "Image Segmentation", "Tokenisation"], answer: 1, why: "Locating objects with bounding boxes is Object Detection." },
    { q: "Labelling the exact pixels that form a tumour's outline in a scan is:", options: ["Image Classification", "Object Detection", "Image Segmentation", "Data Exploration"], answer: 2, why: "Pixel-level labelling of an object's precise shape is Image Segmentation." },
    { q: "In a CNN, a small grid of numbers slid over the image to detect features like edges is called a:", options: ["Label", "Kernel (filter)", "Token", "Confusion matrix"], answer: 1, why: "This sliding grid used in convolution is called a kernel or filter." },
    { q: "Which of these is a real Computer Vision application?", options: ["Predicting next month's sales from records", "Translating spoken English to Hindi", "Detecting a defective item on a factory conveyor belt using a camera", "Auto-correcting spelling while typing"], answer: 2, why: "Detecting defects visually from camera images is a Computer Vision task; the others are Data Sciences or NLP tasks." },
  ],
  keyTopics: [
    { name: "Definition of Computer Vision", importance: "medium", note: "Short 1-mark recall question." },
    { name: "Pixels, resolution and grayscale vs RGB", importance: "high", note: "Numeric-flavoured recall — number of values per pixel, resolution as width×height." },
    { name: "Image as a matrix of numbers", importance: "medium", note: "Conceptual link between pixels and how a computer stores an image." },
    { name: "The three CV tasks — classification, detection, segmentation", importance: "high", note: "Given a scenario, identify which of the three it is." },
    { name: "Convolution, kernels and CNN idea", importance: "medium", note: "Simple, one-paragraph explanation is usually enough at Class 10 level." },
    { name: "Real applications of CV", importance: "low", note: "List-recall; useful for distinguishing CV from NLP in case studies." },
  ],
  written: [
    { q: "Define Computer Vision.", marks: 1, kind: "short", importance: "medium",
      answer: "Computer Vision is the domain of AI that trains machines to <strong>identify and understand objects, scenes and people in images or video</strong>." },
    { q: "What is a pixel?", marks: 1, kind: "short", importance: "high",
      answer: "A pixel is the <strong>smallest single dot</strong> of a digital image; it stores a number (or numbers) that represent its brightness and colour." },
    { q: "Differentiate between a grayscale image and an RGB image in terms of the values stored per pixel.", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>grayscale</strong> image stores just <strong>one</strong> value per pixel (0 = black to 255 = white). An <strong>RGB</strong> (colour) image stores <strong>three</strong> values per pixel — Red, Green and Blue intensities — which combine to produce the pixel's colour." },
    { q: "How does a computer represent a digital image internally? Explain briefly.", marks: 2, kind: "short", importance: "medium",
      answer: "A computer stores an image as a <strong>matrix (grid) of numbers</strong>. A grayscale image is one such matrix of brightness values; a colour (RGB) image is really <strong>three matrices stacked together</strong>, one each for the Red, Green and Blue channels." },
    { q: "Differentiate between Image Classification, Object Detection and Image Segmentation, with one example each.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Image Classification</strong> — names the single main object in the whole image, e.g. “this photo shows a dog”.<br><strong>Object Detection</strong> — finds and marks the location of every object with a bounding box, e.g. locating each car in a street photo.<br><strong>Image Segmentation</strong> — labels the exact pixels of every object's outline, e.g. tracing a tumour's precise shape in a scan." },
    { q: "What is a kernel (filter) in Computer Vision, and what operation uses it?", marks: 2, kind: "short", importance: "medium",
      answer: "A <strong>kernel</strong> is a small grid of numbers that is slid across an image, multiplying and adding values at each position to highlight a feature such as an edge or texture. This sliding operation is called <strong>convolution</strong>." },
    { q: "What is a Convolutional Neural Network (CNN), and how is it different from a hand-coded (rule-based) image program?", marks: 3, kind: "long", importance: "medium",
      answer: "A <strong>CNN</strong> is a deep-learning model built from many convolution layers, where early layers detect simple features (edges, colours) and deeper layers combine them into complex ones (shapes, faces, objects).<br>Unlike a rule-based program, where a human must hand-code exactly what pattern to search for, a CNN <strong>learns which features matter directly from training images</strong>, without being explicitly told what to look for." },
    { q: "Explain, with an example, how you would decide whether a real-world application belongs to Computer Vision or Natural Language Processing.", marks: 2, kind: "short", importance: "medium",
      answer: "Check what kind of data the application processes: if it works with <strong>images or video</strong> (a camera feed, a photo, a scan), it is <strong>Computer Vision</strong>; if it works with <strong>text or speech</strong> (typed or spoken words), it is <strong>Natural Language Processing</strong>. Example: a phone unlocking by scanning your face is CV; the same phone's voice assistant answering a spoken question is NLP." },
    { q: "Describe any three real-life applications of Computer Vision.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>1. Self-driving cars</strong> — detect lanes, road signs, pedestrians and other vehicles from camera feeds.<br><strong>2. Medical imaging</strong> — spot tumours or fractures in X-rays and scans, assisting doctors.<br><strong>3. Factory quality inspection</strong> — automatically identify defective products on a conveyor belt using cameras. (Others: face unlock, OCR, AR filters.)" },
  ],
  assertionReason: [
    { assertion: "A colour (RGB) image needs three numbers to describe each pixel.",
      reason: "Each pixel's colour is formed by mixing Red, Green and Blue intensity values.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains A — the three RGB values are exactly why three numbers per pixel are needed." },
    { assertion: "Object Detection and Image Segmentation give exactly the same output for an image.",
      reason: "Object Detection marks objects with bounding boxes, while Image Segmentation labels the precise pixels belonging to each object.",
      answer: 3, importance: "high",
      why: "A is false — the two tasks give different outputs (boxes vs. pixel-level outlines). R is a true and correct description of that difference." },
    { assertion: "A Convolutional Neural Network can learn to recognise objects without a human explicitly coding what features to look for.",
      reason: "A CNN's convolution layers learn useful features directly from the training images, progressing from simple edges to complex shapes.",
      answer: 0, importance: "medium",
      why: "Both are true, and R correctly explains A — the layer-by-layer feature learning is exactly why no manual feature-coding is needed." },
  ],
  caseStudies: [
    { title: "Classifying a smart-camera application", importance: "medium",
      source: "A supermarket installs a ceiling camera above the checkout counter. The system (1) decides whether each frame shows 'a customer present' or 'no customer', (2) draws a box around every individual item placed on the belt, and (3) highlights the exact outline of a spilled liquid on the floor so a cleaning robot can target only that shape.",
      parts: [
        { q: "Identify which Computer Vision task — Classification, Detection or Segmentation — matches each of the three system behaviours.", marks: 3, answer: "(1) 'Customer present / no customer' → <strong>Image Classification</strong> (one label for the whole frame).<br>(2) Boxing every item on the belt → <strong>Object Detection</strong> (location of each object).<br>(3) Outlining the exact spill shape → <strong>Image Segmentation</strong> (precise pixel-level outline)." },
        { q: "Is this application an example of Computer Vision or Natural Language Processing? Justify in one line.", marks: 1, answer: "Computer Vision — the system processes <strong>camera images/video</strong>, not human language." },
      ] },
  ],
};
