import type { Chapter } from "@/lib/types";

export const ch08: Chapter = {
  slug: "natural-language-processing",
  num: 8,
  title: "Natural Language Processing",
  unit: "domains",
  unitName: "Computer Vision & Natural Language Processing",
  marks: "Part B · Domains",
  minutes: 20,
  blurb: "How a machine makes sense of human language — the text-processing pipeline, turning words into numbers with Bag of Words and TF-IDF, and the two kinds of chatbots.",
  bigIdea: "Human language is full of ambiguity, sarcasm and context that a machine can't feel. NLP is the toolbox that turns messy human sentences into clean, structured numbers a model can actually learn from.",
  syllabus: [
    "What is Natural Language Processing", "Human language vs computer language",
    "Applications of NLP — chatbots, sentiment analysis, translation",
    "Text Processing — tokenisation, stopwords, stemming and lemmatisation, lowercasing",
    "Bag of Words model", "TF-IDF (Term Frequency – Inverse Document Frequency)",
    "Chatbots — script-based vs AI-based/smart bots",
  ],
  blocks: [
    { t: "h", text: "What is Natural Language Processing?" },
    { t: "p", html: "<strong>Natural Language Processing (NLP)</strong> is the domain of AI that enables computers to <strong>understand, interpret and generate human language</strong> — whether typed text or spoken speech." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "NLP is the branch of AI that lets machines read, understand and respond to <strong>human language</strong>, in both text and speech form." },

    { t: "h", text: "Human language vs computer language" },
    { t: "p", html: "Computers are naturally comfortable with precise, structured data — numbers, fixed commands, clear syntax. Human language is the opposite: full of ambiguity, sarcasm, tone, slang and context. NLP exists to bridge this gap." },
    { t: "compare",
      left: { title: "Human (natural) language", items: [
        "Same word can mean different things ('bank' of a river vs a 'bank' account)",
        "Meaning changes with tone and context",
        "Full of idioms, sarcasm and grammar exceptions",
        "Understood instantly by people",
      ] },
      right: { title: "Computer language", items: [
        "Every command has exactly one fixed meaning",
        "Follows strict, unchanging syntax rules",
        "No ambiguity — code must be precise",
        "Understood instantly by machines",
      ] } },
    { t: "note", kind: "trap", html: "A frequent exam trap: give an example of <strong>ambiguity</strong> in human language, e.g. “I saw the man with a telescope” — unclear whether the telescope belongs to the man or was used to see him. This is exactly why NLP is hard." },

    { t: "h", text: "Applications of NLP" },
    { t: "list", items: [
      "<strong>Chatbots / virtual assistants</strong> — Siri, Alexa, Google Assistant answering spoken or typed questions.",
      "<strong>Sentiment Analysis</strong> — deciding whether a review or tweet is positive, negative or neutral.",
      "<strong>Machine Translation</strong> — converting text from one language to another, e.g. Google Translate.",
      "<strong>Spam detection</strong> — reading email text to flag junk mail.",
      "<strong>Auto-complete / spell-check</strong> — predicting or correcting the next word as you type.",
    ] },

    { t: "h", text: "The Text Processing Pipeline" },
    { t: "p", html: "Before any NLP model can use a sentence, it must be cleaned and simplified through a series of steps." },
    { t: "steps", title: "Cleaning a sentence, step by step", intro: "Example sentence: “The cats were running quickly in the gardens.”",
      steps: [
        "<strong>Sentence segmentation</strong> — split a paragraph into individual sentences.",
        "<strong>Tokenisation</strong> — break each sentence into individual words (tokens): the, cats, were, running, quickly, in, the, gardens.",
        "<strong>Lowercasing</strong> — convert all tokens to lower case so 'The' and 'the' are treated as the same word.",
        "<strong>Removing stopwords</strong> — drop common, low-meaning words like 'the', 'were', 'in' → left with: cats, running, quickly, gardens.",
        "<strong>Stemming / Lemmatisation</strong> — reduce each word to its root/base form: cats → cat, running → run, gardens → garden.",
      ],
      answer: "Cleaned tokens: cat, run, quickly, garden — a short, meaningful list ready to be turned into numbers." },
    { t: "table", head: ["", "Stemming", "Lemmatisation"], rows: [
      ["Method", "Chops off word endings using fixed rules", "Uses vocabulary + grammar rules to find the true dictionary root"],
      ["Speed", "Faster, but cruder", "Slower, but more accurate"],
      ["Example", "'studies' → 'studi' (may not be a real word)", "'studies' → 'study' (a real dictionary word)"],
    ] },
    { t: "note", kind: "why", title: "Why remove stopwords?", html: "Words like 'the', 'is', 'and' appear in almost every sentence and carry very little meaning on their own. Removing them lets the model focus computing power on the words that actually distinguish one sentence from another." },

    { t: "h", text: "Turning words into numbers — Bag of Words" },
    { t: "p", html: "A computer cannot learn from raw words — everything must become numbers. The simplest method is the <strong>Bag of Words (BoW)</strong> model: it counts how many times each word appears, completely ignoring grammar and word order." },
    { t: "p", html: "Vocabulary from two short documents — <strong>D1:</strong> “AI is easy AI is fun”, <strong>D2:</strong> “AI is hard” — is: {AI, is, easy, fun, hard}." },
    { t: "table", head: ["Document", "AI", "is", "easy", "fun", "hard"], rows: [
      ["D1: 'AI is easy AI is fun'", "2", "2", "1", "1", "0"],
      ["D2: 'AI is hard'", "1", "1", "0", "0", "1"],
    ] },
    { t: "note", kind: "trap", html: "Bag of Words completely throws away word <strong>order</strong> and grammar — “dog bites man” and “man bites dog” would produce the identical word-count vector, even though they mean very different things." },

    { t: "h", text: "A smarter score — TF-IDF" },
    { t: "p", html: "Plain word counts have a flaw: common words like 'is' get large counts in every document but tell us nothing special about any one of them. <strong>TF-IDF (Term Frequency – Inverse Document Frequency)</strong> fixes this by scoring a word higher when it is frequent in <em>one</em> document but rare across <em>all</em> documents." },
    { t: "eq", caption: "The TF-IDF formulas", lines: [
      "TF (Term Frequency) = (number of times the word appears in a document) / (total words in that document)",
      "IDF (Inverse Document Frequency) = log( total number of documents / number of documents containing the word )",
      "TF-IDF = TF × IDF",
    ] },
    { t: "p", html: "Using D1 and D2 above (2 documents total): 'AI' appears in <strong>both</strong> documents, but 'hard' appears in only <strong>one</strong>." },
    { t: "eq", caption: "Verified worked example", lines: [
      "TF('AI', D2) = 1/3 = 0.333   [D2 has 3 tokens: AI, is, hard]",
      "IDF('AI') = log(2/2) = log(1) = 0   → TF-IDF('AI', D2) = 0.333 × 0 = 0",
      "TF('hard', D2) = 1/3 = 0.333",
      "IDF('hard') = log(2/1) = log(2) ≈ 0.301   → TF-IDF('hard', D2) = 0.333 × 0.301 ≈ 0.10",
    ] },
    { t: "note", kind: "why", title: "Reading the result", html: "'AI' scores <strong>0</strong> because it appears in every document — it carries no special information about D2. 'hard' scores about <strong>0.10</strong> because it appears only in D2, making it the more distinctive, informative word for that document. This is exactly what TF-IDF is designed to capture." },

    { t: "h", text: "Chatbots — script-based vs AI-based" },
    { t: "p", html: "Most chatbots fall into one of two families." },
    { t: "compare",
      left: { title: "Script-bot (rule-based)", items: [
        "Follows a fixed, predefined script/keywords",
        "Cannot handle a question outside its script",
        "Simple to build, no learning involved",
        "Example: a basic FAQ bot on a website",
      ] },
      right: { title: "Smart / AI-bot", items: [
        "Uses NLP + Machine Learning to understand intent",
        "Can handle new, unscripted questions",
        "Learns and improves from more conversations/data",
        "Example: Siri, Alexa, Google Assistant",
      ] } },

    { t: "h", text: "Exam recap" },
    { t: "note", kind: "exam", html: "Common patterns: (1) list/order the text-processing pipeline steps; (2) differentiate stemming vs lemmatisation; (3) explain why stopwords are removed; (4) explain Bag of Words and its limitation (ignores order); (5) explain TF-IDF's purpose in one line — 'gives rare, document-specific words a higher score than common words'." },
  ],
  examFocus: [
    "One-line definition of NLP, and why human language is hard for machines.",
    "Applications — chatbots, sentiment analysis, translation.",
    "The text-processing pipeline in order — segmentation, tokenisation, lowercasing, stopword removal, stemming/lemmatisation.",
    "Stemming vs lemmatisation.",
    "Bag of Words — the concept, a small worked vector, and its limitation.",
    "TF-IDF — the formula, what it fixes, and a tiny verified example.",
    "Script-bot vs smart/AI-bot.",
  ],
  flashcards: [
    { q: "Define Natural Language Processing.", a: "The branch of AI that enables computers to understand, interpret and generate human language, in text or speech form." },
    { q: "Why is human language harder for a computer to process than computer code?", a: "Human language is ambiguous, depends on tone/context, and has idioms and grammar exceptions, whereas code follows fixed, unambiguous syntax." },
    { q: "Give two applications of NLP.", a: "Chatbots/virtual assistants and Sentiment Analysis (also: machine translation, spam detection, autocomplete)." },
    { q: "List the text-processing pipeline steps in order.", a: "Sentence segmentation → Tokenisation → Lowercasing → Removing stopwords → Stemming/Lemmatisation." },
    { q: "What is tokenisation?", a: "Breaking a sentence into individual words or tokens, e.g. 'I like AI' → ['I', 'like', 'AI']." },
    { q: "What are stopwords, and why are they removed?", a: "Very common, low-meaning words like 'the', 'is', 'and'; they are removed because they add little value and waste processing effort." },
    { q: "Differentiate stemming and lemmatisation.", a: "Stemming crudely chops word endings using fixed rules (may give a non-word, e.g. 'studi'); lemmatisation uses vocabulary/grammar to find the true dictionary root (e.g. 'study')." },
    { q: "What is the Bag of Words model?", a: "A method that represents text as a vector of word counts, completely ignoring grammar and word order." },
    { q: "What is the main limitation of Bag of Words?", a: "It ignores word order, so sentences with the same words in a different sequence (and different meaning) get identical vectors." },
    { q: "What does TF-IDF stand for, and what problem does it solve?", a: "Term Frequency – Inverse Document Frequency; it lowers the score of words common to every document and raises the score of words that are rare across documents but frequent in one — making common words like 'the' less important." },
    { q: "Give the TF-IDF formula.", a: "TF-IDF = TF × IDF, where TF = (word count in a document)/(total words in that document), and IDF = log(total documents / documents containing the word)." },
    { q: "Differentiate a script-bot from a smart/AI-bot.", a: "A script-bot follows a fixed predefined script and fails outside it; a smart/AI-bot uses NLP and Machine Learning to understand intent and can handle new, unscripted questions." },
  ],
  quiz: [
    { q: "Natural Language Processing enables computers to:", options: ["See and classify images", "Understand and generate human language", "Perform arithmetic faster", "Store data in tables"], answer: 1, why: "NLP is the AI domain dealing with human language (text/speech), not images or arithmetic." },
    { q: "Which of these best illustrates why human language is hard for a machine?", options: ["2 + 2 always equals 4", "'Bank' can mean a riverbank or a financial bank, depending on context", "A loop runs a fixed number of times", "A variable stores one value"], answer: 1, why: "Word ambiguity that depends on context is a classic reason human language is difficult for machines, unlike precise code or arithmetic." },
    { q: "Deciding whether a product review is positive or negative is called:", options: ["Tokenisation", "Sentiment Analysis", "Stemming", "Object Detection"], answer: 1, why: "Classifying the emotional tone of text is Sentiment Analysis, an NLP application." },
    { q: "Breaking a sentence into individual words is called:", options: ["Lemmatisation", "Tokenisation", "Stopword removal", "Segmentation of paragraphs"], answer: 1, why: "Splitting text into individual word units (tokens) is tokenisation." },
    { q: "Which of these is normally removed as a stopword?", options: ["Elephant", "Because", "Photosynthesis", "The"], answer: 3, why: "'The' is an extremely common, low-meaning word — a classic stopword, unlike the more specific content words listed." },
    { q: "Which technique converts 'studies' to the real dictionary word 'study', using grammar rules rather than blindly chopping letters?", options: ["Stemming", "Lemmatisation", "Tokenisation", "TF-IDF"], answer: 1, why: "Lemmatisation uses vocabulary and grammar to find the true dictionary root, unlike stemming's crude rule-based chopping." },
    { q: "The Bag of Words model represents a document as:", options: ["A grammar tree", "A vector of word counts, ignoring order", "An image matrix", "A single sentiment score"], answer: 1, why: "Bag of Words counts word occurrences and completely ignores grammar and order." },
    { q: "In TF-IDF, a word that appears in every single document in the collection will get:", options: ["A very high TF-IDF score", "A TF-IDF score of (or close to) zero", "Always the same score as its TF", "An undefined score"], answer: 1, why: "If a word appears in all documents, IDF = log(N/N) = log(1) = 0, so its TF-IDF score becomes 0 regardless of TF." },
    { q: "A chatbot that can only respond to a fixed set of predefined keywords, and fails on anything else, is a:", options: ["Smart/AI-bot", "Script-bot", "CNN", "Regression model"], answer: 1, why: "A bot limited to a fixed predefined script/keyword set is a script-bot, not a learning AI-bot." },
    { q: "Siri and Google Assistant, which understand varied, unscripted spoken questions, are examples of:", options: ["Script-bots", "Smart/AI-bots", "Rule-based automation only", "Image classifiers"], answer: 1, why: "They use NLP and Machine Learning to understand intent and handle new questions — the definition of a smart/AI-bot." },
  ],
  keyTopics: [
    { name: "Definition of NLP and human vs computer language", importance: "medium", note: "1-mark definition plus a 2-mark 'why is language hard' question." },
    { name: "Applications — chatbots, sentiment analysis, translation", importance: "medium", note: "List-based recall, sometimes with a scenario to classify." },
    { name: "Text-processing pipeline (in order)", importance: "high", note: "Very common — list all steps in order, or explain any one step." },
    { name: "Stemming vs lemmatisation", importance: "medium", note: "Classic compare-and-contrast, 2 marks." },
    { name: "Bag of Words — concept and limitation", importance: "high", note: "Explain the idea; know that it ignores word order." },
    { name: "TF-IDF — formula and purpose", importance: "high", note: "State the formula and explain why common words score low; small numericals possible." },
  ],
  written: [
    { q: "Define Natural Language Processing.", marks: 1, kind: "short", importance: "high",
      answer: "NLP is the branch of AI that enables computers to <strong>understand, interpret and generate human language</strong>, in both text and speech form." },
    { q: "Give one reason why human language is more difficult for a computer to process than a programming language.", marks: 1, kind: "short", importance: "medium",
      answer: "Human language is <strong>ambiguous</strong> — the same word can have different meanings depending on context (e.g. 'bank' of a river vs a financial 'bank') — whereas a programming language follows fixed, unambiguous rules." },
    { q: "List, in order, the steps of the text processing pipeline.", marks: 3, kind: "short", importance: "high",
      answer: "1. <strong>Sentence segmentation</strong> — split text into sentences.<br>2. <strong>Tokenisation</strong> — split each sentence into words.<br>3. <strong>Lowercasing</strong> — convert all words to lower case.<br>4. <strong>Removing stopwords</strong> — drop common, low-meaning words.<br>5. <strong>Stemming/Lemmatisation</strong> — reduce each word to its root form." },
    { q: "Differentiate between stemming and lemmatisation, with one example each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Stemming</strong> chops off word endings using fixed rules and can produce a non-dictionary word, e.g. 'studies' → 'studi'.<br><strong>Lemmatisation</strong> uses vocabulary and grammar rules to find the real dictionary root, e.g. 'studies' → 'study'. Lemmatisation is slower but more accurate." },
    { q: "Why are stopwords removed during text processing?", marks: 2, kind: "short", importance: "medium",
      answer: "Stopwords (like 'the', 'is', 'and') appear in almost every sentence but carry very little meaning on their own. Removing them lets the model focus its attention and computing power on the words that actually help distinguish one piece of text from another." },
    { q: "Explain the Bag of Words model with a small example, and state one of its limitations.", marks: 3, kind: "numerical", importance: "high", hint: "Build a vocabulary from the documents, then count occurrences per document.",
      answer: "Bag of Words represents text as a vector of <strong>word counts</strong>, ignoring grammar and order.<br><strong>Example:</strong> D1 = “AI is easy AI is fun”, D2 = “AI is hard”. Vocabulary = {AI, is, easy, fun, hard}.<br>D1 vector = [2, 2, 1, 1, 0]; D2 vector = [1, 1, 0, 0, 1].<br><strong>Limitation:</strong> it ignores word order, so “dog bites man” and “man bites dog” would give identical vectors despite meaning different things." },
    { q: "Given two documents — D1: 'AI is easy AI is fun' and D2: 'AI is hard' — calculate the TF-IDF of the word 'hard' for D2.", marks: 5, kind: "numerical", importance: "high", hint: "TF = word count / total words in that document; IDF = log(total documents / documents containing the word).",
      answer: "D2 has 3 tokens (AI, is, hard); 'hard' appears once.<br>TF('hard', D2) = 1/3 ≈ 0.333.<br>'hard' appears in only 1 of the 2 documents, so IDF('hard') = log(2/1) = log(2) ≈ 0.301.<br>TF-IDF('hard', D2) = TF × IDF = 0.333 × 0.301 ≈ <strong>0.10</strong>.<br>(For comparison, 'AI' appears in both documents, so IDF('AI') = log(2/2) = 0, giving TF-IDF('AI', D2) = 0 — showing 'hard' is treated as far more distinctive for D2 than the common word 'AI'.)" },
    { q: "What problem does TF-IDF solve that a plain Bag of Words word-count does not?", marks: 2, kind: "short", importance: "medium",
      answer: "Plain word counts give large values to very common words (like 'is' or 'the') in every document, even though such words carry little useful meaning. TF-IDF fixes this by <strong>multiplying by Inverse Document Frequency</strong>, which reduces the score of words common across all documents and boosts words that are rare overall but frequent in one document — making the score reflect true importance." },
    { q: "Differentiate between a script-bot and a smart (AI-based) chatbot, with one example each.", marks: 2, kind: "short", importance: "medium",
      answer: "A <strong>script-bot</strong> follows a fixed, predefined script or set of keywords and fails on anything outside it — e.g. a simple FAQ bot on a website.<br>A <strong>smart/AI-bot</strong> uses NLP and Machine Learning to understand a user's intent, can handle new/unscripted questions, and improves with more data — e.g. Siri or Alexa." },
    { q: "Describe three real-life applications of NLP.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>1. Virtual assistants/chatbots</strong> (Siri, Alexa) — understand and respond to spoken or typed questions.<br><strong>2. Sentiment Analysis</strong> — automatically judging whether reviews or social media posts are positive or negative.<br><strong>3. Machine Translation</strong> (Google Translate) — converting text from one language into another. (Others: spam detection, autocomplete/spell-check.)" },
  ],
  assertionReason: [
    { assertion: "The word 'the' typically gets a very low TF-IDF score across a collection of documents.",
      reason: "'the' appears in almost every document, so its Inverse Document Frequency (IDF) value is very small, close to zero.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains A — because 'the' occurs in nearly all documents, its IDF (and hence TF-IDF) shrinks toward zero." },
    { assertion: "The Bag of Words model can distinguish 'dog bites man' from 'man bites dog'.",
      reason: "Bag of Words represents text purely as word counts and ignores the order in which words appear.",
      answer: 3, importance: "medium",
      why: "A is false — Bag of Words cannot tell these two sentences apart, since both produce the identical word-count vector. R is true and is exactly the reason A is false." },
    { assertion: "Lemmatisation generally produces more accurate root words than stemming.",
      reason: "Lemmatisation uses a dictionary and grammar rules to find the true root, while stemming only chops off endings using fixed rules.",
      answer: 0, importance: "medium",
      why: "Both are true, and R correctly explains A — using real vocabulary/grammar rather than blind rule-based chopping is exactly why lemmatisation is more accurate." },
    { assertion: "A script-bot can answer any question a user asks, however it is phrased.",
      reason: "A script-bot follows only a fixed, predefined script or keyword list and cannot handle questions outside it.",
      answer: 3, importance: "medium",
      why: "A is false — a script-bot fails on unscripted questions. R is true and correctly explains why A is false: it is exactly this fixed-script limitation that stops a script-bot from answering anything phrased differently." },
  ],
  caseStudies: [
    { title: "Cleaning a customer review for analysis", importance: "high",
      source: "An online store wants to run sentiment analysis on the customer review: “The delivery boys were running late and the packaging was damaged.” Before feeding it to a model, the text must be processed.",
      parts: [
        { q: "List the tokens produced after tokenising this sentence (ignore punctuation).", marks: 2, answer: "The, delivery, boys, were, running, late, and, the, packaging, was, damaged." },
        { q: "Name two words from this sentence that would likely be removed as stopwords.", marks: 1, answer: "Any two of: 'the', 'were', 'and', 'was' — common, low-meaning words." },
        { q: "Apply stemming (or lemmatisation) to the word 'running' and to the word 'boys', giving their root forms.", marks: 1, answer: "'running' → 'run'; 'boys' → 'boy'." },
      ] },
    { title: "Choosing a chatbot type", importance: "medium",
      source: "A small bakery wants a chatbot on its website. Option A only answers from a fixed list of 10 pre-written question-answer pairs about opening hours and menu items, and says “Sorry, I don't understand” for anything else. Option B is trained on thousands of past customer conversations and can handle differently worded questions about orders, complaints and recommendations.",
      parts: [
        { q: "Identify which option is a script-bot and which is a smart/AI-bot.", marks: 2, answer: "Option A is a <strong>script-bot</strong> (fixed predefined Q&A list, fails outside it). Option B is a <strong>smart/AI-bot</strong> (learns from data and understands varied phrasing)." },
        { q: "Give one advantage of Option B over Option A for this bakery.", marks: 1, answer: "Option B can understand and respond to questions it was never explicitly given, phrased in many different ways, instead of failing whenever a customer's wording doesn't exactly match a pre-written script." },
      ] },
  ],
};
