import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "communication-skills",
  num: 9,
  title: "Communication Skills",
  unit: "employability",
  unitName: "Employability Skills",
  marks: "Part A · Employability",
  minutes: 12,
  blurb: "How a message actually travels from one person to another — verbal, non-verbal, visual and written communication, the communication cycle, the 7 Cs, and the barriers that get in the way.",
  bigIdea: "Communication only succeeds when the receiver understands a message the way the sender meant it — talking is not enough, understanding is the goal.",
  syllabus: [
    "Meaning and importance of communication",
    "Types of communication — verbal, non-verbal, visual and written",
    "The communication cycle",
    "7 Cs of effective communication",
    "Barriers to communication",
    "Importance of feedback",
    "Basics of public speaking",
  ],
  blocks: [
    { t: "h", text: "What is communication?" },
    { t: "p", html: "<strong>Communication</strong> is the process of exchanging information, ideas or feelings between two or more people, so that the <em>receiver understands the message the way the sender intended</em>. It is a two-way process, not a one-way announcement." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "Communication is the <strong>exchange of information or ideas</strong> between a sender and a receiver, in a way that is understood correctly." },

    { t: "h", text: "Types of communication" },
    { t: "p", html: "We send messages in more ways than just talking. The board expects you to name each type with an example." },
    { t: "table", head: ["Type", "How the message travels", "Example"], rows: [
      ["Verbal", "Spoken or written words", "A phone call, a classroom lecture"],
      ["Non-verbal", "Body language, facial expressions, gestures, tone", "A nod, a smile, crossed arms, a wave"],
      ["Visual", "Pictures, signs, colours, graphs", "A traffic sign, a pie chart, an emoji"],
      ["Written", "Words recorded as text", "A letter, an email, a text message"],
    ] },
    { t: "note", kind: "real", html: "A large part of everyday communication is <strong>non-verbal</strong> — your tone of voice, posture and facial expression often say more than the words you use." },

    { t: "h", text: "The communication cycle" },
    { t: "p", html: "Every message follows the same journey, called the <strong>communication cycle</strong>. Missing any step can cause a misunderstanding." },
    { t: "list", ordered: true, items: [
      "<strong>Sender</strong> — the person who starts the communication and has an idea to share.",
      "<strong>Message</strong> — the information the sender wants to convey.",
      "<strong>Encoding</strong> — the sender converts the idea into words, symbols or gestures.",
      "<strong>Channel</strong> — the medium used to send it (speech, call, email, letter).",
      "<strong>Receiver</strong> — the person who gets the message.",
      "<strong>Decoding</strong> — the receiver interprets the message to understand its meaning.",
      "<strong>Feedback</strong> — the receiver's response, telling the sender whether the message was understood.",
    ] },
    { t: "note", kind: "memory", html: "Remember the order: <strong>Sender → Message → Encoding → Channel → Receiver → Decoding → Feedback</strong>. Without feedback, the sender never knows if communication actually succeeded." },

    { t: "h", text: "7 Cs of effective communication" },
    { t: "p", html: "These seven qualities make a message land clearly and are a favourite listing question." },
    { t: "list", items: [
      "<strong>Clear</strong> — the message is easy to understand, with one main idea at a time.",
      "<strong>Concise</strong> — short and to the point, without unnecessary words.",
      "<strong>Concrete</strong> — uses specific facts and details, not vague statements.",
      "<strong>Correct</strong> — accurate facts, correct grammar and spelling.",
      "<strong>Coherent</strong> — ideas are logically connected and stay on topic.",
      "<strong>Complete</strong> — includes all the information the receiver needs.",
      "<strong>Courteous</strong> — polite, respectful and considerate of the receiver.",
    ] },
    { t: "note", kind: "exam", html: "A common 3-mark question asks you to <strong>list and briefly explain any four of the 7 Cs</strong>. Pick the ones you remember best and give one line each." },

    { t: "h", text: "Barriers to communication" },
    { t: "p", html: "A barrier is anything that blocks a message from being understood correctly. Effective communicators try to reduce these." },
    { t: "list", items: [
      "<strong>Physical barriers</strong> — noise, distance, poor network or connection.",
      "<strong>Language barriers</strong> — different languages, jargon or difficult vocabulary.",
      "<strong>Cultural barriers</strong> — differing customs, gestures or social norms.",
      "<strong>Perceptual/attitude barriers</strong> — the sender and receiver interpret the same words differently.",
      "<strong>Emotional barriers</strong> — anger, fear or stress that stops a person from speaking or listening clearly.",
    ] },
    { t: "note", kind: "trap", html: "Do not assume barriers are only about <em>language</em>. Noise, poor mood, wrong assumptions and even a bad phone signal are just as much barriers to communication." },

    { t: "h", text: "Feedback and public speaking" },
    { t: "p", html: "<strong>Feedback</strong> is the receiver's reaction — a reply, a nod, a question — that tells the sender whether the message got through. Without it, the sender is only guessing." },
    { t: "note", kind: "why", title: "Why feedback matters", html: "Feedback completes the communication cycle and lets the sender <strong>correct or clarify</strong> the message if it was misunderstood — this is what makes communication two-way instead of one-way." },
    { t: "p", html: "Good <strong>public speaking</strong> follows a few simple habits: know your audience, plan and organise what you will say, practise beforehand, keep eye contact, use clear body language and a well-modulated voice, and stay calm if you feel nervous." },
  ],
  examFocus: [
    "Definition of communication and why it is a two-way process.",
    "The four types of communication with one example each.",
    "The communication cycle in order, with all seven elements.",
    "The 7 Cs of effective communication, explained briefly.",
    "Barriers to communication — naming and explaining at least three.",
    "Why feedback is essential to the communication cycle.",
  ],
  flashcards: [
    { q: "Define communication.", a: "The process of exchanging information or ideas between a sender and a receiver so that the message is understood as intended." },
    { q: "Name the four types of communication.", a: "Verbal, Non-verbal, Visual and Written communication." },
    { q: "Give an example of non-verbal communication.", a: "A smile, a nod, crossed arms, eye contact or tone of voice." },
    { q: "List the elements of the communication cycle in order.", a: "Sender → Message → Encoding → Channel → Receiver → Decoding → Feedback." },
    { q: "What is 'encoding' in the communication cycle?", a: "The sender converting an idea into words, symbols or gestures so it can be sent." },
    { q: "What is 'decoding' in the communication cycle?", a: "The receiver interpreting the message to understand what the sender meant." },
    { q: "Name any four of the 7 Cs of effective communication.", a: "Any four of: Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous." },
    { q: "What does 'concise' mean in the 7 Cs?", a: "The message is short and to the point, without unnecessary words or details." },
    { q: "Give two examples of barriers to communication.", a: "Any two of: physical/noise, language, cultural, perceptual, or emotional barriers." },
    { q: "Why is feedback important in communication?", a: "It tells the sender whether the message was understood correctly, completing the two-way communication cycle." },
    { q: "Give two basics of good public speaking.", a: "Any two of: know your audience, plan the content, practise beforehand, maintain eye contact, use clear body language and voice." },
  ],
  quiz: [
    { q: "Communication is best described as:", options: ["A one-way announcement", "A two-way exchange of information that must be understood correctly", "Only spoken words", "Writing an email"], answer: 1, why: "Communication succeeds only when the receiver understands the message as the sender meant it — it is a two-way process." },
    { q: "A smile, a nod and crossed arms are examples of:", options: ["Verbal communication", "Written communication", "Non-verbal communication", "Visual communication"], answer: 2, why: "Body language and facial expressions are non-verbal communication." },
    { q: "A traffic sign or a pie chart is an example of:", options: ["Verbal communication", "Visual communication", "Written communication", "Feedback"], answer: 1, why: "Signs, colours and graphs that convey meaning through sight are visual communication." },
    { q: "In the communication cycle, converting an idea into words or gestures is called:", options: ["Decoding", "Feedback", "Encoding", "Channel"], answer: 2, why: "Encoding is the sender's step of turning an idea into a message that can be sent." },
    { q: "Which of these correctly completes the communication cycle?", options: ["Sender → Channel → Message → Receiver", "Sender → Message → Encoding → Channel → Receiver → Decoding → Feedback", "Receiver → Sender → Message → Feedback", "Message → Sender → Receiver → Channel"], answer: 1, why: "The correct order is Sender, Message, Encoding, Channel, Receiver, Decoding, Feedback." },
    { q: "Which of these is NOT one of the 7 Cs of effective communication?", options: ["Clear", "Concise", "Colourful", "Courteous"], answer: 2, why: "The 7 Cs are Clear, Concise, Concrete, Correct, Coherent, Complete and Courteous — 'Colourful' is not one of them." },
    { q: "A message that includes all the necessary information for the receiver is described as:", options: ["Concise", "Complete", "Concrete", "Coherent"], answer: 1, why: "'Complete' means the message contains everything the receiver needs to know." },
    { q: "Poor network signal breaking up a phone call is an example of a:", options: ["Language barrier", "Physical barrier", "Cultural barrier", "Emotional barrier"], answer: 1, why: "Noise, distance and poor connections are physical/environmental barriers to communication." },
    { q: "Why is feedback essential in communication?", options: ["It makes the message longer", "It tells the sender whether the message was understood", "It replaces the need for a receiver", "It is only used in written communication"], answer: 1, why: "Feedback lets the sender know whether the message got across correctly, completing the cycle." },
    { q: "Which of the following is a good public-speaking habit?", options: ["Avoiding eye contact", "Speaking as fast as possible", "Planning and practising your content beforehand", "Ignoring the audience"], answer: 2, why: "Knowing your audience and practising beforehand are basic habits of effective public speaking." },
  ],
  keyTopics: [
    { name: "Definition and importance of communication", importance: "medium", note: "Usually a direct 1-mark definition question." },
    { name: "Types of communication (verbal/non-verbal/visual/written)", importance: "high", note: "Name all four with an example each, or classify a given scenario." },
    { name: "The communication cycle", importance: "high", note: "List the seven elements in order; a very common 2–3 mark question." },
    { name: "7 Cs of effective communication", importance: "high", note: "Name and briefly explain any 3–4 Cs when asked." },
    { name: "Barriers to communication", importance: "medium", note: "Name and explain 2–3 types with a real example each." },
    { name: "Feedback and public speaking basics", importance: "low", note: "Short recall questions on why feedback matters and speaking tips." },
  ],
  written: [
    { q: "Define communication.", marks: 1, kind: "short", importance: "high",
      answer: "Communication is the process of <strong>exchanging information or ideas</strong> between a sender and a receiver, so that the message is understood the way it was intended." },
    { q: "Name the four types of communication.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Verbal, Non-verbal, Visual</strong> and <strong>Written</strong> communication." },
    { q: "What is meant by 'feedback' in the communication cycle?", marks: 1, kind: "short", importance: "medium",
      answer: "Feedback is the <strong>receiver's response</strong> to a message (a reply, question or reaction) that tells the sender whether the message was understood correctly." },
    { q: "List the elements of the communication cycle in the correct order.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Sender → Message → Encoding → Channel → Receiver → Decoding → Feedback.</strong>" },
    { q: "Explain any four of the 7 Cs of effective communication.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Clear</strong> — easy to understand.<br><strong>Concise</strong> — short, without unnecessary words.<br><strong>Correct</strong> — accurate facts, spelling and grammar.<br><strong>Courteous</strong> — polite and respectful towards the receiver." },
    { q: "Differentiate between verbal and non-verbal communication with an example each.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Verbal communication</strong> uses spoken or written words, e.g. a phone call.<br><strong>Non-verbal communication</strong> uses body language, gestures or facial expressions instead of words, e.g. a nod or a smile." },
    { q: "Explain any three barriers to communication with an example of each.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>Physical barrier</strong> — noise or a poor phone signal disrupting a call.<br><strong>Language barrier</strong> — using jargon or a language the receiver doesn't know well.<br><strong>Emotional barrier</strong> — anger or nervousness that stops a person from speaking or listening clearly." },
    { q: "Explain the communication cycle with a suitable example.", marks: 3, kind: "long", importance: "high",
      answer: "Riya (<strong>sender</strong>) wants to invite her friend to a party (<strong>message</strong>). She writes it as a text message (<strong>encoding</strong>) and sends it via her phone (<strong>channel</strong>). Her friend (<strong>receiver</strong>) reads and understands it (<strong>decoding</strong>) and replies 'Yes, I'll come!' (<strong>feedback</strong>), completing the cycle and confirming the message was understood." },
    { q: "What are the basics of good public speaking? Explain any three.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>1. Know your audience</strong> — plan what and how to say it based on who is listening.<br><strong>2. Practise beforehand</strong> — reduces mistakes and builds confidence.<br><strong>3. Use clear body language and eye contact</strong> — keeps the audience engaged and shows confidence, along with a well-modulated voice." },
  ],
  assertionReason: [
    { assertion: "Communication is a two-way process.",
      reason: "Feedback from the receiver tells the sender whether the message was understood correctly.",
      answer: 0, importance: "high",
      why: "Both are true, and R is the correct reason: feedback is what makes communication two-way rather than a one-way announcement." },
    { assertion: "A traffic sign is an example of visual communication.",
      reason: "Visual communication conveys a message only through spoken words.",
      answer: 2, importance: "medium",
      why: "A is true — a traffic sign conveys meaning through a sign/image, which is visual communication. R is false: visual communication uses pictures, signs and colours, not spoken words." },
    { assertion: "Encoding and decoding are both essential steps in the communication cycle.",
      reason: "Encoding is done by the sender to form the message, and decoding is done by the receiver to interpret it.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly explains why both steps are needed — one converts the idea into a message, the other interprets it at the other end." },
  ],
  caseStudies: [
    { title: "A message that went wrong", importance: "high",
      source: "Aman sent a long, jargon-filled email to his classmate about a group project, over a very weak internet connection, late at night when he was frustrated. His classmate replied a day later, confused about what exactly Aman wanted him to do.",
      parts: [
        { q: "Identify two barriers to communication in this situation.", marks: 2, answer: "<strong>Language barrier</strong> — the email used jargon that was hard to understand, and <strong>physical/emotional barrier</strong> — a weak internet connection and Aman's frustration while writing it." },
        { q: "Which of the 7 Cs did Aman's message fail to follow? Name one and explain.", marks: 1, answer: "<strong>Clear</strong> (or Concise) — the message was long and full of jargon, so it was not easy for the receiver to understand quickly." },
        { q: "Why did the delayed, confused reply show a problem with feedback?", marks: 1, answer: "The late and confused reply shows the feedback did not confirm the message was understood — it revealed that the communication cycle had broken down and the message needed to be clarified." },
      ] },
  ],
};
