import type { Chapter } from "@/lib/types";

export const ch10: Chapter = {
  slug: "self-management-skills",
  num: 10,
  title: "Self-Management Skills",
  unit: "employability",
  unitName: "Employability Skills",
  marks: "Part A · Employability",
  minutes: 12,
  blurb: "Knowing your own strengths and weaknesses, handling stress, staying motivated, setting SMART goals, managing time, and thinking positively.",
  bigIdea: "Managing yourself well — your emotions, time and goals — is what turns effort into results; no amount of talent helps if you can't organise and motivate yourself.",
  syllabus: [
    "Self-awareness — strengths and weaknesses",
    "Stress — meaning, causes and management techniques",
    "Self-motivation",
    "Goal setting and SMART goals",
    "Time management",
    "Positive thinking",
  ],
  blocks: [
    { t: "h", text: "Self-awareness" },
    { t: "p", html: "<strong>Self-awareness</strong> means understanding your own personality — your <em>strengths</em>, <em>weaknesses</em>, values, likes and dislikes. It is the starting point of self-management: you cannot improve what you don't first recognise." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "Self-awareness is the ability to <strong>recognise and understand your own emotions, strengths and weaknesses</strong> clearly and honestly." },

    { t: "h", text: "Stress and stress management" },
    { t: "p", html: "<strong>Stress</strong> is the body and mind's reaction to pressure or a difficult situation, such as exams, deadlines or arguments. A small amount of stress can motivate you, but too much affects health and performance." },
    { t: "list", items: [
      "<strong>Symptoms of stress</strong> — headache, sleeplessness, irritability, excessive worrying, loss of concentration.",
      "<strong>Common causes</strong> — exams, deadlines, family problems, peer pressure, uncertainty about the future.",
    ] },
    { t: "list", ordered: true, items: [
      "Practise <strong>time management</strong> so work doesn't pile up.",
      "Do <strong>yoga, meditation or deep breathing</strong> exercises regularly.",
      "Get enough <strong>sleep and exercise</strong>.",
      "Talk to someone you trust about what is worrying you.",
      "Take short breaks and pursue a hobby to relax.",
    ] },
    { t: "note", kind: "why", title: "The goal of stress management", html: "Stress management aims to strike a <strong>balance between work, relationships, relaxation and fun</strong> — not to remove all pressure, but to respond to it in a healthy way." },

    { t: "h", text: "Self-motivation" },
    { t: "p", html: "<strong>Self-motivation</strong> is the inner drive that pushes you to start and continue working towards a goal, without needing someone else to push you. Motivated people set clear goals, stay positive after setbacks, and reward their own progress." },
    { t: "note", kind: "real", html: "A student who keeps revising even without a teacher checking on them, because they want to do well, is showing <strong>self-motivation</strong>." },

    { t: "h", text: "Goal setting and SMART goals" },
    { t: "p", html: "A <strong>goal</strong> is a dream with a deadline. Setting clear goals turns a vague wish (“I want to do well”) into an actionable plan. The board expects you to know the <strong>SMART</strong> framework for writing a good goal." },
    { t: "table", head: ["Letter", "Stands for", "Means the goal should be…"], rows: [
      ["S", "Specific", "Clearly defined, not vague"],
      ["M", "Measurable", "You can track progress with a number or clear sign"],
      ["A", "Achievable", "Realistically possible with your resources"],
      ["R", "Relevant", "Matters to your bigger purpose"],
      ["T", "Time-bound", "Has a clear deadline"],
    ] },
    { t: "note", kind: "exam", html: "A frequent question: “Convert this vague goal into a SMART goal.” E.g. vague: <em>“I want to improve my marks.”</em> SMART: <em>“I will score 80% in the next Maths test by studying one extra hour daily for the next four weeks.”</em>" },

    { t: "h", text: "Time management" },
    { t: "p", html: "<strong>Time management</strong> means planning and controlling how much time you spend on different tasks, so important work gets done without last-minute panic." },
    { t: "list", items: [
      "Make a <strong>to-do list</strong> and prioritise the most important/urgent tasks first.",
      "Avoid <strong>procrastination</strong> — putting off work you should be doing now.",
      "Set realistic time limits for each task and avoid multitasking on important work.",
      "Keep some buffer time for unexpected delays.",
    ] },
    { t: "note", kind: "trap", html: "Time management is not about doing <em>more</em> work — it is about doing the <strong>right work at the right time</strong>, using tools like priority lists and schedules." },

    { t: "h", text: "Positive thinking" },
    { t: "p", html: "<strong>Positive thinking</strong> is the habit of focusing on solutions and opportunities rather than dwelling on problems and failures. It helps you stay resilient, recover from setbacks faster, and keep working towards your goals." },
    { t: "note", kind: "memory", html: "Six self-management ideas to remember together: <strong>self-awareness, stress management, self-motivation, goal setting, time management and positive thinking</strong> — they all support each other." },
  ],
  examFocus: [
    "Meaning of self-awareness and why it matters.",
    "Symptoms, causes and techniques of stress management.",
    "Meaning of self-motivation with an example.",
    "SMART goals — the full form and converting a vague goal into a SMART one.",
    "Time management techniques (to-do lists, priorities, avoiding procrastination).",
    "Meaning and benefit of positive thinking.",
  ],
  flashcards: [
    { q: "What is self-awareness?", a: "The ability to recognise and understand your own emotions, strengths and weaknesses clearly and honestly." },
    { q: "What is stress?", a: "The body and mind's reaction to pressure or a difficult situation, such as exams or deadlines." },
    { q: "Name two symptoms of stress.", a: "Any two of: headache, sleeplessness, irritability, excessive worrying, loss of concentration." },
    { q: "Name two stress management techniques.", a: "Any two of: time management, yoga/meditation/deep breathing, adequate sleep and exercise, talking to someone trusted." },
    { q: "What is self-motivation?", a: "The inner drive that pushes a person to start and continue working towards a goal without needing outside pressure." },
    { q: "Expand SMART in goal setting.", a: "Specific, Measurable, Achievable, Relevant, Time-bound." },
    { q: "Why must a goal be 'Time-bound'?", a: "So it has a clear deadline, which creates urgency and lets you track whether you are on schedule." },
    { q: "What is time management?", a: "Planning and controlling how you spend time on different tasks so important work is completed without last-minute rush." },
    { q: "What is procrastination, and why is it a problem?", a: "Delaying or putting off work that should be done now; it causes last-minute stress and lower quality work." },
    { q: "What is positive thinking?", a: "The habit of focusing on solutions and opportunities rather than problems and failures." },
    { q: "Give one example of self-motivation in a student.", a: "Revising regularly on their own, without a teacher or parent checking, because they want to do well." },
  ],
  quiz: [
    { q: "Self-awareness is best described as:", options: ["Knowing what others think of you", "Recognising your own emotions, strengths and weaknesses", "Being famous", "Following a strict timetable"], answer: 1, why: "Self-awareness means understanding your own personality — your strengths, weaknesses and emotions." },
    { q: "Which of these is a common symptom of stress?", options: ["Improved sleep", "Sleeplessness and irritability", "Increased appetite for work only", "Better concentration"], answer: 1, why: "Sleeplessness, irritability and excessive worrying are typical symptoms of stress." },
    { q: "Which is a healthy stress management technique?", options: ["Ignoring deadlines completely", "Deep breathing, yoga or meditation", "Working without any breaks", "Avoiding sleep to finish work"], answer: 1, why: "Yoga, meditation and deep breathing are recommended techniques to manage stress in a healthy way." },
    { q: "A student who studies regularly without anyone reminding them is showing:", options: ["Time management only", "Self-motivation", "Stress", "Poor self-awareness"], answer: 1, why: "Acting on an inner drive to achieve a goal, without external pressure, is self-motivation." },
    { q: "In the SMART goal framework, 'M' stands for:", options: ["Motivating", "Measurable", "Modern", "Manageable"], answer: 1, why: "M stands for Measurable — the goal's progress can be tracked with a number or clear sign." },
    { q: "'I will score 85% in the next Science test by revising one chapter every weekend for two months' is an example of:", options: ["A vague goal", "A SMART goal", "A stress symptom", "A communication barrier"], answer: 1, why: "It is specific, measurable, achievable, relevant and has a clear time frame — a SMART goal." },
    { q: "Delaying important work until the last minute is called:", options: ["Prioritising", "Procrastination", "Self-motivation", "Positive thinking"], answer: 1, why: "Procrastination is putting off work that should be done now, which causes last-minute stress." },
    { q: "A good time management practice is to:", options: ["Do the easiest tasks first regardless of deadline", "Make a to-do list and prioritise urgent/important tasks", "Multitask on all important work at once", "Avoid planning altogether"], answer: 1, why: "Prioritising tasks using a to-do list is a core time management technique." },
    { q: "Positive thinking mainly helps a person to:", options: ["Avoid all problems in life", "Focus on solutions and recover from setbacks", "Ignore feedback from others", "Work without any goals"], answer: 1, why: "Positive thinking is about focusing on solutions/opportunities and bouncing back from failure, not avoiding problems." },
    { q: "Which combination best describes good self-management?", options: ["Only working hard without rest", "Self-awareness, stress management, motivation, goal setting, time management and positive thinking together", "Following only a strict routine with no goals", "Avoiding all stress permanently"], answer: 1, why: "Self-management combines all these skills together — none of them alone is enough." },
  ],
  keyTopics: [
    { name: "Self-awareness (strengths and weaknesses)", importance: "medium", note: "Simple 1-mark definition; sometimes asked with an example." },
    { name: "Stress — symptoms, causes and management", importance: "high", note: "List symptoms/causes and explain 2–3 management techniques." },
    { name: "Self-motivation", importance: "medium", note: "Define and give a real-life example, often in case studies." },
    { name: "SMART goals", importance: "high", note: "Expand SMART and convert a vague goal into a SMART one — very common." },
    { name: "Time management techniques", importance: "high", note: "To-do lists, prioritising, avoiding procrastination." },
    { name: "Positive thinking", importance: "low", note: "Short recall of meaning and benefit." },
  ],
  written: [
    { q: "What is self-awareness?", marks: 1, kind: "short", importance: "medium",
      answer: "Self-awareness is the ability to <strong>recognise and understand</strong> your own emotions, strengths and weaknesses clearly and honestly." },
    { q: "Expand SMART in the context of goal setting.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>S</strong>pecific, <strong>M</strong>easurable, <strong>A</strong>chievable, <strong>R</strong>elevant, <strong>T</strong>ime-bound." },
    { q: "What is self-motivation? Give one example.", marks: 1, kind: "short", importance: "medium",
      answer: "Self-motivation is the <strong>inner drive</strong> that pushes a person to work towards a goal without outside pressure. Example: a student revising regularly on their own to do well in exams." },
    { q: "List two symptoms and two causes of stress.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Symptoms:</strong> headache, sleeplessness (also irritability, loss of concentration).<br><strong>Causes:</strong> exams/deadlines, family problems (also peer pressure, uncertainty)." },
    { q: "What is time management? Give two techniques to manage time well.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Time management</strong> means planning and controlling how time is spent on different tasks so important work is completed on time.<br><strong>Techniques:</strong> making a to-do list and prioritising urgent/important tasks; avoiding procrastination." },
    { q: "Differentiate between self-motivation and stress.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Self-motivation</strong> is a positive inner drive that pushes a person towards a goal. <strong>Stress</strong> is the body and mind's reaction to pressure, which if excessive, can reduce performance and health — one drives you forward, the other can hold you back if unmanaged." },
    { q: "Convert the vague goal 'I want to get better at Maths' into a SMART goal, explaining each part.", marks: 3, kind: "long", importance: "high",
      answer: "SMART goal: <em>“I will score at least 80% in my next Maths unit test by solving 10 practice problems every day for the next three weeks.”</em><br><strong>Specific</strong> — Maths score improvement. <strong>Measurable</strong> — 80% target, 10 problems/day. <strong>Achievable</strong> — a realistic daily target. <strong>Relevant</strong> — matters to overall performance. <strong>Time-bound</strong> — within three weeks, before the next test." },
    { q: "Explain any three techniques of stress management.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>1. Time management</strong> — planning work in advance so it doesn't pile up and cause panic.<br><strong>2. Relaxation techniques</strong> — yoga, meditation or deep breathing to calm the mind.<br><strong>3. Healthy habits</strong> — adequate sleep and exercise, and talking to someone trusted about worries, instead of bottling them up." },
    { q: "Explain the importance of positive thinking and time management in achieving one's goals.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>Positive thinking</strong> helps a person stay resilient — focusing on solutions rather than giving up after setbacks, which keeps motivation alive.<br><strong>Time management</strong> ensures the steps needed to reach a goal actually get done on schedule, through prioritising and avoiding procrastination.<br>Together, they turn a goal from a wish into something achieved — positive thinking keeps you going, time management keeps you on track." },
  ],
  assertionReason: [
    { assertion: "Setting SMART goals makes it easier to achieve them than setting vague goals.",
      reason: "SMART goals are specific, measurable and time-bound, so progress can be tracked clearly.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why: being specific, measurable and time-bound makes progress trackable and the goal easier to work towards." },
    { assertion: "A student who revises daily without being reminded by a parent is showing self-motivation.",
      reason: "Self-motivation means being pushed to act only by outside rewards or punishments.",
      answer: 2, importance: "medium",
      why: "A is true — acting on inner drive without reminders is self-motivation. R is false: self-motivation specifically means acting <em>without</em> needing outside pressure, the opposite of what R claims." },
    { assertion: "Time management is only about doing as many tasks as possible in a day.",
      reason: "Prioritising urgent and important tasks first helps complete meaningful work without last-minute stress.",
      answer: 3, importance: "medium",
      why: "A is false — time management is about doing the <em>right</em> tasks at the right time, not maximising the number of tasks. R is true and describes what good time management actually involves." },
  ],
  caseStudies: [
    { title: "Managing exam-time pressure", importance: "high",
      source: "With board exams two months away, Riya feels overwhelmed — she has headaches, is not sleeping well, and keeps postponing her revision, telling herself she'll 'start seriously tomorrow'. Her only goal so far is 'I want to do well in exams.'",
      parts: [
        { q: "Identify two symptoms of stress Riya is showing.", marks: 2, answer: "Headaches and sleeplessness (also: constantly postponing work, which suggests worry/anxiety)." },
        { q: "What behaviour is Riya showing when she keeps saying she'll 'start tomorrow', and how does it affect her time management?", marks: 1, answer: "This is <strong>procrastination</strong> — delaying necessary work, which leads to a pile-up of revision and last-minute stress instead of steady progress." },
        { q: "Rewrite Riya's goal 'I want to do well in exams' as a SMART goal.", marks: 2, answer: "<em>“I will revise one chapter of each subject every week and complete a full revision cycle by two weeks before the board exams, aiming for at least 80% in each subject.”</em> — this is specific, measurable, achievable, relevant and time-bound." },
      ] },
  ],
};
