import type { Chapter } from "@/lib/types";

export const ch11: Chapter = {
  slug: "ict-skills",
  num: 11,
  title: "ICT Skills",
  unit: "employability",
  unitName: "Employability Skills",
  marks: "Part A · Employability",
  minutes: 12,
  blurb: "What ICT means, hardware and software basics, operating systems, organising files and folders, basic troubleshooting, backing up data, and staying safe online.",
  bigIdea: "ICT skills are the everyday computer habits — organising files, keeping data backed up and safe, and knowing basic fixes — that let you use technology confidently instead of being confused by it.",
  syllabus: [
    "What is ICT (Information and Communication Technology)",
    "Hardware and software basics",
    "Operating system basics",
    "File and folder management",
    "Basic troubleshooting and maintenance",
    "Data backup",
    "Internet and online safety",
  ],
  blocks: [
    { t: "h", text: "What is ICT?" },
    { t: "p", html: "<strong>ICT (Information and Communication Technology)</strong> refers to all the technologies used to store, process, retrieve and communicate information — computers, phones, the internet, software and networks together." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "ICT is the use of <strong>computers, communication devices and the internet</strong> to create, store, exchange and manage information." },

    { t: "h", text: "Hardware and software" },
    { t: "p", html: "A computer system is made of two parts working together: things you can physically touch, and the instructions that tell them what to do." },
    { t: "compare",
      left: { title: "Hardware", items: [
        "Physical, touchable parts of a computer",
        "Examples: keyboard, mouse, monitor, CPU, printer",
        "Cannot work without software telling it what to do",
      ] },
      right: { title: "Software", items: [
        "A set of instructions/programs the hardware runs",
        "Examples: operating system, MS Word, a web browser, a game",
        "Cannot run without hardware to execute it on",
      ] } },
    { t: "note", kind: "memory", html: "You can <strong>touch hardware</strong> but you can only <strong>see software work</strong> — hardware is the body, software is the instructions that make it act." },

    { t: "h", text: "Operating system basics" },
    { t: "p", html: "An <strong>Operating System (OS)</strong> is the most important software on any device — it manages the hardware and lets other software (applications) run on top of it." },
    { t: "list", items: [
      "Manages files, memory, storage and connected devices (printer, mouse, etc.).",
      "Provides the interface (icons, windows, menus) you interact with.",
      "Runs and manages other application programs.",
      "Examples: Windows, macOS, Linux, Android, iOS.",
    ] },
    { t: "note", kind: "why", title: "Why every device needs one", html: "Without an OS, application software would have no way to talk to the hardware — the OS is the <strong>bridge</strong> between the user, the applications and the hardware." },

    { t: "h", text: "File and folder management" },
    { t: "p", html: "A <strong>file</strong> stores actual data (a document, photo or video); a <strong>folder (directory)</strong> is a container used to organise related files together." },
    { t: "list", items: [
      "Use clear, descriptive <strong>file names</strong> instead of generic ones like “Document1”.",
      "Group related files into <strong>folders and sub-folders</strong> (e.g. a “Class 10” folder with subject sub-folders).",
      "Keep a consistent structure so files are easy to <strong>find, move, copy, rename or delete</strong> later.",
    ] },
    { t: "note", kind: "exam", html: "A common question: “Differentiate between a file and a folder.” Answer: a <strong>file</strong> holds actual content/data; a <strong>folder</strong> is only a container that organises files (and other folders) — it holds no content of its own." },

    { t: "h", text: "Basic troubleshooting and maintenance" },
    { t: "p", html: "<strong>Troubleshooting</strong> means identifying and fixing a simple problem with a device. Regular <strong>maintenance</strong> prevents many problems before they start." },
    { t: "list", items: [
      "If a device hangs or freezes, try <strong>restarting</strong> it first.",
      "Keep software and antivirus <strong>updated</strong> to fix bugs and security holes.",
      "Delete unused/temporary files to free up storage space.",
      "Check that all <strong>cables/connections</strong> are secure if a peripheral (printer, mouse) isn't responding.",
    ] },

    { t: "h", text: "Data backup and online safety" },
    { t: "p", html: "A <strong>backup</strong> is a copy of important data kept in another location, so it is not lost if the original device is damaged, lost or infected." },
    { t: "list", items: [
      "Backup options: an external hard disk / pen drive, or <strong>cloud storage</strong> (Google Drive, OneDrive).",
      "Back up regularly, not just once — especially before major updates.",
    ] },
    { t: "note", kind: "trap", html: "A backup stored on the <em>same</em> device as the original is not a safe backup — if that device is lost, stolen or damaged, both copies are gone. Always keep a backup in a <strong>separate location</strong>." },
    { t: "p", html: "Staying safe online means using <strong>strong, unique passwords</strong>, never sharing personal information with strangers, checking a site is genuine before entering details, and being cautious of suspicious links, emails or downloads." },
  ],
  examFocus: [
    "Meaning of ICT and everyday examples.",
    "Hardware vs software — definitions and examples of each.",
    "Role of the operating system.",
    "Difference between a file and a folder; good file-management habits.",
    "Simple troubleshooting steps and why maintenance matters.",
    "Why and how to back up data; basic online-safety practices.",
  ],
  flashcards: [
    { q: "What does ICT stand for?", a: "Information and Communication Technology." },
    { q: "Define hardware, with two examples.", a: "The physical, touchable parts of a computer, e.g. keyboard, monitor, CPU, printer." },
    { q: "Define software, with two examples.", a: "The set of instructions/programs that run on hardware, e.g. an operating system, MS Word, a web browser." },
    { q: "What is an operating system?", a: "The main software that manages a device's hardware and lets other application software run, e.g. Windows, Android, macOS." },
    { q: "Differentiate between a file and a folder.", a: "A file stores actual data/content; a folder is a container used to organise files (and other folders) and holds no content of its own." },
    { q: "Give two good file-management habits.", a: "Any two of: using clear descriptive file names, grouping related files into folders/sub-folders, keeping a consistent structure." },
    { q: "What is troubleshooting?", a: "The process of identifying and fixing a simple problem with a device, e.g. restarting a frozen computer." },
    { q: "Give one basic device maintenance habit.", a: "Any one of: keeping software/antivirus updated, deleting unused files, checking cable connections." },
    { q: "What is a data backup?", a: "A copy of important data kept in a separate location (external drive or cloud storage) so it isn't lost if the original is damaged or lost." },
    { q: "Give two backup storage options.", a: "An external hard disk/pen drive, and cloud storage (e.g. Google Drive, OneDrive)." },
    { q: "Give two basic online safety practices.", a: "Any two of: using strong, unique passwords; not sharing personal information with strangers; avoiding suspicious links/downloads." },
  ],
  quiz: [
    { q: "ICT stands for:", options: ["Internet Computer Technology", "Information and Communication Technology", "Integrated Circuit Technology", "Internal Computing Terminal"], answer: 1, why: "ICT stands for Information and Communication Technology." },
    { q: "Which of these is an example of hardware?", options: ["MS Word", "A web browser", "A keyboard", "Windows operating system"], answer: 2, why: "A keyboard is a physical, touchable part of a computer, so it is hardware; the others are software." },
    { q: "Which of these is an example of software?", options: ["Monitor", "Printer", "Mouse", "Operating system"], answer: 3, why: "An operating system is a set of instructions/programs, so it is software; the others are physical hardware devices." },
    { q: "The main role of an operating system is to:", options: ["Print documents only", "Manage hardware and let other software run", "Only browse the internet", "Store backup files"], answer: 1, why: "The OS manages the hardware and provides the platform on which application software runs." },
    { q: "The difference between a file and a folder is that:", options: ["A file holds data, a folder only organises files", "A folder holds data, a file only organises folders", "There is no difference", "A file can only hold images"], answer: 0, why: "A file stores actual data/content, while a folder is a container used to organise files (and other folders)." },
    { q: "If a computer freezes, the first basic troubleshooting step is usually to:", options: ["Throw it away", "Restart the device", "Ignore it permanently", "Delete the operating system"], answer: 1, why: "Restarting a frozen device is the most common first step in basic troubleshooting." },
    { q: "Which is a good practice for regular device maintenance?", options: ["Never updating software", "Keeping software and antivirus updated", "Filling up all storage with unused files", "Disconnecting all cables permanently"], answer: 1, why: "Keeping software and antivirus updated fixes bugs and security issues, preventing many problems." },
    { q: "A data backup should ideally be stored:", options: ["On the same device only, for convenience", "In a separate location, like an external drive or cloud storage", "Nowhere, since backups aren't needed", "Only on paper"], answer: 1, why: "A backup on a separate device or cloud storage protects data even if the original device is lost or damaged." },
    { q: "Which of these is a safe online practice?", options: ["Sharing your password with a stranger who asks online", "Using strong, unique passwords for each account", "Clicking every link sent by an unknown sender", "Entering personal details on any website that asks"], answer: 1, why: "Using strong, unique passwords is a basic online-safety practice; the other options are unsafe." },
    { q: "Cloud storage such as Google Drive is mainly used for:", options: ["Physically repairing hardware", "Backing up and accessing files from anywhere online", "Replacing the operating system", "Troubleshooting a frozen screen"], answer: 1, why: "Cloud storage lets users back up and access their files over the internet from any device." },
  ],
  keyTopics: [
    { name: "Meaning of ICT", importance: "low", note: "Simple 1-mark definition question." },
    { name: "Hardware vs software", importance: "high", note: "Define both and classify given examples correctly." },
    { name: "Role of the operating system", importance: "medium", note: "Explain what an OS does and name examples." },
    { name: "File vs folder / file management", importance: "high", note: "Common differentiate-type question with good-practice tips." },
    { name: "Troubleshooting and maintenance", importance: "medium", note: "Basic fixes (restart, update) and preventive habits." },
    { name: "Data backup and online safety", importance: "high", note: "Why backups matter, where to store them, and basic safety rules." },
  ],
  written: [
    { q: "What is ICT?", marks: 1, kind: "short", importance: "medium",
      answer: "ICT (Information and Communication Technology) is the use of <strong>computers, communication devices and the internet</strong> to create, store, exchange and manage information." },
    { q: "Define hardware and software.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Hardware</strong> is the physical, touchable part of a computer (e.g. keyboard, monitor). <strong>Software</strong> is the set of instructions/programs that run on the hardware (e.g. an operating system, an app)." },
    { q: "What is the role of an operating system?", marks: 1, kind: "short", importance: "medium",
      answer: "An operating system <strong>manages the computer's hardware and resources</strong> and provides the platform on which other application software can run." },
    { q: "Differentiate between a file and a folder.", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>file</strong> stores actual data or content, such as a document, photo or video. A <strong>folder</strong> is only a container used to organise related files (and other folders) — it holds no content of its own." },
    { q: "What is a data backup, and why is it important?", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>backup</strong> is a copy of important data stored in a separate location. It is important because it protects data from being permanently lost if the original device is damaged, lost, stolen or infected by malware." },
    { q: "Give two examples each of hardware and software.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Hardware:</strong> keyboard, monitor (also mouse, CPU, printer).<br><strong>Software:</strong> operating system, MS Word (also a web browser, a game)." },
    { q: "Explain any three good file and folder management habits.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>1.</strong> Use clear, descriptive file names instead of generic ones like “Document1”.<br><strong>2.</strong> Group related files into folders and sub-folders (e.g. a subject-wise folder structure for school work).<br><strong>3.</strong> Keep a consistent, logical structure so files can be found, renamed, copied or deleted easily later." },
    { q: "Describe three basic troubleshooting or maintenance steps for a computer.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>1.</strong> Restart the device if it freezes or hangs — this fixes many temporary glitches.<br><strong>2.</strong> Keep the operating system and antivirus software updated to fix bugs and close security gaps.<br><strong>3.</strong> Regularly delete unused/temporary files and check cable/device connections if a peripheral like a printer stops responding." },
    { q: "Explain the importance of data backup and describe two safe practices for storing backups and staying safe online.", marks: 3, kind: "long", importance: "high",
      answer: "A backup protects important data from being lost due to device damage, theft or malware, since it keeps a copy in a separate location.<br><strong>Safe practices:</strong> store backups on an external drive or cloud storage rather than the same device as the original; and follow online safety habits like using strong, unique passwords and avoiding suspicious links or unknown downloads." },
  ],
  assertionReason: [
    { assertion: "A computer cannot function without both hardware and software.",
      reason: "Hardware provides the physical parts, while software provides the instructions that make the hardware perform tasks.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why: hardware executes tasks, but only software tells it what tasks to perform." },
    { assertion: "Storing a backup only on the same laptop as the original files is a safe backup practice.",
      reason: "If the laptop is lost, stolen or damaged, both the original data and the backup are lost together.",
      answer: 3, importance: "high",
      why: "A is false — storing a backup on the same device is unsafe, not safe. R is true and actually explains why A is wrong: losing the device loses both copies at once." },
    { assertion: "The operating system is considered the most important software on a computer.",
      reason: "The operating system manages the hardware and allows other application software to run.",
      answer: 0, importance: "medium",
      why: "Both are true, and R gives the correct reason — without the OS acting as the bridge between hardware and applications, no other software could run." },
  ],
  caseStudies: [
    { title: "A messy laptop", importance: "high",
      source: "Karan's laptop has hundreds of files saved directly on the desktop with names like 'New Document (12)' and 'Untitled'. He has never backed up his project work, and last month, when his laptop's hard disk failed, he lost all his files. His antivirus software also hasn't been updated in over a year.",
      parts: [
        { q: "Suggest two improvements Karan should make to his file and folder management.", marks: 2, answer: "He should use clear, descriptive file names instead of 'Untitled'/'New Document', and organise his files into folders and sub-folders (e.g. by subject or project) instead of saving everything loose on the desktop." },
        { q: "Explain what Karan should have done to avoid losing all his files when the hard disk failed.", marks: 1, answer: "He should have kept a <strong>regular backup</strong> of his important files in a separate location, such as an external hard disk or cloud storage, so the data would survive even if the laptop's hard disk failed." },
        { q: "Why is it a problem that Karan's antivirus hasn't been updated in over a year?", marks: 1, answer: "Outdated antivirus software cannot protect against newer viruses and security threats, making his device more vulnerable to attacks and data loss — regular updates are a basic maintenance habit." },
      ] },
  ],
};
