import type { Chapter } from "@/lib/types";

export const ch12: Chapter = {
  slug: "entrepreneurial-skills",
  num: 12,
  title: "Entrepreneurial Skills",
  unit: "employability",
  unitName: "Employability Skills",
  marks: "Part A · Employability",
  minutes: 12,
  blurb: "Who an entrepreneur is, how entrepreneurship differs from a regular job, the qualities and functions of an entrepreneur, common myths, and how entrepreneurs help society.",
  bigIdea: "An entrepreneur doesn't just work for money — they spot a problem worth solving, take the risk of building something new around it, and create value (and jobs) for others in the process.",
  syllabus: [
    "Who is an entrepreneur",
    "Entrepreneurship vs wage employment",
    "Qualities of a successful entrepreneur",
    "Functions of an entrepreneur",
    "Myths about entrepreneurship",
    "How entrepreneurs help society",
  ],
  blocks: [
    { t: "h", text: "Who is an entrepreneur?" },
    { t: "p", html: "An <strong>entrepreneur</strong> is a person who identifies a problem or an opportunity, and takes the <em>risk</em> of starting and running a new business or venture to solve it — instead of working for someone else's business." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "An entrepreneur is a person who <strong>starts and manages a new business</strong>, taking on financial risk in the hope of profit, by turning an idea into a working venture." },

    { t: "h", text: "Entrepreneurship vs wage employment" },
    { t: "p", html: "These are two different ways to earn a living, and the board often asks you to distinguish them clearly." },
    { t: "compare",
      left: { title: "Wage employment", items: [
        "Works for someone else's business",
        "Earns a fixed, regular salary/wage",
        "Follows instructions from an employer",
        "Takes little to no financial risk",
      ] },
      right: { title: "Entrepreneurship", items: [
        "Owns and runs their own business",
        "Income depends on the business's profit (uncertain)",
        "Makes their own decisions",
        "Takes on financial risk and responsibility",
      ] } },
    { t: "note", kind: "trap", html: "A common mistake is thinking entrepreneurship is “safer” because you're your own boss. In reality, entrepreneurs take on <strong>more financial risk and uncertainty</strong> than a salaried employee." },

    { t: "h", text: "Qualities of a successful entrepreneur" },
    { t: "p", html: "Certain personal qualities are commonly seen in entrepreneurs who succeed." },
    { t: "list", items: [
      "<strong>Creativity and innovation</strong> — coming up with new ideas or better ways of doing things.",
      "<strong>Risk-taking ability</strong> — willing to invest time/money without a guaranteed outcome.",
      "<strong>Self-confidence and self-motivation</strong> — believing in the idea and pushing through setbacks.",
      "<strong>Hard work and perseverance</strong> — staying committed even when things are difficult.",
      "<strong>Good decision-making and planning</strong> — thinking ahead and adapting to problems.",
    ] },

    { t: "h", text: "Functions of an entrepreneur" },
    { t: "p", html: "Beyond having the right qualities, an entrepreneur actually performs several roles to build a working enterprise." },
    { t: "list", ordered: true, items: [
      "<strong>Idea generation</strong> — identifying a problem or a gap in the market.",
      "<strong>Planning</strong> — deciding what resources (money, people, materials) are needed.",
      "<strong>Arranging resources</strong> — raising funds, hiring people, sourcing materials.",
      "<strong>Organising production/service</strong> — turning the plan into an actual product or service.",
      "<strong>Risk-bearing</strong> — accepting the possibility of loss if the venture doesn't succeed.",
      "<strong>Innovation</strong> — continuously improving the product, service or process.",
    ] },
    { t: "note", kind: "memory", html: "Remember entrepreneurs don't just have an idea — they <strong>plan it, fund it, build it and bear the risk</strong> of it, from start to finish." },

    { t: "h", text: "Myths about entrepreneurship" },
    { t: "p", html: "Several common beliefs about entrepreneurs are actually false — the board sometimes tests these directly as true/false or assertion-reason items." },
    { t: "table", head: ["Myth", "Reality"], rows: [
      ["Entrepreneurs are born, not made", "Entrepreneurial skills can be learned and developed through practice and experience"],
      ["You need a lot of money to start", "Many successful ventures start small, with limited capital, and grow gradually"],
      ["Entrepreneurs never fail", "Failure is common; many successful entrepreneurs failed before succeeding"],
      ["Entrepreneurship is only for a special few / geniuses", "Anyone with the right skills, planning and persistence can become an entrepreneur"],
    ] },
    { t: "note", kind: "exam", html: "A frequent question: “State any two myths about entrepreneurship and the reality.” Pick two rows from the table above and explain them in your own words." },

    { t: "h", text: "How entrepreneurs help society" },
    { t: "p", html: "Entrepreneurship benefits more than just the entrepreneur — it has a ripple effect on the wider community." },
    { t: "list", items: [
      "Creates <strong>employment</strong> for others by hiring workers.",
      "Introduces new <strong>products, services and innovations</strong> that improve people's lives.",
      "Contributes to the <strong>economy</strong> through taxes and business activity.",
      "Can solve local or social problems (e.g. clean energy, education access) while running a viable business.",
    ] },
    { t: "note", kind: "real", html: "A small local entrepreneur who starts a recycling business doesn't just earn a living — they also create jobs and help reduce waste in their community." },
  ],
  examFocus: [
    "Definition of an entrepreneur.",
    "Entrepreneurship vs wage employment — the key differences.",
    "Qualities of a successful entrepreneur.",
    "Functions performed by an entrepreneur, in a logical order.",
    "Common myths about entrepreneurship and the actual reality.",
    "How entrepreneurship benefits society, not just the entrepreneur.",
  ],
  flashcards: [
    { q: "Define an entrepreneur.", a: "A person who identifies a problem or opportunity and takes the risk of starting and running a new business to solve it." },
    { q: "What is wage employment?", a: "Working for someone else's business for a fixed, regular salary, following the employer's instructions." },
    { q: "Give one key difference between entrepreneurship and wage employment.", a: "An entrepreneur takes on financial risk for uncertain profit and makes their own decisions; a wage employee earns a fixed salary with little risk." },
    { q: "Name two qualities of a successful entrepreneur.", a: "Any two of: creativity/innovation, risk-taking ability, self-confidence, hard work/perseverance, good decision-making." },
    { q: "Name two functions of an entrepreneur.", a: "Any two of: idea generation, planning, arranging resources, organising production, risk-bearing, innovation." },
    { q: "What does 'risk-bearing' mean for an entrepreneur?", a: "Accepting the possibility of financial loss if the venture does not succeed." },
    { q: "State one myth about entrepreneurship and the reality.", a: "Myth: entrepreneurs are born, not made. Reality: entrepreneurial skills can be learned and developed through practice." },
    { q: "Is a large amount of money always needed to start a business?", a: "No — many successful ventures start small with limited capital and grow gradually over time." },
    { q: "Give one way entrepreneurs help society.", a: "They create employment for others by hiring workers (also: introduce new products/services, contribute to the economy)." },
    { q: "Give an example of an entrepreneur solving a social problem through business.", a: "A local entrepreneur starting a recycling business, which creates jobs and also reduces waste in the community." },
  ],
  quiz: [
    { q: "An entrepreneur is best defined as a person who:", options: ["Only works for a fixed monthly salary", "Starts and runs a new business, taking on financial risk", "Never takes any risk", "Only invests in the stock market"], answer: 1, why: "An entrepreneur identifies an opportunity and takes on risk to start and run their own venture." },
    { q: "Which of these is a feature of wage employment, not entrepreneurship?", options: ["Owning the business", "Bearing financial risk", "Earning a fixed, regular salary", "Making all major decisions independently"], answer: 2, why: "A wage employee earns a fixed salary and follows an employer's instructions, unlike an entrepreneur." },
    { q: "Which is a quality commonly seen in successful entrepreneurs?", options: ["Fear of taking any risk", "Creativity and willingness to take risks", "Avoiding hard work", "Relying only on luck"], answer: 1, why: "Creativity, risk-taking ability and hard work are common qualities of successful entrepreneurs." },
    { q: "Accepting the possibility of financial loss if a venture fails is called:", options: ["Wage employment", "Risk-bearing", "Idea generation", "Feedback"], answer: 1, why: "Risk-bearing is the entrepreneurial function of accepting potential loss for the chance of profit." },
    { q: "Which of these is the correct order of an entrepreneur's basic functions?", options: ["Risk-bearing → Idea generation → Planning", "Idea generation → Planning → Arranging resources → Organising production", "Organising production → Idea generation → Planning", "Planning → Risk-bearing → Idea generation"], answer: 1, why: "An entrepreneur first identifies an idea, then plans, arranges resources, and organises production." },
    { q: "'Entrepreneurs are born, not made' is:", options: ["A proven fact", "A myth — entrepreneurial skills can be learned", "True only for large businesses", "The definition of entrepreneurship"], answer: 1, why: "This is a common myth; entrepreneurial skills can actually be developed through learning and practice." },
    { q: "Which statement about starting a business is TRUE?", options: ["A huge amount of capital is always required", "Many ventures start small and grow gradually", "Only geniuses can start a business", "Entrepreneurs never fail"], answer: 1, why: "Many successful businesses start small with limited capital and grow over time — the other options are myths." },
    { q: "Which of these shows how entrepreneurship benefits society?", options: ["It only benefits the entrepreneur", "It creates employment and can introduce useful new products/services", "It reduces the number of jobs available", "It has no effect on the economy"], answer: 1, why: "Entrepreneurship benefits society by creating jobs, introducing innovations, and contributing to the economy." },
    { q: "A person who starts a recycling business, creating jobs while reducing waste, is showing:", options: ["Only wage employment", "Entrepreneurship that also benefits society", "Risk-avoidance", "A myth about entrepreneurship"], answer: 1, why: "This is entrepreneurship that solves a social problem (waste) while also creating jobs — a social benefit." },
    { q: "Compared to a wage employee, an entrepreneur's income is typically:", options: ["Fixed and guaranteed", "Uncertain, depending on the business's profit", "Exactly the same every month", "Paid by a government body"], answer: 1, why: "An entrepreneur's income depends on the profits of the business, unlike a wage employee's fixed salary." },
  ],
  keyTopics: [
    { name: "Definition of an entrepreneur", importance: "medium", note: "Direct 1-mark definition question." },
    { name: "Entrepreneurship vs wage employment", importance: "high", note: "Common differentiate-type question with at least 3 points." },
    { name: "Qualities of a successful entrepreneur", importance: "high", note: "List and briefly explain 3–4 qualities." },
    { name: "Functions of an entrepreneur", importance: "medium", note: "Name the functions, ideally in logical order." },
    { name: "Myths about entrepreneurship", importance: "high", note: "State a myth and the reality — frequently asked." },
    { name: "How entrepreneurs help society", importance: "medium", note: "Link entrepreneurship to jobs, innovation and the economy." },
  ],
  written: [
    { q: "Who is an entrepreneur?", marks: 1, kind: "short", importance: "high",
      answer: "An entrepreneur is a person who identifies a problem or opportunity and takes the <strong>risk of starting and running a new business</strong> to address it." },
    { q: "Give one difference between entrepreneurship and wage employment.", marks: 1, kind: "short", importance: "medium",
      answer: "An entrepreneur <strong>owns the business and bears financial risk</strong> for uncertain profit, while a wage employee works for someone else and earns a <strong>fixed, regular salary</strong>." },
    { q: "State one myth about entrepreneurship and the actual reality.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Myth:</strong> a lot of money is always needed to start a business. <strong>Reality:</strong> many successful ventures start small with limited capital and grow gradually." },
    { q: "List any three qualities of a successful entrepreneur.", marks: 2, kind: "short", importance: "high",
      answer: "Any three of: <strong>creativity/innovation, risk-taking ability, self-confidence and self-motivation, hard work and perseverance, good decision-making.</strong>" },
    { q: "Differentiate between entrepreneurship and wage employment on any two points.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Ownership:</strong> an entrepreneur owns and runs their own business, while a wage employee works within someone else's business.<br><strong>Risk and income:</strong> an entrepreneur bears financial risk with uncertain profit, while a wage employee earns a fixed, regular salary with little risk." },
    { q: "Explain any two functions performed by an entrepreneur.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Idea generation</strong> — identifying a problem or gap worth solving.<br><strong>Risk-bearing</strong> — accepting the possibility of financial loss if the venture does not succeed." },
    { q: "Explain any three myths about entrepreneurship along with the reality for each.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>1. Myth:</strong> entrepreneurs are born, not made. <strong>Reality:</strong> entrepreneurial skills can be learned and developed.<br><strong>2. Myth:</strong> you need a lot of money to start. <strong>Reality:</strong> many ventures start small and grow gradually.<br><strong>3. Myth:</strong> entrepreneurs never fail. <strong>Reality:</strong> failure is common, and many successful entrepreneurs failed before succeeding." },
    { q: "Explain the functions of an entrepreneur in setting up a new business.", marks: 3, kind: "long", importance: "medium",
      answer: "<strong>1. Idea generation</strong> — spotting a problem or market gap.<br><strong>2. Planning</strong> — deciding the resources (money, people, materials) needed.<br><strong>3. Arranging resources</strong> — raising funds, hiring people, sourcing materials.<br><strong>4. Organising production</strong> — turning the plan into an actual product/service.<br><strong>5. Risk-bearing and innovation</strong> — accepting possible loss and continuously improving the venture." },
    { q: "Explain how entrepreneurs contribute to society, with an example.", marks: 3, kind: "long", importance: "high",
      answer: "Entrepreneurs benefit society beyond their own profit: they <strong>create employment</strong> by hiring workers, introduce useful <strong>new products or services</strong>, and contribute to the <strong>economy</strong> through taxes and business activity.<br><strong>Example:</strong> a person starting a recycling business creates jobs for local workers while also helping reduce waste in the community — solving a social problem through a viable business." },
  ],
  assertionReason: [
    { assertion: "Entrepreneurship generally involves more financial risk than wage employment.",
      reason: "An entrepreneur's income depends on the business's profit, which is not guaranteed, unlike a wage employee's fixed salary.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why: uncertain, profit-dependent income means entrepreneurs bear more risk than salaried employees." },
    { assertion: "A large amount of starting capital is always necessary to become an entrepreneur.",
      reason: "Many successful businesses have started small, with limited capital, and grown gradually over time.",
      answer: 3, importance: "medium",
      why: "A is false — this is a common myth. R is true and actually explains why A is false: real examples show ventures can start small and grow." },
    { assertion: "Entrepreneurs help society only by earning profit for themselves.",
      reason: "Entrepreneurship can create employment and introduce new products or services that benefit the wider community.",
      answer: 3, importance: "medium",
      why: "A is false — entrepreneurship benefits society more broadly, not just the entrepreneur. R is true and gives the actual reason A is false — jobs and innovation reach the whole community." },
  ],
  caseStudies: [
    { title: "From idea to enterprise", importance: "high",
      source: "Meera noticed that many small farmers near her village were throwing away large amounts of unsold vegetables every week because they had no way to reach city buyers. She planned a small delivery service connecting farmers directly to city households, arranged a used van and two part-time drivers, and started operating with very limited savings. The first two months were difficult and she barely broke even, but she kept improving her delivery routes and slowly built a steady customer base.",
      parts: [
        { q: "Identify two qualities of a successful entrepreneur that Meera shows in this scenario.", marks: 2, answer: "<strong>Creativity/innovation</strong> — she spotted a real problem and designed a new solution; and <strong>perseverance/risk-taking</strong> — she continued and improved despite a difficult, uncertain start." },
        { q: "Which myth about entrepreneurship does Meera's story disprove?", marks: 1, answer: "The myth that a <strong>large amount of money is always needed to start a business</strong> — Meera started with very limited savings and grew gradually." },
        { q: "Explain one way Meera's business is likely to help her wider community.", marks: 1, answer: "It creates <strong>employment</strong> (the part-time drivers) and helps farmers reduce wasted produce while giving city households fresh vegetables — benefiting more people than just Meera." },
      ] },
  ],
};
