import type { Chapter } from "@/lib/types";

export const ch13: Chapter = {
  slug: "green-skills",
  num: 13,
  title: "Green Skills",
  unit: "employability",
  unitName: "Employability Skills",
  marks: "Part A · Employability",
  minutes: 12,
  blurb: "Sustainable development and why green skills matter, the green economy and green jobs, conserving resources, the problems of unsustainable development, and what individuals can do.",
  bigIdea: "The way we currently produce, consume and throw things away is using up resources faster than the planet can replace them — green skills are the knowledge and habits needed to meet today's needs without wrecking tomorrow's.",
  syllabus: [
    "Meaning of sustainable development",
    "Need for green skills",
    "Green economy and green jobs",
    "Conserving natural resources",
    "Problems caused by unsustainable development",
    "Role of individuals in sustainability",
  ],
  blocks: [
    { t: "h", text: "Sustainable development" },
    { t: "p", html: "<strong>Sustainable development</strong> means meeting the needs of the present generation without compromising the ability of future generations to meet their own needs. It balances economic growth, social well-being and protecting the environment together." },
    { t: "note", kind: "idea", title: "One-line definition for the exam", html: "Sustainable development is development that meets <strong>today's needs without harming the ability of future generations</strong> to meet theirs." },

    { t: "h", text: "Why we need green skills" },
    { t: "p", html: "<strong>Green skills</strong> are the knowledge, abilities and values needed to support a sustainable and resource-efficient way of living and working — for example, knowing how to save energy, reduce waste, or use renewable resources." },
    { t: "list", items: [
      "Natural resources like water, forests and fossil fuels are <strong>limited</strong>, but demand keeps growing.",
      "Climate change, pollution and waste are already affecting health, farming and daily life.",
      "Every job — not just environmental ones — increasingly needs some awareness of sustainable practices.",
    ] },
    { t: "note", kind: "why", title: "Why this matters for every career", html: "Green skills are no longer only for environmentalists — a shop, a factory, an office or a farm can all be run more sustainably, so these skills are becoming valuable across almost every profession." },

    { t: "h", text: "Green economy and green jobs" },
    { t: "p", html: "A <strong>green economy</strong> is one that aims for economic growth while reducing environmental risks, pollution and resource depletion. Within it, <strong>green jobs</strong> are jobs that directly help protect or restore the environment." },
    { t: "table", head: ["Sector", "Example of a green job"], rows: [
      ["Energy", "Solar panel technician / wind turbine installer"],
      ["Agriculture", "Organic farmer using sustainable farming practices"],
      ["Waste management", "Recycling plant worker"],
      ["Construction", "Green building designer using energy-efficient materials"],
      ["Transport", "Electric vehicle technician"],
    ] },
    { t: "note", kind: "exam", html: "A common question: “Define green jobs and give two examples.” Give the definition, then pick any two rows from the table above." },

    { t: "h", text: "Conserving natural resources" },
    { t: "p", html: "Conservation means using resources carefully so they last longer and cause less environmental damage." },
    { t: "list", items: [
      "<strong>Reduce, Reuse, Recycle</strong> — cut down waste at the source, reuse items instead of discarding them, and recycle materials like paper, plastic and metal.",
      "<strong>Save energy and water</strong> — switch off unused appliances/lights, fix leaking taps, use water-efficient devices.",
      "<strong>Use renewable resources</strong> — solar and wind energy instead of only fossil fuels.",
      "<strong>Protect forests and biodiversity</strong> — support afforestation and avoid deforestation.",
    ] },
    { t: "note", kind: "memory", html: "Remember the <strong>3 Rs: Reduce, Reuse, Recycle</strong> — in that order of preference. Reducing what you use in the first place is even better than recycling it afterwards." },

    { t: "h", text: "Problems of unsustainable development" },
    { t: "p", html: "When development ignores the environment, it creates serious long-term problems." },
    { t: "list", items: [
      "<strong>Depletion of natural resources</strong> — water, forests and minerals being used up faster than they can renew.",
      "<strong>Pollution</strong> — of air, water and soil, harming health and ecosystems.",
      "<strong>Climate change</strong> — rising temperatures, unpredictable weather, melting ice caps.",
      "<strong>Loss of biodiversity</strong> — species and habitats disappearing.",
    ] },
    { t: "note", kind: "trap", html: "Unsustainable development is not only about pollution — <strong>using up resources faster than they can be replaced</strong> is just as much a problem, even if the air looks clean today." },

    { t: "h", text: "What individuals can do" },
    { t: "p", html: "Sustainability is not only the job of governments and companies — everyday individual choices add up." },
    { t: "list", items: [
      "Save electricity and water at home and school.",
      "Reduce, reuse and recycle waste instead of throwing everything away.",
      "Choose walking, cycling or public transport over private vehicles when possible.",
      "Support and buy from businesses that follow eco-friendly practices.",
      "Spread awareness about sustainable habits among family and friends.",
    ] },
  ],
  examFocus: [
    "Definition of sustainable development.",
    "Why green skills are needed, and how they apply to many careers.",
    "Meaning of green economy and green jobs, with examples.",
    "Ways to conserve natural resources — especially the 3 Rs.",
    "Problems caused by unsustainable development.",
    "What an individual can do to support sustainability.",
  ],
  flashcards: [
    { q: "Define sustainable development.", a: "Development that meets the needs of the present generation without compromising the ability of future generations to meet their own needs." },
    { q: "What are green skills?", a: "The knowledge, abilities and values needed to support a sustainable, resource-efficient way of living and working." },
    { q: "What is a green economy?", a: "An economy that aims for growth while reducing environmental risks, pollution and resource depletion." },
    { q: "What are green jobs? Give one example.", a: "Jobs that directly help protect or restore the environment, e.g. a solar panel technician or a recycling plant worker." },
    { q: "What are the 3 Rs of conservation?", a: "Reduce, Reuse, Recycle — in that order of preference." },
    { q: "Give two ways to conserve energy or water.", a: "Any two of: switch off unused appliances/lights, fix leaking taps, use water-efficient devices." },
    { q: "Name two renewable resources.", a: "Solar energy and wind energy (also: hydro power, biomass)." },
    { q: "Give two problems caused by unsustainable development.", a: "Any two of: depletion of natural resources, pollution, climate change, loss of biodiversity." },
    { q: "What is meant by 'depletion of resources'?", a: "Using up natural resources like water, forests or minerals faster than they can be renewed or replaced." },
    { q: "Give two things an individual can do to support sustainability.", a: "Any two of: saving electricity/water, reducing and recycling waste, using public transport/cycling, spreading awareness." },
  ],
  quiz: [
    { q: "Sustainable development is best defined as development that:", options: ["Maximises profit regardless of environmental cost", "Meets present needs without harming future generations' ability to meet theirs", "Focuses only on economic growth", "Avoids all use of natural resources"], answer: 1, why: "Sustainable development balances meeting today's needs with protecting resources for the future." },
    { q: "Green skills are best described as:", options: ["Skills needed only by environmental scientists", "Knowledge and abilities to support sustainable, resource-efficient living and working", "Skills for gardening only", "Skills unrelated to most careers"], answer: 1, why: "Green skills apply across many careers, not just environmental ones, and support sustainable practices." },
    { q: "A 'green economy' aims to achieve growth while:", options: ["Increasing pollution as much as possible", "Reducing environmental risk and resource depletion", "Ignoring natural resources completely", "Only focusing on manufacturing"], answer: 1, why: "A green economy pursues economic growth while reducing pollution and protecting resources." },
    { q: "Which of these is an example of a green job?", options: ["A coal mine operator with no environmental measures", "A solar panel technician", "A worker in a highly polluting factory with no controls", "None of these"], answer: 1, why: "A solar panel technician works in renewable energy, directly supporting environmental protection." },
    { q: "The correct order of preference in the 3 Rs of conservation is:", options: ["Recycle, Reuse, Reduce", "Reduce, Reuse, Recycle", "Reuse, Recycle, Reduce", "There is no particular order"], answer: 1, why: "Reducing use in the first place is preferred, then reusing, and recycling as the last resort." },
    { q: "Which of these is a renewable resource?", options: ["Coal", "Petroleum", "Solar energy", "Natural gas"], answer: 2, why: "Solar energy is renewable, unlike fossil fuels such as coal, petroleum and natural gas." },
    { q: "Which of these is a problem caused by unsustainable development?", options: ["Increased biodiversity", "Depletion of natural resources and pollution", "Unlimited renewable energy", "Reduced climate change"], answer: 1, why: "Unsustainable development leads to resource depletion, pollution, climate change and biodiversity loss." },
    { q: "Which statement about unsustainable development is TRUE?", options: ["It only causes visible pollution, nothing else", "It can deplete resources even without visible pollution", "It has no long-term effects", "It only affects wealthy countries"], answer: 1, why: "Using up resources faster than they renew is a problem even if pollution isn't visibly obvious." },
    { q: "Which of these is something an individual can do to support sustainability?", options: ["Leave lights and appliances running when not needed", "Use public transport or cycle instead of driving alone", "Throw away all recyclable waste", "Avoid saving water"], answer: 1, why: "Choosing public transport or cycling reduces individual environmental impact and supports sustainability." },
    { q: "Loss of biodiversity refers to:", options: ["An increase in renewable energy use", "The disappearance of species and habitats", "Better waste recycling", "Improved air quality"], answer: 1, why: "Biodiversity loss means species and their habitats are disappearing, often due to unsustainable development." },
  ],
  keyTopics: [
    { name: "Definition of sustainable development", importance: "high", note: "Precise 1–2 mark definition question, often reused across chapters." },
    { name: "Need for green skills", importance: "medium", note: "Explain why green skills matter across careers, not just 'green' jobs." },
    { name: "Green economy and green jobs", importance: "high", note: "Define both and give 2–3 examples of green jobs." },
    { name: "Conserving resources (3 Rs, energy/water saving)", importance: "high", note: "The 3 Rs and practical conservation habits are frequently asked." },
    { name: "Problems of unsustainable development", importance: "medium", note: "List and briefly explain at least three problems." },
    { name: "Role of individuals in sustainability", importance: "medium", note: "Give practical, everyday examples of individual action." },
  ],
  written: [
    { q: "Define sustainable development.", marks: 1, kind: "short", importance: "high",
      answer: "Sustainable development is development that meets the needs of the <strong>present generation</strong> without compromising the ability of <strong>future generations</strong> to meet their own needs." },
    { q: "What are green jobs? Give one example.", marks: 1, kind: "short", importance: "high",
      answer: "Green jobs are jobs that directly help <strong>protect or restore the environment</strong>. Example: a solar panel technician." },
    { q: "State the 3 Rs of resource conservation.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Reduce, Reuse, Recycle</strong>." },
    { q: "What are green skills? Why are they needed today?", marks: 2, kind: "short", importance: "high",
      answer: "Green skills are the <strong>knowledge, abilities and values</strong> needed to support a sustainable, resource-efficient way of living and working. They are needed because natural resources are limited while demand keeps growing, and pollution/climate change already affect health and daily life." },
    { q: "Differentiate between a green economy and unsustainable development.", marks: 2, kind: "short", importance: "medium",
      answer: "A <strong>green economy</strong> pursues economic growth while reducing environmental risk, pollution and resource depletion. <strong>Unsustainable development</strong> pursues growth while ignoring these effects, leading to depletion of resources, pollution and long-term damage." },
    { q: "Give two examples of individual actions that support sustainability.", marks: 2, kind: "short", importance: "medium",
      answer: "Any two of: <strong>saving electricity and water</strong> at home; <strong>reducing, reusing and recycling</strong> waste instead of discarding it; using public transport or cycling instead of private vehicles." },
    { q: "Explain any three ways to conserve natural resources.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>1. Follow the 3 Rs</strong> — reduce what you use, reuse items, and recycle materials like paper and plastic.<br><strong>2. Save energy and water</strong> — switch off unused appliances/lights and fix leaking taps.<br><strong>3. Use renewable resources</strong> — solar and wind energy instead of relying only on fossil fuels; also protect forests and biodiversity." },
    { q: "Explain any three problems caused by unsustainable development.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>1. Depletion of resources</strong> — water, forests and minerals used up faster than they can renew.<br><strong>2. Pollution</strong> — of air, water and soil, harming health and ecosystems.<br><strong>3. Climate change and biodiversity loss</strong> — rising temperatures, unpredictable weather, and species/habitats disappearing." },
    { q: "Explain the concept of green economy and green jobs, giving three examples of green jobs from different sectors.", marks: 3, kind: "long", importance: "high",
      answer: "A <strong>green economy</strong> aims for economic growth while reducing pollution, environmental risk and resource depletion. Within it, <strong>green jobs</strong> directly help protect or restore the environment.<br><strong>Examples:</strong> a solar panel technician (energy sector), an organic farmer using sustainable practices (agriculture), and a recycling plant worker (waste management)." },
  ],
  assertionReason: [
    { assertion: "Sustainable development requires balancing economic growth with protecting the environment.",
      reason: "Using up natural resources faster than they can be replaced harms the ability of future generations to meet their own needs.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why balance is needed — unchecked resource use today harms future generations, which is exactly what sustainable development tries to avoid." },
    { assertion: "Green skills are useful only for people working in environmental science jobs.",
      reason: "Almost every profession — from farming to construction to retail — can be run in a more or less resource-efficient and sustainable way.",
      answer: 3, importance: "medium",
      why: "A is false — green skills are valuable across nearly all careers, not just environmental ones. R is true and actually explains why A is wrong: sustainability applies broadly across professions." },
    { assertion: "Recycling is the best way to conserve resources, better than reducing consumption.",
      reason: "The 3 Rs of conservation are, in order of preference, Reduce, Reuse and then Recycle.",
      answer: 3, importance: "medium",
      why: "A is false — reducing consumption in the first place is preferred over recycling. R is true and gives the correct order, which shows why A's claim is incorrect." },
  ],
  caseStudies: [
    { title: "A school goes green", importance: "high",
      source: "A school decides to cut down its environmental impact. It installs solar panels on the roof, sets up separate bins for paper, plastic and organic waste, asks students to bring refillable water bottles instead of buying bottled water, and starts a 'walk or cycle to school' day once a week.",
      parts: [
        { q: "Which of the school's actions is an example of using a renewable resource? Explain.", marks: 1, answer: "Installing <strong>solar panels</strong> — solar energy is a renewable resource, unlike fossil fuels, and reduces the school's dependence on non-renewable electricity sources." },
        { q: "Identify which of the 3 Rs the separate waste bins and refillable water bottles each mainly support.", marks: 2, answer: "The separate bins for paper/plastic mainly support <strong>Recycle</strong> (and Reduce, since sorting encourages less waste). Refillable water bottles mainly support <strong>Reduce</strong> — cutting down single-use plastic bottle waste at the source." },
        { q: "Explain how the 'walk or cycle to school' day helps sustainability.", marks: 1, answer: "It reduces the use of fuel-powered vehicles, lowering pollution and fossil-fuel consumption, and encourages a habit of sustainable, eco-friendly individual choices." },
      ] },
  ],
};
