import type { Chapter } from "@/lib/types";

export const ch01: Chapter = {
  slug: "chemical-reactions-and-equations",
  num: 1,
  title: "Chemical Reactions and Equations",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 18,
  blurb: "How to spot that a reaction has happened, how to write it down honestly, and the five families every reaction belongs to.",
  bigIdea: "A chemical reaction is just atoms swapping partners. Nothing is created, nothing is destroyed — which is the entire reason we bother balancing equations.",
  syllabus: [
    "Chemical equations", "Balanced chemical equations",
    "Combination", "Decomposition", "Displacement", "Double displacement", "Precipitation",
    "Exothermic and endothermic reactions", "Oxidation and reduction",
  ],
  blocks: [
    { t: "h", text: "How do you know a reaction happened?" },
    { t: "p", html: "Leave a cut apple on the plate for ten minutes and it browns. Light a matchstick and it gives off heat. Mix lemon juice into milk and it curdles. In every case something <em>new</em> has formed — the original substance is gone." },
    { t: "p", html: "There are five give-away signs, and the board loves asking for them:" },
    { t: "list", items: [
      "<strong>Change in state</strong> — candle wax melting and then burning.",
      "<strong>Change in colour</strong> — shiny silver turning black in air.",
      "<strong>Evolution of a gas</strong> — bubbles when zinc meets acid.",
      "<strong>Change in temperature</strong> — the beaker warms up or goes cold.",
      "<strong>Formation of a precipitate</strong> — a solid appearing out of a clear solution.",
    ] },
    { t: "note", kind: "trap", html: "Melting ice shows a change of state, but no new substance forms — so it is a <strong>physical</strong> change, not a chemical one. The test is always: is the new substance different from what you started with?" },

    { t: "h", text: "Writing an equation that tells the truth" },
    { t: "p", html: "A word equation is a start: <em>magnesium + oxygen → magnesium oxide</em>. But chemists write symbols, and a symbol equation carries a promise — that the atoms on the left are exactly the atoms on the right." },
    { t: "eq", lines: [
      "Skeletal (unbalanced):&nbsp;&nbsp; Mg + O₂ → MgO",
      "Balanced:&nbsp;&nbsp; 2Mg + O₂ → 2MgO",
    ], caption: "Count the oxygens: two on the left, so you need two on the right. That forces a 2 in front of MgO, which then forces a 2 in front of Mg." },
    { t: "note", kind: "why", title: "Why balance at all?", html: "Because of the <strong>law of conservation of mass</strong>: mass can neither be created nor destroyed in a chemical reaction. An unbalanced equation would be claiming atoms appeared from nowhere." },
    { t: "note", kind: "exam", html: "A complete equation also shows the <strong>state symbols</strong> — (s) solid, (l) liquid, (g) gas, (aq) dissolved in water — and any condition written above the arrow (heat, catalyst, pressure). Marks are regularly cut for leaving these out." },
    { t: "sim", id: "equation-balancer" },
    { t: "note", kind: "memory", html: "Balancing order that almost always works: <strong>C, then H, then O last</strong>. Oxygen is usually the flexible one because it turns up in several compounds." },

    { t: "h", text: "The five types of reaction" },
    { t: "p", html: "Every reaction in your syllabus fits one of these boxes. Learn the <em>shape</em> of each one and you can classify any equation you are shown." },
    { t: "table", head: ["Type", "Shape", "Example", "Tell-tale sign"], rows: [
      ["Combination", "A + B → AB", "CaO + H₂O → Ca(OH)₂", "Two things become one"],
      ["Decomposition", "AB → A + B", "2FeSO₄ <span class='faint'>(heat)</span> → Fe₂O₃ + SO₂ + SO₃", "One thing becomes many"],
      ["Displacement", "A + BC → AC + B", "Fe + CuSO₄ → FeSO₄ + Cu", "One element kicks another out"],
      ["Double displacement", "AB + CD → AD + CB", "Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl", "Partners swap"],
      ["Precipitation", "(a double displacement)", "AgNO₃ + NaCl → AgCl↓ + NaNO₃", "An insoluble solid drops out"],
    ] },
    { t: "note", kind: "real", html: "Quicklime + water (CaO + H₂O) is the combination reaction used in whitewashing walls. The calcium hydroxide formed slowly reacts with CO₂ in the air to give a shiny coat of calcium carbonate — the same compound as marble." },
    { t: "p", html: "Decomposition comes in three flavours, named after where the energy comes from:" },
    { t: "list", ordered: true, items: [
      "<strong>Thermal</strong> — driven by heat. <span class='chem'>CaCO₃ → CaO + CO₂</span>, the reaction that makes cement.",
      "<strong>Electrolytic</strong> — driven by electricity. Water splits into hydrogen and oxygen; the hydrogen tube collects twice the volume, because water is H₂O.",
      "<strong>Photolytic</strong> — driven by light. <span class='chem'>2AgCl → 2Ag + Cl₂</span>, the reaction behind old black-and-white photographic film.",
    ] },

    { t: "h", text: "Energy: exothermic and endothermic" },
    { t: "compare", left: { title: "Exothermic — gives out heat", items: [
      "Burning of natural gas, coal, petrol",
      "Respiration in your own cells — glucose + oxygen → CO₂ + water + energy",
      "Quicklime + water (the beaker gets hot enough to be dangerous)",
      "Decomposition of vegetable matter into compost",
    ] }, right: { title: "Endothermic — takes in heat", items: [
      "Photosynthesis — needs sunlight to run",
      "Thermal decomposition of limestone",
      "Dissolving ammonium chloride in water (the beaker goes cold)",
      "Cooking an egg",
    ] } },
    { t: "note", kind: "real", html: "Respiration is technically a combination reaction and an exothermic one. That is why you feel warm after climbing stairs — you are literally burning glucose, just very slowly and in a controlled way." },

    { t: "h", text: "Oxidation and reduction" },
    { t: "p", html: "At Class X level the definition is simple and mechanical:" },
    { t: "list", items: [
      "<strong>Oxidation</strong> = gain of oxygen, or loss of hydrogen.",
      "<strong>Reduction</strong> = loss of oxygen, or gain of hydrogen.",
    ] },
    { t: "p", html: "They always happen together — if something gained oxygen, something else must have lost it. A reaction where both occur is called a <strong>redox</strong> reaction." },
    { t: "eq", lines: [
      "CuO + H₂ → Cu + H₂O",
      "<span class='faint'>CuO loses oxygen → reduced&nbsp;&nbsp;|&nbsp;&nbsp;H₂ gains oxygen → oxidised</span>",
    ] },
    { t: "note", kind: "memory", html: "<strong>OIL RIG</strong> — Oxidation Is Loss (of hydrogen), Reduction Is Gain (of hydrogen). The substance that <em>causes</em> oxidation is the oxidising agent, and it gets reduced itself." },

    { t: "h", text: "Corrosion and rancidity" },
    { t: "p", html: "Two everyday consequences of oxidation that the board asks about almost every year." },
    { t: "list", items: [
      "<strong>Corrosion</strong> — metal slowly eaten away by air and moisture. Iron rusts reddish-brown (Fe₂O₃·xH₂O), copper goes green, silver goes black. Prevented by painting, oiling, galvanising (zinc coating), or alloying into stainless steel.",
      "<strong>Rancidity</strong> — fats and oils in food oxidise, giving that unpleasant smell and taste in old chips or ghee. Prevented by adding antioxidants, packing in nitrogen gas, refrigerating, and using airtight containers.",
    ] },
    { t: "note", kind: "real", html: "Chips packets are flushed with nitrogen before sealing. Nitrogen is unreactive, so it pushes out the oxygen and the fat cannot oxidise — the same reason the packet looks puffed up." },

    { t: "steps", title: "Balance: Fe + H₂O → Fe₃O₄ + H₂",
      intro: "A classic three-mark question. Do it in the standard order and it takes thirty seconds.",
      steps: [
        "Count iron: 1 on the left, 3 on the right. Put a <strong>3</strong> before Fe.",
        "Count oxygen: 1 on the left (in H₂O), 4 on the right. Put a <strong>4</strong> before H₂O.",
        "Now hydrogen: 4 × 2 = 8 on the left. Put a <strong>4</strong> before H₂ on the right.",
        "Re-check everything: Fe 3 = 3 ✓, O 4 = 4 ✓, H 8 = 8 ✓.",
      ],
      answer: "3Fe + 4H₂O → Fe₃O₄ + 4H₂ &nbsp;(steam is needed, so write H₂O as (g))",
    },
  ],
  formulas: [],
  examFocus: [
    "The five observations that tell you a chemical reaction has occurred.",
    "Balancing by the C → H → O order, and never forgetting state symbols.",
    "Being able to name the type of reaction from the shape of the equation alone.",
    "Exothermic vs endothermic with two examples each — respiration and photosynthesis are the safest pair.",
    "In a redox equation, saying <em>which</em> substance was oxidised and which was reduced, with the reason.",
    "Corrosion and rancidity: definition, one everyday example, and two prevention methods.",
  ],
  flashcards: [
    { q: "State the law of conservation of mass.", a: "Mass can neither be created nor destroyed in a chemical reaction — the total mass of reactants equals the total mass of products. This is why equations must be balanced." },
    { q: "What is a skeletal chemical equation?", a: "An equation written with correct formulae but not yet balanced — the atom counts on the two sides do not match." },
    { q: "Give the general form of a double displacement reaction.", a: "AB + CD → AD + CB. The two compounds exchange ions. Example: Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl." },
    { q: "What is a precipitation reaction?", a: "A double displacement reaction in which one product is an insoluble solid (the precipitate) that separates out of the solution." },
    { q: "Why is respiration called an exothermic reaction?", a: "Glucose combines with oxygen in our cells to release energy: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy. Energy is given out, so it is exothermic." },
    { q: "Name the three types of decomposition reaction with one example each.", a: "Thermal (CaCO₃ → CaO + CO₂ on heating), electrolytic (water split by electricity), photolytic (2AgCl → 2Ag + Cl₂ in sunlight)." },
    { q: "In electrolysis of water, why is there twice as much hydrogen as oxygen?", a: "Water is H₂O — two hydrogen atoms for every one oxygen atom. So twice the volume of hydrogen gas is collected, at the cathode." },
    { q: "Define oxidation and reduction in terms of oxygen and hydrogen.", a: "Oxidation is gain of oxygen or loss of hydrogen. Reduction is loss of oxygen or gain of hydrogen. They always occur together in a redox reaction." },
    { q: "What is corrosion? Give two prevention methods.", a: "The slow eating away of a metal by air, moisture or chemicals — e.g. iron rusting. Prevented by painting/oiling, galvanising with zinc, electroplating, or alloying (stainless steel)." },
    { q: "What is rancidity and how is it prevented?", a: "Oxidation of fats and oils in food, producing a bad smell and taste. Prevented by antioxidants, airtight packaging, flushing with nitrogen, and refrigeration." },
    { q: "Why is silver chloride used in photography?", a: "Silver chloride decomposes in sunlight (2AgCl → 2Ag + Cl₂), leaving grey metallic silver — the darkening that records an image." },
    { q: "What happens when quicklime is added to water?", a: "CaO + H₂O → Ca(OH)₂ + heat. A combination reaction and strongly exothermic — the mixture hisses and becomes very hot. Used in whitewashing." },
    { q: "Why must an equation carry state symbols?", a: "They tell you the physical form of every substance — (s), (l), (g), (aq) — which changes the meaning of the reaction. An equation without them is considered incomplete." },
  ],
  quiz: [
    { q: "Which of these is <strong>not</strong> a sign that a chemical reaction has taken place?", options: ["A gas is evolved", "The temperature changes", "Ice melts into water", "A precipitate forms"], answer: 2, why: "Melting ice is a change of state only — the substance is still H₂O, so no new substance is formed. That makes it a physical change." },
    { q: "In the reaction 3Fe + 4H₂O → Fe₃O₄ + 4H₂, how many hydrogen atoms are on the reactant side?", options: ["4", "6", "8", "2"], answer: 2, why: "4H₂O means 4 × 2 = 8 hydrogen atoms. The same 8 appear on the right as 4H₂." },
    { q: "The reaction CaCO₃ → CaO + CO₂ on heating is an example of:", options: ["Combination", "Thermal decomposition", "Displacement", "Double displacement"], answer: 1, why: "One compound splits into two simpler ones, and heat supplies the energy — that is thermal decomposition." },
    { q: "Which reaction is endothermic?", options: ["Burning of coal", "Photosynthesis", "Respiration", "Quicklime added to water"], answer: 1, why: "Photosynthesis absorbs sunlight to run. All the others give out heat and are exothermic." },
    { q: "A copper wire dipped in silver nitrate solution slowly turns the solution blue. Why?", options: ["Copper dissolves without reacting", "Silver displaces copper", "Copper displaces silver, forming blue copper nitrate", "The nitrate decomposes"], answer: 2, why: "Copper is more reactive than silver, so it displaces silver: Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag. Copper nitrate solution is blue and silver deposits on the wire." },
    { q: "In CuO + H₂ → Cu + H₂O, which substance is oxidised?", options: ["CuO", "H₂", "Cu", "H₂O"], answer: 1, why: "Hydrogen gains oxygen to become water, so hydrogen is oxidised. CuO loses oxygen, so it is reduced." },
    { q: "Chips packets are filled with nitrogen because nitrogen:", options: ["Kills bacteria", "Is unreactive and prevents oxidation of the fat", "Keeps the chips crisp by absorbing water", "Is cheaper than air"], answer: 1, why: "Nitrogen displaces oxygen. With no oxygen present, the oils cannot oxidise, so the chips do not turn rancid." },
    { q: "The correct balanced equation for the burning of magnesium is:", options: ["Mg + O₂ → MgO", "2Mg + O₂ → 2MgO", "Mg + 2O → MgO₂", "2Mg + 2O₂ → 2MgO"], answer: 1, why: "Oxygen exists as O₂. Two oxygen atoms need two MgO units, which then need 2Mg on the left." },
    { q: "A white precipitate forms when barium chloride is mixed with sodium sulphate. The precipitate is:", options: ["NaCl", "BaSO₄", "BaCl₂", "Na₂SO₄"], answer: 1, why: "Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl. Barium sulphate is insoluble in water and settles out as a white solid." },
    { q: "Silver articles turn black on long exposure to air because silver reacts with:", options: ["Oxygen", "Carbon dioxide", "Hydrogen sulphide", "Nitrogen"], answer: 2, why: "Silver reacts with the small amount of H₂S in air to form black silver sulphide (Ag₂S). This is corrosion — which is why silver polish exists." },
    { q: "Which statement about a balanced equation is correct?", options: ["The number of molecules is equal on both sides", "The number of atoms of each element is equal on both sides", "The number of compounds is equal on both sides", "The volume is equal on both sides"], answer: 1, why: "Balancing is about atoms, not molecules. 2Mg + O₂ → 2MgO has 3 molecules on the left and 2 on the right, yet it is balanced." },
    { q: "Reduction of a substance means:", options: ["Gain of oxygen", "Loss of hydrogen", "Loss of oxygen or gain of hydrogen", "Increase in mass"], answer: 2, why: "Reduction is loss of oxygen or gain of hydrogen — the exact opposite of oxidation." },
  ],
};
