import type { Chapter } from "@/lib/types";

export const ch02: Chapter = {
  slug: "acids-bases-and-salts",
  num: 2,
  title: "Acids, Bases and Salts",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 20,
  blurb: "Everything follows from two ions: H⁺ and OH⁻. Learn what each one does and the whole chapter falls into place.",
  bigIdea: "An acid is anything that releases H⁺ ions in water; a base releases OH⁻. Every property, every test and every reaction in this chapter is one of those two ions doing its job.",
  syllabus: [
    "Acids and bases in terms of H⁺ and OH⁻ ions", "Indicators",
    "General properties, examples and uses", "Neutralisation", "pH scale",
    "Sodium hydroxide", "Bleaching powder", "Baking soda", "Washing soda", "Plaster of Paris",
  ],
  blocks: [
    { t: "h", text: "The two ions that run the chapter" },
    { t: "p", html: "Dry HCl gas will not turn blue litmus red. Dissolve it in water and it does, instantly. That single experiment tells you something important: <strong>acids need water to behave like acids</strong>, because only in water do they split apart and release H⁺ ions." },
    { t: "eq", lines: [
      "HCl + H₂O → H₃O⁺ + Cl⁻&nbsp;&nbsp;<span class='faint'>(H⁺ never floats alone — it attaches to water as hydronium)</span>",
      "NaOH → Na⁺ + OH⁻&nbsp;&nbsp;<span class='faint'>(a base releases hydroxide)</span>",
    ] },
    { t: "note", kind: "trap", html: "<strong>Always add acid to water, never water to acid.</strong> Dilution is highly exothermic; pouring water onto concentrated acid makes it spit and can burn you badly." },
    { t: "note", kind: "why", title: "Base vs alkali", html: "Every alkali is a base, but not every base is an alkali. A base that <em>dissolves in water</em> is called an alkali — NaOH, KOH, Ca(OH)₂. Copper oxide is a base but not an alkali, because it will not dissolve." },

    { t: "h", text: "Indicators — how you actually tell" },
    { t: "table", head: ["Indicator", "In acid", "In base"], rows: [
      ["Litmus", "Blue → <span style='color:#dc2626'>red</span>", "Red → <span style='color:#2563eb'>blue</span>"],
      ["Methyl orange", "<span style='color:#dc2626'>Red</span>", "<span style='color:#ca8a04'>Yellow</span>"],
      ["Phenolphthalein", "Colourless", "<span style='color:#db2777'>Pink</span>"],
      ["Olfactory (onion, clove oil)", "Smell stays", "Smell disappears"],
    ] },
    { t: "note", kind: "exam", html: "Onion and vanilla essence are <strong>olfactory indicators</strong> — they change smell, not colour. Useful for a visually impaired student, which is exactly how the board frames the question." },

    { t: "h", text: "What acids and bases actually do" },
    { t: "p", html: "Four reactions cover the whole syllabus. Notice that the gas test is asked for every single time." },
    { t: "list", ordered: true, items: [
      "<strong>Acid + metal → salt + hydrogen.</strong> Zn + 2HCl → ZnCl₂ + H₂. Test: bring a burning splint near — it burns with a <em>pop</em> sound.",
      "<strong>Acid + metal carbonate/hydrogencarbonate → salt + water + CO₂.</strong> Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂. Test: pass through lime water — it turns <em>milky</em>. Pass excess and the milkiness disappears.",
      "<strong>Acid + base → salt + water.</strong> This is neutralisation. NaOH + HCl → NaCl + H₂O.",
      "<strong>Metal oxide + acid → salt + water.</strong> CuO + 2HCl → CuCl₂ + H₂O. Because metal oxides behave exactly like bases, they are called <em>basic oxides</em>.",
    ] },
    { t: "note", kind: "real", html: "The pop test and the lime-water test are the two most frequently examined practical observations in the whole Chemistry unit. Learn them word for word." },
    { t: "note", kind: "trap", html: "Non-metal oxides (CO₂, SO₂) are <strong>acidic oxides</strong> — they react with bases. CO₂ + Ca(OH)₂ → CaCO₃ + H₂O is exactly the lime-water test, viewed from the other side." },

    { t: "h", text: "Strong, weak, concentrated, dilute" },
    { t: "p", html: "Students mix these up constantly, and the board knows it." },
    { t: "compare",
      left: { title: "Strong vs weak (about ionisation)", items: [
        "<strong>Strong acid</strong>: ionises completely — HCl, H₂SO₄, HNO₃",
        "<strong>Weak acid</strong>: ionises only partly — CH₃COOH, H₂CO₃, citric acid",
        "Strong base: NaOH, KOH. Weak base: NH₄OH, Mg(OH)₂",
      ] },
      right: { title: "Concentrated vs dilute (about water)", items: [
        "<strong>Concentrated</strong>: little water present",
        "<strong>Dilute</strong>: lots of water present",
        "A dilute solution of a strong acid is still a strong acid",
      ] } },

    { t: "h", text: "pH — putting a number on it" },
    { t: "p", html: "pH stands for 'potenz of Hydrogen' — the power of hydrogen. It runs 0 to 14, and it is a <strong>logarithmic</strong> scale: each step of 1 means a ten-fold change in H⁺ concentration. So pH 3 is not slightly more acidic than pH 5 — it is a hundred times more acidic." },
    { t: "sim", id: "ph-scale" },
    { t: "p", html: "Where pH shows up in real life, and these are the exact examples the board uses:" },
    { t: "list", items: [
      "<strong>In your stomach</strong> — HCl at about pH 1.5 helps digest protein. Too much causes acidity; an antacid (a mild base like Mg(OH)₂) neutralises it.",
      "<strong>In your mouth</strong> — below pH 5.5 tooth enamel starts dissolving. Bacteria make acid from leftover sugar; toothpaste is mildly basic to neutralise it.",
      "<strong>In the soil</strong> — plants need a pH close to neutral. Too acidic and farmers add quicklime; too basic and they add organic matter.",
      "<strong>In rain</strong> — below pH 5.6 it is acid rain, which turns rivers acidic and damages marble monuments.",
      "<strong>In self-defence</strong> — a bee sting injects an acid, so baking soda (a mild base) relieves it. A nettle sting injects methanoic acid; dock leaf sap neutralises it.",
    ] },
    { t: "note", kind: "memory", html: "Rule of thumb: <strong>acid problem → mild base, base problem → mild acid.</strong> That one line answers most application questions in this chapter." },

    { t: "h", text: "The five compounds you must know cold" },
    { t: "table", head: ["Compound", "Formula", "How it is made", "What it is used for"], rows: [
      ["Sodium hydroxide (caustic soda)", "NaOH", "Chlor-alkali process — electricity through brine (NaCl solution)", "Soaps, detergents, paper, degreasing metals. Chlorine and hydrogen are the by-products"],
      ["Bleaching powder", "CaOCl₂", "Cl₂ passed over dry slaked lime Ca(OH)₂", "Bleaching cotton and paper, disinfecting drinking water, oxidising agent"],
      ["Baking soda", "NaHCO₃", "NaCl + H₂O + CO₂ + NH₃ → NaHCO₃ + NH₄Cl", "Baking (releases CO₂ so cakes rise), antacid, in fire extinguishers"],
      ["Washing soda", "Na₂CO₃·10H₂O", "Heat baking soda, then recrystallise the Na₂CO₃ with water", "Removing hardness of water, glass and paper industry, cleaning"],
      ["Plaster of Paris", "CaSO₄·½H₂O", "Heat gypsum to 373 K (100 °C)", "Plaster casts for fractures, ceilings, statues, smoothing walls"],
    ] },
    { t: "note", kind: "trap", html: "Plaster of Paris must be heated to <strong>exactly 373 K</strong>. Heat it higher and you get anhydrous calcium sulphate ('dead burnt plaster'), which will no longer set. And it has to be stored in a moisture-proof container, because it sets on contact with water." },
    { t: "eq", lines: [
      "CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O&nbsp;&nbsp;<span class='faint'>(Plaster of Paris → gypsum, sets hard)</span>",
      "NaHCO₃ + heat → Na₂CO₃ + H₂O + CO₂&nbsp;&nbsp;<span class='faint'>(why baking soda makes cakes rise)</span>",
    ] },
    { t: "note", kind: "real", html: "Baking <em>powder</em> is baking soda plus a mild edible acid (tartaric acid). Without the acid, the sodium carbonate left behind would make the cake taste bitter. That is a favourite one-mark question." },

    { t: "h", text: "Water of crystallisation" },
    { t: "p", html: "Some salt crystals hold water molecules inside their crystal structure. Copper sulphate crystals are blue because of five such molecules — CuSO₄·5H₂O. Heat them and the water leaves, and the crystals turn white. Add water back and the blue returns." },
    { t: "note", kind: "exam", html: "Washing soda Na₂CO₃·10H₂O has <strong>10</strong> molecules of water of crystallisation; gypsum CaSO₄·2H₂O has 2; Plaster of Paris CaSO₄·½H₂O has half. These numbers get asked directly." },

    { t: "steps", title: "Why does a solution of sodium carbonate turn red litmus blue?",
      intro: "A three-mark reasoning question that catches many students.",
      steps: [
        "Sodium carbonate is the salt of a <strong>strong base</strong> (NaOH) and a <strong>weak acid</strong> (H₂CO₃).",
        "In water it hydrolyses: the weak acid formed does not ionise much, but the strong base does.",
        "So there is an excess of OH⁻ ions left in the solution.",
        "Excess OH⁻ means the solution is basic — pH greater than 7.",
      ],
      answer: "Because it is a salt of a strong base and a weak acid, its solution is basic and turns red litmus blue.",
    },
  ],
  formulas: [
    { name: "Neutralisation", expr: "Acid + Base → Salt + Water", note: "The essential reaction: H⁺ + OH⁻ → H₂O" },
    { name: "pH", expr: "pH &lt; 7 acidic &nbsp;·&nbsp; pH = 7 neutral &nbsp;·&nbsp; pH &gt; 7 basic", note: "Each unit is a ten-fold change in H⁺ concentration" },
  ],
  examFocus: [
    "Definitions of acid and base in terms of H⁺ and OH⁻ — the syllabus specifies this wording.",
    "The pop test (hydrogen) and the lime-water test (carbon dioxide), including what happens with excess CO₂.",
    "The difference between strong/weak and concentrated/dilute.",
    "pH applications: stomach, tooth decay, soil, acid rain, bee sting.",
    "The five compounds: formula, one preparation, and two uses each.",
    "Water of crystallisation numbers for washing soda, gypsum and Plaster of Paris.",
  ],
  flashcards: [
    { q: "Define an acid and a base in terms of ions.", a: "An acid produces H⁺ (hydronium, H₃O⁺) ions in aqueous solution. A base produces OH⁻ ions in aqueous solution." },
    { q: "Why does dry HCl gas not change the colour of dry litmus paper?", a: "Because HCl only releases H⁺ ions in the presence of water. Without water it does not ionise, so it cannot behave as an acid." },
    { q: "What is the difference between a base and an alkali?", a: "All alkalis are bases, but only bases that dissolve in water are called alkalis — NaOH, KOH, Ca(OH)₂. CuO is a base but not an alkali." },
    { q: "How do you test for hydrogen gas?", a: "Bring a burning splint near the mouth of the tube — the gas burns with a squeaky pop sound." },
    { q: "How do you test for carbon dioxide?", a: "Pass it through lime water — the lime water turns milky due to CaCO₃. If excess CO₂ is passed, the milkiness disappears as soluble Ca(HCO₃)₂ forms." },
    { q: "What is neutralisation? Give the general equation.", a: "The reaction between an acid and a base to give salt and water: Acid + Base → Salt + Water. At ion level, H⁺ + OH⁻ → H₂O." },
    { q: "Distinguish between a strong acid and a concentrated acid.", a: "Strong refers to complete ionisation in water (HCl, H₂SO₄). Concentrated refers to a small amount of water present. A dilute solution of HCl is still a strong acid." },
    { q: "Why is the pH scale called logarithmic?", a: "Each step of one pH unit means a ten-fold change in H⁺ ion concentration. pH 3 is 100 times more acidic than pH 5." },
    { q: "Why does tooth decay begin when the mouth pH falls below 5.5?", a: "Below pH 5.5 the enamel (calcium phosphate, the hardest substance in the body) starts to dissolve. Bacteria produce this acid from leftover sugar." },
    { q: "Write the formula and one use of bleaching powder.", a: "CaOCl₂. Made by passing chlorine over dry slaked lime. Used for bleaching cotton and paper, disinfecting drinking water, and as an oxidising agent." },
    { q: "Why is baking soda used in cakes?", a: "On heating, NaHCO₃ decomposes to give CO₂ gas, which is trapped in the batter and makes the cake rise and become soft and spongy." },
    { q: "Why is tartaric acid added to baking powder?", a: "To neutralise the sodium carbonate that would otherwise be left behind, which would make the cake taste bitter." },
    { q: "What is Plaster of Paris and how is it made?", a: "CaSO₄·½H₂O, made by heating gypsum (CaSO₄·2H₂O) to 373 K. On adding water it sets into a hard solid — used for plaster casts and ceilings." },
    { q: "Why must Plaster of Paris be stored in a moisture-proof container?", a: "It reacts with moisture in the air and sets into gypsum, becoming useless." },
    { q: "What is water of crystallisation? Give an example.", a: "A fixed number of water molecules present in one formula unit of a salt. Example: CuSO₄·5H₂O — the five water molecules give the crystals their blue colour." },
  ],
  quiz: [
    { q: "Which of these will turn phenolphthalein pink?", options: ["Lemon juice", "Vinegar", "Sodium hydroxide solution", "Distilled water"], answer: 2, why: "Phenolphthalein is colourless in acid and neutral solutions and pink only in bases. NaOH is a strong base." },
    { q: "A gas evolved on adding dilute HCl to a substance turns lime water milky. The substance contains:", options: ["A metal", "A carbonate or hydrogencarbonate", "A sulphate", "A chloride"], answer: 1, why: "Only carbonates and hydrogencarbonates give CO₂ with acids, and CO₂ is the gas that turns lime water milky." },
    { q: "The pH of a solution changes from 7 to 3. The H⁺ ion concentration has:", options: ["Decreased 4 times", "Increased 4 times", "Increased 10,000 times", "Stayed the same"], answer: 2, why: "Each pH unit is a factor of 10. Four units down means 10⁴ = 10,000 times more H⁺ ions." },
    { q: "Which one is a weak acid?", options: ["HCl", "H₂SO₄", "HNO₃", "CH₃COOH"], answer: 3, why: "Acetic (ethanoic) acid ionises only partially in water, so it is a weak acid. The other three ionise completely." },
    { q: "Bleaching powder is prepared by the action of chlorine on:", options: ["Quicklime", "Dry slaked lime", "Limestone", "Sodium hydroxide"], answer: 1, why: "Cl₂ is passed over dry slaked lime, Ca(OH)₂, to give CaOCl₂." },
    { q: "Washing soda has the formula:", options: ["NaHCO₃", "Na₂CO₃·10H₂O", "NaOH", "CaSO₄·½H₂O"], answer: 1, why: "Washing soda is sodium carbonate decahydrate — 10 molecules of water of crystallisation." },
    { q: "A farmer finds his soil is too acidic. He should add:", options: ["Vinegar", "Quicklime or slaked lime", "Ammonium sulphate", "More water"], answer: 1, why: "Acidic soil is corrected by adding a base. Quicklime (CaO) or slaked lime raises the pH towards neutral." },
    { q: "Which of these is a basic oxide?", options: ["CO₂", "SO₂", "CuO", "NO₂"], answer: 2, why: "Metal oxides are basic — CuO reacts with acids to give salt and water. The other three are non-metal (acidic) oxides." },
    { q: "In the chlor-alkali process, the gas produced at the cathode is:", options: ["Chlorine", "Hydrogen", "Oxygen", "Carbon dioxide"], answer: 1, why: "Electrolysis of brine gives chlorine at the anode, hydrogen at the cathode, and NaOH near the cathode." },
    { q: "The correct way to dilute a concentrated acid is to:", options: ["Add water to the acid", "Add acid slowly to water with stirring", "Mix them quickly", "Heat the acid first"], answer: 1, why: "Dilution is strongly exothermic. Adding water to acid causes violent splashing; acid must always be added slowly to water." },
    { q: "Gypsum is heated to 373 K to make Plaster of Paris. What is removed?", options: ["All the water", "One and a half molecules of water", "Half a molecule of water", "Carbon dioxide"], answer: 1, why: "CaSO₄·2H₂O → CaSO₄·½H₂O + 1½H₂O. One and a half water molecules are driven off." },
    { q: "An aqueous solution of sodium chloride is neutral because it is the salt of:", options: ["A strong acid and a weak base", "A weak acid and a strong base", "A strong acid and a strong base", "A weak acid and a weak base"], answer: 2, why: "NaCl comes from HCl (strong acid) and NaOH (strong base). Both ionise fully, so neither H⁺ nor OH⁻ is in excess — pH is 7." },
  ],
};
