import type { Chapter } from "@/lib/types";

export const ch02: Chapter = {
  slug: "acids-bases-and-salts",
  num: 2,
  title: "Acids, Bases and Salts",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 20,
  blurb: "Everything follows from two ions: H⁺ and OH⁻. Learn what each one does and the whole chapter falls into place.",
  bigIdea: "An acid is anything that releases H⁺ ions in water; a base releases OH⁻. Every property, every test and every reaction in this chapter is one of those two ions doing its job.",
  syllabus: [
    "Acids and bases in terms of H⁺ and OH⁻ ions", "Indicators",
    "General properties, examples and uses", "Neutralisation", "pH scale",
    "Sodium hydroxide", "Bleaching powder", "Baking soda", "Washing soda", "Plaster of Paris",
  ],
  blocks: [
    { t: "h", text: "The two ions that run the chapter" },
    { t: "p", html: "Dry HCl gas will not turn blue litmus red. Dissolve it in water and it does, instantly. That single experiment tells you something important: <strong>acids need water to behave like acids</strong>, because only in water do they split apart and release H⁺ ions." },
    { t: "eq", lines: [
      "HCl + H₂O → H₃O⁺ + Cl⁻&nbsp;&nbsp;<span class='faint'>(H⁺ never floats alone — it attaches to water as hydronium)</span>",
      "NaOH → Na⁺ + OH⁻&nbsp;&nbsp;<span class='faint'>(a base releases hydroxide)</span>",
    ] },
    { t: "note", kind: "trap", html: "<strong>Always add acid to water, never water to acid.</strong> Dilution is highly exothermic; pouring water onto concentrated acid makes it spit and can burn you badly." },
    { t: "note", kind: "why", title: "Base vs alkali", html: "Every alkali is a base, but not every base is an alkali. A base that <em>dissolves in water</em> is called an alkali — NaOH, KOH, Ca(OH)₂. Copper oxide is a base but not an alkali, because it will not dissolve." },

    { t: "h", text: "Indicators — how you actually tell" },
    { t: "table", head: ["Indicator", "In acid", "In base"], rows: [
      ["Litmus", "Blue → <span style='color:#dc2626'>red</span>", "Red → <span style='color:#2563eb'>blue</span>"],
      ["Methyl orange", "<span style='color:#dc2626'>Red</span>", "<span style='color:#ca8a04'>Yellow</span>"],
      ["Phenolphthalein", "Colourless", "<span style='color:#db2777'>Pink</span>"],
      ["Olfactory (onion, clove oil)", "Smell stays", "Smell disappears"],
    ] },
    { t: "note", kind: "exam", html: "Onion and vanilla essence are <strong>olfactory indicators</strong> — they change smell, not colour. Useful for a visually impaired student, which is exactly how the board frames the question." },

    { t: "h", text: "What acids and bases actually do" },
    { t: "p", html: "Four reactions cover the whole syllabus. Notice that the gas test is asked for every single time." },
    { t: "list", ordered: true, items: [
      "<strong>Acid + metal → salt + hydrogen.</strong> Zn + 2HCl → ZnCl₂ + H₂. Test: bring a burning splint near — it burns with a <em>pop</em> sound.",
      "<strong>Acid + metal carbonate/hydrogencarbonate → salt + water + CO₂.</strong> Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂. Test: pass through lime water — it turns <em>milky</em>. Pass excess and the milkiness disappears.",
      "<strong>Acid + base → salt + water.</strong> This is neutralisation. NaOH + HCl → NaCl + H₂O.",
      "<strong>Metal oxide + acid → salt + water.</strong> CuO + 2HCl → CuCl₂ + H₂O. Because metal oxides behave exactly like bases, they are called <em>basic oxides</em>.",
    ] },
    { t: "note", kind: "real", html: "The pop test and the lime-water test are the two most frequently examined practical observations in the whole Chemistry unit. Learn them word for word." },
    { t: "note", kind: "trap", html: "Non-metal oxides (CO₂, SO₂) are <strong>acidic oxides</strong> — they react with bases. CO₂ + Ca(OH)₂ → CaCO₃ + H₂O is exactly the lime-water test, viewed from the other side." },

    { t: "h", text: "Strong, weak, concentrated, dilute" },
    { t: "p", html: "Students mix these up constantly, and the board knows it." },
    { t: "compare",
      left: { title: "Strong vs weak (about ionisation)", items: [
        "<strong>Strong acid</strong>: ionises completely — HCl, H₂SO₄, HNO₃",
        "<strong>Weak acid</strong>: ionises only partly — CH₃COOH, H₂CO₃, citric acid",
        "Strong base: NaOH, KOH. Weak base: NH₄OH, Mg(OH)₂",
      ] },
      right: { title: "Concentrated vs dilute (about water)", items: [
        "<strong>Concentrated</strong>: little water present",
        "<strong>Dilute</strong>: lots of water present",
        "A dilute solution of a strong acid is still a strong acid",
      ] } },

    { t: "h", text: "pH — putting a number on it" },
    { t: "p", html: "pH stands for 'potenz of Hydrogen' — the power of hydrogen. It runs 0 to 14, and it is a <strong>logarithmic</strong> scale: each step of 1 means a ten-fold change in H⁺ concentration. So pH 3 is not slightly more acidic than pH 5 — it is a hundred times more acidic." },
    { t: "sim", id: "ph-scale" },
    { t: "p", html: "Where pH shows up in real life, and these are the exact examples the board uses:" },
    { t: "list", items: [
      "<strong>In your stomach</strong> — HCl at about pH 1.5 helps digest protein. Too much causes acidity; an antacid (a mild base like Mg(OH)₂) neutralises it.",
      "<strong>In your mouth</strong> — below pH 5.5 tooth enamel starts dissolving. Bacteria make acid from leftover sugar; toothpaste is mildly basic to neutralise it.",
      "<strong>In the soil</strong> — plants need a pH close to neutral. Too acidic and farmers add quicklime; too basic and they add organic matter.",
      "<strong>In rain</strong> — below pH 5.6 it is acid rain, which turns rivers acidic and damages marble monuments.",
      "<strong>In self-defence</strong> — a bee sting injects an acid, so baking soda (a mild base) relieves it. A nettle sting injects methanoic acid; dock leaf sap neutralises it.",
    ] },
    { t: "note", kind: "memory", html: "Rule of thumb: <strong>acid problem → mild base, base problem → mild acid.</strong> That one line answers most application questions in this chapter." },

    { t: "h", text: "The five compounds you must know cold" },
    { t: "table", head: ["Compound", "Formula", "How it is made", "What it is used for"], rows: [
      ["Sodium hydroxide (caustic soda)", "NaOH", "Chlor-alkali process — electricity through brine (NaCl solution)", "Soaps, detergents, paper, degreasing metals. Chlorine and hydrogen are the by-products"],
      ["Bleaching powder", "CaOCl₂", "Cl₂ passed over dry slaked lime Ca(OH)₂", "Bleaching cotton and paper, disinfecting drinking water, oxidising agent"],
      ["Baking soda", "NaHCO₃", "NaCl + H₂O + CO₂ + NH₃ → NaHCO₃ + NH₄Cl", "Baking (releases CO₂ so cakes rise), antacid, in fire extinguishers"],
      ["Washing soda", "Na₂CO₃·10H₂O", "Heat baking soda, then recrystallise the Na₂CO₃ with water", "Removing hardness of water, glass and paper industry, cleaning"],
      ["Plaster of Paris", "CaSO₄·½H₂O", "Heat gypsum to 373 K (100 °C)", "Plaster casts for fractures, ceilings, statues, smoothing walls"],
    ] },
    { t: "note", kind: "trap", html: "Plaster of Paris must be heated to <strong>exactly 373 K</strong>. Heat it higher and you get anhydrous calcium sulphate ('dead burnt plaster'), which will no longer set. And it has to be stored in a moisture-proof container, because it sets on contact with water." },
    { t: "eq", lines: [
      "CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O&nbsp;&nbsp;<span class='faint'>(Plaster of Paris → gypsum, sets hard)</span>",
      "NaHCO₃ + heat → Na₂CO₃ + H₂O + CO₂&nbsp;&nbsp;<span class='faint'>(why baking soda makes cakes rise)</span>",
    ] },
    { t: "note", kind: "real", html: "Baking <em>powder</em> is baking soda plus a mild edible acid (tartaric acid). Without the acid, the sodium carbonate left behind would make the cake taste bitter. That is a favourite one-mark question." },

    { t: "h", text: "Water of crystallisation" },
    { t: "p", html: "Some salt crystals hold water molecules inside their crystal structure. Copper sulphate crystals are blue because of five such molecules — CuSO₄·5H₂O. Heat them and the water leaves, and the crystals turn white. Add water back and the blue returns." },
    { t: "note", kind: "exam", html: "Washing soda Na₂CO₃·10H₂O has <strong>10</strong> molecules of water of crystallisation; gypsum CaSO₄·2H₂O has 2; Plaster of Paris CaSO₄·½H₂O has half. These numbers get asked directly." },

    { t: "steps", title: "Why does a solution of sodium carbonate turn red litmus blue?",
      intro: "A three-mark reasoning question that catches many students.",
      steps: [
        "Sodium carbonate is the salt of a <strong>strong base</strong> (NaOH) and a <strong>weak acid</strong> (H₂CO₃).",
        "In water it hydrolyses: the weak acid formed does not ionise much, but the strong base does.",
        "So there is an excess of OH⁻ ions left in the solution.",
        "Excess OH⁻ means the solution is basic — pH greater than 7.",
      ],
      answer: "Because it is a salt of a strong base and a weak acid, its solution is basic and turns red litmus blue.",
    },
  ],
  formulas: [
    { name: "Neutralisation", expr: "Acid + Base → Salt + Water", note: "The essential reaction: H⁺ + OH⁻ → H₂O" },
    { name: "pH", expr: "pH &lt; 7 acidic &nbsp;·&nbsp; pH = 7 neutral &nbsp;·&nbsp; pH &gt; 7 basic", note: "Each unit is a ten-fold change in H⁺ concentration" },
  ],
  examFocus: [
    "Definitions of acid and base in terms of H⁺ and OH⁻ — the syllabus specifies this wording.",
    "The pop test (hydrogen) and the lime-water test (carbon dioxide), including what happens with excess CO₂.",
    "The difference between strong/weak and concentrated/dilute.",
    "pH applications: stomach, tooth decay, soil, acid rain, bee sting.",
    "The five compounds: formula, one preparation, and two uses each.",
    "Water of crystallisation numbers for washing soda, gypsum and Plaster of Paris.",
  ],
  flashcards: [
    { q: "Define an acid and a base in terms of ions.", a: "An acid produces H⁺ (hydronium, H₃O⁺) ions in aqueous solution. A base produces OH⁻ ions in aqueous solution." },
    { q: "Why does dry HCl gas not change the colour of dry litmus paper?", a: "Because HCl only releases H⁺ ions in the presence of water. Without water it does not ionise, so it cannot behave as an acid." },
    { q: "What is the difference between a base and an alkali?", a: "All alkalis are bases, but only bases that dissolve in water are called alkalis — NaOH, KOH, Ca(OH)₂. CuO is a base but not an alkali." },
    { q: "How do you test for hydrogen gas?", a: "Bring a burning splint near the mouth of the tube — the gas burns with a squeaky pop sound." },
    { q: "How do you test for carbon dioxide?", a: "Pass it through lime water — the lime water turns milky due to CaCO₃. If excess CO₂ is passed, the milkiness disappears as soluble Ca(HCO₃)₂ forms." },
    { q: "What is neutralisation? Give the general equation.", a: "The reaction between an acid and a base to give salt and water: Acid + Base → Salt + Water. At ion level, H⁺ + OH⁻ → H₂O." },
    { q: "Distinguish between a strong acid and a concentrated acid.", a: "Strong refers to complete ionisation in water (HCl, H₂SO₄). Concentrated refers to a small amount of water present. A dilute solution of HCl is still a strong acid." },
    { q: "Why is the pH scale called logarithmic?", a: "Each step of one pH unit means a ten-fold change in H⁺ ion concentration. pH 3 is 100 times more acidic than pH 5." },
    { q: "Why does tooth decay begin when the mouth pH falls below 5.5?", a: "Below pH 5.5 the enamel (calcium phosphate, the hardest substance in the body) starts to dissolve. Bacteria produce this acid from leftover sugar." },
    { q: "Write the formula and one use of bleaching powder.", a: "CaOCl₂. Made by passing chlorine over dry slaked lime. Used for bleaching cotton and paper, disinfecting drinking water, and as an oxidising agent." },
    { q: "Why is baking soda used in cakes?", a: "On heating, NaHCO₃ decomposes to give CO₂ gas, which is trapped in the batter and makes the cake rise and become soft and spongy." },
    { q: "Why is tartaric acid added to baking powder?", a: "To neutralise the sodium carbonate that would otherwise be left behind, which would make the cake taste bitter." },
    { q: "What is Plaster of Paris and how is it made?", a: "CaSO₄·½H₂O, made by heating gypsum (CaSO₄·2H₂O) to 373 K. On adding water it sets into a hard solid — used for plaster casts and ceilings." },
    { q: "Why must Plaster of Paris be stored in a moisture-proof container?", a: "It reacts with moisture in the air and sets into gypsum, becoming useless." },
    { q: "What is water of crystallisation? Give an example.", a: "A fixed number of water molecules present in one formula unit of a salt. Example: CuSO₄·5H₂O — the five water molecules give the crystals their blue colour." },
  ],
  quiz: [
    { q: "Which of these will turn phenolphthalein pink?", options: ["Lemon juice", "Vinegar", "Sodium hydroxide solution", "Distilled water"], answer: 2, why: "Phenolphthalein is colourless in acid and neutral solutions and pink only in bases. NaOH is a strong base." },
    { q: "A gas evolved on adding dilute HCl to a substance turns lime water milky. The substance contains:", options: ["A metal", "A carbonate or hydrogencarbonate", "A sulphate", "A chloride"], answer: 1, why: "Only carbonates and hydrogencarbonates give CO₂ with acids, and CO₂ is the gas that turns lime water milky." },
    { q: "The pH of a solution changes from 7 to 3. The H⁺ ion concentration has:", options: ["Decreased 4 times", "Increased 4 times", "Increased 10,000 times", "Stayed the same"], answer: 2, why: "Each pH unit is a factor of 10. Four units down means 10⁴ = 10,000 times more H⁺ ions." },
    { q: "Which one is a weak acid?", options: ["HCl", "H₂SO₄", "HNO₃", "CH₃COOH"], answer: 3, why: "Acetic (ethanoic) acid ionises only partially in water, so it is a weak acid. The other three ionise completely." },
    { q: "Bleaching powder is prepared by the action of chlorine on:", options: ["Quicklime", "Dry slaked lime", "Limestone", "Sodium hydroxide"], answer: 1, why: "Cl₂ is passed over dry slaked lime, Ca(OH)₂, to give CaOCl₂." },
    { q: "Washing soda has the formula:", options: ["NaHCO₃", "Na₂CO₃·10H₂O", "NaOH", "CaSO₄·½H₂O"], answer: 1, why: "Washing soda is sodium carbonate decahydrate — 10 molecules of water of crystallisation." },
    { q: "A farmer finds his soil is too acidic. He should add:", options: ["Vinegar", "Quicklime or slaked lime", "Ammonium sulphate", "More water"], answer: 1, why: "Acidic soil is corrected by adding a base. Quicklime (CaO) or slaked lime raises the pH towards neutral." },
    { q: "Which of these is a basic oxide?", options: ["CO₂", "SO₂", "CuO", "NO₂"], answer: 2, why: "Metal oxides are basic — CuO reacts with acids to give salt and water. The other three are non-metal (acidic) oxides." },
    { q: "In the chlor-alkali process, the gas produced at the cathode is:", options: ["Chlorine", "Hydrogen", "Oxygen", "Carbon dioxide"], answer: 1, why: "Electrolysis of brine gives chlorine at the anode, hydrogen at the cathode, and NaOH near the cathode." },
    { q: "The correct way to dilute a concentrated acid is to:", options: ["Add water to the acid", "Add acid slowly to water with stirring", "Mix them quickly", "Heat the acid first"], answer: 1, why: "Dilution is strongly exothermic. Adding water to acid causes violent splashing; acid must always be added slowly to water." },
    { q: "Gypsum is heated to 373 K to make Plaster of Paris. What is removed?", options: ["All the water", "One and a half molecules of water", "Half a molecule of water", "Carbon dioxide"], answer: 1, why: "CaSO₄·2H₂O → CaSO₄·½H₂O + 1½H₂O. One and a half water molecules are driven off." },
    { q: "An aqueous solution of sodium chloride is neutral because it is the salt of:", options: ["A strong acid and a weak base", "A weak acid and a strong base", "A strong acid and a strong base", "A weak acid and a weak base"], answer: 2, why: "NaCl comes from HCl (strong acid) and NaOH (strong base). Both ionise fully, so neither H⁺ nor OH⁻ is in excess — pH is 7." },
  ],
  keyTopics: [
    { name: "Chemical properties of acids and bases — reaction with metals, carbonates, bases", importance: "high", note: "The pop test (H₂) and lime-water test (CO₂) are the most frequently examined practical observations in the chapter." },
    { name: "The pH scale and its everyday applications", importance: "high", note: "Stomach acidity, tooth decay, soil treatment, acid rain and bee stings are the standard application questions." },
    { name: "The five key compounds — NaOH, bleaching powder, baking soda, washing soda, Plaster of Paris", importance: "high", note: "Formula, one preparation and two uses each; frequent 3–5 mark questions, especially the chlor-alkali process." },
    { name: "Strong/weak vs concentrated/dilute", importance: "medium", note: "A reliable short-answer or assertion–reason distinction question." },
    { name: "Indicators, including olfactory indicators", importance: "medium", note: "Onion and vanilla essence as olfactory indicators is a recurring 1–2 mark question." },
    { name: "Water of crystallisation", importance: "medium", note: "The exact number of water molecules for washing soda, gypsum and Plaster of Paris is asked directly." },
    { name: "Acids and bases defined in terms of H⁺ and OH⁻ ions", importance: "medium", note: "The syllabus specifies this exact wording for the definition." },
  ],
  written: [
    { q: "Why does an aqueous solution of an acid conduct electricity?", marks: 1, kind: "short", importance: "medium",
      answer: "In water, an acid ionises to form free-moving ions — H⁺ (as H₃O⁺) and the corresponding negative ion — and it is the movement of these charged ions that conducts an electric current." },
    { q: "Name the gas evolved when dilute hydrochloric acid reacts with sodium carbonate. How is it identified?", marks: 1, kind: "short", importance: "high",
      answer: "Carbon dioxide gas is evolved. It is identified by passing it through lime water, which turns milky: <strong>Ca(OH)₂ + CO₂ → CaCO₃ + H₂O</strong>." },
    { q: "Write balanced chemical equations for the reaction of dilute sulphuric acid with (i) zinc granules and (ii) sodium hydroxide solution.", marks: 2, kind: "numerical", importance: "high",
      answer: "(i) <strong>Zn + H₂SO₄ → ZnSO₄ + H₂↑</strong>.<br>(ii) <strong>2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O</strong>." },
    { q: "What is meant by 'water of crystallisation'? Give the formula of washing soda and state how many molecules of water of crystallisation it contains.", marks: 2, kind: "short", importance: "medium",
      answer: "Water of crystallisation is a fixed number of water molecules present in one formula unit of a salt, which give the crystal its characteristic shape. Washing soda, <strong>Na₂CO₃·10H₂O</strong>, contains <strong>10</strong> molecules of water of crystallisation." },
    { q: "A milkman adds a very small amount of baking soda to fresh milk. Explain why (i) it takes longer for the milk to set as curd, and (ii) this shifts the milk's pH from about 6 to slightly alkaline.", marks: 2, kind: "short", importance: "high",
      answer: "(i) Fresh milk is naturally slightly acidic (pH about 6), and curdling depends on bacteria producing acid. Baking soda, a mild base, raises the pH, so it takes longer before the milk becomes acidic enough to curdle.<br>(ii) Baking soda (NaHCO₃) is basic and neutralises some of the natural acid already present in milk, shifting the pH from about 6 towards the alkaline side." },
    { q: "A compound X, used as an antacid, reacts with dilute hydrochloric acid to neutralise excess acid in the stomach. Identify X, write the chemical equation, and explain why it is used to treat acidity.", marks: 3, kind: "short", importance: "high",
      answer: "X is <strong>magnesium hydroxide, Mg(OH)₂</strong> (milk of magnesia). <strong>Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O</strong>. It is used to treat acidity because it is a mild base that neutralises the excess hydrochloric acid produced in the stomach, relieving the burning sensation, without being strong enough to harm the stomach lining." },
    { q: "Explain why dry HCl gas does not change the colour of dry litmus paper, but its aqueous solution does. Also explain why an acid should always be added to water, and not the other way round, while preparing a dilute solution.", marks: 3, kind: "short", importance: "high",
      answer: "An acid behaves as an acid only by releasing H⁺ (as H₃O⁺) ions, and this ionisation happens only in the presence of water: <strong>HCl + H₂O → H₃O⁺ + Cl⁻</strong>. Dry HCl gas has no water to ionise in, so it forms no H⁺ ions and does not affect dry litmus paper.<br>Dissolving a concentrated acid in water is a highly exothermic process. Adding water to the acid can make the mixture spatter violently and cause burns. Adding acid slowly to a larger volume of water, with stirring, lets the heat spread out and be absorbed safely." },
    { q: "Describe an activity to show that carbon dioxide gas evolves when dilute hydrochloric acid reacts with sodium carbonate, and explain how you would confirm the identity of the gas.", marks: 3, kind: "diagram", importance: "medium",
      answer: "Take a small amount of sodium carbonate in a test tube and add dilute HCl. Bubbles of a colourless gas are seen: <strong>Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑</strong>. Pass this gas through freshly prepared lime water using a delivery tube. If the gas is CO₂, the lime water turns milky: <strong>Ca(OH)₂ + CO₂ → CaCO₃ + H₂O</strong>. Passing the gas in excess makes the milkiness disappear, as soluble calcium hydrogencarbonate forms — confirming the gas is indeed carbon dioxide." },
    { q: "Describe how sodium hydroxide, chlorine and hydrogen are obtained from the electrolysis of a saturated solution of sodium chloride. Write the equation, and give one use each of the three products.", marks: 5, kind: "long", importance: "high",
      answer: "This is called the <strong>chlor-alkali process</strong>: electricity is passed through a saturated solution of NaCl (brine). <strong>2NaCl + 2H₂O →(electricity) 2NaOH + Cl₂↑ + H₂↑</strong>. Chlorine gas is released at the anode, hydrogen gas at the cathode, and NaOH solution forms near the cathode.<br><strong>Uses:</strong> sodium hydroxide is used to make soaps and detergents; chlorine is used to make bleaching powder and to disinfect drinking water; hydrogen is used as a fuel and in the manufacture of ammonia." },
    { q: "Write the chemical name and formula of Plaster of Paris. Describe how it is prepared from gypsum, write the balanced equation for its reaction with water, and state why it must be stored in an airtight container.", marks: 5, kind: "long", importance: "high",
      answer: "Plaster of Paris is <strong>calcium sulphate hemihydrate, CaSO₄·½H₂O</strong>. It is prepared by heating gypsum (CaSO₄·2H₂O) to 373 K: <strong>CaSO₄·2H₂O →(373 K) CaSO₄·½H₂O + 1½H₂O</strong>.<br>When mixed with water it sets into a hard solid, regaining the water it had lost: <strong>CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O</strong> (gypsum).<br>Because it reacts with moisture in the air and slowly turns back into gypsum — becoming useless as a plaster — it must always be stored in an airtight, moisture-proof container." },
  ],
  assertionReason: [
    { assertion: "Bubbles of a gas are observed when a solution of sodium hydroxide is added to zinc granules.",
      reason: "Zinc is a metal, and metals react with all bases to liberate hydrogen gas.",
      answer: 2, importance: "medium",
      why: "The assertion is true — zinc does react with NaOH, an amphoteric metal reaction: Zn + 2NaOH → Na₂ZnO₂ + H₂. But the reason overgeneralises and is false: only strong alkalis such as NaOH and KOH react this way, not 'all' bases." },
    { assertion: "A few drops of phenolphthalein added to a solution of baking soda turn the solution pink.",
      reason: "Baking soda, NaHCO₃, is the salt of a strong base and a weak acid, and gives a basic solution in water.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the reason correctly explains the assertion — a mildly basic solution turns phenolphthalein pink." },
    { assertion: "Tooth decay begins when the pH inside the mouth falls below 5.5.",
      reason: "At this pH, bacteria in the mouth produce a strong acid from leftover sugar, which instantly dissolves the enamel.",
      answer: 2, importance: "high",
      why: "The assertion is true. But the reason is false in its chemistry: the acid produced by these bacteria is a weak organic acid, not a strong acid — it is the prolonged exposure below pH 5.5, not the 'strength' of the acid, that erodes the enamel over time." },
    { assertion: "An acid must always be added slowly to water while diluting, never the reverse.",
      reason: "Dissolving an acid in water is a highly exothermic process, and adding water to a concentrated acid can cause dangerous spattering.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion — the safe way to dilute is to add acid to water, not water to acid." },
  ],
  caseStudies: [
    { title: "Reading the pH scale", importance: "high",
      source: "A student measured the pH of five common samples using universal indicator paper:<br><table><thead><tr><th>Sample</th><th>Lemon juice</th><th>Human blood</th><th>Milk of magnesia</th><th>Gastric juice</th><th>Pure water</th></tr></thead><tbody><tr><td>pH</td><td>2.2</td><td>7.4</td><td>10</td><td>1.5</td><td>7</td></tr></tbody></table>",
      parts: [
        { q: "Which sample is the most acidic, and which is the most basic?", marks: 1, answer: "Gastric juice (pH 1.5) is the most acidic; milk of magnesia (pH 10) is the most basic." },
        { q: "How many times greater is the H⁺ ion concentration in gastric juice compared to pure water?", marks: 2, answer: "The pH difference is 7 − 1.5 = 5.5 units. Since each pH unit is a ten-fold change, the H⁺ concentration in gastric juice is roughly <strong>3 × 10⁵ (about three hundred thousand) times</strong> greater than in pure water." },
        { q: "A person suffering from acidity is advised to take milk of magnesia. Explain why, using the pH values given.", marks: 1, answer: "Milk of magnesia has a pH of about 10, so it is a mild base. It neutralises the excess gastric acid (pH 1.5) in the stomach, bringing the pH back closer to normal and relieving the burning sensation of acidity." },
        { q: "Is human blood acidic, basic or neutral?", marks: 1, answer: "Slightly basic — its pH (7.4) is a little above 7." },
      ] },
    { title: "Making baking powder work", importance: "medium",
      source: "A baker mixes baking soda into cake batter. On heating in the oven, the batter is observed to rise and become light and spongy. A chemistry student notices that baking soda used alone, with no added acid, leaves the cake tasting bitter — which is why bakers use baking powder, a mixture of baking soda and a mild edible acid such as tartaric acid.",
      parts: [
        { q: "Write the balanced equation for the decomposition of baking soda on heating.", marks: 1, answer: "<strong>NaHCO₃ →(heat) Na₂CO₃ + H₂O + CO₂</strong>." },
        { q: "Which gas causes the batter to rise, and why?", marks: 1, answer: "Carbon dioxide gas, released on heating, gets trapped as bubbles in the moist batter, making it rise and turn light and spongy." },
        { q: "Why does baking soda alone leave a bitter taste, and how does tartaric acid solve this problem?", marks: 2, answer: "On heating, baking soda leaves behind sodium carbonate, Na₂CO₃, which is basic and tastes bitter. Tartaric acid, a mild edible acid, reacts with and neutralises this sodium carbonate, so no bitter-tasting residue is left in the baked cake." },
        { q: "Give the chemical formula of baking soda and state one other everyday use besides baking.", marks: 1, answer: "NaHCO₃. It is also used as a mild antacid to relieve acidity, and in soda-acid fire extinguishers." },
      ] },
  ],
};
