import type { Chapter } from "@/lib/types";

export const ch03: Chapter = {
  slug: "metals-and-non-metals",
  num: 3,
  title: "Metals and Non-metals",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 22,
  blurb: "Why metals shine and bend, why some are found pure in the ground and others need a furnace, and how the reactivity series predicts all of it.",
  bigIdea: "Metals want to lose electrons; non-metals want to gain them. Every physical property, every reaction, and the entire logic of extracting a metal from its ore comes out of that one difference.",
  syllabus: [
    "Properties of metals and non-metals", "Reactivity series",
    "Formation and properties of ionic compounds",
    "Basic metallurgical processes", "Corrosion and its prevention",
  ],
  blocks: [
    { t: "h", text: "Physical properties — and the exceptions that get examined" },
    { t: "table", head: ["Property", "Metals", "Non-metals"], rows: [
      ["Appearance", "Lustrous (shiny)", "Dull — <em>except</em> iodine, graphite, diamond"],
      ["Hardness", "Hard", "Soft — <em>except</em> diamond, the hardest natural substance"],
      ["State at room temp.", "Solid — <em>except</em> mercury", "Solid, liquid or gas — bromine is the liquid one"],
      ["Malleable / ductile", "Yes — gold and silver most of all", "No, they are brittle"],
      ["Conductivity", "Good — silver best, then copper", "Poor — <em>except</em> graphite"],
      ["Melting point", "High — <em>except</em> gallium and caesium, which melt in your hand", "Low — <em>except</em> diamond and graphite"],
      ["Sonorous", "Yes (that is why bells are metal)", "No"],
    ] },
    { t: "note", kind: "memory", html: "The exceptions are worth more marks than the rules, because everyone knows the rules. Remember the set: <strong>mercury, bromine, iodine, graphite, diamond, gallium, caesium</strong>." },

    { t: "h", text: "Chemical properties of metals" },
    { t: "list", ordered: true, items: [
      "<strong>With oxygen → metal oxide (basic).</strong> 2Cu + O₂ → 2CuO (black). Some oxides such as Al₂O₃ and ZnO are <em>amphoteric</em> — they react with both acids and bases.",
      "<strong>With water.</strong> K and Na react violently with cold water (and catch fire); Ca and Mg react with hot water; Al, Zn and Fe react only with steam; Cu, Ag and Au do not react at all.",
      "<strong>With dilute acid → salt + hydrogen.</strong> But copper, silver and gold do not displace hydrogen, because they sit below hydrogen in the reactivity series.",
      "<strong>With another metal's salt solution → displacement,</strong> if the added metal is more reactive.",
    ] },
    { t: "note", kind: "trap", html: "Nitric acid is the odd one out. It is such a strong oxidising agent that it oxidises the hydrogen produced straight into water, so you usually get no H₂ gas. The exceptions are magnesium and manganese with <em>very</em> dilute HNO₃." },

    { t: "h", text: "The reactivity series" },
    { t: "p", html: "This one ladder explains displacement reactions, which metals occur free in nature, and which extraction method is needed. It is genuinely the most useful thing in the chapter." },
    { t: "sim", id: "reactivity-series" },
    { t: "note", kind: "memory", html: "<strong>K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Ag, Au</strong> — one sentence that works: <em>Kanpur Na Chalo, Magar Aluminium Zinc Ferrous Lead Hydrogen Copper Silver Gold.</em> Use whatever sentence sticks; just do not get the order wrong." },
    { t: "note", kind: "real", html: "The thermite reaction — Fe₂O₃ + 2Al → 2Fe + Al₂O₃ — is displacement releasing so much heat that the iron comes out molten. Railway workers use it to weld broken rails on the spot." },

    { t: "h", text: "Ionic compounds — why salt behaves the way it does" },
    { t: "p", html: "Sodium has 1 electron in its outermost shell; chlorine needs 1. Sodium gives it away and becomes Na⁺; chlorine takes it and becomes Cl⁻. The two opposite charges attract strongly, and that attraction is the ionic bond." },
    { t: "eq", lines: [
      "Na (2,8,1) → Na⁺ (2,8) + e⁻",
      "Cl (2,8,7) + e⁻ → Cl⁻ (2,8,8)",
      "<span class='faint'>Both now have a full outer shell — the same arrangement as a noble gas.</span>",
    ] },
    { t: "p", html: "Every property of an ionic compound follows from how strong that attraction is:" },
    { t: "list", items: [
      "<strong>Hard, crystalline solids</strong> — the ions are locked in a rigid lattice.",
      "<strong>High melting and boiling points</strong> — a lot of energy is needed to break the lattice apart.",
      "<strong>Soluble in water, insoluble in petrol or kerosene</strong> — water can pull the ions apart, organic solvents cannot.",
      "<strong>Do not conduct as solids, but do when molten or dissolved</strong> — the ions must be free to move before a current can flow. This one is asked constantly.",
    ] },

    { t: "h", text: "Getting a metal out of the ground" },
    { t: "p", html: "Minerals are any naturally occurring compound of a metal. An <strong>ore</strong> is a mineral from which the metal can be extracted profitably. The method depends entirely on where the metal sits in the reactivity series." },
    { t: "table", head: ["Reactivity", "Found as", "Extraction method"], rows: [
      ["<strong>Low</strong> — Au, Ag, Pt, Cu", "Often free (native) in nature", "Simple heating in air, or just physical separation"],
      ["<strong>Middle</strong> — Zn, Fe, Pb, Cu", "Sulphides and carbonates", "Convert to oxide (roasting or calcination), then <strong>reduce with carbon</strong>"],
      ["<strong>High</strong> — K, Na, Ca, Mg, Al", "Chlorides and oxides", "Carbon is not strong enough — use <strong>electrolytic reduction</strong>"],
    ] },
    { t: "p", html: "The three steps in order, and the difference the board always tests:" },
    { t: "list", ordered: true, items: [
      "<strong>Concentration</strong> — remove the gangue (unwanted earthy impurities) from the ore.",
      "<strong>Conversion to oxide.</strong> <strong>Roasting</strong> heats a <em>sulphide</em> ore strongly in the presence of air. <strong>Calcination</strong> heats a <em>carbonate</em> ore in limited air. Oxides are far easier to reduce than sulphides or carbonates.",
      "<strong>Reduction to metal</strong> — with carbon for middle metals, by electrolysis for the reactive ones. Then <strong>refining</strong>, usually by electrolysis, to get pure metal.",
    ] },
    { t: "note", kind: "memory", html: "Ro<strong>a</strong>sting → sulphide, in <strong>a</strong>ir. Calcination → carbonate. Match the first letters and you will never confuse them again." },
    { t: "eq", lines: [
      "2ZnS + 3O₂ → 2ZnO + 2SO₂&nbsp;&nbsp;<span class='faint'>(roasting)</span>",
      "ZnCO₃ → ZnO + CO₂&nbsp;&nbsp;<span class='faint'>(calcination)</span>",
      "ZnO + C → Zn + CO&nbsp;&nbsp;<span class='faint'>(reduction with carbon)</span>",
    ] },
    { t: "note", kind: "why", title: "Why is aluminium so expensive to make?", html: "Aluminium is high in the reactivity series, so carbon cannot pull the oxygen off it. Molten Al₂O₃ has to be electrolysed, which needs enormous amounts of electricity. That is also why recycling aluminium saves about 95% of the energy." },

    { t: "h", text: "Corrosion, alloys and the passive layer" },
    { t: "p", html: "Aluminium is very reactive, yet an aluminium window frame lasts decades. The reason: it reacts instantly with air to form a thin, tough, non-porous layer of Al₂O₃ that seals the metal underneath. Iron oxide flakes off instead, exposing fresh metal — which is why rust keeps eating deeper." },
    { t: "list", items: [
      "<strong>Rusting needs both air and moisture.</strong> Iron in dry air or in boiled, oil-covered water does not rust. This is the standard experiment.",
      "<strong>Galvanisation</strong> — coating iron with zinc. Zinc is more reactive, so it corrodes first and protects the iron even if the coating gets scratched.",
      "<strong>Alloying</strong> — melting a metal with another element. Stainless steel is iron + chromium + nickel and does not rust at all.",
    ] },
    { t: "table", head: ["Alloy", "Made of", "Why it is used"], rows: [
      ["Steel", "Iron + carbon", "Much harder and stronger than pure iron"],
      ["Stainless steel", "Iron + chromium + nickel", "Does not rust — cutlery, utensils"],
      ["Brass", "Copper + zinc", "Harder than copper, does not tarnish easily"],
      ["Bronze", "Copper + tin", "Hard and durable — statues, medals"],
      ["Solder", "Lead + tin", "Very low melting point — joining electrical wires"],
      ["Amalgam", "Any metal + mercury", "Mercury alloys are called amalgams"],
    ] },
    { t: "note", kind: "exam", html: "Alloys are <em>always</em> less conductive and have a <em>lower</em> melting point than the pure metal. That is exactly why solder works." },

    { t: "steps", title: "Why does a copper vessel lose its shine, and how do you clean it?",
      intro: "Two marks, and a nice example of chemistry you can see at home.",
      steps: [
        "Moist air contains CO₂ and moisture. Copper reacts slowly with both.",
        "It forms a green coating of basic copper carbonate, CuCO₃·Cu(OH)₂.",
        "This is corrosion — the shiny metal surface is now covered by a compound.",
        "Lemon or tamarind juice contains citric/tartaric acid, which reacts with and dissolves the basic carbonate.",
      ],
      answer: "The green layer is basic copper carbonate. Acidic lemon or tamarind juice dissolves it and restores the shine.",
    },
  ],
  formulas: [
    { name: "Thermite reaction", expr: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat", note: "Displacement; the iron produced is molten. Used for welding rails." },
    { name: "Roasting", expr: "2MS + 3O₂ → 2MO + 2SO₂", note: "Sulphide ore heated strongly in air" },
    { name: "Calcination", expr: "MCO₃ → MO + CO₂", note: "Carbonate ore heated in limited air" },
  ],
  examFocus: [
    "The exceptions table — mercury, bromine, iodine, graphite, diamond.",
    "The reactivity series in the correct order, and using it to predict displacement.",
    "Why ionic compounds conduct only when molten or dissolved.",
    "Roasting vs calcination — the one-word difference (sulphide vs carbonate).",
    "Why highly reactive metals need electrolytic reduction while middle ones use carbon.",
    "The two conditions for rusting, and three prevention methods with reasons.",
    "Composition and one use for each alloy in the table.",
  ],
  flashcards: [
    { q: "Name the only metal that is liquid at room temperature, and the only non-metal.", a: "Mercury is the liquid metal; bromine is the liquid non-metal." },
    { q: "Which non-metal is lustrous and which conducts electricity?", a: "Iodine is lustrous. Graphite conducts electricity because it has free delocalised electrons." },
    { q: "What is an amphoteric oxide? Give two examples.", a: "An oxide that reacts with both acids and bases to give salt and water. Examples: Al₂O₃ and ZnO." },
    { q: "Why do metals not usually give hydrogen with nitric acid?", a: "HNO₃ is a strong oxidising agent — it oxidises the hydrogen produced into water. Exceptions: Mg and Mn with very dilute HNO₃." },
    { q: "Write the reactivity series from potassium to gold.", a: "K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Ag, Au — most reactive at the top." },
    { q: "Why does an ionic compound conduct electricity when molten but not when solid?", a: "In the solid the ions are held rigidly in a lattice and cannot move. When molten or dissolved the ions become free to move and carry the current." },
    { q: "Define mineral, ore and gangue.", a: "A mineral is any naturally occurring compound of a metal. An ore is a mineral from which the metal can be extracted profitably. Gangue is the unwanted earthy impurity in the ore." },
    { q: "What is the difference between roasting and calcination?", a: "Roasting heats a sulphide ore strongly in the presence of air. Calcination heats a carbonate ore in limited air. Both convert the ore into the oxide." },
    { q: "Why can't carbon be used to reduce aluminium oxide?", a: "Aluminium is more reactive than carbon, so carbon cannot take the oxygen away from it. Electrolytic reduction is used instead." },
    { q: "What is the thermite reaction and where is it used?", a: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat. So much heat is released that the iron comes out molten — used for welding broken railway tracks and cracked machine parts." },
    { q: "What two conditions are needed for iron to rust?", a: "Air (oxygen) and moisture. Iron kept in dry air, or in water with no dissolved oxygen, does not rust." },
    { q: "What is galvanisation and why does it still work if scratched?", a: "Coating iron with a layer of zinc. Zinc is more reactive than iron, so it corrodes preferentially and protects the iron even where the coating is broken." },
    { q: "What is an alloy? How do its properties differ from the pure metal?", a: "A homogeneous mixture of a metal with another metal or non-metal. Alloys are harder and more resistant to corrosion, but have lower electrical conductivity and a lower melting point." },
    { q: "Why does aluminium not corrode away despite being reactive?", a: "It forms a thin, hard, non-porous layer of Al₂O₃ on the surface that seals the metal underneath and stops further reaction." },
    { q: "Why is sodium stored in kerosene?", a: "Sodium reacts vigorously with the oxygen and moisture in air, catching fire. Kerosene keeps air away from it." },
  ],
  quiz: [
    { q: "Which of these pairs correctly matches an exception?", options: ["Mercury — liquid metal", "Graphite — non-conducting non-metal", "Diamond — soft non-metal", "Iodine — dull non-metal"], answer: 0, why: "Mercury is the only metal liquid at room temperature. Graphite conducts, diamond is the hardest substance, and iodine is lustrous." },
    { q: "Zinc oxide reacts with both HCl and NaOH. It is therefore:", options: ["A basic oxide", "An acidic oxide", "An amphoteric oxide", "A neutral oxide"], answer: 2, why: "Oxides that react with both acids and bases are amphoteric. Al₂O₃ and ZnO are the two examples in the syllabus." },
    { q: "Iron nails dipped in copper sulphate solution turn brownish and the solution fades. This is because:", options: ["Copper displaces iron", "Iron displaces copper as iron is more reactive", "The nails dissolve in water", "Copper sulphate decomposes"], answer: 1, why: "Iron is above copper in the reactivity series: Fe + CuSO₄ → FeSO₄ + Cu. Copper deposits on the nail and the blue colour fades to pale green." },
    { q: "A sulphide ore is converted to its oxide by:", options: ["Calcination", "Roasting", "Electrolysis", "Reduction with carbon"], answer: 1, why: "Roasting heats a sulphide ore strongly in the presence of air. Calcination is for carbonate ores." },
    { q: "Which metal is extracted by electrolytic reduction?", options: ["Copper", "Zinc", "Aluminium", "Lead"], answer: 2, why: "Aluminium is high in the reactivity series, so carbon cannot reduce its oxide. Molten Al₂O₃ is electrolysed instead." },
    { q: "Ionic compounds have high melting points because:", options: ["They are heavy", "The ions are free to move", "Strong electrostatic forces hold the ions in a lattice", "They contain water"], answer: 2, why: "A large amount of energy is needed to overcome the strong attraction between oppositely charged ions in the lattice." },
    { q: "Which alloy is used for joining electrical wires?", options: ["Brass", "Bronze", "Solder", "Stainless steel"], answer: 2, why: "Solder is lead + tin and has a very low melting point, so it melts easily and sets quickly." },
    { q: "A metal that can be extracted simply by heating its oxide in air is likely to be:", options: ["Very reactive", "Moderately reactive", "Low in the reactivity series", "A non-metal"], answer: 2, why: "Only low-reactivity metals such as mercury and copper have oxides unstable enough to decompose on simple heating." },
    { q: "Silver articles turn black over time. The compound formed is:", options: ["Ag₂O", "Ag₂S", "AgCl", "AgNO₃"], answer: 1, why: "Silver reacts with hydrogen sulphide in the air to form black silver sulphide, Ag₂S." },
    { q: "Which statement about the electron transfer in NaCl is correct?", options: ["Chlorine loses one electron", "Sodium gains one electron", "Sodium loses one electron to chlorine", "Both share one electron"], answer: 2, why: "Sodium (2,8,1) loses its single valence electron to become Na⁺ (2,8). Chlorine (2,8,7) accepts it to become Cl⁻ (2,8,8)." },
    { q: "Food cans are coated with tin rather than zinc because:", options: ["Tin is cheaper", "Tin is less reactive than zinc and does not contaminate the food", "Zinc does not stick to iron", "Tin is more reactive"], answer: 1, why: "Zinc is more reactive and would react with food acids. Tin is less reactive and safe for food contact." },
    { q: "The green coating on old copper vessels is:", options: ["Copper oxide", "Copper sulphide", "Basic copper carbonate", "Copper chloride"], answer: 2, why: "Moist air containing CO₂ slowly forms basic copper carbonate, CuCO₃·Cu(OH)₂ — removable with lemon or tamarind juice." },
  ],
};
