import type { Chapter } from "@/lib/types";

export const ch03: Chapter = {
  slug: "metals-and-non-metals",
  num: 3,
  title: "Metals and Non-metals",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 22,
  blurb: "Why metals shine and bend, why some are found pure in the ground and others need a furnace, and how the reactivity series predicts all of it.",
  bigIdea: "Metals want to lose electrons; non-metals want to gain them. Every physical property, every reaction, and the entire logic of extracting a metal from its ore comes out of that one difference.",
  syllabus: [
    "Properties of metals and non-metals", "Reactivity series",
    "Formation and properties of ionic compounds",
    "Basic metallurgical processes", "Corrosion and its prevention",
  ],
  blocks: [
    { t: "h", text: "Physical properties — and the exceptions that get examined" },
    { t: "table", head: ["Property", "Metals", "Non-metals"], rows: [
      ["Appearance", "Lustrous (shiny)", "Dull — <em>except</em> iodine, graphite, diamond"],
      ["Hardness", "Hard", "Soft — <em>except</em> diamond, the hardest natural substance"],
      ["State at room temp.", "Solid — <em>except</em> mercury", "Solid, liquid or gas — bromine is the liquid one"],
      ["Malleable / ductile", "Yes — gold and silver most of all", "No, they are brittle"],
      ["Conductivity", "Good — silver best, then copper", "Poor — <em>except</em> graphite"],
      ["Melting point", "High — <em>except</em> gallium and caesium, which melt in your hand", "Low — <em>except</em> diamond and graphite"],
      ["Sonorous", "Yes (that is why bells are metal)", "No"],
    ] },
    { t: "note", kind: "memory", html: "The exceptions are worth more marks than the rules, because everyone knows the rules. Remember the set: <strong>mercury, bromine, iodine, graphite, diamond, gallium, caesium</strong>." },

    { t: "h", text: "Chemical properties of metals" },
    { t: "list", ordered: true, items: [
      "<strong>With oxygen → metal oxide (basic).</strong> 2Cu + O₂ → 2CuO (black). Some oxides such as Al₂O₃ and ZnO are <em>amphoteric</em> — they react with both acids and bases.",
      "<strong>With water.</strong> K and Na react violently with cold water (and catch fire); Ca and Mg react with hot water; Al, Zn and Fe react only with steam; Cu, Ag and Au do not react at all.",
      "<strong>With dilute acid → salt + hydrogen.</strong> But copper, silver and gold do not displace hydrogen, because they sit below hydrogen in the reactivity series.",
      "<strong>With another metal's salt solution → displacement,</strong> if the added metal is more reactive.",
    ] },
    { t: "note", kind: "trap", html: "Nitric acid is the odd one out. It is such a strong oxidising agent that it oxidises the hydrogen produced straight into water, so you usually get no H₂ gas. The exceptions are magnesium and manganese with <em>very</em> dilute HNO₃." },

    { t: "h", text: "The reactivity series" },
    { t: "p", html: "This one ladder explains displacement reactions, which metals occur free in nature, and which extraction method is needed. It is genuinely the most useful thing in the chapter." },
    { t: "sim", id: "reactivity-series" },
    { t: "note", kind: "memory", html: "<strong>K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Ag, Au</strong> — one sentence that works: <em>Kanpur Na Chalo, Magar Aluminium Zinc Ferrous Lead Hydrogen Copper Silver Gold.</em> Use whatever sentence sticks; just do not get the order wrong." },
    { t: "note", kind: "real", html: "The thermite reaction — Fe₂O₃ + 2Al → 2Fe + Al₂O₃ — is displacement releasing so much heat that the iron comes out molten. Railway workers use it to weld broken rails on the spot." },

    { t: "h", text: "Ionic compounds — why salt behaves the way it does" },
    { t: "p", html: "Sodium has 1 electron in its outermost shell; chlorine needs 1. Sodium gives it away and becomes Na⁺; chlorine takes it and becomes Cl⁻. The two opposite charges attract strongly, and that attraction is the ionic bond." },
    { t: "eq", lines: [
      "Na (2,8,1) → Na⁺ (2,8) + e⁻",
      "Cl (2,8,7) + e⁻ → Cl⁻ (2,8,8)",
      "<span class='faint'>Both now have a full outer shell — the same arrangement as a noble gas.</span>",
    ] },
    { t: "p", html: "Every property of an ionic compound follows from how strong that attraction is:" },
    { t: "list", items: [
      "<strong>Hard, crystalline solids</strong> — the ions are locked in a rigid lattice.",
      "<strong>High melting and boiling points</strong> — a lot of energy is needed to break the lattice apart.",
      "<strong>Soluble in water, insoluble in petrol or kerosene</strong> — water can pull the ions apart, organic solvents cannot.",
      "<strong>Do not conduct as solids, but do when molten or dissolved</strong> — the ions must be free to move before a current can flow. This one is asked constantly.",
    ] },

    { t: "h", text: "Getting a metal out of the ground" },
    { t: "p", html: "Minerals are any naturally occurring compound of a metal. An <strong>ore</strong> is a mineral from which the metal can be extracted profitably. The method depends entirely on where the metal sits in the reactivity series." },
    { t: "table", head: ["Reactivity", "Found as", "Extraction method"], rows: [
      ["<strong>Low</strong> — Au, Ag, Pt, Cu", "Often free (native) in nature", "Simple heating in air, or just physical separation"],
      ["<strong>Middle</strong> — Zn, Fe, Pb, Cu", "Sulphides and carbonates", "Convert to oxide (roasting or calcination), then <strong>reduce with carbon</strong>"],
      ["<strong>High</strong> — K, Na, Ca, Mg, Al", "Chlorides and oxides", "Carbon is not strong enough — use <strong>electrolytic reduction</strong>"],
    ] },
    { t: "p", html: "The three steps in order, and the difference the board always tests:" },
    { t: "list", ordered: true, items: [
      "<strong>Concentration</strong> — remove the gangue (unwanted earthy impurities) from the ore.",
      "<strong>Conversion to oxide.</strong> <strong>Roasting</strong> heats a <em>sulphide</em> ore strongly in the presence of air. <strong>Calcination</strong> heats a <em>carbonate</em> ore in limited air. Oxides are far easier to reduce than sulphides or carbonates.",
      "<strong>Reduction to metal</strong> — with carbon for middle metals, by electrolysis for the reactive ones. Then <strong>refining</strong>, usually by electrolysis, to get pure metal.",
    ] },
    { t: "note", kind: "memory", html: "Ro<strong>a</strong>sting → sulphide, in <strong>a</strong>ir. Calcination → carbonate. Match the first letters and you will never confuse them again." },
    { t: "eq", lines: [
      "2ZnS + 3O₂ → 2ZnO + 2SO₂&nbsp;&nbsp;<span class='faint'>(roasting)</span>",
      "ZnCO₃ → ZnO + CO₂&nbsp;&nbsp;<span class='faint'>(calcination)</span>",
      "ZnO + C → Zn + CO&nbsp;&nbsp;<span class='faint'>(reduction with carbon)</span>",
    ] },
    { t: "note", kind: "why", title: "Why is aluminium so expensive to make?", html: "Aluminium is high in the reactivity series, so carbon cannot pull the oxygen off it. Molten Al₂O₃ has to be electrolysed, which needs enormous amounts of electricity. That is also why recycling aluminium saves about 95% of the energy." },

    { t: "h", text: "Corrosion, alloys and the passive layer" },
    { t: "p", html: "Aluminium is very reactive, yet an aluminium window frame lasts decades. The reason: it reacts instantly with air to form a thin, tough, non-porous layer of Al₂O₃ that seals the metal underneath. Iron oxide flakes off instead, exposing fresh metal — which is why rust keeps eating deeper." },
    { t: "list", items: [
      "<strong>Rusting needs both air and moisture.</strong> Iron in dry air or in boiled, oil-covered water does not rust. This is the standard experiment.",
      "<strong>Galvanisation</strong> — coating iron with zinc. Zinc is more reactive, so it corrodes first and protects the iron even if the coating gets scratched.",
      "<strong>Alloying</strong> — melting a metal with another element. Stainless steel is iron + chromium + nickel and does not rust at all.",
    ] },
    { t: "table", head: ["Alloy", "Made of", "Why it is used"], rows: [
      ["Steel", "Iron + carbon", "Much harder and stronger than pure iron"],
      ["Stainless steel", "Iron + chromium + nickel", "Does not rust — cutlery, utensils"],
      ["Brass", "Copper + zinc", "Harder than copper, does not tarnish easily"],
      ["Bronze", "Copper + tin", "Hard and durable — statues, medals"],
      ["Solder", "Lead + tin", "Very low melting point — joining electrical wires"],
      ["Amalgam", "Any metal + mercury", "Mercury alloys are called amalgams"],
    ] },
    { t: "note", kind: "exam", html: "Alloys are <em>always</em> less conductive and have a <em>lower</em> melting point than the pure metal. That is exactly why solder works." },

    { t: "steps", title: "Why does a copper vessel lose its shine, and how do you clean it?",
      intro: "Two marks, and a nice example of chemistry you can see at home.",
      steps: [
        "Moist air contains CO₂ and moisture. Copper reacts slowly with both.",
        "It forms a green coating of basic copper carbonate, CuCO₃·Cu(OH)₂.",
        "This is corrosion — the shiny metal surface is now covered by a compound.",
        "Lemon or tamarind juice contains citric/tartaric acid, which reacts with and dissolves the basic carbonate.",
      ],
      answer: "The green layer is basic copper carbonate. Acidic lemon or tamarind juice dissolves it and restores the shine.",
    },
  ],
  formulas: [
    { name: "Thermite reaction", expr: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat", note: "Displacement; the iron produced is molten. Used for welding rails." },
    { name: "Roasting", expr: "2MS + 3O₂ → 2MO + 2SO₂", note: "Sulphide ore heated strongly in air" },
    { name: "Calcination", expr: "MCO₃ → MO + CO₂", note: "Carbonate ore heated in limited air" },
  ],
  examFocus: [
    "The exceptions table — mercury, bromine, iodine, graphite, diamond.",
    "The reactivity series in the correct order, and using it to predict displacement.",
    "Why ionic compounds conduct only when molten or dissolved.",
    "Roasting vs calcination — the one-word difference (sulphide vs carbonate).",
    "Why highly reactive metals need electrolytic reduction while middle ones use carbon.",
    "The two conditions for rusting, and three prevention methods with reasons.",
    "Composition and one use for each alloy in the table.",
  ],
  flashcards: [
    { q: "Name the only metal that is liquid at room temperature, and the only non-metal.", a: "Mercury is the liquid metal; bromine is the liquid non-metal." },
    { q: "Which non-metal is lustrous and which conducts electricity?", a: "Iodine is lustrous. Graphite conducts electricity because it has free delocalised electrons." },
    { q: "What is an amphoteric oxide? Give two examples.", a: "An oxide that reacts with both acids and bases to give salt and water. Examples: Al₂O₃ and ZnO." },
    { q: "Why do metals not usually give hydrogen with nitric acid?", a: "HNO₃ is a strong oxidising agent — it oxidises the hydrogen produced into water. Exceptions: Mg and Mn with very dilute HNO₃." },
    { q: "Write the reactivity series from potassium to gold.", a: "K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Ag, Au — most reactive at the top." },
    { q: "Why does an ionic compound conduct electricity when molten but not when solid?", a: "In the solid the ions are held rigidly in a lattice and cannot move. When molten or dissolved the ions become free to move and carry the current." },
    { q: "Define mineral, ore and gangue.", a: "A mineral is any naturally occurring compound of a metal. An ore is a mineral from which the metal can be extracted profitably. Gangue is the unwanted earthy impurity in the ore." },
    { q: "What is the difference between roasting and calcination?", a: "Roasting heats a sulphide ore strongly in the presence of air. Calcination heats a carbonate ore in limited air. Both convert the ore into the oxide." },
    { q: "Why can't carbon be used to reduce aluminium oxide?", a: "Aluminium is more reactive than carbon, so carbon cannot take the oxygen away from it. Electrolytic reduction is used instead." },
    { q: "What is the thermite reaction and where is it used?", a: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat. So much heat is released that the iron comes out molten — used for welding broken railway tracks and cracked machine parts." },
    { q: "What two conditions are needed for iron to rust?", a: "Air (oxygen) and moisture. Iron kept in dry air, or in water with no dissolved oxygen, does not rust." },
    { q: "What is galvanisation and why does it still work if scratched?", a: "Coating iron with a layer of zinc. Zinc is more reactive than iron, so it corrodes preferentially and protects the iron even where the coating is broken." },
    { q: "What is an alloy? How do its properties differ from the pure metal?", a: "A homogeneous mixture of a metal with another metal or non-metal. Alloys are harder and more resistant to corrosion, but have lower electrical conductivity and a lower melting point." },
    { q: "Why does aluminium not corrode away despite being reactive?", a: "It forms a thin, hard, non-porous layer of Al₂O₃ on the surface that seals the metal underneath and stops further reaction." },
    { q: "Why is sodium stored in kerosene?", a: "Sodium reacts vigorously with the oxygen and moisture in air, catching fire. Kerosene keeps air away from it." },
  ],
  quiz: [
    { q: "Which of these pairs correctly matches an exception?", options: ["Mercury — liquid metal", "Graphite — non-conducting non-metal", "Diamond — soft non-metal", "Iodine — dull non-metal"], answer: 0, why: "Mercury is the only metal liquid at room temperature. Graphite conducts, diamond is the hardest substance, and iodine is lustrous." },
    { q: "Zinc oxide reacts with both HCl and NaOH. It is therefore:", options: ["A basic oxide", "An acidic oxide", "An amphoteric oxide", "A neutral oxide"], answer: 2, why: "Oxides that react with both acids and bases are amphoteric. Al₂O₃ and ZnO are the two examples in the syllabus." },
    { q: "Iron nails dipped in copper sulphate solution turn brownish and the solution fades. This is because:", options: ["Copper displaces iron", "Iron displaces copper as iron is more reactive", "The nails dissolve in water", "Copper sulphate decomposes"], answer: 1, why: "Iron is above copper in the reactivity series: Fe + CuSO₄ → FeSO₄ + Cu. Copper deposits on the nail and the blue colour fades to pale green." },
    { q: "A sulphide ore is converted to its oxide by:", options: ["Calcination", "Roasting", "Electrolysis", "Reduction with carbon"], answer: 1, why: "Roasting heats a sulphide ore strongly in the presence of air. Calcination is for carbonate ores." },
    { q: "Which metal is extracted by electrolytic reduction?", options: ["Copper", "Zinc", "Aluminium", "Lead"], answer: 2, why: "Aluminium is high in the reactivity series, so carbon cannot reduce its oxide. Molten Al₂O₃ is electrolysed instead." },
    { q: "Ionic compounds have high melting points because:", options: ["They are heavy", "The ions are free to move", "Strong electrostatic forces hold the ions in a lattice", "They contain water"], answer: 2, why: "A large amount of energy is needed to overcome the strong attraction between oppositely charged ions in the lattice." },
    { q: "Which alloy is used for joining electrical wires?", options: ["Brass", "Bronze", "Solder", "Stainless steel"], answer: 2, why: "Solder is lead + tin and has a very low melting point, so it melts easily and sets quickly." },
    { q: "A metal that can be extracted simply by heating its oxide in air is likely to be:", options: ["Very reactive", "Moderately reactive", "Low in the reactivity series", "A non-metal"], answer: 2, why: "Only low-reactivity metals such as mercury and copper have oxides unstable enough to decompose on simple heating." },
    { q: "Silver articles turn black over time. The compound formed is:", options: ["Ag₂O", "Ag₂S", "AgCl", "AgNO₃"], answer: 1, why: "Silver reacts with hydrogen sulphide in the air to form black silver sulphide, Ag₂S." },
    { q: "Which statement about the electron transfer in NaCl is correct?", options: ["Chlorine loses one electron", "Sodium gains one electron", "Sodium loses one electron to chlorine", "Both share one electron"], answer: 2, why: "Sodium (2,8,1) loses its single valence electron to become Na⁺ (2,8). Chlorine (2,8,7) accepts it to become Cl⁻ (2,8,8)." },
    { q: "Food cans are coated with tin rather than zinc because:", options: ["Tin is cheaper", "Tin is less reactive than zinc and does not contaminate the food", "Zinc does not stick to iron", "Tin is more reactive"], answer: 1, why: "Zinc is more reactive and would react with food acids. Tin is less reactive and safe for food contact." },
    { q: "The green coating on old copper vessels is:", options: ["Copper oxide", "Copper sulphide", "Basic copper carbonate", "Copper chloride"], answer: 2, why: "Moist air containing CO₂ slowly forms basic copper carbonate, CuCO₃·Cu(OH)₂ — removable with lemon or tamarind juice." },
  ],
  keyTopics: [
    { name: "The reactivity series and displacement reactions", importance: "high", note: "Used to predict outcomes of metal + salt-solution reactions; a repeated 2–3 mark and assertion–reason topic." },
    { name: "Basic metallurgical processes — roasting, calcination, reduction, electrolytic extraction", importance: "high", note: "Extraction method linked to reactivity is a classic 5-mark long-answer question." },
    { name: "Formation and properties of ionic compounds", importance: "high", note: "Why they conduct only when molten or dissolved is asked almost every year." },
    { name: "Corrosion, galvanisation and alloying", importance: "medium", note: "Why galvanising still protects iron even when scratched is a favourite reasoning question." },
    { name: "Chemical properties of metals — with oxygen, water and acids", importance: "medium", note: "Includes the nitric-acid exception and amphoteric oxides." },
    { name: "Alloys — composition and uses", importance: "medium", note: "Learn the table of alloys (steel, brass, bronze, solder) cold — a reliable short-answer source." },
    { name: "Physical properties and their exceptions", importance: "low", note: "Mercury, bromine, iodine, graphite, diamond, gallium, caesium — worth memorising as a set." },
  ],
  written: [
    { q: "Why is sodium metal kept immersed in kerosene oil?", marks: 1, kind: "short", importance: "medium",
      answer: "Sodium is highly reactive and reacts vigorously with the oxygen and moisture present in air, even catching fire. Kerosene, in which sodium neither dissolves nor reacts, keeps air away and prevents this." },
    { q: "Name two metals that are found in nature in the free (native) state.", marks: 1, kind: "short", importance: "medium",
      answer: "Gold and platinum (silver is sometimes also found free). These are very unreactive metals lying at the very bottom of the reactivity series." },
    { q: "Show, using electronic configurations, how magnesium chloride is formed from magnesium and chlorine atoms. Name the type of bond formed.", marks: 2, kind: "diagram", importance: "high",
      answer: "Mg (2,8,2) loses its two valence electrons to become Mg²⁺ (2,8): <strong>Mg → Mg²⁺ + 2e⁻</strong>. Each of two Cl atoms (2,8,7) gains one electron to become Cl⁻ (2,8,8): <strong>2Cl + 2e⁻ → 2Cl⁻</strong>. The oppositely charged Mg²⁺ and 2Cl⁻ ions attract strongly, forming MgCl₂ — this electrostatic attraction is an <strong>ionic (electrovalent) bond</strong>." },
    { q: "What is meant by 'roasting' and 'calcination'? Give one equation for each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Roasting</strong> is heating a sulphide ore strongly in the presence of excess air to convert it into the metal oxide: <strong>2ZnS + 3O₂ → 2ZnO + 2SO₂</strong>. <strong>Calcination</strong> is heating a carbonate ore in a limited supply of air: <strong>ZnCO₃ → ZnO + CO₂</strong>." },
    { q: "An element X forms an oxide X₂O₃ that is acidic in nature. Is X a metal or a non-metal? Justify with one more property X would show.", marks: 2, kind: "short", importance: "medium",
      answer: "X is a <strong>non-metal</strong>. Non-metal oxides are acidic (they react with bases to give salt and water), while metal oxides are basic. X would also be expected to gain electrons in reactions rather than lose them, and would not displace hydrogen from a dilute acid." },
    { q: "Explain, giving reasons: (i) Platinum, gold and silver are used to make jewellery. (ii) Sodium, potassium and lithium are stored under oil. (iii) Aluminium, though reactive, is used to make cooking utensils.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> These metals lie very low in the reactivity series, so they do not corrode or tarnish in air or moisture, and they can be given a lasting shine — ideal for jewellery.<br><strong>(ii)</strong> These metals are extremely reactive and react vigorously (even catching fire) with the oxygen and moisture in air, so storing them under oil keeps air away and prevents an accident.<br><strong>(iii)</strong> Aluminium reacts instantly with air to form a thin, tough layer of Al₂O₃ that seals the metal underneath and stops further reaction, so despite being reactive it does not corrode further and is safe for cookware." },
    { q: "A metal M liberates hydrogen gas when reacted with dilute sulphuric acid. When a metal N is added to a solution of the sulphate of M, metal M gets displaced. Arrange M, N and hydrogen in order of increasing reactivity, giving reasons.", marks: 3, kind: "short", importance: "medium",
      answer: "Since M liberates hydrogen from a dilute acid, M is <strong>more reactive than hydrogen</strong>. Since N displaces M from its salt solution, N is <strong>more reactive than M</strong>. So the increasing order of reactivity is: <strong>hydrogen &lt; M &lt; N</strong>." },
    { q: "Why does copper not react with dilute hydrochloric acid, whereas zinc reacts vigorously with it? What would you observe if a copper vessel is exposed to moist air for a long time?", marks: 3, kind: "short", importance: "medium",
      answer: "Copper lies <strong>below hydrogen</strong> in the reactivity series, so it cannot displace hydrogen from a dilute acid — no reaction occurs. Zinc lies <strong>above hydrogen</strong>, so it readily displaces hydrogen gas: <strong>Zn + H₂SO₄ → ZnSO₄ + H₂↑</strong>.<br>A copper vessel exposed to moist air for a long time slowly reacts with the CO₂ and moisture present, forming a green coating of <strong>basic copper carbonate, CuCO₃·Cu(OH)₂</strong>, which dulls its original shine." },
    { q: "With the help of the reactivity series, explain how the method used to extract a metal from its ore depends on its position in the series. Give one example each for metals of low, medium and high reactivity.", marks: 5, kind: "long", importance: "high",
      answer: "Extraction method depends entirely on reactivity.<br><strong>Low reactivity metals</strong> (Au, Ag, Cu) are often found free in nature, or need only simple heating or physical separation to obtain the pure metal — e.g. gold is separated from sand by physical methods.<br><strong>Medium reactivity metals</strong> (Zn, Fe, Pb) occur as sulphides or carbonates. The ore is first converted to the oxide by roasting (sulphide) or calcination (carbonate), and the oxide is then reduced with carbon, e.g. <strong>ZnO + C → Zn + CO</strong>.<br><strong>High reactivity metals</strong> (Na, Ca, Al) occur as stable oxides or chlorides that carbon cannot reduce, since these metals are more reactive than carbon itself. They must be extracted by <strong>electrolytic reduction</strong> of the molten compound, e.g. electrolysis of molten Al₂O₃ (dissolved in cryolite) gives aluminium at the cathode." },
    { q: "Describe an activity to demonstrate the formation of an ionic compound between a metal and a non-metal, and explain the general properties shown by ionic compounds, giving reasons in terms of their structure.", marks: 5, kind: "long", importance: "high",
      answer: "Burn a small piece of sodium in a deflagrating spoon in a gas jar of dry chlorine gas. A white solid, sodium chloride, is formed: <strong>2Na + Cl₂ → 2NaCl</strong>. Sodium (2,8,1) loses one electron to become Na⁺ (2,8); chlorine (2,8,7) gains it to become Cl⁻ (2,8,8), and the oppositely charged ions attract to form the ionic compound.<br><strong>Properties, with reasons:</strong> ionic compounds are hard, crystalline solids because the ions are held in a rigid lattice by strong electrostatic forces. They have high melting and boiling points, since a lot of energy is needed to break this lattice. They generally dissolve in water (which can separate the ions) but not in organic solvents such as kerosene. They do not conduct electricity as solids, because the ions cannot move, but they do conduct when molten or dissolved in water, since the ions are then free to move and carry charge." },
  ],
  assertionReason: [
    { assertion: "A piece of zinc metal develops a reddish-brown coating when kept dipped in copper sulphate solution.",
      reason: "Zinc is more reactive than copper and displaces it from copper sulphate solution.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion — zinc, being more reactive, displaces copper, which deposits as a reddish-brown coating: Zn + CuSO₄ → ZnSO₄ + Cu." },
    { assertion: "Ionic compounds generally have high melting and boiling points.",
      reason: "A considerable amount of energy is required to break the strong electrostatic forces of attraction between the oppositely charged ions in the crystal lattice.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion." },
    { assertion: "Sodium chloride does not conduct electricity in the solid state.",
      reason: "There are no ions present in solid sodium chloride.",
      answer: 2, importance: "medium",
      why: "The assertion is true. But the reason is false: solid NaCl does contain Na⁺ and Cl⁻ ions, held rigidly in a lattice — they simply cannot move, which is the actual reason it fails to conduct as a solid." },
    { assertion: "Aluminium, though a reactive metal, is used for making cooking utensils and aircraft bodies.",
      reason: "Aluminium is light in weight and a poor conductor of heat.",
      answer: 2, importance: "medium",
      why: "The assertion is true. But the reason is only half correct: aluminium is indeed light, but it is actually a <em>good</em> conductor of heat — which is exactly why it suits cooking utensils. The false claim makes the reason as a whole incorrect." },
  ],
  caseStudies: [
    { title: "Matching metals to their extraction method", importance: "high",
      source: "The table below shows three metals, their ores and how each is obtained:<br><table><thead><tr><th>Metal</th><th>Ore</th><th>Extraction method</th></tr></thead><tbody><tr><td>Gold</td><td>Native gold</td><td>Physical separation</td></tr><tr><td>Zinc</td><td>Zinc blende (ZnS)</td><td>Roasting, then reduction with carbon</td></tr><tr><td>Aluminium</td><td>Bauxite (Al₂O₃·2H₂O)</td><td>Electrolytic reduction of molten Al₂O₃</td></tr></tbody></table>",
      parts: [
        { q: "Why is gold found in the free state in nature, unlike zinc and aluminium?", marks: 1, answer: "Gold lies at the very bottom of the reactivity series and is so unreactive that it does not combine with the oxygen or moisture in the environment, so it stays in its pure metallic form." },
        { q: "Zinc blende is roasted before reduction. What does roasting mean, and why is it necessary?", marks: 2, answer: "Roasting means heating a sulphide ore strongly in the presence of excess air. It converts zinc sulphide into zinc oxide (<strong>2ZnS + 3O₂ → 2ZnO + 2SO₂</strong>), because oxides are far easier to reduce to the metal than sulphides are." },
        { q: "Why can't aluminium be extracted using carbon as a reducing agent, unlike zinc?", marks: 1, answer: "Aluminium is more reactive than carbon, so carbon cannot remove the oxygen from Al₂O₃. Only electrolytic reduction, using a large amount of electrical energy, can free the metal." },
        { q: "Name the process by which gangue (earthy impurities) is removed from an ore before extraction begins.", marks: 1, answer: "Concentration of the ore (also called dressing or enrichment of the ore)." },
      ] },
    { title: "Why galvanising still protects a scratched nail", importance: "medium",
      source: "Two identical iron nails were taken. Nail A was coated with a thin layer of zinc (galvanised). Nail B was left uncoated. Both nails were then scratched slightly to expose bare iron underneath, and kept in a humid environment for several days. Nail B rusted extensively, while nail A showed almost no rusting, even at the scratch.",
      parts: [
        { q: "What is the process of coating iron with a layer of zinc called?", marks: 1, answer: "Galvanisation." },
        { q: "Explain why nail A did not rust significantly, even at the scratch where the iron was exposed.", marks: 2, answer: "Zinc is more reactive than iron, so even where the coating is scratched and iron is exposed, the surrounding zinc corrodes preferentially and protects the iron underneath — this is called sacrificial protection." },
        { q: "Name one other method of preventing the rusting of iron besides galvanisation.", marks: 1, answer: "Painting or applying oil/grease on the surface to keep out air and moisture (or alloying it, e.g. into stainless steel)." },
        { q: "Give the composition of stainless steel and state why it is preferred over plain iron for cutlery.", marks: 1, answer: "Stainless steel is an alloy of iron with chromium and nickel. It does not rust at all, so it is preferred for cutlery and utensils." },
      ] },
  ],
};
