import type { Chapter } from "@/lib/types";

export const ch04: Chapter = {
  slug: "carbon-and-its-compounds",
  num: 4,
  title: "Carbon and its Compounds",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · 25 marks",
  minutes: 24,
  blurb: "One element, ten million compounds. Why carbon is special, how to name what it builds, and the two compounds you must know in detail.",
  bigIdea: "Carbon has four electrons to share and can bond to itself endlessly. Those two facts alone explain why almost everything alive — and most of what you use daily — is built from carbon.",
  syllabus: [
    "Covalent bonding in carbon compounds", "Versatile nature of carbon",
    "Homologous series", "Saturated and unsaturated hydrocarbons",
    "Nomenclature — alkanes, alkenes, alkynes, functional groups",
    "Combustion, oxidation, addition and substitution reactions",
    "Ethanol and ethanoic acid — properties and uses only", "Soaps and detergents",
  ],
  blocks: [
    { t: "h", text: "Why carbon shares instead of transferring" },
    { t: "p", html: "Carbon has 4 valence electrons. To become stable it would need to either lose 4 (leaving a C⁴⁺ ion — needs far too much energy) or gain 4 (a C⁴⁻ ion — no nucleus with only 6 protons can hold 10 electrons). So it does neither. It <strong>shares</strong>, forming four covalent bonds." },
    { t: "note", kind: "idea", html: "A covalent bond is a shared pair of electrons. Because nothing is fully charged, covalent compounds have <strong>low melting and boiling points</strong> and <strong>do not conduct electricity</strong> — the exact opposite of the ionic compounds in the last chapter." },
    { t: "table", head: ["Molecule", "Bond", "Electron dot idea"], rows: [
      ["H₂", "Single", "H : H — one shared pair"],
      ["O₂", "Double", "O :: O — two shared pairs"],
      ["N₂", "Triple", "N ⋮⋮ N — three shared pairs"],
      ["CH₄", "Four single bonds", "C shares one electron with each of four H atoms"],
    ] },

    { t: "h", text: "Two properties that make carbon unique" },
    { t: "list", items: [
      "<strong>Catenation</strong> — carbon atoms bond to other carbon atoms to form long chains, branched chains and rings. No other element does this to anywhere near the same extent, because the C–C bond is unusually strong and stable.",
      "<strong>Tetravalency</strong> — with four bonds to give, carbon can attach to four other atoms at once, giving an enormous number of possible arrangements.",
    ] },
    { t: "note", kind: "real", html: "Diamond and graphite are both pure carbon, yet one is the hardest natural substance and the other is soft enough to write with. In diamond each carbon bonds to four others in a rigid 3-D network. In graphite each bonds to only three, forming sheets that slide over one another — and the spare electron makes graphite conduct." },

    { t: "h", text: "Saturated and unsaturated" },
    { t: "compare",
      left: { title: "Saturated — alkanes", items: [
        "Only single bonds between carbons",
        "General formula C<sub>n</sub>H<sub>2n+2</sub>",
        "Burn with a clean <strong>blue</strong> flame",
        "React by <strong>substitution</strong> (in sunlight)",
        "Do not decolourise bromine water",
      ] },
      right: { title: "Unsaturated — alkenes and alkynes", items: [
        "At least one double or triple bond",
        "C<sub>n</sub>H<sub>2n</sub> (alkene) or C<sub>n</sub>H<sub>2n−2</sub> (alkyne)",
        "Burn with a <strong>yellow sooty</strong> flame",
        "React by <strong>addition</strong>",
        "Decolourise bromine water — the standard test",
      ] } },
    { t: "note", kind: "exam", html: "&ldquo;How would you distinguish between ethane and ethene?&rdquo; — add bromine water. The orange colour disappears with ethene (unsaturated) and stays with ethane. Learn this as one sentence." },

    { t: "h", text: "Homologous series and naming" },
    { t: "p", html: "A homologous series is a family of compounds with the same functional group, where each member differs from the next by one <strong>–CH₂–</strong> unit (a mass difference of 14 u). Because the functional group is the same, the chemistry is the same — only the physical properties change gradually as the chain lengthens." },
    { t: "sim", id: "homologous-builder" },
    { t: "p", html: "Naming is mechanical once you know the parts:" },
    { t: "list", ordered: true, items: [
      "Count the carbons in the longest chain: 1 meth, 2 eth, 3 prop, 4 but, 5 pent, 6 hex.",
      "Add the ending for the bond type: <strong>-ane</strong> (single), <strong>-ene</strong> (double), <strong>-yne</strong> (triple).",
      "If there is a functional group, replace the final 'e' with its suffix, or add a prefix. Ethane + –OH becomes ethan<strong>ol</strong>.",
    ] },
    { t: "table", head: ["Functional group", "Formula", "Suffix / prefix", "Example"], rows: [
      ["Halo (chloro, bromo)", "–Cl, –Br", "prefix chloro-, bromo-", "Chloroethane"],
      ["Alcohol", "–OH", "-ol", "Ethanol, C₂H₅OH"],
      ["Aldehyde", "–CHO", "-al", "Ethanal, CH₃CHO"],
      ["Ketone", "&gt;C=O", "-one", "Propanone, CH₃COCH₃"],
      ["Carboxylic acid", "–COOH", "-oic acid", "Ethanoic acid, CH₃COOH"],
    ] },
    { t: "note", kind: "trap", html: "Ketones need at least <strong>three</strong> carbons — the C=O must sit in the middle of the chain, not at the end. Propanone is the smallest ketone." },

    { t: "h", text: "The three reaction types" },
    { t: "list", ordered: true, items: [
      "<strong>Combustion</strong> — burning in oxygen to give CO₂, water and a lot of heat. This is why carbon compounds are our fuels. <span class='chem'>CH₄ + 2O₂ → CO₂ + 2H₂O + heat</span>",
      "<strong>Oxidation</strong> — alcohols become carboxylic acids with alkaline KMnO₄ or acidified K₂Cr₂O₇. These are called <em>oxidising agents</em>: they add oxygen to other substances.",
      "<strong>Addition</strong> — unsaturated compounds add hydrogen across the double bond in the presence of nickel or palladium. This is <strong>hydrogenation</strong>, and it turns liquid vegetable oils into solid vanaspati ghee.",
      "<strong>Substitution</strong> — saturated compounds have no spare bonds, so one atom must be swapped out. <span class='chem'>CH₄ + Cl₂ →(sunlight) CH₃Cl + HCl</span>",
    ] },
    { t: "note", kind: "real", html: "Vegetable oils contain unsaturated fats; animal fats are saturated. Hydrogenation makes oil solid and shelf-stable, but it also converts a healthier unsaturated fat into a less healthy saturated one — which is why doctors prefer cooking with oil over vanaspati." },
    { t: "note", kind: "why", title: "Why does a gas stove flame go yellow?", html: "A blue flame means complete combustion — enough oxygen. A yellow, sooty flame means incomplete combustion, usually because the air holes are blocked. Incomplete combustion wastes fuel and produces carbon monoxide, which is poisonous." },

    { t: "h", text: "Ethanol — C₂H₅OH" },
    { t: "list", items: [
      "A colourless liquid at room temperature, with a low melting and boiling point.",
      "<strong>With sodium:</strong> 2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂. Hydrogen gas is evolved — this is the test for an alcohol.",
      "<strong>Dehydration:</strong> heated with excess concentrated H₂SO₄ at 443 K, it loses water to give ethene. The acid acts as a dehydrating agent.",
      "<strong>Uses:</strong> in medicines such as tincture of iodine and cough syrups, as a solvent, and as a cleaner fuel when blended with petrol.",
      "<strong>Effect on the body:</strong> ethanol slows down the nervous system. Methanol, in contrast, is oxidised in the liver to methanal, which is lethal in very small quantities — this is why industrial spirit is deliberately poisoned (denatured) with methanol and dye to make it undrinkable.",
    ] },

    { t: "h", text: "Ethanoic acid — CH₃COOH" },
    { t: "list", items: [
      "5–8% ethanoic acid in water is <strong>vinegar</strong>. Pure ethanoic acid freezes at 290 K, just below room temperature in cold climates, which is why it is called <strong>glacial</strong> acetic acid.",
      "<strong>With a base:</strong> CH₃COOH + NaOH → CH₃COONa + H₂O — plain neutralisation.",
      "<strong>With a carbonate:</strong> gives CO₂ (which turns lime water milky). This distinguishes it from alcohols, which give no reaction with carbonates.",
      "<strong>Esterification:</strong> acid + alcohol, with a little concentrated H₂SO₄, gives an <strong>ester</strong> — a sweet-smelling liquid used in perfumes and flavourings. Warming an ester with NaOH gives back the alcohol and the soap of the acid: this reverse reaction is <strong>saponification</strong>, the reaction used to make soap.",
    ] },
    { t: "note", kind: "exam", html: "To distinguish ethanol from ethanoic acid: add sodium hydrogencarbonate. The acid gives brisk effervescence of CO₂; the alcohol does nothing. Alternatively, use litmus — the acid turns blue litmus red." },

    { t: "h", text: "Soap and detergent — the cleverest molecule in the chapter" },
    { t: "p", html: "A soap molecule has two ends that want completely different things. The long hydrocarbon tail is <strong>hydrophobic</strong> — it hates water but loves oil and grease. The ionic head (–COO⁻Na⁺) is <strong>hydrophilic</strong> — it loves water." },
    { t: "list", ordered: true, items: [
      "Tails bury themselves in the greasy dirt; heads stay pointing outwards into the water.",
      "The result is a ball called a <strong>micelle</strong>, with dirt trapped inside.",
      "Because the outside of every micelle is charged and water-loving, the whole cluster lifts off the cloth and washes away.",
    ] },
    { t: "note", kind: "why", title: "Why does soap not work in hard water?", html: "Hard water contains calcium and magnesium ions. These react with soap to form an insoluble sticky solid — the <strong>scum</strong> you see in the basin. Detergents use sulphonate or ammonium salts instead, which do not form insoluble salts with Ca²⁺ and Mg²⁺, so detergents lather even in hard water." },
    { t: "note", kind: "real", html: "The catch: many detergents have branched hydrocarbon chains that bacteria cannot break down, so they build up in rivers and cause foaming and pollution. Soaps are biodegradable; that is their one big advantage." },

    { t: "steps", title: "Why does soap clean but plain water does not?",
      intro: "A five-mark favourite. Structure your answer around the molecule.",
      steps: [
        "Dirt on clothes is usually oily, and oil does not dissolve in water — so water alone slides straight past it.",
        "A soap molecule has a long hydrocarbon tail (hydrophobic) and an ionic head (hydrophilic).",
        "The tails dissolve into the oily dirt while the heads stay in the water, so soap can grip both at once.",
        "Many molecules cluster into a micelle, with the dirt trapped in the oily centre and charged heads on the outside.",
        "Micelles repel each other (all the same charge), so they stay suspended and rinse away with the water, carrying the dirt with them.",
      ],
      answer: "Soap works because one end of the molecule dissolves in grease and the other in water, letting dirt be lifted into micelles and washed away.",
    },
  ],
  formulas: [
    { name: "Alkane", expr: "C<sub>n</sub>H<sub>2n+2</sub>", note: "Saturated. Methane CH₄, ethane C₂H₆, propane C₃H₈" },
    { name: "Alkene", expr: "C<sub>n</sub>H<sub>2n</sub>", note: "One double bond. Ethene C₂H₄ (n starts at 2)" },
    { name: "Alkyne", expr: "C<sub>n</sub>H<sub>2n−2</sub>", note: "One triple bond. Ethyne C₂H₂" },
    { name: "Esterification", expr: "CH₃COOH + C₂H₅OH →(conc. H₂SO₄) CH₃COOC₂H₅ + H₂O", note: "Gives a sweet-smelling ester" },
    { name: "Saponification", expr: "Ester + NaOH → Alcohol + Sodium salt of the acid (soap)", note: "The reverse of esterification" },
  ],
  examFocus: [
    "Why carbon forms covalent bonds rather than ions — the energy argument.",
    "Catenation and tetravalency, defined in one line each.",
    "Bromine water test and the flame colour test for unsaturation.",
    "Naming a compound from a structure, and drawing a structure from a name.",
    "Addition vs substitution — which type of compound does which, and why.",
    "Ethanol and ethanoic acid: reaction with sodium, with carbonate, and esterification.",
    "The micelle diagram with hydrophilic head and hydrophobic tail labelled — draw it, do not just describe it.",
    "Soap vs detergent in hard water, with the reason.",
  ],
  flashcards: [
    { q: "Why does carbon form covalent bonds instead of ionic bonds?", a: "Losing 4 electrons would need far too much energy, and gaining 4 would mean a nucleus with only 6 protons holding 10 electrons — unstable. So carbon shares electrons instead." },
    { q: "What is catenation?", a: "The ability of an element to bond with atoms of itself to form long chains, branched chains and rings. Carbon does this better than any other element because C–C bonds are very strong." },
    { q: "Why is diamond hard but graphite soft?", a: "In diamond each carbon is bonded to four others in a rigid 3-D network. In graphite each carbon bonds to three, forming layers that slide over one another." },
    { q: "How would you test whether a hydrocarbon is unsaturated?", a: "Add bromine water. An unsaturated compound decolourises the orange-brown colour by an addition reaction; a saturated compound does not." },
    { q: "What is a homologous series?", a: "A family of compounds with the same functional group in which each member differs from the next by one –CH₂– unit (14 u). They have similar chemical properties and gradually changing physical properties." },
    { q: "Why do unsaturated hydrocarbons burn with a sooty flame?", a: "They have a higher percentage of carbon, so combustion is incomplete and unburnt carbon particles glow yellow and deposit as soot." },
    { q: "What is hydrogenation and where is it used?", a: "Adding hydrogen across a double bond using a nickel or palladium catalyst. It converts unsaturated vegetable oils into saturated solid fats — this is how vanaspati ghee is made." },
    { q: "Give the reaction of ethanol with sodium.", a: "2C₂H₅OH + 2Na → 2C₂H₅ONa (sodium ethoxide) + H₂. Evolution of hydrogen gas is the test for an alcohol." },
    { q: "Why is pure ethanoic acid called glacial acetic acid?", a: "It freezes at 290 K (17 °C), just below room temperature in cold places, forming ice-like crystals." },
    { q: "How do you distinguish ethanol from ethanoic acid?", a: "Add sodium hydrogencarbonate. Ethanoic acid gives brisk effervescence of CO₂ which turns lime water milky; ethanol gives no reaction. Ethanoic acid also turns blue litmus red." },
    { q: "What is esterification?", a: "A carboxylic acid reacting with an alcohol in the presence of a little concentrated H₂SO₄ to form a sweet-smelling ester and water. Esters are used in perfumes and flavourings." },
    { q: "What is saponification?", a: "The reaction of an ester with a base such as NaOH to give back the alcohol and the sodium salt of the acid. This is the reaction used to make soap." },
    { q: "Draw and describe a micelle.", a: "A spherical cluster of soap molecules with the hydrophobic hydrocarbon tails pointing inwards into the oily dirt and the hydrophilic ionic heads pointing outwards into the water." },
    { q: "Why does soap not lather in hard water?", a: "Hard water contains Ca²⁺ and Mg²⁺ ions which react with soap to form an insoluble scum, so no lather forms until all these ions are used up." },
    { q: "Why is a detergent better than soap in hard water?", a: "Detergents are ammonium or sulphonate salts whose calcium and magnesium salts are soluble, so they do not form scum and lather even in hard water." },
    { q: "What is denatured alcohol and why is it made?", a: "Ethanol made unfit for drinking by adding poisonous substances such as methanol and dye. It is done so that industrial alcohol can be sold cheaply without misuse." },
  ],
  quiz: [
    { q: "The number of covalent bonds a carbon atom forms is:", options: ["2", "3", "4", "6"], answer: 2, why: "Carbon has 4 valence electrons and shares each one, forming four covalent bonds — this is tetravalency." },
    { q: "Which of these will decolourise bromine water?", options: ["CH₄", "C₂H₆", "C₂H₄", "C₃H₈"], answer: 2, why: "C₂H₄ (ethene) is unsaturated and undergoes an addition reaction with bromine, removing the colour. The others are saturated alkanes." },
    { q: "The general formula of an alkyne is:", options: ["CnH2n+2", "CnH2n", "CnH2n−2", "CnH2n+1OH"], answer: 2, why: "An alkyne has one triple bond, so it has four fewer hydrogens than the corresponding alkane: CnH2n−2." },
    { q: "Consecutive members of a homologous series differ by a mass of:", options: ["12 u", "14 u", "16 u", "2 u"], answer: 1, why: "They differ by one –CH₂– unit: carbon (12) + two hydrogens (2) = 14 u." },
    { q: "Vanaspati ghee is made from vegetable oil by:", options: ["Oxidation", "Substitution", "Hydrogenation", "Esterification"], answer: 2, why: "Hydrogen is added across the double bonds using a nickel catalyst, converting unsaturated liquid oil into saturated solid fat." },
    { q: "Ethanol reacts with sodium to give:", options: ["Sodium ethanoate and water", "Sodium ethoxide and hydrogen", "Ethene and water", "An ester"], answer: 1, why: "2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂. The evolution of hydrogen is the standard test for an alcohol." },
    { q: "Which reaction is characteristic of saturated hydrocarbons?", options: ["Addition", "Substitution", "Polymerisation", "Neutralisation"], answer: 1, why: "Saturated compounds have no spare bonds, so an atom must be replaced rather than added. Chlorination of methane in sunlight is the classic example." },
    { q: "The functional group present in ethanoic acid is:", options: ["–OH", "–CHO", "–COOH", ">C=O"], answer: 2, why: "Ethanoic acid is CH₃COOH — the carboxylic acid group –COOH." },
    { q: "The hydrophobic end of a soap molecule is:", options: ["The ionic –COO⁻Na⁺ head", "The long hydrocarbon tail", "The whole molecule", "The water layer around it"], answer: 1, why: "The long hydrocarbon chain is water-repelling but dissolves in oil and grease. The ionic head is the water-loving part." },
    { q: "A sweet-smelling compound formed by warming ethanoic acid with ethanol is:", options: ["A soap", "An ester", "An aldehyde", "A ketone"], answer: 1, why: "Acid + alcohol with concentrated H₂SO₄ gives an ester — ethyl ethanoate here. Esters are used in perfumes and flavourings." },
    { q: "Which is the smallest ketone possible?", options: ["Ethanone", "Propanone", "Butanone", "Methanone"], answer: 1, why: "The C=O group in a ketone must sit between two carbons, so at least three carbons are needed. Propanone (CH₃COCH₃) is the smallest." },
    { q: "Detergents cause water pollution mainly because:", options: ["They are acidic", "Their branched chains are not biodegradable", "They contain calcium", "They evaporate quickly"], answer: 1, why: "Many detergents have branched hydrocarbon chains that bacteria cannot break down, so they persist in water bodies and cause foaming." },
  ],
  keyTopics: [
    { name: "Nomenclature — naming compounds from structure and functional group", importance: "high", note: "A guaranteed 2-mark skill: name a structure, or draw a structure from a name." },
    { name: "Chemical properties — combustion, oxidation, addition, substitution", importance: "high", note: "Distinguishing addition from substitution, and the bromine-water test for unsaturation, appear almost every year." },
    { name: "Ethanol and ethanoic acid — reactions and uses", importance: "high", note: "Reaction with sodium, with a carbonate, and esterification/saponification are the syllabus's named reactions and are tested in detail." },
    { name: "Soaps and detergents — micelle formation and cleaning action", importance: "high", note: "The 5-mark 'how does soap clean' diagram-based question is one of the most repeated long answers in the whole paper." },
    { name: "Catenation and tetravalency", importance: "medium", note: "Defined in one line each, and used to explain why carbon forms so many compounds — a common 2–3 mark question." },
    { name: "Homologous series, saturated and unsaturated hydrocarbons", importance: "medium", note: "General formulae C<sub>n</sub>H<sub>2n+2</sub>, C<sub>n</sub>H<sub>2n</sub>, C<sub>n</sub>H<sub>2n−2</sub> and the flame-colour/bromine-water tests." },
    { name: "Covalent bonding and electron dot structures", importance: "medium", note: "Draw the electron dot structure for simple molecules such as methane, ethane or ethene." },
  ],
  written: [
    { q: "Why do covalent compounds generally have low melting and boiling points?", marks: 1, kind: "short", importance: "medium",
      answer: "Covalent compounds are made up of neutral molecules held together by weak intermolecular forces of attraction, unlike ionic compounds, so relatively little energy is needed to separate the molecules and melt or boil them." },
    { q: "Name the functional group present in (i) CH₃CH₂OH and (ii) CH₃COOH.", marks: 1, kind: "short", importance: "high",
      answer: "(i) Alcohol (–OH group). (ii) Carboxylic acid (–COOH group)." },
    { q: "Draw the electron dot structure of ethane, C₂H₆.", marks: 2, kind: "diagram", importance: "high",
      answer: "Each carbon atom has 4 valence electrons. In ethane, the two carbon atoms share one pair of electrons to form a single C–C bond, and each carbon shares one electron with each of three hydrogen atoms to form six C–H bonds. Every atom then has a stable outer shell — each carbon effectively has 8 electrons around it, and each hydrogen has 2." },
    { q: "How would you distinguish experimentally between ethanol and ethanoic acid using sodium hydrogencarbonate?", marks: 2, kind: "short", importance: "high",
      answer: "Add a pinch of sodium hydrogencarbonate (NaHCO₃) to each in separate test tubes. Ethanoic acid reacts with brisk effervescence of carbon dioxide gas (which turns lime water milky): <strong>CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂↑</strong>. Ethanol shows no such reaction, since it is not acidic." },
    { q: "Write the chemical equation for the esterification reaction between ethanoic acid and ethanol, and state one use of esters.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>CH₃COOH + C₂H₅OH →(conc. H₂SO₄) CH₃COOC₂H₅ + H₂O</strong>. Esters are sweet-smelling compounds used in making perfumes and as flavouring agents in food." },
    { q: "What are catenation and tetravalency? Explain how these two properties together are responsible for the huge number of known carbon compounds.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Catenation</strong> is the ability of carbon atoms to bond with one another to form long chains, branched chains and rings, because the C–C bond is very strong and stable. <strong>Tetravalency</strong> is carbon's ability to form four covalent bonds, since it has four valence electrons to share.<br>Catenation lets carbon atoms link up in an almost unlimited variety of chain lengths and shapes, while tetravalency means each carbon atom still has bonds free to attach different other atoms or groups (H, O, N, halogens, and so on) along the chain. This combination of near-infinite skeletons and varying attached groups is why carbon forms millions of compounds." },
    { q: "How would you differentiate experimentally between a saturated and an unsaturated hydrocarbon? Give the test and the observation.", marks: 3, kind: "diagram", importance: "high",
      answer: "Add a few drops of bromine water to samples of each hydrocarbon and shake. An <strong>unsaturated</strong> hydrocarbon (with a C=C or C≡C bond) decolourises the orange-brown bromine water instantly, since bromine adds across the double or triple bond. A <strong>saturated</strong> hydrocarbon shows no such colour change, since it has no multiple bond to add across.<br>Alternatively, burn a small sample of each: saturated hydrocarbons burn with a clean blue flame, while unsaturated hydrocarbons burn with a yellow, sooty flame owing to their higher carbon content." },
    { q: "Explain why soap does not lather well in hard water, and how a detergent solves this problem.", marks: 3, kind: "short", importance: "high",
      answer: "Hard water contains dissolved calcium and magnesium ions. These react with soap (a sodium or potassium salt of a fatty acid) to form an insoluble, sticky precipitate called scum, so soap does not lather until all the Ca²⁺ and Mg²⁺ ions are used up forming this scum.<br>Detergents are ammonium or sulphonate salts of long-chain acids. Their calcium and magnesium salts remain soluble in water, so no insoluble scum forms, and detergents lather effectively even in hard water." },
    { q: "Explain, with reference to its molecular structure, how soap removes an oily or greasy stain from a dirty cloth when dissolved in water.", marks: 5, kind: "diagram", importance: "high",
      answer: "A soap molecule has two very different ends: a long hydrocarbon tail that is <strong>hydrophobic</strong> (repels water, dissolves in oil and grease) and an ionic head, –COO⁻Na⁺, that is <strong>hydrophilic</strong> (dissolves in water).<br>When soap is added to water containing an oily or greasy stain, the hydrocarbon tails of many soap molecules bury themselves into the oily dirt, while the ionic heads stay pointing outward into the surrounding water. This forms a spherical cluster called a <strong>micelle</strong>, with the greasy dirt trapped in the oil-loving centre and the charged heads facing outward.<br>Because the outer surface of every micelle carries the same charge, micelles repel each other and remain suspended in water rather than clumping back together. Gentle agitation, such as scrubbing or the spin of a washing machine, then lifts these micelles — carrying the trapped dirt — off the cloth and washes them away with the rinse water." },
    { q: "Give the names, molecular formulae and general formula of the first four members of the homologous series of alkanes. Explain what is meant by a homologous series, with reference to this example.", marks: 5, kind: "long", importance: "medium",
      answer: "The first four alkanes are methane CH₄, ethane C₂H₆, propane C₃H₈ and butane C₄H₁₀ — all fitting the general formula <strong>C<sub>n</sub>H<sub>2n+2</sub></strong>.<br>A homologous series is a family of compounds with the same functional group, in which each successive member differs from the one before it by one <strong>–CH₂–</strong> unit, that is, by a mass of 14 u. Because they share the same functional group (here, none — just single C–C and C–H bonds), all members show similar chemical properties, such as combustion and substitution reactions, while physical properties like melting point and boiling point change gradually as the chain gets longer." },
  ],
  assertionReason: [
    { assertion: "Carbon forms covalent compounds by sharing electrons rather than forming ions.",
      reason: "Carbon has 4 electrons in its valence shell, and gaining or losing all four would require far too much energy to form a stable ion easily.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion — neither losing nor gaining 4 electrons is energetically easy for carbon, so it shares electrons instead." },
    { assertion: "Ethyne (C₂H₂) decolourises bromine water rapidly.",
      reason: "Ethyne is a saturated hydrocarbon and reacts with bromine by a substitution reaction.",
      answer: 2, importance: "high",
      why: "The assertion is true — ethyne, with a triple bond, is highly unsaturated and reacts fast with bromine water. But the reason is false on both counts: ethyne is <em>unsaturated</em>, not saturated, and it reacts by <em>addition</em> across the triple bond, not substitution." },
    { assertion: "A soap solution fails to lather when mixed with hard water, forming a white scum instead.",
      reason: "Hard water contains dissolved calcium and magnesium salts, which react with soap to form an insoluble precipitate.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion." },
    { assertion: "Diamond is used as an abrasive for cutting and polishing hard materials.",
      reason: "In diamond, every carbon atom is bonded to only three other carbon atoms, forming flat sheets that slide over one another.",
      answer: 2, importance: "medium",
      why: "The assertion is true — diamond's extreme hardness makes it ideal as an abrasive. But the reason describes <em>graphite's</em> structure, not diamond's: in diamond, each carbon is bonded to four others in a rigid three-dimensional network, which is exactly why it is so hard." },
  ],
  caseStudies: [
    { title: "Spotting the pattern in a homologous series", importance: "medium",
      source: "A chemistry teacher wrote four hydrocarbons on the board and asked students to study the pattern in their formulae and boiling points:<br><table><thead><tr><th>Compound</th><th>Formula</th><th>Boiling point (°C)</th></tr></thead><tbody><tr><td>Methane</td><td>CH₄</td><td>−162</td></tr><tr><td>Ethane</td><td>C₂H₆</td><td>−89</td></tr><tr><td>Propane</td><td>C₃H₈</td><td>−42</td></tr><tr><td>Butane</td><td>C₄H₁₀</td><td>−0.5</td></tr></tbody></table>",
      parts: [
        { q: "What functional group do these four compounds share, and what family do they belong to?", marks: 1, answer: "None of them has any functional group — they contain only single C–C and C–H bonds, so they belong to the family of <strong>alkanes</strong> (saturated hydrocarbons)." },
        { q: "By how much does the molecular mass increase from one compound to the next, and what unit does this represent?", marks: 1, answer: "By 14 u each time, representing one <strong>–CH₂–</strong> unit — the defining feature of successive members of a homologous series." },
        { q: "What trend do you notice in the boiling points as the chain length increases, and why does this happen?", marks: 2, answer: "The boiling point steadily <strong>increases</strong> as the carbon chain gets longer. Longer chains have a greater surface area of contact and stronger intermolecular forces of attraction between molecules, so more energy (a higher temperature) is needed to separate them into the gas phase." },
        { q: "Write the general formula for this homologous series.", marks: 1, answer: "<strong>C<sub>n</sub>H<sub>2n+2</sub></strong>." },
      ] },
    { title: "Soaps versus detergents in hard water", importance: "high",
      source: "Equal amounts of soap solution and detergent solution were added, drop by drop, to two separate samples of hard water containing dissolved calcium and magnesium salts, and shaken. The number of drops needed to produce a stable lather was noted:<br><table><thead><tr><th>Sample</th><th>Drops needed for lather</th><th>Scum observed?</th></tr></thead><tbody><tr><td>Soap in hard water</td><td>18</td><td>Yes</td></tr><tr><td>Detergent in hard water</td><td>4</td><td>No</td></tr></tbody></table>",
      parts: [
        { q: "Why did the soap solution need many more drops to lather compared to the detergent?", marks: 2, answer: "The Ca²⁺ and Mg²⁺ ions in hard water react with soap to form an insoluble scum, using up the soap without producing lather. This continues until all the calcium and magnesium ions are used up, requiring many drops before any soap is left free to lather." },
        { q: "Why did the detergent not form scum in hard water?", marks: 1, answer: "Detergents are ammonium or sulphonate salts whose calcium and magnesium salts are soluble in water, so no insoluble precipitate (scum) forms." },
        { q: "Apart from their behaviour in hard water, what is the main chemical difference between a soap molecule and a detergent molecule?", marks: 1, answer: "Both have a long hydrocarbon tail and a charged head, but soap's head is a carboxylate (–COO⁻Na⁺) group, while a detergent's head is typically a sulphonate (–SO₃⁻) or ammonium salt group." },
        { q: "Give one environmental disadvantage of detergents compared with soaps.", marks: 1, answer: "Many detergents have branched hydrocarbon chains that bacteria cannot break down (non-biodegradable), so they persist in rivers and water bodies, causing pollution and foaming — whereas soaps are biodegradable." },
      ] },
  ],
};
