import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "periodic-classification-of-elements",
  num: 5,
  title: "Periodic Classification of Elements",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · formative assessment only",
  formative: true,
  minutes: 16,
  blurb: "How chemists went from 'these three look similar' to a table that predicts elements nobody had found yet.",
  bigIdea: "The periodic table is not a filing system — it is a prediction machine. Once you know an element's position, you can say how big it is, how reactive it is and what it will bond with.",
  syllabus: [
    "Döbereiner's triads", "Newlands' law of octaves",
    "Mendeléev's periodic table", "Modern periodic table",
    "Gradation in properties", "Valency", "Atomic number",
    "Metallic and non-metallic properties",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "About this chapter", html: "CBSE has placed this topic under <strong>formative assessment only</strong> for 2026-27 — it will not be set in the year-end paper, but it can appear in periodic tests, portfolio work and internal assessment. It also underpins Chapters 3 and 4, so it is worth understanding rather than skipping." },

    { t: "h", text: "Three attempts before the right answer" },
    { t: "p", html: "By the early 1800s chemists knew of about 30 elements and could see that some behaved alike. The problem was finding the pattern." },
    { t: "table", head: ["Attempt", "The idea", "Why it failed"], rows: [
      ["<strong>Döbereiner's triads</strong> (1817)", "Groups of three similar elements where the middle atomic mass is the average of the other two. Li(7), Na(23), K(39) — and (7+39)/2 = 23.", "Only three triads could be found among all known elements. Too few to be a real law."],
      ["<strong>Newlands' octaves</strong> (1866)", "Arrange by increasing atomic mass and every eighth element repeats the properties of the first — like the eight notes of a musical scale.", "Worked only up to calcium. It assumed no more elements would be discovered, and forced two elements into one slot."],
      ["<strong>Mendeléev's table</strong> (1869)", "Arranged by increasing atomic mass, but grouped by <em>chemical properties</em> — particularly the formulae of their oxides and hydrides.", "Could not place hydrogen properly; isotopes had no home; and a few pairs had to be placed out of mass order."],
    ] },
    { t: "note", kind: "idea", title: "Why Mendeléev is the famous one", html: "He left <strong>gaps</strong>. Rather than force elements to fit, he predicted that undiscovered elements would fill those gaps, and described their properties in advance — calling them eka-boron, eka-aluminium and eka-silicon. When scandium, gallium and germanium were later found and matched his predictions almost exactly, the table was accepted worldwide." },
    { t: "note", kind: "why", title: "The anomaly that broke it", html: "Cobalt (58.9) had to be placed <em>before</em> nickel (58.7) even though its mass is higher, because its chemistry demanded it. That inconsistency was the clue that atomic mass was not the real organising principle." },

    { t: "h", text: "The modern periodic law" },
    { t: "p", html: "In 1913 Henry Moseley showed that <strong>atomic number</strong> — the number of protons — is the fundamental property of an element, not atomic mass. The modern periodic law follows:" },
    { t: "formula", name: "Modern periodic law", expr: "Properties of elements are a periodic function of their <strong>atomic number</strong>.", where: ["atomic number = number of protons in the nucleus"] },
    { t: "p", html: "Switching from mass to number fixed every problem at once: cobalt and nickel fell into the right order, isotopes had no issue (same atomic number, so same position), and the position of every element became fixed and unambiguous." },
    { t: "list", items: [
      "<strong>18 groups</strong> (vertical columns) — elements in a group have the <strong>same number of valence electrons</strong>, so they behave chemically alike.",
      "<strong>7 periods</strong> (horizontal rows) — the period number tells you <strong>how many shells</strong> the atom has.",
    ] },
    { t: "sim", id: "periodic-table" },

    { t: "h", text: "The four trends" },
    { t: "p", html: "Almost every question in this chapter is one of these four, so learn them as a pair of directions each." },
    { t: "table", head: ["Property", "Across a period (left → right)", "Down a group", "Reason"], rows: [
      ["Valency", "Rises 1→4 then falls 4→0", "Stays the same", "Decided by valence electrons"],
      ["Atomic size", "<span style='color:#dc2626'>Decreases</span>", "<span style='color:#16a34a'>Increases</span>", "Across: same shell, more protons pulling harder. Down: a whole new shell is added"],
      ["Metallic character", "<span style='color:#dc2626'>Decreases</span>", "<span style='color:#16a34a'>Increases</span>", "Metals lose electrons — easier when the outer shell is far from the nucleus"],
      ["Non-metallic character", "<span style='color:#16a34a'>Increases</span>", "<span style='color:#dc2626'>Decreases</span>", "Non-metals gain electrons — easier when the nucleus pulls strongly"],
    ] },
    { t: "note", kind: "memory", html: "One sentence covers three of them: <strong>going down a group, the atom gets bigger, so it holds its outer electrons more loosely, so it becomes more metallic.</strong> Everything else is the reverse of that." },
    { t: "note", kind: "trap", html: "Atomic size <em>decreasing</em> across a period surprises people — you are adding electrons, so surely it should grow? No: those electrons all go into the <em>same</em> shell, while the nuclear charge keeps rising. The stronger pull shrinks the atom." },

    { t: "h", text: "Reading the table like a chemist" },
    { t: "list", items: [
      "<strong>Group 1 — alkali metals.</strong> One valence electron, lose it eagerly, extremely reactive. Reactivity increases down the group (caesium is dangerous in air).",
      "<strong>Group 2 — alkaline earth metals.</strong> Two valence electrons, valency 2.",
      "<strong>Group 17 — halogens.</strong> Seven valence electrons, desperate for one more, so very reactive non-metals. Reactivity <em>decreases</em> down this group.",
      "<strong>Group 18 — noble gases.</strong> Complete outer shell, valency 0, essentially unreactive.",
      "<strong>Metalloids</strong> — B, Si, Ge, As, Sb, Te sit on the zig-zag boundary and show properties of both metals and non-metals.",
    ] },
    { t: "note", kind: "real", html: "Silicon is a metalloid, and that is precisely why every chip in your phone is made of it — it conducts, but only just, and only when you want it to. Pure metals conduct too well to be useful as switches." },

    { t: "steps", title: "An element has the electron arrangement 2, 8, 7. Find its group, period and nature.",
      intro: "This exact style of question comes up every year. It takes three lines.",
      steps: [
        "Count the shells: there are three numbers, so it is in <strong>period 3</strong>.",
        "Look at the valence electrons: <strong>7</strong>. For elements with 3 or more valence electrons, group number = valence electrons + 10, so 7 + 10 = <strong>group 17</strong>.",
        "Seven valence electrons means it needs just one more, so it gains an electron: valency = 8 − 7 = <strong>1</strong>.",
        "Elements that gain electrons are non-metals, and group 17 is the halogen family — so this is chlorine (Z = 17).",
      ],
      answer: "Period 3, Group 17, valency 1, a highly reactive non-metal — chlorine.",
    },
  ],
  formulas: [
    { name: "Modern periodic law", expr: "Properties are a periodic function of atomic number", note: "Replaced Mendeléev's atomic-mass version in 1913" },
    { name: "Group from valence electrons", expr: "1–2 electrons → group = electrons &nbsp;·&nbsp; 3–8 electrons → group = electrons + 10" },
    { name: "Period", expr: "Period number = number of occupied shells" },
  ],
  examFocus: [
    "The three early attempts, one limitation each — that is the standard three-mark question.",
    "Why Mendeléev's gaps made his table a scientific triumph, with the three predicted elements.",
    "Why atomic number replaced atomic mass — cobalt/nickel and isotopes are the two arguments.",
    "The four trends, each with a reason, not just a direction.",
    "Finding group, period, valency and nature from an electron arrangement.",
  ],
  flashcards: [
    { q: "State Döbereiner's law of triads.", a: "When three chemically similar elements are arranged by increasing atomic mass, the atomic mass of the middle element is roughly the average of the other two. Example: Li(7), Na(23), K(39)." },
    { q: "What was Newlands' law of octaves and its main limitation?", a: "Arranged by increasing atomic mass, every eighth element repeated the properties of the first. It only worked up to calcium and assumed no new elements would be discovered." },
    { q: "Why is Mendeléev's periodic table considered a major achievement?", a: "He left gaps for undiscovered elements and predicted their properties. Scandium, gallium and germanium were later found and matched his predictions closely." },
    { q: "Name two limitations of Mendeléev's periodic table.", a: "Hydrogen had no fixed position (it resembles both group 1 and group 17), and isotopes of the same element could not be placed since they have different atomic masses." },
    { q: "State the modern periodic law.", a: "Properties of elements are a periodic function of their atomic number." },
    { q: "How many groups and periods are in the modern periodic table?", a: "18 groups (vertical columns) and 7 periods (horizontal rows)." },
    { q: "What do elements in the same group have in common?", a: "The same number of valence electrons, which is why they show similar chemical properties and the same valency." },
    { q: "Why does atomic size decrease across a period?", a: "Electrons are added to the same shell while the number of protons increases, so the nucleus pulls the electron cloud in more strongly." },
    { q: "Why does metallic character increase down a group?", a: "Atomic size increases, so the valence electrons are further from the nucleus and held more loosely — making them easier to lose, which is what a metal does." },
    { q: "How does valency change across a period?", a: "It increases from 1 to 4 and then decreases back to 0 — because valency is decided by how many electrons are gained or lost to complete the outer shell." },
    { q: "What are metalloids? Name three.", a: "Elements showing properties of both metals and non-metals, lying along the zig-zag boundary. Examples: boron, silicon, germanium." },
    { q: "An element has the arrangement 2,8,2. What is its group, period and valency?", a: "Three shells → period 3. Two valence electrons → group 2, valency 2. It is magnesium, a metal." },
  ],
  quiz: [
    { q: "In Döbereiner's triad Li, Na, K with masses 7, 23, 39, the mass of sodium is:", options: ["The sum of the other two", "The average of the other two", "Twice lithium", "Half of potassium"], answer: 1, why: "(7 + 39)/2 = 23 — the middle element's atomic mass is the average of the first and third." },
    { q: "Newlands' law of octaves failed because:", options: ["It used atomic number", "It worked only up to calcium", "It ignored noble gases only", "It had too many groups"], answer: 1, why: "Beyond calcium the pattern broke down, and Newlands wrongly assumed that only 56 elements existed." },
    { q: "Mendeléev's greatest success was:", options: ["Using atomic number", "Placing hydrogen correctly", "Leaving gaps and predicting undiscovered elements", "Including the noble gases"], answer: 2, why: "He predicted eka-boron, eka-aluminium and eka-silicon — later found as scandium, gallium and germanium, with properties close to his predictions." },
    { q: "The modern periodic table arranges elements by increasing:", options: ["Atomic mass", "Atomic number", "Valency", "Density"], answer: 1, why: "Moseley showed atomic number, not atomic mass, is the fundamental property. This fixed the cobalt/nickel anomaly and the isotope problem." },
    { q: "Which of these has the largest atomic radius?", options: ["Li", "Na", "K", "H"], answer: 2, why: "Atomic size increases down a group as new shells are added. K is lowest of these in group 1." },
    { q: "Across period 3 from Na to Cl, the atomic size:", options: ["Increases", "Decreases", "Stays the same", "First increases then decreases"], answer: 1, why: "Electrons enter the same shell while nuclear charge increases, pulling the electron cloud inward." },
    { q: "An element with electron arrangement 2,8,8 belongs to group:", options: ["8", "16", "18", "2"], answer: 2, why: "Eight valence electrons means a complete outer shell — a noble gas, in group 18. This is argon." },
    { q: "Which element is most metallic?", options: ["Mg", "Al", "Si", "Na"], answer: 3, why: "Metallic character decreases across a period. Sodium is furthest left of these, so it is the most metallic." },
    { q: "The number of shells in an atom tells you its:", options: ["Group number", "Period number", "Valency", "Atomic mass"], answer: 1, why: "Period number equals the number of occupied electron shells." },
    { q: "Which pair would have similar chemical properties?", options: ["Na and Mg", "Cl and Br", "C and N", "Li and Be"], answer: 1, why: "Cl and Br are both in group 17 with 7 valence electrons, so they behave chemically alike." },
  ],
};
