import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "periodic-classification-of-elements",
  num: 5,
  title: "Periodic Classification of Elements",
  unit: "chemistry",
  unitName: "Chemical Substances — Nature and Behaviour",
  marks: "Unit I · formative assessment only",
  formative: true,
  minutes: 16,
  blurb: "How chemists went from 'these three look similar' to a table that predicts elements nobody had found yet.",
  bigIdea: "The periodic table is not a filing system — it is a prediction machine. Once you know an element's position, you can say how big it is, how reactive it is and what it will bond with.",
  syllabus: [
    "Döbereiner's triads", "Newlands' law of octaves",
    "Mendeléev's periodic table", "Modern periodic table",
    "Gradation in properties", "Valency", "Atomic number",
    "Metallic and non-metallic properties",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "About this chapter", html: "CBSE has placed this topic under <strong>formative assessment only</strong> for 2026-27 — it will not be set in the year-end paper, but it can appear in periodic tests, portfolio work and internal assessment. It also underpins Chapters 3 and 4, so it is worth understanding rather than skipping." },

    { t: "h", text: "Three attempts before the right answer" },
    { t: "p", html: "By the early 1800s chemists knew of about 30 elements and could see that some behaved alike. The problem was finding the pattern." },
    { t: "table", head: ["Attempt", "The idea", "Why it failed"], rows: [
      ["<strong>Döbereiner's triads</strong> (1817)", "Groups of three similar elements where the middle atomic mass is the average of the other two. Li(7), Na(23), K(39) — and (7+39)/2 = 23.", "Only three triads could be found among all known elements. Too few to be a real law."],
      ["<strong>Newlands' octaves</strong> (1866)", "Arrange by increasing atomic mass and every eighth element repeats the properties of the first — like the eight notes of a musical scale.", "Worked only up to calcium. It assumed no more elements would be discovered, and forced two elements into one slot."],
      ["<strong>Mendeléev's table</strong> (1869)", "Arranged by increasing atomic mass, but grouped by <em>chemical properties</em> — particularly the formulae of their oxides and hydrides.", "Could not place hydrogen properly; isotopes had no home; and a few pairs had to be placed out of mass order."],
    ] },
    { t: "note", kind: "idea", title: "Why Mendeléev is the famous one", html: "He left <strong>gaps</strong>. Rather than force elements to fit, he predicted that undiscovered elements would fill those gaps, and described their properties in advance — calling them eka-boron, eka-aluminium and eka-silicon. When scandium, gallium and germanium were later found and matched his predictions almost exactly, the table was accepted worldwide." },
    { t: "note", kind: "why", title: "The anomaly that broke it", html: "Cobalt (58.9) had to be placed <em>before</em> nickel (58.7) even though its mass is higher, because its chemistry demanded it. That inconsistency was the clue that atomic mass was not the real organising principle." },

    { t: "h", text: "The modern periodic law" },
    { t: "p", html: "In 1913 Henry Moseley showed that <strong>atomic number</strong> — the number of protons — is the fundamental property of an element, not atomic mass. The modern periodic law follows:" },
    { t: "formula", name: "Modern periodic law", expr: "Properties of elements are a periodic function of their <strong>atomic number</strong>.", where: ["atomic number = number of protons in the nucleus"] },
    { t: "p", html: "Switching from mass to number fixed every problem at once: cobalt and nickel fell into the right order, isotopes had no issue (same atomic number, so same position), and the position of every element became fixed and unambiguous." },
    { t: "list", items: [
      "<strong>18 groups</strong> (vertical columns) — elements in a group have the <strong>same number of valence electrons</strong>, so they behave chemically alike.",
      "<strong>7 periods</strong> (horizontal rows) — the period number tells you <strong>how many shells</strong> the atom has.",
    ] },
    { t: "sim", id: "periodic-table" },

    { t: "h", text: "The four trends" },
    { t: "p", html: "Almost every question in this chapter is one of these four, so learn them as a pair of directions each." },
    { t: "table", head: ["Property", "Across a period (left → right)", "Down a group", "Reason"], rows: [
      ["Valency", "Rises 1→4 then falls 4→0", "Stays the same", "Decided by valence electrons"],
      ["Atomic size", "<span style='color:#dc2626'>Decreases</span>", "<span style='color:#16a34a'>Increases</span>", "Across: same shell, more protons pulling harder. Down: a whole new shell is added"],
      ["Metallic character", "<span style='color:#dc2626'>Decreases</span>", "<span style='color:#16a34a'>Increases</span>", "Metals lose electrons — easier when the outer shell is far from the nucleus"],
      ["Non-metallic character", "<span style='color:#16a34a'>Increases</span>", "<span style='color:#dc2626'>Decreases</span>", "Non-metals gain electrons — easier when the nucleus pulls strongly"],
    ] },
    { t: "note", kind: "memory", html: "One sentence covers three of them: <strong>going down a group, the atom gets bigger, so it holds its outer electrons more loosely, so it becomes more metallic.</strong> Everything else is the reverse of that." },
    { t: "note", kind: "trap", html: "Atomic size <em>decreasing</em> across a period surprises people — you are adding electrons, so surely it should grow? No: those electrons all go into the <em>same</em> shell, while the nuclear charge keeps rising. The stronger pull shrinks the atom." },

    { t: "h", text: "Reading the table like a chemist" },
    { t: "list", items: [
      "<strong>Group 1 — alkali metals.</strong> One valence electron, lose it eagerly, extremely reactive. Reactivity increases down the group (caesium is dangerous in air).",
      "<strong>Group 2 — alkaline earth metals.</strong> Two valence electrons, valency 2.",
      "<strong>Group 17 — halogens.</strong> Seven valence electrons, desperate for one more, so very reactive non-metals. Reactivity <em>decreases</em> down this group.",
      "<strong>Group 18 — noble gases.</strong> Complete outer shell, valency 0, essentially unreactive.",
      "<strong>Metalloids</strong> — B, Si, Ge, As, Sb, Te sit on the zig-zag boundary and show properties of both metals and non-metals.",
    ] },
    { t: "note", kind: "real", html: "Silicon is a metalloid, and that is precisely why every chip in your phone is made of it — it conducts, but only just, and only when you want it to. Pure metals conduct too well to be useful as switches." },

    { t: "steps", title: "An element has the electron arrangement 2, 8, 7. Find its group, period and nature.",
      intro: "This exact style of question comes up every year. It takes three lines.",
      steps: [
        "Count the shells: there are three numbers, so it is in <strong>period 3</strong>.",
        "Look at the valence electrons: <strong>7</strong>. For elements with 3 or more valence electrons, group number = valence electrons + 10, so 7 + 10 = <strong>group 17</strong>.",
        "Seven valence electrons means it needs just one more, so it gains an electron: valency = 8 − 7 = <strong>1</strong>.",
        "Elements that gain electrons are non-metals, and group 17 is the halogen family — so this is chlorine (Z = 17).",
      ],
      answer: "Period 3, Group 17, valency 1, a highly reactive non-metal — chlorine.",
    },
  ],
  formulas: [
    { name: "Modern periodic law", expr: "Properties are a periodic function of atomic number", note: "Replaced Mendeléev's atomic-mass version in 1913" },
    { name: "Group from valence electrons", expr: "1–2 electrons → group = electrons &nbsp;·&nbsp; 3–8 electrons → group = electrons + 10" },
    { name: "Period", expr: "Period number = number of occupied shells" },
  ],
  examFocus: [
    "The three early attempts, one limitation each — that is the standard three-mark question.",
    "Why Mendeléev's gaps made his table a scientific triumph, with the three predicted elements.",
    "Why atomic number replaced atomic mass — cobalt/nickel and isotopes are the two arguments.",
    "The four trends, each with a reason, not just a direction.",
    "Finding group, period, valency and nature from an electron arrangement.",
  ],
  flashcards: [
    { q: "State Döbereiner's law of triads.", a: "When three chemically similar elements are arranged by increasing atomic mass, the atomic mass of the middle element is roughly the average of the other two. Example: Li(7), Na(23), K(39)." },
    { q: "What was Newlands' law of octaves and its main limitation?", a: "Arranged by increasing atomic mass, every eighth element repeated the properties of the first. It only worked up to calcium and assumed no new elements would be discovered." },
    { q: "Why is Mendeléev's periodic table considered a major achievement?", a: "He left gaps for undiscovered elements and predicted their properties. Scandium, gallium and germanium were later found and matched his predictions closely." },
    { q: "Name two limitations of Mendeléev's periodic table.", a: "Hydrogen had no fixed position (it resembles both group 1 and group 17), and isotopes of the same element could not be placed since they have different atomic masses." },
    { q: "State the modern periodic law.", a: "Properties of elements are a periodic function of their atomic number." },
    { q: "How many groups and periods are in the modern periodic table?", a: "18 groups (vertical columns) and 7 periods (horizontal rows)." },
    { q: "What do elements in the same group have in common?", a: "The same number of valence electrons, which is why they show similar chemical properties and the same valency." },
    { q: "Why does atomic size decrease across a period?", a: "Electrons are added to the same shell while the number of protons increases, so the nucleus pulls the electron cloud in more strongly." },
    { q: "Why does metallic character increase down a group?", a: "Atomic size increases, so the valence electrons are further from the nucleus and held more loosely — making them easier to lose, which is what a metal does." },
    { q: "How does valency change across a period?", a: "It increases from 1 to 4 and then decreases back to 0 — because valency is decided by how many electrons are gained or lost to complete the outer shell." },
    { q: "What are metalloids? Name three.", a: "Elements showing properties of both metals and non-metals, lying along the zig-zag boundary. Examples: boron, silicon, germanium." },
    { q: "An element has the arrangement 2,8,2. What is its group, period and valency?", a: "Three shells → period 3. Two valence electrons → group 2, valency 2. It is magnesium, a metal." },
  ],
  quiz: [
    { q: "In Döbereiner's triad Li, Na, K with masses 7, 23, 39, the mass of sodium is:", options: ["The sum of the other two", "The average of the other two", "Twice lithium", "Half of potassium"], answer: 1, why: "(7 + 39)/2 = 23 — the middle element's atomic mass is the average of the first and third." },
    { q: "Newlands' law of octaves failed because:", options: ["It used atomic number", "It worked only up to calcium", "It ignored noble gases only", "It had too many groups"], answer: 1, why: "Beyond calcium the pattern broke down, and Newlands wrongly assumed that only 56 elements existed." },
    { q: "Mendeléev's greatest success was:", options: ["Using atomic number", "Placing hydrogen correctly", "Leaving gaps and predicting undiscovered elements", "Including the noble gases"], answer: 2, why: "He predicted eka-boron, eka-aluminium and eka-silicon — later found as scandium, gallium and germanium, with properties close to his predictions." },
    { q: "The modern periodic table arranges elements by increasing:", options: ["Atomic mass", "Atomic number", "Valency", "Density"], answer: 1, why: "Moseley showed atomic number, not atomic mass, is the fundamental property. This fixed the cobalt/nickel anomaly and the isotope problem." },
    { q: "Which of these has the largest atomic radius?", options: ["Li", "Na", "K", "H"], answer: 2, why: "Atomic size increases down a group as new shells are added. K is lowest of these in group 1." },
    { q: "Across period 3 from Na to Cl, the atomic size:", options: ["Increases", "Decreases", "Stays the same", "First increases then decreases"], answer: 1, why: "Electrons enter the same shell while nuclear charge increases, pulling the electron cloud inward." },
    { q: "An element with electron arrangement 2,8,8 belongs to group:", options: ["8", "16", "18", "2"], answer: 2, why: "Eight valence electrons means a complete outer shell — a noble gas, in group 18. This is argon." },
    { q: "Which element is most metallic?", options: ["Mg", "Al", "Si", "Na"], answer: 3, why: "Metallic character decreases across a period. Sodium is furthest left of these, so it is the most metallic." },
    { q: "The number of shells in an atom tells you its:", options: ["Group number", "Period number", "Valency", "Atomic mass"], answer: 1, why: "Period number equals the number of occupied electron shells." },
    { q: "Which pair would have similar chemical properties?", options: ["Na and Mg", "Cl and Br", "C and N", "Li and Be"], answer: 1, why: "Cl and Br are both in group 17 with 7 valence electrons, so they behave chemically alike." },
  ],
  keyTopics: [
    { name: "Mendeléev's periodic table — achievements and limitations", importance: "high", note: "The gaps-and-predictions story (eka-boron, eka-aluminium, eka-silicon) is the standard 3-mark question." },
    { name: "The modern periodic law and the shift from atomic mass to atomic number", importance: "high", note: "Explained using the cobalt–nickel anomaly and the isotope problem — a common 3-mark reasoning question." },
    { name: "Trends across a period and down a group", importance: "high", note: "Atomic size, metallic/non-metallic character and valency, each with its reason — the most tested skill in the chapter." },
    { name: "Finding group, period, valency and nature from an electronic configuration", importance: "medium", note: "A short, mechanical 2–3 mark question that appears in every practice set." },
    { name: "Döbereiner's triads and Newlands' law of octaves", importance: "medium", note: "One-line statement plus one limitation each." },
    { name: "Characteristic groups — alkali metals, halogens, noble gases", importance: "medium", note: "Reactivity trends within group 1 and group 17 are opposite to each other — a common trap." },
    { name: "Metalloids and the zig-zag boundary", importance: "low", note: "Name three (boron, silicon, germanium) and their dual metal/non-metal behaviour." },
  ],
  written: [
    { q: "Why did Mendeléev leave gaps in his periodic table?", marks: 1, kind: "short", importance: "high",
      answer: "He arranged elements by increasing atomic mass but grouped them by similar chemical properties. Where no known element fitted a particular position, he left a gap, correctly predicting that an undiscovered element with those properties would be found later." },
    { q: "State the modern periodic law.", marks: 1, kind: "short", importance: "high",
      answer: "The properties of elements are a periodic function of their atomic number." },
    { q: "An element has the electronic configuration 2, 8, 3. Find its group and period.", marks: 2, kind: "numerical", importance: "high",
      answer: "Three shells are occupied, so it is in <strong>period 3</strong>. It has 3 valence electrons; for 3–8 valence electrons, group number = valence electrons + 10 = 3 + 10 = <strong>group 13</strong>. (This is aluminium, Z = 13.)" },
    { q: "State two limitations of Mendeléev's periodic table.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> Hydrogen's position was not fixed — it resembles both the alkali metals (group 1) and the halogens (group 17). <strong>(ii)</strong> Isotopes of the same element have different atomic masses, so they could not be given a fixed position on the basis of mass, even though they are the same element." },
    { q: "Why does atomic size decrease across a period from left to right, but increase down a group?", marks: 2, kind: "short", importance: "high",
      answer: "Across a period, electrons are added to the <em>same</em> outermost shell while the number of protons (nuclear charge) increases, so the nucleus pulls the electron cloud in more tightly, shrinking the atom. Down a group, a new shell is added at each step, and this increase in the number of shells outweighs the increase in nuclear charge, so the atom gets larger." },
    { q: "State Döbereiner's law of triads and Newlands' law of octaves, with one limitation of each.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Döbereiner's triads:</strong> in a group of three chemically similar elements arranged by increasing atomic mass, the atomic mass of the middle element is approximately the average of the other two (e.g. Li, Na, K). Limitation: only three such triads could be identified among all the known elements.<br><strong>Newlands' law of octaves:</strong> when elements are arranged in order of increasing atomic mass, every eighth element has properties similar to the first, like musical octaves. Limitation: it worked only up to calcium and broke down for heavier elements, since Newlands wrongly assumed only 56 elements existed in nature." },
    { q: "Why is atomic number, and not atomic mass, considered the basis of the modern periodic table? Explain with reference to cobalt and nickel.", marks: 3, kind: "short", importance: "high",
      answer: "In Mendeléev's table, cobalt (atomic mass 58.9) had to be placed before nickel (atomic mass 58.7) even though its mass is higher, purely because its chemical properties demanded that position — an inconsistency that could not be explained on the basis of atomic mass.<br>Henry Moseley showed that atomic number (the number of protons) is the truly fundamental property of an element. Arranging elements by atomic number places cobalt (Z = 27) correctly before nickel (Z = 28), resolving the anomaly and giving every element an unambiguous position." },
    { q: "How does valency vary across period 3, from sodium to argon, and why?", marks: 3, kind: "numerical", importance: "medium",
      answer: "Across period 3: Na(1), Mg(2), Al(3), Si(4), P(3), S(2), Cl(1), Ar(0). Valency <strong>rises from 1 to 4</strong> (Na to Si) as the number of valence electrons increases from 1 to 4, then <strong>falls back to 0</strong> (P to Ar), because from this point valency is counted as the number of electrons needed to complete the outer shell (8 − valence electrons), which decreases as the shell gets closer to being full." },
    { q: "Compare Mendeléev's periodic table with the modern periodic table under the following heads: (i) basis of classification, (ii) position of isotopes, (iii) anomalous pairs, (iv) number of groups, (v) prediction of new elements.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>(i) Basis:</strong> Mendeléev used increasing atomic mass; the modern table uses increasing atomic number.<br><strong>(ii) Isotopes:</strong> Mendeléev's table had no place for isotopes, since they have different atomic masses; the modern table places all isotopes of an element in the same position, since they share the same atomic number.<br><strong>(iii) Anomalous pairs:</strong> Mendeléev had to place some heavier-mass elements before lighter ones (e.g. cobalt before nickel) to match their properties; the modern table resolves this naturally, since it follows atomic number order.<br><strong>(iv) Groups:</strong> Mendeléev's table had 8 groups; the modern periodic table has 18 groups.<br><strong>(v) Prediction:</strong> Mendeléev left gaps and predicted new elements (eka-boron, eka-aluminium, eka-silicon); the modern table is essentially complete for naturally occurring elements and is used to explain, rather than predict, periodicity." },
    { q: "Explain the trends in metallic and non-metallic character across a period and down a group, giving the reason in each case. Illustrate using elements of period 3.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Across a period</strong> (e.g. Na to Cl in period 3), metallic character <strong>decreases</strong> and non-metallic character <strong>increases</strong>. Atomic size decreases and nuclear charge increases across the period, so the atom holds on to its valence electrons more tightly — making it harder to lose electrons (less metallic) and easier to gain electrons to complete the outer shell (more non-metallic). Sodium is a reactive metal; chlorine is a reactive non-metal.<br><strong>Down a group</strong> (e.g. from fluorine to iodine, or lithium to caesium), the trend reverses: metallic character <strong>increases</strong> and non-metallic character <strong>decreases</strong>, because a new shell is added at each step, so the valence electrons are farther from the nucleus and held more loosely. This makes it easier to lose an electron (more metallic) and harder to attract one more (less non-metallic) going down the group." },
  ],
  assertionReason: [
    { assertion: "Isotopes of the same element occupy the same position in the modern periodic table.",
      reason: "Isotopes have the same atomic number, though their atomic masses are different.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the reason correctly explains the assertion — position in the modern table is fixed by atomic number, which is identical for all isotopes of an element." },
    { assertion: "Atomic size decreases on moving from left to right across a period.",
      reason: "The number of shells in the atom increases across a period.",
      answer: 2, importance: "high",
      why: "The assertion is true. But the reason is false: the number of shells stays the <em>same</em> across a period — it is the increasing nuclear charge pulling on electrons in that same shell that actually causes atomic size to decrease." },
    { assertion: "Fluorine is a more reactive non-metal than iodine.",
      reason: "Down a group, non-metallic character decreases because atomic size increases and the nucleus attracts an incoming electron less strongly.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the reason correctly explains the assertion — fluorine, being smaller and at the top of group 17, attracts an extra electron more strongly than iodine does." },
    { assertion: "Mendeléev's periodic table could accommodate the noble gases smoothly when they were later discovered.",
      reason: "The noble gases were not known when Mendeléev first proposed his table.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but the reason does not explain the assertion. The noble gases fitted in smoothly because they could be added as a completely new group without disturbing the existing sequence of elements — not simply because they were unknown at the time." },
  ],
  caseStudies: [
    { title: "Reading electronic configurations", importance: "high",
      source: "Four elements P, Q, R and S have the electronic configurations shown below:<br><table><thead><tr><th>Element</th><th>Electronic configuration</th></tr></thead><tbody><tr><td>P</td><td>2, 8, 1</td></tr><tr><td>Q</td><td>2, 8, 7</td></tr><tr><td>R</td><td>2, 8, 8</td></tr><tr><td>S</td><td>2, 8, 8, 2</td></tr></tbody></table>",
      parts: [
        { q: "Which element belongs to the halogen family? Give its group number.", marks: 1, answer: "Q (configuration 2,8,7). Seven valence electrons gives group number = 7 + 10 = <strong>group 17</strong>, the halogens." },
        { q: "Which two elements are likely to react vigorously with each other, and what type of bond would they form?", marks: 2, answer: "P (1 valence electron, tends to lose it) and Q (7 valence electrons, tends to gain one) would react vigorously. P would lose its one electron to Q, forming P⁺ and Q⁻ ions, which attract to form an <strong>ionic bond</strong>." },
        { q: "Which element is chemically unreactive, and why?", marks: 1, answer: "R, with configuration 2,8,8, has a completely filled outer shell (8 valence electrons), so it has no tendency to gain, lose or share electrons — it is a noble gas and chemically unreactive." },
        { q: "Are P and S likely to belong to the same group? Justify.", marks: 1, answer: "No. P has 1 valence electron (group 1), while S has 2 valence electrons (group 2). Even though both are metals, a group is defined by the number of valence electrons, and they differ in this respect." },
      ] },
    { title: "From triads to the modern table", importance: "medium",
      source: "A study group compares three attempts at classifying elements:<br><table><thead><tr><th>Attempt</th><th>Basis of arrangement</th><th>Elements covered</th></tr></thead><tbody><tr><td>Döbereiner (1817)</td><td>Increasing atomic mass, in groups of three</td><td>A handful of triads only</td></tr><tr><td>Newlands (1866)</td><td>Increasing atomic mass, repeating every 8th element</td><td>Worked only up to calcium</td></tr><tr><td>Mendeléev (1869)</td><td>Increasing atomic mass, grouped by chemical properties</td><td>All known elements, with gaps left for more</td></tr></tbody></table>",
      parts: [
        { q: "Why could Döbereiner's classification not be extended to all known elements?", marks: 1, answer: "Among all the elements known at the time, only a few triads could be identified where the pattern held, so it could not be applied as a general law." },
        { q: "What was different about Mendeléev's approach compared to Newlands' that made it more successful?", marks: 2, answer: "Mendeléev grouped elements primarily by chemical properties (such as the formulae of their oxides and hydrides) rather than strictly by atomic mass, and he was willing to leave gaps for undiscovered elements instead of forcing every known element into a fixed slot of eight, as Newlands had done." },
        { q: "What eventually replaced atomic mass as the basis for arranging elements, and who discovered this?", marks: 1, answer: "Atomic number, shown by Henry Moseley in 1913 to be the truly fundamental property governing the periodicity of elements' properties." },
      ] },
  ],
};
