import type { Chapter } from "@/lib/types";

export const ch06: Chapter = {
  slug: "life-processes",
  num: 6,
  title: "Life Processes",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · 25 marks",
  minutes: 28,
  blurb: "Four jobs every living body must do without stopping: take in food, release energy, move things around, and throw out the waste.",
  bigIdea: "Being alive costs energy every second, even asleep. Nutrition, respiration, transport and excretion are simply the four systems that keep paying that bill.",
  syllabus: [
    "Nutrition in plants and animals", "Respiration in plants and animals",
    "Transport in plants and animals", "Excretion in plants and animals",
  ],
  blocks: [
    { t: "h", text: "What counts as a life process?" },
    { t: "p", html: "Molecules in a living body are constantly wearing out and being replaced. That maintenance never stops — not even when you are asleep or a plant is in the dark. The processes that keep it running are the life processes." },
    { t: "note", kind: "idea", html: "A one-celled amoeba can get everything it needs by diffusion across its surface. A human cannot: we are too big, and our inner cells are nowhere near the outside. That single problem of <strong>size</strong> is why we need lungs, blood, a heart and kidneys at all." },

    { t: "h", text: "Nutrition in plants — photosynthesis" },
    { t: "p", html: "Autotrophs make their own food. Plants take in the simplest possible raw materials — carbon dioxide and water — and, using sunlight captured by chlorophyll, build glucose." },
    { t: "formula", name: "Photosynthesis", expr: "6CO₂ + 6H₂O &nbsp;—<span class='faint'>sunlight, chlorophyll</span>→&nbsp; C₆H₁₂O₆ + 6O₂",
      where: ["CO₂ enters through stomata", "water comes up from the roots", "glucose is stored as starch"] },
    { t: "list", ordered: true, items: [
      "Chlorophyll absorbs light energy.",
      "That energy splits water into hydrogen and oxygen — the oxygen you breathe is a by-product of this step.",
      "CO₂ is reduced to carbohydrate using the hydrogen.",
    ] },
    { t: "p", html: "<strong>Stomata</strong> are tiny pores, mostly on the underside of leaves, each guarded by two bean-shaped guard cells. When the guard cells take in water they swell and bend apart, opening the pore; when they lose water they go limp and close it." },
    { t: "note", kind: "why", title: "Why do stomata close at all?", html: "Open stomata let CO₂ in — but they also let a great deal of water escape. So the plant keeps them shut when it does not need gas exchange, which is why they are mostly closed at night." },

    { t: "h", text: "Nutrition in animals" },
    { t: "p", html: "Heterotrophs eat ready-made food. Amoeba engulfs its food with pseudopodia; a paramecium sweeps it in with cilia; we have a five-metre tube with specialists stationed along it." },
    { t: "sim", id: "digestion-journey" },
    { t: "table", head: ["Where", "Juice / enzyme", "Acts on", "Product"], rows: [
      ["Mouth", "Saliva — salivary amylase", "Starch", "Sugar (maltose)"],
      ["Stomach", "Gastric juice — pepsin, HCl, mucus", "Proteins", "Peptides"],
      ["Small intestine", "Bile (from liver)", "Fats", "Emulsified into small droplets"],
      ["Small intestine", "Pancreatic juice — trypsin, lipase, amylase", "Proteins, fats, starch", "Amino acids, fatty acids + glycerol, sugars"],
      ["Small intestine", "Intestinal juice", "Everything remaining", "Fully digested, ready to absorb"],
    ] },
    { t: "note", kind: "exam", html: "Three functions of HCl in the stomach: it makes the medium acidic so pepsin can work, it kills bacteria in the food, and it softens the food. And bile does <strong>not</strong> contain any enzyme — its job is emulsification and making the medium alkaline. Both points are examined constantly." },
    { t: "note", kind: "why", title: "Why are villi finger-shaped?", html: "The small intestine is lined with millions of tiny projections called villi. They multiply the absorbing surface enormously — the same trick as crumpling a sheet of paper to fit more of it into a small space. Each villus has blood vessels waiting just beneath the surface." },

    { t: "h", text: "Respiration — releasing the energy" },
    { t: "p", html: "Photosynthesis <em>stored</em> the energy in glucose. Respiration <em>releases</em> it, in a controlled step-by-step way, and packs it into a molecule called <strong>ATP</strong> — the energy currency the cell actually spends." },
    { t: "table", head: ["Type", "Where", "Products", "Energy"], rows: [
      ["<strong>Aerobic</strong> (with oxygen)", "Mitochondria", "CO₂ + water", "A lot — 38 ATP"],
      ["<strong>Anaerobic in yeast</strong>", "Cytoplasm", "Ethanol + CO₂", "Little"],
      ["<strong>Anaerobic in our muscles</strong>", "Cytoplasm", "Lactic acid", "Little"],
    ] },
    { t: "note", kind: "real", html: "That cramp after sprinting is lactic acid. Your muscles ran out of oxygen, switched to anaerobic respiration, and the lactic acid built up. It clears once you rest and breathe deeply — which is exactly why you keep panting after you stop running." },
    { t: "p", html: "In humans, air enters through the nostrils (where hair and mucus filter it), passes down the trachea — held open by rings of cartilage — and branches into bronchi, bronchioles and finally <strong>alveoli</strong>, tiny balloon-like sacs." },
    { t: "note", kind: "idea", html: "The alveoli are where the whole system pays off: hundreds of millions of them give a surface area of roughly 80 m², about half a badminton court, all folded inside your chest. Each is one cell thick and wrapped in capillaries, so oxygen has the shortest possible distance to cross." },
    { t: "p", html: "Haemoglobin in red blood cells carries the oxygen. Carbon dioxide is more soluble, so most of it is simply carried dissolved in the plasma." },
    { t: "note", kind: "trap", html: "Fish extract oxygen dissolved in water, which is far less concentrated than in air — so their breathing rate is much faster than ours. That comparison is a standard two-mark question." },

    { t: "h", text: "Transport in humans" },
    { t: "sim", id: "heart-circulation" },
    { t: "list", items: [
      "<strong>Four chambers.</strong> Two atria on top receive blood; two ventricles below pump it out. The left ventricle has the thickest wall because it must push blood all the way round the body.",
      "<strong>Valves</strong> make sure blood only goes one way — that clicking shut is the 'lub-dub' of a heartbeat.",
      "<strong>Arteries</strong> carry blood away from the heart, have thick elastic walls (the blood is under high pressure) and no valves. <strong>Veins</strong> carry blood back, have thin walls and valves to stop backflow.",
      "<strong>Capillaries</strong> are one cell thick — that is where the actual exchange with tissues happens.",
      "<strong>Lymph</strong> is the fluid that leaks out of capillaries into tissues; it drains back into the veins, and also carries digested fat from the intestine.",
    ] },
    { t: "note", kind: "why", title: "Why do we need double circulation?", html: "Because we are warm-blooded. Keeping body temperature constant burns a lot of energy, which needs a lot of oxygen, which needs oxygenated and deoxygenated blood kept completely separate. Fish, which are not warm-blooded, manage with single circulation and a two-chambered heart." },

    { t: "h", text: "Transport in plants" },
    { t: "compare",
      left: { title: "Xylem — the water pipe", items: [
        "Carries <strong>water and minerals</strong>",
        "Upward only, roots → leaves",
        "Made of dead cells forming hollow tubes",
        "Driven by <strong>transpiration pull</strong> — water evaporating from leaves sucks the column upward",
        "No energy needed from the plant",
      ] },
      right: { title: "Phloem — the food pipe", items: [
        "Carries <strong>food</strong> (sucrose) and hormones",
        "Both directions, wherever food is needed",
        "Made of living cells",
        "Called <strong>translocation</strong>; uses energy from ATP",
        "Water follows the sugar by osmosis, creating pressure that moves the sap",
      ] } },
    { t: "note", kind: "real", html: "Transpiration is not just a side effect. It pulls water up a hundred-foot tree with no pump at all, and it cools the plant — the same way sweating cools you." },

    { t: "h", text: "Excretion" },
    { t: "sim", id: "nephron-filter" },
    { t: "p", html: "Each kidney holds about a million filtering units called <strong>nephrons</strong>. The logic is counter-intuitive but efficient: filter almost everything out of the blood first, then take back what is still useful." },
    { t: "note", kind: "exam", html: "In a healthy person, <strong>all</strong> the glucose is reabsorbed — glucose in urine is a sign that blood sugar is too high for the tubules to keep up. Amount of urine depends on how much excess water the body has and how much dissolved waste must be flushed out." },
    { t: "p", html: "When kidneys fail, blood is cleaned artificially by <strong>dialysis</strong>, using a machine with a semi-permeable membrane and a fluid that has the same salts and glucose as blood but no nitrogenous waste — so waste diffuses out while useful things stay in." },
    { t: "p", html: "Plants have it much easier. They have no specialised excretory organ:" },
    { t: "list", items: [
      "Excess oxygen and carbon dioxide leave through stomata.",
      "Extra water is lost by transpiration.",
      "Waste products are stored in old leaves — which are then shed — or in vacuoles, resins and gums in the bark.",
      "Some waste is simply released into the soil around the roots.",
    ] },

    { t: "steps", title: "Trace a molecule of oxygen from the air to a muscle cell in your leg.",
      intro: "This links three systems together, which is exactly why the board likes it.",
      steps: [
        "Air is drawn in through the nostrils, filtered and warmed, and passes down the trachea and bronchi.",
        "It reaches an <strong>alveolus</strong>, whose wall is one cell thick and surrounded by capillaries.",
        "Oxygen diffuses across into the blood and binds to <strong>haemoglobin</strong> in red blood cells.",
        "The blood returns via the pulmonary vein to the <strong>left atrium</strong>, then the left ventricle.",
        "The left ventricle pumps it into the aorta and on through arteries to the leg.",
        "In the leg capillaries oxygen diffuses out into the muscle cell, and is used in the <strong>mitochondria</strong> to break down glucose and release ATP.",
      ],
      answer: "Nostrils → trachea → bronchi → alveoli → blood (haemoglobin) → pulmonary vein → left atrium → left ventricle → aorta → leg capillaries → muscle cell mitochondria.",
    },
  ],
  formulas: [
    { name: "Photosynthesis", expr: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂", note: "Requires sunlight and chlorophyll. Endothermic." },
    { name: "Aerobic respiration", expr: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP", note: "In mitochondria" },
    { name: "Anaerobic — yeast", expr: "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + energy", note: "Fermentation; happens in the cytoplasm" },
    { name: "Anaerobic — muscle", expr: "C₆H₁₂O₆ → 2C₃H₆O₃ (lactic acid) + energy", note: "Causes cramps during heavy exercise" },
  ],
  examFocus: [
    "The photosynthesis equation with conditions written above the arrow, and the three events in order.",
    "Guard cells and the opening/closing mechanism, with why stomata close at night.",
    "The enzyme table — which juice, from where, acting on what.",
    "Three functions of HCl, and that bile has no enzyme.",
    "Why villi are needed — surface area argument.",
    "Aerobic vs anaerobic with products and site, including the lactic acid cramp example.",
    "Labelled heart diagram, and why the left ventricle wall is thickest.",
    "Xylem vs phloem in a five-row comparison table.",
    "The three steps in a nephron: filtration, selective reabsorption, water balance.",
  ],
  flashcards: [
    { q: "Write the balanced equation for photosynthesis.", a: "6CO₂ + 6H₂O →(sunlight, chlorophyll) C₆H₁₂O₆ + 6O₂. Carbon dioxide and water become glucose and oxygen." },
    { q: "What are the three events of photosynthesis?", a: "1) Chlorophyll absorbs light energy. 2) Light energy splits water into hydrogen and oxygen. 3) Carbon dioxide is reduced to carbohydrate using that hydrogen." },
    { q: "How do guard cells open and close a stoma?", a: "When guard cells take in water they swell and bow apart, opening the pore. When they lose water they become flaccid and the pore closes." },
    { q: "Name the three functions of HCl in the stomach.", a: "Creates the acidic medium pepsin needs, kills bacteria in the food, and softens the food." },
    { q: "What is the role of bile?", a: "Bile contains no enzyme. It makes the acidic food from the stomach alkaline, and emulsifies fat — breaking large globules into small droplets so lipase can act on them." },
    { q: "Why is the small intestine so long and lined with villi?", a: "Digestion of all three food types completes here and absorption takes time. Villi are finger-like projections that hugely increase the surface area for absorption, with blood vessels just beneath." },
    { q: "Compare aerobic and anaerobic respiration.", a: "Aerobic: in mitochondria, uses oxygen, gives CO₂ + water, releases a lot of energy (38 ATP). Anaerobic: in cytoplasm, no oxygen, gives ethanol + CO₂ (yeast) or lactic acid (muscle), releases little energy." },
    { q: "Why do muscles cramp during heavy exercise?", a: "Oxygen supply falls short, so muscles respire anaerobically and produce lactic acid. Its build-up causes cramps, which clear on rest as oxygen returns." },
    { q: "Why are alveoli so effective at gas exchange?", a: "They are extremely numerous (surface area about 80 m²), one cell thick, moist, and richly supplied with capillaries — so oxygen has the shortest path into the blood." },
    { q: "Why is the wall of the left ventricle thicker than the right?", a: "The left ventricle must pump blood at high pressure to the entire body; the right ventricle only pumps it to the nearby lungs." },
    { q: "Differentiate arteries and veins.", a: "Arteries carry blood away from the heart, have thick elastic walls, carry blood at high pressure and have no valves. Veins carry blood back to the heart, have thin walls, low pressure, and valves to prevent backflow." },
    { q: "What is lymph and what does it do?", a: "A colourless fluid that leaks out of capillaries into intercellular spaces. It drains back into veins, carries digested fat from the intestine, and helps fight infection." },
    { q: "Compare xylem and phloem.", a: "Xylem carries water and minerals upward through dead hollow cells, driven by transpiration pull with no energy required. Phloem carries food in both directions through living cells, using energy from ATP — this is translocation." },
    { q: "What is transpiration pull?", a: "As water evaporates from leaf cells, it creates a suction that pulls the continuous column of water up the xylem from the roots — the main force lifting water in tall plants." },
    { q: "Describe the three steps in urine formation.", a: "1) Filtration in the glomerulus — water, glucose, salts and urea are forced out of the blood. 2) Selective reabsorption in the tubule — all glucose, most water and some salts are taken back. 3) Water balance in the collecting duct decides the final volume." },
    { q: "How do plants get rid of waste?", a: "Gases leave through stomata, excess water by transpiration, and waste is stored in old leaves that are shed, or as resins and gums in bark, or released into the surrounding soil." },
  ],
  quiz: [
    { q: "The site of aerobic respiration in a cell is the:", options: ["Nucleus", "Cytoplasm", "Mitochondria", "Ribosome"], answer: 2, why: "Glycolysis begins in the cytoplasm, but the oxygen-using steps that release most of the energy occur in the mitochondria — which is why they are called the powerhouse of the cell." },
    { q: "Which of these does bile NOT do?", options: ["Make the medium alkaline", "Emulsify fats", "Digest proteins", "Help lipase to act"], answer: 2, why: "Bile contains no enzyme at all, so it cannot digest anything. It only emulsifies fat and makes the medium alkaline." },
    { q: "The opening and closing of stomata is controlled by:", options: ["Chlorophyll", "Guard cells", "Xylem", "Root hairs"], answer: 1, why: "Two bean-shaped guard cells surround each stoma. They swell to open it and become flaccid to close it." },
    { q: "During vigorous exercise, muscles produce:", options: ["Ethanol and CO₂", "Lactic acid", "Water and CO₂ only", "Glucose"], answer: 1, why: "With insufficient oxygen, muscle cells respire anaerobically and glucose is converted to lactic acid, causing cramps." },
    { q: "Blood returning from the lungs enters the:", options: ["Right atrium", "Left atrium", "Right ventricle", "Aorta"], answer: 1, why: "Oxygenated blood comes back through the pulmonary vein into the left atrium, then passes to the left ventricle and out to the body." },
    { q: "Which vessel carries oxygenated blood but is called a vein?", options: ["Pulmonary artery", "Pulmonary vein", "Aorta", "Vena cava"], answer: 1, why: "The pulmonary vein is the exception — it carries oxygenated blood from lungs to heart. (The pulmonary artery is the reverse exception.)" },
    { q: "Water rises in a tall tree mainly because of:", options: ["Root pressure alone", "Transpiration pull", "Translocation", "Osmosis in the phloem"], answer: 1, why: "Evaporation from leaves creates a suction that pulls the continuous water column up the xylem. Root pressure alone is far too weak for a tall tree." },
    { q: "In a healthy person, the glucose filtered in the glomerulus is:", options: ["Excreted fully", "Partly excreted", "Completely reabsorbed", "Converted to urea"], answer: 2, why: "Selective reabsorption in the tubule takes back all the glucose, which is why healthy urine contains none." },
    { q: "Which of these is a function of lymph?", options: ["Carrying oxygen", "Carrying digested fat from the intestine", "Producing bile", "Filtering urea"], answer: 1, why: "Lymph absorbs and transports digested fats from the intestine and returns leaked fluid to the blood." },
    { q: "The dialysis fluid used in an artificial kidney contains:", options: ["Only water", "Same salts and glucose as blood, but no nitrogenous waste", "Concentrated urea", "Blood plasma"], answer: 1, why: "Matching the salts and glucose stops them diffusing out, while the absence of urea makes urea diffuse from blood into the fluid." },
    { q: "Fish breathe faster than land animals because:", options: ["They are smaller", "Water contains far less dissolved oxygen than air", "They have no lungs", "Water is denser"], answer: 1, why: "The amount of dissolved oxygen in water is much lower than in air, so fish must pass much more water over their gills." },
    { q: "Which statement about phloem is correct?", options: ["It is made of dead cells", "It carries water only", "It transports food in both directions using energy", "It works only at night"], answer: 2, why: "Translocation through the living phloem moves food from leaves to wherever it is needed — upward or downward — and requires ATP." },
  ],
};
