import type { Chapter } from "@/lib/types";

export const ch07: Chapter = {
  slug: "control-and-coordination",
  num: 7,
  title: "Control and Coordination",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · 25 marks",
  minutes: 22,
  blurb: "Two messaging systems — one electrical and instant, one chemical and slow — and why a body needs both.",
  bigIdea: "Nerves send fast messages down wires to specific places. Hormones send slow messages through the bloodstream to everywhere at once. Speed versus reach — that trade-off explains the whole chapter.",
  syllabus: [
    "Tropic movements in plants", "Introduction to plant hormones",
    "Control and co-ordination in animals: nervous system",
    "Voluntary, involuntary and reflex action",
    "Chemical co-ordination: animal hormones",
  ],
  blocks: [
    { t: "h", text: "Plants: movement without muscles" },
    { t: "p", html: "A plant has no muscles and no nerves, yet a sunflower tracks the sun and a touch-me-not folds the instant you poke it. Plants manage this in two quite different ways." },
    { t: "compare",
      left: { title: "Nastic — independent of direction", items: [
        "The response has no relation to the direction of the stimulus",
        "Fast — seconds",
        "Caused by <strong>water moving out of cells</strong>, not by growth",
        "Not permanent — the leaf reopens later",
        "Example: <em>Mimosa pudica</em> (touch-me-not) folding on touch",
      ] },
      right: { title: "Tropic — directional", items: [
        "The plant grows <em>towards</em> or <em>away from</em> the stimulus",
        "Slow — hours or days",
        "Caused by <strong>uneven growth</strong>: cells on one side elongate more",
        "Permanent — the bend stays",
        "Example: a shoot bending towards light",
      ] } },
    { t: "sim", id: "plant-tropism" },
    { t: "table", head: ["Tropism", "Stimulus", "Shoot", "Root"], rows: [
      ["Phototropism", "Light", "Positive — grows towards", "Negative — grows away"],
      ["Geotropism", "Gravity", "Negative — grows up", "Positive — grows down"],
      ["Hydrotropism", "Water", "—", "Positive — grows towards water"],
      ["Chemotropism", "Chemicals", "Pollen tube grows towards the ovule", "—"],
      ["Thigmotropism", "Touch", "Tendrils coil around a support", "—"],
    ] },
    { t: "note", kind: "why", title: "How does auxin bend a shoot?", html: "When light falls on one side, the hormone auxin diffuses to the <strong>shaded</strong> side. Auxin makes cells elongate, so the shaded side grows longer than the lit side — and a longer side on one edge makes the whole shoot curve towards the light. Nothing is 'reaching' for anything; it is pure geometry." },
    { t: "table", head: ["Plant hormone", "What it does"], rows: [
      ["<strong>Auxin</strong>", "Cell elongation; responsible for phototropism and geotropism"],
      ["<strong>Gibberellin</strong>", "Stem growth; helps seeds germinate"],
      ["<strong>Cytokinin</strong>", "Promotes cell division; abundant in fruits and seeds"],
      ["<strong>Abscisic acid</strong>", "Inhibits growth; causes wilting and leaf fall — the 'stress' hormone"],
    ] },
    { t: "note", kind: "memory", html: "Three promote, one inhibits. <strong>A</strong>bscisic acid is the <strong>A</strong>nti-growth one — everything else builds." },

    { t: "h", text: "The nervous system" },
    { t: "p", html: "A <strong>neuron</strong> is the longest cell in your body and is built for one job: carrying a signal in one direction." },
    { t: "list", ordered: true, items: [
      "<strong>Dendrites</strong> pick up the information at the receiving end.",
      "The signal travels as an electrical impulse along the <strong>axon</strong>.",
      "At the axon's end the electrical signal triggers the release of chemicals (<strong>neurotransmitters</strong>).",
      "Those chemicals cross the tiny gap — the <strong>synapse</strong> — and start a fresh electrical impulse in the next neuron.",
    ] },
    { t: "note", kind: "idea", html: "Why bother converting electrical → chemical → electrical at every junction? Because the synapse is a one-way valve. Chemicals are released on one side only, so the impulse can never run backwards. It is also where the body can decide whether to pass a message on at all." },
    { t: "sim", id: "reflex-arc" },
    { t: "p", html: "Three kinds of action, and the difference is <em>who decides</em>:" },
    { t: "table", head: ["Type", "Controlled by", "Under your will?", "Example"], rows: [
      ["<strong>Voluntary</strong>", "Cerebrum (fore-brain)", "Yes", "Writing, walking, speaking"],
      ["<strong>Involuntary</strong>", "Medulla (hind-brain)", "No", "Heartbeat, breathing, digestion, blood pressure"],
      ["<strong>Reflex</strong>", "Spinal cord", "No — brain informed afterwards", "Pulling your hand off a hot pan, blinking, knee jerk"],
    ] },
    { t: "note", kind: "why", title: "Why do reflexes bypass the brain?", html: "Thinking is slow. Sending the signal all the way to the brain, deciding, and sending it back would take long enough to burn your hand. The spinal cord acts as a local shortcut so the response happens in milliseconds — and only <em>then</em> does the brain find out." },

    { t: "h", text: "The three parts of the brain" },
    { t: "table", head: ["Part", "Region", "In charge of"], rows: [
      ["<strong>Cerebrum</strong>", "Fore-brain", "Thinking, memory, reasoning, and all voluntary action. Also receives sensory impulses — hearing, smell, sight"],
      ["<strong>Cerebellum</strong>", "Hind-brain", "Balance and precision of voluntary movement — picking up a pencil without knocking it over"],
      ["<strong>Medulla oblongata</strong>", "Hind-brain", "Involuntary actions: heartbeat, breathing, blood pressure, vomiting, salivation"],
      ["<strong>Pons</strong>", "Hind-brain", "Regulates breathing"],
      ["<strong>Hypothalamus</strong>", "Fore-brain", "Hunger, thirst, body temperature; controls the pituitary gland"],
    ] },
    { t: "note", kind: "exam", html: "The brain sits inside the skull, cushioned by cerebrospinal fluid inside three membranes; the spinal cord runs inside the vertebral column. Both protection questions come up regularly." },
    { t: "note", kind: "trap", html: "A very common one-mark trap: which part controls <em>balance</em>? Cerebellum. Which controls <em>heartbeat</em>? Medulla. Do not swap them." },

    { t: "h", text: "Hormones — the slow, wide broadcast" },
    { t: "p", html: "The nervous system is fast but its reach is limited to where nerves go, and nerve cells need recovery time before they can fire again. For messages that must reach every cell and keep working for hours or years, the body uses chemicals released straight into the blood." },
    { t: "table", head: ["Gland", "Hormone", "What it does", "If it goes wrong"], rows: [
      ["Pituitary", "Growth hormone", "Controls growth of the body", "Too little → dwarfism; too much → gigantism"],
      ["Thyroid", "Thyroxine", "Regulates carbohydrate, protein and fat metabolism", "Needs iodine — deficiency causes goitre"],
      ["Pancreas", "Insulin", "Lowers blood sugar", "Too little → blood sugar stays high (diabetes)"],
      ["Adrenal", "Adrenaline", "Prepares the body for emergency — heart races, breathing quickens, blood diverted to muscles", "The 'fight or flight' response"],
      ["Testis", "Testosterone", "Male secondary sexual characters", "—"],
      ["Ovary", "Oestrogen", "Female secondary sexual characters", "—"],
    ] },
    { t: "note", kind: "real", html: "That jolt when a bike nearly hits you — pounding heart, dry mouth, shaking hands — is adrenaline, released in seconds. Blood is redirected away from the digestive system towards skeletal muscles, which is exactly why you cannot eat when you are frightened." },
    { t: "note", kind: "why", title: "Why is iodised salt sold everywhere in India?", html: "The thyroid gland cannot make thyroxine without iodine. In regions where the soil and water are low in iodine, deficiency leads to goitre — a visible swelling of the neck. Adding iodine to common salt was the simplest way to reach an entire population." },
    { t: "note", kind: "idea", title: "Feedback control", html: "Hormones are not released constantly. When blood sugar rises, the pancreas releases insulin; as sugar falls, insulin release drops. This self-correcting loop is called <strong>feedback control</strong>, and it is how the body keeps everything within safe limits." },

    { t: "steps", title: "Compare the nervous and hormonal systems in a way that earns full marks.",
      intro: "Do not just list features — pair them so each line contrasts.",
      steps: [
        "<strong>Signal type:</strong> nervous = electrical impulse along neurons; hormonal = chemical carried in blood.",
        "<strong>Speed:</strong> nervous is almost instant; hormonal is slow, taking seconds to years.",
        "<strong>Reach:</strong> nervous reaches only where nerves go; hormonal reaches every cell the blood touches.",
        "<strong>Duration:</strong> nervous effect is brief; hormonal effect is long-lasting.",
        "<strong>Recovery:</strong> a neuron needs time before it can fire again — so nerves alone cannot maintain a steady, continuous state. Hormones can.",
      ],
      answer: "Nerves are for fast, targeted, short-lived responses; hormones are for slow, widespread, sustained control. A body needs both.",
    },
  ],
  formulas: [],
  examFocus: [
    "Nastic vs tropic movement — the touch-me-not vs the bending shoot, with the growth/water distinction.",
    "How auxin causes phototropism — the shaded side elongates.",
    "The four plant hormones and one function each.",
    "Neuron structure with dendrite, axon, synapse labelled, and why the synapse makes transmission one-way.",
    "Reflex arc pathway in order, and why it bypasses the brain.",
    "Cerebrum, cerebellum and medulla — do not confuse balance with heartbeat.",
    "The gland–hormone–function table, especially thyroxine/iodine and insulin/diabetes.",
    "A five-point comparison of nervous and hormonal coordination.",
  ],
  flashcards: [
    { q: "Differentiate between nastic and tropic movements.", a: "Nastic movements are non-directional, fast, caused by water leaving cells, and reversible (touch-me-not). Tropic movements are directional, slow, caused by unequal growth, and permanent (shoot bending to light)." },
    { q: "How does auxin cause a shoot to bend towards light?", a: "Auxin diffuses to the shaded side of the shoot. It makes those cells elongate more than the lit side, so the shoot curves towards the light." },
    { q: "Name the four plant hormones and their main function.", a: "Auxin — cell elongation. Gibberellin — stem growth and germination. Cytokinin — cell division. Abscisic acid — inhibits growth, causes wilting and leaf fall." },
    { q: "What is a synapse and why is it important?", a: "The tiny gap between two neurons. The electrical impulse triggers release of chemicals which cross the gap and start a new impulse. Because chemicals are released on one side only, transmission is one-way." },
    { q: "Define a reflex action and give the pathway.", a: "A rapid, automatic response to a stimulus, controlled by the spinal cord. Pathway: receptor → sensory neuron → spinal cord (relay neuron) → motor neuron → effector muscle." },
    { q: "Why do reflex actions not involve the brain?", a: "Sending the signal to the brain and back would take too long. The spinal cord provides a shortcut so the response happens in milliseconds; the brain is informed afterwards." },
    { q: "Which part of the brain controls balance and posture?", a: "The cerebellum, in the hind-brain. It also makes voluntary movements precise." },
    { q: "Which part of the brain controls heartbeat and breathing?", a: "The medulla oblongata, in the hind-brain. It controls involuntary actions such as heartbeat, breathing, blood pressure and vomiting." },
    { q: "How is the brain protected?", a: "It sits inside the bony skull, surrounded by three membranes, with cerebrospinal fluid between them that cushions it against shock." },
    { q: "Why is iodine essential in our diet?", a: "The thyroid gland needs iodine to make thyroxine, which regulates metabolism. Deficiency causes goitre — swelling of the thyroid in the neck." },
    { q: "What does adrenaline do in an emergency?", a: "Heart beats faster, breathing rate rises, and blood is diverted from the digestive system to skeletal muscles — preparing the body to fight or flee." },
    { q: "What is feedback control of hormones?", a: "The amount of hormone released is regulated by the effect it produces. When blood sugar rises, insulin is released; as sugar falls, insulin release decreases automatically." },
    { q: "Give four differences between nervous and hormonal coordination.", a: "Nervous: electrical, very fast, targeted, short-lived. Hormonal: chemical, slow, reaches all cells via blood, long-lasting." },
    { q: "Name the tropism shown by a pollen tube growing towards the ovule.", a: "Chemotropism — growth in response to a chemical stimulus." },
  ],
  quiz: [
    { q: "The folding of touch-me-not leaves on being touched is:", options: ["Phototropism", "A nastic movement", "Geotropism", "A growth movement"], answer: 1, why: "It is fast, non-directional and caused by water leaving the cells rather than by growth — so it is a nastic movement, not a tropism." },
    { q: "Roots growing downward show:", options: ["Positive phototropism", "Negative geotropism", "Positive geotropism", "Hydrotropism only"], answer: 2, why: "Roots grow towards gravity, which is positive geotropism. Shoots grow away from it — negative geotropism." },
    { q: "Which plant hormone inhibits growth?", options: ["Auxin", "Cytokinin", "Gibberellin", "Abscisic acid"], answer: 3, why: "Abscisic acid is the growth inhibitor; it causes wilting and leaf fall. The other three promote growth." },
    { q: "The gap between two neurons is called the:", options: ["Axon", "Dendrite", "Synapse", "Nerve ending"], answer: 2, why: "The synapse is the junction where chemicals carry the signal from one neuron to the next, ensuring one-way transmission." },
    { q: "The correct reflex arc pathway is:", options: ["Receptor → motor neuron → spinal cord → sensory neuron → muscle", "Receptor → sensory neuron → spinal cord → motor neuron → muscle", "Receptor → brain → spinal cord → muscle", "Muscle → sensory neuron → brain → receptor"], answer: 1, why: "Sensory neurons carry the message in, the spinal cord relays it, and motor neurons carry the command out to the effector muscle." },
    { q: "Salivation on seeing food is controlled by the:", options: ["Cerebellum", "Medulla", "Cerebrum", "Spinal cord"], answer: 1, why: "Salivation, like heartbeat and breathing, is an involuntary action controlled by the medulla oblongata." },
    { q: "A person is unable to walk in a straight line. The affected part is likely to be the:", options: ["Cerebrum", "Cerebellum", "Medulla", "Pons"], answer: 1, why: "The cerebellum maintains balance and posture and gives precision to voluntary movement." },
    { q: "Deficiency of which hormone causes diabetes?", options: ["Thyroxine", "Adrenaline", "Insulin", "Growth hormone"], answer: 2, why: "Insulin from the pancreas lowers blood sugar. Insufficient insulin leaves blood sugar levels high." },
    { q: "Excess secretion of growth hormone in childhood causes:", options: ["Dwarfism", "Gigantism", "Goitre", "Diabetes"], answer: 1, why: "Too much growth hormone from the pituitary in the growing years causes gigantism; too little causes dwarfism." },
    { q: "Which of these is the main advantage of hormonal over nervous control?", options: ["It is faster", "It reaches all cells and its effect lasts long", "It uses less energy", "It works only in plants"], answer: 1, why: "Hormones travel in blood, so they reach every cell, and their effect persists — useful for slow, sustained processes like growth." },
    { q: "Cerebrospinal fluid protects the brain by:", options: ["Supplying oxygen", "Acting as a shock absorber", "Producing hormones", "Carrying impulses"], answer: 1, why: "It fills the space between the three membranes around the brain and cushions it against mechanical shock." },
    { q: "Tendrils of a pea plant coiling around a stick is an example of:", options: ["Chemotropism", "Hydrotropism", "Thigmotropism", "Geotropism"], answer: 2, why: "Growth in response to touch is thigmotropism. The side away from the support grows faster, curling the tendril around it." },
  ],
};
