import type { Chapter } from "@/lib/types";

export const ch08: Chapter = {
  slug: "how-do-organisms-reproduce",
  num: 8,
  title: "How do Organisms Reproduce?",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · 25 marks",
  minutes: 24,
  blurb: "Copying versus mixing — why some organisms make identical children and others go to enormous trouble not to.",
  bigIdea: "Reproduction is really about copying DNA. Copy it exactly and you get identical offspring; combine DNA from two individuals and you get variation — and variation is what lets a species survive when the world changes.",
  syllabus: [
    "Reproduction in animals and plants (asexual and sexual)",
    "Need for and methods of family planning",
    "Safe sex vs HIV/AIDS", "Child bearing and women's health",
  ],
  blocks: [
    { t: "h", text: "Why reproduce at all?" },
    { t: "p", html: "An individual organism does not need to reproduce to stay alive. Reproduction is not for the individual — it is for the <strong>species</strong>. And at its core it is a DNA-copying process." },
    { t: "note", kind: "idea", html: "DNA copying is never perfect. Small mistakes creep in, and those mistakes are <strong>variations</strong>. Most are useless, some are harmful — but occasionally one turns out to be useful when conditions change. A population with no variation at all has no way of surviving a new disease or a change in temperature." },

    { t: "h", text: "Asexual reproduction — one parent, identical children" },
    { t: "table", head: ["Method", "Organism", "What happens"], rows: [
      ["<strong>Fission</strong> — binary", "Amoeba, Leishmania, bacteria", "The cell splits into two. In Leishmania it always splits along the length of its whip-like flagellum"],
      ["<strong>Fission</strong> — multiple", "Plasmodium (malaria parasite)", "Splits into many daughter cells at once"],
      ["<strong>Budding</strong>", "Yeast, Hydra", "A small bud grows out of the parent, then detaches"],
      ["<strong>Fragmentation</strong>", "Spirogyra", "The filament breaks into pieces, each of which grows into a new individual"],
      ["<strong>Regeneration</strong>", "Planaria, Hydra", "A cut piece can regrow the entire organism. Not the same as reproduction — you cannot cut a person in half and get two"],
      ["<strong>Spore formation</strong>", "Rhizopus (bread mould)", "Thread-like hyphae with sporangia at the tips release thousands of tough spores"],
      ["<strong>Vegetative propagation</strong>", "Potato, sugarcane, rose, Bryophyllum", "New plants from roots, stems or leaves — no seed involved"],
    ] },
    { t: "note", kind: "real", html: "Bryophyllum leaves grow tiny plantlets right on their notched edges. Drop a leaf on damp soil and you get a row of new plants — which is why gardeners never need seeds for it." },
    { t: "note", kind: "why", title: "Why do farmers use vegetative propagation?", html: "Three reasons the board wants: plants are genetically identical to the parent so quality is guaranteed; they flower and fruit much earlier than seed-grown plants; and plants that produce no viable seeds (banana, orange, jasmine) can only be grown this way. <strong>Tissue culture</strong> takes this further — thousands of plants from a few cells." },

    { t: "h", text: "Sexual reproduction in flowering plants" },
    { t: "sim", id: "flower-anatomy" },
    { t: "p", html: "A flower is a reproductive organ, and its four whorls each have a job. <strong>Stamen</strong> (anther + filament) is the male part and makes pollen. <strong>Carpel or pistil</strong> (stigma, style, ovary) is the female part and holds the ovules." },
    { t: "list", ordered: true, items: [
      "<strong>Pollination</strong> — pollen is transferred to the stigma. <em>Self-pollination</em> is within the same flower; <em>cross-pollination</em> is between two flowers, carried by wind, water or insects.",
      "<strong>Germination of the pollen grain</strong> — it grows a pollen tube down through the style towards the ovule (this is chemotropism).",
      "<strong>Fertilisation</strong> — the male germ cell fuses with the female germ cell inside the ovule, forming a <strong>zygote</strong>.",
      "<strong>After fertilisation</strong> — the zygote becomes the embryo, the ovule becomes the <strong>seed</strong>, and the ovary becomes the <strong>fruit</strong>. Petals, sepals, stamens and stigma usually wither and fall.",
    ] },
    { t: "note", kind: "memory", html: "Two lines that answer half the questions in this section: <strong>ovule → seed</strong>, <strong>ovary → fruit</strong>. Germination then needs water, air and a suitable temperature." },

    { t: "h", text: "Reproduction in human beings" },
    { t: "p", html: "The reproductive system does three things: makes the germ cells, brings them together, and — in the female — provides the environment for the embryo to develop." },
    { t: "table", head: ["Structure", "Function"], rows: [
      ["<strong>Testes</strong>", "Produce sperm and the hormone testosterone. Located outside the abdomen in the scrotum because sperm formation needs a temperature slightly lower than body temperature"],
      ["<strong>Vas deferens</strong>", "Carries sperm from the testes"],
      ["<strong>Prostate and seminal vesicles</strong>", "Add fluid that nourishes the sperm and makes them easier to transport — sperm plus this fluid is semen"],
      ["<strong>Ovaries</strong>", "Produce ova (eggs) and the hormones oestrogen and progesterone. A girl is born with all her immature eggs already present"],
      ["<strong>Fallopian tube (oviduct)</strong>", "Carries the egg towards the uterus. Fertilisation, if it happens, occurs here"],
      ["<strong>Uterus</strong>", "Where the embryo implants and develops"],
      ["<strong>Placenta</strong>", "A disc-like tissue connecting the embryo to the uterine wall. Nutrients and oxygen pass from mother to embryo; waste passes back"],
    ] },
    { t: "p", html: "Every month one egg is released and the uterus lining thickens in preparation. If the egg is not fertilised, the lining is not needed and is shed along with blood and mucus — this is <strong>menstruation</strong>, lasting about 2–8 days and repeating roughly every 28 days." },
    { t: "note", kind: "exam", html: "Puberty is when the reproductive organs mature. Common secondary sexual characters asked for: in boys, deepening of voice, facial and body hair, broader shoulders; in girls, breast development, widening of hips, onset of menstruation. Both: growth of hair in armpits and genital area, oily skin, growth spurt." },

    { t: "h", text: "Reproductive health" },
    { t: "p", html: "The syllabus treats this as a health topic, and the questions are factual." },
    { t: "list", items: [
      "<strong>Why family planning matters.</strong> India's population is large and growing; spacing births protects the health of the mother and improves the care each child receives. Frequent pregnancies leave a woman's body little time to recover.",
      "<strong>Barrier methods</strong> — condoms. They prevent the sperm reaching the egg, and are the only method that also protects against sexually transmitted infections.",
      "<strong>Hormonal methods</strong> — oral pills change the hormone balance so that eggs are not released. They can have side effects and should be taken on medical advice.",
      "<strong>Intra-uterine devices</strong> — a copper-T or loop placed in the uterus prevents implantation.",
      "<strong>Surgical methods</strong> — vasectomy in males (the vas deferens is blocked) and tubectomy in females (the fallopian tube is blocked). These are permanent.",
    ] },
    { t: "note", kind: "idea", title: "Sexually transmitted infections", html: "Bacterial infections such as gonorrhoea and syphilis, and viral infections including HIV/AIDS and warts, spread through sexual contact. HIV attacks the immune system so the body can no longer fight ordinary infections. There is no cure, so prevention matters: using condoms, avoiding shared needles, and screening donated blood. Casual contact — sharing food, hugging, using the same toilet — does <strong>not</strong> spread HIV." },
    { t: "note", kind: "trap", html: "Female foeticide — determining the sex of an unborn child and terminating female pregnancies — is illegal in India, and prenatal sex determination is banned by law. It has badly skewed the child sex ratio in several states. This appears as a value-based question." },

    { t: "steps", title: "Compare asexual and sexual reproduction, and say which is better.",
      intro: "A five-mark question. The trick is to answer the 'which is better' part honestly — neither is, and you should say why.",
      steps: [
        "<strong>Parents:</strong> asexual needs one; sexual needs two (or two germ cells).",
        "<strong>Germ cells:</strong> asexual involves none; sexual involves fusion of male and female gametes.",
        "<strong>Offspring:</strong> asexual gives genetically identical copies; sexual gives offspring with a new combination of DNA.",
        "<strong>Speed:</strong> asexual is much faster and needs no partner — a huge advantage in a stable environment.",
        "<strong>Variation:</strong> sexual creates variation, which is the raw material of evolution. If the environment changes, at least some individuals may survive.",
      ],
      answer: "Neither is 'better'. Asexual wins on speed and certainty in a stable environment; sexual wins on adaptability when conditions change — which is why long-lived, complex organisms almost all reproduce sexually.",
    },
  ],
  formulas: [],
  examFocus: [
    "Matching each asexual method to the right organism — Leishmania, Plasmodium, Spirogyra, Planaria, Rhizopus.",
    "Why regeneration is not the same as reproduction.",
    "Three advantages of vegetative propagation.",
    "A labelled flower diagram, and the ovule → seed, ovary → fruit rule.",
    "Why the testes lie outside the abdominal cavity.",
    "Functions of the placenta.",
    "Contraceptive methods grouped as barrier, hormonal, IUD and surgical, with one example each.",
    "Prevention of HIV/AIDS, and how it is <em>not</em> transmitted.",
  ],
  flashcards: [
    { q: "Why is DNA copying essential in reproduction?", a: "DNA carries the information for building the body. Reproduction is fundamentally the process of copying that DNA so the offspring can build a similar organism." },
    { q: "How do variations arise, and why do they matter?", a: "DNA copying is not perfectly accurate, so small changes appear. Variations allow at least some individuals in a population to survive if the environment changes — they are the basis of evolution." },
    { q: "How does Leishmania reproduce?", a: "By binary fission, which occurs in a definite orientation — along the length of the cell relative to its whip-like flagellum." },
    { q: "What is multiple fission? Give an example.", a: "A single cell divides into many daughter cells simultaneously. Plasmodium, the malarial parasite, reproduces this way." },
    { q: "How does Rhizopus reproduce?", a: "By spore formation. Thread-like hyphae bear sporangia (knob-like structures) which contain thousands of spores; each spore can grow into a new individual when it lands in a moist place." },
    { q: "Why is regeneration not considered reproduction?", a: "Regeneration is the regrowing of a lost part or a whole organism from a cut piece by specialised cells. It is not the normal way the organism multiplies, and complex organisms cannot do it." },
    { q: "Give three advantages of vegetative propagation.", a: "Offspring are genetically identical to the parent so desirable qualities are retained; plants flower and bear fruit earlier; plants that do not produce viable seeds (banana, orange, jasmine) can still be grown." },
    { q: "Name the male and female reproductive parts of a flower.", a: "Male: stamen, made of anther and filament — produces pollen. Female: carpel or pistil, made of stigma, style and ovary — contains the ovules." },
    { q: "What happens to the ovule and ovary after fertilisation?", a: "The ovule develops into the seed and the ovary develops into the fruit. The zygote becomes the embryo. Petals, sepals, stamens and stigma usually wither and fall off." },
    { q: "Why are the testes located outside the abdominal cavity?", a: "Sperm formation requires a temperature slightly lower than normal body temperature, which the scrotum provides." },
    { q: "What are the functions of the placenta?", a: "It connects the embryo to the mother's uterine wall. Glucose and oxygen pass from mother to embryo through it, and waste produced by the embryo passes back into the mother's blood." },
    { q: "What is menstruation and why does it occur?", a: "Each month the uterus lining thickens to receive a fertilised egg. If fertilisation does not occur, the lining is not needed and is shed along with blood and mucus over about 2–8 days." },
    { q: "Name four types of contraceptive method with one example each.", a: "Barrier — condoms. Hormonal — oral pills. Intra-uterine device — copper-T. Surgical — vasectomy in males, tubectomy in females." },
    { q: "Which contraceptive method also prevents sexually transmitted infections?", a: "Barrier methods, specifically condoms, since they physically prevent contact and transfer of body fluids." },
    { q: "How can the spread of HIV be prevented?", a: "Using condoms, avoiding shared needles, screening donated blood, and preventing transmission from mother to child through medical care. HIV does not spread through casual contact such as sharing food or hugging." },
  ],
  quiz: [
    { q: "Binary fission in a definite orientation along the flagellum is seen in:", options: ["Amoeba", "Leishmania", "Plasmodium", "Yeast"], answer: 1, why: "Leishmania has a whip-like flagellum at one end and always splits lengthwise along it. Amoeba splits in any plane." },
    { q: "Plasmodium reproduces by:", options: ["Budding", "Binary fission", "Multiple fission", "Fragmentation"], answer: 2, why: "The malarial parasite divides into many daughter cells at once — multiple fission." },
    { q: "Which of these is NOT a method of asexual reproduction?", options: ["Budding", "Fragmentation", "Fertilisation", "Spore formation"], answer: 2, why: "Fertilisation is the fusion of male and female gametes, which is the defining step of sexual reproduction." },
    { q: "Bananas and oranges are propagated vegetatively because:", options: ["It is cheaper", "They do not produce viable seeds", "Their seeds take too long", "They cannot be pollinated"], answer: 1, why: "These plants have lost the ability to produce viable seeds, so vegetative propagation is the only practical way to grow them." },
    { q: "After fertilisation in a flower, the ovary develops into the:", options: ["Seed", "Embryo", "Fruit", "Endosperm"], answer: 2, why: "The ovule becomes the seed and the ovary becomes the fruit. Remember them as a pair." },
    { q: "The pollen tube grows towards the ovule. This is an example of:", options: ["Phototropism", "Chemotropism", "Geotropism", "Hydrotropism"], answer: 1, why: "Growth in response to a chemical stimulus released by the ovule is chemotropism." },
    { q: "Fertilisation in humans normally takes place in the:", options: ["Uterus", "Ovary", "Fallopian tube", "Vagina"], answer: 2, why: "The sperm meets the egg in the fallopian tube (oviduct). The fertilised egg then travels to the uterus and implants there." },
    { q: "The placenta allows:", options: ["Only oxygen to pass", "Nutrients and oxygen in, waste out", "Blood of mother and child to mix freely", "Only hormones to pass"], answer: 1, why: "It is the exchange surface: glucose and oxygen pass to the embryo and waste passes back. The two blood supplies do not mix." },
    { q: "A copper-T is an example of a:", options: ["Barrier method", "Hormonal method", "Intra-uterine device", "Surgical method"], answer: 2, why: "It is placed inside the uterus and prevents implantation — an intra-uterine contraceptive device." },
    { q: "Vasectomy involves blocking the:", options: ["Fallopian tube", "Vas deferens", "Urethra", "Ureter"], answer: 1, why: "In vasectomy the vas deferens is cut and tied so sperm cannot travel. In females the equivalent, tubectomy, blocks the fallopian tube." },
    { q: "HIV/AIDS is NOT transmitted by:", options: ["Shared needles", "Unscreened blood transfusion", "Sharing food and hugging", "Mother to child"], answer: 2, why: "HIV spreads through blood and certain body fluids, not through casual social contact such as eating together or hugging." },
    { q: "The main advantage of sexual over asexual reproduction is that it:", options: ["Is faster", "Needs only one parent", "Produces variation", "Requires less energy"], answer: 2, why: "Combining DNA from two parents creates new combinations. That variation is what allows a species to adapt when conditions change." },
  ],
  keyTopics: [
    { name: "Human reproductive system — male and female organs and their functions", importance: "high", note: "A labelled diagram of the male or female reproductive system, with functions of key parts, is one of the most reliable 5-markers in this chapter." },
    { name: "Modes of asexual reproduction matched to organisms", importance: "high", note: "Fission, budding, fragmentation, regeneration and spore formation — matching the method to the right organism (Leishmania, Plasmodium, Spirogyra, Planaria, Rhizopus) is tested every year." },
    { name: "Sexual reproduction in flowering plants — pollination and fertilisation", importance: "high", note: "A labelled flower diagram and the ovule→seed, ovary→fruit rule are frequently combined into a 5-mark diagram question." },
    { name: "Contraceptive methods — barrier, hormonal, IUD, surgical", importance: "high", note: "Categorising methods with an example of each, and identifying which also prevents STIs, is a recurring 3-mark question." },
    { name: "Menstrual cycle, fertilisation and events after it", importance: "medium", note: "Short-answer questions on why menstruation occurs and what happens if the egg is fertilised." },
    { name: "Puberty and secondary sexual characters", importance: "medium", note: "Listing changes in boys/girls at puberty — a straightforward 2–3 mark recall question." },
    { name: "STI/HIV-AIDS prevention", importance: "medium", note: "A value-based question on how HIV spreads and does not spread." },
    { name: "Vegetative propagation and its advantages", importance: "low", note: "Naming examples and giving reasons farmers use it — a common 2–3 mark question." },
  ],
  written: [
    { q: "Define fertilisation.", marks: 1, kind: "short", importance: "medium",
      answer: "The fusion of a male germ cell (sperm/pollen tube's male gamete) with a female germ cell (egg/ovum) to form a zygote." },
    { q: "Name the part of the human female reproductive system where fertilisation normally occurs.", marks: 1, kind: "short", importance: "high",
      answer: "The <strong>fallopian tube (oviduct)</strong>." },
    { q: "Differentiate between pollination and fertilisation.", marks: 2, kind: "short", importance: "high", years: "2019",
      answer: "<strong>Pollination</strong> is the transfer of pollen grains from the anther to the stigma of a flower. <strong>Fertilisation</strong> is a later event — the fusion of the male germ cell (from the pollen tube) with the female germ cell inside the ovule, forming a zygote. Pollination must happen before fertilisation can occur." },
    { q: "Why are the testes located outside the abdominal cavity, in the scrotum?", marks: 2, kind: "short", importance: "high", years: "2017",
      answer: "Formation of healthy sperm requires a temperature <strong>slightly lower</strong> than normal body temperature. The scrotum, being outside the abdomen, provides this cooler environment, which the inside of the body cannot." },
    { q: "State two reasons why family planning and spacing of births are important for a country like India.", marks: 2, kind: "short", importance: "medium",
      answer: "It protects the <strong>health of the mother</strong>, since frequent pregnancies leave little time for her body to recover; and it allows each child to receive <strong>adequate care, nutrition and attention</strong>, which is harder when births are too closely spaced in a large population." },
    { q: "Explain any three advantages of vegetative propagation for farmers, with examples.", marks: 3, kind: "short", importance: "medium", years: "2018",
      answer: "<strong>(i)</strong> Offspring are genetically identical to the parent, so desirable qualities of a good variety are reliably retained (e.g. sugarcane, potato). <strong>(ii)</strong> Plants raised this way flower and bear fruit earlier than seed-grown plants. <strong>(iii)</strong> Plants that produce no viable seeds, such as banana, orange and jasmine, can only be propagated this way. Modern <strong>tissue culture</strong> extends this to produce thousands of identical plants from just a few cells." },
    { q: "Differentiate between asexual and sexual reproduction under any three heads.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Number of parents:</strong> asexual needs one; sexual needs two (or fusion of two gametes).<br><strong>Germ cells:</strong> asexual involves no fusion of gametes; sexual involves fusion of male and female germ cells.<br><strong>Offspring:</strong> asexual produces genetically identical copies of the parent; sexual produces offspring with new combinations of DNA, giving variation." },
    { q: "List the various methods of contraception under barrier, hormonal, intra-uterine and surgical categories, giving one example of each. Which of these also prevents sexually transmitted infections?", marks: 3, kind: "short", importance: "high", years: "2020",
      answer: "<strong>Barrier</strong> — condoms. <strong>Hormonal</strong> — oral contraceptive pills. <strong>Intra-uterine device</strong> — copper-T/loop. <strong>Surgical</strong> — vasectomy (male) and tubectomy (female). Only the <strong>barrier method (condom)</strong> also prevents the spread of sexually transmitted infections, including HIV, since it physically blocks the exchange of body fluids." },
    { q: "List the changes that occur in the human body at puberty in both boys and girls (secondary sexual characters).", marks: 3, kind: "short", importance: "medium",
      answer: "<strong>Common to both:</strong> growth spurt, hair in armpits and pubic region, oily skin/acne.<br><strong>In boys:</strong> deepening of voice, growth of facial and body hair, broadening of shoulders and chest.<br><strong>In girls:</strong> development of breasts, widening of hips, onset of menstruation." },
    { q: "Draw a labelled longitudinal section of a bisexual flower and describe the events that take place after fertilisation.", marks: 5, kind: "diagram", importance: "high", years: "2016, 2013",
      answer: "<strong>Diagram:</strong> show the four whorls — outer sepals and petals, the <strong>stamen</strong> (anther + filament) as the male part, and the <strong>carpel/pistil</strong> (stigma, style, ovary containing ovules) as the female part.<br><strong>After fertilisation:</strong> the zygote develops into the <strong>embryo</strong>; the ovule develops into the <strong>seed</strong>; the ovary develops into the <strong>fruit</strong>, its wall becoming the fruit wall (pericarp). The petals, sepals, stamens and stigma usually wither and fall off, since they are no longer needed." },
    { q: "Draw a labelled diagram of the human male reproductive system, and describe the functions of the testes, vas deferens and seminal vesicles.", marks: 5, kind: "diagram", importance: "high", years: "2015",
      answer: "<strong>Diagram:</strong> show a testis inside the scrotum, connected by the vas deferens which loops up and joins the urethra, with the prostate gland and seminal vesicles opening into this path, and the urethra running through the penis.<br><strong>Functions:</strong> the <strong>testes</strong> produce sperm and the hormone testosterone. The <strong>vas deferens</strong> carries sperm from the testes towards the urethra. The <strong>seminal vesicles</strong> (along with the prostate) secrete fluid that nourishes the sperm and makes them easier to transport; this fluid together with the sperm makes up semen." },
    { q: "Describe the sequence of events in the human female reproductive system from the release of an egg to either menstruation or the beginning of pregnancy.", marks: 5, kind: "long", importance: "high",
      answer: "Every month, one of the <strong>ovaries</strong> releases a mature egg, and at the same time the lining of the <strong>uterus</strong> becomes thick and spongy in preparation to receive a fertilised egg, with an increased blood supply.<br>If the egg travelling down the fallopian tube is <strong>fertilised</strong> by a sperm, it implants in the uterine lining, and further changes are triggered to sustain the growing embryo — the <strong>placenta</strong> forms and pregnancy continues.<br>If the egg is <strong>not fertilised</strong>, the thickened uterine lining is no longer needed. It breaks down and is shed, along with blood and mucus, through the vagina — this is <strong>menstruation</strong>, occurring roughly every 28 days and lasting about 2–8 days." },
  ],
  assertionReason: [
    { assertion: "The testes are situated outside the abdominal cavity, inside the scrotum.",
      reason: "Sperm formation requires a temperature slightly lower than normal body temperature.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A: the scrotum keeps the testes a little cooler than the rest of the body, which is essential for healthy sperm production." },
    { assertion: "Bananas, oranges and jasmine are commercially grown only by vegetative propagation.",
      reason: "These plants do not produce seeds capable of germinating into new, viable plants.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R is the correct reason: since these plants cannot be reliably grown from seed, vegetative propagation (cuttings, grafting, etc.) is the only practical method used." },
    { assertion: "The sex of a child is determined by the father, not the mother.",
      reason: "A male child receives his X chromosome from his father.",
      answer: 2, importance: "high", years: "2023",
      why: "A is true — since every egg carries an X and sperm carry either X or Y, it is the father's contribution that decides whether the child is XX (girl) or XY (boy). But R is false: a <em>male</em> child is XY, and he receives his <strong>Y</strong> chromosome from his father and his <strong>X</strong> chromosome from his mother, not the other way round." },
    { assertion: "Regeneration, as seen in Planaria, is considered a normal mode of reproduction in that organism.",
      reason: "Regeneration allows a complete new organism to grow from a cut fragment through the activity of specialised cells.",
      answer: 3, importance: "medium",
      why: "R is true — regeneration does work this way in organisms like Planaria and Hydra. But A is false: regeneration is a repair/regrowth ability, not the organism's normal, everyday way of multiplying, and it is quite different from processes like binary fission or budding that are true reproduction." },
  ],
  caseStudies: [
    { title: "Producing a hybrid seed variety", importance: "high",
      source: "A plant breeder wants to cross-pollinate a high-yield wheat variety (as the female parent) with a disease-resistant variety (as the male parent). Before the flower buds of the female parent open, the breeder carefully removes all the anthers with forceps, and then covers the flower with a paper or muslin bag. A day later, pollen collected from the disease-resistant variety is dusted onto the stigma, and the bag is put back on.",
      caption: "Based on standard emasculation-and-bagging technique used in plant breeding.",
      parts: [
        { q: "Why does the breeder remove the anthers from the female parent's flower before it opens?", marks: 1, answer: "To prevent <strong>self-pollination</strong> — if left in place, the flower's own pollen could fertilise its own stigma before the breeder can introduce pollen from the other variety." },
        { q: "Why is the flower covered with a bag both before and after pollen is applied?", marks: 1, answer: "To prevent <strong>unwanted pollen</strong> (carried by wind, insects or other plants) from reaching the stigma, ensuring only the pollen deliberately applied by the breeder fertilises the flower." },
        { q: "What type of pollination has been artificially carried out here?", marks: 1, answer: "<strong>Cross-pollination</strong> — pollen was transferred from the flower of one plant to the stigma of a flower on a genetically different plant." },
        { q: "After the pollen lands on the stigma, name the two events that must occur before a seed can form.", marks: 2, answer: "First, the pollen grain <strong>germinates</strong> and grows a pollen tube down through the style towards the ovule. Then <strong>fertilisation</strong> occurs — the male germ cell fuses with the female germ cell in the ovule to form a zygote, which develops into the embryo, while the ovule becomes the seed." },
      ] },
    { title: "Choosing a contraceptive method", importance: "medium",
      source: "A newly married couple visits a family planning clinic and is given information on different contraceptive options:<br><table><thead><tr><th>Method</th><th>Category</th><th>How it works</th></tr></thead><tbody><tr><td>Condom</td><td>Barrier</td><td>Prevents sperm from reaching the egg</td></tr><tr><td>Oral pill</td><td>Hormonal</td><td>Alters hormone balance so eggs are not released</td></tr><tr><td>Copper-T</td><td>Intra-uterine device</td><td>Prevents implantation in the uterus</td></tr></tbody></table>",
      parts: [
        { q: "Which of the three methods listed would you recommend if the couple also wants protection from sexually transmitted infections, and why?", marks: 2, answer: "The <strong>condom</strong> (barrier method), because it is the only one of the three that physically prevents the exchange of body fluids during intercourse, so it also blocks the transmission of infections such as HIV, in addition to preventing pregnancy." },
        { q: "Name one surgical method of contraception for males and one for females.", marks: 2, answer: "<strong>Vasectomy</strong> in males (the vas deferens is cut and blocked) and <strong>tubectomy</strong> in females (the fallopian tube is cut and blocked)." },
      ] },
  ],
};
