import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "heredity",
  num: 9,
  title: "Heredity",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · 25 marks",
  minutes: 18,
  blurb: "How a trait can vanish in one generation and reappear in the next — and why a father decides the sex of the child.",
  bigIdea: "You get one copy of every gene from each parent. A trait that does not show up is not gone — it is simply being outvoted by the other copy.",
  syllabus: [
    "Heredity", "Mendel's contribution — laws for inheritance of traits",
    "Sex determination — a brief introduction",
  ],
  blocks: [
    { t: "h", text: "Why Mendel picked pea plants" },
    { t: "p", html: "Gregor Mendel, a monk working in a monastery garden in the 1860s, chose the garden pea for reasons that were entirely practical — and that is why his experiments worked when everyone else's had failed." },
    { t: "list", items: [
      "Peas have clearly <strong>contrasting traits</strong> — tall or dwarf, round or wrinkled, with nothing in between.",
      "They are normally <strong>self-pollinating</strong>, so he could get pure lines, but he could also cross-pollinate them by hand when he wanted.",
      "They have a <strong>short life cycle</strong>, so he could see many generations quickly.",
      "They produce plenty of offspring, so his numbers were large enough to see ratios clearly.",
    ] },
    { t: "note", kind: "idea", html: "The real breakthrough was that Mendel <strong>counted</strong>. Others had done crosses before; he was the first to treat the results as numbers and notice the ratios — 3:1, and later 9:3:3:1." },

    { t: "h", text: "The monohybrid cross" },
    { t: "p", html: "Mendel crossed a pure tall plant (TT) with a pure dwarf plant (tt). Every single plant in the first generation, F₁, was tall. The dwarf trait had vanished." },
    { t: "p", html: "Then he let the F₁ plants self-pollinate. In F₂ the dwarf plants came back — in a ratio of about three tall to one dwarf." },
    { t: "sim", id: "punnett-square" },
    { t: "note", kind: "idea", title: "What that proves", html: "The dwarf trait was never destroyed. It was carried, silently, through the F₁ generation. So each plant must hold <strong>two copies</strong> of the factor for height, one from each parent — and when the two differ, one of them decides the appearance. That copy is <strong>dominant</strong>; the hidden one is <strong>recessive</strong>." },
    { t: "table", head: ["Term", "Meaning"], rows: [
      ["<strong>Gene</strong>", "A section of DNA carrying the information for one trait"],
      ["<strong>Allele</strong>", "One of the alternative forms of a gene — T and t are alleles"],
      ["<strong>Genotype</strong>", "The pair of alleles present — TT, Tt or tt"],
      ["<strong>Phenotype</strong>", "What you actually see — tall or dwarf"],
      ["<strong>Homozygous</strong>", "Both alleles the same — TT or tt (also called pure)"],
      ["<strong>Heterozygous</strong>", "Two different alleles — Tt (also called hybrid)"],
    ] },
    { t: "note", kind: "trap", html: "The <strong>3:1 ratio is the phenotype ratio</strong>. The genotype ratio in F₂ is <strong>1 TT : 2 Tt : 1 tt</strong>. Questions often ask for one and students give the other." },

    { t: "h", text: "The dihybrid cross — where the real insight is" },
    { t: "p", html: "Mendel then followed two traits at once: seed shape (round R / wrinkled r) and seed colour (yellow Y / green y). He crossed RRYY with rryy. All of F₁ was round and yellow, as expected." },
    { t: "p", html: "In F₂ he got four types — and crucially, two of them were combinations that neither grandparent had: round-green and wrinkled-yellow." },
    { t: "table", head: ["F₂ phenotype", "Number out of 16"], rows: [
      ["Round, yellow", "9"],
      ["Round, green", "3"],
      ["Wrinkled, yellow", "3"],
      ["Wrinkled, green", "1"],
    ] },
    { t: "note", kind: "why", title: "What 9:3:3:1 really tells you", html: "New combinations appeared. That means the gene for shape and the gene for colour are inherited <strong>independently</strong> of each other — inheriting 'round' does not oblige you to inherit 'yellow'. This is Mendel's law of independent assortment, and it is the reason siblings can look so different." },
    { t: "list", ordered: true, items: [
      "<strong>Law of dominance</strong> — when two contrasting alleles are present, only the dominant one is expressed.",
      "<strong>Law of segregation</strong> — the two alleles of a pair separate during gamete formation, so each gamete gets only one.",
      "<strong>Law of independent assortment</strong> — alleles of different traits are distributed to gametes independently of one another.",
    ] },

    { t: "h", text: "Sex determination in humans" },
    { t: "p", html: "Humans have 23 pairs of chromosomes. Twenty-two pairs are the same in everyone; the twenty-third pair is the <strong>sex chromosomes</strong>." },
    { t: "list", items: [
      "A female has two X chromosomes (XX). Every egg she produces therefore carries an <strong>X</strong>.",
      "A male has one X and one Y (XY). Half his sperm carry X and half carry Y.",
      "If an X-carrying sperm fertilises the egg → XX → girl. If a Y-carrying sperm does → XY → boy.",
    ] },
    { t: "note", kind: "idea", html: "It follows that the <strong>father determines the sex of the child</strong>, and that the chance is close to 50:50 every time. This is not opinion — it is arithmetic, and it is one of the most socially important facts in the Class X syllabus." },
    { t: "note", kind: "real", html: "In some species it is not genetic at all. In many turtles and crocodiles the temperature of the sand the eggs are buried in decides the sex. In snails an individual can change sex. Human XY determination is only one solution among many." },

    { t: "h", text: "Acquired and inherited traits" },
    { t: "compare",
      left: { title: "Inherited traits", items: [
        "Caused by a change in the <strong>germ cells</strong> (DNA)",
        "Passed to the next generation",
        "Example: eye colour, attached or free earlobes",
      ] },
      right: { title: "Acquired traits", items: [
        "Caused by changes in <strong>body cells</strong> during a lifetime",
        "<strong>Not</strong> passed on",
        "Example: a scar, muscles built at the gym, a learnt language",
      ] } },
    { t: "note", kind: "why", title: "The mice-tail experiment", html: "August Weismann cut the tails off mice for many generations. Every generation was still born with a full tail. Cutting a tail changes body cells, not germ cells — so the change cannot reach the next generation. This experiment is a standard three-mark answer." },

    { t: "steps", title: "A tall pea plant is crossed with a dwarf. All offspring are tall. What is the tall parent's genotype?",
      intro: "This is a test cross, and the logic runs backwards from the result.",
      steps: [
        "The dwarf parent must be <strong>tt</strong>, because dwarf is recessive and only shows when both alleles are recessive.",
        "So every gamete from the dwarf parent carries a <strong>t</strong>.",
        "If the tall parent were <strong>Tt</strong>, half the offspring would receive t from both sides and be dwarf — a 1:1 ratio.",
        "Since <em>every</em> offspring is tall, the tall parent must have given a T to all of them.",
      ],
      answer: "The tall parent is homozygous, TT. (This is exactly why a test cross with the recessive parent is used to find out whether an individual is pure or hybrid.)",
    },
  ],
  formulas: [
    { name: "Monohybrid F₂ phenotype ratio", expr: "3 : 1", note: "Genotype ratio is 1 TT : 2 Tt : 1 tt" },
    { name: "Dihybrid F₂ phenotype ratio", expr: "9 : 3 : 3 : 1", note: "Proves independent assortment of the two genes" },
    { name: "Human sex determination", expr: "Mother XX · Father XY → XX (girl) or XY (boy)", note: "The father's sperm decides; probability is close to 50%" },
  ],
  examFocus: [
    "Four reasons Mendel chose pea plants.",
    "The full monohybrid cross written out with a Punnett square, giving both phenotype and genotype ratios.",
    "The dihybrid 9:3:3:1 result and what the new combinations prove.",
    "The three laws, stated in one line each.",
    "Sex determination with a cross diagram, and the conclusion that the father determines the sex.",
    "Acquired vs inherited traits, with Weismann's mice experiment as the reason.",
  ],
  flashcards: [
    { q: "Why did Mendel choose the garden pea?", a: "It has clear contrasting traits, is normally self-pollinating but can be cross-pollinated by hand, has a short life cycle, and produces many offspring so ratios are visible." },
    { q: "Define genotype and phenotype.", a: "Genotype is the genetic make-up — the pair of alleles present (TT, Tt, tt). Phenotype is the observable characteristic — tall or dwarf." },
    { q: "What is the F₂ phenotype and genotype ratio in a monohybrid cross?", a: "Phenotype ratio 3 : 1 (three dominant to one recessive). Genotype ratio 1 TT : 2 Tt : 1 tt." },
    { q: "State the law of segregation.", a: "The two alleles of a trait separate from each other during gamete formation, so that each gamete receives only one allele of the pair." },
    { q: "State the law of independent assortment.", a: "Alleles of different traits are inherited independently of each other — inheriting one trait does not influence which version of another trait is inherited." },
    { q: "What does the 9:3:3:1 ratio prove?", a: "That two genes assort independently. New combinations appear in F₂ that were not present in either grandparent, so the two traits are not inherited together." },
    { q: "How is the sex of a human child determined?", a: "All eggs carry X. Sperm carry either X or Y. X sperm + egg → XX → girl. Y sperm + egg → XY → boy. So the father determines the sex of the child." },
    { q: "Why are the chances of a boy or a girl about 50%?", a: "Half of a father's sperm carry X and half carry Y, and either is equally likely to fertilise the egg." },
    { q: "Differentiate acquired and inherited traits with examples.", a: "Acquired traits arise in body cells during a lifetime and are not passed on — a scar, gym-built muscles. Inherited traits arise from changes in germ cells (DNA) and are passed to offspring — eye colour, earlobe shape." },
    { q: "Describe Weismann's experiment and its conclusion.", a: "He removed the tails of mice for many generations, yet every generation was born with tails. Cutting the tail changes body cells, not germ cells, so an acquired trait cannot be inherited." },
    { q: "What is a test cross?", a: "Crossing an individual showing the dominant trait with a homozygous recessive individual, to find out whether it is homozygous (all offspring dominant) or heterozygous (1:1 ratio)." },
    { q: "Define homozygous and heterozygous.", a: "Homozygous means both alleles are identical (TT or tt) — also called pure. Heterozygous means the two alleles differ (Tt) — also called hybrid." },
  ],
  quiz: [
    { q: "In a cross between TT and tt pea plants, the F₁ generation will be:", options: ["All dwarf", "All tall", "Half tall, half dwarf", "3 tall : 1 dwarf"], answer: 1, why: "Every F₁ plant is Tt. Since T (tall) is dominant, all appear tall — the dwarf allele is present but not expressed." },
    { q: "The genotype ratio in the F₂ generation of a monohybrid cross is:", options: ["3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1", "1 : 1"], answer: 1, why: "F₂ gives 1 TT : 2 Tt : 1 tt. The 3:1 ratio is the phenotype ratio, since TT and Tt both look tall." },
    { q: "The appearance of round-green and wrinkled-yellow seeds in F₂ shows that:", options: ["Genes are linked", "The two traits are inherited independently", "Mendel made an error", "Round is recessive"], answer: 1, why: "New combinations that neither grandparent had could only appear if shape and colour were assorted independently during gamete formation." },
    { q: "A woman's egg always carries:", options: ["An X chromosome", "A Y chromosome", "Either X or Y", "Neither"], answer: 0, why: "Females are XX, so every egg carries an X. Only sperm can carry a Y." },
    { q: "Which of these is an acquired trait?", options: ["Free earlobes", "Eye colour", "Weight lost by dieting", "Blood group"], answer: 2, why: "Weight change happens in body cells during a lifetime and is not passed to offspring. The others are determined by inherited DNA." },
    { q: "In Weismann's experiment, the mice born after 20 generations of tail removal had:", options: ["No tails", "Short tails", "Normal tails", "Tails only in males"], answer: 2, why: "Cutting the tail affects only body cells. Germ cell DNA is unchanged, so every generation was still born with a normal tail." },
    { q: "A pea plant with genotype Tt is described as:", options: ["Homozygous dominant", "Heterozygous", "Homozygous recessive", "Pure tall"], answer: 1, why: "Two different alleles are present, so it is heterozygous (hybrid). It looks tall because T is dominant." },
    { q: "The father determines the sex of the child because:", options: ["He is genetically stronger", "Only he produces Y-carrying gametes", "The mother's egg is passive", "Only he has 23 chromosomes"], answer: 1, why: "The mother can only give X. The father gives either X or Y, and that choice decides whether the child is XX or XY." },
    { q: "In a test cross, a tall plant is crossed with a dwarf and half the offspring are dwarf. The tall parent was:", options: ["TT", "Tt", "tt", "Cannot be determined"], answer: 1, why: "A 1:1 ratio means the tall parent contributed t half the time, so it must be heterozygous, Tt." },
    { q: "Mendel's law of dominance states that:", options: ["Both alleles are expressed equally", "Only the dominant allele is expressed when both are present", "Recessive alleles are destroyed", "Alleles blend together"], answer: 1, why: "When contrasting alleles are present, only the dominant one shows in the phenotype. The recessive one is carried unchanged." },
    { q: "In some turtles, the sex of the offspring is determined by:", options: ["The X and Y chromosomes", "The temperature at which eggs are incubated", "The size of the egg", "The mother's diet"], answer: 1, why: "Many reptiles use temperature-dependent sex determination rather than sex chromosomes." },
    { q: "How many pairs of chromosomes does a human being have?", options: ["21", "22", "23", "46"], answer: 2, why: "23 pairs — 22 pairs of autosomes plus one pair of sex chromosomes, giving 46 chromosomes in total." },
  ],
  keyTopics: [
    { name: "Monohybrid cross — Mendel's F1/F2 results, Punnett square, ratios", importance: "high", note: "Working out a Tt × Tt (or similar) cross with both genotype (1:2:1) and phenotype (3:1) ratios is one of the most repeated numericals in the whole subject." },
    { name: "Dihybrid cross — the 9:3:3:1 ratio and independent assortment", importance: "high", note: "Explaining why new combinations appear in F2 is a frequent 5-mark/case-study question." },
    { name: "Sex determination in humans — XX/XY mechanism", importance: "high", note: "A cross diagram plus the conclusion 'the father determines the child's sex' is tested almost every year, often as an assertion–reason or case study." },
    { name: "Mendel's three laws of inheritance", importance: "high", note: "Stating dominance, segregation and independent assortment accurately, each in one line, is a common 3–5 mark question." },
    { name: "Genotype, phenotype, homozygous, heterozygous — terminology", importance: "medium", note: "Definition-based 1–2 mark recall that underlies every genetics numerical." },
    { name: "Acquired vs inherited traits, Weismann's experiment", importance: "medium", note: "A reliable 2–3 mark reasoning question, often set as assertion–reason." },
    { name: "Test cross", importance: "medium", note: "Used to determine whether a dominant-phenotype individual is homozygous or heterozygous; a favourite reasoning-based numerical." },
    { name: "Why Mendel chose the garden pea", importance: "low", note: "A straightforward 2-mark recall question." },
  ],
  written: [
    { q: "Define an allele.", marks: 1, kind: "short", importance: "medium",
      answer: "One of the two or more alternative forms of a gene that occupy the same position on a chromosome and control the same trait, e.g. T (tall) and t (dwarf) are alleles for height in pea plants." },
    { q: "What is a test cross?", marks: 1, kind: "short", importance: "medium",
      answer: "A cross between an individual showing the dominant trait (of unknown genotype) and a homozygous recessive individual, done to find out whether the dominant individual is homozygous or heterozygous." },
    { q: "Differentiate between genotype and phenotype, with an example.", marks: 2, kind: "short", importance: "high", years: "2018",
      answer: "<strong>Genotype</strong> is the genetic make-up of an organism — the actual combination of alleles it carries (e.g. Tt). <strong>Phenotype</strong> is the observable physical characteristic that results from the genotype (e.g. tall). Two different genotypes, TT and Tt, can produce the <em>same</em> phenotype, tall." },
    { q: "State Mendel's law of dominance.", marks: 2, kind: "short", importance: "high",
      answer: "When an organism has two contrasting alleles for a trait, only the <strong>dominant</strong> allele expresses itself in the phenotype, while the <strong>recessive</strong> allele remains suppressed but is not destroyed and can reappear in later generations." },
    { q: "Give two reasons why Mendel selected the garden pea plant for his breeding experiments.", marks: 2, kind: "short", importance: "medium",
      answer: "The garden pea shows clear, easily distinguishable <strong>contrasting traits</strong> (e.g. tall/dwarf, round/wrinkled); and it is normally self-pollinating, which let Mendel maintain pure-breeding lines, while still allowing him to <strong>cross-pollinate it by hand</strong> whenever he wanted to perform a controlled cross." },
    { q: "Differentiate between homozygous and heterozygous genotypes, giving one example of each.", marks: 3, kind: "short", importance: "medium",
      answer: "A <strong>homozygous</strong> (or pure) genotype has two identical alleles for a trait, e.g. TT (pure tall) or tt (pure dwarf). A <strong>heterozygous</strong> (or hybrid) genotype has two different alleles, e.g. Tt — such a plant is tall in appearance because T is dominant, but it still carries the recessive t allele." },
    { q: "Differentiate between acquired and inherited traits, and describe Weismann's experiment that supports this distinction.", marks: 3, kind: "short", importance: "high", years: "2019",
      answer: "<strong>Inherited traits</strong> arise from changes in the DNA of germ cells and are passed on to offspring (e.g. eye colour). <strong>Acquired traits</strong> arise from changes in body cells during an individual's lifetime and are not passed on (e.g. a scar, muscles built through exercise).<br><strong>Weismann's experiment:</strong> he cut off the tails of mice for many successive generations, yet every generation was still born with a full-length tail — proving that a change confined to body cells cannot alter the DNA of germ cells, so it cannot be inherited." },
    { q: "Two heterozygous tall pea plants (Tt) are crossed. Using a Punnett square, work out the genotypic and phenotypic ratio of the offspring.", marks: 3, kind: "numerical", importance: "high", years: "2017, 2014",
      answer: "<strong>Cross:</strong> Tt × Tt. Gametes from each parent: T and t.<br><table><thead><tr><th>×</th><th>T</th><th>t</th></tr></thead><tbody><tr><th>T</th><td>TT</td><td>Tt</td></tr><tr><th>t</th><td>Tt</td><td>tt</td></tr></tbody></table><strong>Genotypic ratio:</strong> 1 TT : 2 Tt : 1 tt.<br><strong>Phenotypic ratio:</strong> 3 tall (TT + Tt) : 1 dwarf (tt), since T is dominant." },
    { q: "A tall pea plant of unknown genotype is crossed with a homozygous dwarf plant (tt), and the offspring are found to be 50% tall and 50% dwarf. What was the genotype of the tall parent? Show your reasoning.", marks: 3, kind: "numerical", importance: "high",
      answer: "Every gamete from the dwarf parent carries <strong>t</strong>. Since the offspring are tall and dwarf in a 1:1 ratio, the tall parent must be contributing T half the time and t the other half — which is only possible if the tall parent is <strong>heterozygous, Tt</strong>. (Tt × tt → 1 Tt (tall) : 1 tt (dwarf).) This is exactly the logic of a test cross." },
    { q: "State Mendel's three laws of inheritance, explaining each briefly with reference to his pea-plant experiments.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>1. Law of dominance:</strong> when two contrasting alleles are present together, only the dominant allele is expressed in the phenotype — seen in F1 of the Tt cross being entirely tall.<br><strong>2. Law of segregation:</strong> the two alleles of a gene pair separate from each other during the formation of gametes, so each gamete carries only one allele — this is why the recessive trait reappears in F2 (the 3:1 ratio).<br><strong>3. Law of independent assortment:</strong> when two traits are considered together, the alleles of one gene pair are distributed to gametes independently of the alleles of another gene pair — demonstrated by the appearance of new combinations (round-green, wrinkled-yellow) in Mendel's dihybrid cross, giving the 9:3:3:1 ratio." },
    { q: "A pea plant heterozygous for both seed shape and seed colour (RrYy, round & yellow) is self-pollinated. Work out the phenotypic ratio of the offspring for seed shape and seed colour, and state which law of inheritance this demonstrates.", marks: 5, kind: "numerical", importance: "high", years: "2024",
      answer: "<strong>Cross:</strong> RrYy × RrYy. Each parent produces four types of gametes in equal proportion: RY, Ry, rY, ry.<br>Combining these (16 possible fertilisations) gives four phenotypic classes:<br><table><thead><tr><th>Phenotype</th><th>Number out of 16</th></tr></thead><tbody><tr><td>Round, yellow</td><td>9</td></tr><tr><td>Round, green</td><td>3</td></tr><tr><td>Wrinkled, yellow</td><td>3</td></tr><tr><td>Wrinkled, green</td><td>1</td></tr></tbody></table><strong>Phenotypic ratio = 9 : 3 : 3 : 1.</strong> Two of these combinations (round-green, wrinkled-yellow) are new — not present in either original parent — which shows that the gene for shape and the gene for colour assort <strong>independently</strong> of each other. This demonstrates Mendel's <strong>law of independent assortment</strong>." },
    { q: "With the help of a cross/diagram, explain how the sex of a child is determined in human beings, and why the probability of having a boy or a girl is roughly equal.", marks: 5, kind: "diagram", importance: "high",
      answer: "<strong>Diagram:</strong> show the mother as XX producing all eggs carrying X, and the father as XY producing two types of sperm in equal number, X-carrying and Y-carrying. Show the fertilisation of the egg by either type of sperm leading to two possible outcomes.<br><table><thead><tr><th>Mother's egg ×</th><th>Father's sperm (X)</th><th>Father's sperm (Y)</th></tr></thead><tbody><tr><th>X</th><td>XX (girl)</td><td>XY (boy)</td></tr></tbody></table><strong>Explanation:</strong> a woman is XX, so every egg she produces carries an X chromosome. A man is XY, and produces X-bearing and Y-bearing sperm in equal numbers. If an X-bearing sperm fertilises the egg, the child is XX (girl); if a Y-bearing sperm does, the child is XY (boy). Since both kinds of sperm are equally likely to fertilise the egg, the probability of a boy or a girl in each pregnancy is close to <strong>50:50</strong>, and it is the <strong>father's</strong> genetic contribution that decides the outcome." },
  ],
  assertionReason: [
    { assertion: "A pea plant with the genotype Tt appears tall, not of intermediate height.",
      reason: "The allele T (tall) is dominant over the allele t (dwarf), so only its effect is expressed when both are present.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A: dominance means the heterozygote Tt shows the tall phenotype exactly like TT, with the recessive t allele present but not expressed." },
    { assertion: "The F2 generation of a monohybrid cross shows a phenotypic ratio of 3 : 1.",
      reason: "The genotypic ratio in the F2 generation of a monohybrid cross is also 3 : 1.",
      answer: 2, importance: "high",
      why: "A is true. But R is false: the genotypic ratio in F2 is <strong>1 TT : 2 Tt : 1 tt</strong>, not 3:1. It is only when TT and Tt are grouped together by their shared (dominant) appearance that the phenotypic ratio becomes 3:1." },
    { assertion: "New phenotype combinations such as round-green and wrinkled-yellow seeds appeared in the F2 generation of Mendel's dihybrid cross experiment.",
      reason: "The genes controlling seed shape and seed colour are distributed to gametes independently of each other.",
      answer: 0, importance: "high", years: "2024",
      why: "Both statements are true, and R correctly explains A: because the two genes assort independently during gamete formation, alleles can combine in new ways that were not present in either parent, producing the 9:3:3:1 ratio." },
    { assertion: "A bodybuilder's children are not born with unusually large muscles.",
      reason: "Changes that occur in the body cells of an organism during its lifetime do not alter the DNA of its germ cells.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R is the correct explanation: muscle growth from exercise is an acquired trait confined to body cells, so it cannot change the genetic information carried in sperm or egg cells, and is therefore not passed on to offspring." },
  ],
  caseStudies: [
    { title: "Counting a monohybrid cross", importance: "high",
      source: "A student crosses two pea plants that are both heterozygous for seed shape (Rr, round seeds) and grows 320 seeds from the cross to record their shape:<br><table><thead><tr><th>Phenotype</th><th>Number observed</th></tr></thead><tbody><tr><td>Round</td><td>243</td></tr><tr><td>Wrinkled</td><td>77</td></tr></tbody></table>",
      caption: "Based on Mendel's own classic seed-shape data (5474 round : 1850 wrinkled ≈ 2.96:1).",
      parts: [
        { q: "What phenotypic ratio does classical genetics predict for this cross, and does the student's data agree with it?", marks: 1, answer: "The predicted ratio is <strong>3 : 1</strong> (round : wrinkled). Out of 320, the expected numbers would be 240 round and 80 wrinkled — very close to the observed 243 and 77, so yes, the data agrees well with the prediction." },
        { q: "Write the genotypes of the two parent plants used in this cross.", marks: 1, answer: "Both parents are heterozygous: <strong>Rr</strong> (round seed shape, but carrying the recessive wrinkled allele)." },
        { q: "What is the expected genotypic ratio among the 320 offspring, and how many would be expected to be homozygous recessive?", marks: 2, answer: "The genotypic ratio is <strong>1 RR : 2 Rr : 1 rr</strong>. Homozygous recessive (rr) offspring — which appear wrinkled — would be expected to make up 1/4 of the total: 320 ÷ 4 = <strong>80</strong> plants, close to the 77 actually observed." },
        { q: "Name the scientist and the law that explains why the recessive (wrinkled) trait reappears in this generation after being absent in F1.", marks: 1, answer: "<strong>Gregor Mendel</strong>; explained by the <strong>law of segregation</strong> — the recessive allele was not lost in F1, only masked, and re-emerges when two recessive alleles come together again in F2." },
      ] },
    { title: "Whose 'fault' is it?", importance: "medium",
      source: "In a village, a woman who has had three daughters is pressured by relatives to have another child in the hope of a son, and is blamed for 'failing' to have a boy.",
      parts: [
        { q: "Scientifically, which parent's chromosomal contribution actually determines the sex of a child? Explain briefly.", marks: 2, answer: "The <strong>father</strong>. A woman is XX, so every egg she produces carries only an X chromosome. A man is XY, and produces both X-carrying and Y-carrying sperm in equal numbers; whichever type fertilises the egg decides whether the child is XX (girl) or XY (boy)." },
        { q: "Is it scientifically justified to blame the mother for the sex of her children? Give a reason.", marks: 1, answer: "No. Since the mother's egg always carries an X chromosome and cannot influence which type of sperm fertilises it, she has no biological control over the child's sex — the outcome depends entirely on the father's sperm." },
        { q: "Based on this, what would you say to the family to correct their understanding?", marks: 1, answer: "Explain that each pregnancy has close to an equal, independent 50:50 chance of being a boy or a girl, decided by the father's sperm, and that blaming the mother has no scientific basis — this understanding is also why sex-selective practices are both unscientific and illegal." },
      ] },
  ],
};
