import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "heredity",
  num: 9,
  title: "Heredity",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · 25 marks",
  minutes: 18,
  blurb: "How a trait can vanish in one generation and reappear in the next — and why a father decides the sex of the child.",
  bigIdea: "You get one copy of every gene from each parent. A trait that does not show up is not gone — it is simply being outvoted by the other copy.",
  syllabus: [
    "Heredity", "Mendel's contribution — laws for inheritance of traits",
    "Sex determination — a brief introduction",
  ],
  blocks: [
    { t: "h", text: "Why Mendel picked pea plants" },
    { t: "p", html: "Gregor Mendel, a monk working in a monastery garden in the 1860s, chose the garden pea for reasons that were entirely practical — and that is why his experiments worked when everyone else's had failed." },
    { t: "list", items: [
      "Peas have clearly <strong>contrasting traits</strong> — tall or dwarf, round or wrinkled, with nothing in between.",
      "They are normally <strong>self-pollinating</strong>, so he could get pure lines, but he could also cross-pollinate them by hand when he wanted.",
      "They have a <strong>short life cycle</strong>, so he could see many generations quickly.",
      "They produce plenty of offspring, so his numbers were large enough to see ratios clearly.",
    ] },
    { t: "note", kind: "idea", html: "The real breakthrough was that Mendel <strong>counted</strong>. Others had done crosses before; he was the first to treat the results as numbers and notice the ratios — 3:1, and later 9:3:3:1." },

    { t: "h", text: "The monohybrid cross" },
    { t: "p", html: "Mendel crossed a pure tall plant (TT) with a pure dwarf plant (tt). Every single plant in the first generation, F₁, was tall. The dwarf trait had vanished." },
    { t: "p", html: "Then he let the F₁ plants self-pollinate. In F₂ the dwarf plants came back — in a ratio of about three tall to one dwarf." },
    { t: "sim", id: "punnett-square" },
    { t: "note", kind: "idea", title: "What that proves", html: "The dwarf trait was never destroyed. It was carried, silently, through the F₁ generation. So each plant must hold <strong>two copies</strong> of the factor for height, one from each parent — and when the two differ, one of them decides the appearance. That copy is <strong>dominant</strong>; the hidden one is <strong>recessive</strong>." },
    { t: "table", head: ["Term", "Meaning"], rows: [
      ["<strong>Gene</strong>", "A section of DNA carrying the information for one trait"],
      ["<strong>Allele</strong>", "One of the alternative forms of a gene — T and t are alleles"],
      ["<strong>Genotype</strong>", "The pair of alleles present — TT, Tt or tt"],
      ["<strong>Phenotype</strong>", "What you actually see — tall or dwarf"],
      ["<strong>Homozygous</strong>", "Both alleles the same — TT or tt (also called pure)"],
      ["<strong>Heterozygous</strong>", "Two different alleles — Tt (also called hybrid)"],
    ] },
    { t: "note", kind: "trap", html: "The <strong>3:1 ratio is the phenotype ratio</strong>. The genotype ratio in F₂ is <strong>1 TT : 2 Tt : 1 tt</strong>. Questions often ask for one and students give the other." },

    { t: "h", text: "The dihybrid cross — where the real insight is" },
    { t: "p", html: "Mendel then followed two traits at once: seed shape (round R / wrinkled r) and seed colour (yellow Y / green y). He crossed RRYY with rryy. All of F₁ was round and yellow, as expected." },
    { t: "p", html: "In F₂ he got four types — and crucially, two of them were combinations that neither grandparent had: round-green and wrinkled-yellow." },
    { t: "table", head: ["F₂ phenotype", "Number out of 16"], rows: [
      ["Round, yellow", "9"],
      ["Round, green", "3"],
      ["Wrinkled, yellow", "3"],
      ["Wrinkled, green", "1"],
    ] },
    { t: "note", kind: "why", title: "What 9:3:3:1 really tells you", html: "New combinations appeared. That means the gene for shape and the gene for colour are inherited <strong>independently</strong> of each other — inheriting 'round' does not oblige you to inherit 'yellow'. This is Mendel's law of independent assortment, and it is the reason siblings can look so different." },
    { t: "list", ordered: true, items: [
      "<strong>Law of dominance</strong> — when two contrasting alleles are present, only the dominant one is expressed.",
      "<strong>Law of segregation</strong> — the two alleles of a pair separate during gamete formation, so each gamete gets only one.",
      "<strong>Law of independent assortment</strong> — alleles of different traits are distributed to gametes independently of one another.",
    ] },

    { t: "h", text: "Sex determination in humans" },
    { t: "p", html: "Humans have 23 pairs of chromosomes. Twenty-two pairs are the same in everyone; the twenty-third pair is the <strong>sex chromosomes</strong>." },
    { t: "list", items: [
      "A female has two X chromosomes (XX). Every egg she produces therefore carries an <strong>X</strong>.",
      "A male has one X and one Y (XY). Half his sperm carry X and half carry Y.",
      "If an X-carrying sperm fertilises the egg → XX → girl. If a Y-carrying sperm does → XY → boy.",
    ] },
    { t: "note", kind: "idea", html: "It follows that the <strong>father determines the sex of the child</strong>, and that the chance is close to 50:50 every time. This is not opinion — it is arithmetic, and it is one of the most socially important facts in the Class X syllabus." },
    { t: "note", kind: "real", html: "In some species it is not genetic at all. In many turtles and crocodiles the temperature of the sand the eggs are buried in decides the sex. In snails an individual can change sex. Human XY determination is only one solution among many." },

    { t: "h", text: "Acquired and inherited traits" },
    { t: "compare",
      left: { title: "Inherited traits", items: [
        "Caused by a change in the <strong>germ cells</strong> (DNA)",
        "Passed to the next generation",
        "Example: eye colour, attached or free earlobes",
      ] },
      right: { title: "Acquired traits", items: [
        "Caused by changes in <strong>body cells</strong> during a lifetime",
        "<strong>Not</strong> passed on",
        "Example: a scar, muscles built at the gym, a learnt language",
      ] } },
    { t: "note", kind: "why", title: "The mice-tail experiment", html: "August Weismann cut the tails off mice for many generations. Every generation was still born with a full tail. Cutting a tail changes body cells, not germ cells — so the change cannot reach the next generation. This experiment is a standard three-mark answer." },

    { t: "steps", title: "A tall pea plant is crossed with a dwarf. All offspring are tall. What is the tall parent's genotype?",
      intro: "This is a test cross, and the logic runs backwards from the result.",
      steps: [
        "The dwarf parent must be <strong>tt</strong>, because dwarf is recessive and only shows when both alleles are recessive.",
        "So every gamete from the dwarf parent carries a <strong>t</strong>.",
        "If the tall parent were <strong>Tt</strong>, half the offspring would receive t from both sides and be dwarf — a 1:1 ratio.",
        "Since <em>every</em> offspring is tall, the tall parent must have given a T to all of them.",
      ],
      answer: "The tall parent is homozygous, TT. (This is exactly why a test cross with the recessive parent is used to find out whether an individual is pure or hybrid.)",
    },
  ],
  formulas: [
    { name: "Monohybrid F₂ phenotype ratio", expr: "3 : 1", note: "Genotype ratio is 1 TT : 2 Tt : 1 tt" },
    { name: "Dihybrid F₂ phenotype ratio", expr: "9 : 3 : 3 : 1", note: "Proves independent assortment of the two genes" },
    { name: "Human sex determination", expr: "Mother XX · Father XY → XX (girl) or XY (boy)", note: "The father's sperm decides; probability is close to 50%" },
  ],
  examFocus: [
    "Four reasons Mendel chose pea plants.",
    "The full monohybrid cross written out with a Punnett square, giving both phenotype and genotype ratios.",
    "The dihybrid 9:3:3:1 result and what the new combinations prove.",
    "The three laws, stated in one line each.",
    "Sex determination with a cross diagram, and the conclusion that the father determines the sex.",
    "Acquired vs inherited traits, with Weismann's mice experiment as the reason.",
  ],
  flashcards: [
    { q: "Why did Mendel choose the garden pea?", a: "It has clear contrasting traits, is normally self-pollinating but can be cross-pollinated by hand, has a short life cycle, and produces many offspring so ratios are visible." },
    { q: "Define genotype and phenotype.", a: "Genotype is the genetic make-up — the pair of alleles present (TT, Tt, tt). Phenotype is the observable characteristic — tall or dwarf." },
    { q: "What is the F₂ phenotype and genotype ratio in a monohybrid cross?", a: "Phenotype ratio 3 : 1 (three dominant to one recessive). Genotype ratio 1 TT : 2 Tt : 1 tt." },
    { q: "State the law of segregation.", a: "The two alleles of a trait separate from each other during gamete formation, so that each gamete receives only one allele of the pair." },
    { q: "State the law of independent assortment.", a: "Alleles of different traits are inherited independently of each other — inheriting one trait does not influence which version of another trait is inherited." },
    { q: "What does the 9:3:3:1 ratio prove?", a: "That two genes assort independently. New combinations appear in F₂ that were not present in either grandparent, so the two traits are not inherited together." },
    { q: "How is the sex of a human child determined?", a: "All eggs carry X. Sperm carry either X or Y. X sperm + egg → XX → girl. Y sperm + egg → XY → boy. So the father determines the sex of the child." },
    { q: "Why are the chances of a boy or a girl about 50%?", a: "Half of a father's sperm carry X and half carry Y, and either is equally likely to fertilise the egg." },
    { q: "Differentiate acquired and inherited traits with examples.", a: "Acquired traits arise in body cells during a lifetime and are not passed on — a scar, gym-built muscles. Inherited traits arise from changes in germ cells (DNA) and are passed to offspring — eye colour, earlobe shape." },
    { q: "Describe Weismann's experiment and its conclusion.", a: "He removed the tails of mice for many generations, yet every generation was born with tails. Cutting the tail changes body cells, not germ cells, so an acquired trait cannot be inherited." },
    { q: "What is a test cross?", a: "Crossing an individual showing the dominant trait with a homozygous recessive individual, to find out whether it is homozygous (all offspring dominant) or heterozygous (1:1 ratio)." },
    { q: "Define homozygous and heterozygous.", a: "Homozygous means both alleles are identical (TT or tt) — also called pure. Heterozygous means the two alleles differ (Tt) — also called hybrid." },
  ],
  quiz: [
    { q: "In a cross between TT and tt pea plants, the F₁ generation will be:", options: ["All dwarf", "All tall", "Half tall, half dwarf", "3 tall : 1 dwarf"], answer: 1, why: "Every F₁ plant is Tt. Since T (tall) is dominant, all appear tall — the dwarf allele is present but not expressed." },
    { q: "The genotype ratio in the F₂ generation of a monohybrid cross is:", options: ["3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1", "1 : 1"], answer: 1, why: "F₂ gives 1 TT : 2 Tt : 1 tt. The 3:1 ratio is the phenotype ratio, since TT and Tt both look tall." },
    { q: "The appearance of round-green and wrinkled-yellow seeds in F₂ shows that:", options: ["Genes are linked", "The two traits are inherited independently", "Mendel made an error", "Round is recessive"], answer: 1, why: "New combinations that neither grandparent had could only appear if shape and colour were assorted independently during gamete formation." },
    { q: "A woman's egg always carries:", options: ["An X chromosome", "A Y chromosome", "Either X or Y", "Neither"], answer: 0, why: "Females are XX, so every egg carries an X. Only sperm can carry a Y." },
    { q: "Which of these is an acquired trait?", options: ["Free earlobes", "Eye colour", "Weight lost by dieting", "Blood group"], answer: 2, why: "Weight change happens in body cells during a lifetime and is not passed to offspring. The others are determined by inherited DNA." },
    { q: "In Weismann's experiment, the mice born after 20 generations of tail removal had:", options: ["No tails", "Short tails", "Normal tails", "Tails only in males"], answer: 2, why: "Cutting the tail affects only body cells. Germ cell DNA is unchanged, so every generation was still born with a normal tail." },
    { q: "A pea plant with genotype Tt is described as:", options: ["Homozygous dominant", "Heterozygous", "Homozygous recessive", "Pure tall"], answer: 1, why: "Two different alleles are present, so it is heterozygous (hybrid). It looks tall because T is dominant." },
    { q: "The father determines the sex of the child because:", options: ["He is genetically stronger", "Only he produces Y-carrying gametes", "The mother's egg is passive", "Only he has 23 chromosomes"], answer: 1, why: "The mother can only give X. The father gives either X or Y, and that choice decides whether the child is XX or XY." },
    { q: "In a test cross, a tall plant is crossed with a dwarf and half the offspring are dwarf. The tall parent was:", options: ["TT", "Tt", "tt", "Cannot be determined"], answer: 1, why: "A 1:1 ratio means the tall parent contributed t half the time, so it must be heterozygous, Tt." },
    { q: "Mendel's law of dominance states that:", options: ["Both alleles are expressed equally", "Only the dominant allele is expressed when both are present", "Recessive alleles are destroyed", "Alleles blend together"], answer: 1, why: "When contrasting alleles are present, only the dominant one shows in the phenotype. The recessive one is carried unchanged." },
    { q: "In some turtles, the sex of the offspring is determined by:", options: ["The X and Y chromosomes", "The temperature at which eggs are incubated", "The size of the egg", "The mother's diet"], answer: 1, why: "Many reptiles use temperature-dependent sex determination rather than sex chromosomes." },
    { q: "How many pairs of chromosomes does a human being have?", options: ["21", "22", "23", "46"], answer: 2, why: "23 pairs — 22 pairs of autosomes plus one pair of sex chromosomes, giving 46 chromosomes in total." },
  ],
};
