import type { Chapter } from "@/lib/types";

export const ch10: Chapter = {
  slug: "evolution",
  num: 10,
  title: "Evolution",
  unit: "biology",
  unitName: "World of the Living",
  marks: "Unit II · formative assessment only",
  formative: true,
  minutes: 18,
  blurb: "How a species becomes two, why a whale has hip bones, and what a fossil in a deeper rock layer tells you.",
  bigIdea: "Evolution is not organisms trying to improve. It is variation appearing by accident, and the environment quietly deciding which variations get to have children.",
  syllabus: [
    "Acquired and inherited traits", "Speciation",
    "Classification and evolution", "Fossils",
    "Evolution by stages", "Evolution should not be equated with progress",
    "Human evolution",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "About this chapter", html: "CBSE has placed Evolution under <strong>formative assessment only</strong> for 2026-27 — it will not appear in the year-end paper, but it may be assessed in periodic tests and portfolio work. It is also one of the most interesting ideas in the syllabus, so it is worth reading properly." },

    { t: "h", text: "Two ways a population can change" },
    { t: "p", html: "Imagine twelve red beetles in a bush. Their population grows. Two different things can happen — and the difference between them is the whole chapter." },
    { t: "sim", id: "natural-selection" },
    { t: "list", ordered: true, items: [
      "<strong>Natural selection.</strong> A green beetle appears by a chance variation. Crows eat beetles, but green ones are harder to spot on green leaves. Green beetles survive and reproduce more. Over generations, the population becomes mostly green. The environment did the selecting.",
      "<strong>Genetic drift.</strong> A blue beetle appears. Blue offers no advantage at all — but an elephant happens to crush most of the red beetles. The few survivors happen to include the blue one. The population becomes bluer purely by <em>accident</em>.",
    ] },
    { t: "note", kind: "idea", html: "Both change the gene frequency of the population. The difference: natural selection is driven by an advantage; genetic drift is driven by chance. Both are real, and both matter — this distinction is the most commonly examined part of the topic." },

    { t: "h", text: "Speciation — how one species becomes two" },
    { t: "p", html: "A <strong>species</strong> is a group whose members can interbreed and produce fertile offspring. Speciation happens when two populations of one species stop being able to do that." },
    { t: "list", ordered: true, items: [
      "A population gets split by a <strong>geographical barrier</strong> — a river changes course, a mountain rises, a group of birds is blown to an island.",
      "The two groups can no longer interbreed, so their gene pools stop mixing.",
      "Variations accumulate differently in each — by natural selection (different environments) and by genetic drift.",
      "Eventually the accumulated differences are so great that even if the barrier is removed, the two groups cannot interbreed successfully.",
      "They are now two separate species.",
    ] },
    { t: "note", kind: "trap", html: "Self-pollinating plants and asexually reproducing organisms are far less likely to speciate, because there is much less variation to work with. Geographical isolation does very little for a plant that fertilises itself." },

    { t: "h", text: "The evidence" },
    { t: "table", head: ["Type of evidence", "What it means", "Example"], rows: [
      ["<strong>Homologous organs</strong>", "Same basic structure and origin, different functions — so the species share a common ancestor", "The forelimb of a human, a bat's wing, a whale's flipper — the same bones, rearranged"],
      ["<strong>Analogous organs</strong>", "Different structure and origin, same function — no close ancestry, just the same problem solved twice", "A bat's wing (skin over bones) and an insect's wing (a fold of body wall)"],
      ["<strong>Fossils</strong>", "Preserved remains or impressions of organisms from the past", "<em>Archaeopteryx</em> has feathers and wings like a bird but teeth and a bony tail like a reptile"],
      ["<strong>Vestigial organs</strong>", "Structures that have lost their function but remain", "Human appendix, wisdom teeth, the tiny hip bones inside a whale"],
    ] },
    { t: "note", kind: "why", title: "How do you date a fossil?", html: "Two ways. First, <strong>depth</strong> — fossils in deeper layers of rock are older than those closer to the surface, because sediment builds up over time. Second, <strong>radioactive dating</strong> — measuring the ratio of certain isotopes in the fossil gives an actual age in years." },
    { t: "note", kind: "idea", html: "<em>Archaeopteryx</em> matters because it is a <strong>connecting link</strong>. It shows that birds are very likely descended from reptiles, and that big changes happen through intermediate forms rather than in one leap." },

    { t: "h", text: "Evolution happens in stages" },
    { t: "p", html: "A common objection: what use is half an eye? The answer is that intermediate stages are useful too, just for something simpler." },
    { t: "list", items: [
      "A flatworm has light-sensitive eye spots. They cannot form an image, but they tell the worm which way is up and where the shade is — which is genuinely useful.",
      "Feathers almost certainly first evolved for <strong>insulation</strong> in dinosaurs, not for flight. They were later co-opted for flying.",
      "The wild cabbage was bred by farmers into cabbage, cauliflower, broccoli, kohlrabi and kale — all from one species, by selecting different parts to grow larger. This is artificial selection, but it shows how far accumulated small changes can go.",
    ] },
    { t: "note", kind: "trap", title: "Evolution is not progress", html: "Bacteria have been around far longer than humans, exist in vastly greater numbers, and thrive in places we cannot survive a minute. Humans are not the 'top' of evolution — there is no top. Every species alive today is equally the current end of its own branch. This is a favourite reasoning question." },

    { t: "h", text: "Human evolution" },
    { t: "p", html: "All modern humans belong to a single species, <em>Homo sapiens</em>, which arose in Africa. From there our ancestors spread outwards in waves — moving, settling, moving again, sometimes returning." },
    { t: "note", kind: "idea", html: "The genetic evidence is clear on one point: there is no biological basis for dividing humans into distinct races. The variation <em>within</em> any human group is greater than the average variation <em>between</em> groups. We are one recently-separated species that has not had time to become anything else." },
    { t: "p", html: "The tools used to trace this history are <strong>excavated fossils</strong>, <strong>carbon dating</strong> of remains, studies of ancient tools and cave art, and — most powerfully — <strong>DNA sequencing</strong>, which lets us measure how closely two populations are related." },

    { t: "steps", title: "Explain how a new species could form from a population of beetles.",
      intro: "A five-mark question. Structure it as a sequence and name the mechanism at each step.",
      steps: [
        "A large population of beetles gets split into two by a <strong>geographical barrier</strong> — say a river changing course.",
        "The two sub-populations can no longer interbreed, so their <strong>gene pools become separated</strong>.",
        "Variations arise independently in each group through errors in DNA copying.",
        "<strong>Natural selection</strong> acts differently on each — the two sides of the river may have different predators, plants or climate.",
        "<strong>Genetic drift</strong> also changes gene frequencies by chance, especially if either group is small.",
        "Over many generations the differences accumulate until the two groups can no longer interbreed to produce fertile offspring — even if they meet again.",
      ],
      answer: "Geographical isolation → reproductive isolation → accumulated variation through natural selection and genetic drift → two distinct species.",
    },
  ],
  formulas: [],
  examFocus: [
    "Natural selection vs genetic drift — the beetle example makes the distinction easy to write.",
    "The five-step speciation sequence.",
    "Homologous vs analogous organs, with the correct examples on each side.",
    "Two methods of dating fossils.",
    "Why <em>Archaeopteryx</em> is important.",
    "Why evolution should not be equated with progress.",
    "Vestigial organs with three human examples.",
  ],
  flashcards: [
    { q: "Differentiate between natural selection and genetic drift.", a: "Natural selection changes gene frequency because a variation gives a survival advantage. Genetic drift changes it by pure chance — for example when accident wipes out most of a small population." },
    { q: "Define a species.", a: "A group of organisms whose members can interbreed with one another and produce fertile offspring." },
    { q: "What is speciation? Name the main factors.", a: "The formation of a new species from an existing one. Main factors: geographical isolation, genetic drift, natural selection acting differently on the two groups, and accumulation of variations until interbreeding is no longer possible." },
    { q: "Why does geographical isolation not cause speciation in self-pollinating plants?", a: "Self-pollination produces very little variation, so the separated populations do not accumulate enough genetic difference to become distinct species." },
    { q: "What are homologous organs? Give an example.", a: "Organs with the same basic structure and embryonic origin but different functions — evidence of a common ancestor. Example: the forelimbs of humans, bats, whales and lizards." },
    { q: "What are analogous organs? Give an example.", a: "Organs with different structure and origin but the same function. Example: the wing of a bat (skin over bones) and the wing of an insect (a fold of the body wall)." },
    { q: "Why is Archaeopteryx an important fossil?", a: "It has feathers and wings like a bird but teeth and a long bony tail like a reptile, so it is a connecting link showing that birds are closely related to reptiles." },
    { q: "How are fossils dated?", a: "By depth — fossils found in deeper layers of rock are older. And by radioactive dating, which measures the ratio of isotopes in the fossil to give an age in years." },
    { q: "What are vestigial organs? Give three human examples.", a: "Organs that have lost their original function but are still present. In humans: the appendix, wisdom teeth, and the muscles that move the ear." },
    { q: "Why should evolution not be equated with progress?", a: "There is no ladder with humans at the top. Bacteria are older, far more numerous, and survive in far harsher environments. Every living species is equally the current tip of its own branch." },
    { q: "Give an example of artificial selection.", a: "From wild cabbage, farmers selected for different features to produce cabbage, cauliflower, broccoli, kohlrabi and kale — all from one original species." },
    { q: "What does the study of human DNA tell us about race?", a: "All humans belong to one species that arose in Africa and spread out. Genetic variation within any group is greater than the average variation between groups, so there is no biological basis for distinct races." },
  ],
  quiz: [
    { q: "A population becomes mostly blue because an elephant crushed most of the red beetles. This is an example of:", options: ["Natural selection", "Genetic drift", "Speciation", "Artificial selection"], answer: 1, why: "The blue colour gave no survival advantage — the change happened purely by accident, which is genetic drift." },
    { q: "Which of these is a homologous pair?", options: ["Bat wing and insect wing", "Human arm and whale flipper", "Fish fin and dolphin flipper", "Potato tuber and sweet potato"], answer: 1, why: "The human arm and whale flipper have the same bone structure and embryonic origin but different functions — a hallmark of common ancestry." },
    { q: "Fossils found in deeper layers of the earth are:", options: ["Younger", "Older", "The same age", "Impossible to date"], answer: 1, why: "Sediment accumulates over time, so material buried deeper was laid down earlier and is older." },
    { q: "Archaeopteryx is considered a connecting link between:", options: ["Fish and amphibians", "Reptiles and birds", "Reptiles and mammals", "Amphibians and reptiles"], answer: 1, why: "It has bird-like feathers and wings alongside reptile-like teeth and a bony tail." },
    { q: "Which is a vestigial organ in humans?", options: ["Liver", "Appendix", "Kidney", "Pancreas"], answer: 1, why: "The appendix has lost its original digestive function in humans but is still present." },
    { q: "Cauliflower, broccoli and cabbage were all developed from:", options: ["Different wild species", "Wild cabbage, by artificial selection", "Genetic drift", "Random mutation alone"], answer: 1, why: "Farmers selected different parts of wild cabbage to enlarge — flower buds gave cauliflower and broccoli, the terminal bud gave cabbage." },
    { q: "Two populations become separate species when they:", options: ["Look different", "Live in different places", "Can no longer interbreed to give fertile offspring", "Have different diets"], answer: 2, why: "The defining test of a species is reproductive: members must be able to interbreed and produce fertile offspring." },
    { q: "The wing of a bat and the wing of a butterfly are:", options: ["Homologous", "Analogous", "Vestigial", "Identical"], answer: 1, why: "They perform the same function but have completely different structures and origins — analogous organs." },
    { q: "Which statement is correct?", options: ["Humans evolved from monkeys", "Humans and apes share a common ancestor", "Evolution always leads to more complex organisms", "Bacteria are less evolved than humans"], answer: 1, why: "Humans did not descend from present-day monkeys or apes; both descend from a shared ancestor. And evolution has no direction towards complexity." },
    { q: "Acquired traits are not inherited because they:", options: ["Are too small to matter", "Do not change the DNA of germ cells", "Occur only in adults", "Are always harmful"], answer: 1, why: "Changes in body cells cannot reach the germ cells, so they cannot be passed to the next generation — as Weismann's mice experiment showed." },
  ],
};
