import type { Chapter } from "@/lib/types";

export const ch11: Chapter = {
  slug: "light-reflection-and-refraction",
  num: 11,
  title: "Light — Reflection and Refraction",
  unit: "light",
  unitName: "Natural Phenomena — Light and Optics",
  marks: "Unit III · 12 marks",
  minutes: 28,
  blurb: "Mirrors, lenses, sign conventions and the two formulas that between them answer every numerical in the chapter.",
  bigIdea: "Light travels in straight lines until something makes it turn. A mirror bounces it back; a lens bends it as it passes through. Everything else — every image, every formula — follows from tracing where those straight lines end up.",
  syllabus: [
    "Reflection of light by curved surfaces", "Images formed by spherical mirrors",
    "Centre of curvature, principal axis, principal focus, focal length",
    "Mirror formula (derivation not required)", "Magnification",
    "Refraction, laws of refraction, refractive index",
    "Refraction of light by spherical lenses", "Image formation by lenses",
    "Lens formula (derivation not required)", "Magnification", "Power of a lens",
  ],
  blocks: [
    { t: "h", text: "The two laws of reflection" },
    { t: "list", ordered: true, items: [
      "The angle of incidence equals the angle of reflection: <strong>∠i = ∠r</strong>.",
      "The incident ray, the reflected ray and the normal at the point of incidence all lie in the <strong>same plane</strong>.",
    ] },
    { t: "note", kind: "exam", html: "These two laws hold for <em>every</em> reflecting surface — flat, curved, polished or rough. A rough wall obeys them too; it just has normals pointing in every direction, which is why it scatters light instead of forming an image." },

    { t: "h", text: "Spherical mirrors — the vocabulary" },
    { t: "list", items: [
      "<strong>Pole (P)</strong> — the centre of the reflecting surface.",
      "<strong>Centre of curvature (C)</strong> — the centre of the sphere the mirror is a part of.",
      "<strong>Radius of curvature (R)</strong> — the distance PC.",
      "<strong>Principal focus (F)</strong> — where rays parallel to the principal axis converge (concave) or appear to diverge from (convex).",
      "<strong>Focal length (f)</strong> — the distance PF. For a spherical mirror, <strong>f = R/2</strong>.",
    ] },
    { t: "sim", id: "mirror-ray" },
    { t: "note", kind: "idea", title: "The sign convention (New Cartesian)", html: "Put the pole at the origin, with light travelling from left to right. Then: distances measured <strong>against</strong> the incident light are <strong>negative</strong>; those measured along it are positive. Heights above the axis are positive, below it negative.<br><br>Consequences worth memorising: <strong>u is always negative</strong> (the object is always in front). <strong>f is negative for a concave mirror, positive for a convex mirror.</strong>" },
    { t: "note", kind: "trap", html: "Nearly every lost mark in this chapter is a sign error, not a physics error. Write down u, f and their signs <em>before</em> you touch the formula." },

    { t: "h", text: "Where the image goes — the six cases" },
    { t: "table", head: ["Object position", "Image position", "Nature", "Size"], rows: [
      ["At infinity", "At F", "Real, inverted", "Point-sized"],
      ["Beyond C", "Between F and C", "Real, inverted", "Diminished"],
      ["At C", "At C", "Real, inverted", "Same size"],
      ["Between C and F", "Beyond C", "Real, inverted", "Enlarged"],
      ["At F", "At infinity", "Real, inverted", "Highly enlarged"],
      ["Between F and P", "Behind the mirror", "<strong>Virtual, erect</strong>", "Enlarged"],
    ] },
    { t: "note", kind: "memory", html: "For a concave mirror there is only <strong>one</strong> virtual case — object between the pole and the focus. Everywhere else the image is real and inverted. A convex mirror is even simpler: the image is <em>always</em> virtual, erect and diminished, wherever you put the object." },
    { t: "note", kind: "real", html: "That is why a convex mirror is used as a vehicle's rear-view mirror: it always gives an erect image and covers a much wider field of view. The trade-off is that objects look smaller and therefore further away — hence the warning printed on it." },
    { t: "list", items: [
      "<strong>Concave mirror uses:</strong> torches, headlights and searchlights (a bulb at the focus gives a parallel beam); shaving mirrors and dentists' mirrors (enlarged erect image when the face is close); solar cookers and furnaces (concentrating sunlight at the focus).",
      "<strong>Convex mirror uses:</strong> rear-view mirrors on vehicles, and security mirrors at shop corners — both for the wide field of view.",
    ] },

    { t: "h", text: "The mirror formula" },
    { t: "formula", name: "Mirror formula", expr: "1/v + 1/u = 1/f",
      where: ["v = image distance from the pole", "u = object distance from the pole", "f = focal length, and f = R/2"] },
    { t: "formula", name: "Magnification (mirror)", expr: "m = h′/h = −v/u",
      where: ["h′ = image height, h = object height", "m negative → real and inverted", "m positive → virtual and erect", "|m| &gt; 1 → enlarged, |m| &lt; 1 → diminished"] },
    { t: "steps", title: "An object is placed 20 cm in front of a concave mirror of focal length 15 cm. Find the image.",
      intro: "The full method — signs first, then formula, then interpret.",
      steps: [
        "Write the signs: u = −20 cm, f = −15 cm (concave, so f is negative).",
        "Mirror formula: 1/v = 1/f − 1/u = (−1/15) − (−1/20) = −1/15 + 1/20.",
        "LCM is 60: (−4 + 3)/60 = −1/60, so <strong>v = −60 cm</strong>.",
        "v is negative, so the image is 60 cm in front of the mirror — it is <strong>real</strong>.",
        "Magnification: m = −v/u = −(−60)/(−20) = −3. Negative means inverted; |m| = 3 means three times larger.",
      ],
      answer: "Image is 60 cm in front of the mirror, real, inverted and three times enlarged.",
    },

    { t: "h", text: "Refraction — why light bends" },
    { t: "p", html: "Put a pencil in a glass of water and it looks broken at the surface. Look at a coin at the bottom of a bucket and it seems closer than it is. Both happen because light changes speed when it moves from one medium to another — and a change of speed at an angle means a change of direction." },
    { t: "sim", id: "refraction-slab" },
    { t: "list", ordered: true, items: [
      "The incident ray, the refracted ray and the normal all lie in the <strong>same plane</strong>.",
      "<strong>Snell's law:</strong> the ratio sin i / sin r is a constant for a given pair of media. That constant is the refractive index.",
    ] },
    { t: "formula", name: "Refractive index", expr: "n<sub>21</sub> = sin i / sin r = v₁ / v₂",
      where: ["v₁ = speed of light in medium 1", "v₂ = speed of light in medium 2", "absolute refractive index n = c / v, where c = 3 × 10⁸ m/s"] },
    { t: "note", kind: "memory", html: "<strong>Denser → bends towards the normal. Rarer → bends away from the normal.</strong> That single line lets you sketch any refraction diagram correctly, even before you calculate anything." },
    { t: "note", kind: "why", title: "Why does the pencil look bent?", html: "Light from the submerged part travels from water (denser) into air (rarer), so it bends away from the normal as it leaves. Your brain assumes light travelled in a straight line, so it traces the ray back to a point higher than the real one — and the pencil appears to break at the surface." },
    { t: "note", kind: "trap", html: "A light ray falling <strong>perpendicular</strong> to a surface (∠i = 0°) does <em>not</em> bend at all. Its speed still changes, but there is no sideways deflection. Students often draw a bend here and lose the mark." },

    { t: "h", text: "Lenses" },
    { t: "sim", id: "lens-ray" },
    { t: "p", html: "A convex lens is thicker in the middle and <strong>converges</strong> parallel light to a real focus. A concave lens is thinner in the middle and <strong>diverges</strong> it, so the rays only <em>appear</em> to come from a virtual focus." },
    { t: "note", kind: "idea", title: "Sign convention for lenses", html: "Same rules, with the optical centre O as origin. Key results: <strong>f is positive for a convex lens, negative for a concave lens.</strong> Object distance u is still negative. A positive v means a real image on the far side; a negative v means a virtual image on the same side as the object." },
    { t: "formula", name: "Lens formula", expr: "1/v − 1/u = 1/f", where: ["Note the minus sign — it is <strong>not</strong> the same as the mirror formula"] },
    { t: "formula", name: "Magnification (lens)", expr: "m = h′/h = v/u", where: ["No minus sign here either — again, different from the mirror"] },
    { t: "formula", name: "Power of a lens", expr: "P = 1 / f&nbsp;<span class='faint'>(f in metres)</span>",
      where: ["Unit is the dioptre, D", "Convex lens → positive power; concave lens → negative power", "Lenses in contact: P = P₁ + P₂ + …"] },
    { t: "note", kind: "trap", html: "The two pairs of formulas differ only by a sign, and that is exactly what the examiner is testing.<br><br><strong>Mirror:</strong> 1/v + 1/u = 1/f, m = −v/u<br><strong>Lens:</strong> 1/v − 1/u = 1/f, m = +v/u" },
    { t: "table", head: ["Object position (convex lens)", "Image position", "Nature and size"], rows: [
      ["At infinity", "At F₂", "Real, inverted, point-sized"],
      ["Beyond 2F₁", "Between F₂ and 2F₂", "Real, inverted, diminished"],
      ["At 2F₁", "At 2F₂", "Real, inverted, same size"],
      ["Between F₁ and 2F₁", "Beyond 2F₂", "Real, inverted, enlarged"],
      ["At F₁", "At infinity", "Real, inverted, highly enlarged"],
      ["Between F₁ and O", "Same side as object", "<strong>Virtual, erect, enlarged</strong>"],
    ] },
    { t: "note", kind: "real", html: "A concave lens always gives a virtual, erect, diminished image — exactly like a convex mirror. That is why it is used to correct myopia, and why a peephole in a door shows a small wide-angle view of the corridor." },

    { t: "steps", title: "A concave lens of focal length 15 cm forms an image 10 cm from the lens. Where is the object?",
      intro: "Work backwards. The signs are the whole battle.",
      steps: [
        "A concave lens always forms a virtual image on the same side as the object, so v = −10 cm. And f = −15 cm.",
        "Lens formula: 1/v − 1/u = 1/f, so 1/u = 1/v − 1/f.",
        "1/u = (−1/10) − (−1/15) = −1/10 + 1/15.",
        "LCM 30: (−3 + 2)/30 = −1/30, so <strong>u = −30 cm</strong>.",
        "Magnification m = v/u = (−10)/(−30) = +1/3 — positive, so erect, and one-third the size.",
      ],
      answer: "The object is 30 cm in front of the lens. The image is virtual, erect and one-third the size.",
    },
  ],
  formulas: [
    { name: "Laws of reflection", expr: "∠i = ∠r; incident ray, reflected ray and normal are coplanar" },
    { name: "Mirror formula", expr: "1/v + 1/u = 1/f", note: "f = R/2. Concave f negative, convex f positive." },
    { name: "Magnification (mirror)", expr: "m = h′/h = −v/u", note: "Negative m → real and inverted" },
    { name: "Snell's law", expr: "sin i / sin r = n₂₁ = v₁/v₂", note: "Constant for a given pair of media" },
    { name: "Absolute refractive index", expr: "n = c / v", note: "c = 3 × 10⁸ m/s in vacuum" },
    { name: "Lens formula", expr: "1/v − 1/u = 1/f", note: "Convex f positive, concave f negative" },
    { name: "Magnification (lens)", expr: "m = h′/h = v/u", note: "No minus sign, unlike the mirror" },
    { name: "Power of a lens", expr: "P = 1/f (f in metres)", note: "Unit: dioptre (D). For lenses in contact, P = P₁ + P₂" },
  ],
  examFocus: [
    "The New Cartesian sign convention — state it, then apply it before every calculation.",
    "The six-case table for a concave mirror, and the single-line rule for a convex mirror.",
    "Two uses each for concave and convex mirrors, with a reason.",
    "The two laws of refraction, including Snell's law with the constant named.",
    "Denser → towards the normal; rarer → away from it. Draw diagrams to match.",
    "Knowing that a perpendicular ray does not bend.",
    "The four formulas and, above all, the sign difference between mirror and lens.",
    "Power of a lens, its sign, and the addition rule for lenses in contact.",
  ],
  flashcards: [
    { q: "State the two laws of reflection.", a: "1) The angle of incidence equals the angle of reflection. 2) The incident ray, the reflected ray and the normal at the point of incidence all lie in the same plane." },
    { q: "What is the relationship between focal length and radius of curvature?", a: "f = R/2. The focus lies midway between the pole and the centre of curvature." },
    { q: "State the New Cartesian sign convention.", a: "The pole is the origin and light travels left to right. Distances measured in the direction of the incident light are positive, against it negative. Heights above the principal axis are positive, below it negative." },
    { q: "Write the mirror formula and the magnification formula.", a: "1/v + 1/u = 1/f, and m = h′/h = −v/u. A negative m means a real, inverted image." },
    { q: "When does a concave mirror form a virtual image?", a: "Only when the object is placed between the pole and the principal focus. The image is then virtual, erect and enlarged — as in a shaving mirror." },
    { q: "Why is a convex mirror used as a rear-view mirror?", a: "It always gives an erect, virtual, diminished image and has a much wider field of view, so the driver can see more traffic behind." },
    { q: "Why is a concave mirror used in a torch?", a: "The bulb is placed at the principal focus, so the reflected rays emerge parallel to the axis, giving a strong straight beam." },
    { q: "State the laws of refraction.", a: "1) The incident ray, refracted ray and normal lie in the same plane. 2) Snell's law: sin i / sin r is a constant for a given pair of media — the refractive index." },
    { q: "Define absolute refractive index.", a: "n = c/v, where c is the speed of light in vacuum (3 × 10⁸ m/s) and v is its speed in the medium. It tells you how much the medium slows light down." },
    { q: "What happens when light travels from a rarer to a denser medium?", a: "It slows down and bends towards the normal, so the angle of refraction is smaller than the angle of incidence." },
    { q: "Why does a ray falling perpendicular to a surface not bend?", a: "The angle of incidence is 0°, so there is no sideways component to deflect. The speed changes but the direction does not." },
    { q: "Write the lens formula and the lens magnification formula.", a: "1/v − 1/u = 1/f, and m = h′/h = v/u. Note the signs differ from the mirror versions." },
    { q: "Define the power of a lens and give its unit.", a: "P = 1/f, with f in metres. The unit is the dioptre (D). Convex lenses have positive power, concave lenses negative." },
    { q: "What kind of image does a concave lens always form?", a: "Virtual, erect and diminished, on the same side as the object — no matter where the object is placed." },
    { q: "Why does a pencil appear bent in a glass of water?", a: "Light from the submerged part bends away from the normal as it leaves the water. The eye traces the rays back in a straight line to a point higher than the actual one, so the pencil appears to break at the surface." },
  ],
  quiz: [
    { q: "The focal length of a spherical mirror of radius of curvature 30 cm is:", options: ["30 cm", "15 cm", "60 cm", "7.5 cm"], answer: 1, why: "f = R/2 = 30/2 = 15 cm." },
    { q: "An object is placed between the pole and the focus of a concave mirror. The image is:", options: ["Real, inverted, diminished", "Real, inverted, enlarged", "Virtual, erect, enlarged", "Virtual, inverted, diminished"], answer: 2, why: "This is the only case where a concave mirror gives a virtual image — erect and enlarged, which is how a shaving mirror works." },
    { q: "For a convex mirror, the magnification is always:", options: ["Negative and greater than 1", "Positive and less than 1", "Negative and less than 1", "Exactly 1"], answer: 1, why: "A convex mirror always gives a virtual (positive m), erect, diminished (|m| < 1) image, whatever the object distance." },
    { q: "In the New Cartesian sign convention, the object distance u is:", options: ["Always positive", "Always negative", "Positive for mirrors, negative for lenses", "Zero"], answer: 1, why: "The object is always placed in front, i.e. against the direction of incident light, so u is always negative." },
    { q: "An object 10 cm in front of a concave mirror of focal length 20 cm gives an image at:", options: ["v = −20 cm", "v = +20 cm", "v = −6.7 cm", "v = +6.7 cm"], answer: 1, why: "u = −10, f = −20. 1/v = 1/f − 1/u = −1/20 + 1/10 = 1/20, so v = +20 cm — a virtual image behind the mirror." },
    { q: "Light entering a glass slab from air:", options: ["Bends away from the normal", "Bends towards the normal", "Does not bend", "Reflects back"], answer: 1, why: "Glass is optically denser than air, so light slows down and bends towards the normal." },
    { q: "The refractive index of water is 1.33. The speed of light in water is about:", options: ["3 × 10⁸ m/s", "2.25 × 10⁸ m/s", "4 × 10⁸ m/s", "1.33 × 10⁸ m/s"], answer: 1, why: "n = c/v, so v = c/n = 3 × 10⁸ / 1.33 ≈ 2.25 × 10⁸ m/s." },
    { q: "A convex lens of focal length 25 cm has a power of:", options: ["+25 D", "+4 D", "−4 D", "+0.25 D"], answer: 1, why: "P = 1/f with f in metres: f = 0.25 m, so P = 1/0.25 = +4 D. Positive because the lens is convex." },
    { q: "An object placed at 2F₁ of a convex lens forms an image that is:", options: ["At F₂, diminished", "At 2F₂, same size, real, inverted", "At infinity", "Virtual and erect"], answer: 1, why: "The 2F position is the symmetric case: the image forms at 2F on the other side, real, inverted and the same size." },
    { q: "Two lenses of power +2 D and −5 D are placed in contact. The net power is:", options: ["+7 D", "−3 D", "+3 D", "−7 D"], answer: 1, why: "Powers add: P = 2 + (−5) = −3 D. The combination behaves as a concave lens." },
    { q: "Which formula is correct for a lens?", options: ["1/v + 1/u = 1/f", "1/v − 1/u = 1/f", "1/u − 1/v = 1/f", "v + u = f"], answer: 1, why: "The lens formula uses a minus sign; the mirror formula uses a plus. This is the single most common error in the chapter." },
    { q: "The magnification produced by a plane mirror is:", options: ["Zero", "+1", "−1", "Infinite"], answer: 1, why: "A plane mirror gives a virtual, erect image of the same size, so m = +1." },
  ],
  keyTopics: [
    { name: "Sign convention (New Cartesian) for mirrors and lenses", importance: "high", note: "Every numerical depends on getting u, v and f signs right — this is the single biggest source of lost marks in the chapter." },
    { name: "Mirror formula and magnification numericals", importance: "high", note: "1/v + 1/u = 1/f and m = −v/u appear in almost every 3- and 5-mark numerical." },
    { name: "Lens formula, magnification and power of a lens", importance: "high", note: "1/v − 1/u = 1/f, m = v/u and P = 1/f, including lenses in combination." },
    { name: "Image formation tables — six cases for mirrors and lenses", importance: "high", note: "Tested through ray-diagram questions asking for position, nature and size of the image." },
    { name: "Refraction, Snell's law and refractive index", importance: "medium", note: "Definition-based questions and numericals relating n, speed of light and angle." },
    { name: "Uses of concave and convex mirrors and lenses", importance: "medium", note: "Reason-based 1–2 mark questions, e.g. why a convex mirror suits a rear-view mirror." },
    { name: "Laws of reflection and refraction", importance: "low", note: "Straightforward 1-mark recall, but occasionally embedded inside a diagram question." },
  ],
  written: [
    { q: "Which single type of spherical mirror always gives an erect and diminished image of an object placed at any distance from it?", marks: 1, kind: "short", importance: "medium",
      answer: "A <strong>convex mirror</strong>. It always forms a virtual, erect and diminished image, whatever the position of the object." },
    { q: "Define the power of a lens and state its SI unit.", marks: 1, kind: "short", importance: "high",
      answer: "The power of a lens is the reciprocal of its focal length in metres: <strong>P = 1/f</strong>. Its SI unit is the <strong>dioptre (D)</strong>. 1 D is the power of a lens of focal length 1 m." },
    { q: "State two differences between the images formed by a concave mirror and a convex mirror.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>(i)</strong> A concave mirror can form both real and virtual images depending on the object's position, while a convex mirror <em>always</em> forms a virtual image.<br><strong>(ii)</strong> A concave mirror's image can be enlarged, diminished or the same size, while a convex mirror's image is <em>always</em> diminished." },
    { q: "A convex lens of focal length 10 cm forms a virtual image that is twice the size of the object. Find the distance of the object from the lens.", marks: 2, kind: "numerical", importance: "high",
      answer: "Virtual image ⇒ m is positive: m = v/u = +2, so <strong>v = 2u</strong>.<br>Lens formula: 1/v − 1/u = 1/f. Substituting v = 2u: 1/(2u) − 1/u = 1/10 ⇒ (1 − 2)/(2u) = 1/10 ⇒ −1/(2u) = 1/10 ⇒ u = −5.<br>So <strong>u = −5 cm</strong> — the object is placed 5 cm from the lens (inside the focal length, as expected for a virtual image)." },
    { q: "Two thin lenses of powers +5 D and −2.5 D are placed in contact. Find the power and the focal length of the combination, and state whether it behaves as a converging or diverging lens.", marks: 2, kind: "numerical", importance: "high",
      answer: "For lenses in contact, powers add: P = P₁ + P₂ = 5 + (−2.5) = <strong>+2.5 D</strong>.<br>Focal length f = 1/P = 1/2.5 = <strong>0.4 m = 40 cm</strong>.<br>Since P is positive, the combination behaves as a <strong>converging (convex) lens</strong>." },
    { q: "A concave mirror produces a three times magnified real image of an object placed 10 cm in front of it. Find the position of the image.", marks: 3, kind: "numerical", importance: "high",
      answer: "Real image ⇒ m is negative: m = −v/u = −3, with u = −10 cm.<br>−v/(−10) = −3 ⇒ v/10 = −3 ⇒ <strong>v = −30 cm</strong>.<br>The image forms 30 cm in front of the mirror, and is real (v negative), inverted and three times enlarged, consistent with a real magnified image." },
    { q: "With the help of a ray diagram, show the formation of an image when an object is placed between the pole and the principal focus of a concave mirror. State the nature of the image.", marks: 3, kind: "diagram", importance: "high",
      answer: "Two rays from the tip of the object are traced: one parallel to the principal axis, which reflects through F; and one directed towards F (or along a line through F), which reflects parallel to the axis. Both reflected rays diverge and appear to meet <em>behind</em> the mirror when produced backward, so their intersection point locates the image.<br>The image formed is <strong>virtual, erect and magnified</strong> — this is the working principle of a shaving or dentist's mirror." },
    { q: "The refractive index of diamond is 2.42 and that of glass is 1.5. Calculate the refractive index of diamond with respect to glass, and hence find the ratio of the speed of light in glass to that in diamond.", marks: 3, kind: "numerical", importance: "medium",
      answer: "Refractive index of diamond w.r.t. glass, n<sub>dg</sub> = n<sub>d</sub>/n<sub>g</sub> = 2.42/1.5 ≈ <strong>1.61</strong>.<br>Since n = c/v, this same ratio equals the ratio of speeds: v<sub>glass</sub>/v<sub>diamond</sub> = n<sub>diamond</sub>/n<sub>glass</sub> ≈ <strong>1.61</strong>. So light travels about 1.61 times faster in glass than in diamond." },
    { q: "Draw ray diagrams to show the image formed by a convex lens when the object is placed (i) at 2F₁, and (ii) between the optical centre and F₁. In each case, state the position, nature and size of the image.", marks: 5, kind: "diagram", importance: "high",
      answer: "<strong>(i) Object at 2F₁:</strong> a ray parallel to the axis refracts through F₂; a ray through the optical centre goes straight on. They meet at <strong>2F₂</strong> on the far side. Image: <strong>real, inverted, same size</strong> as the object.<br><strong>(ii) Object between O and F₁:</strong> the two refracted rays diverge on the far side and only appear to meet when produced backward, on the <em>same side</em> as the object. Image: <strong>virtual, erect and enlarged</strong> — this is how a convex lens is used as a magnifying glass." },
    { q: "An object 4 cm high is placed 30 cm from a concave mirror of focal length 15 cm. Find the position, nature and size of the image formed.", marks: 5, kind: "numerical", importance: "high",
      answer: "u = −30 cm, f = −15 cm.<br>1/v = 1/f − 1/u = (−1/15) − (−1/30) = −2/30 + 1/30 = −1/30 ⇒ <strong>v = −30 cm</strong>.<br>Magnification m = −v/u = −(−30)/(−30) = <strong>−1</strong>.<br>The image forms 30 cm in front of the mirror (real, since v is negative), is <strong>inverted</strong>, and since |m| = 1 it is the <strong>same size</strong> as the object (height = 4 cm) — exactly as expected, since the object is at the centre of curvature (R = 2f = 30 cm)." },
  ],
  assertionReason: [
    { assertion: "A concave mirror can form a virtual image of an object.",
      reason: "A concave mirror always converges a parallel beam of light to its principal focus.",
      answer: 1, importance: "medium",
      why: "Both statements are true — a concave mirror does form a virtual image when the object is between the pole and focus, and it does converge parallel rays to F. But the second fact does not explain the first: the virtual image arises from the specific object position, not from the mirror's general converging property." },
    { assertion: "The image formed by a convex lens is always real.",
      reason: "A convex lens is a converging lens.",
      answer: 3, importance: "high",
      why: "A is false — a convex lens forms a virtual, erect image when the object is placed between the optical centre and the focus. R is true: a convex lens is indeed a converging lens; it just doesn't make every image real." },
    { assertion: "A ray of light travelling from water into air bends away from the normal.",
      reason: "Air is optically denser than water.",
      answer: 2, importance: "medium",
      why: "A is true: going from a denser medium (water) to a rarer one (air), light bends away from the normal. R is false: air is optically <em>rarer</em> than water, not denser." },
    { assertion: "A convex mirror is preferred as a rear-view mirror in vehicles.",
      reason: "A convex mirror always forms an erect, virtual and diminished image, and has a wider field of view than a plane mirror of the same size.",
      answer: 0, importance: "high", years: "2020",
      why: "Both statements are true, and R correctly explains A: the always-erect, always-diminished image and the wide field of view are exactly why a convex mirror is chosen." },
  ],
  caseStudies: [
    { title: "Determining the focal length of a convex lens experimentally", importance: "high",
      source: "A student places an object at different distances u in front of a convex lens and notes the distance v at which a sharp image forms on a screen:<br><table><thead><tr><th>u (cm)</th><th>30</th><th>20</th><th>15</th><th>12</th></tr></thead><tbody><tr><td>v (cm)</td><td>15</td><td>20</td><td>30</td><td>60</td></tr></tbody></table>",
      parts: [
        { q: "Using any one pair of readings, calculate the focal length of the lens.", marks: 2, answer: "Taking u = −30 cm, v = +15 cm: 1/f = 1/v − 1/u = 1/15 − (−1/30) = 2/30 + 1/30 = 3/30 = 1/10, so <strong>f = 10 cm</strong>. (Every pair in the table gives the same value.)" },
        { q: "At what object distance would the image form at the same distance as the object? What is this position called?", marks: 1, answer: "When u = v = 20 cm, i.e. the object is at <strong>2F</strong>. Here the image is real, inverted and the same size as the object." },
        { q: "If the object were placed 8 cm from the lens, what would be the nature of the image?", marks: 1, answer: "Since 8 cm is less than the focal length (10 cm), the image would be <strong>virtual, erect and magnified</strong>, on the same side as the object." },
        { q: "Name one common optical device that uses the lens in the way described in part (iii).", marks: 1, answer: "A <strong>simple magnifying glass</strong> (or the lens of a microscope's eyepiece)." },
      ] },
    { title: "Combining lenses to change optical power", importance: "medium",
      source: "An optical instrument uses two thin lenses held in contact: lens A of power +6 D and lens B of power −4 D.",
      parts: [
        { q: "Find the power of the combination.", marks: 1, answer: "P = P<sub>A</sub> + P<sub>B</sub> = 6 + (−4) = <strong>+2 D</strong>." },
        { q: "Find the focal length of the combination and state whether it is converging or diverging.", marks: 2, answer: "f = 1/P = 1/2 = <strong>0.5 m = 50 cm</strong>. Since P is positive, the combination is <strong>converging</strong> (behaves like a convex lens)." },
        { q: "What is the focal length of lens A alone?", marks: 1, answer: "f<sub>A</sub> = 1/P<sub>A</sub> = 1/6 m ≈ <strong>16.7 cm</strong>." },
        { q: "Give one reason why optical instruments often use a combination of lenses rather than a single lens.", marks: 1, answer: "Combining lenses lets the designer obtain a required power (or correct defects such as chromatic aberration) more precisely than a single lens can, while keeping each individual lens thinner and lighter." },
      ] },
  ],
};
