import type { Chapter } from "@/lib/types";

export const ch12: Chapter = {
  slug: "human-eye-and-colourful-world",
  num: 12,
  title: "The Human Eye and the Colourful World",
  unit: "light",
  unitName: "Natural Phenomena — Light and Optics",
  marks: "Unit III · 12 marks",
  minutes: 20,
  blurb: "The best camera you own, the three defects it can develop, and why the sky is blue but the sunset is red.",
  bigIdea: "The eye is a lens whose focal length you can change at will. Every defect of vision is that adjustment failing at one end of its range — and every corrective lens simply moves the focus back onto the retina.",
  syllabus: [
    "Functioning of a lens in the human eye", "Defects of vision and their corrections",
    "Applications of spherical mirrors and lenses",
    "Refraction of light through a prism", "Dispersion of light",
    "Scattering of light and applications in daily life",
  ],
  blocks: [
    { t: "h", text: "How the eye works" },
    { t: "table", head: ["Part", "What it does"], rows: [
      ["<strong>Cornea</strong>", "The transparent front bulge. Most of the bending of light actually happens here, not at the lens"],
      ["<strong>Iris</strong>", "The coloured ring. It is a muscle that controls the size of the pupil"],
      ["<strong>Pupil</strong>", "The hole light passes through — it widens in dim light and narrows in bright light"],
      ["<strong>Crystalline lens</strong>", "Fine-tunes the focus. Made of a flexible jelly-like material"],
      ["<strong>Ciliary muscles</strong>", "Squeeze or relax the lens to change its focal length"],
      ["<strong>Retina</strong>", "The light-sensitive screen at the back, with rods (dim light) and cones (colour)"],
      ["<strong>Optic nerve</strong>", "Carries the signal to the brain"],
    ] },
    { t: "note", kind: "idea", title: "Accommodation", html: "The eye's ability to change the focal length of its lens to focus on objects at different distances is called <strong>accommodation</strong>. Looking at something far away, the ciliary muscles relax and the lens becomes thin (long focal length). Looking at something near, they contract and the lens becomes thicker (short focal length)." },
    { t: "note", kind: "exam", html: "Two numbers to memorise: the <strong>near point</strong> (least distance of distinct vision) is <strong>25 cm</strong> for a normal young adult, and the <strong>far point</strong> is <strong>infinity</strong>. Almost every defect question is defined against these two." },
    { t: "note", kind: "why", title: "Why does a dark room feel blindingly bright when the lights come on?", html: "In the dark the iris opens the pupil wide to let in as much light as possible. When the lights come on suddenly, the pupil is still wide and lets in far too much — it takes a second or two for the iris to contract. The same reason works in reverse when you walk into a cinema." },

    { t: "h", text: "The three defects of vision" },
    { t: "sim", id: "eye-defects" },
    { t: "table", head: ["Defect", "What happens", "Cause", "Correction"], rows: [
      ["<strong>Myopia</strong><br>(short-sightedness)", "Distant objects blurred; the image forms <em>in front of</em> the retina. Far point is nearer than infinity", "Eyeball too long, or the lens is too converging (excessive curvature)", "<strong>Concave lens</strong> of suitable negative power"],
      ["<strong>Hypermetropia</strong><br>(long-sightedness)", "Nearby objects blurred; the image would form <em>behind</em> the retina. Near point is further than 25 cm", "Eyeball too short, or the focal length of the lens is too long", "<strong>Convex lens</strong> of suitable positive power"],
      ["<strong>Presbyopia</strong>", "Both near and distant vision get worse with age", "Ciliary muscles weaken and the lens becomes rigid, so accommodation is lost", "Bifocal lenses — concave upper half for distance, convex lower half for reading"],
    ] },
    { t: "note", kind: "memory", html: "<strong>Myopia = Minus lens. Hypermetropia = Plus lens.</strong> The 'M' does the work." },
    { t: "steps", title: "A person cannot see beyond 1.5 m. What lens does he need?",
      intro: "The standard myopia numerical. The trick: the lens must make an object at infinity appear to be at his far point.",
      steps: [
        "The object is at infinity, so u = ∞ and 1/u = 0.",
        "The image must form at his far point, on the same side as the object: v = −1.5 m.",
        "Lens formula: 1/f = 1/v − 1/u = (−1/1.5) − 0 = −0.667.",
        "So f = −1.5 m, and P = 1/f = <strong>−0.67 D</strong>.",
      ],
      answer: "A concave lens of power −0.67 D (focal length 1.5 m). Note the shortcut: for myopia, f = −(far point).",
    },

    { t: "h", text: "Refraction through a prism and dispersion" },
    { t: "sim", id: "prism-dispersion" },
    { t: "p", html: "In a glass slab the two faces are parallel, so the emergent ray comes out parallel to the incident ray — merely displaced. A prism has two <em>inclined</em> faces, so the two bends add up instead of cancelling. The result is a net turning called the <strong>angle of deviation</strong>." },
    { t: "p", html: "When white light passes through a prism it does not just bend — it fans out into seven colours. This splitting is <strong>dispersion</strong>." },
    { t: "note", kind: "why", title: "Why does dispersion happen?", html: "Different colours travel at slightly different speeds inside glass, so each has a slightly different refractive index. Violet is slowed the most, so it bends the most; red is slowed the least and bends the least. In air they all travel at the same speed, which is why white light stays white until it enters the glass." },
    { t: "note", kind: "memory", html: "<strong>VIBGYOR</strong> from most bent to least: Violet, Indigo, Blue, Green, Yellow, Orange, Red." },
    { t: "note", kind: "idea", html: "Newton proved that the colours come from the light and not from the glass: he placed a second, inverted prism after the first, and the seven colours recombined into white light." },
    { t: "p", html: "A <strong>rainbow</strong> is a natural spectrum. Sunlight enters a raindrop, refracts and disperses, reflects once off the inner back surface, and refracts again on the way out. That is why you always see a rainbow with the sun <em>behind</em> you and the rain in front." },

    { t: "h", text: "Atmospheric refraction" },
    { t: "p", html: "Air is not uniform — it is hotter and less dense near the ground, cooler and denser higher up. Light passing through it bends continuously, and the bending changes as the air moves." },
    { t: "list", items: [
      "<strong>Twinkling of stars.</strong> A star is so far away it is effectively a point source. Its light passes through constantly shifting layers of air, so its apparent position and brightness wobble — it twinkles. Planets are much closer and appear as a collection of point sources, whose variations average out. <strong>Planets do not twinkle</strong>, and that comparison is examined every year.",
      "<strong>The advance sunrise and delayed sunset.</strong> Refraction bends sunlight downward, so the sun appears above the horizon when it is actually still below it. You see the sun about <strong>two minutes before</strong> it actually rises and for about two minutes after it has set.",
      "<strong>The flattened sun at the horizon.</strong> Light from the lower edge is bent more than light from the upper edge, squashing the disc into an oval.",
    ] },

    { t: "h", text: "Scattering of light" },
    { t: "sim", id: "scattering" },
    { t: "p", html: "When light meets particles much smaller than its wavelength, it is scattered — and shorter wavelengths are scattered far more strongly. Blue light is scattered about sixteen times more than red." },
    { t: "list", items: [
      "<strong>Why the sky is blue.</strong> Air molecules scatter blue light in every direction, so whichever way you look you see scattered blue. Without an atmosphere the sky would look black, which is exactly what astronauts see.",
      "<strong>Why the sun is red at sunrise and sunset.</strong> Near the horizon, sunlight travels through a much thicker layer of atmosphere. Almost all the blue is scattered out along the way, leaving mostly red and orange to reach your eye.",
      "<strong>Why danger signals are red.</strong> Red has the longest wavelength, so it is scattered the least by fog, dust and mist — it travels furthest and stays visible.",
      "<strong>The Tyndall effect.</strong> The path of a beam becomes visible when it passes through a colloid — sunlight through a canopy of trees, or a torch beam in a smoky room.",
    ] },
    { t: "note", kind: "real", html: "The sky looks dark from an aeroplane at high altitude for the same reason it is black in space: there is less air above you, so less scattering. And the colour is bluer looking up than sideways, because sideways you are looking through more atmosphere." },

    { t: "steps", title: "Why does the sun appear white at noon but red at sunset?",
      intro: "Three marks, and the answer is entirely about path length.",
      steps: [
        "At noon the sun is overhead, so its light travels through the <strong>shortest</strong> path in the atmosphere.",
        "Very little scattering occurs, so all seven colours reach the eye together and the sun appears white.",
        "At sunset the sun is near the horizon, so the light travels through a <strong>much longer</strong> path through the atmosphere.",
        "Along that long path, most of the shorter wavelengths — blue and violet — are scattered away.",
        "Only the longer wavelengths, red and orange, survive the journey to your eye.",
      ],
      answer: "It is the difference in the length of the atmospheric path, and the fact that blue is scattered far more strongly than red.",
    },
  ],
  formulas: [
    { name: "Near point (normal eye)", expr: "25 cm", note: "Least distance of distinct vision" },
    { name: "Far point (normal eye)", expr: "Infinity" },
    { name: "Myopia correction", expr: "f = −(far point)", note: "Concave lens; power is negative" },
    { name: "Hypermetropia correction", expr: "1/f = 1/v − 1/u, with u = −25 cm, v = −(near point)", note: "Convex lens; power is positive" },
    { name: "Power of a lens", expr: "P = 1/f (f in metres)", note: "Unit: dioptre (D)" },
  ],
  examFocus: [
    "Accommodation defined, and how the ciliary muscles change the lens for near and far objects.",
    "Near point = 25 cm and far point = infinity for a normal eye.",
    "The three defects with cause, effect and correcting lens, plus a ray diagram for each.",
    "The myopia and hypermetropia numericals — set them up with the far point / near point as the image distance.",
    "Why dispersion happens, VIBGYOR order, and Newton's two-prism experiment.",
    "Why stars twinkle but planets do not.",
    "The three scattering applications: blue sky, red sunset, red danger signals.",
  ],
  flashcards: [
    { q: "What is accommodation?", a: "The ability of the eye lens to change its focal length so that objects at different distances can be focused sharply on the retina. Ciliary muscles do this by squeezing or relaxing the lens." },
    { q: "State the near point and far point of a normal human eye.", a: "Near point (least distance of distinct vision) is 25 cm. Far point is infinity." },
    { q: "What is the function of the iris and pupil?", a: "The iris is a muscular diaphragm that controls the size of the pupil, which is the opening light enters through. It widens in dim light and narrows in bright light." },
    { q: "What causes myopia and how is it corrected?", a: "The eyeball is too long or the lens too converging, so distant images form in front of the retina. Corrected with a concave lens of suitable negative power." },
    { q: "What causes hypermetropia and how is it corrected?", a: "The eyeball is too short or the lens's focal length too long, so nearby images would form behind the retina. Corrected with a convex lens of suitable positive power." },
    { q: "What is presbyopia?", a: "Age-related loss of accommodation: the ciliary muscles weaken and the lens becomes rigid, so both near and distant vision suffer. Corrected with bifocal lenses." },
    { q: "Why does a prism disperse white light but a glass slab does not?", a: "A prism has two inclined faces, so the deviations at each face add up and different colours emerge along different directions. In a slab the faces are parallel and the deviations cancel, so the emergent ray is white and merely displaced." },
    { q: "Why does violet bend more than red in a prism?", a: "Violet light travels most slowly in glass, so glass has the highest refractive index for violet and it is deviated the most. Red travels fastest and deviates least." },
    { q: "How did Newton prove that white light is made of seven colours?", a: "He passed white light through a prism to get a spectrum, then placed a second identical prism upside down. The colours recombined into white light, proving the colours came from the light, not from the glass." },
    { q: "Why do stars twinkle but planets do not?", a: "A star is effectively a point source, and atmospheric refraction constantly shifts its apparent position and brightness. A planet is a collection of many point sources, and their variations average out." },
    { q: "Why does the sun appear about two minutes before actual sunrise?", a: "Atmospheric refraction bends light from the sun downward, so the sun appears raised above the horizon when it is actually still below it. The same happens at sunset." },
    { q: "Why is the sky blue?", a: "Air molecules scatter shorter wavelengths much more strongly. Blue light is scattered in all directions and reaches the eye from every part of the sky." },
    { q: "Why is the sun red at sunrise and sunset?", a: "Near the horizon sunlight travels a much longer path through the atmosphere, so nearly all the blue is scattered away and only the longer red and orange wavelengths reach the eye." },
    { q: "Why is red used for danger signals?", a: "Red has the longest wavelength and is scattered the least by fog, dust and mist, so it remains visible from the greatest distance." },
    { q: "What is the Tyndall effect?", a: "The scattering of light by colloidal particles, which makes the path of the beam visible — for example a torch beam in a smoky room or sunlight through a forest canopy." },
  ],
  quiz: [
    { q: "The change in focal length of the eye lens to focus on near and far objects is called:", options: ["Refraction", "Accommodation", "Dispersion", "Scattering"], answer: 1, why: "Accommodation is the eye's adjustment of its lens's focal length, done by the ciliary muscles." },
    { q: "The least distance of distinct vision for a normal eye is:", options: ["10 cm", "25 cm", "50 cm", "Infinity"], answer: 1, why: "25 cm is the near point of a normal young adult eye. The far point is infinity." },
    { q: "A person who cannot see distant objects clearly suffers from:", options: ["Hypermetropia", "Myopia", "Presbyopia", "Cataract"], answer: 1, why: "In myopia the image of a distant object forms in front of the retina. It is corrected with a concave lens." },
    { q: "Hypermetropia is corrected using a:", options: ["Concave lens", "Convex lens", "Plane mirror", "Bifocal lens"], answer: 1, why: "A convex lens converges the rays before they enter the eye, bringing the image forward onto the retina." },
    { q: "A person needs a lens of power −2 D. His far point is at:", options: ["2 m", "0.5 m", "−2 m", "50 cm"], answer: 1, why: "f = 1/P = 1/(−2) = −0.5 m. For myopia, f = −(far point), so the far point is 0.5 m." },
    { q: "Bifocal lenses are used to correct:", options: ["Myopia", "Hypermetropia", "Presbyopia", "Astigmatism"], answer: 2, why: "Presbyopia affects both near and distant vision, so the upper part of the lens is concave (distance) and the lower part convex (reading)." },
    { q: "The splitting of white light into its colours is called:", options: ["Refraction", "Scattering", "Dispersion", "Reflection"], answer: 2, why: "Dispersion is the separation of white light into its constituent colours because each has a different refractive index in the medium." },
    { q: "Which colour is deviated the most by a prism?", options: ["Red", "Yellow", "Green", "Violet"], answer: 3, why: "Violet has the shortest wavelength and the highest refractive index in glass, so it is bent the most." },
    { q: "Stars twinkle because of:", options: ["Their own brightness changing", "Atmospheric refraction", "Dispersion in space", "Scattering by dust"], answer: 1, why: "Continuously changing layers of air refract the star's light differently from moment to moment, so its apparent position and brightness fluctuate." },
    { q: "The sky appears black to an astronaut because:", options: ["There is no sunlight", "There is no atmosphere to scatter light", "The sun is too far", "Space absorbs blue light"], answer: 1, why: "Scattering needs particles. With no atmosphere there is nothing to scatter sunlight, so the sky has no colour of its own." },
    { q: "Danger signals are red because red light:", options: ["Is the brightest", "Has the shortest wavelength", "Is scattered least and travels furthest through fog", "Is easiest to produce"], answer: 2, why: "Longest wavelength means least scattering, so red penetrates fog and haze better than any other visible colour." },
    { q: "The sun appears flattened at sunset because:", options: ["The sun really is oval", "Light from its lower edge is refracted more than from its upper edge", "Of scattering", "Of dispersion in clouds"], answer: 1, why: "Atmospheric refraction raises the lower edge more than the upper edge, compressing the disc vertically into an oval." },
  ],
  keyTopics: [
    { name: "Defects of vision — myopia, hypermetropia, presbyopia", importance: "high", note: "Cause, effect and corrective lens for each; frequently paired with a numerical or ray diagram." },
    { name: "Correcting-lens numericals using u, v, f and P = 1/f", importance: "high", note: "Set up with the far point or near point as the image distance — the most common numerical in the chapter." },
    { name: "Dispersion of light through a prism", importance: "high", note: "VIBGYOR order, why violet bends most, and Newton's recombination experiment." },
    { name: "Scattering of light — blue sky, red sunset, danger signals", importance: "high", note: "Reason-based questions asked almost every year, often as a 1–2 mark or assertion–reason item." },
    { name: "Atmospheric refraction — twinkling of stars, advance sunrise/delayed sunset", importance: "medium", note: "Why stars twinkle but planets do not is a classic repeated question." },
    { name: "Structure and functioning of the eye, accommodation", importance: "medium", note: "Near point (25 cm) and far point (infinity); diagram-labelling questions." },
    { name: "Prism vs glass slab", importance: "low", note: "Why a slab does not disperse light but a prism does." },
  ],
  written: [
    { q: "Define the near point of the human eye.", marks: 1, kind: "short", importance: "medium",
      answer: "The near point (least distance of distinct vision) is the closest distance at which an object can be seen clearly without strain. For a normal young adult it is about <strong>25 cm</strong>." },
    { q: "Name the phenomenon responsible for the flattened appearance of the sun's disc at sunset.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Atmospheric refraction.</strong> Light from the sun's lower edge is bent more than light from its upper edge, squashing the disc into an oval." },
    { q: "What is myopia? State one possible cause of this defect.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Myopia (short-sightedness)</strong> is a defect in which a person can see nearby objects clearly but distant objects appear blurred, because the image of a distant object forms in front of the retina.<br>Cause: the eyeball has become too long, or the eye lens is too strongly converging." },
    { q: "A person needs a concave lens of power −2.5 D to correct his myopia. What is the farthest distance at which he can see an object clearly without wearing this lens?", marks: 2, kind: "numerical", importance: "high",
      answer: "f = 1/P = 1/(−2.5) = <strong>−0.4 m = −40 cm</strong>.<br>For myopia, f = −(far point), so his far point is <strong>40 cm</strong>. Without his spectacles he can see objects clearly only up to 40 cm away." },
    { q: "Why is the danger signal light red in colour and not green or blue?", marks: 2, kind: "short", importance: "medium",
      answer: "Red light has the <strong>longest wavelength</strong> among visible colours, so it is scattered the <em>least</em> by fog, smoke and dust particles in the air. It therefore travels the greatest distance without being scattered away and remains visible from far off, making it the safest choice for a warning signal." },
    { q: "The near point of a hypermetropic eye is 1 m. What power of lens is needed to enable him to read a book held at the normal near point of 25 cm?", marks: 3, kind: "numerical", importance: "high",
      answer: "The lens must form a virtual image of the book (held at u = −25 cm = −0.25 m) at his actual near point, v = −1 m.<br>1/f = 1/v − 1/u = (−1/1) − (−1/0.25) = −1 + 4 = <strong>3 m⁻¹</strong>.<br>So f = 1/3 m, and <strong>P = 1/f = +3 D</strong>. He needs a convex lens of power +3 D." },
    { q: "Draw a labelled ray diagram to show the correction of myopia using a concave lens.", marks: 3, kind: "diagram", importance: "high",
      answer: "<strong>Uncorrected:</strong> rays from a distant object converge and form a point image in front of the retina.<br><strong>Corrected:</strong> a concave lens of suitable focal length is placed in front of the eye. It first diverges the incoming parallel rays slightly, so that after passing through the eye's own lens they now converge exactly <strong>on</strong> the retina, giving a sharp image." },
    { q: "Explain why the sky appears blue during the day, but looks black to an astronaut in space.", marks: 3, kind: "short", importance: "medium",
      answer: "Sunlight passing through the atmosphere is scattered by air molecules, and shorter wavelengths (blue, violet) are scattered <em>much</em> more strongly than longer ones. Scattered blue light reaches our eyes from every direction in the sky, so the sky looks blue.<br>An astronaut in space is above the atmosphere, so there are no molecules to scatter sunlight. With no scattered light reaching the eye from any direction other than directly from the sun, the sky appears <strong>black</strong>." },
    { q: "With the help of a labelled ray diagram, explain how a glass prism splits white light into its seven constituent colours. Describe how Newton showed that these colours belong to the light itself and not to the prism.", marks: 5, kind: "diagram", importance: "high",
      answer: "White light entering a prism refracts at the first inclined face and again at the second. Each colour has a slightly different refractive index in glass — violet the highest, red the lowest — so each bends by a different amount. The colours emerge spread out in the order <strong>VIBGYOR</strong> (violet deviated most, red least), forming a spectrum.<br><strong>Newton's experiment:</strong> he passed sunlight through a prism to obtain a spectrum, then placed a second, identical prism upside down in the path of this spectrum. The second prism recombined all seven colours back into white light — proving the colours were already present in sunlight and were merely separated (not created) by the first prism." },
    { q: "A person cannot see distant objects clearly beyond 2 m. (i) Name the defect. (ii) Which type of lens will correct it? (iii) Calculate the power of the lens required. (iv) State one possible cause of the defect.", marks: 5, kind: "numerical", importance: "high",
      answer: "<strong>(i)</strong> The far point is nearer than infinity, so this is <strong>myopia</strong>.<br><strong>(ii)</strong> Corrected using a <strong>concave lens</strong>.<br><strong>(iii)</strong> f = −(far point) = <strong>−2 m</strong>, so P = 1/f = <strong>−0.5 D</strong>.<br><strong>(iv)</strong> Cause: the eyeball has elongated, or the eye lens has become too strongly converging, so images of distant objects form in front of the retina instead of on it." },
  ],
  assertionReason: [
    { assertion: "A person suffering from myopia can see nearby objects clearly but not distant objects.",
      reason: "In myopia, the image of a distant object is formed in front of the retina instead of on it.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A: because the image falls short of the retina, distant objects appear blurred while near objects (whose images fall further back, closer to the retina) remain clear." },
    { assertion: "A convex lens corrects hypermetropia by diverging the incoming light rays before they enter the eye.",
      reason: "A convex lens is a converging lens that increases the total converging power of the eye's lens system.",
      answer: 3, importance: "high",
      why: "A is false — a convex lens converges light, it does not diverge it. R is true: a convex lens does add converging power, which is exactly why it corrects hypermetropia (by bringing the image forward onto the retina), just not by the mechanism the assertion describes." },
    { assertion: "A person suffering from hypermetropia cannot see nearby objects clearly.",
      reason: "In hypermetropia, the eyeball has become too long, causing the image to form in front of the retina.",
      answer: 2, importance: "medium",
      why: "A is true — the near point recedes beyond 25 cm in hypermetropia. R is false: in hypermetropia the eyeball is too <em>short</em> (or the lens too weakly converging), causing the image to form <em>behind</em> the retina — the description given matches myopia, not hypermetropia." },
    { assertion: "Stars twinkle in the night sky, but planets do not.",
      reason: "A star is effectively a point source of light, so its apparent position and brightness fluctuate continuously due to atmospheric refraction, whereas a planet is seen as a collection of many point sources whose variations average out.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R gives the correct explanation of A — this point-source vs extended-source distinction is exactly why only stars twinkle." },
  ],
  caseStudies: [
    { title: "A vision test report", importance: "high",
      source: "During a routine eye check-up, two patients' readings were recorded:<br><table><thead><tr><th>Patient</th><th>Near point</th><th>Far point</th></tr></thead><tbody><tr><td>A</td><td>50 cm</td><td>Infinity</td></tr><tr><td>B</td><td>25 cm</td><td>3 m</td></tr></tbody></table>",
      parts: [
        { q: "Identify the defect of vision suffered by Patient A and by Patient B.", marks: 2, answer: "<strong>Patient A</strong> has a near point farther than the normal 25 cm (but a normal far point), so he suffers from <strong>hypermetropia</strong>.<br><strong>Patient B</strong> has a normal near point but a far point nearer than infinity, so he suffers from <strong>myopia</strong>." },
        { q: "Which type of lens would correct Patient B's defect? Calculate its power.", marks: 2, answer: "A <strong>concave lens</strong>. f = −(far point) = <strong>−3 m</strong>, so P = 1/f ≈ <strong>−0.33 D</strong>." },
        { q: "State one likely cause of Patient A's defect.", marks: 1, answer: "The eyeball has become too <strong>short</strong>, or the focal length of the eye lens has increased, so the image of a nearby object would form behind the retina." },
      ] },
    { title: "Rainbows and the colour of the sky", importance: "medium",
      source: "A student notices that a rainbow appears in the sky only when the sun is behind her and rain is falling in front of her. She also notices that the daytime sky looks blue, while the setting sun looks orange-red.",
      parts: [
        { q: "Explain the role of raindrops in the formation of a rainbow.", marks: 2, answer: "Each raindrop acts like a tiny prism. Sunlight entering a drop is <strong>refracted</strong>, then undergoes total internal <strong>reflection</strong> off the drop's inner back surface, and is <strong>refracted</strong> again on its way out. This double refraction plus one reflection disperses white sunlight into its seven constituent colours." },
        { q: "Why must the sun be behind the observer for a rainbow to be visible?", marks: 1, answer: "The dispersed light emerges from each raindrop back towards the side the sunlight came from, so the observer must stand with the sun behind and the rain-filled sky in front to receive that returning light." },
        { q: "Using the idea of scattering, explain why the sky is blue but the setting sun looks orange-red.", marks: 2, answer: "Air molecules scatter shorter wavelengths (blue) far more than longer ones (red), so overhead in the daytime we receive scattered blue light from all directions, making the sky blue. At sunset the sunlight travels a much longer path through the atmosphere to reach us; nearly all the blue is scattered out along this long path, leaving mostly red and orange light to reach the eye directly." },
      ] },
  ],
};
