import type { Chapter } from "@/lib/types";

export const ch13: Chapter = {
  slug: "electricity",
  num: 13,
  title: "Electricity",
  unit: "current",
  unitName: "How Things Work — Effects of Current",
  marks: "Unit IV · 13 marks",
  minutes: 26,
  blurb: "Current, voltage, resistance and power — four quantities, one law connecting them, and a lot of numericals worth easy marks.",
  bigIdea: "Voltage pushes, resistance holds back, and current is what actually gets through. Once you truly believe that sentence, every circuit question becomes arithmetic.",
  syllabus: [
    "Electric current and potential difference",
    "Ohm's law", "Resistance", "Resistivity",
    "Factors on which the resistance of a conductor depends",
    "Series and parallel combinations of resistors and their applications in daily life",
    "Heating effect of electric current and its applications",
    "Electric power", "Interrelation between P, V, I and R",
  ],
  blocks: [
    { t: "h", text: "The three basic quantities" },
    { t: "p", html: "A useful picture: think of a water pipe. <strong>Potential difference</strong> is the pressure pushing the water. <strong>Current</strong> is how much water flows past a point each second. <strong>Resistance</strong> is how narrow the pipe is." },
    { t: "formula", name: "Electric current", expr: "I = Q / t",
      where: ["Q = charge in coulombs (C)", "t = time in seconds", "I is measured in amperes (A). 1 A = 1 C/s", "Charge on one electron = 1.6 × 10⁻¹⁹ C"] },
    { t: "formula", name: "Potential difference", expr: "V = W / Q",
      where: ["W = work done in joules", "V is measured in volts. 1 V = 1 J/C", "Measured with a voltmeter connected in <strong>parallel</strong>"] },
    { t: "note", kind: "trap", html: "<strong>An ammeter goes in series; a voltmeter goes in parallel.</strong> An ammeter has very low resistance (so it does not reduce the current it is measuring); a voltmeter has very high resistance (so it draws almost no current). Circuit-diagram questions test this every year." },
    { t: "note", kind: "why", title: "Which way does current flow?", html: "Conventional current is taken to flow from + to −, which is the direction a positive charge would move. Electrons actually flow the opposite way, from − to +. This is a historical accident from before the electron was discovered — but every formula and diagram uses the conventional direction, so stick with it." },

    { t: "h", text: "Ohm's law" },
    { t: "sim", id: "ohms-law" },
    { t: "formula", name: "Ohm's law", expr: "V = I R",
      where: ["Valid at constant temperature", "R is measured in ohms (Ω)", "A V–I graph is a straight line through the origin, and its slope is 1/R"] },
    { t: "note", kind: "exam", html: "&ldquo;State Ohm's law&rdquo; requires the condition: <em>the current through a conductor is directly proportional to the potential difference across its ends, <strong>provided the temperature and other physical conditions remain constant</strong>.</em> Leave out the condition and you lose a mark." },

    { t: "h", text: "What resistance depends on" },
    { t: "formula", name: "Resistance and resistivity", expr: "R = ρ · l / A",
      where: ["l = length of the conductor", "A = area of cross-section", "ρ (rho) = resistivity, a property of the <strong>material</strong> alone", "Unit of ρ is ohm-metre (Ω m)"] },
    { t: "list", items: [
      "<strong>Longer wire → more resistance</strong> (R ∝ l). Twice as long means twice the resistance.",
      "<strong>Thicker wire → less resistance</strong> (R ∝ 1/A). Double the radius means four times the area, so a quarter of the resistance.",
      "<strong>Material matters</strong> — this is what ρ captures.",
      "<strong>Temperature</strong> — for metals, resistance rises as temperature rises.",
    ] },
    { t: "note", kind: "real", html: "Copper and aluminium have very low resistivity, so they are used for connecting wires and transmission lines. Nichrome has resistivity about 60 times that of copper and does not oxidise readily even when red hot — so it is used for the heating elements of toasters, irons and heaters. Tungsten has a very high melting point, which is why it is used for bulb filaments." },
    { t: "note", kind: "trap", html: "Resistivity ρ is a property of the <em>material</em> and does not change when you cut the wire. Resistance R is a property of that <em>particular piece</em> and does change. Cut a wire in half and each half has half the resistance, but exactly the same resistivity." },

    { t: "h", text: "Combining resistors" },
    { t: "sim", id: "series-parallel" },
    { t: "compare",
      left: { title: "Series", items: [
        "<strong>R<sub>s</sub> = R₁ + R₂ + R₃</strong>",
        "Same <strong>current</strong> through every resistor",
        "Voltage divides across them",
        "Total R is <em>greater</em> than the largest individual R",
        "One component fails → the whole circuit breaks",
      ] },
      right: { title: "Parallel", items: [
        "<strong>1/R<sub>p</sub> = 1/R₁ + 1/R₂ + 1/R₃</strong>",
        "Same <strong>voltage</strong> across every resistor",
        "Current divides between them",
        "Total R is <em>less</em> than the smallest individual R",
        "One component fails → the others keep working",
      ] } },
    { t: "note", kind: "why", title: "Why are home appliances wired in parallel?", html: "Three reasons, and the board wants all three. First, every appliance gets the full 220 V it is designed for. Second, each can be switched on and off independently. Third, if one fails the rest keep working. The cost is that the total resistance falls, so the total current drawn rises — which is exactly why you need a fuse." },
    { t: "note", kind: "memory", html: "Quick check for parallel: the answer must always be <strong>smaller than the smallest resistor</strong> in the combination. If it is not, you have made an arithmetic error." },

    { t: "h", text: "Heating effect and power" },
    { t: "p", html: "Whenever current flows through a resistance, some electrical energy turns into heat. That is unavoidable — sometimes it is a nuisance (a warm phone charger) and sometimes it is the entire point (a heater)." },
    { t: "formula", name: "Joule's law of heating", expr: "H = I² R t",
      where: ["H = heat produced in joules", "Heat ∝ square of the current — doubling the current gives four times the heat"] },
    { t: "formula", name: "Electric power — all four forms", expr: "P = V I = I² R = V² / R = W / t",
      where: ["Unit is the watt (W). 1 W = 1 J/s", "Use whichever form matches the quantities you are given"] },
    { t: "formula", name: "Commercial unit of energy", expr: "1 kWh = 1 unit = 3.6 × 10⁶ J",
      where: ["1 kWh = 1000 W × 3600 s", "Electricity bills are charged per unit"] },
    { t: "sim", id: "power-bill" },
    { t: "note", kind: "real", html: "A 100 W bulb rated for 220 V has resistance R = V²/P = 220²/100 = 484 Ω. A 60 W bulb of the same rating has R = 807 Ω — <em>higher</em> resistance. So the dimmer bulb has more resistance, which surprises people until they remember P = V²/R." },
    { t: "list", items: [
      "<strong>Electric heaters, irons, toasters, geysers</strong> — the heating effect is the purpose. They use nichrome elements.",
      "<strong>Electric bulb</strong> — tungsten filament heated to about 2500 °C, in a bulb filled with chemically inactive nitrogen or argon so the filament does not burn away.",
      "<strong>Fuse</strong> — a deliberately weak link. A short piece of wire with a low melting point that melts and breaks the circuit if the current exceeds a safe value.",
    ] },

    { t: "steps", title: "Two lamps, 100 W and 60 W, both rated 220 V, are connected in series to a 220 V supply. Which glows brighter?",
      intro: "A classic trap. Most students say the 100 W one, and most students are wrong.",
      steps: [
        "Find each resistance from its rating: R = V²/P. For the 100 W lamp, R = 220²/100 = 484 Ω. For the 60 W lamp, R = 220²/60 ≈ 807 Ω.",
        "In <strong>series</strong>, the same current flows through both.",
        "Power actually dissipated is P = I²R, and since I is the same, the lamp with the <strong>larger R</strong> dissipates more power.",
        "807 Ω &gt; 484 Ω, so the 60 W lamp dissipates more power in this circuit.",
      ],
      answer: "The 60 W lamp glows brighter. In parallel the answer would flip — there V is the same and P = V²/R, so the lower-resistance 100 W lamp wins.",
    },
    { t: "steps", title: "Find the equivalent resistance: 6 Ω and 3 Ω in parallel, that combination in series with 4 Ω.",
      intro: "Always solve the parallel bit first, then add the series parts.",
      steps: [
        "Parallel first: 1/R<sub>p</sub> = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2.",
        "So R<sub>p</sub> = 2 Ω. Sanity check: 2 Ω is less than 3 Ω, the smaller of the two. ✓",
        "Now add the series resistor: R = R<sub>p</sub> + 4 = 2 + 4.",
      ],
      answer: "R = 6 Ω. If the supply were 12 V, the total current would be I = V/R = 12/6 = 2 A.",
    },
  ],
  formulas: [
    { name: "Current", expr: "I = Q / t", note: "1 A = 1 C/s. Electron charge = 1.6 × 10⁻¹⁹ C" },
    { name: "Potential difference", expr: "V = W / Q", note: "1 V = 1 J/C" },
    { name: "Ohm's law", expr: "V = I R", note: "At constant temperature. V–I graph is a straight line, slope = 1/R" },
    { name: "Resistivity", expr: "R = ρ l / A", note: "ρ in Ω m; a property of the material only" },
    { name: "Series", expr: "R<sub>s</sub> = R₁ + R₂ + R₃", note: "Same current; total R greater than the largest" },
    { name: "Parallel", expr: "1/R<sub>p</sub> = 1/R₁ + 1/R₂ + 1/R₃", note: "Same voltage; total R less than the smallest" },
    { name: "Joule's law of heating", expr: "H = I² R t", note: "Heat is proportional to the square of the current" },
    { name: "Power", expr: "P = VI = I²R = V²/R", note: "Watt; 1 W = 1 J/s" },
    { name: "Commercial energy unit", expr: "1 kWh = 3.6 × 10⁶ J", note: "= 1 'unit' on your electricity bill" },
  ],
  examFocus: [
    "Ohm's law stated with the constant-temperature condition.",
    "Ammeter in series with low resistance; voltmeter in parallel with high resistance.",
    "The four factors resistance depends on, and R = ρl/A.",
    "Resistivity is a material property; resistance is not — the cut-wire question.",
    "Series and parallel formulas plus the three reasons for parallel household wiring.",
    "All four forms of the power formula, and picking the right one for the data given.",
    "The series-lamp brightness question — P = I²R when current is common.",
    "1 kWh = 3.6 × 10⁶ J, and calculating a monthly bill.",
  ],
  flashcards: [
    { q: "Define electric current and give its SI unit.", a: "The rate of flow of charge: I = Q/t. SI unit is the ampere (A); 1 A = 1 coulomb per second." },
    { q: "Define potential difference.", a: "The work done in moving a unit charge from one point to another: V = W/Q. SI unit is the volt; 1 V = 1 joule per coulomb." },
    { q: "State Ohm's law.", a: "The current through a conductor is directly proportional to the potential difference across its ends, provided the temperature and other physical conditions remain constant. So V = IR." },
    { q: "How are an ammeter and a voltmeter connected, and why?", a: "An ammeter is connected in series and has very low resistance so it does not change the current. A voltmeter is connected in parallel and has very high resistance so it draws almost no current." },
    { q: "On what four factors does the resistance of a conductor depend?", a: "Length (R ∝ l), area of cross-section (R ∝ 1/A), the nature of the material (resistivity ρ), and temperature." },
    { q: "Define resistivity and give its unit.", a: "The resistance of a conductor of unit length and unit cross-sectional area: ρ = RA/l. Unit is the ohm-metre (Ω m). It depends only on the material and temperature." },
    { q: "A wire is cut into two equal halves. What happens to its resistance and resistivity?", a: "Each half has half the original resistance, since R ∝ l. The resistivity is unchanged, because it is a property of the material and not of the piece." },
    { q: "Why is nichrome used in heating elements?", a: "It has a very high resistivity (about 60 times that of copper), so it produces a lot of heat, and it does not oxidise readily even when glowing red hot." },
    { q: "Give the formulas for resistors in series and in parallel.", a: "Series: Rs = R₁ + R₂ + R₃, greater than the largest. Parallel: 1/Rp = 1/R₁ + 1/R₂ + 1/R₃, less than the smallest." },
    { q: "Why are domestic appliances connected in parallel?", a: "Each appliance gets the full supply voltage, each can be switched independently, and a fault in one does not stop the others." },
    { q: "State Joule's law of heating.", a: "The heat produced in a resistor is H = I²Rt — directly proportional to the square of the current, to the resistance, and to the time." },
    { q: "Write all the forms of the electric power formula.", a: "P = VI = I²R = V²/R = W/t. SI unit is the watt; 1 W = 1 J/s." },
    { q: "What is 1 kWh in joules?", a: "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J. This is the 'unit' used on electricity bills." },
    { q: "Why is tungsten used for bulb filaments?", a: "It has a very high melting point (about 3380 °C) so it can be heated until it glows without melting, and a high resistivity." },
    { q: "What is a fuse and how does it protect a circuit?", a: "A short piece of wire with a low melting point placed in series in the circuit. If the current exceeds the safe limit, the fuse wire melts and breaks the circuit before the wiring is damaged." },
  ],
  quiz: [
    { q: "How much charge flows when a current of 0.5 A passes for 4 minutes?", options: ["2 C", "120 C", "240 C", "0.5 C"], answer: 1, why: "Q = It = 0.5 × (4 × 60) = 0.5 × 240 = 120 C. Remember to convert minutes to seconds." },
    { q: "A voltmeter must be connected:", options: ["In series, with low resistance", "In parallel, with high resistance", "In series, with high resistance", "In parallel, with low resistance"], answer: 1, why: "It is connected across the component (parallel), and its high resistance ensures it draws negligible current." },
    { q: "The slope of a V–I graph for a conductor gives:", options: ["R", "1/R", "P", "ρ"], answer: 0, why: "If V is on the y-axis and I on the x-axis, the slope V/I = R. (Plotted the other way round, the slope would be 1/R — check the axes.)" },
    { q: "A wire of resistance 8 Ω is stretched so that its length doubles. Its new resistance is:", options: ["4 Ω", "16 Ω", "32 Ω", "8 Ω"], answer: 2, why: "Doubling the length halves the area (volume is constant), so R = ρl/A increases by a factor of 4: 8 × 4 = 32 Ω." },
    { q: "Three resistors of 2 Ω, 3 Ω and 6 Ω are in parallel. The equivalent resistance is:", options: ["11 Ω", "1 Ω", "0.5 Ω", "3.67 Ω"], answer: 1, why: "1/Rp = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 1, so Rp = 1 Ω — less than the smallest, as expected." },
    { q: "In a series circuit, the quantity that is the same through every resistor is:", options: ["Voltage", "Current", "Power", "Resistance"], answer: 1, why: "There is only one path, so the same current flows through all components. Voltage divides between them." },
    { q: "The resistance of a 220 V, 100 W bulb is:", options: ["220 Ω", "484 Ω", "100 Ω", "2.2 Ω"], answer: 1, why: "R = V²/P = 220²/100 = 48400/100 = 484 Ω." },
    { q: "If the current through a resistor is doubled, the heat produced in the same time:", options: ["Doubles", "Halves", "Becomes four times", "Stays the same"], answer: 2, why: "H = I²Rt, so heat is proportional to the square of the current. Doubling I gives 2² = 4 times the heat." },
    { q: "An electric heater of 1500 W runs for 2 hours daily. Units consumed in 30 days:", options: ["45", "90", "3", "900"], answer: 1, why: "Energy per day = 1.5 kW × 2 h = 3 kWh. Over 30 days = 90 kWh, i.e. 90 units." },
    { q: "Two identical bulbs are connected first in series and then in parallel to the same supply. They are brighter in:", options: ["Series", "Parallel", "Both the same", "Depends on the bulbs"], answer: 1, why: "In parallel each bulb gets the full voltage, so P = V²/R is larger. In series the voltage is shared, so each is dimmer." },
    { q: "Which of these has the highest resistivity?", options: ["Copper", "Aluminium", "Nichrome", "Silver"], answer: 2, why: "Nichrome's resistivity is roughly 60 times that of copper, which is why it is used as a heating element rather than as a connecting wire." },
    { q: "1 kilowatt-hour is equal to:", options: ["1000 J", "3600 J", "3.6 × 10⁶ J", "3.6 × 10³ J"], answer: 2, why: "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J." },
  ],
};
