import type { Chapter } from "@/lib/types";

export const ch14: Chapter = {
  slug: "magnetic-effects-of-electric-current",
  num: 14,
  title: "Magnetic Effects of Electric Current",
  unit: "current",
  unitName: "How Things Work — Effects of Current",
  marks: "Unit IV · 13 marks",
  minutes: 22,
  blurb: "A compass needle twitching next to a wire started all of this. Field lines, two hand rules, and the wiring inside your walls.",
  bigIdea: "Every electric current has a magnetic field around it. Get comfortable with the two hand rules — one for the direction of the field, one for the direction of the force — and the chapter is done.",
  syllabus: [
    "Magnetic field and field lines",
    "Magnetic field due to a current-carrying conductor",
    "Field due to a current-carrying coil or solenoid",
    "Force on a current-carrying conductor", "Fleming's left hand rule",
    "Direct and alternating current", "Frequency of AC", "Advantages of AC over DC",
    "Domestic electric circuits",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "What is not in the year-end paper", html: "For 2026-27, CBSE has moved the <strong>electric motor, electromagnetic induction and the electric generator</strong> to formative assessment only — they will not be set in the final exam. Everything else in this chapter is examinable. The topics are still worth reading, because they are the natural continuation of Fleming's rule." },

    { t: "h", text: "Oersted's accident" },
    { t: "p", html: "In 1820 Hans Christian Oersted noticed that a compass needle near a wire twitched whenever he switched the current on. Nobody had expected electricity and magnetism to be connected at all. That single observation opened up everything from motors to generators to the electric grid." },
    { t: "note", kind: "idea", html: "A <strong>magnetic field</strong> is the region around a magnet or a current where a magnetic force can be felt. It has both magnitude and direction, so it is a vector quantity — and we draw it using <strong>field lines</strong>." },
    { t: "list", items: [
      "Field lines run from <strong>north to south outside</strong> a magnet, and from south to north inside it — so they always form closed loops.",
      "The <strong>closer</strong> the lines, the stronger the field.",
      "Two field lines <strong>never cross</strong>. If they did, a compass at that point would have to point in two directions at once, which is impossible.",
    ] },

    { t: "h", text: "Fields around currents" },
    { t: "sim", id: "magnetic-field" },
    { t: "table", head: ["Conductor", "Shape of the field", "Rule to find direction"], rows: [
      ["<strong>Straight wire</strong>", "Concentric circles around the wire, closer together near the wire", "<strong>Right-hand thumb rule</strong> — thumb along the current, curled fingers give the field"],
      ["<strong>Circular loop</strong>", "Circles near the wire, becoming almost straight and parallel at the centre", "Right-hand thumb rule applied to any small part of the loop"],
      ["<strong>Solenoid</strong>", "Uniform and parallel inside; identical to a bar magnet outside", "Right-hand thumb rule; one end behaves as N, the other as S"],
    ] },
    { t: "note", kind: "why", title: "Why does the field get stronger with more turns?", html: "Each turn of a coil contributes its own field, and inside the coil all those contributions point the same way — so they add up. That is why a solenoid with many turns gives a much stronger field than a single loop carrying the same current." },
    { t: "note", kind: "real", html: "Put a soft iron core inside a solenoid and you get an <strong>electromagnet</strong>: a magnet you can switch off. Soft iron is used, not steel, because it loses its magnetism as soon as the current stops — which is exactly what a crane in a scrapyard, an electric bell or a doctor's MRI machine needs." },
    { t: "note", kind: "memory", html: "The field is stronger when: the <strong>current</strong> is larger, the <strong>number of turns</strong> is greater, or you are <strong>closer</strong> to the conductor. Those three factors cover most one-mark questions." },

    { t: "h", text: "Force on a current-carrying conductor" },
    { t: "p", html: "If a current produces a magnetic field, and a magnet has a magnetic field, then a current placed in a magnetic field should feel a push. It does — and the direction is given by Fleming's left hand rule." },
    { t: "sim", id: "fleming-lhr" },
    { t: "note", kind: "memory", title: "Fleming's left hand rule", html: "Stretch the thumb, forefinger and middle finger of your <strong>left</strong> hand so all three are mutually perpendicular. Then:<br><strong>F</strong>orefinger = <strong>F</strong>ield &nbsp;·&nbsp; <strong>C</strong>entral finger = <strong>C</strong>urrent &nbsp;·&nbsp; Thu<strong>M</strong>b = <strong>M</strong>otion (force).<br>The alphabetical order F, C, M matches Field, Current, Motion." },
    { t: "list", items: [
      "The force is <strong>largest</strong> when the current is at 90° to the field.",
      "The force is <strong>zero</strong> when the current is parallel to the field.",
      "Reverse either the current or the field and the force reverses. Reverse both and it stays the same.",
    ] },

    { t: "h", text: "AC and DC" },
    { t: "compare",
      left: { title: "Direct current (DC)", items: [
        "Flows in one direction only",
        "Comes from cells, batteries, solar panels",
        "Cannot be transmitted over long distances without large losses",
      ] },
      right: { title: "Alternating current (AC)", items: [
        "Reverses direction periodically",
        "In India it reverses <strong>50 times per second</strong>, so the frequency is <strong>50 Hz</strong>",
        "Direction changes every <strong>1/100 second</strong> — twice per cycle",
        "Can be stepped up and down using transformers, so it travels long distances with far less loss",
      ] } },
    { t: "note", kind: "exam", html: "That 1/100 second catches people out. The <em>cycle</em> takes 1/50 s, but the current reverses <em>twice</em> in every cycle, so the direction changes every 1/100 s. Both numbers get asked." },

    { t: "h", text: "The circuit in your walls" },
    { t: "sim", id: "domestic-circuit" },
    { t: "table", head: ["Wire", "Colour (Indian convention)", "Job"], rows: [
      ["<strong>Live</strong>", "Red or brown", "Carries the supply at 220 V"],
      ["<strong>Neutral</strong>", "Black or blue", "The return path, at 0 V"],
      ["<strong>Earth</strong>", "Green or yellow-green", "Connected to a metal plate buried in the ground — a safety escape route"],
    ] },
    { t: "list", items: [
      "The supply reaches the house through a main fuse and a meter, then splits into separate circuits — typically a 15 A circuit for heavy appliances (geyser, AC) and a 5 A circuit for lights and fans.",
      "All appliances are connected in <strong>parallel</strong>, so each gets the full 220 V and can be switched independently.",
      "The <strong>fuse or MCB</strong> is always placed in the <strong>live</strong> wire, so that when it breaks, the appliance is fully disconnected from the 220 V supply.",
      "The <strong>earth wire</strong> is connected to the metal body of appliances such as a fridge, geyser or iron.",
    ] },
    { t: "note", kind: "why", title: "How does an earth wire actually save you?", html: "If the live wire touches the metal casing of an appliance, that casing becomes live at 220 V. Touch it and the current would flow through <em>you</em> to the ground. The earth wire offers a path of far lower resistance straight into the ground, so the current goes that way instead — and the surge usually blows the fuse as well." },
    { t: "list", items: [
      "<strong>Short circuit</strong> — live and neutral touch directly. Resistance collapses to nearly zero, so current shoots up and the fuse melts instantly.",
      "<strong>Overloading</strong> — too many high-power appliances on one circuit, or a supply voltage surge. The current exceeds the safe rating and the fuse breaks the circuit before the wiring can overheat and catch fire.",
    ] },

    { t: "steps", title: "Why must a fuse always be in the live wire and never the neutral?",
      intro: "A two-mark safety question that comes up regularly.",
      steps: [
        "A fuse works by melting and breaking the circuit when the current is too high.",
        "If the fuse were in the <strong>neutral</strong> wire, it would break there — but the appliance would still be connected to the live wire.",
        "That means the appliance and its wiring would remain at 220 V even though it is not working.",
        "Anyone touching it would get a severe shock. Putting the fuse in the live wire disconnects the 220 V supply itself.",
      ],
      answer: "So that when the fuse blows, the appliance is completely isolated from the 220 V supply rather than being left live.",
    },
  ],
  formulas: [
    { name: "Right-hand thumb rule", expr: "Thumb along the current → curled fingers give the direction of the magnetic field" },
    { name: "Fleming's left hand rule", expr: "Forefinger = Field · Central finger = Current · Thumb = Motion (force)" },
    { name: "AC frequency in India", expr: "50 Hz", note: "Direction reverses every 1/100 second" },
    { name: "Domestic supply", expr: "220 V, 50 Hz", note: "Live at 220 V, neutral at 0 V" },
  ],
  examFocus: [
    "Three properties of magnetic field lines, especially why they never cross.",
    "The right-hand thumb rule, applied to a straight wire, a loop and a solenoid.",
    "Why a solenoid behaves like a bar magnet, and why soft iron is used in an electromagnet.",
    "Fleming's left hand rule with the F-C-M mnemonic, and what happens when you reverse current or field.",
    "AC vs DC, the 50 Hz frequency, the 1/100 second reversal, and one advantage of AC.",
    "The three wires with colours and functions, plus a labelled domestic circuit diagram.",
    "Short circuit and overloading defined, and why the fuse goes in the live wire.",
  ],
  flashcards: [
    { q: "What did Oersted discover?", a: "That a compass needle placed near a current-carrying wire is deflected — showing that an electric current produces a magnetic field around it." },
    { q: "Give three properties of magnetic field lines.", a: "They run from north to south outside a magnet and south to north inside, forming closed loops. The closer they are, the stronger the field. They never intersect, because a compass cannot point in two directions at once." },
    { q: "State the right-hand thumb rule.", a: "Hold the conductor in your right hand with the thumb pointing in the direction of the current. Your curled fingers then show the direction of the magnetic field lines around it." },
    { q: "What is the shape of the field around a straight current-carrying wire?", a: "Concentric circles centred on the wire, in a plane perpendicular to it. The circles are closest together near the wire, showing the field is strongest there." },
    { q: "Why is the magnetic field inside a solenoid uniform?", a: "Each turn contributes a field pointing in the same direction inside the coil, so the contributions add and the resulting field is strong, straight and of the same strength throughout." },
    { q: "Why is soft iron used as the core of an electromagnet?", a: "Soft iron becomes strongly magnetised when current flows but loses its magnetism almost completely when the current stops — so the electromagnet can be switched off." },
    { q: "State Fleming's left hand rule.", a: "Stretch the thumb, forefinger and central finger of the left hand mutually perpendicular. Forefinger points along the field, central finger along the current, and the thumb gives the direction of motion (force) on the conductor." },
    { q: "When is the force on a current-carrying conductor in a magnetic field greatest and when is it zero?", a: "Greatest when the current is perpendicular (90°) to the field, and zero when the current is parallel to the field." },
    { q: "What is the frequency of AC in India, and how often does the current reverse direction?", a: "50 Hz. The current completes 50 cycles per second, and since it reverses twice in each cycle, the direction changes every 1/100 second." },
    { q: "Give one advantage of AC over DC.", a: "AC can be stepped up to a high voltage with a transformer for transmission, which greatly reduces energy losses over long distances, and stepped down again for use." },
    { q: "Name the three wires in a domestic circuit with their colours.", a: "Live — red or brown, at 220 V. Neutral — black or blue, at 0 V. Earth — green or yellow-green, connected to a metal plate in the ground." },
    { q: "What is the function of the earth wire?", a: "It provides a low-resistance path to the ground for any leakage current. If the live wire touches an appliance's metal body, current flows to earth instead of through a person touching it." },
    { q: "What is a short circuit?", a: "When the live and neutral wires come into direct contact, the resistance falls almost to zero and a very large current flows, which melts the fuse and breaks the circuit." },
    { q: "What is overloading?", a: "Drawing more current than a circuit is designed for, either because too many high-power appliances are on the same circuit or because of a voltage surge. It causes the wiring to overheat, which is why a fuse is fitted." },
    { q: "Why is a fuse connected in the live wire?", a: "So that when it blows, the appliance is completely disconnected from the 220 V supply. A fuse in the neutral wire would leave the appliance live and dangerous." },
  ],
  quiz: [
    { q: "Two magnetic field lines can never intersect because:", options: ["They are parallel", "A compass would have to point in two directions at once", "They repel each other", "They are closed loops"], answer: 1, why: "At the point of intersection there would be two different directions for the field, which is physically impossible." },
    { q: "The magnetic field around a long straight current-carrying wire is:", options: ["Uniform and straight", "Concentric circles around the wire", "Radial from the wire", "Zero"], answer: 1, why: "The field lines form concentric circles in a plane perpendicular to the wire, getting weaker further away." },
    { q: "If the current in a straight wire is reversed, the magnetic field lines:", options: ["Disappear", "Reverse their direction", "Become stronger", "Are unchanged"], answer: 1, why: "By the right-hand thumb rule, reversing the thumb (current) reverses the direction the fingers curl — so the field reverses." },
    { q: "A solenoid carrying current behaves like:", options: ["An electric cell", "A bar magnet", "A resistor", "A capacitor"], answer: 1, why: "Its field pattern outside is identical to that of a bar magnet, with a north pole at one end and a south pole at the other." },
    { q: "In Fleming's left hand rule, the central finger represents:", options: ["Field", "Current", "Motion", "Force"], answer: 1, why: "Forefinger = Field, Central finger = Current, Thumb = Motion. The mnemonic is F-C-M." },
    { q: "The force on a current-carrying conductor in a magnetic field is zero when the current is:", options: ["Perpendicular to the field", "At 45° to the field", "Parallel to the field", "Very large"], answer: 2, why: "Force is maximum at 90° and falls to zero when the current direction is along the field." },
    { q: "The frequency of AC supply in India is:", options: ["50 Hz", "60 Hz", "100 Hz", "220 Hz"], answer: 0, why: "India uses 220 V, 50 Hz AC. In some countries such as the USA it is 60 Hz." },
    { q: "AC in India changes direction every:", options: ["1/50 second", "1/100 second", "1 second", "50 seconds"], answer: 1, why: "One full cycle takes 1/50 s, but the current reverses twice per cycle, so the direction changes every 1/100 s." },
    { q: "The colour of the earth wire in the Indian convention is:", options: ["Red", "Black", "Green", "Blue"], answer: 2, why: "Green (or green with a yellow stripe) is the earth wire. Red or brown is live and black or blue is neutral." },
    { q: "A fuse is connected in series with the:", options: ["Neutral wire", "Earth wire", "Live wire", "Any wire"], answer: 2, why: "Putting it in the live wire ensures that when it blows, the 220 V supply itself is disconnected from the appliance." },
    { q: "Soft iron is preferred over steel for an electromagnet core because it:", options: ["Is cheaper", "Loses its magnetism when the current stops", "Is stronger", "Conducts electricity better"], answer: 1, why: "The whole point of an electromagnet is that it can be switched off, which requires a core that does not retain magnetism." },
    { q: "Household appliances are connected in parallel so that:", options: ["Less current is used", "Each gets the full 220 V and works independently", "The wiring is cheaper", "The fuse never blows"], answer: 1, why: "Parallel wiring gives every appliance the full supply voltage and lets each be switched on and off without affecting the others." },
  ],
};
