import type { Chapter } from "@/lib/types";

export const ch15: Chapter = {
  slug: "our-environment",
  num: 15,
  title: "Our Environment",
  unit: "environment",
  unitName: "Natural Resources — Environment",
  marks: "Unit V · 5 marks",
  minutes: 14,
  blurb: "Small chapter, easy marks. Food chains, why energy runs out after four links, and the two environmental problems you must be able to explain.",
  bigIdea: "Energy flows through an ecosystem in one direction and shrinks by 90% at every step. Matter, by contrast, cycles round — unless we make things that nothing can break down.",
  syllabus: [
    "Ecosystem", "Environmental problems", "Ozone depletion",
    "Waste production and their solutions",
    "Biodegradable and non-biodegradable substances",
  ],
  blocks: [
    { t: "h", text: "What an ecosystem is made of" },
    { t: "p", html: "An <strong>ecosystem</strong> is all the living organisms in an area together with the non-living physical factors around them — soil, water, temperature, sunlight. A forest, a pond and a lake are natural ecosystems; a garden, a crop field and an aquarium are artificial ones." },
    { t: "table", head: ["Component", "Role", "Examples"], rows: [
      ["<strong>Producers</strong>", "Make their own food using sunlight", "Green plants, blue-green algae"],
      ["<strong>Consumers</strong>", "Depend on producers directly or indirectly", "Herbivores, carnivores, omnivores, parasites"],
      ["<strong>Decomposers</strong>", "Break down dead remains into simple substances that go back to the soil", "Bacteria, fungi"],
    ] },
    { t: "note", kind: "idea", html: "Decomposers are the recycling department. Without them, nutrients would stay locked inside dead bodies and the soil would never be replenished — producers would have nothing to grow with, and the whole ecosystem would grind to a halt." },
    { t: "note", kind: "trap", html: "An aquarium is an <strong>artificial</strong> and <em>incomplete</em> ecosystem — it needs a human to clean it and to feed the fish, because it has no proper decomposer cycle of its own. That is a standard question." },

    { t: "h", text: "Food chains and the 10% law" },
    { t: "sim", id: "food-chain" },
    { t: "p", html: "A <strong>food chain</strong> is a series of organisms in which each eats the previous one. Each step is a <strong>trophic level</strong>. In reality organisms eat several different things, so many chains interlink into a <strong>food web</strong>." },
    { t: "formula", name: "The 10% law (Lindeman)", expr: "Only ~10% of the energy at one trophic level passes to the next",
      where: ["The other 90% is lost as heat, in movement, and in life processes"] },
    { t: "note", kind: "why", title: "Why are food chains only 3–4 links long?", html: "Start with 10,000 J in the plants. The herbivore gets 1,000 J, the small carnivore 100 J, the next 10 J. By the fifth level there is almost nothing left to support an animal. The energy simply runs out — which is also why there are always far fewer tigers than deer." },
    { t: "note", kind: "idea", html: "Energy flow is <strong>unidirectional</strong>: it enters as sunlight, passes up the chain, and leaves as heat. It never comes back. Matter, in contrast, cycles — decomposers return it to the soil for reuse." },
    { t: "note", kind: "real", title: "Biomagnification", html: "Pesticides such as DDT do not break down, and they are not excreted. So they accumulate in each organism and become <strong>more concentrated</strong> at every trophic level. Energy shrinks up the chain but poison concentrates — which is why top predators, and human beings, carry the highest loads. It is the single best argument against non-biodegradable chemicals." },

    { t: "h", text: "Biodegradable and non-biodegradable" },
    { t: "sim", id: "waste-sorter" },
    { t: "compare",
      left: { title: "Biodegradable", items: [
        "Broken down by decomposers into simple substances",
        "Paper, cotton, wood, food waste, cow dung, leather",
        "Return nutrients to the soil",
        "Can still cause problems if produced faster than decomposers can handle — foul smell, disease",
      ] },
      right: { title: "Non-biodegradable", items: [
        "Cannot be broken down by decomposers",
        "Plastic, glass, metals, DDT, thermocol, synthetic fibres",
        "Accumulate in the environment for decades or centuries",
        "Enter food chains and undergo biomagnification",
      ] } },
    { t: "note", kind: "memory", html: "Rough test: if it came from a plant or an animal, it is usually biodegradable. If it was made in a factory from minerals or petroleum, it usually is not." },
    { t: "p", html: "Ways to manage waste, and the board wants specifics:" },
    { t: "list", items: [
      "<strong>Segregation at source</strong> — separating wet (biodegradable) and dry (non-biodegradable) waste before it is collected.",
      "<strong>Composting and vermicomposting</strong> — turning kitchen and garden waste into manure.",
      "<strong>Recycling</strong> — reprocessing paper, glass, metal and some plastics into new products.",
      "<strong>Sewage treatment</strong> before releasing water into rivers.",
      "<strong>Reduce and reuse</strong> — reducing consumption is the most effective step, because waste that is never created needs no disposal at all.",
    ] },

    { t: "h", text: "The ozone layer" },
    { t: "sim", id: "ozone-shield" },
    { t: "p", html: "Ozone is O₃ — three oxygen atoms instead of the usual two. High up in the stratosphere it forms a thin layer that absorbs most of the sun's ultraviolet radiation. UV damages living cells: too much of it causes skin cancer and cataract in humans and harms crops and plankton." },
    { t: "eq", lines: [
      "O₂ &nbsp;—<span class='faint'>UV</span>→&nbsp; O + O",
      "O + O₂ → O₃&nbsp;&nbsp;<span class='faint'>(ozone is formed high in the atmosphere)</span>",
    ] },
    { t: "note", kind: "why", title: "What damaged it?", html: "<strong>CFCs</strong> — chlorofluorocarbons — used in refrigerators, air conditioners and aerosol spray cans. UV breaks a CFC molecule apart, releasing a chlorine atom that destroys ozone molecules and then survives to destroy more. A single chlorine atom can break down thousands." },
    { t: "note", kind: "real", html: "In 1987 the world agreed the <strong>Montreal Protocol</strong> to freeze and then phase out CFC production, and it worked — the ozone layer is slowly recovering. It remains the clearest proof that global environmental damage can be reversed when countries act together. This is a favourite value-based question." },
    { t: "note", kind: "trap", html: "Do not confuse the two. Ozone <em>depletion</em> is caused by CFCs and lets in more UV. The <em>greenhouse effect</em> is caused by CO₂ and other gases trapping heat, which causes global warming. Different gases, different mechanism, different problem." },

    { t: "steps", title: "In a food chain grass → deer → tiger, if the grass has 10,000 J of energy, how much reaches the tiger?",
      intro: "One of the easiest numerical questions in the whole paper.",
      steps: [
        "Grass (producer, T₁) holds 10,000 J.",
        "Only 10% passes to the deer: 10% of 10,000 = <strong>1,000 J</strong>.",
        "Only 10% of that passes to the tiger: 10% of 1,000 = <strong>100 J</strong>.",
        "So 9,900 J of the original 10,000 J has been lost as heat and used up in life processes.",
      ],
      answer: "The tiger receives 100 J — just 1% of the energy the grass originally captured.",
    },
  ],
  formulas: [
    { name: "10% law", expr: "Energy at next level = 10% of the level below", note: "Proposed by Lindeman. Explains why food chains are short." },
  ],
  examFocus: [
    "Producers, consumers and decomposers with two examples each, and why decomposers are essential.",
    "Why an aquarium is an incomplete artificial ecosystem.",
    "Food chain vs food web, and the 10% law with a worked calculation.",
    "Why energy flow is unidirectional and food chains are limited to 3–4 links.",
    "Biomagnification, with DDT as the example.",
    "Biodegradable vs non-biodegradable with four examples each, and three disposal methods.",
    "How CFCs deplete ozone, the health effects of UV, and the Montreal Protocol.",
    "Not confusing ozone depletion with the greenhouse effect.",
  ],
  flashcards: [
    { q: "Define an ecosystem and give two natural and two artificial examples.", a: "All the interacting organisms in an area together with the non-living physical factors. Natural: forest, pond, lake. Artificial: garden, crop field, aquarium." },
    { q: "Why are decomposers essential to an ecosystem?", a: "They break down dead remains and waste into simple substances that return to the soil, so nutrients can be reused by producers. Without them nutrients would stay locked in dead matter." },
    { q: "Why is an aquarium called an incomplete ecosystem?", a: "It is artificial and cannot sustain itself — it needs humans to clean it and feed the fish, because it lacks a full decomposer cycle." },
    { q: "Differentiate a food chain from a food web.", a: "A food chain is a single linear series of organisms each eating the previous one. A food web is many interconnected food chains, which is what actually happens in nature since most organisms eat several things." },
    { q: "State the 10% law.", a: "Only about 10% of the energy at one trophic level is transferred to the next; the remaining 90% is lost as heat and used in life processes." },
    { q: "Why are food chains limited to three or four trophic levels?", a: "Because only 10% of energy passes on at each step. After three or four levels there is too little energy left to support another organism." },
    { q: "Why is the flow of energy in an ecosystem unidirectional?", a: "Energy enters as sunlight, passes up the trophic levels, and is finally lost as heat. It cannot be recaptured or sent back down the chain." },
    { q: "What is biomagnification?", a: "The increase in concentration of a harmful non-biodegradable chemical, such as DDT, at each successive trophic level, because it is neither broken down nor excreted. Top-level consumers accumulate the most." },
    { q: "Give four examples each of biodegradable and non-biodegradable waste.", a: "Biodegradable: paper, cotton cloth, food waste, cow dung, wood. Non-biodegradable: plastic, glass, DDT, thermocol, aluminium foil." },
    { q: "Suggest three methods of waste management.", a: "Segregation of wet and dry waste at source, composting or vermicomposting of biodegradable waste, and recycling of paper, glass, metal and plastic. Reducing consumption is the most effective step of all." },
    { q: "What is ozone and why is it important?", a: "Ozone is O₃, formed high in the stratosphere. It absorbs most of the sun's harmful ultraviolet radiation, protecting living organisms from skin cancer, cataract and crop damage." },
    { q: "How is ozone formed in the upper atmosphere?", a: "UV radiation splits an O₂ molecule into free oxygen atoms, and each free atom combines with another O₂ molecule to form O₃." },
    { q: "How do CFCs deplete the ozone layer?", a: "UV breaks CFC molecules apart, releasing chlorine atoms. Each chlorine atom destroys ozone molecules and is regenerated afterwards, so a single atom can destroy thousands of ozone molecules." },
    { q: "What was the Montreal Protocol?", a: "A 1987 international agreement to freeze and then phase out the production of CFCs. It has worked — the ozone layer is slowly recovering — and it shows that global cooperation can reverse environmental damage." },
    { q: "Differentiate ozone depletion from the greenhouse effect.", a: "Ozone depletion is caused by CFCs destroying stratospheric ozone, letting in harmful UV. The greenhouse effect is caused by CO₂ and other gases trapping infrared heat near the surface, causing global warming." },
  ],
  quiz: [
    { q: "Which of these is a decomposer?", options: ["Grass", "Deer", "Fungi", "Hawk"], answer: 2, why: "Fungi and bacteria break down dead organic matter into simple substances that return to the soil." },
    { q: "In the food chain grass → grasshopper → frog → snake, the frog is a:", options: ["Producer", "Primary consumer", "Secondary consumer", "Decomposer"], answer: 2, why: "Grass is the producer, the grasshopper is the primary consumer, and the frog — which eats the grasshopper — is the secondary consumer." },
    { q: "If producers have 20,000 J of energy, the third trophic level receives about:", options: ["2,000 J", "200 J", "20 J", "2 J"], answer: 1, why: "10% at each step: 20,000 → 2,000 → 200 J at the third trophic level." },
    { q: "Energy flow in an ecosystem is:", options: ["Cyclic", "Unidirectional", "Bidirectional", "Random"], answer: 1, why: "Energy enters as sunlight and leaves as heat. Unlike matter, it never cycles back." },
    { q: "Which of these is non-biodegradable?", options: ["Cotton cloth", "Cow dung", "Aluminium foil", "Paper"], answer: 2, why: "Aluminium foil cannot be broken down by decomposers. The other three are of plant or animal origin and are biodegradable." },
    { q: "Accumulation of DDT increasing at each trophic level is called:", options: ["Bioaccumulation of energy", "Biomagnification", "Eutrophication", "Decomposition"], answer: 1, why: "DDT is neither broken down nor excreted, so its concentration rises at every successive level of the food chain." },
    { q: "The ozone layer protects us by absorbing:", options: ["Infrared radiation", "Ultraviolet radiation", "Radio waves", "Visible light"], answer: 1, why: "Ozone absorbs most of the sun's UV, which would otherwise cause skin cancer, cataract and damage to crops." },
    { q: "The main cause of ozone depletion is:", options: ["Carbon dioxide", "Methane", "Chlorofluorocarbons", "Sulphur dioxide"], answer: 2, why: "UV breaks CFC molecules, releasing chlorine atoms that destroy ozone catalytically — one atom can destroy thousands of ozone molecules." },
    { q: "The Montreal Protocol of 1987 was an agreement to:", options: ["Reduce CO₂ emissions", "Phase out CFC production", "Ban plastic", "Protect forests"], answer: 1, why: "It froze and then phased out CFC production worldwide, and the ozone layer has begun to recover as a result." },
    { q: "An aquarium needs regular cleaning because:", options: ["Fish dislike dirty water", "It lacks decomposers to recycle waste", "Sunlight cannot reach it", "It has too many producers"], answer: 1, why: "It is an artificial and incomplete ecosystem with no proper decomposer cycle, so waste accumulates unless humans remove it." },
    { q: "The chemical formula of ozone is:", options: ["O₂", "O₃", "CO₂", "NO₂"], answer: 1, why: "Ozone is a molecule of three oxygen atoms, O₃." },
    { q: "The most effective single step in waste management is:", options: ["Recycling", "Incineration", "Reducing consumption", "Landfilling"], answer: 2, why: "Waste that is never created needs no collection, transport or disposal at all — reduction beats every downstream method." },
  ],
  keyTopics: [
    { name: "Food chain, food web and trophic levels", importance: "high", note: "Frequently tested through identify-the-level and food-chain-construction questions." },
    { name: "The 10% law and energy-flow numericals", importance: "high", note: "A guaranteed short numerical: given energy at one level, find it at another." },
    { name: "Ecosystem components — producers, consumers, decomposers", importance: "high", note: "Definitions with examples, and why decomposers are essential to nutrient recycling." },
    { name: "Ozone layer depletion, CFCs and the Montreal Protocol", importance: "high", note: "A regular 3–5 mark question, often paired with a value-based question on international cooperation." },
    { name: "Biodegradable vs non-biodegradable substances, biomagnification", importance: "medium", note: "Classification questions with examples, and the DDT/biomagnification explanation." },
    { name: "Waste management methods", importance: "medium", note: "Segregation, composting, recycling and reduction — usually a short-answer list question." },
    { name: "Natural vs artificial ecosystems", importance: "low", note: "The standard 'why is an aquarium incomplete' question." },
  ],
  written: [
    { q: "Name two decomposers.", marks: 1, kind: "short", importance: "low",
      answer: "<strong>Bacteria</strong> and <strong>fungi</strong>." },
    { q: "Write the chemical formula of ozone.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>O₃</strong> — a molecule made of three oxygen atoms." },
    { q: "Differentiate between a food chain and a food web.", marks: 2, kind: "short", importance: "high",
      answer: "A <strong>food chain</strong> is a single, linear sequence of organisms in which each is eaten by the next. A <strong>food web</strong> is a network of many interconnected food chains, since most organisms in nature actually feed on more than one kind of organism." },
    { q: "Why is an aquarium considered an incomplete, artificial ecosystem?", marks: 2, kind: "short", importance: "medium",
      answer: "It is <strong>artificial</strong> because it is set up by humans, and <strong>incomplete</strong> because it lacks a proper community of decomposers to recycle waste and nutrients on its own — a person must regularly clean it and feed the fish for it to keep functioning." },
    { q: "State the 10% law of energy transfer in a food chain.", marks: 2, kind: "short", importance: "high",
      answer: "Only about <strong>10%</strong> of the energy available at one trophic level is passed on to the next trophic level; the remaining <strong>90%</strong> is lost as heat and used up in the organism's own life processes." },
    { q: "If 1,00,000 J of energy is available to the producers in a food chain, calculate the amount of energy available to the organisms at the third trophic level.", marks: 3, kind: "numerical", importance: "high",
      answer: "Producers (T₁) = 1,00,000 J.<br>Only 10% passes on at each step: T₂ = 10% of 1,00,000 = 10,000 J.<br>T₃ = 10% of 10,000 = <strong>1,000 J</strong>.<br>So the third trophic level receives 1,000 J — just 1% of the energy the producers originally captured." },
    { q: "Explain why the flow of energy in an ecosystem is unidirectional.", marks: 3, kind: "short", importance: "high",
      answer: "Energy enters an ecosystem as sunlight, is captured by producers through photosynthesis, and then passes upward through successive trophic levels as one organism is eaten by another. At each step, most of the energy is lost permanently as heat through respiration and other life processes. Since this lost heat cannot be recaptured by producers and sent back up the chain, energy can only flow <strong>one way</strong> — it never cycles back, unlike matter." },
    { q: "What is biomagnification? Explain with the help of an example.", marks: 3, kind: "short", importance: "medium",
      answer: "<strong>Biomagnification</strong> is the increase in the concentration of a harmful, non-biodegradable substance at each successive trophic level of a food chain, because the substance is neither broken down nor excreted by organisms.<br><strong>Example:</strong> the pesticide <strong>DDT</strong>, sprayed on crops, washes into water bodies and is taken up by algae in tiny amounts. Small fish eating large numbers of algae accumulate more DDT, and larger fish or birds eating many small fish accumulate the highest concentration of all — so top-level consumers, including humans, end up carrying the greatest load." },
    { q: "Explain how the depletion of the ozone layer takes place due to CFCs. What steps has the international community taken to address this problem?", marks: 5, kind: "long", importance: "high",
      answer: "Ozone (O₃) high in the stratosphere absorbs most of the sun's harmful ultraviolet (UV) radiation. <strong>Chlorofluorocarbons (CFCs)</strong>, released from refrigerators, air conditioners and aerosol sprays, drift up into the stratosphere, where UV radiation breaks them apart and releases <strong>chlorine atoms</strong>. Each chlorine atom reacts with and destroys an ozone molecule, and is regenerated in the process — so a single chlorine atom can go on to destroy thousands of ozone molecules over time. This thins the ozone layer, letting more UV radiation reach the Earth's surface, where it can cause skin cancer, cataract, and damage to crops and aquatic life.<br>In <strong>1987</strong>, nations of the world signed the <strong>Montreal Protocol</strong>, agreeing to freeze and then progressively phase out the production of CFCs and other ozone-depleting substances. This international cooperation has worked — the ozone layer is now slowly recovering, making it a strong example of global action successfully reversing environmental damage." },
    { q: "What is meant by biodegradable and non-biodegradable substances? Give four examples of each, and explain why non-biodegradable substances are more harmful to the environment.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Biodegradable</strong> substances are those that can be broken down into simple, harmless substances by the action of decomposers such as bacteria and fungi — for example, <strong>paper, cotton cloth, food waste and cow dung</strong>.<br><strong>Non-biodegradable</strong> substances cannot be broken down by decomposers and remain unchanged in the environment for very long periods — for example, <strong>plastic, glass, DDT and aluminium foil</strong>.<br>Non-biodegradable substances are more harmful because they <strong>persist and accumulate</strong> in soil, water and air for decades or centuries rather than being recycled back into the ecosystem; and where they enter a food chain (as DDT does), their concentration keeps rising at each trophic level through <strong>biomagnification</strong>, eventually reaching harmful levels in top consumers such as birds of prey and humans." },
  ],
  assertionReason: [
    { assertion: "DDT becomes more concentrated as it passes through successive trophic levels of a food chain.",
      reason: "DDT is non-biodegradable and is neither broken down nor excreted by the organisms that ingest it.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A: because DDT cannot be metabolised or removed from the body, each organism retains what it has consumed, so its concentration keeps rising at every higher trophic level (biomagnification)." },
    { assertion: "Food chains are usually limited to only 3 or 4 trophic levels.",
      reason: "Green plants can prepare their own food using sunlight through the process of photosynthesis.",
      answer: 1, importance: "medium",
      why: "Both statements are true individually, but R is irrelevant to A — the actual reason chains are short is that only about 10% of energy passes from one trophic level to the next, not the plants' ability to photosynthesise." },
    { assertion: "Non-biodegradable substances such as plastic persist in the environment for a very long time.",
      reason: "Non-biodegradable substances are broken down completely by decomposers over a period of several years.",
      answer: 2, importance: "high",
      why: "A is true. R is false and self-contradictory: by definition, non-biodegradable substances are <em>not</em> broken down by decomposers at all — that is precisely why they persist for so long." },
    { assertion: "Global warming and the depletion of the ozone layer are caused by the same set of gases.",
      reason: "Ozone depletion is caused mainly by chlorofluorocarbons, while global warming (the greenhouse effect) is caused mainly by carbon dioxide and other greenhouse gases.",
      answer: 3, importance: "medium",
      why: "A is false — the two phenomena are caused by different gases and involve different mechanisms. R is true, and it is precisely because the causes are different that A is false: R does not support A, it contradicts it." },
  ],
  caseStudies: [
    { title: "Energy flow in a pond ecosystem", importance: "high",
      source: "In a pond ecosystem, the food chain is: Phytoplankton → Zooplankton → Small fish → Large fish. The phytoplankton fix 1,00,000 J of solar energy through photosynthesis.",
      parts: [
        { q: "Name the producers and the primary consumers in this food chain.", marks: 1, answer: "<strong>Producers:</strong> phytoplankton. <strong>Primary consumers:</strong> zooplankton." },
        { q: "Calculate the amount of energy available to the large fish.", marks: 2, answer: "Applying the 10% law at each step: phytoplankton = 1,00,000 J → zooplankton = 10,000 J → small fish = 1,000 J → large fish = <strong>100 J</strong>." },
        { q: "If this pond became contaminated with DDT, which organism in the chain would accumulate the highest concentration, and why?", marks: 2, answer: "The <strong>large fish</strong>, the top consumer. DDT is non-biodegradable and cannot be excreted, so its concentration increases at each successive trophic level through <strong>biomagnification</strong> — the organism at the top of the chain ends up with the highest dose." },
      ] },
    { title: "Segregating a society's waste", importance: "medium",
      source: "A residential society generates daily waste that includes vegetable peels, plastic packets, glass bottles and old batteries. The society decides to start a waste-segregation programme using separate bins for wet and dry waste.",
      parts: [
        { q: "Classify the four types of waste mentioned as biodegradable or non-biodegradable.", marks: 2, answer: "<strong>Biodegradable:</strong> vegetable peels. <strong>Non-biodegradable:</strong> plastic packets, glass bottles, old batteries." },
        { q: "Suggest a suitable method of disposing of the vegetable peels that would also benefit the society's garden.", marks: 1, answer: "<strong>Composting or vermicomposting</strong> the peels to convert them into manure for the garden." },
        { q: "Why is it important to segregate waste at source instead of dumping all of it together?", marks: 2, answer: "Segregation keeps biodegradable waste from contaminating recyclable dry waste, makes recycling and composting far more effective, reduces the volume sent to landfill, and allows hazardous items like batteries to be collected and disposed of separately so they do not leak toxic substances into the soil and water." },
      ] },
  ],
};
