import type { Chapter } from "@/lib/types";

export const ch01: Chapter = {
  slug: "nationalism-in-europe",
  num: 1,
  title: "The Rise of Nationalism in Europe",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · 20 marks",
  minutes: 20,
  blurb: "How a continent of kingdoms and empires became a continent of nation-states — starting with one revolution in France.",
  bigIdea: "A nation is not a natural fact. It has to be imagined, argued for and often fought for — and in nineteenth-century Europe that took eighty years.",
  syllabus: [
    "The French Revolution and the idea of the nation",
    "The making of nationalism in Europe",
    "The age of revolutions, 1830–1848",
    "The making of Germany and Italy",
    "Visualising the nation",
    "Nationalism and imperialism",
  ],
  blocks: [
    { t: "h", text: "Where the idea came from" },
    { t: "p", html: "In 1848 the French artist <strong>Frédéric Sorrieu</strong> printed four images of a world made up of democratic and social Republics. Peoples of Europe and America march in a long train to offer homage to the Statue of Liberty. It is a utopia — a vision of a society so ideal that it is unlikely to exist. But it tells you what nationalists of that generation wanted." },
    { t: "sim", id: "europe-timeline" },
    { t: "note", kind: "idea", html: "The first clear expression of nationalism came with the <strong>French Revolution in 1789</strong>. Sovereignty was transferred from the monarchy to a body of French citizens. A new flag, a new anthem, a centralised administration, uniform weights and measures, and French as the national language — a nation was being deliberately constructed." },
    { t: "note", kind: "why", title: "Napoleon: liberator or conqueror?", html: "The <strong>Civil Code of 1804</strong>, known as the Napoleonic Code, abolished privileges based on birth, established equality before the law and secured the right to property. Napoleon carried it into the territories he controlled, simplifying administrative divisions and abolishing the feudal system.<br><br>But increased taxation, censorship and forced conscription made the same people resent French rule. This is the standard five-mark question: the reforms were welcomed, the domination was not." },

    { t: "h", text: "Who wanted a nation, and why" },
    { t: "table", head: ["Group", "What they wanted"], rows: [
      ["<strong>The liberal middle classes</strong>", "Freedom for the individual and equality before the law; government by consent; an end to aristocratic privilege. Note that liberal did <em>not</em> mean universal suffrage — only property-owning men could vote."],
      ["<strong>Industrialists and merchants</strong>", "An end to the maze of tariffs, currencies and weights that made trade almost impossible. Economic nationalism came before political nationalism."],
      ["<strong>Conservatives</strong>", "After 1815, to preserve monarchy, Church, social hierarchies and property. They believed change should be slow, and they set up the Congress of Vienna to enforce it."],
      ["<strong>Revolutionaries</strong>", "Secret societies to train revolutionaries and spread their ideas. <strong>Giuseppe Mazzini</strong> founded Young Italy in Marseilles and Young Europe in Berne."],
    ] },
    { t: "note", kind: "real", html: "Metternich described Mazzini as &ldquo;the most dangerous enemy of our social order&rdquo;. That is how seriously the conservative order took the idea of the nation." },

    { t: "h", text: "The economic argument" },
    { t: "p", html: "In 1834 a customs union — the <strong>Zollverein</strong> — was formed at Prussia's initiative. It abolished tariff barriers between most German states and reduced the number of currencies from over thirty to two. A network of railways followed." },
    { t: "note", kind: "idea", html: "Economic unity came before political unity, and helped cause it. This is a favourite question: <em>how did economic factors contribute to German unification?</em> The Zollverein and the railways are the answer." },

    { t: "h", text: "1848 — the year of revolutions" },
    { t: "list", items: [
      "In February 1848 food shortages and unemployment brought Parisians onto the streets. Louis Philippe fled and a republic was proclaimed, with <strong>universal male suffrage</strong>.",
      "In May 1848, <strong>831 elected representatives</strong> met in St Paul's Church, Frankfurt, and drafted a constitution for a German nation headed by a monarchy subject to parliament. Friedrich Wilhelm IV of Prussia rejected the crown and joined the other monarchs in opposing the assembly.",
      "Women had participated actively but were admitted only as observers to the Frankfurt Parliament.",
      "The liberal revolutions failed. But the monarchies realised that concessions were now unavoidable, and serfdom and bonded labour were abolished in the Habsburg dominions and in Russia.",
    ] },

    { t: "h", text: "Germany and Italy" },
    { t: "compare",
      left: { title: "Germany — unified 1871", items: [
        "Led by <strong>Prussia</strong>, and by its chief minister <strong>Otto von Bismarck</strong>",
        "Achieved through <strong>three wars in seven years</strong> — against Denmark, Austria and France",
        "18 January 1871: Kaiser William I proclaimed German Emperor at Versailles",
        "Nation-building was carried out by the army and the Prussian bureaucracy",
        "The new state emphasised currency, banking, legal and judicial modernisation",
      ] },
      right: { title: "Italy — unified 1861–1871", items: [
        "Led by <strong>Sardinia-Piedmont</strong> and its minister <strong>Cavour</strong>",
        "Mazzini supplied the ideas; Cavour the diplomacy; <strong>Garibaldi</strong> and his volunteers the fighting",
        "1861: Victor Emmanuel II proclaimed king of united Italy. Venetia joined in 1866 and Rome in 1870",
        "Cavour spoke French better than Italian; most Italians could not read the language",
        "Garibaldi's volunteers were known as <strong>Red Shirts</strong>",
      ] } },
    { t: "note", kind: "exam", html: "The favourite comparison question: in <strong>both</strong> cases unification was led by a strong state and achieved by war and diplomacy, not by popular revolution — despite nationalism having begun as a popular, liberal movement." },

    { t: "h", text: "Britain — the other model" },
    { t: "p", html: "There was no British nation before the eighteenth century. English, Welsh, Scots and Irish were distinct ethnic groups. The English parliament, having seized power from the monarchy in 1688, extended English influence over the others. The <strong>Act of Union of 1707</strong> between England and Scotland created the United Kingdom of Great Britain; Ireland was forcibly incorporated in <strong>1801</strong>." },
    { t: "note", kind: "why", html: "Britain's nation was the result of <strong>a long process of internal conquest</strong>, not of a popular revolution. Scottish highland culture and the Gaelic language were systematically suppressed. The symbols of the new Britain — the flag, the anthem, the English language — were all English." },

    { t: "h", text: "Picturing the nation" },
    { t: "list", items: [
      "Artists personified nations as female figures — an <strong>allegory</strong>. <strong>Marianne</strong> stood for the French republic, with the red cap, the tricolour and the cockade. <strong>Germania</strong> wore a crown of oak leaves, because the German oak stands for heroism.",
      "Attributes carry meaning: broken chains = being freed; the breastplate with an eagle = the German empire's strength; the olive branch around the sword = willingness to make peace; the rays of the rising sun = the beginning of a new era.",
    ] },

    { t: "h", text: "Nationalism turns dangerous" },
    { t: "p", html: "After 1871 nationalism in Europe lost its idealism. Major powers manipulated the nationalist aspirations of subject peoples to further their own imperial aims. The <strong>Balkans</strong> — Greece, Romania, Bulgaria, Serbia, Bosnia-Herzegovina, Albania, Montenegro — became the region of most serious conflict. As the Ottoman Empire weakened, each group claimed independence and each big power backed a different claimant." },
    { t: "note", kind: "idea", html: "Nationalism, aligned with imperialism, led Europe to disaster in <strong>1914</strong>. The idea that began as a demand for liberty ended as a cause of the First World War — and that reversal is the point the chapter closes on." },
  ],
  examFocus: [
    "The French Revolution as the first expression of nationalism, with three concrete measures.",
    "Napoleon's Civil Code — the reforms, and why people still resented French rule.",
    "The Zollverein and the economic argument for German unification.",
    "The Frankfurt Parliament: what it attempted, and why it failed.",
    "A structured comparison of German and Italian unification.",
    "Britain's nation as internal conquest, not revolution.",
    "Allegories — Marianne, Germania — and the meaning of the attributes.",
    "How nationalism after 1871 combined with imperialism to produce the Balkans crisis.",
  ],
  flashcards: [
    { q: "What is a utopia? Who painted one in 1848?", a: "A vision of a society so ideal that it is unlikely to actually exist. Frédéric Sorrieu, a French artist, produced a series of four prints in 1848 visualising a world of democratic and social Republics." },
    { q: "Name three measures by which revolutionary France created a sense of nation.", a: "A new tricolour flag replacing the royal standard, a centralised administration with uniform laws, and the abolition of internal customs duties along with uniform weights and measures. French became the common national language." },
    { q: "What was the Napoleonic Code of 1804?", a: "The Civil Code of 1804. It abolished all privileges based on birth, established equality before the law, and secured the right to property. Napoleon carried it into the territories he controlled." },
    { q: "Why did people in Napoleon-controlled regions turn against French rule?", a: "Increased taxation, censorship, and forced conscription into the French armies. The administrative reforms were welcomed, but the political domination was not." },
    { q: "What did 'liberalism' mean in nineteenth-century Europe?", a: "Freedom for the individual and equality before the law, government by consent, and an end to autocracy. Note that the right to vote was restricted to property-owning men — it did not mean universal suffrage." },
    { q: "What was the Zollverein and why did it matter?", a: "A customs union formed in 1834 at Prussia's initiative. It abolished tariff barriers among most German states and reduced over thirty currencies to two, creating economic unity that made political unity far more likely." },
    { q: "Who was Giuseppe Mazzini?", a: "An Italian revolutionary who founded two underground societies — Young Italy in Marseilles and Young Europe in Berne. Metternich called him 'the most dangerous enemy of our social order'." },
    { q: "What happened at the Frankfurt Parliament in 1848?", a: "831 elected representatives met in St Paul's Church, Frankfurt, and drafted a constitution for a German nation headed by a monarchy subject to parliament. The King of Prussia rejected the crown and the assembly was eventually disbanded." },
    { q: "Who led German unification, and how?", a: "Otto von Bismarck of Prussia, with the help of the Prussian army and bureaucracy, through three wars over seven years — against Denmark, Austria and France. William I was proclaimed German Emperor at Versailles on 18 January 1871." },
    { q: "Name the three figures central to Italian unification.", a: "Giuseppe Mazzini supplied the ideas, Count Cavour of Sardinia-Piedmont the diplomacy, and Giuseppe Garibaldi the armed force with his volunteer Red Shirts." },
    { q: "How was the British nation formed?", a: "Not by revolution but by a long process of internal conquest. The Act of Union of 1707 joined England and Scotland; Ireland was forcibly incorporated in 1801. The symbols of Britain — flag, anthem, language — were all English." },
    { q: "What do Marianne and Germania represent?", a: "Female allegories of the nation. Marianne personified the French Republic, with the red cap, the tricolour and the cockade. Germania personified the German nation, wearing a crown of oak leaves since the German oak stands for heroism." },
    { q: "Why did the Balkans become the most serious source of conflict after 1871?", a: "As the Ottoman Empire weakened, each Balkan group claimed independence on the basis of nationality, while the major European powers each backed different claimants to extend their own influence — leading directly towards the First World War." },
  ],
  quiz: [
    { q: "The first clear expression of nationalism came with:", options: ["The Congress of Vienna", "The French Revolution of 1789", "The unification of Germany", "The Industrial Revolution"], answer: 1, why: "In 1789 sovereignty was transferred from the monarchy to the body of French citizens, and a deliberate programme of nation-building followed." },
    { q: "The Napoleonic Code of 1804 did NOT:", options: ["Abolish privileges based on birth", "Establish equality before the law", "Grant universal suffrage to women", "Secure the right to property"], answer: 2, why: "The Code brought legal equality and property rights but did not extend political rights to women." },
    { q: "The Congress of Vienna in 1815 was hosted by:", options: ["Napoleon", "Duke Metternich", "Bismarck", "Mazzini"], answer: 1, why: "The Austrian Chancellor Duke Metternich hosted the Congress, whose object was to restore the conservative order after Napoleon's defeat." },
    { q: "The Zollverein was:", options: ["A German parliament", "A customs union", "A secret society", "A treaty of peace"], answer: 1, why: "Formed in 1834 at Prussia's initiative, it abolished tariff barriers between German states and reduced dozens of currencies to two." },
    { q: "Young Italy was founded by:", options: ["Cavour", "Garibaldi", "Mazzini", "Victor Emmanuel II"], answer: 2, why: "Giuseppe Mazzini founded Young Italy in Marseilles and later Young Europe in Berne." },
    { q: "The Frankfurt Parliament met in:", options: ["The Rhineland", "St Paul's Church", "Versailles", "Vienna"], answer: 1, why: "831 elected representatives met in St Paul's Church, Frankfurt, in May 1848." },
    { q: "Germany was unified in:", options: ["1848", "1861", "1871", "1707"], answer: 2, why: "On 18 January 1871 the Prussian king William I was proclaimed German Emperor at Versailles." },
    { q: "Garibaldi's volunteers were known as the:", options: ["Red Shirts", "Black Hands", "Carbonari", "Jacobins"], answer: 0, why: "Garibaldi led a band of armed volunteers called the Red Shirts, who joined him in south Italy in 1860." },
    { q: "The Act of Union of 1707 united:", options: ["England and Ireland", "England and Scotland", "England and Wales", "Scotland and Ireland"], answer: 1, why: "It created the 'United Kingdom of Great Britain' from England and Scotland. Ireland was incorporated separately, in 1801." },
    { q: "Germania wore a crown of oak leaves because the German oak stands for:", options: ["Peace", "Justice", "Heroism", "Freedom"], answer: 2, why: "Each attribute in an allegory carries meaning — the oak stands for heroism, the broken chain for being freed, the olive branch for peace." },
    { q: "Nationalism after 1871 in Europe is best described as:", options: ["Increasingly liberal", "Aligned with imperialism and increasingly intolerant", "Fading away", "Purely economic"], answer: 1, why: "It lost its idealist character, became narrow and intolerant, and was used by the major powers to further imperial aims — leading to the Balkans crisis and the First World War." },
    { q: "The 1848 revolution in France resulted in:", options: ["Napoleon's return", "A republic with universal male suffrage", "The Congress of Vienna", "German unification"], answer: 1, why: "Louis Philippe fled, a National Assembly proclaimed a Republic, and universal male suffrage was granted." },
  ],
};
