import type { Chapter } from "@/lib/types";

export const ch02: Chapter = {
  slug: "nationalism-in-india",
  num: 2,
  title: "Nationalism in India",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · 20 marks · includes map work",
  minutes: 24,
  blurb: "Three mass movements, twenty-eight years, and one question the examiner keeps asking: why did different groups join, and why did they leave?",
  bigIdea: "Gandhi turned nationalism from a debate among the educated few into a movement of millions — but every group that joined brought its own grievance, and that is why the movements kept fracturing.",
  syllabus: [
    "The First World War, Khilafat and Non-Cooperation",
    "Differing strands within the movement",
    "Towards Civil Disobedience",
    "The sense of collective belonging",
  ],
  blocks: [
    { t: "h", text: "The chain of events" },
    { t: "sim", id: "india-freedom-timeline" },
    { t: "note", kind: "idea", title: "What satyagraha means", html: "Gandhi returned to India in January 1915 from South Africa. His method, <strong>satyagraha</strong>, emphasised the power of truth and the need to search for truth. It suggested that if the cause was true and the struggle against injustice, physical force was not necessary to fight the oppressor. It could unite all Indians." },
    { t: "list", items: [
      "<strong>Champaran, 1917</strong> — Bihar, to inspire the peasants to struggle against the oppressive plantation system.",
      "<strong>Kheda, 1917</strong> — Gujarat, to support peasants who could not pay revenue after crop failure and a plague epidemic.",
      "<strong>Ahmedabad, 1918</strong> — a satyagraha among cotton mill workers.",
    ] },

    { t: "h", text: "Rowlatt Act and Jallianwala Bagh" },
    { t: "p", html: "The <strong>Rowlatt Act</strong> was passed in 1919 through the Imperial Legislative Council despite the united opposition of Indian members. It gave the government enormous powers to repress political activities and allowed detention of political prisoners without trial for two years. Gandhi called a nationwide hartal on 6 April." },
    { t: "note", kind: "real", html: "On <strong>13 April 1919</strong> a crowd gathered in the enclosed ground of Jallianwala Bagh in Amritsar — some to protest, many for the annual Baisakhi fair. General Dyer blocked the exit and opened fire, killing hundreds. His stated object was to 'produce a moral effect'. It produced the opposite." },

    { t: "h", text: "Non-Cooperation and Khilafat, 1920–22" },
    { t: "p", html: "Gandhi took up the Khilafat issue — the Ottoman Emperor, the spiritual head of the Islamic world, was to be treated harshly after the war — to bring Hindus and Muslims into a single movement. In his book <em>Hind Swaraj</em> (1909) he had argued that British rule was established in India with the cooperation of Indians, and had survived only because of that cooperation. Withdraw it, and it would collapse within a year." },
    { t: "table", head: ["Group", "Why they joined", "What they wanted"], rows: [
      ["<strong>Middle class in towns</strong>", "Boycott of foreign goods and institutions", "Swaraj — but many students returned to school and lawyers to work when the cost proved high"],
      ["<strong>Peasants in Awadh</strong>", "Led by <strong>Baba Ramchandra</strong>", "Reduction of revenue, abolition of <em>begar</em> (forced labour), and the social boycott of oppressive landlords"],
      ["<strong>Tribals in Gudem Hills</strong>", "Led by <strong>Alluri Sitaram Raju</strong>", "Right to enter forests for grazing and fuel wood — closed by the colonial government. Raju used guerrilla warfare, not non-violence"],
      ["<strong>Plantation workers in Assam</strong>", "Freedom to move in and out of the enclosed space", "The right to leave the tea gardens — under the Inland Emigration Act of 1859 they could not leave without permission"],
      ["<strong>Business classes</strong>", "Protection against imports", "Refusal to trade in foreign goods and to finance foreign trade"],
    ] },
    { t: "note", kind: "why", title: "Why the movement was called off", html: "In February 1922 at <strong>Chauri Chaura</strong>, a procession turned violent and a police station was burnt. Gandhi called off Non-Cooperation, convinced that the movement was turning violent and that satyagrahis needed proper training. This is the standard question — and the honest answer includes that many leaders, including C. R. Das and Motilal Nehru, disagreed and formed the <strong>Swaraj Party</strong> to argue for a return to council politics." },
    { t: "note", kind: "trap", html: "Note how each group's idea of swaraj was different. For the peasants of Awadh it meant no revenue and no <em>begar</em>; for the tribals of Gudem it meant the forest; for business it meant protection from imports. When Congress could not deliver these, the groups fell away. That is the underlying answer to almost every 'why did the movement weaken' question." },

    { t: "h", text: "Civil Disobedience, 1930" },
    { t: "p", html: "In December 1929, under Jawaharlal Nehru, the Lahore Congress formalised the demand for <strong>Purna Swaraj</strong>. 26 January 1930 was to be celebrated as Independence Day. Gandhi then found the issue that could unite the country: salt." },
    { t: "note", kind: "idea", html: "Gandhi's letter to Viceroy Irwin on 31 January 1930 listed eleven demands, the most stirring of which was to abolish the salt tax. <strong>Salt is consumed by rich and poor alike</strong> — the tax and the government monopoly over its production revealed the most oppressive face of British rule." },
    { t: "p", html: "The <strong>Dandi March</strong> began on 12 March 1930. Gandhi and 78 volunteers walked about 240 miles from Sabarmati to Dandi over 24 days, reaching the coast on 6 April, where he broke the salt law by boiling sea water." },
    { t: "compare",
      left: { title: "Non-Cooperation, 1920–22", items: [
        "Refuse to cooperate with the colonial government",
        "Surrender titles; boycott schools, courts and councils",
        "Withdraw from institutions",
        "Called off after Chauri Chaura, February 1922",
      ] },
      right: { title: "Civil Disobedience, 1930–34", items: [
        "Actively <strong>break</strong> colonial laws, not merely refuse cooperation",
        "Make salt, refuse taxes, picket liquor shops, boycott foreign cloth",
        "Village officials resigned; forest people violated forest laws",
        "Gandhi–Irwin Pact 1931; relaunched, then lost momentum by 1934",
      ] } },
    { t: "note", kind: "exam", html: "The limits of Civil Disobedience are as examinable as its scope. <strong>Dalits</strong> largely stayed away — Ambedkar wanted separate electorates, which Gandhi opposed, and the conflict was settled by the <strong>Poona Pact of September 1932</strong>, giving the Depressed Classes reserved seats voted on by the general electorate. Many <strong>Muslim political organisations</strong> also kept their distance after relations soured following Non-Cooperation." },
    { t: "note", kind: "real", html: "Women participated in large numbers — picketing shops, manufacturing salt, going to jail. But Congress was long reluctant to give them positions of authority, seeing their role as symbolic. Gandhi himself framed their participation in terms of duty within the household." },

    { t: "h", text: "Making a nation feel like one" },
    { t: "list", items: [
      "<strong>Bharat Mata</strong> — the image of the nation as a mother figure. Bankim Chandra Chattopadhyay wrote <em>Vande Mataram</em> in the 1870s; <strong>Abanindranath Tagore</strong> painted his famous image of Bharat Mata as an ascetic figure, calm and spiritual.",
      "<strong>Folklore</strong> — Rabindranath Tagore collected ballads and nursery rhymes; in Madras, Natesa Sastri published a collection of Tamil folk tales, arguing that folklore was national literature.",
      "<strong>Flags</strong> — during the Swadeshi movement in Bengal a tricolour (green, yellow, red) with eight lotuses and a crescent moon was designed. By 1921 Gandhi had designed the Swaraj flag — red, green and white with a spinning wheel at the centre, representing self-help.",
      "<strong>History</strong> — Indians began to rewrite the past, glorifying ancient achievements and framing British rule as a period of decline.",
    ] },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "exam", title: "Map work", html: "For History the board expects you to locate: <strong>Congress sessions</strong> at Calcutta (September 1920), Nagpur (December 1920) and Madras (1927); the three <strong>satyagrahas</strong> at Champaran, Kheda and Ahmedabad; <strong>Jallianwala Bagh</strong>; and <strong>Dandi</strong>. The locator above has all eight under the history layer." },
  ],
  examFocus: [
    "Satyagraha defined, and the three early satyagrahas with their locations.",
    "The Rowlatt Act and Jallianwala Bagh, with the date 13 April 1919.",
    "Why different social groups joined Non-Cooperation — and how their idea of swaraj differed.",
    "Chauri Chaura and the reasons for calling off the movement, including the Swaraj Party's disagreement.",
    "Why salt was chosen, and the Dandi March details.",
    "A structured comparison of Non-Cooperation and Civil Disobedience.",
    "The limits of Civil Disobedience — Dalits, Muslim organisations, and the Poona Pact.",
    "Bharat Mata, folklore, flags and history as ways of creating collective belonging.",
    "The eight map locations.",
  ],
  flashcards: [
    { q: "What is satyagraha?", a: "Gandhi's method of mass agitation, emphasising the power of truth and the need to search for truth. If the cause is true and the struggle against injustice, physical force is not necessary to fight the oppressor." },
    { q: "Name Gandhi's three early satyagrahas in India and their causes.", a: "Champaran 1917 against the oppressive indigo plantation system; Kheda 1917 to support peasants who could not pay revenue after crop failure and plague; Ahmedabad 1918 among cotton mill workers." },
    { q: "What was the Rowlatt Act?", a: "An Act passed in 1919 by the Imperial Legislative Council despite united Indian opposition. It gave the government enormous powers to repress political activities and allowed detention without trial for two years." },
    { q: "What happened at Jallianwala Bagh?", a: "On 13 April 1919 a crowd gathered in an enclosed ground in Amritsar. General Dyer blocked the exit and opened fire, killing hundreds. His stated intention was to produce a 'moral effect'." },
    { q: "Why did Gandhi take up the Khilafat issue?", a: "To bring Hindus and Muslims together in a single united movement. A Khilafat Committee was formed in Bombay in March 1919, and the Non-Cooperation and Khilafat movements were launched together." },
    { q: "What did peasants in Awadh want from the movement?", a: "Reduction of revenue, abolition of begar (forced labour without payment), and the social boycott of oppressive landlords. They were led by Baba Ramchandra." },
    { q: "Who was Alluri Sitaram Raju?", a: "Leader of a militant guerrilla movement in the Gudem Hills of Andhra Pradesh. Tribal people resisted the closing of forests, which had ended their traditional rights to graze cattle and collect fuel wood." },
    { q: "Why was Non-Cooperation called off?", a: "After Chauri Chaura in February 1922, where a procession turned violent and a police station was burnt. Gandhi felt the movement was turning violent and that satyagrahis needed proper training." },
    { q: "What was the Swaraj Party and who founded it?", a: "Formed by C. R. Das and Motilal Nehru, who disagreed with calling off the movement and argued for a return to participation in the provincial councils." },
    { q: "Why did Gandhi choose salt for the Civil Disobedience movement?", a: "Salt is consumed by rich and poor alike and is one of the most essential items of food. The tax on it and the government monopoly over its production revealed the most oppressive face of British rule, so it could unite everyone." },
    { q: "Give the details of the Dandi March.", a: "Began 12 March 1930. Gandhi and 78 volunteers walked about 240 miles from Sabarmati to Dandi in 24 days, arriving on 6 April, where he broke the salt law by boiling sea water." },
    { q: "How did Civil Disobedience differ from Non-Cooperation?", a: "Non-Cooperation meant refusing to cooperate with the colonial government. Civil Disobedience went further — people were asked actively to break colonial laws, make salt, refuse taxes and picket shops." },
    { q: "What was the Poona Pact of September 1932?", a: "An agreement between Dr B. R. Ambedkar and Gandhi. It gave the Depressed Classes reserved seats in provincial and central legislative councils, voted on by the general electorate, instead of separate electorates." },
    { q: "Who painted Bharat Mata and what did the image show?", a: "Abanindranath Tagore. He portrayed Bharat Mata as an ascetic figure — calm, composed, divine and spiritual." },
    { q: "Describe the Swaraj flag of 1921.", a: "Designed by Gandhi. A tricolour of red, green and white with a spinning wheel at the centre, representing the Gandhian ideal of self-help." },
  ],
  quiz: [
    { q: "Gandhi returned to India from South Africa in:", options: ["1909", "1915", "1919", "1920"], answer: 1, why: "He returned in January 1915, having developed the method of satyagraha in South Africa." },
    { q: "The Champaran satyagraha of 1917 was against:", options: ["The salt tax", "The oppressive plantation system", "The Rowlatt Act", "Forest laws"], answer: 1, why: "Gandhi travelled to Champaran in Bihar to inspire the peasants to struggle against the oppressive indigo plantation system." },
    { q: "The Jallianwala Bagh massacre took place on:", options: ["6 April 1919", "13 April 1919", "12 March 1930", "26 January 1930"], answer: 1, why: "General Dyer opened fire on the crowd in the enclosed ground at Amritsar on 13 April 1919." },
    { q: "The Non-Cooperation movement was formally adopted at the Congress session in:", options: ["Calcutta, September 1920", "Nagpur, December 1920", "Lahore, 1929", "Madras, 1927"], answer: 1, why: "It was adopted at the Nagpur session in December 1920, after being discussed at the Calcutta session in September." },
    { q: "Baba Ramchandra led peasants in:", options: ["Gudem Hills", "Awadh", "Champaran", "Kheda"], answer: 1, why: "Baba Ramchandra led the Awadh peasant movement, demanding revenue reduction and the abolition of begar." },
    { q: "The Non-Cooperation movement was called off after the incident at:", options: ["Jallianwala Bagh", "Chauri Chaura", "Dandi", "Bardoli"], answer: 1, why: "In February 1922 a procession at Chauri Chaura turned violent and a police station was burnt, and Gandhi called off the movement." },
    { q: "Purna Swaraj was declared at the Congress session at:", options: ["Nagpur", "Lahore", "Madras", "Calcutta"], answer: 1, why: "The Lahore Congress of December 1929, under Jawaharlal Nehru, formalised the demand for complete independence." },
    { q: "The Dandi March covered a distance of about:", options: ["100 miles", "240 miles", "500 miles", "50 miles"], answer: 1, why: "Gandhi and 78 volunteers walked about 240 miles from Sabarmati to Dandi over 24 days." },
    { q: "The Poona Pact was signed between Gandhi and:", options: ["Jinnah", "Nehru", "Dr B. R. Ambedkar", "C. R. Das"], answer: 2, why: "Signed in September 1932, it gave the Depressed Classes reserved seats voted on by the general electorate." },
    { q: "The Swaraj Party was founded by:", options: ["Gandhi and Nehru", "C. R. Das and Motilal Nehru", "Ambedkar and Jinnah", "Tilak and Gokhale"], answer: 1, why: "They disagreed with calling off Non-Cooperation and argued for a return to council politics." },
    { q: "Plantation workers in Assam were prevented from leaving by the:", options: ["Rowlatt Act", "Inland Emigration Act of 1859", "Vernacular Press Act", "Forest Act"], answer: 1, why: "Under the Inland Emigration Act of 1859, plantation workers were not permitted to leave the tea gardens without permission." },
    { q: "The Swaraj flag designed by Gandhi in 1921 carried at its centre a:", options: ["Crescent moon", "Lotus", "Spinning wheel", "Lion"], answer: 2, why: "The red, green and white tricolour had a spinning wheel at the centre, representing the Gandhian ideal of self-help." },
  ],
};
