import type { Chapter } from "@/lib/types";

export const ch03: Chapter = {
  slug: "making-of-a-global-world",
  num: 3,
  title: "The Making of a Global World",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · 20 marks",
  minutes: 18,
  blurb: "Trade, work and disease have been moving between continents for centuries — and rarely on equal terms.",
  bigIdea: "Globalisation is not new. What changes is who controls the flows of goods, people and money — and who pays the price when they shift.",
  syllabus: [
    "The pre-modern world",
    "Silk routes link the world",
    "Food travels: spaghetti and potato",
    "Conquest, disease and trade",
    "Subtopics 2 to 4.4 are assessed as Periodic Assessment only",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "What is examined here", html: "For 2026-27 CBSE examines <strong>subtopics 1 to 1.3</strong> of this chapter in the board paper — the pre-modern world, the silk routes, food that travelled, and conquest, disease and trade. The later sections (the nineteenth century, the inter-war economy, rebuilding after the Second World War) are assessed as <strong>periodic assessment only</strong>. They are included below because they carry the argument, and because the interdisciplinary project draws on them." },

    { t: "h", text: "The world was never separate" },
    { t: "sim", id: "global-world-timeline" },
    { t: "p", html: "From ancient times, travellers, traders, priests and pilgrims moved for knowledge, opportunity and spiritual fulfilment, and carried goods, money, values, skills, ideas, inventions — and germs — with them. As early as 3000 BCE, coastal trade linked the Indus valley civilisations with present-day West Asia. Cowries from the Maldives found their way to China and East Africa." },

    { t: "h", text: "The silk routes" },
    { t: "list", items: [
      "A vivid name for the links between distant parts of the world. There were several silk routes, over land and sea, spanning Asia and linking it with Europe and northern Africa.",
      "Known to have existed since before the Christian era and thriving almost till the fifteenth century.",
      "<strong>Chinese pottery</strong> travelled the same route, as did textiles and spices from India and Southeast Asia. In return, <strong>precious metals — gold and silver — flowed from Europe to Asia</strong>.",
      "Trade and cultural exchange went together. Early Christian missionaries, Muslim preachers and Buddhism, which emerged from eastern India, all travelled these routes.",
    ] },
    { t: "note", kind: "idea", html: "Notice the direction: goods moved west, precious metals moved east. That asymmetry is worth remembering, because it reverses after 1492." },

    { t: "h", text: "Food that travelled" },
    { t: "p", html: "Traders and travellers introduced new crops to the lands they visited. Ready foodstuff in distant parts of the world might share common origins — spaghetti and noodles are a plausible example, though it is uncertain who inspired whom." },
    { t: "note", kind: "real", title: "The potato and the Irish famine", html: "Many of our common foods — <strong>potatoes, soya, groundnuts, maize, tomatoes, chillies, sweet potatoes</strong> — were not known in Europe and Asia until about five centuries ago. They came from the Americas.<br><br>Europe's poor began to eat better and live longer with the introduction of the potato. Ireland's poorest peasants became so dependent on it that when disease destroyed the crop in the mid-1840s, hundreds of thousands died of starvation. That is the <strong>Irish Potato Famine</strong>, and it is the standard example of the risk of dependence on a single crop." },

    { t: "h", text: "Conquest, disease and trade" },
    { t: "p", html: "Until the fifteenth century America had remained cut off from regular contact with the rest of the world. From the sixteenth century, European sailors found a sea route to Asia and also stumbled on the Americas. Precious metals, particularly silver from mines in present-day Peru and Mexico, enhanced Europe's wealth and financed its trade with Asia." },
    { t: "note", kind: "why", title: "The weapon that was not a weapon", html: "The Spanish conquerors of America did not win primarily through superior firepower. Their most powerful weapon was <strong>smallpox</strong>, which they carried on their person.<br><br>America's original inhabitants had no immunity to diseases from Europe. Smallpox proved a deadly killer, spreading deep into the continent ahead of any European reaching there, killing and decimating whole communities and paving the way for conquest. Europeans, by contrast, died in large numbers of tropical fevers in Africa — which is why they could not conquer it as easily." },
    { t: "note", kind: "idea", html: "Until well into the eighteenth century, <strong>China and India were among the world's richest countries</strong> and pre-eminent in Asian trade. From the fifteenth century China restricted overseas contacts and retreated into isolation. The reduced role of China, and the rising importance of the Americas, gradually moved the centre of world trade westwards. Europe emerged as the centre of world trade." },

    { t: "h", text: "The nineteenth century — three flows" },
    { t: "note", kind: "exam", html: "Periodic assessment only, but the framework is worth knowing because it is the clearest way to think about globalisation in the Economics book too." },
    { t: "table", head: ["Flow", "What moved", "Example"], rows: [
      ["<strong>Trade</strong>", "Goods — cloth, wheat, machinery", "The abolition of the Corn Laws in Britain in 1846 let cheap food flood in, and distant lands began growing food for Britain"],
      ["<strong>Labour</strong>", "People, in search of work", "Indentured labour from India to the Caribbean, Mauritius and Fiji — described as a 'new system of slavery'"],
      ["<strong>Capital</strong>", "Investment, over short or long term", "British finance built railways, ports and mines across the world — and Britain became the world's leading creditor"],
    ] },
    { t: "note", kind: "real", html: "<strong>Rinderpest</strong> — a fast-spreading cattle plague — arrived in Africa in the late 1880s with infected cattle imported from Asia. It moved across the continent in about a decade and killed roughly <strong>90% of the cattle</strong>. Losing their livestock, Africans lost their means of livelihood, and colonisers were able to force them into the labour market. Disease again did the work of conquest." },

    { t: "h", text: "The twentieth century" },
    { t: "list", items: [
      "<strong>The First World War (1914–18)</strong> was the first modern industrial war, fought with machine guns, tanks, aircraft and chemical weapons. Around 9 million died and 20 million were injured — most of them men of working age. Britain borrowed heavily from US banks and turned from the world's leading lender into a debtor.",
      "<strong>The Great Depression (1929)</strong> began with agricultural overproduction and falling prices. As American loans were withdrawn, the crisis spread. <strong>India's exports and imports nearly halved between 1928 and 1934</strong>, and peasants who produced for the world market fell deep into debt.",
      "<strong>Bretton Woods, 1944</strong> established the IMF and the World Bank to preserve economic stability and full employment in the industrial world — and gave the western industrial powers the controlling vote.",
    ] },
    { t: "note", kind: "idea", html: "This chapter and the Economics chapter on Globalisation are two halves of one argument. The interdisciplinary project the syllabus assigns joins them deliberately — the same forces, seen a century apart." },
  ],
  examFocus: [
    "That subtopics 1 to 1.3 are examined and the rest is periodic assessment only.",
    "The silk routes: what travelled which way, and that religion travelled too.",
    "The potato and the Irish famine as the example of dependence on one crop.",
    "Smallpox as the decisive weapon in the conquest of America.",
    "Why the centre of world trade shifted westwards after the fifteenth century.",
    "Rinderpest in Africa, and how disease was used to force people into wage labour.",
  ],
  flashcards: [
    { q: "What were the silk routes?", a: "A network of overland and sea routes linking Asia with Europe and northern Africa, known to have existed before the Christian era and thriving almost till the fifteenth century. They carried goods, ideas and religions." },
    { q: "What travelled in each direction along the silk routes?", a: "Chinese pottery, and textiles and spices from India and Southeast Asia, travelled west. In return, precious metals — gold and silver — flowed from Europe to Asia." },
    { q: "Name five foods that came to Europe and Asia from the Americas.", a: "Potatoes, soya, groundnuts, maize, tomatoes, chillies and sweet potatoes were all unknown in Europe and Asia until about five centuries ago." },
    { q: "What caused the Irish Potato Famine?", a: "Ireland's poorest peasants had become so dependent on the potato that when disease destroyed the crop in the mid-1840s, hundreds of thousands died of starvation." },
    { q: "What was the most powerful weapon of the Spanish conquerors of America?", a: "Smallpox, which they carried on their person. America's original inhabitants had no immunity to it, so it spread ahead of the Europeans, killing whole communities and clearing the way for conquest." },
    { q: "Why could Europeans not conquer Africa as easily as America?", a: "Africa had its own diseases — tropical fevers — to which Europeans had no immunity, so they died in large numbers there. The immunity advantage ran the other way." },
    { q: "Why did the centre of world trade shift westwards?", a: "China restricted overseas contacts from the fifteenth century and retreated into isolation, while the Americas were drawn into world trade. Europe emerged as the centre." },
    { q: "What was rinderpest and what did it do?", a: "A fast-spreading cattle plague that reached Africa in the late 1880s with infected cattle from Asia. It killed about 90% of African cattle within a decade, destroying livelihoods and forcing Africans into the colonial labour market." },
    { q: "What was indentured labour?", a: "A bonded labourer under contract to work for an employer for a specific period to pay off a passage. Indians went to the Caribbean, Mauritius and Fiji. It has been described as a 'new system of slavery'." },
    { q: "What were the Corn Laws and what happened when they were abolished?", a: "British laws restricting the import of corn, which kept food prices high. After their abolition in 1846, cheap imported food undercut British agriculture, drove labour to cities, and drew distant lands into food production for Britain." },
    { q: "What was agreed at Bretton Woods in 1944?", a: "The International Monetary Fund and the World Bank were established to manage post-war finance and reconstruction, with the western industrial powers holding the controlling vote." },
    { q: "How did the Great Depression affect India?", a: "India's exports and imports nearly halved between 1928 and 1934. Agricultural prices collapsed while the colonial government refused to reduce revenue demands, so peasants fell deeply into debt — which fed into the Civil Disobedience movement." },
  ],
  quiz: [
    { q: "Cowries used as a form of currency came from:", options: ["China", "The Maldives", "Africa", "Europe"], answer: 1, why: "Cowries from the Maldives found their way to China and East Africa, showing how far pre-modern trade networks reached." },
    { q: "Which of these did NOT travel along the silk routes?", options: ["Chinese pottery", "Indian spices", "Buddhism", "Potatoes"], answer: 3, why: "Potatoes came from the Americas, which had no regular contact with the rest of the world until the late fifteenth century." },
    { q: "The Irish Potato Famine of the 1840s shows the danger of:", options: ["Free trade", "Depending heavily on a single crop", "Industrialisation", "Colonial rule"], answer: 1, why: "Ireland's poor had become so dependent on the potato that when disease destroyed the crop, hundreds of thousands starved." },
    { q: "The most powerful weapon of the Spanish conquerors of America was:", options: ["Guns", "Horses", "Smallpox", "Ships"], answer: 2, why: "Native Americans had no immunity to smallpox, which spread ahead of the conquerors and decimated communities." },
    { q: "Precious metals that financed Europe's trade with Asia came largely from mines in:", options: ["South Africa", "Peru and Mexico", "Australia", "Siberia"], answer: 1, why: "Silver from mines in present-day Peru and Mexico enhanced Europe's wealth and financed its trade with Asia." },
    { q: "Rinderpest killed about what proportion of Africa's cattle?", options: ["10%", "50%", "90%", "25%"], answer: 2, why: "Within a decade of arriving in the late 1880s it had killed roughly 90% of the cattle, destroying African livelihoods." },
    { q: "The Corn Laws in Britain were abolished in:", options: ["1815", "1846", "1890", "1914"], answer: 1, why: "Under pressure from industrialists and urban dwellers, the laws restricting corn imports were abolished in 1846." },
    { q: "Indentured labour has been described as:", options: ["Free migration", "A new system of slavery", "Skilled emigration", "Voluntary settlement"], answer: 1, why: "Workers were bonded by contract, often recruited by deception, and the system has been called a 'new system of slavery'." },
    { q: "After the First World War, Britain became:", options: ["The world's leading lender", "A debtor nation", "Economically isolated", "The largest exporter"], answer: 1, why: "Having borrowed heavily from US banks during the war, Britain shifted from the world's leading creditor to a debtor." },
    { q: "The IMF and World Bank were set up at:", options: ["The Congress of Vienna", "Bretton Woods, 1944", "The League of Nations", "The Treaty of Versailles"], answer: 1, why: "The Bretton Woods conference of 1944 established both institutions to manage post-war finance and reconstruction." },
  ],
  keyTopics: [
    { name: "The silk routes — what travelled, which way, and religion alongside trade", importance: "high", note: "Board-examined (subtopic 1.2). A reliable 2–3 mark question on the network and its two-way flow of goods and ideas." },
    { name: "Food that travelled — the potato and the Irish Famine", importance: "high", note: "Board-examined (subtopic 1.3). The single most-asked question from this chapter: explain the famine as an example of crop dependence." },
    { name: "Conquest, disease and trade — smallpox in the Americas", importance: "high", note: "Board-examined (subtopic 1.3). 'Disease as conqueror' is a favourite 3–5 mark and case-study theme." },
    { name: "The pre-modern world — early trade links, cowries, the Indus valley", importance: "medium", note: "Board-examined (subtopic 1.1). Usually a short 1–2 mark recall question." },
    { name: "The nineteenth-century world economy — trade, labour and capital", importance: "medium", note: "Periodic assessment only for 2026-27, but shares its framework with the Economics chapter on Globalisation." },
    { name: "Rinderpest and the colonisation of Africa's labour", importance: "medium", note: "Periodic assessment only; a striking example of disease used to force people into wage labour." },
    { name: "The Great Depression and its effect on India", importance: "medium", note: "Periodic assessment only, but a strong 5-marker linking colonial agriculture, debt and later the Civil Disobedience movement." },
    { name: "Bretton Woods institutions, 1944", importance: "low", note: "Simple 1-mark recall — name the IMF and World Bank and the year." },
  ],
  written: [
    { q: "From where did the cowries used as a form of currency in parts of Africa and Asia originate?", marks: 1, kind: "short", importance: "medium",
      answer: "Cowries came from the <strong>Maldives</strong> and, through pre-modern trade networks, found their way to China and East Africa." },
    { q: "Name the disease that proved to be the most powerful weapon of the Spanish conquerors of America.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Smallpox.</strong> Since the original inhabitants of America had no immunity to it, it spread ahead of the conquerors and killed and decimated whole communities." },
    { q: "What were the silk routes? Name two kinds of goods that travelled westward along them.", marks: 2, kind: "short", importance: "high",
      answer: "The silk routes were a network of overland and sea links, existing since before the Christian era and thriving almost till the fifteenth century, connecting Asia with Europe and northern Africa.<br>Two examples of goods that travelled <strong>westward</strong> were <strong>Chinese pottery</strong> and <strong>textiles and spices from India and Southeast Asia</strong>. In exchange, precious metals such as gold and silver flowed eastward from Europe to Asia." },
    { q: "Explain the significance of the Irish Potato Famine of the 1840s.", marks: 2, kind: "short", importance: "high",
      answer: "The potato, brought from the Americas, had made Europe's poor eat better and live longer, and Ireland's poorest peasants had become almost entirely dependent on it as a staple food. When a disease destroyed the potato crop in the mid-1840s, <strong>hundreds of thousands of people died of starvation</strong>. The famine is the standard illustration of the danger of an economy or a population depending too heavily on a <strong>single crop</strong>." },
    { q: "Why could the Europeans not colonise Africa as swiftly as they colonised America?", marks: 2, kind: "short", importance: "medium",
      answer: "In America, European diseases like smallpox, to which the local population had no immunity, wiped out communities and cleared the way for conquest.<br>In Africa the advantage was reversed — Europeans had no immunity to local <strong>tropical fevers</strong> and died in large numbers, which slowed and delayed European colonisation of the continent until much later." },
    { q: "Explain how religion and culture spread alongside trade along the silk routes.", marks: 3, kind: "long", importance: "medium",
      answer: "<ul><li>The silk routes were not merely commercial; trade and cultural exchange went hand in hand along them.</li><li><strong>Early Christian missionaries</strong> are believed to have travelled this route to Europe and beyond.</li><li><strong>Muslim preachers</strong> also travelled along these routes over several centuries, spreading Islam to distant regions.</li><li><strong>Buddhism</strong>, which emerged from eastern India, spread along a similar route in several directions — to Central Asia, China, and beyond.</li></ul>The silk routes therefore show how goods, ideas and faiths moved together, long before the modern idea of 'globalisation'." },
    { q: "Describe how rinderpest changed the lives and livelihoods of the people of Africa in the late nineteenth century.", marks: 3, kind: "long", importance: "medium",
      answer: "<ul><li><strong>Rinderpest</strong>, a fast-spreading cattle plague, arrived in Africa in the late 1880s, carried by infected cattle imported from British Asia to feed Italian soldiers invading Eritrea.</li><li>It spread rapidly across the continent, reaching the Atlantic coast within about a decade, and killed roughly <strong>90 per cent</strong> of the cattle in affected regions.</li><li>Cattle were the chief form of livelihood for many African communities. Losing their cattle, people lost their means of subsistence.</li><li>Robbed of this independent livelihood, Africans were left with little choice but to <strong>work for wages on European-owned plantations and mines</strong> — disease had done the work that conquest alone could not. Colonial powers exploited the crisis to force Africans into the labour market.</li></ul>" },
    { q: "Explain any three flows that characterised the world economy of the nineteenth century, with one example of each.", marks: 3, kind: "long", importance: "medium",
      answer: "<ul><li><strong>Flow of trade:</strong> goods such as cloth, wheat and machinery moved between countries — for example, once Britain abolished the Corn Laws in 1846, cheap food imports flooded in and distant lands began growing food specifically for the British market.</li><li><strong>Flow of labour:</strong> people migrated in search of work — for example, <strong>indentured Indian labourers</strong> were taken to the Caribbean, Mauritius and Fiji, a system later described as a 'new system of slavery'.</li><li><strong>Flow of capital:</strong> investment moved across borders over the short or long term — British finance, for instance, built railways, ports and mines around the world, making Britain the world's leading creditor nation.</li></ul>" },
    { q: "'Trade and conquest were often closely intertwined in the pre-modern world.' Explain this statement with reference to the European conquest of America.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li>From the sixteenth century, European sailors searching for a sea route to Asia stumbled upon the American continents, until then cut off from regular contact with the rest of the world.</li><li>The conquest of America was not achieved chiefly through superior European weaponry. Their <strong>most powerful weapon was smallpox</strong>, which the conquerors carried on their person, often unknowingly.</li><li>Because the original inhabitants of America had built up <strong>no immunity</strong> to diseases originating in Europe, smallpox spread deep into the continent well ahead of any European soldier reaching there, killing and decimating whole communities and clearing the way for conquest.</li><li>Once conquered, <strong>precious metals — especially silver from mines in present-day Peru and Mexico</strong> — enriched Europe and financed a great expansion of trade with Asia.</li><li>Meanwhile, from the fifteenth century <strong>China restricted overseas contacts</strong> and retreated into relative isolation, and the centre of world trade gradually shifted from Asia to Europe.</li></ul>Conclusion: the conquest of America, the flow of silver, and the shift of the trading centre to Europe were all part of one connected process, in which disease and trade advanced hand in hand with conquest." },
    { q: "Explain the impact of the Great Depression of 1929 on India's economy and society.", marks: 5, kind: "long", importance: "medium",
      answer: "<ul><li>The Great Depression began with <strong>agricultural overproduction</strong>, which was made worse as farmers across the world expanded production even further in the face of falling prices, hoping to make up for lost income through higher output.</li><li>As US banks withdrew loans, the crisis spread internationally, hitting economies dependent on agricultural exports and international lending hardest, including <strong>colonial India</strong>.</li><li>India's exports and imports <strong>nearly halved between 1928 and 1934</strong>. Peasants and farmers who produced for the world market were the worst hit.</li><li>Even as prices crashed, the <strong>colonial government refused to reduce the revenue demand</strong>, forcing peasants who had borrowed against their crops deep into <strong>debt</strong>, since they had to pay revenue and repay loans out of a much smaller income.</li><li>This rural distress fed directly into the political mood of the time, and the resulting discontent became part of the backdrop to the <strong>Civil Disobedience Movement</strong> of the early 1930s.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "The silk routes are named after the fine-quality silk textiles that Chinese traders carried westward.",
      reason: "Precious metals such as gold and silver flowed from Europe to Asia in exchange for these goods.",
      answer: 1, importance: "medium",
      why: "Both statements are true — silk did travel west, and metals did flow east in return — but R does not explain A. The naming of the routes comes from the silk trade itself, not from the direction of the metal flow." },
    { assertion: "The Irish Potato Famine of the 1840s illustrates the danger of excessive dependence on a single crop.",
      reason: "Ireland's poorest peasants had come to depend almost entirely on the potato as their staple food, and disease destroyed the crop in the mid-1840s.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A — it was precisely this dependence on one crop, combined with the crop's failure, that caused mass starvation." },
    { assertion: "The Spanish conquerors were able to conquer America chiefly because of their superior firepower and weapons technology.",
      reason: "Smallpox, carried unknowingly by the Europeans, killed and decimated communities across the Americas because the original inhabitants had no immunity to it.",
      answer: 3, importance: "high",
      why: "A is false — the Spanish conquerors' most powerful weapon was not superior firepower but disease. R is true, and is in fact the correct account of how the conquest was really achieved." },
    { assertion: "China's importance in world trade declined relative to Europe from around the fifteenth century.",
      reason: "China voluntarily restricted its overseas contacts and retreated into relative isolation, while Europe expanded through contact with the Americas.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly explains A — China's deliberate withdrawal, alongside Europe's new access to American silver and markets, is exactly why the centre of world trade shifted westwards." },
  ],
  caseStudies: [
    { title: "Smallpox, the invisible conqueror", importance: "high",
      source: "When Spanish sailors landed in the Caribbean and later on the American mainland in the sixteenth century, they were followed by an invisible companion: the smallpox virus. The original inhabitants of the Americas had lived apart from Afro-Asian diseases for thousands of years and had no immunity to them. As a result, smallpox spread from one community to another far ahead of any European soldier, in some regions destroying entire settlements before a single shot was fired. By the time European conquerors arrived to claim the land, disease had often already done the harder part of their work.",
      parts: [
        { q: "Why did the original inhabitants of America have no immunity to diseases like smallpox?", marks: 1,
          answer: "They had lived in isolation from the rest of the world, cut off from regular contact with Europe, Asia and Africa, for thousands of years, and so had never been exposed to Afro-Asian diseases or developed any resistance to them." },
        { q: "In what sense did smallpox act as a 'conqueror' even before European soldiers arrived?", marks: 2,
          answer: "The disease travelled from community to community faster than the Europeans themselves could, killing and decimating populations well in advance of any military encounter. This meant many regions were already devastated and weakened by the time European conquerors physically reached them — disease, not the sword, broke the resistance of the Americas." },
        { q: "Name the two present-day countries whose silver mines enriched Europe after the conquest.", marks: 1,
          answer: "<strong>Peru and Mexico.</strong> Silver from these mines enhanced Europe's wealth and financed its trade with Asia." },
        { q: "Why, by contrast, did Europeans find it difficult to conquer Africa in the same period?", marks: 1,
          answer: "In Africa the disease advantage ran the other way — Europeans had no immunity to local tropical fevers and died there in large numbers, which slowed European conquest of the African interior until much later." },
      ] },
    { title: "Rinderpest and the making of a colonial workforce", importance: "medium",
      caption: "From the periodic-assessment portion of the chapter (the nineteenth-century world economy); included because it feeds the interdisciplinary project with Economics.",
      source: "In the late 1880s a fast-spreading cattle disease called rinderpest reached East Africa, carried by infected cattle imported to feed the animals of invading colonial armies. It spread across the continent 'like a forest fire', reaching the Atlantic coast within about a decade and killing an estimated 90 per cent of the region's cattle. For many African communities, cattle were the chief form of livelihood and wealth. Deprived of their herds, people had little option left but to sell their labour for wages on European-owned plantations, mines and colonial construction projects.",
      parts: [
        { q: "How did rinderpest spread across Africa, and what proportion of cattle did it kill?", marks: 2,
          answer: "It arrived with infected cattle imported for colonial armies and spread rapidly across the continent within about a decade, killing roughly <strong>90 per cent</strong> of the cattle in the affected regions." },
        { q: "How did the loss of cattle change the relationship between Africans and colonial employers?", marks: 2,
          answer: "Having lost cattle — their main source of livelihood and independence — many Africans were left with no choice but to <strong>work for wages</strong> on plantations, in mines, and on colonial projects, a dependence they had previously been able to avoid." },
        { q: "In what sense can disease be said to have 'done the work of conquest' in Africa?", marks: 1,
          answer: "Just as smallpox weakened resistance in the Americas, rinderpest broke the economic independence of African communities without a single battle being fought, making it far easier for colonial powers to force people into the labour market they controlled." },
      ] },
  ],
};
