import type { Chapter } from "@/lib/types";

export const ch04: Chapter = {
  slug: "age-of-industrialisation",
  num: 4,
  title: "The Age of Industrialisation",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · periodic assessment only",
  formative: true,
  formativeLabel: "periodic assessment",
  minutes: 16,
  blurb: "Industrialisation did not start with factories, did not always need machines, and did not make workers better off. Three assumptions, all wrong.",
  bigIdea: "The image of rapid technological progress is a story told afterwards. What actually happened was slower, patchier and far harder on the people doing the work.",
  syllabus: [
    "Before the Industrial Revolution — proto-industrialisation",
    "Hand labour and steam power",
    "Industrialisation in the colonies",
    "Factories come up; the peculiarities of Indian industrial growth",
    "Market for goods",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "About this chapter", html: "CBSE has placed this chapter under <strong>periodic assessment only</strong> for 2026-27, so it will not be set in the year-end paper. It is included because it is the background to the Geography chapter on Manufacturing Industries and to the Economics chapters on Sectors and Globalisation — and because it is genuinely one of the more interesting chapters in the book." },

    { t: "h", text: "Before the factory" },
    { t: "sim", id: "industrialisation-timeline" },
    { t: "p", html: "Even before factories began to dot the landscape in England and Europe, there was large-scale industrial production for an international market. This is called <strong>proto-industrialisation</strong>." },
    { t: "list", items: [
      "Merchants moved to the countryside because town guilds controlled production, competition and prices in the towns, and it was difficult to set up new businesses.",
      "They supplied money to peasants and artisans to produce for an international market.",
      "For peasants, whose common lands had been enclosed, this income supplemented shrinking cultivation. A close relationship developed between the town and the countryside.",
      "Merchants were based in towns; the work was done in the countryside. Twenty to twenty-five workers might be employed by each merchant.",
    ] },

    { t: "h", text: "Hand labour and steam power" },
    { t: "note", kind: "why", title: "Why English industrialists preferred hand labour", html: "This is the central argument of the chapter, and the one worth remembering.<br><br>In Victorian Britain there was <strong>no shortage of human labour</strong>. Wages were low. Industrialists had no problem of labour shortage or high wage costs, so they did not want to introduce machines that cost a great deal and needed repair.<br><br>Machines were also <strong>oriented to producing uniforms in large quantities</strong>. But the market often demanded variety — hundreds of designs and shapes, intricate handmade products. That could not be produced by machinery.<br><br>In Victorian Britain, the upper classes preferred things produced by hand. Handmade products came to symbolise refinement and class." },
    { t: "note", kind: "real", html: "The <strong>Spinning Jenny</strong>, devised by James Hargreaves in 1764, sped up spinning and reduced labour demand. Women who survived on hand spinning began attacking the new machines. Technology was not welcomed by everyone — the fear of losing work was entirely rational." },

    { t: "h", text: "Industry in colonial India" },
    { t: "p", html: "Before machine industries, India was the world's largest producer of cotton textiles. Surat, Masulipatam and Hooghly were the main ports. Then the European companies gained power — first securing concessions, then a monopoly on trade — and the old ports declined." },
    { t: "list", ordered: true, items: [
      "By the 1750s the old trading network broke down. Exports from Surat and Hooghly fell dramatically; <strong>Bombay and Calcutta</strong> grew instead — ports controlled by European companies.",
      "The East India Company appointed <strong>gomasthas</strong> — paid servants — to supervise weavers, collect supplies and examine cloth quality, eliminating the existing traders and brokers.",
      "Weavers were given <strong>advances</strong> to buy raw material. Once they took the advance they could not take orders from anyone else. Many lost their land and became entirely dependent.",
      "From the early nineteenth century, <strong>Manchester cotton flooded Indian markets</strong>. By 1850 cotton goods were over 31% of India's imports. Indian weavers faced a market collapse and a raw cotton shortage as exports rose.",
    ] },
    { t: "note", kind: "idea", html: "This is why colonial industrialisation looks different: Britain industrialised partly by <strong>de-industrialising</strong> India. Indian weavers did not fail because their product was poor — it was the best in the world — but because tariffs, monopoly and machine competition were arranged against them." },

    { t: "h", text: "Indian factories" },
    { t: "table", head: ["Year", "Development"], rows: [
      ["1854", "The first cotton mill in Bombay is set up; it goes into production two years later"],
      ["1855", "The first jute mill comes up in Bengal, followed by another in 1862"],
      ["1860s", "The Elgin Mill starts in Kanpur; a year later the first cotton mill in Ahmedabad"],
      ["1874", "The first spinning and weaving mill in Madras begins production"],
      ["1912", "TISCO begins producing steel at Jamshedpur"],
      ["1917", "Seth Hukumchand sets up the first Indian jute mill in Calcutta"],
    ] },
    { t: "note", kind: "real", html: "Indian entrepreneurs accumulated capital through China trade and other channels. <strong>Dwarkanath Tagore</strong> in Bengal, <strong>Dinshaw Petit</strong> and <strong>Jamsetjee Nusserwanjee Tata</strong> in Bombay, and <strong>Seth Hukumchand</strong> in Calcutta built industry alongside — not merely under — colonial trade." },
    { t: "note", kind: "why", title: "The peculiarity of Indian industrial growth", html: "European Managing Agencies controlled a large sector of Indian industries, and they invested in tea and coffee plantations, mining, indigo and jute — products for export, not for the Indian market. Indian businessmen were pushed towards industries the Europeans did not want, and were kept out of the export trade almost entirely." },
    { t: "note", kind: "idea", html: "The <strong>First World War</strong> changed this. Manchester mills were busy with war supplies, so imports to India fell. Indian mills had a vast home market to supply, worked in double shifts, and new factories were set up. After the war Manchester never recovered its old position, and by the 1930s the pattern of Indian industry had permanently shifted." },

    { t: "h", text: "Selling the goods" },
    { t: "p", html: "New consumers had to be created. Manchester industrialists put <strong>labels</strong> on cloth bundles — 'MADE IN MANCHESTER' — so buyers would know what they were buying and feel confident. Labels carried images of Indian gods and goddesses, or of Indian rulers, to make the product feel familiar and approved of." },
    { t: "note", kind: "real", html: "When Indian manufacturers advertised, the message was explicitly nationalist: <strong>if you care for the nation, buy products Indians produce</strong>. Advertisements became a vehicle of the swadeshi message — which is exactly where this chapter joins Nationalism in India." },
  ],
  examFocus: [
    "Proto-industrialisation — what it was and why merchants moved to the countryside.",
    "The three reasons English industrialists preferred hand labour over machines.",
    "How the East India Company reshaped weaving through gomasthas and advances.",
    "Why Indian weavers declined: market collapse plus raw cotton shortage.",
    "The dates of the early Indian mills, and TISCO in 1912.",
    "The peculiarity of Indian industrial growth and the effect of the First World War.",
    "Labels and advertising as ways of creating a market.",
  ],
  flashcards: [
    { q: "What is proto-industrialisation?", a: "Large-scale industrial production for an international market that took place before factories, with merchants supplying money to peasants and artisans who produced in the countryside." },
    { q: "Why did merchants move to the countryside?", a: "Town guilds controlled production, competition and prices, and it was difficult for new merchants to set up business in towns. In the countryside there were no such restrictions." },
    { q: "Why did English industrialists prefer hand labour to machines?", a: "There was no labour shortage and wages were low; machines were expensive and needed repair; and machines produced uniform goods while the market often wanted variety and intricate handmade designs prized by the upper classes." },
    { q: "What was the Spinning Jenny and how was it received?", a: "A machine devised by James Hargreaves in 1764 that sped up spinning and reduced labour demand. Women who survived on hand spinning attacked the machines, fearing for their livelihoods." },
    { q: "Who were gomasthas?", a: "Paid servants appointed by the East India Company to supervise weavers, collect supplies and examine the quality of cloth, replacing the existing traders and brokers." },
    { q: "How did the advance system trap weavers?", a: "Weavers took loans to buy raw material. Once they had taken the advance they could not sell to any other buyer, and many lost their land and became entirely dependent on the Company." },
    { q: "Why did Indian weavers decline in the nineteenth century?", a: "Manchester cotton flooded Indian markets, and at the same time raw cotton exports rose, causing a shortage and price rise for Indian weavers. They faced collapsing demand and rising input costs at once." },
    { q: "When was the first cotton mill in Bombay set up?", a: "In 1854. It went into production two years later. The first jute mill in Bengal came up in 1855." },
    { q: "When did TISCO begin producing steel, and where?", a: "1912, at Jamshedpur. It was set up by the family of Jamsetjee Nusserwanjee Tata." },
    { q: "How did the First World War change Indian industry?", a: "Manchester mills were busy with war supplies so imports fell. Indian mills had a vast home market, worked double shifts, and expanded. After the war Manchester never regained its earlier position in India." },
    { q: "What was the peculiarity of Indian industrial growth under colonialism?", a: "European Managing Agencies controlled much of Indian industry and invested in export products — tea, coffee, mining, indigo, jute — rather than in goods for the Indian market. Indian businessmen were largely kept out of the export trade." },
    { q: "How did manufacturers create a market for their goods?", a: "Through labels showing the place of manufacture, images of Indian gods and rulers to make products feel familiar, calendars and advertisements. Indian manufacturers used explicitly nationalist, swadeshi messages." },
  ],
  quiz: [
    { q: "Proto-industrialisation refers to production:", options: ["In large factories", "For an international market but without factories", "Only for local use", "Using steam power"], answer: 1, why: "It was large-scale industrial production for an international market, organised by merchants in the countryside rather than in factories." },
    { q: "The Spinning Jenny was invented by:", options: ["Richard Arkwright", "James Hargreaves", "James Watt", "Samuel Crompton"], answer: 1, why: "James Hargreaves devised it in 1764. It sped up spinning and reduced the labour required." },
    { q: "English industrialists were slow to adopt machines mainly because:", options: ["Machines did not work", "Labour was cheap and plentiful", "The government banned them", "Workers refused to use them"], answer: 1, why: "With no labour shortage and low wages, expensive machines that needed repair offered little advantage." },
    { q: "Gomasthas were:", options: ["Indian weavers", "Paid servants of the Company who supervised weavers", "British officials", "Cloth merchants in Manchester"], answer: 1, why: "They supervised weavers, collected supplies and checked quality, displacing the existing brokers." },
    { q: "The first cotton mill in Bombay was set up in:", options: ["1820", "1854", "1874", "1912"], answer: 1, why: "It was set up in 1854 and went into production two years later." },
    { q: "TISCO began producing steel in:", options: ["1855", "1874", "1912", "1917"], answer: 2, why: "The Tata Iron and Steel Company started production at Jamshedpur in 1912." },
    { q: "Which Indian entrepreneur set up the first Indian jute mill in Calcutta in 1917?", options: ["Dwarkanath Tagore", "Dinshaw Petit", "Seth Hukumchand", "J. N. Tata"], answer: 2, why: "Seth Hukumchand, a Marwari businessman, set it up in 1917." },
    { q: "The First World War affected Indian industry by:", options: ["Destroying Indian factories", "Increasing British imports", "Giving Indian mills a vast home market as imports fell", "Ending industrial production"], answer: 2, why: "Manchester mills were occupied with war supplies, so imports to India declined and Indian mills expanded to fill the gap." },
    { q: "Labels reading 'MADE IN MANCHESTER' were used to:", options: ["Comply with law", "Give buyers confidence about quality and origin", "Increase the price", "Identify the weaver"], answer: 1, why: "Labels were a marketing device — they told the buyer where the cloth came from and were meant to inspire confidence." },
    { q: "European Managing Agencies in India mainly invested in:", options: ["Goods for the Indian market", "Export products such as tea, jute and mining", "Small-scale handicrafts", "Consumer electronics"], answer: 1, why: "They concentrated on products for export rather than for Indian consumers, which shaped the peculiar pattern of Indian industrial growth." },
  ],
};
