import type { Chapter } from "@/lib/types";

export const ch04: Chapter = {
  slug: "age-of-industrialisation",
  num: 4,
  title: "The Age of Industrialisation",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · periodic assessment only",
  formative: true,
  formativeLabel: "periodic assessment",
  minutes: 16,
  blurb: "Industrialisation did not start with factories, did not always need machines, and did not make workers better off. Three assumptions, all wrong.",
  bigIdea: "The image of rapid technological progress is a story told afterwards. What actually happened was slower, patchier and far harder on the people doing the work.",
  syllabus: [
    "Before the Industrial Revolution — proto-industrialisation",
    "Hand labour and steam power",
    "Industrialisation in the colonies",
    "Factories come up; the peculiarities of Indian industrial growth",
    "Market for goods",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "About this chapter", html: "CBSE has placed this chapter under <strong>periodic assessment only</strong> for 2026-27, so it will not be set in the year-end paper. It is included because it is the background to the Geography chapter on Manufacturing Industries and to the Economics chapters on Sectors and Globalisation — and because it is genuinely one of the more interesting chapters in the book." },

    { t: "h", text: "Before the factory" },
    { t: "sim", id: "industrialisation-timeline" },
    { t: "p", html: "Even before factories began to dot the landscape in England and Europe, there was large-scale industrial production for an international market. This is called <strong>proto-industrialisation</strong>." },
    { t: "list", items: [
      "Merchants moved to the countryside because town guilds controlled production, competition and prices in the towns, and it was difficult to set up new businesses.",
      "They supplied money to peasants and artisans to produce for an international market.",
      "For peasants, whose common lands had been enclosed, this income supplemented shrinking cultivation. A close relationship developed between the town and the countryside.",
      "Merchants were based in towns; the work was done in the countryside. Twenty to twenty-five workers might be employed by each merchant.",
    ] },

    { t: "h", text: "Hand labour and steam power" },
    { t: "note", kind: "why", title: "Why English industrialists preferred hand labour", html: "This is the central argument of the chapter, and the one worth remembering.<br><br>In Victorian Britain there was <strong>no shortage of human labour</strong>. Wages were low. Industrialists had no problem of labour shortage or high wage costs, so they did not want to introduce machines that cost a great deal and needed repair.<br><br>Machines were also <strong>oriented to producing uniforms in large quantities</strong>. But the market often demanded variety — hundreds of designs and shapes, intricate handmade products. That could not be produced by machinery.<br><br>In Victorian Britain, the upper classes preferred things produced by hand. Handmade products came to symbolise refinement and class." },
    { t: "note", kind: "real", html: "The <strong>Spinning Jenny</strong>, devised by James Hargreaves in 1764, sped up spinning and reduced labour demand. Women who survived on hand spinning began attacking the new machines. Technology was not welcomed by everyone — the fear of losing work was entirely rational." },

    { t: "h", text: "Industry in colonial India" },
    { t: "p", html: "Before machine industries, India was the world's largest producer of cotton textiles. Surat, Masulipatam and Hooghly were the main ports. Then the European companies gained power — first securing concessions, then a monopoly on trade — and the old ports declined." },
    { t: "list", ordered: true, items: [
      "By the 1750s the old trading network broke down. Exports from Surat and Hooghly fell dramatically; <strong>Bombay and Calcutta</strong> grew instead — ports controlled by European companies.",
      "The East India Company appointed <strong>gomasthas</strong> — paid servants — to supervise weavers, collect supplies and examine cloth quality, eliminating the existing traders and brokers.",
      "Weavers were given <strong>advances</strong> to buy raw material. Once they took the advance they could not take orders from anyone else. Many lost their land and became entirely dependent.",
      "From the early nineteenth century, <strong>Manchester cotton flooded Indian markets</strong>. By 1850 cotton goods were over 31% of India's imports. Indian weavers faced a market collapse and a raw cotton shortage as exports rose.",
    ] },
    { t: "note", kind: "idea", html: "This is why colonial industrialisation looks different: Britain industrialised partly by <strong>de-industrialising</strong> India. Indian weavers did not fail because their product was poor — it was the best in the world — but because tariffs, monopoly and machine competition were arranged against them." },

    { t: "h", text: "Indian factories" },
    { t: "table", head: ["Year", "Development"], rows: [
      ["1854", "The first cotton mill in Bombay is set up; it goes into production two years later"],
      ["1855", "The first jute mill comes up in Bengal, followed by another in 1862"],
      ["1860s", "The Elgin Mill starts in Kanpur; a year later the first cotton mill in Ahmedabad"],
      ["1874", "The first spinning and weaving mill in Madras begins production"],
      ["1912", "TISCO begins producing steel at Jamshedpur"],
      ["1917", "Seth Hukumchand sets up the first Indian jute mill in Calcutta"],
    ] },
    { t: "note", kind: "real", html: "Indian entrepreneurs accumulated capital through China trade and other channels. <strong>Dwarkanath Tagore</strong> in Bengal, <strong>Dinshaw Petit</strong> and <strong>Jamsetjee Nusserwanjee Tata</strong> in Bombay, and <strong>Seth Hukumchand</strong> in Calcutta built industry alongside — not merely under — colonial trade." },
    { t: "note", kind: "why", title: "The peculiarity of Indian industrial growth", html: "European Managing Agencies controlled a large sector of Indian industries, and they invested in tea and coffee plantations, mining, indigo and jute — products for export, not for the Indian market. Indian businessmen were pushed towards industries the Europeans did not want, and were kept out of the export trade almost entirely." },
    { t: "note", kind: "idea", html: "The <strong>First World War</strong> changed this. Manchester mills were busy with war supplies, so imports to India fell. Indian mills had a vast home market to supply, worked in double shifts, and new factories were set up. After the war Manchester never recovered its old position, and by the 1930s the pattern of Indian industry had permanently shifted." },

    { t: "h", text: "Selling the goods" },
    { t: "p", html: "New consumers had to be created. Manchester industrialists put <strong>labels</strong> on cloth bundles — 'MADE IN MANCHESTER' — so buyers would know what they were buying and feel confident. Labels carried images of Indian gods and goddesses, or of Indian rulers, to make the product feel familiar and approved of." },
    { t: "note", kind: "real", html: "When Indian manufacturers advertised, the message was explicitly nationalist: <strong>if you care for the nation, buy products Indians produce</strong>. Advertisements became a vehicle of the swadeshi message — which is exactly where this chapter joins Nationalism in India." },
  ],
  examFocus: [
    "Proto-industrialisation — what it was and why merchants moved to the countryside.",
    "The three reasons English industrialists preferred hand labour over machines.",
    "How the East India Company reshaped weaving through gomasthas and advances.",
    "Why Indian weavers declined: market collapse plus raw cotton shortage.",
    "The dates of the early Indian mills, and TISCO in 1912.",
    "The peculiarity of Indian industrial growth and the effect of the First World War.",
    "Labels and advertising as ways of creating a market.",
  ],
  flashcards: [
    { q: "What is proto-industrialisation?", a: "Large-scale industrial production for an international market that took place before factories, with merchants supplying money to peasants and artisans who produced in the countryside." },
    { q: "Why did merchants move to the countryside?", a: "Town guilds controlled production, competition and prices, and it was difficult for new merchants to set up business in towns. In the countryside there were no such restrictions." },
    { q: "Why did English industrialists prefer hand labour to machines?", a: "There was no labour shortage and wages were low; machines were expensive and needed repair; and machines produced uniform goods while the market often wanted variety and intricate handmade designs prized by the upper classes." },
    { q: "What was the Spinning Jenny and how was it received?", a: "A machine devised by James Hargreaves in 1764 that sped up spinning and reduced labour demand. Women who survived on hand spinning attacked the machines, fearing for their livelihoods." },
    { q: "Who were gomasthas?", a: "Paid servants appointed by the East India Company to supervise weavers, collect supplies and examine the quality of cloth, replacing the existing traders and brokers." },
    { q: "How did the advance system trap weavers?", a: "Weavers took loans to buy raw material. Once they had taken the advance they could not sell to any other buyer, and many lost their land and became entirely dependent on the Company." },
    { q: "Why did Indian weavers decline in the nineteenth century?", a: "Manchester cotton flooded Indian markets, and at the same time raw cotton exports rose, causing a shortage and price rise for Indian weavers. They faced collapsing demand and rising input costs at once." },
    { q: "When was the first cotton mill in Bombay set up?", a: "In 1854. It went into production two years later. The first jute mill in Bengal came up in 1855." },
    { q: "When did TISCO begin producing steel, and where?", a: "1912, at Jamshedpur. It was set up by the family of Jamsetjee Nusserwanjee Tata." },
    { q: "How did the First World War change Indian industry?", a: "Manchester mills were busy with war supplies so imports fell. Indian mills had a vast home market, worked double shifts, and expanded. After the war Manchester never regained its earlier position in India." },
    { q: "What was the peculiarity of Indian industrial growth under colonialism?", a: "European Managing Agencies controlled much of Indian industry and invested in export products — tea, coffee, mining, indigo, jute — rather than in goods for the Indian market. Indian businessmen were largely kept out of the export trade." },
    { q: "How did manufacturers create a market for their goods?", a: "Through labels showing the place of manufacture, images of Indian gods and rulers to make products feel familiar, calendars and advertisements. Indian manufacturers used explicitly nationalist, swadeshi messages." },
  ],
  quiz: [
    { q: "Proto-industrialisation refers to production:", options: ["In large factories", "For an international market but without factories", "Only for local use", "Using steam power"], answer: 1, why: "It was large-scale industrial production for an international market, organised by merchants in the countryside rather than in factories." },
    { q: "The Spinning Jenny was invented by:", options: ["Richard Arkwright", "James Hargreaves", "James Watt", "Samuel Crompton"], answer: 1, why: "James Hargreaves devised it in 1764. It sped up spinning and reduced the labour required." },
    { q: "English industrialists were slow to adopt machines mainly because:", options: ["Machines did not work", "Labour was cheap and plentiful", "The government banned them", "Workers refused to use them"], answer: 1, why: "With no labour shortage and low wages, expensive machines that needed repair offered little advantage." },
    { q: "Gomasthas were:", options: ["Indian weavers", "Paid servants of the Company who supervised weavers", "British officials", "Cloth merchants in Manchester"], answer: 1, why: "They supervised weavers, collected supplies and checked quality, displacing the existing brokers." },
    { q: "The first cotton mill in Bombay was set up in:", options: ["1820", "1854", "1874", "1912"], answer: 1, why: "It was set up in 1854 and went into production two years later." },
    { q: "TISCO began producing steel in:", options: ["1855", "1874", "1912", "1917"], answer: 2, why: "The Tata Iron and Steel Company started production at Jamshedpur in 1912." },
    { q: "Which Indian entrepreneur set up the first Indian jute mill in Calcutta in 1917?", options: ["Dwarkanath Tagore", "Dinshaw Petit", "Seth Hukumchand", "J. N. Tata"], answer: 2, why: "Seth Hukumchand, a Marwari businessman, set it up in 1917." },
    { q: "The First World War affected Indian industry by:", options: ["Destroying Indian factories", "Increasing British imports", "Giving Indian mills a vast home market as imports fell", "Ending industrial production"], answer: 2, why: "Manchester mills were occupied with war supplies, so imports to India declined and Indian mills expanded to fill the gap." },
    { q: "Labels reading 'MADE IN MANCHESTER' were used to:", options: ["Comply with law", "Give buyers confidence about quality and origin", "Increase the price", "Identify the weaver"], answer: 1, why: "Labels were a marketing device — they told the buyer where the cloth came from and were meant to inspire confidence." },
    { q: "European Managing Agencies in India mainly invested in:", options: ["Goods for the Indian market", "Export products such as tea, jute and mining", "Small-scale handicrafts", "Consumer electronics"], answer: 1, why: "They concentrated on products for export rather than for Indian consumers, which shaped the peculiar pattern of Indian industrial growth." },
  ],
  keyTopics: [
    { name: "Why English industrialists preferred hand labour over machines", importance: "high", note: "The central argument of the chapter — a very common 3–5 mark 'give reasons' question, even in periodic tests." },
    { name: "The decline of Indian weavers — gomasthas, advances, Manchester cloth", importance: "high", note: "The standard 5-mark 'explain the problems faced by Indian weavers' question." },
    { name: "Proto-industrialisation — production before the factory", importance: "medium", note: "Defines the chapter's opening idea; usually a 2–3 mark question." },
    { name: "The peculiarity of Indian industrial growth under colonial rule", importance: "medium", note: "Managing Agencies, and how the First World War changed the pattern — a good 3-mark 'explain' question." },
    { name: "Early Indian entrepreneurs and the first factories", importance: "medium", note: "Dates and named entrepreneurs (Tata, Tagore, Petit, Hukumchand) — reliable 1–2 mark recall." },
    { name: "Market-making — labels, advertisements and the swadeshi message", importance: "medium", note: "Links this chapter to Nationalism in India; a 2–3 mark 'how were markets created' question." },
    { name: "The Spinning Jenny and resistance to new technology", importance: "low", note: "A short factual question on the machine, its inventor, and why hand-spinners opposed it." },
  ],
  written: [
    { q: "What is meant by 'proto-industrialisation'?", marks: 1, kind: "short", importance: "medium",
      answer: "Large-scale industrial production for an international market that took place <strong>before the coming of factories</strong>, organised by merchants who supplied money to peasants and artisans producing in the countryside." },
    { q: "Who invented the Spinning Jenny, and in which year?", marks: 1, kind: "short", importance: "low",
      answer: "<strong>James Hargreaves</strong> devised the Spinning Jenny in <strong>1764</strong>. It sped up the spinning process and reduced the labour required per unit of cloth." },
    { q: "Why did merchants in Europe move production to the countryside rather than keep it in towns?", marks: 2, kind: "short", importance: "medium",
      answer: "Production in towns was organised by <strong>guilds</strong>, which controlled competition, regulated prices, and restricted the entry of new merchants and traders. Unable to expand within towns, merchants turned to the countryside, where such guild restrictions did not apply and where poor peasants — whose common lands were being enclosed — were willing to work for extra income." },
    { q: "Who were 'gomasthas'? What role did they play in the colonial textile trade?", marks: 2, kind: "short", importance: "high",
      answer: "Gomasthas were <strong>paid servants appointed by the East India Company</strong> to supervise weavers, collect supplies, and examine the quality of cloth.<br>They replaced the existing traders and brokers who had earlier connected weavers to the market, and enforced strict Company control — weavers could no longer bargain freely or sell through other channels." },
    { q: "Give two reasons why Indian weavers found themselves in crisis by the mid-nineteenth century.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> Cheap machine-made cloth from <strong>Manchester</strong> flooded Indian markets, and by 1850 cotton goods made up over 31% of India's imports, collapsing demand for local weavers.<br><strong>(ii)</strong> At the same time, exports of <strong>raw cotton</strong> from India rose sharply, creating a shortage of raw material at home and pushing up its price for Indian weavers." },
    { q: "Explain any three reasons why English industrialists in the nineteenth century preferred hand labour to machines.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>There was <strong>no shortage of human labour</strong> in Victorian Britain, and wages were low, so industrialists felt no urgent need for expensive labour-saving machinery.</li><li>New technology was <strong>costly and needed regular repair</strong>, and was not always as effective as its inventors claimed — a risk industrialists were reluctant to take on.</li><li>Machines were suited to producing <strong>standardised goods in bulk</strong>, but the market often wanted intricate designs and a wide variety of shapes — goods that could only be produced by <strong>skilled hand labour</strong>, and which the Victorian upper classes regarded as symbols of refinement and class.</li></ul>" },
    { q: "How did the East India Company reorganise the system of textile production and procurement in eighteenth-century Bengal?", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>The Company first tried to <strong>eliminate existing traders and brokers</strong> connected with the cloth trade, and instead appointed <strong>gomasthas</strong> — paid servants — to supervise weavers, collect supplies and check the quality of cloth.</li><li>Weavers were prevented from dealing with other buyers; this was enforced through a system of <strong>advances</strong> — loans given to weavers to purchase raw material, after which they could not take orders from anyone else.</li><li>Many weavers, unable to bargain over prices and locked into debt, lost their land and became <strong>entirely dependent</strong> on the Company for their livelihood, while old trading centres like Surat and Hooghly declined as Company-controlled ports like Bombay and Calcutta grew.</li></ul>" },
    { q: "Explain the 'peculiarity' of Indian industrial growth in the late nineteenth and early twentieth centuries.", marks: 3, kind: "long", importance: "medium",
      answer: "<ul><li>Large European Managing Agencies controlled a big share of Indian industry, but they invested mainly in products meant for <strong>export</strong> — tea and coffee plantations, mining, and indigo and jute processing — not in goods for the Indian market.</li><li>Indian businessmen were largely <strong>kept out of the export trade</strong> and were pushed towards industries the Europeans did not want to enter, such as cotton textiles for the home market.</li><li>This pattern changed only with the <strong>First World War</strong>, when Manchester imports fell as British mills were occupied with war production, giving Indian industry a vast home market to supply — a shift that outlasted the war itself.</li></ul>" },
    { q: "Describe the decline of the textile weavers of India in the nineteenth century, and explain how the crisis unfolded.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li>Before machine industries came up, India was the <strong>world's largest producer of cotton textiles</strong>, and Surat, Masulipatam and Hooghly were flourishing ports through which this trade moved.</li><li>As European trading companies won concessions and then a monopoly over trade, the old trading network collapsed — exports through Surat and Hooghly fell sharply, while <strong>Bombay and Calcutta</strong>, controlled by the Company, grew instead.</li><li>The Company appointed <strong>gomasthas</strong> to supervise weavers directly, doing away with existing traders and brokers.</li><li>Weavers were forced to take <strong>advances</strong> to buy raw material, after which they could not sell to anyone else, and many, unable to negotiate a fair price, fell into debt, lost their land, and became labourers rather than independent producers.</li><li>From the early nineteenth century, <strong>Manchester's machine-made cloth</strong> flooded Indian markets — by 1850 cotton goods made up over 31% of India's imports — while raw cotton exports from India rose, creating a domestic shortage and driving up local prices.</li></ul>Conclusion: Indian weavers did not decline because their craft was inferior — it was famed the world over — but because the combined weight of Company monopoly, the advance system, and machine competition from Britain was arranged against them." },
    { q: "'The history of industrialisation in the colonies is very different from that in Europe.' Explain this statement with reference to India, using at least two arguments.", marks: 5, kind: "long", importance: "medium",
      answer: "<ul><li>In Britain, industrialists slowly adopted machinery over more than a century, mostly retaining hand labour where markets demanded variety and where labour was cheap and plentiful.</li><li>In India, industrialisation was shaped first by <strong>de-industrialisation</strong> — Manchester's cheap machine-made cloth and colonial trade policy destroyed a flourishing indigenous weaving industry rather than helping it modernise.</li><li>When factories did emerge in India — the first cotton mill in Bombay in 1854, the first jute mill in Bengal in 1855, TISCO at Jamshedpur in 1912 — they were set up mostly by <strong>Indian entrepreneurs</strong> such as Dwarkanath Tagore, Dinshaw Petit, Jamsetjee Tata and Seth Hukumchand, often building capital through trade with China rather than through colonial patronage.</li><li>Unlike in Britain, <strong>European Managing Agencies</strong> in India invested chiefly in export-oriented sectors — plantations, mining, jute — leaving Indian industrialists to develop the market for Indian consumers largely on their own, a pattern that only shifted decisively after the First World War disrupted British imports.</li></ul>Conclusion: Indian industrialisation therefore grew in the shadow of, and often in spite of, colonial interests — a very different story from Britain's own industrial revolution." },
  ],
  assertionReason: [
    { assertion: "English industrialists in the nineteenth century were slow to introduce new machinery on a large scale.",
      reason: "There was no shortage of labour in Victorian Britain and wages were low, so machines offered industrialists little immediate advantage.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A — with abundant cheap labour available, there was little pressure on industrialists to invest in costly machinery that also needed repair." },
    { assertion: "Weavers who took advances from the East India Company gained greater independence in the textile trade.",
      reason: "Once a weaver had accepted an advance, he could not take orders from or sell his cloth to any other buyer.",
      answer: 3, importance: "high",
      why: "A is false — weavers who took advances became more, not less, dependent on the Company, often losing their land and bargaining power. R is true, and is in fact the reason A is false." },
    { assertion: "Machines in nineteenth-century Britain could not fully replace hand labour in the production of textiles.",
      reason: "Machines were oriented towards producing large quantities of a single, standardised design, while markets often demanded intricate and varied handmade products.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly explains A — the demand for variety and fine craftsmanship, valued by the Victorian upper classes, was something contemporary machinery simply could not supply." },
    { assertion: "The First World War helped Indian cotton and jute mills expand their production.",
      reason: "Manchester's textile industry increased its cloth exports to India during the war to meet growing military demand.",
      answer: 2, importance: "medium",
      why: "A is true — Indian mills gained a vast home market during the war. But R is false: it was the opposite — Manchester mills were occupied with British war needs and cloth imports to India actually <em>fell</em>, which is exactly why Indian mills had room to expand." },
  ],
  caseStudies: [
    { title: "The weaver and the advance", importance: "high",
      source: "A weaver in a Bengal village in the 1770s, once free to sell his cloth to any trader who offered a good price, is now dependent on a gomastha appointed by the East India Company. To secure his supply of cloth, the gomastha has given the weaver an advance to purchase the raw silk thread he needs. But by accepting this advance, the weaver has bound himself: he can no longer sell his finished cloth to any other merchant, and if he tries, the Company's agents deal with him harshly. When cotton prices rise or the harvest fails, he has no cushion — he owes the advance regardless.",
      parts: [
        { q: "Who was a gomastha, and what was his role in this system?", marks: 1,
          answer: "A gomastha was a paid servant of the East India Company, appointed to supervise weavers, collect the cloth they produced, and examine its quality — replacing the independent traders who had earlier dealt with weavers." },
        { q: "Why could the weaver in the passage not sell his cloth to another merchant?", marks: 1,
          answer: "Because he had accepted an <strong>advance</strong> (a loan) from the gomastha to buy his raw material. Under this system, once a weaver took an advance, he was bound to supply his cloth only to the Company and could not deal with any other buyer." },
        { q: "What long-term effect did this system of advances have on many weavers?", marks: 2,
          answer: "Many weavers, unable to negotiate fair prices and trapped by recurring loans, fell deeply into <strong>debt</strong>. A large number eventually lost their land and their independence, becoming entirely dependent on the Company rather than being free producers who sold to the highest bidder." },
        { q: "How does this passage illustrate the wider decline of Indian weavers in the colonial period?", marks: 1,
          answer: "It shows that the crisis was not only about competition from Manchester cloth — it began earlier, with the Company's own system of control through gomasthas and advances, which stripped weavers of bargaining power well before machine-made imports arrived in large numbers." },
      ] },
  ],
};
