import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "print-culture-and-the-modern-world",
  num: 5,
  title: "Print Culture and the Modern World",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · 20 marks",
  minutes: 20,
  blurb: "A technology for copying words turned out to be a technology for changing minds — and every authority in Europe and India understood that quickly.",
  bigIdea: "Print did not merely spread existing ideas faster. By letting ordinary people read, argue and disagree in public, it created a new kind of public — and made both reform and revolution possible.",
  syllabus: [
    "The first printed books",
    "Print comes to Europe",
    "The print revolution and its impact",
    "The reading mania",
    "The nineteenth century",
    "India and the world of print",
    "Religious reform and public debates",
    "New forms of publication",
    "Print and censorship",
  ],
  blocks: [
    { t: "h", text: "From woodblock to movable type" },
    { t: "sim", id: "print-culture-timeline" },
    { t: "p", html: "The earliest print technology was developed in China, Japan and Korea. From <strong>594 CE</strong> books in China were printed by rubbing paper against the inked surface of woodblocks. Because the traditional Chinese 'accordion book' was folded and stitched at the side, the technique of hand printing developed as skilled craftsmanship." },
    { t: "note", kind: "idea", html: "For a very long time the <strong>imperial state in China was the major producer of printed material</strong>, chiefly for the civil service examinations. Print began as a tool of the state. It only later became a tool of merchants, of the reading public, and finally of dissent." },
    { t: "p", html: "Marco Polo brought the knowledge of woodblock printing back to Italy from China in 1295. By the fifteenth century woodblocks were widely used in Europe — but they could not meet the growing demand for books." },
    { t: "note", kind: "why", title: "What Gutenberg actually did", html: "<strong>Johann Gutenberg</strong> adapted existing technology to a new purpose. He knew the olive press, so he adapted it into the printing press. He knew polishing stones and had experience with goldsmithing, so he developed <strong>movable metal type</strong> for each letter of the alphabet.<br><br>The <strong>Bible</strong> was the first book he printed. About 180 copies took three years to produce — which, by the standards of hand-copying, was extraordinarily fast. This is the <strong>print revolution</strong>." },

    { t: "h", text: "What print did to Europe" },
    { t: "list", ordered: true, items: [
      "<strong>A new reading public.</strong> Books could be produced in far greater numbers and at lower cost, so a wider readership emerged. But literacy was low, so publishers began printing popular ballads and folk tales, and books were often <strong>read aloud</strong> — the line between the hearing public and the reading public blurred.",
      "<strong>Religious debate and fear.</strong> In 1517 <strong>Martin Luther</strong> wrote his Ninety Five Theses criticising the Roman Catholic Church. Printed and widely circulated, it led to a division within the Church. Luther said, 'Printing is the ultimate gift of God and the greatest one.'",
      "<strong>Fear of print.</strong> Not everyone welcomed it. Religious authorities and monarchs feared that if uncontrolled printed matter reached the common people, rebellious and irreligious thoughts would spread. From <strong>1558</strong> the Roman Church maintained an <strong>Index of Prohibited Books</strong>.",
      "<strong>Reading mania.</strong> Through the seventeenth and eighteenth centuries literacy rates rose across Europe. New forms appeared — almanacs, ballads, folktales, and in England the penny <em>chapbooks</em> carried by pedlars called chapmen.",
    ] },
    { t: "note", kind: "real", title: "Print and the French Revolution", html: "Three arguments are usually made, and a good answer gives all three with the qualification.<br><br>1. Print popularised the ideas of the Enlightenment thinkers, who attacked the authority of the Church and the despotism of the state.<br>2. Print created a new culture of <strong>dialogue and debate</strong>; values and institutions were re-evaluated in public.<br>3. Literature mocked royalty and raised questions about the existing order.<br><br>The qualification, which earns the extra mark: people did not read just one kind of literature, and they did not accept everything they read. Print opened the possibility of thinking differently — it did not determine what people thought." },

    { t: "h", text: "Print comes to India" },
    { t: "p", html: "India had a rich and old tradition of handwritten manuscripts — in Sanskrit, Arabic, Persian and vernacular languages, copied on palm leaves or handmade paper. But manuscripts were expensive, fragile, and could not be read easily because scripts were written in different styles." },
    { t: "list", items: [
      "The printing press first came to <strong>Goa with Portuguese missionaries</strong> in the mid-sixteenth century. Jesuit priests learnt Konkani and printed several tracts.",
      "By 1674 about 50 books had been printed in Konkani and Kanara languages. The first <strong>Tamil book</strong> was printed at Cochin in 1579, and the first <strong>Malayalam book</strong> in 1713.",
      "<strong>James Augustus Hickey</strong> began the <em>Bengal Gazette</em> in 1780, 'a commercial paper open to all, but influenced by none'. He published a good deal of gossip about the Company's senior officials, and Governor-General Warren Hastings persecuted him.",
      "By the close of the eighteenth century a number of newspapers and journals appeared in print, and Indians also began to publish.",
    ] },

    { t: "h", text: "Religious reform and public debate" },
    { t: "p", html: "From the early nineteenth century, intense controversies took place around religious issues — widow immolation, monotheism, Brahmanical priesthood, idolatry. Printed tracts and newspapers not only spread the new ideas but shaped the nature of the debate, because a wider public could now participate and express its views." },
    { t: "note", kind: "idea", html: "<strong>Rammohun Roy</strong> published the <em>Sambad Kaumudi</em> from 1821, and Hindu orthodoxy commissioned the <em>Samachar Chandrika</em> to oppose his opinions. From 1822 two Persian newspapers, <em>Jam-i-Jahan Nama</em> and <em>Shamsul Akhbar</em>, were published. This is what a public sphere looks like — arguments in print, answered in print." },
    { t: "list", items: [
      "In north India, the <strong>ulama</strong> used cheap lithographic presses to publish Persian and Urdu translations of holy scriptures and printed religious newspapers and tracts. The <strong>Deoband Seminary</strong>, founded in 1867, published thousands of <em>fatwas</em>.",
      "Print encouraged the reading of religious texts in vernacular languages. The first printed edition of the <strong>Ramcharitmanas</strong> came out from Calcutta in 1810.",
      "Naval Kishore Press at Lucknow and Shri Venkateshwar Press in Bombay published numerous religious texts in vernaculars.",
    ] },

    { t: "h", text: "New readers" },
    { t: "table", head: ["Group", "What print meant for them"], rows: [
      ["<strong>Women</strong>", "Women's reading increased enormously. Liberal husbands and fathers educated their womenfolk at home; some women learnt in secret. <strong>Rashsundari Debi</strong> wrote <em>Amar Jiban</em> (1876), the first full-length autobiography in Bengali. Journals written by and for women discussed education, widowhood and widow remarriage."],
      ["<strong>Poor people</strong>", "Very cheap small books were sold at crossroads in nineteenth-century Madras. Public libraries came up from the early twentieth century. <strong>Jyotiba Phule</strong> wrote about caste injustice in <em>Gulamgiri</em> (1871); B. R. Ambedkar and E. V. Ramaswamy Naicker wrote powerfully on caste."],
      ["<strong>Workers</strong>", "Factory workers were too overworked to write much, but <strong>Kashibaba</strong> wrote and published <em>Chhote Aur Bade Ka Sawal</em> in 1938 to show the links between caste and class exploitation. Workers set up libraries to educate themselves."],
    ] },

    { t: "h", text: "Censorship" },
    { t: "p", html: "Before 1798 the colonial state was not too concerned with censorship — its early measures were aimed at controlling <em>English</em> publications critical of Company misrule. By the 1820s the Company began to restrict press freedom, and after the revolt of 1857 the attitude hardened." },
    { t: "note", kind: "exam", html: "The <strong>Vernacular Press Act of 1878</strong>, modelled on the Irish Press Laws, gave the government extensive rights to censor reports and editorials in the vernacular press. If a report was judged seditious, the newspaper was warned; if the warning was ignored, the press could be seized and the printing machinery confiscated. Learn the name, the year and the model." },
    { t: "note", kind: "real", html: "Despite censorship, nationalist newspapers grew in number across India. When <strong>Balgangadhar Tilak</strong> wrote with sympathy about Punjab revolutionaries in his <em>Kesari</em>, he was imprisoned in 1908, provoking widespread protest all over India. Repression made print more powerful, not less." },
  ],
  examFocus: [
    "Woodblock printing in China, and print as an instrument of the state before it became one of dissent.",
    "What Gutenberg adapted, the Bible as the first printed book, and what 'print revolution' means.",
    "Luther, the Ninety Five Theses, and the Index of Prohibited Books from 1558.",
    "The three arguments linking print to the French Revolution — with the qualification.",
    "Print's arrival in Goa, the first Tamil and Malayalam books, and the Bengal Gazette of 1780.",
    "Rammohun Roy, Samachar Chandrika, and print as a public sphere.",
    "What print meant for women, poor people and workers — one named example each.",
    "The Vernacular Press Act of 1878 and Tilak's imprisonment in 1908.",
  ],
  flashcards: [
    { q: "Where and when did the earliest print technology develop?", a: "In China, Japan and Korea. From 594 CE books in China were printed by rubbing paper against the inked surface of woodblocks." },
    { q: "Who was the major producer of printed material in China for a long time, and why?", a: "The imperial state, chiefly to produce textbooks for the civil service examinations, which recruited its personnel." },
    { q: "What did Gutenberg adapt to build the printing press?", a: "The olive press became the model for the printing press, and his goldsmithing experience let him develop movable metal type for each letter of the alphabet." },
    { q: "What was the first book Gutenberg printed?", a: "The Bible. About 180 copies were printed and it took three years to produce them." },
    { q: "What was the print revolution?", a: "The transformation brought by the shift from hand copying to printing — books could be produced faster and cheaper, a new reading public emerged, and a new culture of debate developed." },
    { q: "How did print affect the Protestant Reformation?", a: "Martin Luther's Ninety Five Theses of 1517, criticising the Roman Catholic Church, was printed and widely circulated, leading to a division within the Church. Luther called printing 'the ultimate gift of God'." },
    { q: "What was the Index of Prohibited Books?", a: "A list maintained by the Roman Church from 1558 of books that Catholics were forbidden to read, a response to the fear that uncontrolled printed matter would spread irreligious ideas." },
    { q: "Give three ways print contributed to the French Revolution.", a: "It popularised Enlightenment ideas that attacked Church authority and state despotism; it created a culture of dialogue and public debate; and literature mocked royalty and questioned the existing order. But people did not accept everything they read — print opened the possibility of thinking differently." },
    { q: "When and how did print reach India?", a: "The printing press came to Goa with Portuguese missionaries in the mid-sixteenth century. The first Tamil book was printed at Cochin in 1579 and the first Malayalam book in 1713." },
    { q: "What was the Bengal Gazette?", a: "A weekly begun in 1780 by James Augustus Hickey, describing itself as 'a commercial paper open to all, but influenced by none'. It gossiped about senior Company officials and was persecuted by Warren Hastings." },
    { q: "Who wrote Amar Jiban and why does it matter?", a: "Rashsundari Debi, a housewife in a rural Bengal village, wrote it in 1876. It was the first full-length autobiography published in Bengali, and she had taught herself to read in secret." },
    { q: "Name two writers who used print to attack caste injustice.", a: "Jyotiba Phule, who wrote Gulamgiri in 1871, and later B. R. Ambedkar and E. V. Ramaswamy Naicker, whose writings were widely read across India." },
    { q: "What was the Vernacular Press Act of 1878?", a: "Modelled on the Irish Press Laws, it gave the government extensive rights to censor reports and editorials in the vernacular press. Repeated offences allowed the press to be seized and the printing machinery confiscated." },
    { q: "What happened to Balgangadhar Tilak in 1908?", a: "He was imprisoned after writing with sympathy about Punjab revolutionaries in his newspaper Kesari, which provoked widespread protest across India." },
  ],
  quiz: [
    { q: "The earliest kind of print technology was developed in:", options: ["Germany", "China, Japan and Korea", "Italy", "India"], answer: 1, why: "Hand printing from woodblocks developed in China, Japan and Korea, with Chinese books printed from 594 CE." },
    { q: "Gutenberg's first printed book was:", options: ["A dictionary", "The Bible", "A ballad collection", "An almanac"], answer: 1, why: "About 180 copies were printed and it took three years to produce them." },
    { q: "Martin Luther's Ninety Five Theses were published in:", options: ["1450", "1517", "1558", "1780"], answer: 1, why: "His criticism of the Roman Catholic Church was printed in 1517 and circulated widely, leading to a division within the Church." },
    { q: "The Index of Prohibited Books was maintained from 1558 by:", options: ["The French monarchy", "The Roman Church", "The British Parliament", "The East India Company"], answer: 1, why: "It listed books Catholics were forbidden to read, reflecting the Church's fear of uncontrolled print." },
    { q: "The printing press first came to India with:", options: ["The British", "Portuguese missionaries in Goa", "Dutch traders", "Mughal rulers"], answer: 1, why: "Portuguese missionaries brought it to Goa in the mid-sixteenth century, and Jesuit priests printed tracts in Konkani." },
    { q: "The Bengal Gazette was published by:", options: ["Rammohun Roy", "James Augustus Hickey", "Warren Hastings", "Balgangadhar Tilak"], answer: 1, why: "Hickey began the weekly in 1780 and was persecuted by Warren Hastings for his gossip about Company officials." },
    { q: "Rammohun Roy published which newspaper from 1821?", options: ["Samachar Chandrika", "Sambad Kaumudi", "Kesari", "Jam-i-Jahan Nama"], answer: 1, why: "Hindu orthodoxy responded by commissioning the Samachar Chandrika to oppose his opinions." },
    { q: "Amar Jiban, the first full-length autobiography in Bengali, was written by:", options: ["Kailashbashini Debi", "Rashsundari Debi", "Tarabai Shinde", "Pandita Ramabai"], answer: 1, why: "Rashsundari Debi, a housewife who taught herself to read in secret, published it in 1876." },
    { q: "Gulamgiri (1871), attacking caste injustice, was written by:", options: ["B. R. Ambedkar", "Jyotiba Phule", "E. V. Ramaswamy Naicker", "Kashibaba"], answer: 1, why: "Jyotiba Phule wrote about the injustices of the caste system in Gulamgiri in 1871." },
    { q: "The Vernacular Press Act of 1878 was modelled on:", options: ["The Irish Press Laws", "American press law", "The Index of Prohibited Books", "The Rowlatt Act"], answer: 0, why: "It gave the government extensive rights to censor the vernacular press and to confiscate printing machinery for repeated offences." },
    { q: "The first printed edition of the Ramcharitmanas came out from Calcutta in:", options: ["1780", "1810", "1867", "1878"], answer: 1, why: "Print encouraged the reading of religious texts in vernacular languages, and the Ramcharitmanas was printed in 1810." },
    { q: "The Deoband Seminary, founded in 1867, used print mainly to:", options: ["Publish novels", "Publish fatwas and religious guidance", "Print newspapers in English", "Produce school textbooks"], answer: 1, why: "It published thousands of fatwas telling Muslim readers how to conduct themselves in their everyday lives." },
  ],
  keyTopics: [
    { name: "Gutenberg and the print revolution", importance: "high", note: "What he adapted, the Bible as first printed book — a reliable 2–3 mark question and the anchor of a case study." },
    { name: "Print and the French Revolution — the three arguments (with the qualification)", importance: "high", note: "The chapter's classic 5-mark question. Losing the qualification ('print did not determine what people thought') costs a mark." },
    { name: "Censorship in colonial India — the Vernacular Press Act of 1878", importance: "high", note: "Name, year and model (Irish Press Laws) are frequently tested, often alongside Tilak's imprisonment in 1908." },
    { name: "Print's arrival in India — Goa, the Bengal Gazette, Rammohun Roy", importance: "high", note: "Dates and named firsts (first Tamil/Malayalam book, Hickey's paper) are common 1–3 mark recall." },
    { name: "New readers — what print meant for women, the poor and workers", importance: "medium", note: "Expect one named example per group — Rashsundari Debi, Jyotiba Phule, Kashibaba." },
    { name: "Religious reform and public debate in print", importance: "medium", note: "Rammohun Roy vs Samachar Chandrika, and the ulama's use of lithographic presses, illustrate print as a 'public sphere'." },
    { name: "Luther, the Reformation and the Index of Prohibited Books", importance: "medium", note: "Shows both sides — print as a tool of reform, and the fear it provoked in authority." },
    { name: "Woodblock printing in China and print as an instrument of the state", importance: "low", note: "Sets up the chapter's opening idea; usually only a short recall question." },
  ],
  written: [
    { q: "What was the first book Gutenberg printed, and how many copies were produced?", marks: 1, kind: "short", importance: "high",
      answer: "The <strong>Bible</strong>. About <strong>180 copies</strong> were printed, taking three years to produce — extraordinarily fast compared to hand-copying." },
    { q: "In which year was the Vernacular Press Act passed, and on which law was it modelled?", marks: 1, kind: "short", importance: "high",
      answer: "It was passed in <strong>1878</strong>, modelled on the <strong>Irish Press Laws</strong>." },
    { q: "How did Johann Gutenberg develop the technology of the printing press?", marks: 2, kind: "short", importance: "high",
      answer: "Gutenberg was familiar with the <strong>olive press</strong> used in his region, and adapted its mechanism to build the printing press. His experience as a <strong>goldsmith</strong> allowed him to develop durable <strong>movable metal type</strong> for each letter of the alphabet, which could be arranged and rearranged to print different texts quickly." },
    { q: "What was the 'Index of Prohibited Books'?", marks: 2, kind: "short", importance: "medium",
      answer: "A list of books banned by the <strong>Roman Church</strong>, maintained from <strong>1558</strong>, which Catholics were forbidden to read. It reflected the fear of religious and secular authorities that uncontrolled printed material would spread rebellious and irreligious ideas among the common people." },
    { q: "Why did Rammohun Roy publish the Sambad Kaumudi, and how did Hindu orthodoxy respond?", marks: 2, kind: "short", importance: "medium",
      answer: "Rammohun Roy published the <em>Sambad Kaumudi</em> from 1821 to spread his reformist religious views and campaign against practices such as widow immolation. Hindu orthodoxy responded by <strong>commissioning the <em>Samachar Chandrika</em></strong> to oppose his opinions — a clear example of print creating a public debate conducted entirely in print." },
    { q: "Explain any three ways in which print culture created a new reading public in Europe.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>Books could now be <strong>produced in far greater numbers and at a much lower cost</strong> than hand-copied manuscripts, so a wider section of society could afford to buy them.</li><li>Since literacy levels remained low for a long time, publishers began printing <strong>popular ballads and folk tales</strong>, often illustrated, that could be enjoyed even by those who could not read well.</li><li>Books were frequently <strong>read aloud</strong> to groups of listeners in villages and taverns, so the line between a 'reading public' and a 'hearing public' blurred — print reached far beyond those who were literate.</li></ul>" },
    { q: "Describe what print meant for women readers in nineteenth-century India, with examples.", marks: 3, kind: "long", importance: "medium",
      answer: "<ul><li>Women's reading increased enormously in the nineteenth century, though access still depended on the family — <strong>liberal husbands and fathers</strong> educated women at home, while others were forced to <strong>learn in secret</strong>.</li><li><strong>Rashsundari Debi</strong>, a housewife in rural Bengal who had taught herself to read in secret, wrote <em>Amar Jiban</em> in 1876 — the <strong>first full-length autobiography</strong> published in the Bengali language.</li><li>Journals specifically written by and for women began to discuss issues such as women's <strong>education, widowhood and widow remarriage</strong>, giving women a public space to debate their own concerns for the first time.</li></ul>" },
    { q: "Explain the provisions of the Vernacular Press Act of 1878 and its effect on Indian journalism.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>Modelled on the <strong>Irish Press Laws</strong>, the Act gave the colonial government extensive powers to <strong>censor reports and editorials</strong> published in the vernacular (Indian-language) press.</li><li>If a report was judged <strong>seditious</strong>, the newspaper was first issued a warning; if the warning was ignored, the government could <strong>seize the press and confiscate the printing machinery</strong>.</li><li>Despite the Act, nationalist newspapers continued to <strong>grow in number</strong> across India — when <strong>Balgangadhar Tilak</strong> wrote sympathetically about Punjab revolutionaries in his paper <em>Kesari</em>, he was imprisoned in <strong>1908</strong>, an act of repression that provoked widespread protest rather than silence.</li></ul>" },
    { q: "'Print did not merely popularise ideas — it created an entirely new culture of debate.' Discuss this statement with reference to the French Revolution.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Spreading Enlightenment ideas:</strong> print popularised the ideas of Enlightenment thinkers, who collectively attacked the sacred authority of the Church and the despotic power of the state, giving people a shared vocabulary with which to question authority.</li><li><strong>A culture of dialogue and debate:</strong> print created the possibility of wide, simultaneous discussion — the same ideas could now be read, discussed and challenged by people across France at the same time, so existing values and institutions were re-evaluated by a large reading public, not just a few elites.</li><li><strong>Satire and mockery:</strong> a large body of literature mocked royalty and criticised their morality, indirectly building up a case for the Revolution by making the monarchy an object of public ridicule rather than reverence.</li></ul><strong>The necessary qualification:</strong> however, people did not read only one kind of literature, and did not uncritically believe everything that was printed. It would therefore be wrong to say print directly 'caused' the Revolution — what it did was to open up the <strong>possibility of thinking differently</strong>, and it was this openness, more than any single printed idea, that made the Revolution imaginable." },
    { q: "Trace the arrival and early development of print culture in India, from the sixteenth century to the end of the eighteenth century.", marks: 5, kind: "long", importance: "medium",
      answer: "<ul><li>The printing press first reached India at <strong>Goa</strong> with Portuguese missionaries in the mid-sixteenth century; Jesuit priests learnt the local Konkani language and printed several religious tracts.</li><li>By <strong>1674</strong> about fifty books had been printed in the Konkani and Kanara languages. The first <strong>Tamil book</strong> was printed at Cochin in <strong>1579</strong>, and the first <strong>Malayalam book</strong> in <strong>1713</strong>.</li><li>Catholic priests printed the first Tamil and Malayalam books, but for a long time print remained largely a tool of missionary religious activity rather than a public medium.</li><li>This changed with <strong>James Augustus Hickey</strong>, who began the <em>Bengal Gazette</em> in <strong>1780</strong> — describing it as 'a commercial paper open to all, but influenced by none'. He printed a good deal of gossip about senior Company officials, for which Governor-General <strong>Warren Hastings</strong> persecuted him.</li><li>By the close of the eighteenth century a number of newspapers and journals had appeared in print, and <strong>Indians themselves</strong> had begun to publish, setting the stage for the explosion of vernacular and nationalist print in the nineteenth century.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Manuscripts written in India could not be easily read by everyone.",
      reason: "Manuscripts were also expensive and fragile, and had to be handled carefully.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but R does not explain A — manuscripts being hard to read was because of different, non-standardised scripts and styles of handwriting, which is a separate problem from their expense and fragility." },
    { assertion: "Martin Luther condemned the printing press as a corrupting, ungodly invention.",
      reason: "His Ninety Five Theses of 1517, criticising the Roman Catholic Church, were printed and circulated widely, leading to a division within the Church.",
      answer: 3, importance: "high",
      why: "A is false — Luther in fact praised print, calling it 'the ultimate gift of God and the greatest one'. R is true, and it was precisely this wide circulation of his printed Theses that fuelled his enthusiasm for the new technology." },
    { assertion: "Not all readers in nineteenth-century Europe accepted everything they encountered in print.",
      reason: "People responded to printed ideas in very different ways — some questioned established beliefs, while others held firmly to traditional views regardless of what they read.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly explains A — print opened up the possibility of new ideas reaching people, but it did not determine what any individual reader chose to believe." },
    { assertion: "Balgangadhar Tilak was imprisoned in 1908 for writing sympathetically about Punjab revolutionaries in his newspaper Kesari.",
      reason: "The Vernacular Press Act was enacted specifically in response to Tilak's writings, to allow the government to imprison him.",
      answer: 2, importance: "high",
      why: "A is true — Tilak was imprisoned in 1908 over his articles in Kesari. R is false: the Vernacular Press Act was passed thirty years earlier, in <strong>1878</strong>, so it could not have been enacted in response to an event that had not yet happened." },
  ],
  caseStudies: [
    { title: "Gutenberg and the print revolution", importance: "high",
      source: "In the German city of Strasbourg, Johann Gutenberg spent years perfecting a new device for printing. He was familiar with the mechanism of the olive press used to extract oil, and adapted its design to build the printing press; his experience as a goldsmith helped him cast individual metal type for every letter of the alphabet, which could be arranged and rearranged to print different pages. The first major book he printed was the Bible — about 180 copies were produced over roughly three years, a pace of output that hand-copying could never have matched. Martin Luther later called printing 'the ultimate gift of God and the greatest one'.",
      parts: [
        { q: "Name two earlier crafts or technologies that Gutenberg drew upon to build his printing press.", marks: 2,
          answer: "The <strong>olive press</strong>, whose mechanism he adapted for the printing press, and his skill as a <strong>goldsmith</strong>, which allowed him to cast movable metal type for each letter of the alphabet." },
        { q: "Which book did Gutenberg print first, and roughly how many copies were made?", marks: 1,
          answer: "The <strong>Bible</strong>; about <strong>180 copies</strong> were produced." },
        { q: "Why is Gutenberg's achievement described as a 'print revolution' rather than a simple improvement in technology?", marks: 1,
          answer: "Because it changed the <em>scale</em> of what was possible — books could now be produced far faster and far more cheaply than by hand-copying, allowing a much wider reading public to emerge and putting new ideas within reach of ordinary people for the first time." },
        { q: "How did Martin Luther regard the invention of the printing press?", marks: 1,
          answer: "He welcomed it enthusiastically, calling it 'the ultimate gift of God and the greatest one' — recognising how the printed and widely circulated Ninety Five Theses had helped his ideas spread." },
      ] },
    { title: "Censoring the vernacular press", importance: "high",
      source: "By the 1870s the colonial government, once relatively unconcerned with the Indian-language press, had grown anxious about the increasingly nationalist and critical tone of vernacular newspapers. In 1878 it passed a law modelled on a similar law used in Ireland, giving magistrates wide powers to censor reports and editorials in the vernacular press. If a report was judged seditious, the newspaper concerned was first issued a warning; if the warning was ignored, the government could seize the press and confiscate its printing machinery. Despite this, nationalist newspapers continued to multiply across the country, and in 1908 the editor of a prominent Marathi paper was sent to prison for writing sympathetically about revolutionaries.",
      parts: [
        { q: "Name the law described in the passage, the year it was passed, and the law it was modelled on.", marks: 2,
          answer: "The <strong>Vernacular Press Act</strong>, passed in <strong>1878</strong>, modelled on the <strong>Irish Press Laws</strong>." },
        { q: "What happened if a report in the vernacular press was judged to be seditious under this law?", marks: 1,
          answer: "The newspaper was first given a <strong>warning</strong>; if the warning was ignored, the government could <strong>seize the press and confiscate its printing machinery</strong>." },
        { q: "Identify the newspaper and its editor referred to at the end of the passage, and explain why he was imprisoned.", marks: 2,
          answer: "The newspaper was <em>Kesari</em>, edited by <strong>Balgangadhar Tilak</strong>. He was imprisoned in 1908 for writing with sympathy about revolutionaries in Punjab, an act of repression that provoked widespread protest across India rather than silencing the nationalist press." },
      ] },
  ],
};
