import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "print-culture-and-the-modern-world",
  num: 5,
  title: "Print Culture and the Modern World",
  unit: "history",
  unitName: "India and the Contemporary World — II",
  marks: "History · 20 marks",
  minutes: 20,
  blurb: "A technology for copying words turned out to be a technology for changing minds — and every authority in Europe and India understood that quickly.",
  bigIdea: "Print did not merely spread existing ideas faster. By letting ordinary people read, argue and disagree in public, it created a new kind of public — and made both reform and revolution possible.",
  syllabus: [
    "The first printed books",
    "Print comes to Europe",
    "The print revolution and its impact",
    "The reading mania",
    "The nineteenth century",
    "India and the world of print",
    "Religious reform and public debates",
    "New forms of publication",
    "Print and censorship",
  ],
  blocks: [
    { t: "h", text: "From woodblock to movable type" },
    { t: "sim", id: "print-culture-timeline" },
    { t: "p", html: "The earliest print technology was developed in China, Japan and Korea. From <strong>594 CE</strong> books in China were printed by rubbing paper against the inked surface of woodblocks. Because the traditional Chinese 'accordion book' was folded and stitched at the side, the technique of hand printing developed as skilled craftsmanship." },
    { t: "note", kind: "idea", html: "For a very long time the <strong>imperial state in China was the major producer of printed material</strong>, chiefly for the civil service examinations. Print began as a tool of the state. It only later became a tool of merchants, of the reading public, and finally of dissent." },
    { t: "p", html: "Marco Polo brought the knowledge of woodblock printing back to Italy from China in 1295. By the fifteenth century woodblocks were widely used in Europe — but they could not meet the growing demand for books." },
    { t: "note", kind: "why", title: "What Gutenberg actually did", html: "<strong>Johann Gutenberg</strong> adapted existing technology to a new purpose. He knew the olive press, so he adapted it into the printing press. He knew polishing stones and had experience with goldsmithing, so he developed <strong>movable metal type</strong> for each letter of the alphabet.<br><br>The <strong>Bible</strong> was the first book he printed. About 180 copies took three years to produce — which, by the standards of hand-copying, was extraordinarily fast. This is the <strong>print revolution</strong>." },

    { t: "h", text: "What print did to Europe" },
    { t: "list", ordered: true, items: [
      "<strong>A new reading public.</strong> Books could be produced in far greater numbers and at lower cost, so a wider readership emerged. But literacy was low, so publishers began printing popular ballads and folk tales, and books were often <strong>read aloud</strong> — the line between the hearing public and the reading public blurred.",
      "<strong>Religious debate and fear.</strong> In 1517 <strong>Martin Luther</strong> wrote his Ninety Five Theses criticising the Roman Catholic Church. Printed and widely circulated, it led to a division within the Church. Luther said, 'Printing is the ultimate gift of God and the greatest one.'",
      "<strong>Fear of print.</strong> Not everyone welcomed it. Religious authorities and monarchs feared that if uncontrolled printed matter reached the common people, rebellious and irreligious thoughts would spread. From <strong>1558</strong> the Roman Church maintained an <strong>Index of Prohibited Books</strong>.",
      "<strong>Reading mania.</strong> Through the seventeenth and eighteenth centuries literacy rates rose across Europe. New forms appeared — almanacs, ballads, folktales, and in England the penny <em>chapbooks</em> carried by pedlars called chapmen.",
    ] },
    { t: "note", kind: "real", title: "Print and the French Revolution", html: "Three arguments are usually made, and a good answer gives all three with the qualification.<br><br>1. Print popularised the ideas of the Enlightenment thinkers, who attacked the authority of the Church and the despotism of the state.<br>2. Print created a new culture of <strong>dialogue and debate</strong>; values and institutions were re-evaluated in public.<br>3. Literature mocked royalty and raised questions about the existing order.<br><br>The qualification, which earns the extra mark: people did not read just one kind of literature, and they did not accept everything they read. Print opened the possibility of thinking differently — it did not determine what people thought." },

    { t: "h", text: "Print comes to India" },
    { t: "p", html: "India had a rich and old tradition of handwritten manuscripts — in Sanskrit, Arabic, Persian and vernacular languages, copied on palm leaves or handmade paper. But manuscripts were expensive, fragile, and could not be read easily because scripts were written in different styles." },
    { t: "list", items: [
      "The printing press first came to <strong>Goa with Portuguese missionaries</strong> in the mid-sixteenth century. Jesuit priests learnt Konkani and printed several tracts.",
      "By 1674 about 50 books had been printed in Konkani and Kanara languages. The first <strong>Tamil book</strong> was printed at Cochin in 1579, and the first <strong>Malayalam book</strong> in 1713.",
      "<strong>James Augustus Hickey</strong> began the <em>Bengal Gazette</em> in 1780, 'a commercial paper open to all, but influenced by none'. He published a good deal of gossip about the Company's senior officials, and Governor-General Warren Hastings persecuted him.",
      "By the close of the eighteenth century a number of newspapers and journals appeared in print, and Indians also began to publish.",
    ] },

    { t: "h", text: "Religious reform and public debate" },
    { t: "p", html: "From the early nineteenth century, intense controversies took place around religious issues — widow immolation, monotheism, Brahmanical priesthood, idolatry. Printed tracts and newspapers not only spread the new ideas but shaped the nature of the debate, because a wider public could now participate and express its views." },
    { t: "note", kind: "idea", html: "<strong>Rammohun Roy</strong> published the <em>Sambad Kaumudi</em> from 1821, and Hindu orthodoxy commissioned the <em>Samachar Chandrika</em> to oppose his opinions. From 1822 two Persian newspapers, <em>Jam-i-Jahan Nama</em> and <em>Shamsul Akhbar</em>, were published. This is what a public sphere looks like — arguments in print, answered in print." },
    { t: "list", items: [
      "In north India, the <strong>ulama</strong> used cheap lithographic presses to publish Persian and Urdu translations of holy scriptures and printed religious newspapers and tracts. The <strong>Deoband Seminary</strong>, founded in 1867, published thousands of <em>fatwas</em>.",
      "Print encouraged the reading of religious texts in vernacular languages. The first printed edition of the <strong>Ramcharitmanas</strong> came out from Calcutta in 1810.",
      "Naval Kishore Press at Lucknow and Shri Venkateshwar Press in Bombay published numerous religious texts in vernaculars.",
    ] },

    { t: "h", text: "New readers" },
    { t: "table", head: ["Group", "What print meant for them"], rows: [
      ["<strong>Women</strong>", "Women's reading increased enormously. Liberal husbands and fathers educated their womenfolk at home; some women learnt in secret. <strong>Rashsundari Debi</strong> wrote <em>Amar Jiban</em> (1876), the first full-length autobiography in Bengali. Journals written by and for women discussed education, widowhood and widow remarriage."],
      ["<strong>Poor people</strong>", "Very cheap small books were sold at crossroads in nineteenth-century Madras. Public libraries came up from the early twentieth century. <strong>Jyotiba Phule</strong> wrote about caste injustice in <em>Gulamgiri</em> (1871); B. R. Ambedkar and E. V. Ramaswamy Naicker wrote powerfully on caste."],
      ["<strong>Workers</strong>", "Factory workers were too overworked to write much, but <strong>Kashibaba</strong> wrote and published <em>Chhote Aur Bade Ka Sawal</em> in 1938 to show the links between caste and class exploitation. Workers set up libraries to educate themselves."],
    ] },

    { t: "h", text: "Censorship" },
    { t: "p", html: "Before 1798 the colonial state was not too concerned with censorship — its early measures were aimed at controlling <em>English</em> publications critical of Company misrule. By the 1820s the Company began to restrict press freedom, and after the revolt of 1857 the attitude hardened." },
    { t: "note", kind: "exam", html: "The <strong>Vernacular Press Act of 1878</strong>, modelled on the Irish Press Laws, gave the government extensive rights to censor reports and editorials in the vernacular press. If a report was judged seditious, the newspaper was warned; if the warning was ignored, the press could be seized and the printing machinery confiscated. Learn the name, the year and the model." },
    { t: "note", kind: "real", html: "Despite censorship, nationalist newspapers grew in number across India. When <strong>Balgangadhar Tilak</strong> wrote with sympathy about Punjab revolutionaries in his <em>Kesari</em>, he was imprisoned in 1908, provoking widespread protest all over India. Repression made print more powerful, not less." },
  ],
  examFocus: [
    "Woodblock printing in China, and print as an instrument of the state before it became one of dissent.",
    "What Gutenberg adapted, the Bible as the first printed book, and what 'print revolution' means.",
    "Luther, the Ninety Five Theses, and the Index of Prohibited Books from 1558.",
    "The three arguments linking print to the French Revolution — with the qualification.",
    "Print's arrival in Goa, the first Tamil and Malayalam books, and the Bengal Gazette of 1780.",
    "Rammohun Roy, Samachar Chandrika, and print as a public sphere.",
    "What print meant for women, poor people and workers — one named example each.",
    "The Vernacular Press Act of 1878 and Tilak's imprisonment in 1908.",
  ],
  flashcards: [
    { q: "Where and when did the earliest print technology develop?", a: "In China, Japan and Korea. From 594 CE books in China were printed by rubbing paper against the inked surface of woodblocks." },
    { q: "Who was the major producer of printed material in China for a long time, and why?", a: "The imperial state, chiefly to produce textbooks for the civil service examinations, which recruited its personnel." },
    { q: "What did Gutenberg adapt to build the printing press?", a: "The olive press became the model for the printing press, and his goldsmithing experience let him develop movable metal type for each letter of the alphabet." },
    { q: "What was the first book Gutenberg printed?", a: "The Bible. About 180 copies were printed and it took three years to produce them." },
    { q: "What was the print revolution?", a: "The transformation brought by the shift from hand copying to printing — books could be produced faster and cheaper, a new reading public emerged, and a new culture of debate developed." },
    { q: "How did print affect the Protestant Reformation?", a: "Martin Luther's Ninety Five Theses of 1517, criticising the Roman Catholic Church, was printed and widely circulated, leading to a division within the Church. Luther called printing 'the ultimate gift of God'." },
    { q: "What was the Index of Prohibited Books?", a: "A list maintained by the Roman Church from 1558 of books that Catholics were forbidden to read, a response to the fear that uncontrolled printed matter would spread irreligious ideas." },
    { q: "Give three ways print contributed to the French Revolution.", a: "It popularised Enlightenment ideas that attacked Church authority and state despotism; it created a culture of dialogue and public debate; and literature mocked royalty and questioned the existing order. But people did not accept everything they read — print opened the possibility of thinking differently." },
    { q: "When and how did print reach India?", a: "The printing press came to Goa with Portuguese missionaries in the mid-sixteenth century. The first Tamil book was printed at Cochin in 1579 and the first Malayalam book in 1713." },
    { q: "What was the Bengal Gazette?", a: "A weekly begun in 1780 by James Augustus Hickey, describing itself as 'a commercial paper open to all, but influenced by none'. It gossiped about senior Company officials and was persecuted by Warren Hastings." },
    { q: "Who wrote Amar Jiban and why does it matter?", a: "Rashsundari Debi, a housewife in a rural Bengal village, wrote it in 1876. It was the first full-length autobiography published in Bengali, and she had taught herself to read in secret." },
    { q: "Name two writers who used print to attack caste injustice.", a: "Jyotiba Phule, who wrote Gulamgiri in 1871, and later B. R. Ambedkar and E. V. Ramaswamy Naicker, whose writings were widely read across India." },
    { q: "What was the Vernacular Press Act of 1878?", a: "Modelled on the Irish Press Laws, it gave the government extensive rights to censor reports and editorials in the vernacular press. Repeated offences allowed the press to be seized and the printing machinery confiscated." },
    { q: "What happened to Balgangadhar Tilak in 1908?", a: "He was imprisoned after writing with sympathy about Punjab revolutionaries in his newspaper Kesari, which provoked widespread protest across India." },
  ],
  quiz: [
    { q: "The earliest kind of print technology was developed in:", options: ["Germany", "China, Japan and Korea", "Italy", "India"], answer: 1, why: "Hand printing from woodblocks developed in China, Japan and Korea, with Chinese books printed from 594 CE." },
    { q: "Gutenberg's first printed book was:", options: ["A dictionary", "The Bible", "A ballad collection", "An almanac"], answer: 1, why: "About 180 copies were printed and it took three years to produce them." },
    { q: "Martin Luther's Ninety Five Theses were published in:", options: ["1450", "1517", "1558", "1780"], answer: 1, why: "His criticism of the Roman Catholic Church was printed in 1517 and circulated widely, leading to a division within the Church." },
    { q: "The Index of Prohibited Books was maintained from 1558 by:", options: ["The French monarchy", "The Roman Church", "The British Parliament", "The East India Company"], answer: 1, why: "It listed books Catholics were forbidden to read, reflecting the Church's fear of uncontrolled print." },
    { q: "The printing press first came to India with:", options: ["The British", "Portuguese missionaries in Goa", "Dutch traders", "Mughal rulers"], answer: 1, why: "Portuguese missionaries brought it to Goa in the mid-sixteenth century, and Jesuit priests printed tracts in Konkani." },
    { q: "The Bengal Gazette was published by:", options: ["Rammohun Roy", "James Augustus Hickey", "Warren Hastings", "Balgangadhar Tilak"], answer: 1, why: "Hickey began the weekly in 1780 and was persecuted by Warren Hastings for his gossip about Company officials." },
    { q: "Rammohun Roy published which newspaper from 1821?", options: ["Samachar Chandrika", "Sambad Kaumudi", "Kesari", "Jam-i-Jahan Nama"], answer: 1, why: "Hindu orthodoxy responded by commissioning the Samachar Chandrika to oppose his opinions." },
    { q: "Amar Jiban, the first full-length autobiography in Bengali, was written by:", options: ["Kailashbashini Debi", "Rashsundari Debi", "Tarabai Shinde", "Pandita Ramabai"], answer: 1, why: "Rashsundari Debi, a housewife who taught herself to read in secret, published it in 1876." },
    { q: "Gulamgiri (1871), attacking caste injustice, was written by:", options: ["B. R. Ambedkar", "Jyotiba Phule", "E. V. Ramaswamy Naicker", "Kashibaba"], answer: 1, why: "Jyotiba Phule wrote about the injustices of the caste system in Gulamgiri in 1871." },
    { q: "The Vernacular Press Act of 1878 was modelled on:", options: ["The Irish Press Laws", "American press law", "The Index of Prohibited Books", "The Rowlatt Act"], answer: 0, why: "It gave the government extensive rights to censor the vernacular press and to confiscate printing machinery for repeated offences." },
    { q: "The first printed edition of the Ramcharitmanas came out from Calcutta in:", options: ["1780", "1810", "1867", "1878"], answer: 1, why: "Print encouraged the reading of religious texts in vernacular languages, and the Ramcharitmanas was printed in 1810." },
    { q: "The Deoband Seminary, founded in 1867, used print mainly to:", options: ["Publish novels", "Publish fatwas and religious guidance", "Print newspapers in English", "Produce school textbooks"], answer: 1, why: "It published thousands of fatwas telling Muslim readers how to conduct themselves in their everyday lives." },
  ],
};
