import type { Chapter } from "@/lib/types";

export const ch06: Chapter = {
  slug: "resources-and-development",
  num: 1,
  title: "Resources and Development",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 18,
  blurb: "Nothing is a resource until people can use it. Everything after that — classification, planning, conservation — follows from that one idea.",
  bigIdea: "Resources are not simply lying around waiting. They become resources when technology, institutions and human need turn them into something usable — which is why the same rock is worthless in one century and vital in the next.",
  syllabus: [
    "Types of resources",
    "Development of resources and resource planning in India",
    "Land resources and land utilisation",
    "Land degradation and conservation measures",
    "Soil as a resource — classification and types",
    "Soil erosion and soil conservation",
    "Map work: major soil types",
  ],
  blocks: [
    { t: "h", text: "What counts as a resource" },
    { t: "formula", name: "Definition",
      expr: "Everything available in our environment which can be used to satisfy our needs is a resource, provided it is <strong>technologically accessible</strong>, <strong>economically feasible</strong> and <strong>culturally acceptable</strong>." },
    { t: "table", head: ["Basis", "Types"], rows: [
      ["<strong>Origin</strong>", "Biotic (from the biosphere — plants, animals, people) and Abiotic (non-living — rocks, metals)"],
      ["<strong>Exhaustibility</strong>", "Renewable (solar, wind, water, forests) and Non-renewable (minerals, fossil fuels)"],
      ["<strong>Ownership</strong>", "Individual, Community, National, International"],
      ["<strong>Status of development</strong>", "Potential, Developed, Stock, Reserves"],
    ] },
    { t: "note", kind: "trap", html: "<strong>Stock</strong> versus <strong>reserves</strong> is a common confusion. Stock is material that has the potential to satisfy needs but which we lack the technology to use — hydrogen in water is a rich source of energy, but we do not have the technology to use it easily. <strong>Reserves</strong> are the subset of stock that <em>can</em> be used with existing technical know-how but has not been started — like water in dams for generating electricity." },
    { t: "note", kind: "real", html: "Potential resources are found in a region but not yet used. Rajasthan and Gujarat have enormous potential for wind and solar energy, but only a part of it has been developed so far." },

    { t: "h", text: "Development, and its price" },
    { t: "p", html: "Indiscriminate use of resources has led to three major problems: depletion for the satisfaction of a few individuals; accumulation of resources in a few hands, dividing society into haves and have-nots; and indiscriminate exploitation leading to global ecological crises such as global warming, ozone layer depletion, environmental pollution and land degradation." },
    { t: "note", kind: "idea", html: "The answer proposed is <strong>sustainable development</strong> — development that takes place without damaging the environment, and without compromising the needs of future generations. The <strong>Rio de Janeiro Earth Summit of 1992</strong> agreed on Agenda 21, a global agreement for combating environmental damage, poverty and disease through global cooperation." },
    { t: "note", kind: "exam", html: "Resource planning in India has three stages, and questions ask for all three in order: <strong>identification and inventory</strong> of resources across regions; <strong>evolving a planning structure</strong> with appropriate technology, skill and institutional setup; and <strong>matching the resource development plans with overall national development plans</strong>." },

    { t: "h", text: "Land use" },
    { t: "sim", id: "land-use" },
    { t: "p", html: "India has a land area of about <strong>3.28 million square kilometres</strong>, but land-use data is available for only about 93% of it. Land under permanent pasture has decreased. Most of the reported area classified as fallow other than current fallow is either of poor quality or the cost of cultivation is very high." },
    { t: "note", kind: "why", title: "Why land degradation matters", html: "Human activities such as deforestation, overgrazing, mining and quarrying have contributed significantly to land degradation. Mining sites are abandoned after excavation, leaving deep scars and traces of overburden. In Gujarat, Rajasthan, Madhya Pradesh and Maharashtra, overgrazing is one of the main reasons. In Punjab, Haryana and western Uttar Pradesh, over-irrigation causes <strong>waterlogging</strong> and increases salinity and alkalinity." },
    { t: "list", items: [
      "<strong>Afforestation and proper management of grazing</strong> can help to some extent.",
      "Planting of <strong>shelter belts</strong> of plants, control of overgrazing, stabilisation of sand dunes by growing thorny bushes.",
      "Proper management of wastelands, control of mining activities, and proper discharge and disposal of industrial effluents and wastes after treatment.",
    ] },

    { t: "h", text: "Soils of India" },
    { t: "table", head: ["Soil", "Where", "Character"], rows: [
      ["<strong>Alluvial</strong>", "The entire northern plains, and eastern coastal plains in the deltas of the Mahanadi, Godavari, Krishna and Kaveri", "Deposited by the Indus, Ganga and Brahmaputra. Very fertile, rich in potash, phosphoric acid and lime. Ideal for sugarcane, paddy and wheat. <em>Khadar</em> is new alluvium and more fertile; <em>bangar</em> is old alluvium with more kanker nodules"],
      ["<strong>Black (regur)</strong>", "The Deccan trap — Maharashtra, Saurashtra, Malwa, Madhya Pradesh, Chhattisgarh, extending along the Godavari and Krishna", "Made of lava flows. Ideal for growing <strong>cotton</strong>. Holds moisture extremely well, is rich in calcium carbonate, magnesium, potash and lime, but poor in phosphoric contents. Develops deep cracks in hot weather, which helps aeration"],
      ["<strong>Red and yellow</strong>", "Eastern and southern Deccan plateau, parts of Odisha, Chhattisgarh, southern middle Ganga plain, Western Ghats piedmont", "Develops on crystalline igneous rocks in areas of low rainfall. Red because of the diffusion of iron; yellow when it occurs in a hydrated form"],
      ["<strong>Laterite</strong>", "Karnataka, Kerala, Tamil Nadu, Madhya Pradesh, hilly areas of Odisha and Assam", "Develops under high temperature and heavy rainfall, as a result of intense leaching. Humus-poor. After adopting soil conservation techniques it is suitable for tea, coffee and cashew nut"],
      ["<strong>Arid</strong>", "Western Rajasthan", "Ranges from red to brown, generally sandy and saline. Lacks humus and moisture because evaporation is faster. Lower horizons are occupied by kanker, restricting water infiltration"],
      ["<strong>Forest</strong>", "Hilly and mountainous areas with sufficient rain forests", "Loamy and silty in valley sides, coarse-grained in upper slopes. In snow-covered areas they are acidic with low humus content"],
    ] },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "memory", html: "Match soil to crop and you have half the marks: <strong>alluvial → wheat, paddy, sugarcane; black → cotton; laterite → tea, coffee, cashew</strong>." },

    { t: "h", text: "Soil erosion and conservation" },
    { t: "list", items: [
      "<strong>Gully erosion</strong> — running water cuts through clayey soils making deep channels. Land unfit for cultivation is called <strong>bad land</strong>; in the Chambal basin such lands are called <strong>ravines</strong>.",
      "<strong>Sheet erosion</strong> — water flows as a sheet over large areas down a slope and washes away the topsoil.",
      "<strong>Wind erosion</strong> — wind blows loose soil off flat or sloping land.",
      "Defective methods of farming, especially <strong>ploughing up and down the slope</strong>, form channels for the quick flow of water.",
    ] },
    { t: "table", head: ["Conservation method", "How it works"], rows: [
      ["<strong>Contour ploughing</strong>", "Ploughing along the contour lines can decelerate the flow of water down the slopes"],
      ["<strong>Terrace farming</strong>", "Steps cut on slopes restrict erosion. Western and central Himalayas have well-developed terrace farming"],
      ["<strong>Strip cropping</strong>", "Large fields divided into strips, with strips of grass left in between to break the force of the wind"],
      ["<strong>Shelter belts</strong>", "Rows of trees planted to break wind force. They have contributed significantly to the stabilisation of sand dunes and to stabilising the desert in western India"],
    ] },
    { t: "note", kind: "exam", title: "Map work", html: "For this chapter the board asks you to identify <strong>major soil types</strong> on an outline map of India. Learn which soil belongs to which broad region — the table above is arranged for exactly that." },
  ],
  examFocus: [
    "The definition of a resource, with all three conditions.",
    "The four bases of classification, with examples.",
    "Stock versus reserves — hydrogen in water versus water in dams.",
    "The three stages of resource planning, in order.",
    "Sustainable development and the Rio Earth Summit of 1992.",
    "Causes of land degradation, region by region, and four conservation measures.",
    "The six soil types with location, character and matching crop.",
    "Types of soil erosion and four conservation methods.",
  ],
  flashcards: [
    { q: "Define a resource.", a: "Everything available in our environment which can be used to satisfy our needs, provided it is technologically accessible, economically feasible and culturally acceptable." },
    { q: "Distinguish between stock and reserves.", a: "Stock is material that could satisfy needs but which we lack the technology to use — hydrogen in water. Reserves are the part of stock that can be used with existing technology but has not been started — water in dams for electricity." },
    { q: "What are potential resources? Give an example.", a: "Resources found in a region that have not yet been used. Rajasthan and Gujarat have enormous potential for wind and solar energy, only partly developed so far." },
    { q: "What is sustainable development?", a: "Development that takes place without damaging the environment, and which does not compromise the needs of future generations." },
    { q: "What was agreed at the Rio Earth Summit of 1992?", a: "Agenda 21 — a global agreement to combat environmental damage, poverty and disease through global cooperation, with each local government drawing up its own local Agenda 21." },
    { q: "Name the three stages of resource planning in India.", a: "Identification and inventory of resources across regions; evolving a planning structure with appropriate technology, skill and institutional setup; and matching resource development plans with overall national development plans." },
    { q: "What is the difference between khadar and bangar?", a: "Khadar is new alluvium, found in the lower areas of the floodplain, finer and more fertile. Bangar is older alluvium on higher ground with more kanker nodules." },
    { q: "Why is black soil ideal for cotton?", a: "It is made from lava flows, holds moisture extremely well, and is rich in calcium carbonate, magnesium, potash and lime. It also develops deep cracks in hot weather, which helps aeration." },
    { q: "How does laterite soil form and what is it good for?", a: "Under high temperature and heavy rainfall, as a result of intense leaching which removes humus. After soil conservation techniques are applied it is suitable for tea, coffee and cashew nut." },
    { q: "What are ravines?", a: "Deep channels cut by running water through clayey soils, making the land unfit for cultivation. Such bad land in the Chambal basin is called ravines." },
    { q: "Name four methods of soil conservation.", a: "Contour ploughing along the contour lines; terrace farming on steep slopes; strip cropping with grass strips between; and shelter belts of trees to break wind force." },
    { q: "Which activities cause land degradation in which regions?", a: "Mining in Jharkhand, Chhattisgarh, Madhya Pradesh and Odisha; overgrazing in Gujarat, Rajasthan, Madhya Pradesh and Maharashtra; and over-irrigation causing waterlogging and salinity in Punjab, Haryana and western Uttar Pradesh." },
  ],
  quiz: [
    { q: "Hydrogen in water is best described as:", options: ["A reserve", "Stock", "A developed resource", "A biotic resource"], answer: 1, why: "It could satisfy needs but we lack the technology to use it easily, which is the definition of stock rather than reserve." },
    { q: "Which soil is most suitable for growing cotton?", options: ["Alluvial", "Black", "Laterite", "Arid"], answer: 1, why: "Black soil, also called regur, is made from lava flows, retains moisture well, and is ideal for cotton." },
    { q: "Laterite soil forms as a result of:", options: ["Volcanic activity", "Intense leaching under high temperature and heavy rainfall", "Wind deposition", "River deposition"], answer: 1, why: "Heavy rain leaches away the lime and silica, leaving a humus-poor soil." },
    { q: "Ravines in the Chambal basin are an example of:", options: ["Sheet erosion", "Wind erosion", "Gully erosion", "Waterlogging"], answer: 2, why: "Running water cuts deep channels through clayey soils, producing bad land known locally as ravines." },
    { q: "Ploughing along contour lines to slow water flow is called:", options: ["Strip cropping", "Terrace farming", "Contour ploughing", "Shelter belting"], answer: 2, why: "Contour ploughing decelerates the flow of water down the slope and reduces erosion." },
    { q: "The Earth Summit of 1992 was held at:", options: ["Stockholm", "Rio de Janeiro", "Kyoto", "Paris"], answer: 1, why: "The United Nations Conference on Environment and Development was held at Rio de Janeiro, Brazil, and agreed Agenda 21." },
    { q: "Over-irrigation in Punjab and Haryana has mainly caused:", options: ["Deforestation", "Waterlogging and increased salinity", "Gully erosion", "Wind erosion"], answer: 1, why: "Excess water raises the water table, causing waterlogging and increasing the salinity and alkalinity of the soil." },
    { q: "Alluvial soil is NOT typically found in:", options: ["The northern plains", "The Godavari delta", "Western Rajasthan", "The Kaveri delta"], answer: 2, why: "Western Rajasthan has arid soil — sandy, saline and low in humus. Alluvial soil is river-deposited." },
    { q: "Resources classified on the basis of ownership include:", options: ["Biotic and abiotic", "Renewable and non-renewable", "Individual, community, national and international", "Potential and developed"], answer: 2, why: "Ownership divides resources into individual, community, national and international categories." },
    { q: "India's total land area is approximately:", options: ["1.28 million sq km", "3.28 million sq km", "5.28 million sq km", "8.28 million sq km"], answer: 1, why: "India has a land area of about 3.28 million square kilometres, though land-use data is available for only about 93% of it." },
  ],
  keyTopics: [
    { name: "Classification of resources — origin, exhaustibility, ownership, status of development", importance: "high", note: "Almost every year as a 1–2 mark identify/classify question, and the four bases are frequently listed in a 3-mark answer." },
    { name: "Stock versus reserves", importance: "high", note: "A classic distinguish-between question and a favourite for assertion–reason — hydrogen in water versus water stored behind a dam." },
    { name: "Land degradation — causes and conservation measures", importance: "high", note: "'Explain any three/five measures' is asked almost every cycle, often region-linked (mining, overgrazing, over-irrigation)." },
    { name: "Soil types — location, characteristics, matching crop", importance: "high", note: "Core of the chapter's map-work component; also a favourite case-study table (identify the soil from a description)." },
    { name: "Soil erosion — types and conservation techniques", importance: "high", note: "Gully/sheet/wind erosion plus contour ploughing, terracing, strip cropping and shelter belts make a reliable 3-mark answer." },
    { name: "Resource planning — three stages", importance: "medium", note: "Asked as 'describe the steps in resource planning in India' — the sequence itself is often what is checked." },
    { name: "Sustainable development and the Rio Earth Summit", importance: "medium", note: "Short definition question, sometimes linked to Agenda 21." },
    { name: "Land use categories and the land-use pattern", importance: "low", note: "Occasional 1-mark recall question on land-use data." },
  ],
  written: [
    { q: "Define a 'resource'.", marks: 1, kind: "short", importance: "high",
      answer: "Everything available in our environment which can be used to satisfy our needs is a resource, provided it is <strong>technologically accessible, economically feasible and culturally acceptable</strong>." },
    { q: "What is meant by sustainable development?", marks: 1, kind: "short", importance: "medium",
      answer: "Development that takes place without damaging the environment, and which does not compromise the ability of future generations to meet their own needs." },
    { q: "Distinguish between renewable and non-renewable resources, giving one example of each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Renewable resources</strong> can be renewed or replenished within a short span of time through physical, chemical or mechanical processes, e.g. solar and wind energy, water.<br><strong>Non-renewable resources</strong> take a very long geological time to form, so once used up they cannot easily be replaced, e.g. coal, petroleum, and minerals." },
    { q: "Differentiate between 'stock' and 'reserves', with an example of each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Stock</strong> is material in the environment that could satisfy human needs but which we do not have the appropriate technology to access — e.g. hydrogen in water is a rich source of energy, but we cannot use it economically yet.<br><strong>Reserves</strong> are the part of stock that can be put to use with existing technical know-how, but has not been used so far — e.g. water in dams held back for generating electricity." },
    { q: "Why is resource planning essential in a country like India?", marks: 2, kind: "short", importance: "medium",
      answer: "India has great diversity in the availability of resources: some regions are rich in certain resources but deficient in others — some are self-sufficient while others have acute shortages. Resource planning balances this uneven distribution so every region and section of society can develop, which is why a <strong>national resource planning policy</strong> is needed." },
    { q: "Explain any three human activities responsible for land degradation in India.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Mining:</strong> mining sites are often abandoned after excavation, leaving deep scars and traces of overburden that degrade the land, e.g. in Jharkhand, Chhattisgarh, Madhya Pradesh and Odisha.</li><li><strong>Overgrazing:</strong> livestock strip the land of vegetation faster than it can regrow, a major cause of degradation in Gujarat, Rajasthan, Madhya Pradesh and Maharashtra.</li><li><strong>Over-irrigation:</strong> in Punjab, Haryana and western Uttar Pradesh, excess irrigation has caused waterlogging, increasing the salinity and alkalinity of the soil.</li></ul>" },
    { q: "Explain three types of soil erosion.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Gully erosion:</strong> running water cuts through clayey soils, forming deep channels called gullies. Land made unfit for cultivation this way is called bad land — in the Chambal basin such lands are called ravines.</li><li><strong>Sheet erosion:</strong> water flows as a sheet over large areas down a slope, washing away the top layer of soil almost uniformly.</li><li><strong>Wind erosion:</strong> wind blows loose soil off flat or sloping land, especially where vegetation cover is thin, as in dry regions.</li></ul>" },
    { q: "Describe the characteristics of black soil that make it ideal for growing cotton.", marks: 3, kind: "short", importance: "high",
      answer: "Black soil (also called regur) is formed from the weathering of lava flows and is found extensively over the Deccan trap. It is <strong>extremely moisture-retentive</strong>, so it does not need frequent irrigation. It is rich in <strong>calcium carbonate, magnesium, potash and lime</strong>, though poor in phosphoric content. When exposed to hot weather it develops deep cracks, allowing <strong>natural aeration</strong> of the soil. These qualities together — retained moisture, mineral richness, and self-aeration — suit the growth of cotton particularly well." },
    { q: "Explain the four bases on which resources are classified, giving one example under each.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>On the basis of origin:</strong> biotic resources are obtained from the biosphere — plants, animals, and human beings; abiotic resources are non-living, such as rocks and metals.</li><li><strong>On the basis of exhaustibility:</strong> renewable resources can be replenished, e.g. solar energy; non-renewable resources take a long geological time to form and cannot be replaced quickly, e.g. fossil fuels.</li><li><strong>On the basis of ownership:</strong> resources may be individual (private plots), community (public parks, grazing grounds), national (all resources within a country's political boundaries), or international (resources of the open ocean beyond 200 nautical miles).</li><li><strong>On the basis of status of development:</strong> potential resources are found in a region but not yet used, e.g. wind and solar potential in Rajasthan and Gujarat; developed resources are surveyed and their quality determined; stock refers to material we cannot yet use technologically, e.g. hydrogen in water; reserves are the part of stock that can be used with existing technology but has not been tapped, e.g. water in dams.</li></ul>" },
    { q: "Explain any five measures of soil conservation.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Contour ploughing:</strong> ploughing along the contour lines of a slope decelerates the flow of water downhill, reducing its erosive power.</li><li><strong>Terrace farming:</strong> steps cut on steep slopes restrict erosion — well developed in the western and central Himalayas.</li><li><strong>Strip cropping:</strong> large fields are divided into strips, with strips of grass left between crops to break the force of the wind.</li><li><strong>Shelter belts:</strong> rows of trees are planted to break the force of the wind; these have helped stabilise sand dunes in western India.</li><li><strong>Afforestation and controlled grazing:</strong> planting trees and regulating the number of livestock allowed to graze helps restore vegetation cover and prevent further degradation.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Resource planning is essential for the sustainable existence of all forms of life in India.",
      reason: "India has great diversity in the availability of resources — some regions are rich in certain resources but are deficient in some other, equally important, resources.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the uneven regional distribution described in R is exactly why a national resource-planning policy (A) is necessary." },
    { assertion: "Rajasthan and Gujarat are considered to have great potential for the development of wind and solar energy.",
      reason: "Both states receive very low annual rainfall and have a hot, dry climate.",
      answer: 1, importance: "medium",
      why: "Both statements are factually true, but the reason given (low rainfall and dry climate) does not, by itself, explain why these particular states have wind and solar potential — that depends on sunlight exposure and open terrain, not on rainfall being low." },
    { assertion: "Black soil, also known as regur, is considered ideal for growing cotton.",
      reason: "Black soil is formed from lava flows, retains moisture for a long time, and is rich in calcium carbonate, potash and lime.",
      answer: 0, importance: "high",
      why: "Both are true, and R gives exactly the properties of black soil that make it well suited to cotton cultivation." },
    { assertion: "In the Chambal basin, land made unfit for cultivation by deep channels is called ravines.",
      reason: "Ravines are formed by sheet erosion, in which water flows uniformly over a large area and washes away the top layer of soil.",
      answer: 2, importance: "medium",
      why: "A is true — such bad land is indeed called ravines in the Chambal basin. But R is false: ravines are the result of <em>gully</em> erosion, where running water cuts deep channels through clayey soil, not sheet erosion." },
  ],
  caseStudies: [
    { title: "Identify the soil from its description", importance: "high",
      source: "Study the following extract and answer the questions that follow:<br>Region A is found in the northern plains and in the deltas of the Mahanadi, Godavari, Krishna and Kaveri, deposited over centuries by rivers.<br>Region B covers the Deccan trap, including parts of Maharashtra and Malwa, formed from lava flows, and is capable of holding moisture for a long time.<br>Region C is found in parts of Karnataka, Kerala and Tamil Nadu, formed under conditions of high temperature and heavy rainfall through a process of intense leaching.",
      parts: [
        { q: "Identify soil Region A and name two crops for which it is ideal.", marks: 1, answer: "<strong>Alluvial soil</strong>; it is ideal for wheat, rice and sugarcane." },
        { q: "Identify soil Region B and name the crop it is best suited to.", marks: 1, answer: "<strong>Black soil (regur)</strong>; it is best suited to cotton." },
        { q: "Identify soil Region C. Why is it generally poor in humus?", marks: 2, answer: "<strong>Laterite soil</strong>. It forms under high temperature and heavy rainfall, and the process of intense leaching washes away soluble nutrients and humus, leaving the soil humus-poor." },
        { q: "Suggest one measure through which soil erosion can be checked in hilly regions such as the western and central Himalayas.", marks: 1, answer: "<strong>Terrace farming</strong> — cutting steps into the slope restricts the speed at which water flows downhill, reducing erosion." },
      ] },
    { title: "Land degradation and its causes", importance: "high",
      source: "Read the following passage: 'Human activities have contributed significantly to land degradation in India. In states such as Jharkhand, Chhattisgarh, Madhya Pradesh and Odisha, mining sites left abandoned after excavation, with overburden dumped nearby, have caused severe land degradation. In Gujarat, Rajasthan, Madhya Pradesh and Maharashtra, overgrazing has degraded large stretches of land. In Punjab, Haryana and western Uttar Pradesh, over-irrigation has caused waterlogging, increasing the salinity and alkalinity of the soil.'",
      parts: [
        { q: "Name any two states where mining has been a major cause of land degradation.", marks: 1, answer: "Any two of: Jharkhand, Chhattisgarh, Madhya Pradesh, Odisha." },
        { q: "Which human activity has caused land degradation in Gujarat and Rajasthan? Explain briefly.", marks: 2, answer: "<strong>Overgrazing.</strong> Livestock remove vegetation cover faster than it can regenerate, which exposes the soil to erosion by wind and water and reduces its fertility." },
        { q: "How has over-irrigation degraded land in Punjab and Haryana?", marks: 1, answer: "It has raised the water table, causing <strong>waterlogging</strong>, which in turn increases the salinity and alkalinity of the soil." },
        { q: "Suggest one measure that can help control land degradation caused by overgrazing.", marks: 1, answer: "Proper management of grazing — restricting the number of livestock per area (rotational grazing) along with afforestation to restore vegetation cover." },
      ] },
  ],
};
