import type { Chapter } from "@/lib/types";

export const ch06: Chapter = {
  slug: "resources-and-development",
  num: 1,
  title: "Resources and Development",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 18,
  blurb: "Nothing is a resource until people can use it. Everything after that — classification, planning, conservation — follows from that one idea.",
  bigIdea: "Resources are not simply lying around waiting. They become resources when technology, institutions and human need turn them into something usable — which is why the same rock is worthless in one century and vital in the next.",
  syllabus: [
    "Types of resources",
    "Development of resources and resource planning in India",
    "Land resources and land utilisation",
    "Land degradation and conservation measures",
    "Soil as a resource — classification and types",
    "Soil erosion and soil conservation",
    "Map work: major soil types",
  ],
  blocks: [
    { t: "h", text: "What counts as a resource" },
    { t: "formula", name: "Definition",
      expr: "Everything available in our environment which can be used to satisfy our needs is a resource, provided it is <strong>technologically accessible</strong>, <strong>economically feasible</strong> and <strong>culturally acceptable</strong>." },
    { t: "table", head: ["Basis", "Types"], rows: [
      ["<strong>Origin</strong>", "Biotic (from the biosphere — plants, animals, people) and Abiotic (non-living — rocks, metals)"],
      ["<strong>Exhaustibility</strong>", "Renewable (solar, wind, water, forests) and Non-renewable (minerals, fossil fuels)"],
      ["<strong>Ownership</strong>", "Individual, Community, National, International"],
      ["<strong>Status of development</strong>", "Potential, Developed, Stock, Reserves"],
    ] },
    { t: "note", kind: "trap", html: "<strong>Stock</strong> versus <strong>reserves</strong> is a common confusion. Stock is material that has the potential to satisfy needs but which we lack the technology to use — hydrogen in water is a rich source of energy, but we do not have the technology to use it easily. <strong>Reserves</strong> are the subset of stock that <em>can</em> be used with existing technical know-how but has not been started — like water in dams for generating electricity." },
    { t: "note", kind: "real", html: "Potential resources are found in a region but not yet used. Rajasthan and Gujarat have enormous potential for wind and solar energy, but only a part of it has been developed so far." },

    { t: "h", text: "Development, and its price" },
    { t: "p", html: "Indiscriminate use of resources has led to three major problems: depletion for the satisfaction of a few individuals; accumulation of resources in a few hands, dividing society into haves and have-nots; and indiscriminate exploitation leading to global ecological crises such as global warming, ozone layer depletion, environmental pollution and land degradation." },
    { t: "note", kind: "idea", html: "The answer proposed is <strong>sustainable development</strong> — development that takes place without damaging the environment, and without compromising the needs of future generations. The <strong>Rio de Janeiro Earth Summit of 1992</strong> agreed on Agenda 21, a global agreement for combating environmental damage, poverty and disease through global cooperation." },
    { t: "note", kind: "exam", html: "Resource planning in India has three stages, and questions ask for all three in order: <strong>identification and inventory</strong> of resources across regions; <strong>evolving a planning structure</strong> with appropriate technology, skill and institutional setup; and <strong>matching the resource development plans with overall national development plans</strong>." },

    { t: "h", text: "Land use" },
    { t: "sim", id: "land-use" },
    { t: "p", html: "India has a land area of about <strong>3.28 million square kilometres</strong>, but land-use data is available for only about 93% of it. Land under permanent pasture has decreased. Most of the reported area classified as fallow other than current fallow is either of poor quality or the cost of cultivation is very high." },
    { t: "note", kind: "why", title: "Why land degradation matters", html: "Human activities such as deforestation, overgrazing, mining and quarrying have contributed significantly to land degradation. Mining sites are abandoned after excavation, leaving deep scars and traces of overburden. In Gujarat, Rajasthan, Madhya Pradesh and Maharashtra, overgrazing is one of the main reasons. In Punjab, Haryana and western Uttar Pradesh, over-irrigation causes <strong>waterlogging</strong> and increases salinity and alkalinity." },
    { t: "list", items: [
      "<strong>Afforestation and proper management of grazing</strong> can help to some extent.",
      "Planting of <strong>shelter belts</strong> of plants, control of overgrazing, stabilisation of sand dunes by growing thorny bushes.",
      "Proper management of wastelands, control of mining activities, and proper discharge and disposal of industrial effluents and wastes after treatment.",
    ] },

    { t: "h", text: "Soils of India" },
    { t: "table", head: ["Soil", "Where", "Character"], rows: [
      ["<strong>Alluvial</strong>", "The entire northern plains, and eastern coastal plains in the deltas of the Mahanadi, Godavari, Krishna and Kaveri", "Deposited by the Indus, Ganga and Brahmaputra. Very fertile, rich in potash, phosphoric acid and lime. Ideal for sugarcane, paddy and wheat. <em>Khadar</em> is new alluvium and more fertile; <em>bangar</em> is old alluvium with more kanker nodules"],
      ["<strong>Black (regur)</strong>", "The Deccan trap — Maharashtra, Saurashtra, Malwa, Madhya Pradesh, Chhattisgarh, extending along the Godavari and Krishna", "Made of lava flows. Ideal for growing <strong>cotton</strong>. Holds moisture extremely well, is rich in calcium carbonate, magnesium, potash and lime, but poor in phosphoric contents. Develops deep cracks in hot weather, which helps aeration"],
      ["<strong>Red and yellow</strong>", "Eastern and southern Deccan plateau, parts of Odisha, Chhattisgarh, southern middle Ganga plain, Western Ghats piedmont", "Develops on crystalline igneous rocks in areas of low rainfall. Red because of the diffusion of iron; yellow when it occurs in a hydrated form"],
      ["<strong>Laterite</strong>", "Karnataka, Kerala, Tamil Nadu, Madhya Pradesh, hilly areas of Odisha and Assam", "Develops under high temperature and heavy rainfall, as a result of intense leaching. Humus-poor. After adopting soil conservation techniques it is suitable for tea, coffee and cashew nut"],
      ["<strong>Arid</strong>", "Western Rajasthan", "Ranges from red to brown, generally sandy and saline. Lacks humus and moisture because evaporation is faster. Lower horizons are occupied by kanker, restricting water infiltration"],
      ["<strong>Forest</strong>", "Hilly and mountainous areas with sufficient rain forests", "Loamy and silty in valley sides, coarse-grained in upper slopes. In snow-covered areas they are acidic with low humus content"],
    ] },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "memory", html: "Match soil to crop and you have half the marks: <strong>alluvial → wheat, paddy, sugarcane; black → cotton; laterite → tea, coffee, cashew</strong>." },

    { t: "h", text: "Soil erosion and conservation" },
    { t: "list", items: [
      "<strong>Gully erosion</strong> — running water cuts through clayey soils making deep channels. Land unfit for cultivation is called <strong>bad land</strong>; in the Chambal basin such lands are called <strong>ravines</strong>.",
      "<strong>Sheet erosion</strong> — water flows as a sheet over large areas down a slope and washes away the topsoil.",
      "<strong>Wind erosion</strong> — wind blows loose soil off flat or sloping land.",
      "Defective methods of farming, especially <strong>ploughing up and down the slope</strong>, form channels for the quick flow of water.",
    ] },
    { t: "table", head: ["Conservation method", "How it works"], rows: [
      ["<strong>Contour ploughing</strong>", "Ploughing along the contour lines can decelerate the flow of water down the slopes"],
      ["<strong>Terrace farming</strong>", "Steps cut on slopes restrict erosion. Western and central Himalayas have well-developed terrace farming"],
      ["<strong>Strip cropping</strong>", "Large fields divided into strips, with strips of grass left in between to break the force of the wind"],
      ["<strong>Shelter belts</strong>", "Rows of trees planted to break wind force. They have contributed significantly to the stabilisation of sand dunes and to stabilising the desert in western India"],
    ] },
    { t: "note", kind: "exam", title: "Map work", html: "For this chapter the board asks you to identify <strong>major soil types</strong> on an outline map of India. Learn which soil belongs to which broad region — the table above is arranged for exactly that." },
  ],
  examFocus: [
    "The definition of a resource, with all three conditions.",
    "The four bases of classification, with examples.",
    "Stock versus reserves — hydrogen in water versus water in dams.",
    "The three stages of resource planning, in order.",
    "Sustainable development and the Rio Earth Summit of 1992.",
    "Causes of land degradation, region by region, and four conservation measures.",
    "The six soil types with location, character and matching crop.",
    "Types of soil erosion and four conservation methods.",
  ],
  flashcards: [
    { q: "Define a resource.", a: "Everything available in our environment which can be used to satisfy our needs, provided it is technologically accessible, economically feasible and culturally acceptable." },
    { q: "Distinguish between stock and reserves.", a: "Stock is material that could satisfy needs but which we lack the technology to use — hydrogen in water. Reserves are the part of stock that can be used with existing technology but has not been started — water in dams for electricity." },
    { q: "What are potential resources? Give an example.", a: "Resources found in a region that have not yet been used. Rajasthan and Gujarat have enormous potential for wind and solar energy, only partly developed so far." },
    { q: "What is sustainable development?", a: "Development that takes place without damaging the environment, and which does not compromise the needs of future generations." },
    { q: "What was agreed at the Rio Earth Summit of 1992?", a: "Agenda 21 — a global agreement to combat environmental damage, poverty and disease through global cooperation, with each local government drawing up its own local Agenda 21." },
    { q: "Name the three stages of resource planning in India.", a: "Identification and inventory of resources across regions; evolving a planning structure with appropriate technology, skill and institutional setup; and matching resource development plans with overall national development plans." },
    { q: "What is the difference between khadar and bangar?", a: "Khadar is new alluvium, found in the lower areas of the floodplain, finer and more fertile. Bangar is older alluvium on higher ground with more kanker nodules." },
    { q: "Why is black soil ideal for cotton?", a: "It is made from lava flows, holds moisture extremely well, and is rich in calcium carbonate, magnesium, potash and lime. It also develops deep cracks in hot weather, which helps aeration." },
    { q: "How does laterite soil form and what is it good for?", a: "Under high temperature and heavy rainfall, as a result of intense leaching which removes humus. After soil conservation techniques are applied it is suitable for tea, coffee and cashew nut." },
    { q: "What are ravines?", a: "Deep channels cut by running water through clayey soils, making the land unfit for cultivation. Such bad land in the Chambal basin is called ravines." },
    { q: "Name four methods of soil conservation.", a: "Contour ploughing along the contour lines; terrace farming on steep slopes; strip cropping with grass strips between; and shelter belts of trees to break wind force." },
    { q: "Which activities cause land degradation in which regions?", a: "Mining in Jharkhand, Chhattisgarh, Madhya Pradesh and Odisha; overgrazing in Gujarat, Rajasthan, Madhya Pradesh and Maharashtra; and over-irrigation causing waterlogging and salinity in Punjab, Haryana and western Uttar Pradesh." },
  ],
  quiz: [
    { q: "Hydrogen in water is best described as:", options: ["A reserve", "Stock", "A developed resource", "A biotic resource"], answer: 1, why: "It could satisfy needs but we lack the technology to use it easily, which is the definition of stock rather than reserve." },
    { q: "Which soil is most suitable for growing cotton?", options: ["Alluvial", "Black", "Laterite", "Arid"], answer: 1, why: "Black soil, also called regur, is made from lava flows, retains moisture well, and is ideal for cotton." },
    { q: "Laterite soil forms as a result of:", options: ["Volcanic activity", "Intense leaching under high temperature and heavy rainfall", "Wind deposition", "River deposition"], answer: 1, why: "Heavy rain leaches away the lime and silica, leaving a humus-poor soil." },
    { q: "Ravines in the Chambal basin are an example of:", options: ["Sheet erosion", "Wind erosion", "Gully erosion", "Waterlogging"], answer: 2, why: "Running water cuts deep channels through clayey soils, producing bad land known locally as ravines." },
    { q: "Ploughing along contour lines to slow water flow is called:", options: ["Strip cropping", "Terrace farming", "Contour ploughing", "Shelter belting"], answer: 2, why: "Contour ploughing decelerates the flow of water down the slope and reduces erosion." },
    { q: "The Earth Summit of 1992 was held at:", options: ["Stockholm", "Rio de Janeiro", "Kyoto", "Paris"], answer: 1, why: "The United Nations Conference on Environment and Development was held at Rio de Janeiro, Brazil, and agreed Agenda 21." },
    { q: "Over-irrigation in Punjab and Haryana has mainly caused:", options: ["Deforestation", "Waterlogging and increased salinity", "Gully erosion", "Wind erosion"], answer: 1, why: "Excess water raises the water table, causing waterlogging and increasing the salinity and alkalinity of the soil." },
    { q: "Alluvial soil is NOT typically found in:", options: ["The northern plains", "The Godavari delta", "Western Rajasthan", "The Kaveri delta"], answer: 2, why: "Western Rajasthan has arid soil — sandy, saline and low in humus. Alluvial soil is river-deposited." },
    { q: "Resources classified on the basis of ownership include:", options: ["Biotic and abiotic", "Renewable and non-renewable", "Individual, community, national and international", "Potential and developed"], answer: 2, why: "Ownership divides resources into individual, community, national and international categories." },
    { q: "India's total land area is approximately:", options: ["1.28 million sq km", "3.28 million sq km", "5.28 million sq km", "8.28 million sq km"], answer: 1, why: "India has a land area of about 3.28 million square kilometres, though land-use data is available for only about 93% of it." },
  ],
};
