import type { Chapter } from "@/lib/types";

export const ch07: Chapter = {
  slug: "forest-and-wildlife-resources",
  num: 2,
  title: "Forest and Wildlife Resources",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks",
  minutes: 15,
  blurb: "India has 8% of the world's recorded species. It is also losing them faster than almost anywhere — and the reasons are mostly economic, not natural.",
  bigIdea: "Biodiversity is not decoration. Human life depends on an intricate web of species, and the pressures destroying that web are the same ones we call development.",
  syllabus: [
    "Flora and fauna in India",
    "Vanishing forests and the causes of depletion",
    "Asiatic cheetah — where did they go?",
    "Conservation of forest and wildlife in India",
    "Types and distribution of forests and wildlife resources",
    "Community and conservation",
  ],
  blocks: [
    { t: "h", text: "How much there is, and how fast it is going" },
    { t: "p", html: "India is one of the world's richest countries in terms of its biological diversity. It has nearly <strong>8% of the total number of species in the world</strong>, estimated to be 1.6 million. But a large number are now under threat." },
    { t: "sim", id: "wildlife-status" },
    { t: "note", kind: "real", title: "The Asiatic cheetah", html: "The world's fastest land mammal can achieve 112 km/h. It was <strong>declared extinct in India in 1952</strong>. The reason was not natural: they were hunted for sport and for capture, and Indian rulers kept them for coursing. Once a species is gone, no amount of conservation brings it back — which is the point of listing the categories at all." },

    { t: "h", text: "Why forests and species are disappearing" },
    { t: "list", items: [
      "<strong>Colonial forestry and commercial agriculture.</strong> Between 1951 and 1980, over 26,200 sq km of forest was converted into agricultural land. Substantial parts of tribal belts were cleared for commercial crops.",
      "<strong>Shifting cultivation</strong> — slash and burn agriculture — has also caused depletion in parts of the north-east and central India.",
      "<strong>Large development projects.</strong> Since 1951, over 5,000 sq km of forest was cleared for river valley projects — the Narmada Sagar Project in Madhya Pradesh alone would flood about 40,000 hectares of forest.",
      "<strong>Mining.</strong> The Buxa Tiger Reserve in West Bengal is seriously threatened by dolomite mining, which has blocked migration routes of several species including the great Indian elephant.",
      "<strong>Grazing and fuelwood collection</strong> — though these are more often subsistence activities than the main cause, and the NCERT is careful about that distinction.",
      "<strong>Unequal access and consumption.</strong> The richest fifth of Indian society consumes far more than the poorest, and it is that consumption, not poverty, that drives most environmental damage.",
    ] },
    { t: "note", kind: "why", title: "Who pays the price", html: "Deforestation hits women hardest. In poor rural households, women bear the responsibility of collecting fuel, fodder, water and other basic subsistence needs. As these resources become scarce, women must walk further, work longer, and often neglect home and children — and girls are pulled out of school to help." },

    { t: "h", text: "Conservation, and the argument about it" },
    { t: "table", head: ["Category", "Meaning", "Share"], rows: [
      ["<strong>Reserved forests</strong>", "The most valuable as far as conservation is concerned", "More than half of the total forest land"],
      ["<strong>Protected forests</strong>", "Protected from further depletion", "Almost one-third of the total forest area"],
      ["<strong>Unclassed forests</strong>", "Other forests and wastelands belonging to both government and private individuals and communities", "The remainder"],
    ] },
    { t: "note", kind: "idea", html: "<strong>Project Tiger</strong> was launched in 1973, one of the best-publicised wildlife campaigns in the world. Tiger populations had fallen from an estimated 55,000 at the turn of the twentieth century to 1,827 in 1973. Corbett National Park in Uttarakhand, Sunderbans in West Bengal, Bandhavgarh in Madhya Pradesh, Sariska in Rajasthan, Manas in Assam and Periyar in Kerala are among the tiger reserves." },
    { t: "note", kind: "trap", html: "A conservation programme that <strong>excludes local people</strong> often fails. In Sariska Tiger Reserve, villagers have protested against the government's exclusion from the reserve. The chapter's argument is that conservation works better <em>with</em> communities than against them." },

    { t: "h", text: "Communities doing it themselves" },
    { t: "list", items: [
      "In Sariska, villagers have fought against mining by citing the <strong>Wildlife Protection Act</strong>.",
      "In Alwar district of Rajasthan, five villages have declared 1,200 hectares of forest as the <strong>Bhairodev Dakav 'Sonchuri'</strong>, with their own set of rules and regulations which do not allow hunting and protect the wildlife against outside encroachments.",
      "The <strong>Chipko movement</strong> in the Himalayas successfully resisted deforestation and showed that community afforestation with indigenous species can be enormously successful.",
      "The <strong>Beej Bachao Andolan</strong> in Tehri and organisations like Navdanya have shown that adequate levels of diversified crop production without chemical fertilisers are possible and economically viable.",
      "<strong>Joint Forest Management (JFM)</strong> involves local communities in the management and restoration of degraded forests. Odisha passed the first resolution for JFM in <strong>1988</strong>. Village institutions undertake protection activities and in return get benefits like non-timber forest produce and a share in timber harvested.",
    ] },
    { t: "note", kind: "real", html: "Nature worship is an age-old tribal belief. Many forests have been preserved in their pristine form as <strong>sacred groves</strong> — the forests of God and Goddesses. The Mundas and Santhals of Chotanagpur worship the mahua and kadamba trees; the Odishans and Bihar tribes worship the tamarind and mango during weddings. This is conservation without any conservation programme." },
    { t: "note", kind: "exam", html: "The chapter's conclusion is worth writing out: conservation strategies must be built around, not against, the people who live in and depend on forests. Community participation is not an add-on — it is what makes the strategy work." },
  ],
  examFocus: [
    "India's share of world species — 8% of an estimated 1.6 million.",
    "The species categories with one Indian example each.",
    "The Asiatic cheetah, declared extinct in India in 1952, and why.",
    "The causes of forest depletion, with figures where you know them.",
    "Why deforestation affects women disproportionately.",
    "Reserved, protected and unclassed forests with their shares.",
    "Project Tiger, 1973, and the reserves.",
    "Community conservation: Sariska, Bhairodev Dakav, Chipko, Beej Bachao Andolan, JFM in Odisha 1988, sacred groves.",
  ],
  flashcards: [
    { q: "What share of the world's species does India have?", a: "Nearly 8% of the total number of species in the world, which is estimated at 1.6 million." },
    { q: "When was the Asiatic cheetah declared extinct in India, and why did it disappear?", a: "1952. It was hunted for sport and captured for coursing by Indian rulers — the causes were human, not natural." },
    { q: "How much forest was converted to agricultural land between 1951 and 1980?", a: "Over 26,200 square kilometres. Substantial parts of tribal belts were also cleared for commercial crops." },
    { q: "How have river valley projects affected forests?", a: "Since 1951, over 5,000 sq km of forest was cleared for river valley projects. The Narmada Sagar Project in Madhya Pradesh alone would inundate about 40,000 hectares of forest." },
    { q: "Which mining activity threatens the Buxa Tiger Reserve?", a: "Dolomite mining, which has blocked the migration routes of several species including the great Indian elephant." },
    { q: "Why does deforestation affect women more than men?", a: "In poor rural households women collect fuel, fodder and water. As these become scarce they must walk further and work longer, damaging their health and often forcing girls out of school to help." },
    { q: "Name the three categories of forest and their approximate shares.", a: "Reserved forests — more than half the total forest land, and the most valuable for conservation. Protected forests — almost one-third. Unclassed forests — other forests and wastelands, government and privately owned." },
    { q: "What was Project Tiger and when was it launched?", a: "A wildlife conservation campaign launched in 1973 after tiger numbers fell from an estimated 55,000 at the start of the twentieth century to 1,827 in 1973." },
    { q: "What is the Bhairodev Dakav 'Sonchuri'?", a: "1,200 hectares of forest in Alwar district, Rajasthan, declared protected by five villages with their own rules banning hunting and guarding against outside encroachment." },
    { q: "What did the Chipko movement achieve?", a: "It successfully resisted deforestation in the Himalayas and demonstrated that community afforestation with indigenous species can be extremely successful." },
    { q: "What is Joint Forest Management?", a: "A programme involving local communities in the management and restoration of degraded forests. Odisha passed the first JFM resolution in 1988. Communities protect the forest and receive non-timber forest produce and a share of timber in return." },
    { q: "What are sacred groves?", a: "Forests preserved in pristine form because of religious belief — the forests of Gods and Goddesses. Certain trees like mahua, kadamba, tamarind and mango are considered sacred and are not cut." },
  ],
  quiz: [
    { q: "India has approximately what share of the world's species?", options: ["2%", "8%", "16%", "25%"], answer: 1, why: "India holds nearly 8% of the estimated 1.6 million species in the world." },
    { q: "The Asiatic cheetah was declared extinct in India in:", options: ["1947", "1952", "1973", "1988"], answer: 1, why: "It was declared extinct in 1952, having been hunted for sport and captured for coursing." },
    { q: "Project Tiger was launched in:", options: ["1952", "1972", "1973", "1988"], answer: 2, why: "It was launched in 1973, when the tiger population had fallen to 1,827." },
    { q: "Reserved forests constitute:", options: ["Less than a quarter of forest land", "More than half of the total forest land", "Exactly one-third", "All privately owned forests"], answer: 1, why: "More than half of the total forest land is reserved, and these are regarded as the most valuable for conservation." },
    { q: "The first state to pass a resolution for Joint Forest Management was:", options: ["Kerala", "Odisha", "Uttarakhand", "Rajasthan"], answer: 1, why: "Odisha passed the first JFM resolution in 1988." },
    { q: "Buxa Tiger Reserve is threatened by:", options: ["Shifting cultivation", "Dolomite mining", "River valley projects", "Urban expansion"], answer: 1, why: "Dolomite mining has blocked migration routes of several species including the great Indian elephant." },
    { q: "The Asiatic elephant and Gangetic dolphin are classified as:", options: ["Endangered", "Vulnerable", "Rare", "Endemic"], answer: 1, why: "Vulnerable species are those whose population has declined to levels from which they are likely to become endangered if the negative factors continue." },
    { q: "Andaman teal and Nicobar pigeon are examples of ______ species.", options: ["Extinct", "Vulnerable", "Endemic", "Normal"], answer: 2, why: "Endemic species are found only in particular areas, usually isolated by natural or geographical barriers." },
    { q: "Sacred groves are best described as:", options: ["Government-protected reserves", "Forests preserved through religious belief", "Commercial plantations", "Abandoned mining land"], answer: 1, why: "Nature worship led communities to preserve certain forests in pristine form as the forests of Gods and Goddesses." },
    { q: "The Beej Bachao Andolan in Tehri showed that:", options: ["Chemical fertilisers are essential", "Diversified crop production without chemical fertilisers is viable", "Forests must be closed to people", "Mining can be sustainable"], answer: 1, why: "It demonstrated that adequate levels of diversified crop production without chemical fertilisers are both possible and economically viable." },
  ],
};
