import type { Chapter } from "@/lib/types";

export const ch08: Chapter = {
  slug: "water-resources",
  num: 3,
  title: "Water Resources",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 16,
  blurb: "A country with plenty of rain and a serious water shortage. The gap between those two facts is what this chapter explains.",
  bigIdea: "Water scarcity is rarely about how much rain falls. It is about how the water is stored, who gets it, and what it is used for.",
  syllabus: [
    "Water scarcity and the need for water conservation and management",
    "Multi-purpose river projects and integrated water resources management",
    "Rainwater harvesting",
    "Map work: dams and projects",
  ],
  blocks: [
    { t: "h", text: "Why there is scarcity" },
    { t: "p", html: "Three-quarters of the earth's surface is covered with water, but freshwater is only about <strong>2.5% of the total volume</strong>, and most of that is in ice sheets and glaciers. India receives nearly 4% of the global precipitation and ranks 133rd in the world for water availability per person per year." },
    { t: "list", items: [
      "<strong>Over-exploitation and unequal access.</strong> In housing colonies and industrial areas, people have their own groundwater pumping devices — those who can afford it draw as much as they want.",
      "<strong>Growing population.</strong> More water is needed for domestic use and to produce more food, so irrigation demand rises.",
      "<strong>Industrialisation.</strong> Industries need water and energy, much of which is hydroelectric. Multiplying industries have exerted pressure on both.",
      "<strong>Pollution.</strong> Water may be abundant but unfit to use — polluted by domestic and industrial wastes, chemicals, pesticides and fertilisers.",
    ] },
    { t: "note", kind: "trap", html: "The chapter's argument is that a region can have <strong>ample water and still face scarcity</strong>, because the water is polluted or because access is unequal. Writing 'less rainfall' as the only cause of water scarcity will not earn full marks." },

    { t: "h", text: "Multi-purpose river projects" },
    { t: "sim", id: "dam-tradeoffs" },
    { t: "p", html: "A <strong>dam</strong> is a barrier across flowing water that obstructs, directs or retards the flow, often creating a reservoir. Most dams built today are <strong>multi-purpose</strong> — the integrated water resources management approach means one project serves irrigation, electricity, water supply, flood control, recreation, inland navigation and fish breeding together." },
    { t: "note", kind: "real", html: "Jawaharlal Nehru proclaimed dams as the <strong>'temples of modern India'</strong> — the reason being that they would integrate development of agriculture and the village economy with rapid industrialisation and urban growth. Half a century later, the argument had turned, and a good answer gives both halves." },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "exam", title: "Map work", html: "The board asks you to locate these dams and projects: <strong>Salal, Bhakra Nangal, Tehri, Rana Pratap Sagar, Sardar Sarovar, Hirakud, Nagarjuna Sagar and Tungabhadra</strong>. Learn the river with each one — the locator above lists them all with their rivers." },
    { t: "table", head: ["Project", "River", "State"], rows: [
      ["Salal", "Chenab", "Jammu & Kashmir"],
      ["Bhakra Nangal", "Satluj-Beas", "Punjab–Himachal Pradesh"],
      ["Tehri", "Bhagirathi", "Uttarakhand"],
      ["Rana Pratap Sagar", "Chambal", "Rajasthan"],
      ["Sardar Sarovar", "Narmada", "Gujarat"],
      ["Hirakud", "Mahanadi", "Odisha"],
      ["Nagarjuna Sagar", "Krishna", "Telangana–Andhra Pradesh"],
      ["Tungabhadra", "Tungabhadra", "Karnataka"],
    ] },

    { t: "h", text: "Rainwater harvesting" },
    { t: "p", html: "In ancient India people had extraordinary hydraulic structures. In the first century BC, Sringaverapura near Allahabad had sophisticated water harvesting systems channelling the flood water of the Ganga. Chandragupta Maurya's time saw dams, lakes and irrigation systems built extensively. Bhopal Lake, built in the eleventh century, was one of the largest artificial lakes of its time." },
    { t: "table", head: ["Region", "Structure", "How it works"], rows: [
      ["Hill and mountainous regions", "<strong>Guls</strong> and <strong>kuls</strong>", "Diversion channels built to divert stream water into agricultural fields — Western Himalayas"],
      ["Rajasthan", "<strong>Tankas</strong>", "Underground tanks in courtyards storing rooftop rainwater. Part of the well-developed rooftop rainwater harvesting tradition"],
      ["West Bengal", "Inundation channels", "Used to irrigate the fields with flood water in the flood plains"],
      ["Semi-arid and arid regions", "<strong>Khadins</strong> in Jaisalmer and <strong>Johads</strong> elsewhere in Rajasthan", "Agricultural fields converted into rain-fed storage structures, allowing water to stand and moisten the soil"],
      ["Meghalaya", "Bamboo drip irrigation", "A 200-year-old system of tapping stream and spring water using bamboo pipes"],
    ] },
    { t: "note", kind: "real", title: "Two places worth naming", html: "<strong>Gendathur</strong>, a remote backward village in Mysuru, Karnataka: nearly 200 households have installed rooftop rainwater harvesting, and the village has earned the rare distinction of being rich in rainwater.<br><br>In the semi-arid regions of Rajasthan, <strong>tankas</strong> were built inside the main house or courtyard, connected by pipes to sloping roofs. The first spell of rain was usually not collected, as it would clean the roofs and pipes; the rain from the second spell onwards was stored. This water lasted till the next rainfall — and in extremely hot and dry Rajasthan, the tanka also kept the room cool." },
    { t: "note", kind: "idea", html: "The argument the chapter builds to: as the ecological and social costs of large dams have become clearer, <strong>water harvesting</strong> is being revived as a socio-economically and environmentally viable alternative. Tamil Nadu is the first and only state in India that has made <strong>rooftop rainwater harvesting structures compulsory</strong> for all houses across the state." },
  ],
  examFocus: [
    "Four distinct causes of water scarcity — and that pollution and unequal access matter as much as rainfall.",
    "What multi-purpose means, and Nehru's 'temples of modern India'.",
    "Advantages and disadvantages of multi-purpose projects, in balance.",
    "The Narmada Bachao Andolan.",
    "The eight dams with their rivers and states — this is map work.",
    "Traditional harvesting structures by region: guls, tankas, khadins, johads, bamboo drip irrigation.",
    "Gendathur, and Tamil Nadu's compulsory rooftop harvesting.",
  ],
  flashcards: [
    { q: "What proportion of the earth's water is freshwater?", a: "About 2.5% of the total volume, and most of that is locked in ice sheets and glaciers. India receives nearly 4% of global precipitation." },
    { q: "Give four causes of water scarcity in India.", a: "Over-exploitation and unequal access, particularly through private groundwater pumping; growing population raising domestic and irrigation demand; industrialisation demanding water and hydroelectricity; and pollution making available water unfit for use." },
    { q: "Why can a region with plenty of water still face scarcity?", a: "Because the water may be polluted by domestic and industrial waste, chemicals, pesticides and fertilisers, or because access to it is unequal — those who can afford pumps take as much as they want." },
    { q: "What is a multi-purpose river project?", a: "A project where one dam serves several purposes together — irrigation, electricity generation, water supply, flood control, recreation, inland navigation and fish breeding." },
    { q: "Who called dams the 'temples of modern India' and why?", a: "Jawaharlal Nehru, because they would integrate development of agriculture and the village economy with rapid industrialisation and the growth of the urban economy." },
    { q: "Give three arguments against large dams.", a: "They displace local people who lose land and livelihood; they fragment rivers and harm aquatic life through sedimentation; and they have caused inter-state and intra-state conflicts over water sharing." },
    { q: "What was the Narmada Bachao Andolan?", a: "A movement that mobilised tribal people, farmers, environmentalists and human rights activists against the Sardar Sarovar dam on the Narmada, over displacement and environmental damage." },
    { q: "What are guls and kuls?", a: "Diversion channels in the Western Himalayas that carry stream water to agricultural fields." },
    { q: "What is a tanka?", a: "An underground tank in Rajasthan, built in the main house or courtyard and connected by pipes to sloping rooftops, used to store rooftop rainwater for drinking. The first spell of rain is not collected, as it cleans the roof and pipes." },
    { q: "What are khadins and johads?", a: "Rain-fed storage structures in the semi-arid regions of Rajasthan — agricultural fields converted so that water stands and moistens the soil. Khadins are found in Jaisalmer." },
    { q: "Which village in Karnataka is known for rooftop rainwater harvesting?", a: "Gendathur, a remote backward village in Mysuru, where nearly 200 households have installed rooftop harvesting and the village has become rich in rainwater." },
    { q: "Which state has made rooftop rainwater harvesting compulsory?", a: "Tamil Nadu — the first and only state in India to make rooftop rainwater harvesting structures compulsory for all houses across the state." },
  ],
  quiz: [
    { q: "Freshwater accounts for about what share of the earth's total water?", options: ["25%", "10%", "2.5%", "50%"], answer: 2, why: "Only about 2.5% is freshwater, and most of that is in ice sheets and glaciers." },
    { q: "Bhakra Nangal is built on the:", options: ["Chenab", "Satluj-Beas", "Mahanadi", "Narmada"], answer: 1, why: "Bhakra Nangal on the Satluj-Beas is used for water storage and electricity generation." },
    { q: "The Hirakud project is on the:", options: ["Krishna", "Chambal", "Mahanadi", "Bhagirathi"], answer: 2, why: "Hirakud, on the Mahanadi in Odisha, integrates conservation of water with flood control." },
    { q: "The Sardar Sarovar dam is on the river:", options: ["Tapi", "Narmada", "Godavari", "Chenab"], answer: 1, why: "It is on the Narmada in Gujarat, and was the focus of the Narmada Bachao Andolan." },
    { q: "Tankas are found in:", options: ["Meghalaya", "Rajasthan", "West Bengal", "Kerala"], answer: 1, why: "Tankas are underground tanks in Rajasthan for storing rooftop rainwater for drinking." },
    { q: "Bamboo drip irrigation is a 200-year-old system found in:", options: ["Rajasthan", "Meghalaya", "Karnataka", "Punjab"], answer: 1, why: "In Meghalaya, stream and spring water is tapped using bamboo pipes." },
    { q: "Guls and kuls are diversion channels found in the:", options: ["Deccan plateau", "Western Himalayas", "Coastal plains", "Thar desert"], answer: 1, why: "They divert stream water into agricultural fields in hill and mountainous regions." },
    { q: "Which state made rooftop rainwater harvesting compulsory for all houses?", options: ["Kerala", "Rajasthan", "Tamil Nadu", "Karnataka"], answer: 2, why: "Tamil Nadu is the first and only state to make it compulsory statewide." },
    { q: "In Rajasthan, the first spell of rain is usually not collected in a tanka because:", options: ["It is too little", "It cleans the roof and pipes", "It is too acidic", "It evaporates"], answer: 1, why: "The first spell washes the roofs and pipes clean; storage begins from the second spell onwards." },
    { q: "The Narmada Bachao Andolan was primarily concerned with:", options: ["Water pollution", "Displacement and environmental damage from a large dam", "Inter-state river disputes only", "Groundwater depletion"], answer: 1, why: "It mobilised tribal people, farmers and environmentalists against the Sardar Sarovar dam over displacement and ecological cost." },
  ],
};
