import type { Chapter } from "@/lib/types";

export const ch08: Chapter = {
  slug: "water-resources",
  num: 3,
  title: "Water Resources",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 16,
  blurb: "A country with plenty of rain and a serious water shortage. The gap between those two facts is what this chapter explains.",
  bigIdea: "Water scarcity is rarely about how much rain falls. It is about how the water is stored, who gets it, and what it is used for.",
  syllabus: [
    "Water scarcity and the need for water conservation and management",
    "Multi-purpose river projects and integrated water resources management",
    "Rainwater harvesting",
    "Map work: dams and projects",
  ],
  blocks: [
    { t: "h", text: "Why there is scarcity" },
    { t: "p", html: "Three-quarters of the earth's surface is covered with water, but freshwater is only about <strong>2.5% of the total volume</strong>, and most of that is in ice sheets and glaciers. India receives nearly 4% of the global precipitation and ranks 133rd in the world for water availability per person per year." },
    { t: "list", items: [
      "<strong>Over-exploitation and unequal access.</strong> In housing colonies and industrial areas, people have their own groundwater pumping devices — those who can afford it draw as much as they want.",
      "<strong>Growing population.</strong> More water is needed for domestic use and to produce more food, so irrigation demand rises.",
      "<strong>Industrialisation.</strong> Industries need water and energy, much of which is hydroelectric. Multiplying industries have exerted pressure on both.",
      "<strong>Pollution.</strong> Water may be abundant but unfit to use — polluted by domestic and industrial wastes, chemicals, pesticides and fertilisers.",
    ] },
    { t: "note", kind: "trap", html: "The chapter's argument is that a region can have <strong>ample water and still face scarcity</strong>, because the water is polluted or because access is unequal. Writing 'less rainfall' as the only cause of water scarcity will not earn full marks." },

    { t: "h", text: "Multi-purpose river projects" },
    { t: "sim", id: "dam-tradeoffs" },
    { t: "p", html: "A <strong>dam</strong> is a barrier across flowing water that obstructs, directs or retards the flow, often creating a reservoir. Most dams built today are <strong>multi-purpose</strong> — the integrated water resources management approach means one project serves irrigation, electricity, water supply, flood control, recreation, inland navigation and fish breeding together." },
    { t: "note", kind: "real", html: "Jawaharlal Nehru proclaimed dams as the <strong>'temples of modern India'</strong> — the reason being that they would integrate development of agriculture and the village economy with rapid industrialisation and urban growth. Half a century later, the argument had turned, and a good answer gives both halves." },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "exam", title: "Map work", html: "The board asks you to locate these dams and projects: <strong>Salal, Bhakra Nangal, Tehri, Rana Pratap Sagar, Sardar Sarovar, Hirakud, Nagarjuna Sagar and Tungabhadra</strong>. Learn the river with each one — the locator above lists them all with their rivers." },
    { t: "table", head: ["Project", "River", "State"], rows: [
      ["Salal", "Chenab", "Jammu & Kashmir"],
      ["Bhakra Nangal", "Satluj-Beas", "Punjab–Himachal Pradesh"],
      ["Tehri", "Bhagirathi", "Uttarakhand"],
      ["Rana Pratap Sagar", "Chambal", "Rajasthan"],
      ["Sardar Sarovar", "Narmada", "Gujarat"],
      ["Hirakud", "Mahanadi", "Odisha"],
      ["Nagarjuna Sagar", "Krishna", "Telangana–Andhra Pradesh"],
      ["Tungabhadra", "Tungabhadra", "Karnataka"],
    ] },

    { t: "h", text: "Rainwater harvesting" },
    { t: "p", html: "In ancient India people had extraordinary hydraulic structures. In the first century BC, Sringaverapura near Allahabad had sophisticated water harvesting systems channelling the flood water of the Ganga. Chandragupta Maurya's time saw dams, lakes and irrigation systems built extensively. Bhopal Lake, built in the eleventh century, was one of the largest artificial lakes of its time." },
    { t: "table", head: ["Region", "Structure", "How it works"], rows: [
      ["Hill and mountainous regions", "<strong>Guls</strong> and <strong>kuls</strong>", "Diversion channels built to divert stream water into agricultural fields — Western Himalayas"],
      ["Rajasthan", "<strong>Tankas</strong>", "Underground tanks in courtyards storing rooftop rainwater. Part of the well-developed rooftop rainwater harvesting tradition"],
      ["West Bengal", "Inundation channels", "Used to irrigate the fields with flood water in the flood plains"],
      ["Semi-arid and arid regions", "<strong>Khadins</strong> in Jaisalmer and <strong>Johads</strong> elsewhere in Rajasthan", "Agricultural fields converted into rain-fed storage structures, allowing water to stand and moisten the soil"],
      ["Meghalaya", "Bamboo drip irrigation", "A 200-year-old system of tapping stream and spring water using bamboo pipes"],
    ] },
    { t: "note", kind: "real", title: "Two places worth naming", html: "<strong>Gendathur</strong>, a remote backward village in Mysuru, Karnataka: nearly 200 households have installed rooftop rainwater harvesting, and the village has earned the rare distinction of being rich in rainwater.<br><br>In the semi-arid regions of Rajasthan, <strong>tankas</strong> were built inside the main house or courtyard, connected by pipes to sloping roofs. The first spell of rain was usually not collected, as it would clean the roofs and pipes; the rain from the second spell onwards was stored. This water lasted till the next rainfall — and in extremely hot and dry Rajasthan, the tanka also kept the room cool." },
    { t: "note", kind: "idea", html: "The argument the chapter builds to: as the ecological and social costs of large dams have become clearer, <strong>water harvesting</strong> is being revived as a socio-economically and environmentally viable alternative. Tamil Nadu is the first and only state in India that has made <strong>rooftop rainwater harvesting structures compulsory</strong> for all houses across the state." },
  ],
  examFocus: [
    "Four distinct causes of water scarcity — and that pollution and unequal access matter as much as rainfall.",
    "What multi-purpose means, and Nehru's 'temples of modern India'.",
    "Advantages and disadvantages of multi-purpose projects, in balance.",
    "The Narmada Bachao Andolan.",
    "The eight dams with their rivers and states — this is map work.",
    "Traditional harvesting structures by region: guls, tankas, khadins, johads, bamboo drip irrigation.",
    "Gendathur, and Tamil Nadu's compulsory rooftop harvesting.",
  ],
  flashcards: [
    { q: "What proportion of the earth's water is freshwater?", a: "About 2.5% of the total volume, and most of that is locked in ice sheets and glaciers. India receives nearly 4% of global precipitation." },
    { q: "Give four causes of water scarcity in India.", a: "Over-exploitation and unequal access, particularly through private groundwater pumping; growing population raising domestic and irrigation demand; industrialisation demanding water and hydroelectricity; and pollution making available water unfit for use." },
    { q: "Why can a region with plenty of water still face scarcity?", a: "Because the water may be polluted by domestic and industrial waste, chemicals, pesticides and fertilisers, or because access to it is unequal — those who can afford pumps take as much as they want." },
    { q: "What is a multi-purpose river project?", a: "A project where one dam serves several purposes together — irrigation, electricity generation, water supply, flood control, recreation, inland navigation and fish breeding." },
    { q: "Who called dams the 'temples of modern India' and why?", a: "Jawaharlal Nehru, because they would integrate development of agriculture and the village economy with rapid industrialisation and the growth of the urban economy." },
    { q: "Give three arguments against large dams.", a: "They displace local people who lose land and livelihood; they fragment rivers and harm aquatic life through sedimentation; and they have caused inter-state and intra-state conflicts over water sharing." },
    { q: "What was the Narmada Bachao Andolan?", a: "A movement that mobilised tribal people, farmers, environmentalists and human rights activists against the Sardar Sarovar dam on the Narmada, over displacement and environmental damage." },
    { q: "What are guls and kuls?", a: "Diversion channels in the Western Himalayas that carry stream water to agricultural fields." },
    { q: "What is a tanka?", a: "An underground tank in Rajasthan, built in the main house or courtyard and connected by pipes to sloping rooftops, used to store rooftop rainwater for drinking. The first spell of rain is not collected, as it cleans the roof and pipes." },
    { q: "What are khadins and johads?", a: "Rain-fed storage structures in the semi-arid regions of Rajasthan — agricultural fields converted so that water stands and moistens the soil. Khadins are found in Jaisalmer." },
    { q: "Which village in Karnataka is known for rooftop rainwater harvesting?", a: "Gendathur, a remote backward village in Mysuru, where nearly 200 households have installed rooftop harvesting and the village has become rich in rainwater." },
    { q: "Which state has made rooftop rainwater harvesting compulsory?", a: "Tamil Nadu — the first and only state in India to make rooftop rainwater harvesting structures compulsory for all houses across the state." },
  ],
  quiz: [
    { q: "Freshwater accounts for about what share of the earth's total water?", options: ["25%", "10%", "2.5%", "50%"], answer: 2, why: "Only about 2.5% is freshwater, and most of that is in ice sheets and glaciers." },
    { q: "Bhakra Nangal is built on the:", options: ["Chenab", "Satluj-Beas", "Mahanadi", "Narmada"], answer: 1, why: "Bhakra Nangal on the Satluj-Beas is used for water storage and electricity generation." },
    { q: "The Hirakud project is on the:", options: ["Krishna", "Chambal", "Mahanadi", "Bhagirathi"], answer: 2, why: "Hirakud, on the Mahanadi in Odisha, integrates conservation of water with flood control." },
    { q: "The Sardar Sarovar dam is on the river:", options: ["Tapi", "Narmada", "Godavari", "Chenab"], answer: 1, why: "It is on the Narmada in Gujarat, and was the focus of the Narmada Bachao Andolan." },
    { q: "Tankas are found in:", options: ["Meghalaya", "Rajasthan", "West Bengal", "Kerala"], answer: 1, why: "Tankas are underground tanks in Rajasthan for storing rooftop rainwater for drinking." },
    { q: "Bamboo drip irrigation is a 200-year-old system found in:", options: ["Rajasthan", "Meghalaya", "Karnataka", "Punjab"], answer: 1, why: "In Meghalaya, stream and spring water is tapped using bamboo pipes." },
    { q: "Guls and kuls are diversion channels found in the:", options: ["Deccan plateau", "Western Himalayas", "Coastal plains", "Thar desert"], answer: 1, why: "They divert stream water into agricultural fields in hill and mountainous regions." },
    { q: "Which state made rooftop rainwater harvesting compulsory for all houses?", options: ["Kerala", "Rajasthan", "Tamil Nadu", "Karnataka"], answer: 2, why: "Tamil Nadu is the first and only state to make it compulsory statewide." },
    { q: "In Rajasthan, the first spell of rain is usually not collected in a tanka because:", options: ["It is too little", "It cleans the roof and pipes", "It is too acidic", "It evaporates"], answer: 1, why: "The first spell washes the roofs and pipes clean; storage begins from the second spell onwards." },
    { q: "The Narmada Bachao Andolan was primarily concerned with:", options: ["Water pollution", "Displacement and environmental damage from a large dam", "Inter-state river disputes only", "Groundwater depletion"], answer: 1, why: "It mobilised tribal people, farmers and environmentalists against the Sardar Sarovar dam over displacement and ecological cost." },
  ],
  keyTopics: [
    { name: "Causes of water scarcity — including pollution and unequal access, not just rainfall", importance: "high", note: "The chapter's central trap: 'less rainfall' alone will not earn full marks in a 3-mark answer." },
    { name: "Multi-purpose river projects — advantages and disadvantages", importance: "high", note: "A frequent 5-mark 'explain both sides' long answer; Nehru's 'temples of modern India' quote is often asked for directly." },
    { name: "Dams and their rivers/states", importance: "high", note: "The map-work list — Salal, Bhakra Nangal, Tehri, Rana Pratap Sagar, Sardar Sarovar, Hirakud, Nagarjuna Sagar, Tungabhadra — is tested as identification and in case studies." },
    { name: "Traditional rainwater harvesting structures by region", importance: "high", note: "Tankas, guls/kuls, khadins/johads, bamboo drip irrigation — a reliable 3-mark 'describe' question." },
    { name: "Narmada Bachao Andolan and arguments against big dams", importance: "medium", note: "Displacement, ecological damage and inter-state conflict — usually a 3-mark list answer." },
    { name: "Tamil Nadu's compulsory rooftop harvesting and Gendathur", importance: "medium", note: "Specific named examples that show up in 1-mark recall and case studies." },
  ],
  written: [
    { q: "What is meant by a 'multi-purpose river project'?", marks: 1, kind: "short", importance: "high",
      answer: "A project in which a single dam is built to serve several purposes together — such as irrigation, electricity generation, water supply, flood control, recreation, inland navigation and fish breeding — rather than one purpose alone." },
    { q: "Name the river on which the Sardar Sarovar Dam is built, and the state in which it is located.", marks: 1, kind: "short", importance: "high",
      answer: "The <strong>Narmada</strong> river; the dam is located in <strong>Gujarat</strong>." },
    { q: "Mention two disadvantages of multi-purpose river projects.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> They cause large-scale displacement of local communities, who lose their land, livelihood and any meaningful say in the process, often without adequate compensation.<br><strong>(ii)</strong> They fragment rivers, disrupting the natural flow and causing excessive sedimentation at the dam site, which affects the food chain of the aquatic life living there." },
    { q: "What are 'tankas'? Where are they traditionally found?", marks: 2, kind: "short", importance: "high",
      answer: "Tankas are <strong>underground tanks</strong> built inside the main house or courtyard, connected by pipes to the sloping roof of the house, used to store rooftop rainwater for drinking. They are traditionally found in the semi-arid and arid regions of <strong>Rajasthan</strong>." },
    { q: "Why is it wrong to say water scarcity in India is caused only by low rainfall?", marks: 2, kind: "short", importance: "high",
      answer: "A region can have plenty of water and still face scarcity, because of <strong>pollution</strong> — domestic and industrial waste, chemicals, pesticides and fertilisers can make available water unfit to use — or because of <strong>unequal access</strong>, since those who can afford private pumping devices draw as much groundwater as they want, leaving less for others." },
    { q: "Explain any three arguments put forward by people opposing the construction of large dams.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Displacement:</strong> large dams have displaced local communities, who lose their land and livelihood without always receiving fair compensation.</li><li><strong>Ecological damage:</strong> dams fragment rivers, causing excessive sedimentation and disrupting the food chain of aquatic life; they can also increase the risk of earthquakes, reduce the productive capacity of the land, and cause pollution from the excessive use of water.</li><li><strong>Conflict over sharing:</strong> multi-purpose projects intended to control floods have themselves caused floods due to badly managed reservoirs, and led to inter-state water-sharing conflicts.</li></ul>" },
    { q: "Describe the rooftop rainwater harvesting system traditionally practised in Rajasthan.", marks: 3, kind: "short", importance: "high",
      answer: "Almost all households in the semi-arid and arid regions of Rajasthan traditionally had underground tanks called <strong>tankas</strong> for storing drinking water, built inside the main house or courtyard. The tankas were connected by pipes to the sloping roofs of the houses, from which rainwater was channelled and stored. The water from the <strong>first spell of rain was not collected</strong>, since it would clean the roof and pipes; water from subsequent spells was then stored, and this lasted the household until the next rainfall. In the hot, dry climate of Rajasthan, the tanka also helped keep the room in which it was built cool." },
    { q: "Explain any three causes of water scarcity in India.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Over-exploitation and unequal access:</strong> in housing colonies and industrial areas, those who can afford private groundwater pumping devices draw as much water as they want.</li><li><strong>Growing population:</strong> more water is needed for domestic use and to produce more food, raising irrigation demand.</li><li><strong>Pollution:</strong> water may be abundant but unfit to use, polluted by domestic and industrial waste, chemicals, pesticides and fertilisers.</li></ul>" },
    { q: "Explain any five objectives fulfilled by multi-purpose river projects, and give one criticism made against them.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Irrigation</strong> — supplying water to farmland to increase crop production.</li><li><strong>Electricity generation</strong> — through hydel power stations built into the dam.</li><li><strong>Water supply</strong> — for domestic and industrial use in nearby towns and cities.</li><li><strong>Flood control</strong> — regulating the release of water to reduce the risk of downstream flooding.</li><li><strong>Recreation, inland navigation and fish breeding</strong> — reservoirs are also used for boating and tourism, as waterways, and to support fisheries.</li></ul>Nehru called dams the 'temples of modern India' for integrating agricultural and industrial development in this way — but critics point out that the same projects have displaced communities, fragmented rivers, and disrupted aquatic ecosystems through sedimentation." },
    { q: "Describe the traditional methods of rainwater harvesting practised in different parts of India.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Guls and kuls</strong> — diversion channels in the hill and mountainous regions of the western Himalayas that carry stream water to agricultural fields.</li><li><strong>Tankas</strong> — underground tanks in Rajasthan's courtyards that store rooftop rainwater for drinking.</li><li><strong>Inundation channels</strong> — used in the flood plains of West Bengal to irrigate fields with flood water.</li><li><strong>Khadins</strong> (in Jaisalmer) and <strong>johads</strong> (elsewhere in Rajasthan) — agricultural fields converted into rain-fed storage structures that let water stand and moisten the soil.</li><li><strong>Bamboo drip irrigation</strong> — a 200-year-old system in Meghalaya that taps stream and spring water using bamboo pipes.</li></ul>As large dams have come under criticism for their social and ecological costs, these traditional, low-cost methods are being revived as a viable alternative — Tamil Nadu has even made rooftop rainwater harvesting compulsory for all houses across the state." },
  ],
  assertionReason: [
    { assertion: "Multi-purpose river projects are viewed with increasing resistance in India today.",
      reason: "These projects have caused large-scale displacement of local communities and have disrupted aquatic ecosystems through sedimentation.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly gives the social and ecological reasons behind the growing opposition described in A." },
    { assertion: "India faces water scarcity despite receiving nearly 4% of the world's total precipitation.",
      reason: "Much of India's available freshwater is either polluted or made inaccessible to a large section of the population by unequal distribution.",
      answer: 0, importance: "high",
      why: "Both are true, and R explains exactly why abundant rainfall does not translate into water security for everyone." },
    { assertion: "Tankas were traditionally built as part of the rainwater harvesting system in Rajasthan.",
      reason: "Rajasthan receives heavy annual rainfall, which makes rooftop harvesting the cheapest source of water there.",
      answer: 2, importance: "medium",
      why: "A is true — tankas are a genuine Rajasthani tradition. But R is false: Rajasthan is a semi-arid to arid state with low, unreliable rainfall, which is precisely why households needed to carefully store every drop that fell." },
    { assertion: "Dams are commonly referred to as multi-purpose river valley projects.",
      reason: "Dams are built primarily to store water for irrigation and to generate hydroelectric power.",
      answer: 1, importance: "medium",
      why: "Both statements are true on their own, but R does not explain why dams are called 'multi-purpose' — that name comes from serving several functions together (irrigation, power, water supply, flood control, navigation, fisheries), not merely from the two purposes named in R." },
  ],
  caseStudies: [
    { title: "Multi-purpose projects — rivers and states", importance: "high",
      source: "Study the table below and answer the questions that follow:<br><table><thead><tr><th>Project</th><th>River</th><th>State</th></tr></thead><tbody><tr><td>Bhakra Nangal</td><td>Satluj-Beas</td><td>Punjab–Himachal Pradesh</td></tr><tr><td>Sardar Sarovar</td><td>Narmada</td><td>Gujarat</td></tr><tr><td>Hirakud</td><td>Mahanadi</td><td>Odisha</td></tr><tr><td>Tehri</td><td>Bhagirathi</td><td>Uttarakhand</td></tr></tbody></table>",
      parts: [
        { q: "Name the state in which the Sardar Sarovar Dam is located, and identify the river on which it is built.", marks: 1, answer: "<strong>Gujarat</strong>; it is built on the river <strong>Narmada</strong>." },
        { q: "Which of the projects listed integrates conservation of water with flood control, and in which state does it lie?", marks: 1, answer: "<strong>Hirakud</strong>, on the Mahanadi, in <strong>Odisha</strong> — it was built partly to control the floods that used to plague the Mahanadi delta." },
        { q: "Identify the dam built on the Bhagirathi river and name the state in which it lies.", marks: 1, answer: "The <strong>Tehri Dam</strong>, in <strong>Uttarakhand</strong>." },
        { q: "Which movement is associated with opposition to the dam located in Gujarat? State one reason for the opposition.", marks: 2, answer: "The <strong>Narmada Bachao Andolan</strong>; it opposed the Sardar Sarovar Dam because of the large-scale displacement of tribal people and farmers, and the environmental damage caused by submergence of forest land." },
      ] },
    { title: "Reading about the tanka", importance: "medium",
      source: "Read the following passage: 'In the semi-arid and arid regions of Rajasthan, almost all households traditionally had underground tanks, called tankas, for storing drinking water. The tankas were built inside the main house or the courtyard, and were connected to the sloping roofs of the houses through a pipe. Rainwater was collected from these roofs and stored. The water from the first spell of rain was usually not collected, as it would clean the roofs and pipes. The rainwater from the following spells was then collected.'",
      parts: [
        { q: "What is a tanka, and in which state is it traditionally used?", marks: 1, answer: "An underground tank for storing rooftop rainwater, traditionally built inside the house or courtyard in <strong>Rajasthan</strong>." },
        { q: "Why was the water from the first spell of rain not collected in a tanka?", marks: 1, answer: "Because it would wash the dust and dirt off the roof and connecting pipes; storage began only from the next spell of rain onwards." },
        { q: "Besides providing drinking water, what other advantage did the tanka give to Rajasthani households?", marks: 1, answer: "It helped keep the room in which it was built cool, which was a valuable benefit in the extremely hot and dry climate of Rajasthan." },
        { q: "Name a village in Karnataka known for successful rooftop rainwater harvesting, and explain its significance.", marks: 2, answer: "<strong>Gendathur</strong>, in Mysuru district; nearly 200 households there have installed rooftop rainwater harvesting, and this otherwise remote, backward village has earned the distinction of being rich in rainwater — showing the practice is viable even in ordinary rural settings, not just showcase projects." },
      ] },
  ],
};
