import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "agriculture",
  num: 4,
  title: "Agriculture",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 20,
  blurb: "Two-thirds of India still depends on farming. This chapter is about how that farming is organised, what it grows, and why it is under strain.",
  bigIdea: "Indian agriculture is shaped by three things: the monsoon, the size of the average holding, and government policy. Change any one and the whole picture shifts.",
  syllabus: [
    "Types of farming",
    "Cropping pattern and major crops",
    "Technological and institutional reforms",
    "Impact of globalisation on agriculture",
    "Map work: major crop-growing areas and leading producer states",
  ],
  blocks: [
    { t: "h", text: "Types of farming" },
    { t: "table", head: ["Type", "How it works", "Where"], rows: [
      ["<strong>Primitive subsistence</strong>", "Slash and burn on small patches with primitive tools — hoe, dao, digging sticks — and family labour. Depends on the monsoon and natural soil fertility. When soil fertility drops, the family moves to another patch", "Known as <em>jhumming</em> in the north-east, <em>bewar</em> or <em>dahiya</em> in Madhya Pradesh, <em>podu</em> or <em>penda</em> in Andhra Pradesh, <em>kumari</em> in the Western Ghats"],
      ["<strong>Intensive subsistence</strong>", "Practised where land holdings are small. Labour-intensive, with high doses of biochemical inputs and irrigation. The 'right of inheritance' keeps fragmenting land, making holdings uneconomical", "Areas of high population pressure on land"],
      ["<strong>Commercial farming</strong>", "Higher doses of modern inputs — HYV seeds, chemical fertilisers, insecticides, pesticides — to obtain higher productivity. What counts as commercial varies by region: rice is commercial in Punjab and Haryana but subsistence in Odisha", "Punjab, Haryana, western Uttar Pradesh"],
      ["<strong>Plantation</strong>", "A single crop grown on a large area, with capital-intensive inputs and migrant labourers. Produce is used as raw material in industries, so an efficient transport network is essential", "Tea in Assam and North Bengal, coffee in Karnataka, rubber in Kerala"],
    ] },

    { t: "h", text: "The three cropping seasons" },
    { t: "sim", id: "cropping-seasons" },
    { t: "note", kind: "trap", html: "<strong>Sugarcane</strong> takes almost a year to grow, so it does not belong to any of the three cropping seasons. That exception is asked directly." },

    { t: "h", text: "Major crops" },
    { t: "table", head: ["Crop", "Conditions", "Leading areas"], rows: [
      ["<strong>Rice</strong>", "Kharif. High temperature (above 25°C) and high humidity with annual rainfall above 100 cm. Grown with irrigation in areas of less rainfall", "Northern and north-eastern plains, coastal areas, deltaic regions. Punjab, Haryana, western UP and parts of Rajasthan grow it with canals and tubewells"],
      ["<strong>Wheat</strong>", "Rabi. Cool growing season and bright sunshine at ripening. 50–75 cm of annual rainfall, evenly distributed", "The Ganga-Satluj plains in the north-west and the black soil region of the Deccan"],
      ["<strong>Millets — jowar, bajra, ragi</strong>", "Coarse grains, very high nutritional value. Jowar is rain-fed, mostly grown in the moist areas", "Jowar: Maharashtra, Karnataka, Andhra Pradesh, Madhya Pradesh. Bajra: sandy soils and shallow black soil — Rajasthan, UP, Maharashtra, Gujarat, Haryana. Ragi: dry regions — Karnataka, Tamil Nadu, Himachal"],
      ["<strong>Maize</strong>", "Kharif, but grown as a rabi crop in Bihar. Both food and fodder. Old alluvial soil, temperature 21–27°C", "Karnataka, Uttar Pradesh, Bihar, Andhra Pradesh, Madhya Pradesh"],
      ["<strong>Pulses</strong>", "Mostly rainfed. Being leguminous, they help restore soil fertility by fixing nitrogen from the air — except arhar", "Madhya Pradesh, Rajasthan, Maharashtra, Karnataka, Uttar Pradesh"],
      ["<strong>Sugarcane</strong>", "Tropical and subtropical. Hot and humid climate, 21–27°C, 75–100 cm rainfall", "Uttar Pradesh, Maharashtra, Karnataka, Tamil Nadu, Andhra Pradesh, Bihar, Punjab, Haryana"],
      ["<strong>Tea</strong>", "Plantation. Tropical and sub-tropical climate, deep fertile well-drained soil rich in humus and organic matter. Warm, moist frost-free climate all year", "Assam, hills of Darjeeling and Jalpaiguri, Tamil Nadu, Kerala, Himachal, Uttarakhand"],
      ["<strong>Coffee</strong>", "Indian coffee is famous for its quality. The Arabica variety was initially brought from Yemen", "Nilgiri hills of Karnataka, Kerala and Tamil Nadu"],
      ["<strong>Cotton</strong>", "Kharif. Black soil of the Deccan plateau. High temperature, light rainfall, 210 frost-free days, bright sunshine. Takes 6–8 months to mature", "Maharashtra, Gujarat, Madhya Pradesh, Karnataka, Andhra Pradesh, Tamil Nadu, Punjab, Haryana"],
      ["<strong>Jute</strong>", "Well-drained fertile soils in the flood plains where soils are renewed every year. High temperature during growth", "West Bengal, Bihar, Assam, Odisha, Meghalaya"],
    ] },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "exam", title: "Map work", html: "The board asks for <strong>major areas of rice and wheat</strong>, and the <strong>largest or major producer states</strong> of sugarcane, tea, coffee, rubber, cotton and jute. The crops layer in the locator has each one plotted at its leading state." },
    { t: "note", kind: "real", html: "India is the second largest producer of rice in the world after China, and the largest producer and consumer of pulses. Millets are described in the NCERT as coarse grains, but they have <strong>very high nutritional value</strong> — ragi is rich in iron, calcium, other micro nutrients and roughage." },

    { t: "h", text: "Reforms, and where they fell short" },
    { t: "list", items: [
      "After independence, <strong>collectivisation, consolidation of holdings, cooperation and abolition of zamindari</strong> were given priority. The Land Reform Acts were passed but implementation was weak in the absence of political will.",
      "The <strong>Green Revolution</strong> (HYV seeds) and the <strong>White Revolution</strong> (Operation Flood, milk) transformed output — but they were concentrated in a few regions and among the better-off farmers, and left large parts of the country untouched.",
      "Institutional support followed: <strong>Kisan Credit Card (KCC)</strong>, <strong>Personal Accident Insurance Scheme (PAIS)</strong>, crop insurance against natural calamities, minimum support prices, subsidies on inputs, and special weather bulletins for farmers on radio and television.",
    ] },
    { t: "note", kind: "why", title: "Why Indian farmers are under pressure", html: "Since 1990, the reduction in public investment in agriculture, the reduction in import duties on agricultural products, and competition from highly subsidised farmers in developed countries have all squeezed Indian farmers. Subsidy on fertilisers has decreased while power and fertiliser costs rise. Farmers withdrawing investment from agriculture is causing a <strong>downfall in employment</strong> in the sector — which is exactly what the Economics chapter on Sectors describes from the other side." },
    { t: "note", kind: "idea", html: "The chapter's own suggestion: instead of pushing food grains further, farmers could shift to <strong>horticulture, fruits and vegetables, medicinal and aromatic plants, floriculture, bio-diesel crops and organic farming</strong> — which are less water-intensive and fetch higher prices. Gene manipulation and improved seeds also matter, but so does simply making agriculture profitable again." },
  ],
  examFocus: [
    "Four types of farming with distinguishing features and regions.",
    "The three cropping seasons with crops and months — and that sugarcane fits none.",
    "Growing conditions and leading states for rice, wheat, cotton, jute, tea and coffee.",
    "Local names of shifting cultivation — jhumming, bewar, podu, kumari.",
    "Why pulses restore soil fertility, and the exception (arhar).",
    "Institutional and technological reforms, with named schemes.",
    "The effect of globalisation on Indian farmers, and the alternatives suggested.",
    "The crop map-work list.",
  ],
  flashcards: [
    { q: "What is primitive subsistence farming?", a: "Slash and burn agriculture on small patches using primitive tools like the hoe, dao and digging sticks, with family labour. It depends on the monsoon and natural soil fertility; when fertility falls the family moves on." },
    { q: "Give four local names for shifting cultivation in India.", a: "Jhumming in the north-eastern states, bewar or dahiya in Madhya Pradesh, podu or penda in Andhra Pradesh, and kumari in the Western Ghats." },
    { q: "Why do intensive subsistence holdings keep getting smaller?", a: "Because of the right of inheritance, which leads to the division of land between successive generations, making holdings increasingly uneconomical." },
    { q: "What distinguishes plantation agriculture?", a: "A single crop grown over a large area, with capital-intensive inputs and migrant labourers. The produce is used as industrial raw material, so an efficient transport network is essential." },
    { q: "Give the growing conditions for rice.", a: "A kharif crop needing high temperature above 25°C, high humidity, and annual rainfall above 100 cm. In areas of less rainfall it is grown with irrigation from canals and tubewells." },
    { q: "Give the growing conditions for wheat.", a: "A rabi crop needing a cool growing season and bright sunshine at ripening, with 50 to 75 cm of evenly distributed annual rainfall. Grown in the Ganga-Satluj plains and the black soil region of the Deccan." },
    { q: "Why are pulses important for the soil?", a: "Being leguminous crops, all pulses except arhar help restore soil fertility by fixing nitrogen from the air. They are therefore grown in rotation with other crops." },
    { q: "What conditions does cotton need?", a: "Black soil of the Deccan plateau, high temperature, light rainfall or irrigation, 210 frost-free days and bright sunshine. It takes six to eight months to mature." },
    { q: "Where is jute grown and why there?", a: "West Bengal, Bihar, Assam, Odisha and Meghalaya — on well-drained fertile soils in the flood plains, where soils are renewed every year, with high temperature during the growing period." },
    { q: "What were the Green and White Revolutions?", a: "The Green Revolution introduced high-yielding variety seeds and modern inputs, transforming food-grain output. The White Revolution, or Operation Flood, transformed milk production. Both were concentrated in a few regions." },
    { q: "Name three institutional supports provided to Indian farmers.", a: "The Kisan Credit Card, the Personal Accident Insurance Scheme, crop insurance against natural calamities, minimum support prices, and special weather bulletins for farmers on radio and television." },
    { q: "How has globalisation put pressure on Indian farmers?", a: "Reduced public investment in agriculture, reduced import duties on agricultural products, and competition from heavily subsidised farmers in developed countries — alongside rising input costs as subsidies fall." },
  ],
  quiz: [
    { q: "Jhumming is a name for:", options: ["Plantation farming", "Shifting cultivation", "Intensive subsistence farming", "Commercial farming"], answer: 1, why: "Jhumming is the north-eastern name for slash and burn shifting cultivation. Other names include bewar, podu and kumari." },
    { q: "Which crop does not belong to any of the three cropping seasons?", options: ["Wheat", "Rice", "Sugarcane", "Bajra"], answer: 2, why: "Sugarcane takes almost a year to grow, so it does not fit the rabi, kharif or zaid pattern." },
    { q: "Rice is a ______ crop.", options: ["Rabi", "Kharif", "Zaid", "Plantation"], answer: 1, why: "Rice is sown with the onset of the monsoon in June-July and harvested in September-October." },
    { q: "Cotton grows best in:", options: ["Alluvial soil", "Black soil", "Laterite soil", "Arid soil"], answer: 1, why: "Cotton requires the black soil of the Deccan plateau, along with high temperature and bright sunshine." },
    { q: "Which pulse does NOT fix nitrogen in the soil?", options: ["Gram", "Moong", "Arhar", "Urad"], answer: 2, why: "All pulses except arhar are leguminous and help restore soil fertility by fixing nitrogen from the air." },
    { q: "The leading producer of tea in India is:", options: ["Kerala", "Assam", "Karnataka", "West Bengal"], answer: 1, why: "Assam is the leading tea-producing state, followed by the hills of Darjeeling and Jalpaiguri in West Bengal." },
    { q: "The Arabica variety of coffee was initially brought from:", options: ["Brazil", "Yemen", "Ethiopia", "Sri Lanka"], answer: 1, why: "Indian coffee production began with the Arabica variety initially brought from Yemen, and is grown in the Nilgiri hills." },
    { q: "Ragi is particularly rich in:", options: ["Protein only", "Iron, calcium, micro nutrients and roughage", "Fat", "Vitamin C"], answer: 1, why: "Though classed as a coarse grain, ragi has very high nutritional value — rich in iron, calcium, other micro nutrients and roughage." },
    { q: "Maize is grown as a rabi crop in:", options: ["Punjab", "Bihar", "Kerala", "Assam"], answer: 1, why: "Maize is generally a kharif crop, but in Bihar it is grown as a rabi crop." },
    { q: "Which of these is a plantation crop?", options: ["Wheat", "Bajra", "Rubber", "Gram"], answer: 2, why: "Rubber, like tea and coffee, is a plantation crop — a single crop on a large area with capital-intensive inputs and migrant labour." },
  ],
  keyTopics: [
    { name: "Types of farming — primitive subsistence, intensive subsistence, commercial, plantation", importance: "high", note: "A reliable 'distinguish between' or 'describe' 3-mark question, and the basis of a case-study format." },
    { name: "Cropping seasons — rabi, kharif, zaid, and the sugarcane exception", importance: "high", note: "Repeated 1-mark question: which crop belongs to none of the three seasons." },
    { name: "Rice and wheat — growing conditions and leading areas", importance: "high", note: "Core of the map-work component; also the chapter's most-asked crop-conditions question." },
    { name: "Cash and plantation crops — cotton, jute, tea, coffee — conditions and leading states", importance: "high", note: "Map work again, plus 'explain the conditions required' as a 3-mark answer." },
    { name: "Institutional and technological reforms — Green Revolution, White Revolution, KCC, MSP", importance: "medium", note: "Named-scheme recall, usually 2–3 marks." },
    { name: "Impact of globalisation on Indian agriculture", importance: "medium", note: "A 3–5 mark analytical question — reduced subsidies, import competition, and the suggested alternatives." },
    { name: "Pulses and nitrogen fixation — the arhar exception", importance: "low", note: "A quick, commonly repeated 1-mark trap question." },
  ],
  written: [
    { q: "Name the crop that does not belong to any of the three cropping seasons.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Sugarcane.</strong> It takes almost a year to mature, so it does not fit the rabi, kharif or zaid pattern." },
    { q: "Which pulse crop does not help in restoring soil fertility by fixing nitrogen?", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Arhar.</strong> All other pulses, being leguminous, help restore soil fertility by fixing nitrogen from the air." },
    { q: "Differentiate between rabi and kharif crops, giving one example of each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Rabi crops</strong> are sown in winter, from October to December, and harvested in summer, from April to June, e.g. wheat.<br><strong>Kharif crops</strong> are sown with the onset of the monsoon, in June-July, and harvested in September-October, e.g. rice." },
    { q: "What is meant by 'plantation agriculture'? Give one example.", marks: 2, kind: "short", importance: "high",
      answer: "A type of farming in which a single crop is grown over a large area, using capital-intensive inputs and migrant labour, with the produce used as raw material in industries — which is why an efficient transport network is essential to move it before it perishes. Example: tea in Assam and the hills of Darjeeling and Jalpaiguri." },
    { q: "Mention two institutional reforms introduced by the government to support farmers.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>(i)</strong> The <strong>Kisan Credit Card (KCC)</strong>, giving farmers easier access to credit.<br><strong>(ii)</strong> <strong>Minimum Support Prices (MSP)</strong> for crops, along with crop insurance and the Personal Accident Insurance Scheme (PAIS)." },
    { q: "Distinguish between intensive subsistence farming and commercial farming.", marks: 3, kind: "long", importance: "high",
      answer: "<strong>Intensive subsistence farming</strong> is practised where landholdings are small; it is labour-intensive and uses high doses of biochemical inputs and irrigation to get the most out of a small piece of land, and holdings keep shrinking further because of the right of inheritance.<br><strong>Commercial farming</strong> uses even higher doses of modern inputs — HYV seeds, chemical fertilisers, insecticides and pesticides — mainly to sell the produce in the market rather than for the farmer's own consumption. Whether a crop counts as commercial or subsistence depends on the region: rice is a commercial crop in Punjab and Haryana, but a subsistence crop in Odisha." },
    { q: "Describe the geographical conditions required for the cultivation of rice.", marks: 3, kind: "short", importance: "high",
      answer: "Rice is a <strong>kharif crop</strong> that requires <strong>high temperature</strong> (above 25°C), <strong>high humidity</strong>, and annual rainfall <strong>above 100 cm</strong>. In areas that receive less rainfall, it is grown with the help of irrigation from canals and tubewells, as in Punjab, Haryana and western Uttar Pradesh. It is grown extensively in the northern and north-eastern plains, coastal areas and deltaic regions." },
    { q: "Explain any three effects of globalisation on Indian agriculture since 1990.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Reduced public investment</strong> in agriculture since 1990 has weakened infrastructure such as irrigation, power, roads and market linkages.</li><li><strong>Reduced import duties</strong> on agricultural products have exposed Indian farmers to <strong>competition from highly subsidised farmers in developed countries</strong>, undercutting their prices.</li><li><strong>Falling input subsidies</strong>, combined with rising power and fertiliser costs, have squeezed farm incomes, causing many farmers to withdraw investment from agriculture — leading to a decline in employment in the sector.</li></ul>" },
    { q: "Explain the various types of farming practised in India, with the region where each is important.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Primitive subsistence farming</strong> — slash-and-burn cultivation on small patches using primitive tools like the hoe, dao and digging sticks, with family labour, depending on the monsoon and natural soil fertility. Known as jhumming in the north-east, bewar/dahiya in Madhya Pradesh, podu/penda in Andhra Pradesh, and kumari in the Western Ghats.</li><li><strong>Intensive subsistence farming</strong> — practised on small landholdings with high doses of inputs and irrigation, common in areas of high population pressure on land.</li><li><strong>Commercial farming</strong> — uses HYV seeds and modern inputs for higher productivity; found mainly in Punjab, Haryana and western Uttar Pradesh.</li><li><strong>Plantation agriculture</strong> — a single crop over a large area with capital-intensive inputs and migrant labour, e.g. tea in Assam, coffee in Karnataka, rubber in Kerala.</li></ul>" },
    { q: "Explain any five institutional and technological reforms introduced by the government to modernise Indian agriculture.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Collectivisation, consolidation of holdings and abolition of zamindari</strong> were given priority right after independence, through Land Reform Acts (though implementation was uneven).</li><li>The <strong>Green Revolution</strong> introduced high-yielding variety (HYV) seeds and transformed food-grain output, though concentrated in a few regions.</li><li>The <strong>White Revolution (Operation Flood)</strong> transformed milk production nationally.</li><li>The <strong>Kisan Credit Card (KCC)</strong> and the <strong>Personal Accident Insurance Scheme (PAIS)</strong> improved farmers' access to credit and insurance.</li><li><strong>Crop insurance against natural calamities, minimum support prices, input subsidies, and special weather bulletins</strong> on radio and television for farmers were introduced to reduce risk and support incomes.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Rice is predominantly grown as a kharif crop in India.",
      reason: "Rice requires high temperature, high humidity, and annual rainfall above 100 cm, conditions that prevail during the south-west monsoon.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R gives exactly the climatic requirements that tie rice cultivation to the monsoon (kharif) season." },
    { assertion: "Sugarcane is not classified under any of the three cropping seasons.",
      reason: "Sugarcane takes almost a year to mature, unlike crops that are strictly sown and harvested within the rabi, kharif or zaid period.",
      answer: 0, importance: "high",
      why: "Both are true, and R correctly explains why sugarcane's long growth cycle places it outside the three-season classification." },
    { assertion: "Pulses are generally grown in rotation with other crops in India.",
      reason: "Except for arhar, pulses require comparatively little irrigation and fertiliser, and help restore soil fertility by fixing nitrogen from the air.",
      answer: 0, importance: "medium",
      why: "Both are true, and R explains why farmers value pulses as a rotation crop — they replenish the soil between cycles of more demanding crops." },
    { assertion: "The Green Revolution and the White Revolution benefited farmers equally across all regions of India.",
      reason: "Both revolutions were concentrated mainly in a few regions and benefited primarily the better-off farmers there.",
      answer: 3, importance: "medium",
      why: "A is false — the benefits were not spread equally; large parts of the country remained untouched. R is true, and it is precisely why A is false: the concentration of benefits in a few regions is the opposite of an equal, nationwide impact." },
  ],
  caseStudies: [
    { title: "Identify the type of farming", importance: "high",
      source: "Read the following descriptions of farming practices in India and answer the questions that follow:<br>Farm A: small patches of land are cleared by cutting and burning vegetation; primitive tools like the hoe and digging stick are used along with family labour; when soil fertility declines, the family moves to a new patch.<br>Farm B: land holdings are small, but high doses of biochemical inputs and irrigation are used to get higher yields from the same small piece of land, keeping the farmer occupied through the year.<br>Farm C: a single crop is grown over a large area with capital-intensive inputs, using migrant labourers, and the produce is used as raw material in nearby processing industries.",
      parts: [
        { q: "Identify the type of farming described in Farm A, and name one region where it is locally known as jhumming.", marks: 2, answer: "<strong>Primitive subsistence farming</strong>; it is known as jhumming in the <strong>north-eastern states</strong> of India." },
        { q: "Identify the type of farming in Farm B. Why do the landholdings under this system keep shrinking?", marks: 2, answer: "<strong>Intensive subsistence farming</strong>; because of the <strong>right of inheritance</strong>, land is divided among successive generations, making holdings smaller and increasingly uneconomical over time." },
        { q: "Identify the type of farming in Farm C. Name one crop grown this way, and the state that leads in producing it.", marks: 1, answer: "<strong>Plantation agriculture</strong>; tea is grown this way, with <strong>Assam</strong> as the leading producer state." },
      ] },
    { title: "Comparing two food crops", importance: "high",
      source: "Study the data given below about two major food crops of India and answer the questions that follow:<br><table><thead><tr><th>Feature</th><th>Crop X</th><th>Crop Y</th></tr></thead><tbody><tr><td>Season</td><td>Kharif</td><td>Rabi</td></tr><tr><td>Temperature needed</td><td>Above 25°C</td><td>Cool growing season, bright sunshine at ripening</td></tr><tr><td>Rainfall needed</td><td>Above 100 cm (or irrigation)</td><td>50–75 cm, evenly distributed</td></tr><tr><td>Leading areas</td><td>Northern and north-eastern plains, coastal and deltaic regions</td><td>Ganga-Satluj plains, black soil region of the Deccan</td></tr></tbody></table>",
      parts: [
        { q: "Identify Crop X and Crop Y.", marks: 1, answer: "Crop X is <strong>rice</strong>; Crop Y is <strong>wheat</strong>." },
        { q: "Name two states that are leading producers of Crop X, and two that are leading producers of Crop Y.", marks: 2, answer: "Rice — West Bengal and Punjab (also Andhra Pradesh, Uttar Pradesh). Wheat — Uttar Pradesh and Punjab (also Haryana, Madhya Pradesh)." },
        { q: "Crop X needs more than 100 cm of rainfall, yet it is grown in some areas that do not receive this much. Explain how.", marks: 1, answer: "In areas that do not naturally receive the required rainfall, it is grown with the help of <strong>irrigation from canals and tubewells</strong>, as in Punjab, Haryana and western Uttar Pradesh." },
        { q: "Explain why the growing seasons of Crop X and Crop Y do not overlap.", marks: 1, answer: "Crop X (rice) is sown with the onset of the monsoon in June–July and harvested by September–October; Crop Y (wheat) is then sown in winter, October–December, after the kharif harvest, and harvested in summer, April–June — the two seasons run one after the other rather than at the same time." },
      ] },
  ],
};
