import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "agriculture",
  num: 4,
  title: "Agriculture",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 20,
  blurb: "Two-thirds of India still depends on farming. This chapter is about how that farming is organised, what it grows, and why it is under strain.",
  bigIdea: "Indian agriculture is shaped by three things: the monsoon, the size of the average holding, and government policy. Change any one and the whole picture shifts.",
  syllabus: [
    "Types of farming",
    "Cropping pattern and major crops",
    "Technological and institutional reforms",
    "Impact of globalisation on agriculture",
    "Map work: major crop-growing areas and leading producer states",
  ],
  blocks: [
    { t: "h", text: "Types of farming" },
    { t: "table", head: ["Type", "How it works", "Where"], rows: [
      ["<strong>Primitive subsistence</strong>", "Slash and burn on small patches with primitive tools — hoe, dao, digging sticks — and family labour. Depends on the monsoon and natural soil fertility. When soil fertility drops, the family moves to another patch", "Known as <em>jhumming</em> in the north-east, <em>bewar</em> or <em>dahiya</em> in Madhya Pradesh, <em>podu</em> or <em>penda</em> in Andhra Pradesh, <em>kumari</em> in the Western Ghats"],
      ["<strong>Intensive subsistence</strong>", "Practised where land holdings are small. Labour-intensive, with high doses of biochemical inputs and irrigation. The 'right of inheritance' keeps fragmenting land, making holdings uneconomical", "Areas of high population pressure on land"],
      ["<strong>Commercial farming</strong>", "Higher doses of modern inputs — HYV seeds, chemical fertilisers, insecticides, pesticides — to obtain higher productivity. What counts as commercial varies by region: rice is commercial in Punjab and Haryana but subsistence in Odisha", "Punjab, Haryana, western Uttar Pradesh"],
      ["<strong>Plantation</strong>", "A single crop grown on a large area, with capital-intensive inputs and migrant labourers. Produce is used as raw material in industries, so an efficient transport network is essential", "Tea in Assam and North Bengal, coffee in Karnataka, rubber in Kerala"],
    ] },

    { t: "h", text: "The three cropping seasons" },
    { t: "sim", id: "cropping-seasons" },
    { t: "note", kind: "trap", html: "<strong>Sugarcane</strong> takes almost a year to grow, so it does not belong to any of the three cropping seasons. That exception is asked directly." },

    { t: "h", text: "Major crops" },
    { t: "table", head: ["Crop", "Conditions", "Leading areas"], rows: [
      ["<strong>Rice</strong>", "Kharif. High temperature (above 25°C) and high humidity with annual rainfall above 100 cm. Grown with irrigation in areas of less rainfall", "Northern and north-eastern plains, coastal areas, deltaic regions. Punjab, Haryana, western UP and parts of Rajasthan grow it with canals and tubewells"],
      ["<strong>Wheat</strong>", "Rabi. Cool growing season and bright sunshine at ripening. 50–75 cm of annual rainfall, evenly distributed", "The Ganga-Satluj plains in the north-west and the black soil region of the Deccan"],
      ["<strong>Millets — jowar, bajra, ragi</strong>", "Coarse grains, very high nutritional value. Jowar is rain-fed, mostly grown in the moist areas", "Jowar: Maharashtra, Karnataka, Andhra Pradesh, Madhya Pradesh. Bajra: sandy soils and shallow black soil — Rajasthan, UP, Maharashtra, Gujarat, Haryana. Ragi: dry regions — Karnataka, Tamil Nadu, Himachal"],
      ["<strong>Maize</strong>", "Kharif, but grown as a rabi crop in Bihar. Both food and fodder. Old alluvial soil, temperature 21–27°C", "Karnataka, Uttar Pradesh, Bihar, Andhra Pradesh, Madhya Pradesh"],
      ["<strong>Pulses</strong>", "Mostly rainfed. Being leguminous, they help restore soil fertility by fixing nitrogen from the air — except arhar", "Madhya Pradesh, Rajasthan, Maharashtra, Karnataka, Uttar Pradesh"],
      ["<strong>Sugarcane</strong>", "Tropical and subtropical. Hot and humid climate, 21–27°C, 75–100 cm rainfall", "Uttar Pradesh, Maharashtra, Karnataka, Tamil Nadu, Andhra Pradesh, Bihar, Punjab, Haryana"],
      ["<strong>Tea</strong>", "Plantation. Tropical and sub-tropical climate, deep fertile well-drained soil rich in humus and organic matter. Warm, moist frost-free climate all year", "Assam, hills of Darjeeling and Jalpaiguri, Tamil Nadu, Kerala, Himachal, Uttarakhand"],
      ["<strong>Coffee</strong>", "Indian coffee is famous for its quality. The Arabica variety was initially brought from Yemen", "Nilgiri hills of Karnataka, Kerala and Tamil Nadu"],
      ["<strong>Cotton</strong>", "Kharif. Black soil of the Deccan plateau. High temperature, light rainfall, 210 frost-free days, bright sunshine. Takes 6–8 months to mature", "Maharashtra, Gujarat, Madhya Pradesh, Karnataka, Andhra Pradesh, Tamil Nadu, Punjab, Haryana"],
      ["<strong>Jute</strong>", "Well-drained fertile soils in the flood plains where soils are renewed every year. High temperature during growth", "West Bengal, Bihar, Assam, Odisha, Meghalaya"],
    ] },
    { t: "sim", id: "india-locator" },
    { t: "note", kind: "exam", title: "Map work", html: "The board asks for <strong>major areas of rice and wheat</strong>, and the <strong>largest or major producer states</strong> of sugarcane, tea, coffee, rubber, cotton and jute. The crops layer in the locator has each one plotted at its leading state." },
    { t: "note", kind: "real", html: "India is the second largest producer of rice in the world after China, and the largest producer and consumer of pulses. Millets are described in the NCERT as coarse grains, but they have <strong>very high nutritional value</strong> — ragi is rich in iron, calcium, other micro nutrients and roughage." },

    { t: "h", text: "Reforms, and where they fell short" },
    { t: "list", items: [
      "After independence, <strong>collectivisation, consolidation of holdings, cooperation and abolition of zamindari</strong> were given priority. The Land Reform Acts were passed but implementation was weak in the absence of political will.",
      "The <strong>Green Revolution</strong> (HYV seeds) and the <strong>White Revolution</strong> (Operation Flood, milk) transformed output — but they were concentrated in a few regions and among the better-off farmers, and left large parts of the country untouched.",
      "Institutional support followed: <strong>Kisan Credit Card (KCC)</strong>, <strong>Personal Accident Insurance Scheme (PAIS)</strong>, crop insurance against natural calamities, minimum support prices, subsidies on inputs, and special weather bulletins for farmers on radio and television.",
    ] },
    { t: "note", kind: "why", title: "Why Indian farmers are under pressure", html: "Since 1990, the reduction in public investment in agriculture, the reduction in import duties on agricultural products, and competition from highly subsidised farmers in developed countries have all squeezed Indian farmers. Subsidy on fertilisers has decreased while power and fertiliser costs rise. Farmers withdrawing investment from agriculture is causing a <strong>downfall in employment</strong> in the sector — which is exactly what the Economics chapter on Sectors describes from the other side." },
    { t: "note", kind: "idea", html: "The chapter's own suggestion: instead of pushing food grains further, farmers could shift to <strong>horticulture, fruits and vegetables, medicinal and aromatic plants, floriculture, bio-diesel crops and organic farming</strong> — which are less water-intensive and fetch higher prices. Gene manipulation and improved seeds also matter, but so does simply making agriculture profitable again." },
  ],
  examFocus: [
    "Four types of farming with distinguishing features and regions.",
    "The three cropping seasons with crops and months — and that sugarcane fits none.",
    "Growing conditions and leading states for rice, wheat, cotton, jute, tea and coffee.",
    "Local names of shifting cultivation — jhumming, bewar, podu, kumari.",
    "Why pulses restore soil fertility, and the exception (arhar).",
    "Institutional and technological reforms, with named schemes.",
    "The effect of globalisation on Indian farmers, and the alternatives suggested.",
    "The crop map-work list.",
  ],
  flashcards: [
    { q: "What is primitive subsistence farming?", a: "Slash and burn agriculture on small patches using primitive tools like the hoe, dao and digging sticks, with family labour. It depends on the monsoon and natural soil fertility; when fertility falls the family moves on." },
    { q: "Give four local names for shifting cultivation in India.", a: "Jhumming in the north-eastern states, bewar or dahiya in Madhya Pradesh, podu or penda in Andhra Pradesh, and kumari in the Western Ghats." },
    { q: "Why do intensive subsistence holdings keep getting smaller?", a: "Because of the right of inheritance, which leads to the division of land between successive generations, making holdings increasingly uneconomical." },
    { q: "What distinguishes plantation agriculture?", a: "A single crop grown over a large area, with capital-intensive inputs and migrant labourers. The produce is used as industrial raw material, so an efficient transport network is essential." },
    { q: "Give the growing conditions for rice.", a: "A kharif crop needing high temperature above 25°C, high humidity, and annual rainfall above 100 cm. In areas of less rainfall it is grown with irrigation from canals and tubewells." },
    { q: "Give the growing conditions for wheat.", a: "A rabi crop needing a cool growing season and bright sunshine at ripening, with 50 to 75 cm of evenly distributed annual rainfall. Grown in the Ganga-Satluj plains and the black soil region of the Deccan." },
    { q: "Why are pulses important for the soil?", a: "Being leguminous crops, all pulses except arhar help restore soil fertility by fixing nitrogen from the air. They are therefore grown in rotation with other crops." },
    { q: "What conditions does cotton need?", a: "Black soil of the Deccan plateau, high temperature, light rainfall or irrigation, 210 frost-free days and bright sunshine. It takes six to eight months to mature." },
    { q: "Where is jute grown and why there?", a: "West Bengal, Bihar, Assam, Odisha and Meghalaya — on well-drained fertile soils in the flood plains, where soils are renewed every year, with high temperature during the growing period." },
    { q: "What were the Green and White Revolutions?", a: "The Green Revolution introduced high-yielding variety seeds and modern inputs, transforming food-grain output. The White Revolution, or Operation Flood, transformed milk production. Both were concentrated in a few regions." },
    { q: "Name three institutional supports provided to Indian farmers.", a: "The Kisan Credit Card, the Personal Accident Insurance Scheme, crop insurance against natural calamities, minimum support prices, and special weather bulletins for farmers on radio and television." },
    { q: "How has globalisation put pressure on Indian farmers?", a: "Reduced public investment in agriculture, reduced import duties on agricultural products, and competition from heavily subsidised farmers in developed countries — alongside rising input costs as subsidies fall." },
  ],
  quiz: [
    { q: "Jhumming is a name for:", options: ["Plantation farming", "Shifting cultivation", "Intensive subsistence farming", "Commercial farming"], answer: 1, why: "Jhumming is the north-eastern name for slash and burn shifting cultivation. Other names include bewar, podu and kumari." },
    { q: "Which crop does not belong to any of the three cropping seasons?", options: ["Wheat", "Rice", "Sugarcane", "Bajra"], answer: 2, why: "Sugarcane takes almost a year to grow, so it does not fit the rabi, kharif or zaid pattern." },
    { q: "Rice is a ______ crop.", options: ["Rabi", "Kharif", "Zaid", "Plantation"], answer: 1, why: "Rice is sown with the onset of the monsoon in June-July and harvested in September-October." },
    { q: "Cotton grows best in:", options: ["Alluvial soil", "Black soil", "Laterite soil", "Arid soil"], answer: 1, why: "Cotton requires the black soil of the Deccan plateau, along with high temperature and bright sunshine." },
    { q: "Which pulse does NOT fix nitrogen in the soil?", options: ["Gram", "Moong", "Arhar", "Urad"], answer: 2, why: "All pulses except arhar are leguminous and help restore soil fertility by fixing nitrogen from the air." },
    { q: "The leading producer of tea in India is:", options: ["Kerala", "Assam", "Karnataka", "West Bengal"], answer: 1, why: "Assam is the leading tea-producing state, followed by the hills of Darjeeling and Jalpaiguri in West Bengal." },
    { q: "The Arabica variety of coffee was initially brought from:", options: ["Brazil", "Yemen", "Ethiopia", "Sri Lanka"], answer: 1, why: "Indian coffee production began with the Arabica variety initially brought from Yemen, and is grown in the Nilgiri hills." },
    { q: "Ragi is particularly rich in:", options: ["Protein only", "Iron, calcium, micro nutrients and roughage", "Fat", "Vitamin C"], answer: 1, why: "Though classed as a coarse grain, ragi has very high nutritional value — rich in iron, calcium, other micro nutrients and roughage." },
    { q: "Maize is grown as a rabi crop in:", options: ["Punjab", "Bihar", "Kerala", "Assam"], answer: 1, why: "Maize is generally a kharif crop, but in Bihar it is grown as a rabi crop." },
    { q: "Which of these is a plantation crop?", options: ["Wheat", "Bajra", "Rubber", "Gram"], answer: 2, why: "Rubber, like tea and coffee, is a plantation crop — a single crop on a large area with capital-intensive inputs and migrant labour." },
  ],
};
