import type { Chapter } from "@/lib/types";

export const ch10: Chapter = {
  slug: "minerals-and-energy-resources",
  num: 5,
  title: "Minerals and Energy Resources",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 18,
  blurb: "Everything you use started as a rock or a fuel someone dug up. This chapter is about where those come from in India, and what running out would mean.",
  bigIdea: "Minerals take millions of years to form and are consumed in decades. That mismatch is the whole conservation argument.",
  syllabus: [
    "What is a mineral, and modes of occurrence",
    "Ferrous and non-ferrous minerals, non-metallic minerals, rock minerals",
    "Conservation of minerals",
    "Conventional and non-conventional sources of energy",
    "Map work: iron ore mines, coal mines, oil fields, power plants",
  ],
  blocks: [
    { t: "h", text: "What a mineral is, and where it sits" },
    { t: "p", html: "A mineral is a <strong>homogenous, naturally occurring substance with a definable internal structure</strong>. Geologists define it by chemical and physical properties; geographers care about distribution and use. Minerals are found in <em>ores</em> — an accumulation of any mineral mixed with other elements." },
    { t: "table", head: ["Mode of occurrence", "How it forms", "Examples"], rows: [
      ["<strong>Veins and lodes</strong>", "In cracks, crevices, faults and joints of igneous and metamorphic rocks. Molten or gaseous forms are forced upward and cool and solidify. Smaller occurrences are veins, larger ones are lodes", "Tin, copper, zinc, lead"],
      ["<strong>Beds and layers</strong>", "In sedimentary rocks, formed as a result of deposition, accumulation and concentration in horizontal strata", "Coal, iron ore, gypsum, potash salt, sodium salt"],
      ["<strong>Decomposition of surface rocks</strong>", "Soluble constituents are removed by weathering, leaving a residual mass of weathered material", "Bauxite"],
      ["<strong>Alluvial deposits (placer deposits)</strong>", "In sands of valley floors and the base of hills. Generally contain minerals that are <strong>not corroded by water</strong>", "Gold, silver, tin, platinum"],
      ["<strong>Ocean waters</strong>", "Most are too widely diffused to be significant, but some are extracted", "Common salt, magnesium, bromine. Ocean beds are rich in manganese nodules"],
    ] },
    { t: "note", kind: "trap", html: "Placer deposits contain minerals that are <strong>not corroded by water</strong> — that clause is the mark. Gold, silver, tin and platinum survive being washed down a river; iron would not." },

    { t: "h", text: "Ferrous, non-ferrous, non-metallic" },
    { t: "table", head: ["Mineral", "Key facts", "Where"], rows: [
      ["<strong>Iron ore</strong> (ferrous)", "The basic mineral and the backbone of industrial development. <strong>Magnetite</strong> is the finest, with up to 70% iron, and has excellent magnetic qualities. <strong>Haematite</strong> is the most important industrially, with 50–60% iron", "Odisha–Jharkhand belt, Durg–Bastar–Chandrapur belt, Bellary–Chitradurga–Chikkamagaluru–Tumakuru belt, Maharashtra–Goa belt"],
      ["<strong>Manganese</strong> (ferrous)", "Used in manufacturing steel and ferro-manganese alloy. Nearly <strong>10 kg of manganese is required to manufacture one tonne of steel</strong>. Also used in bleaching powder, insecticides and paints", "Odisha is the largest producer"],
      ["<strong>Copper</strong> (non-ferrous)", "Malleable, ductile and a good conductor. Used mainly in electrical cables, electronics and chemical industries", "Balaghat (MP), Khetri (Rajasthan), Singhbhum (Jharkhand)"],
      ["<strong>Bauxite</strong> (non-ferrous)", "The ore from which aluminium is obtained. Aluminium combines the strength of metals with extreme lightness and good conductivity", "Odisha is the largest producer — Panchpatmali deposits in Koraput district"],
      ["<strong>Mica</strong> (non-metallic)", "Splits easily into thin sheets, can be clear, black, green, red, yellow or brown. Because of excellent <strong>di-electric strength, low power loss factor, insulating properties and resistance to high voltage</strong>, it is indispensable in electric and electronic industries", "Chota Nagpur plateau, Koderma–Gaya–Hazaribagh belt of Jharkhand, Rajasthan around Ajmer, Nellore in Andhra Pradesh"],
      ["<strong>Limestone</strong> (rock mineral)", "Found in sedimentary rocks. The basic raw material for the <strong>cement industry</strong> and essential for smelting iron ore in the blast furnace", "Widely distributed in sedimentary rock regions"],
    ] },
    { t: "note", kind: "exam", title: "Map work", html: "Iron ore mines: <strong>Mayurbhanj, Durg, Bailadila, Bellary, Kudremukh</strong>. Coal mines: <strong>Raniganj, Bokaro, Talcher, Neyveli</strong>. Oil fields: <strong>Digboi, Naharkatiya, Mumbai High, Bassien, Kalol, Ankleshwar</strong>. Use the minerals layer in the locator to place them." },
    { t: "sim", id: "india-locator" },

    { t: "h", text: "The cost of mining" },
    { t: "note", kind: "why", html: "Mining is called a <strong>killer industry</strong> for a reason. Inhaling dust makes miners vulnerable to pulmonary diseases; there is the constant risk of collapsing mine roofs, inundation and fires; water sources in the region get contaminated; and dumping of waste and slurry degrades land and soil." },
    { t: "note", kind: "idea", html: "Conservation is not optional. The total volume of workable mineral deposits is <strong>one per cent of the earth's crust</strong>. Minerals take millions of years to be created and concentrated; the rate of replenishment is infinitely small compared with the rate of consumption. Recycling metals, using scrap and looking for substitutes are the practical answers." },

    { t: "h", text: "Energy: conventional and non-conventional" },
    { t: "sim", id: "energy-mix" },
    { t: "table", head: ["Source", "What to know"], rows: [
      ["<strong>Coal</strong>", "India's most abundant fossil fuel, providing a substantial part of the nation's energy needs. Formed by compression of plant material over millions of years. Grades by degree of compression: <strong>peat</strong> (low carbon, high moisture, low heating capacity), <strong>lignite</strong> (low grade brown coal, soft, high moisture — Neyveli in Tamil Nadu), <strong>bituminous</strong> (most popular for commercial use, formed by great depth and high temperature; metallurgical coal is high grade bituminous, used in smelting iron), <strong>anthracite</strong> (the highest quality hard coal)"],
      ["<strong>Petroleum</strong>", "Provides fuel for heat and lighting, lubricants for machinery, and raw materials for petrochemical industries. Occurs in anticlines and fault traps, in the zones between porous and non-porous rocks. About 63% of India's petroleum production is from Mumbai High, 18% from Gujarat and 16% from Assam. <strong>Digboi</strong> is the oldest oil field"],
      ["<strong>Natural gas</strong>", "An important clean energy resource found alongside or without petroleum. Used both as a source of energy and as an industrial raw material in petrochemicals. Low carbon dioxide emissions, so it is the <strong>environment-friendly fuel</strong>. The Krishna-Godavari basin has large reserves. The 1,700 km <strong>Hazira–Vijaipur–Jagdishpur (HVJ) pipeline</strong> links Mumbai High and Bassien with the fertiliser, power and industrial complexes of western and northern India"],
      ["<strong>Electricity</strong>", "Generated mainly in two ways: <strong>hydro electricity</strong> from fast-flowing water, and <strong>thermal electricity</strong> by burning coal, petroleum and natural gas. Thermal uses non-renewable fossil fuels; hydro is renewable"],
    ] },
    { t: "note", kind: "real", title: "Non-conventional sources", html: "<strong>Nuclear</strong> — from altering the structure of atoms; uranium and thorium in Jharkhand and the Aravalli ranges of Rajasthan, and the monazite sands of Kerala are rich in thorium.<br><strong>Solar</strong> — India is a tropical country with enormous potential. The largest solar plant of India is located at <strong>Madhapur, near Bhuj</strong>, where solar energy is used to sterilise milk cans.<br><strong>Wind</strong> — India is the largest wind energy farm cluster in Nagarcoil and Jaisalmer. Nagarcoil and Jaisalmer are well known for effective use of wind energy.<br><strong>Biogas</strong> — shrubs, farm waste, animal and human waste are used to produce biogas for domestic consumption. Biogas plants using cattle dung are known as <strong>gobar gas plants</strong> in rural India. They give twin benefits — energy, and improved manure quality.<br><strong>Tidal</strong> — the Gulf of Khambhat and the Gulf of Kachchh in Gujarat, and the Gangetic delta in the Sunderban region, provide ideal conditions.<br><strong>Geothermal</strong> — two experimental projects: the Parvati valley near Manikaran in Himachal Pradesh, and the Puga Valley in Ladakh." },
    { t: "note", kind: "trap", html: "Non-conventional does not mean the same as renewable in every case — <strong>nuclear energy is non-conventional but not renewable</strong>. Read the question carefully." },
  ],
  examFocus: [
    "Definition of a mineral, and the five modes of occurrence with examples.",
    "Why placer deposits contain only non-corrodible minerals.",
    "Magnetite versus haematite — iron content and why each matters.",
    "Manganese: 10 kg per tonne of steel.",
    "Why mica is indispensable to the electronics industry — the four properties.",
    "Why mining is called a killer industry.",
    "The four grades of coal in order.",
    "The HVJ pipeline and what it connects.",
    "Non-conventional sources with one named Indian site each.",
    "The map-work list of mines, oil fields and power plants.",
  ],
  flashcards: [
    { q: "Define a mineral.", a: "A homogenous, naturally occurring substance with a definable internal structure. Minerals are found in ores — an accumulation of a mineral mixed with other elements." },
    { q: "What are veins and lodes?", a: "Minerals formed in cracks, crevices, faults or joints of igneous and metamorphic rocks, where molten or gaseous forms are forced upward and solidify. Smaller occurrences are veins, larger ones lodes. Tin, copper, zinc and lead occur this way." },
    { q: "What are placer deposits and what do they contain?", a: "Alluvial deposits in the sands of valley floors and at the base of hills. They generally contain minerals not corroded by water — gold, silver, tin and platinum." },
    { q: "Compare magnetite and haematite.", a: "Magnetite is the finest iron ore, with up to 70% iron content and excellent magnetic qualities. Haematite is the most important industrially, with 50 to 60% iron content." },
    { q: "How much manganese is needed per tonne of steel?", a: "Nearly 10 kg. Manganese is also used to make ferro-manganese alloy, bleaching powder, insecticides and paints." },
    { q: "Why is mica indispensable to electronics?", a: "Because of its excellent di-electric strength, low power loss factor, insulating properties and resistance to high voltage." },
    { q: "Why is mining called a killer industry?", a: "Miners inhale dust and become vulnerable to pulmonary disease; there is risk of collapsing roofs, inundation and fire; water sources get contaminated; and waste and slurry dumping degrades land and soil." },
    { q: "Name the four grades of coal in order of quality.", a: "Peat — low carbon, high moisture, low heating capacity. Lignite — low grade brown coal, soft with high moisture. Bituminous — the most popular commercial grade. Anthracite — the highest quality hard coal." },
    { q: "Where does India's petroleum come from?", a: "About 63% from Mumbai High, 18% from Gujarat and 16% from Assam. Digboi in Assam is the oldest oil field in the country." },
    { q: "What is the HVJ pipeline?", a: "The 1,700 km Hazira–Vijaipur–Jagdishpur pipeline, linking Mumbai High and Bassien with the fertiliser, power and industrial complexes of western and northern India." },
    { q: "Where is India's largest solar plant and what does it do?", a: "At Madhapur near Bhuj, where solar energy is used to sterilise milk cans." },
    { q: "What are gobar gas plants and what are their twin benefits?", a: "Biogas plants using cattle dung, common in rural India. They provide energy and at the same time improve the quality of manure." },
  ],
  quiz: [
    { q: "Which of these is found as a placer deposit?", options: ["Coal", "Bauxite", "Gold", "Iron ore"], answer: 2, why: "Placer deposits form in valley sands and contain minerals not corroded by water — gold, silver, tin and platinum." },
    { q: "Bauxite is formed by:", options: ["Deposition in sedimentary layers", "Decomposition of surface rocks leaving a residual mass", "Cooling of molten rock in cracks", "Evaporation of sea water"], answer: 1, why: "Weathering removes the soluble constituents of surface rocks, leaving a residual mass of weathered material from which bauxite forms." },
    { q: "The iron ore with the highest iron content is:", options: ["Haematite", "Magnetite", "Limonite", "Siderite"], answer: 1, why: "Magnetite contains up to 70% iron and has excellent magnetic qualities." },
    { q: "Manganese is chiefly used in:", options: ["Making cement", "Manufacturing steel and ferro-manganese alloy", "Electrical cables", "Aircraft bodies"], answer: 1, why: "About 10 kg of manganese is needed per tonne of steel; it also goes into bleaching powder, insecticides and paints." },
    { q: "The largest producer of bauxite in India is:", options: ["Jharkhand", "Odisha", "Gujarat", "Rajasthan"], answer: 1, why: "Odisha is the largest bauxite producer, with the Panchpatmali deposits in Koraput district." },
    { q: "Lignite is mined at:", options: ["Raniganj", "Neyveli", "Bokaro", "Talcher"], answer: 1, why: "Neyveli in Tamil Nadu has large lignite reserves, used to generate thermal electricity." },
    { q: "Most of India's petroleum comes from:", options: ["Assam", "Gujarat", "Mumbai High", "Krishna-Godavari"], answer: 2, why: "About 63% of India's petroleum production is from Mumbai High." },
    { q: "Which is described as the environment-friendly fuel?", options: ["Coal", "Petroleum", "Natural gas", "Lignite"], answer: 2, why: "Natural gas has low carbon dioxide emissions and is therefore the environment-friendly fuel." },
    { q: "Monazite sands rich in thorium are found in:", options: ["Kerala", "Rajasthan", "Jharkhand", "Odisha"], answer: 0, why: "The monazite sands of Kerala are rich in thorium, used for nuclear energy." },
    { q: "Which non-conventional source is NOT renewable?", options: ["Solar", "Wind", "Nuclear", "Tidal"], answer: 2, why: "Nuclear energy is non-conventional but uses uranium and thorium, which are exhaustible." },
  ],
  keyTopics: [
    { name: "Conservation of minerals — why, and measures", importance: "high", note: "A recurring 3–5 mark 'why/suggest measures' question; the one-per-cent-of-the-crust fact is the hook." },
    { name: "Conventional vs non-conventional sources of energy", importance: "high", note: "Standard 'distinguish' 2–3 marker, and the base of most assertion–reason items in this chapter." },
    { name: "Ferrous and non-ferrous minerals — iron ore, manganese, copper, bauxite", importance: "high", note: "Magnetite vs haematite and the 10 kg-manganese-per-tonne fact are asked almost every year." },
    { name: "Mining hazards — 'a killer industry'", importance: "high", note: "3-mark 'explain the ill-effects of mining' question, often paired with the conservation answer." },
    { name: "Modes of occurrence of minerals", importance: "medium", note: "Placer deposits and the non-corrodible clause are a favourite trap." },
    { name: "Non-conventional sources — one named site each", importance: "medium", note: "Solar (Bhuj), wind (Nagarcoil/Jaisalmer), nuclear (Jharkhand, Aravallis, Kerala), tidal (Khambhat/Kachchh), geothermal (Manikaran, Puga)." },
    { name: "Coal grades and petroleum distribution", importance: "medium", note: "Peat→lignite→bituminous→anthracite sequence; Mumbai High share of production." },
    { name: "Map work — mines, oil fields, power plants", importance: "high", note: "Guaranteed marks in the map-based question; learn the locator list exactly." },
  ],
  written: [
    { q: "What is a mineral?", marks: 1, kind: "short", importance: "medium",
      answer: "A mineral is a <strong>homogenous, naturally occurring substance with a definable internal structure</strong>. Minerals occur in <em>ores</em> — an accumulation of a mineral mixed with other elements." },
    { q: "Name one non-conventional source of energy that is not renewable.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Nuclear energy.</strong> It is non-conventional but depends on uranium and thorium, which are exhaustible mineral reserves — so it is not renewable." },
    { q: "Distinguish between conventional and non-conventional sources of energy.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Conventional sources</strong> — coal, petroleum, natural gas, and hydro and thermal electricity generated from them. Mostly non-renewable (except hydro), have been in long-established use, and are the main cause of pollution. <strong>Non-conventional sources</strong> — solar, wind, tidal, biogas, geothermal and nuclear. Mostly renewable (nuclear is the exception), cleaner, and only recently exploited on a large scale." },
    { q: "Why is copper mainly used in making electrical cables and equipment?", marks: 2, kind: "short", importance: "medium",
      answer: "Copper is <strong>malleable, ductile and a very good conductor</strong> of electricity, so it can be drawn into wires without breaking and carries current with low loss. It is therefore essential in electrical cables, electronics and chemical industries." },
    { q: "What are placer deposits? Name two minerals commonly found in them.", marks: 2, kind: "short", importance: "medium",
      answer: "Placer deposits are <strong>alluvial deposits found in the sands of valley floors and at the base of hills</strong>. They generally contain minerals that are <strong>not corroded by water</strong> — for example <strong>gold and platinum</strong> (also silver and tin)." },
    { q: "Why should minerals be conserved? Suggest any three measures of conservation.", marks: 3, kind: "long", importance: "high",
      answer: "Minerals need to be conserved because <strong>the total volume of workable mineral deposits is barely one per cent of the earth's crust</strong>, they take millions of years to form and concentrate, and the rate at which they are being consumed is far greater than the rate at which new deposits can form.<br>Measures of conservation:<ul><li>Use <strong>improved and appropriate technology</strong> so a smaller quantity of mineral achieves the same output.</li><li><strong>Recycle scrap metals</strong> and use them again instead of mining fresh ore.</li><li>Substitute exhausted or costly minerals with <strong>alternative and renewable materials</strong> wherever possible.</li></ul>" },
    { q: "Distinguish between ferrous and non-ferrous minerals, giving two examples of each.", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Ferrous minerals</strong> contain iron and account for about three-fourths of the total value of metallic mineral production in India — for example <strong>iron ore and manganese</strong>. They form the basis of the iron and steel industry.<br><strong>Non-ferrous minerals</strong> do not contain iron — for example <strong>copper and bauxite</strong>. India's reserves and production of these are not as satisfactory as those of ferrous minerals, but they are vital for electrical, electronic and aluminium industries." },
    { q: "Explain any three ill-effects of mining on the health of miners and on the environment.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>Miners <strong>inhale poisonous dust and gases</strong> continuously, which makes them vulnerable to serious pulmonary diseases.</li><li>There is a constant danger of <strong>collapsing mine roofs, flooding and fires</strong> in underground mines.</li><li><strong>Water sources in the region get contaminated</strong>, and the dumping of waste and slurry degrades the surrounding land and soil, turning agricultural and forest land into wasteland.</li></ul>This is why mining is often called a <strong>killer industry</strong>." },
    { q: "Describe the distribution of iron ore in India, and explain why it is regarded as the basic mineral of industrial development.", marks: 5, kind: "long", importance: "high",
      answer: "Iron ore is called the basic mineral because it is the backbone of modern industry — used to manufacture machinery, tools, transport equipment and construction material. India has fairly abundant reserves, occurring mainly in four belts:<ul><li>The <strong>Odisha–Jharkhand belt</strong>, in Mayurbhanj and Kendujhar (Odisha) and Singhbhum (Jharkhand).</li><li>The <strong>Durg–Bastar–Chandrapur belt</strong> along the Maharashtra–Madhya Pradesh border, including Bailadila.</li><li>The <strong>Bellary–Chitradurga–Chikkamagaluru–Tumakuru belt</strong> in Karnataka, which has high-grade haematite.</li><li>The <strong>Maharashtra–Goa belt</strong>, including the Ratnagiri district, whose ore is exported through Marmagao port.</li></ul>Iron ore occurs as <strong>magnetite</strong> (up to 70% iron, excellent magnetic quality) and <strong>haematite</strong> (50–60% iron, industrially the most important)." },
    { q: "Distinguish between conventional and non-conventional sources of energy, and describe any three non-conventional sources used in India.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Conventional sources</strong> (coal, petroleum, natural gas, hydro/thermal electricity) are mostly non-renewable and have been used for a long time; <strong>non-conventional sources</strong> (solar, wind, tidal, biogas, geothermal, nuclear) are newer and mostly renewable.<ul><li><strong>Solar energy</strong> — India, being a tropical country, has enormous potential; the country's largest solar plant is at <strong>Madhapur, near Bhuj</strong>, where it is used to sterilise milk cans.</li><li><strong>Wind energy</strong> — India has the largest wind energy farm clusters at <strong>Nagarcoil and Jaisalmer</strong>.</li><li><strong>Biogas</strong> — produced from shrubs, farm waste and animal/human waste; cattle-dung plants are called <strong>gobar gas plants</strong> and give the twin benefit of energy plus improved manure.</li></ul>" },
    { q: "Why is jute concentrated in West Bengal, and what step has the government taken to help jute farmers?", marks: 2, kind: "short", importance: "medium",
      answer: "This is actually a manufacturing-chapter fact worth remembering alongside minerals: jute mills cluster along the Hugli in West Bengal for cheap water transport, abundant water for processing and easy access to labour and the port of Kolkata. The <strong>National Jute Policy of 2005</strong> aims to increase productivity, improve quality and ensure fair prices to jute farmers." },
  ],
  assertionReason: [
    { assertion: "Magnetite is considered the finest quality of iron ore.",
      reason: "Magnetite contains up to 70% iron content and possesses excellent magnetic qualities.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the high iron content with magnetic properties is exactly why magnetite is rated the finest ore — R correctly explains A." },
    { assertion: "Mining is often described as a 'killer industry'.",
      reason: "Miners inhale poisonous dust that makes them vulnerable to pulmonary diseases, and face the constant risk of collapsing mine roofs, inundation and fires.",
      answer: 0, importance: "high",
      why: "Both are true, and the health and safety hazards listed in R are precisely why mining earns the label in A." },
    { assertion: "Nuclear energy is classified as a non-conventional source of energy.",
      reason: "Nuclear energy is a renewable source because it can be produced indefinitely from ordinary water.",
      answer: 2, importance: "high",
      why: "A is true — nuclear is grouped with the non-conventional sources. But R is false: nuclear energy depends on exhaustible radioactive minerals (uranium, thorium), so it is non-renewable, not renewable." },
    { assertion: "Natural gas is considered an environment-friendly fuel.",
      reason: "Natural gas has very low carbon dioxide emissions compared to coal and petroleum when burnt.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the low carbon dioxide emission in R is exactly the reason natural gas earns the 'environment-friendly' label in A." },
  ],
  caseStudies: [
    { title: "Why conservation cannot wait", importance: "high",
      source: "Read the passage and answer the questions that follow: minerals are formed by slow geological processes that take millions of years, but modern industry can exhaust a rich deposit within a few decades of continuous mining. Geologists estimate that the total volume of workable mineral deposits is barely one per cent of the earth's crust, and once a deposit is exhausted it cannot be replenished within a human lifetime.",
      parts: [
        { q: "Why is there a mismatch between the rate of formation and the rate of consumption of minerals?", marks: 1, answer: "Minerals take millions of years to form and concentrate through geological processes, but modern mining and industry consume them within a few decades — a pace geology cannot match." },
        { q: "Suggest any two measures for conserving mineral resources.", marks: 2, answer: "<strong>(i)</strong> Recycling and reusing scrap metal instead of mining fresh ore. <strong>(ii)</strong> Adopting improved technology that uses minerals more efficiently, and using substitutes where possible." },
        { q: "Name one practical alternative industries increasingly rely on instead of mining new ore.", marks: 1, answer: "Using <strong>scrap metal</strong> (recycled metal) in place of freshly mined ore." },
        { q: "Give one reason why mining is considered harmful even where conservation measures are followed.", marks: 1, answer: "Mining still exposes workers to dust and the risk of roof collapse, inundation and fire, and mining waste and slurry continue to degrade land, soil and water in the surrounding area." },
      ] },
    { title: "Classifying India's energy sources", importance: "medium",
      source: "Study the table of energy sources and their well-known Indian locations, and answer the questions:<br><table><thead><tr><th>Source</th><th>Example location in India</th></tr></thead><tbody><tr><td>A</td><td>Neyveli (Tamil Nadu)</td></tr><tr><td>B</td><td>Madhapur, near Bhuj (Gujarat)</td></tr><tr><td>C</td><td>Nagarcoil and Jaisalmer</td></tr><tr><td>D</td><td>Jharkhand and the Aravalli ranges</td></tr></tbody></table>",
      parts: [
        { q: "Identify energy sources A, B, C and D.", marks: 2, answer: "A = <strong>lignite (coal)</strong>, mined at Neyveli. B = <strong>solar energy</strong>. C = <strong>wind energy</strong>. D = <strong>nuclear energy</strong> (uranium and thorium)." },
        { q: "Classify A, B, C and D into conventional and non-conventional sources.", marks: 1, answer: "<strong>Conventional:</strong> A (lignite/coal). <strong>Non-conventional:</strong> B (solar), C (wind), D (nuclear)." },
        { q: "Which of B, C or D is non-conventional but NOT renewable? Justify.", marks: 1, answer: "<strong>D — nuclear energy.</strong> Although grouped with the non-conventional sources, it depends on exhaustible radioactive minerals such as uranium and thorium, so it cannot be classed as renewable." },
        { q: "Name one environmental concern associated with expanding source A.", marks: 1, answer: "Coal and lignite mining causes land and water contamination and is a major contributor to air pollution when burnt — and being a fossil fuel, its reserves are non-renewable." },
      ] },
  ],
};
