import type { Chapter } from "@/lib/types";

export const ch11: Chapter = {
  slug: "manufacturing-industries",
  num: 6,
  title: "Manufacturing Industries",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · 20 marks · includes map work",
  minutes: 20,
  blurb: "Why a steel plant sits where it sits, why the cotton mills clustered in Mumbai, and why all of it is now an environmental problem too.",
  bigIdea: "Industry does not choose a location by accident. It goes where the cost of raw material, power, labour, market and transport add up to the least.",
  syllabus: [
    "Importance of manufacturing and industrial location",
    "Classification of industries",
    "Agro-based industries: textile, sugar",
    "Mineral-based industries: iron and steel, aluminium smelting, chemical, fertiliser, cement",
    "Automobile and information technology industries",
    "Industrial pollution and environmental degradation, and control measures",
    "Map work: major industrial centres and steel plants",
  ],
  blocks: [
    { t: "h", text: "Why manufacturing matters" },
    { t: "p", html: "Manufacturing is the <strong>production of goods in large quantities after processing from raw materials to more valuable products</strong>. The economic strength of a country is measured by the development of its manufacturing industries. Manufacturing is considered the <strong>backbone of development</strong> because it reduces dependence on agriculture by providing jobs in secondary and tertiary sectors, helps eradicate unemployment and poverty, brings in foreign exchange through exports, and transforms raw material into finished goods of higher value." },
    { t: "note", kind: "idea", html: "Agriculture and industry are not separate worlds. Agro-industries have raised agricultural productivity by supplying irrigation pumps, fertilisers, insecticides, machines and tools; industry in turn depends on agriculture for raw material. The chapter calls this <strong>interdependence</strong>." },

    { t: "h", text: "Where industries locate" },
    { t: "sim", id: "industry-location" },
    { t: "p", html: "The ideal location is where the <strong>cost of production and delivery to the market is the lowest</strong>. Availability of raw material, labour, capital, power and market all matter. Cities offer markets, banking, insurance, transport, labour and consultants — so industries cluster in and around them. When several industries locate together and share these benefits, that is <strong>agglomeration economies</strong>." },

    { t: "h", text: "Classifying industries" },
    { t: "table", head: ["Basis", "Types"], rows: [
      ["Source of raw materials", "<strong>Agro-based</strong> — cotton, woollen, jute, silk textile, rubber, sugar, tea, coffee, edible oil. <strong>Mineral-based</strong> — iron and steel, cement, aluminium, machine tools, petrochemicals"],
      ["Main role", "<strong>Basic or key industries</strong> supply raw materials to other industries — iron and steel, copper smelting, aluminium smelting. <strong>Consumer industries</strong> produce goods for direct use — sugar, toothpaste, paper, sewing machines, fans"],
      ["Capital investment", "<strong>Small scale</strong> — investment up to the prescribed ceiling. <strong>Large scale</strong> — above it"],
      ["Ownership", "<strong>Public sector</strong> (BHEL, SAIL), <strong>private sector</strong> (TISCO, Bajaj Auto, Dabur), <strong>joint sector</strong> (Oil India Ltd), <strong>cooperative sector</strong> (Amul, the sugar mills of Maharashtra, the coir industry of Kerala)"],
      ["Bulk and weight of material and product", "<strong>Heavy industries</strong> — iron and steel. <strong>Light industries</strong> — electrical goods"],
    ] },

    { t: "h", text: "Agro-based industries" },
    { t: "list", items: [
      "<strong>Cotton textiles.</strong> In ancient India cotton textiles were produced with hand spinning and handloom weaving. The first successful mill was established in <strong>Mumbai in 1854</strong>. Mumbai and Ahmedabad became early centres because of the black cotton soil of the hinterland, port facilities, a moist climate, capital and available labour. Today the industry is spread across the country. It supports the largest number of people after agriculture, and provides employment across a whole chain — farming, ginning, spinning, weaving, dyeing, designing, packaging, tailoring and sewing. India has a large share of world loomage but the <strong>weaving sector is fragmented</strong>, so much yarn is exported rather than woven at home.",
      "<strong>Jute textiles.</strong> India is the largest producer of raw jute and jute goods and stands second as an exporter after Bangladesh. Most mills are in West Bengal, in a narrow belt along the banks of the Hugli. The first jute mill was set up near Kolkata at <strong>Rishra in 1855</strong>. Location factors: proximity to the jute-producing areas, inexpensive water transport, a network of railways, roadways and waterways, abundant water for processing, cheap labour from West Bengal, Bihar, Odisha and Uttar Pradesh, and Kolkata as a port with banking and insurance. The <strong>National Jute Policy of 2005</strong> aimed to increase productivity, improve quality and ensure good prices to farmers.",
      "<strong>Sugar.</strong> India is the second largest producer of sugar and the largest producer of gur and khandsari. About 60% of mills are in Uttar Pradesh and Bihar, but the industry is shifting to Maharashtra and the south because the cane there has a <strong>higher sucrose content</strong>, the cooler climate ensures a longer crushing season, and cooperatives are more successful. Sugarcane is a weight-losing crop that must be crushed quickly, so mills sit inside the cane-growing areas.",
    ] },

    { t: "h", text: "Mineral-based industries" },
    { t: "p", html: "<strong>Iron and steel</strong> is the basic industry — all others depend on it for their machinery. Production and consumption of steel is often regarded as the index of a country's development. It is a heavy industry: all inputs and outputs are bulky and incur heavy transport costs. Iron ore, coking coal and limestone are needed in the ratio of approximately <strong>4 : 2 : 1</strong>, along with manganese. Most plants sit in the Chhotanagpur plateau region because of low-cost iron ore, high-grade raw materials in proximity, cheap labour and a vast home market." },
    { t: "note", kind: "why", title: "Why India is not further ahead in steel", html: "India is the largest producer of sponge iron and among the largest producers of crude steel, yet per capita consumption is only around 100 kg a year. The problems the chapter names: <strong>high costs and limited availability of coking coal, lower productivity of labour, irregular supply of energy, and poor infrastructure</strong>. Liberalisation and foreign direct investment have given a boost, and the industry's future depends on efficient use of energy." },
    { t: "table", head: ["Industry", "Points to remember"], rows: [
      ["<strong>Aluminium smelting</strong>", "The second most important metallurgical industry. Aluminium is light, resistant to corrosion, a good conductor of heat, malleable, and becomes strong when mixed with other metals. It is used for aircraft, utensils and wires, and has replaced steel, copper, zinc and lead in many industries. <strong>Bauxite</strong> — a bulky, dark reddish rock — is the raw material. Regular supply of electricity and an assured source of raw material at minimum cost are the two prime location factors"],
      ["<strong>Chemical</strong>", "Contributes about 3% of GDP and is the third largest in Asia. <strong>Inorganic chemicals</strong> — sulphuric acid (used in fertilisers, synthetic fibres, plastics, adhesives, paints, dyestuffs), nitric acid, alkalies, soda ash (glass, soaps, detergents, paper), caustic soda. <strong>Organic chemicals</strong> — petrochemicals, used for synthetic fibres, synthetic rubber, plastics, dye-stuffs, drugs and pharmaceuticals. Organic chemical plants are located near oil refineries or petrochemical plants. The chemical industry is its own largest consumer"],
      ["<strong>Fertiliser</strong>", "Produces nitrogenous fertilisers (mainly urea), phosphatic fertilisers, and complex fertilisers combining nitrogen, phosphate and potash. India has no commercially usable <strong>potash or potassium compound</strong> reserves, so potash is entirely imported. After the Green Revolution the industry expanded across the country"],
      ["<strong>Cement</strong>", "Essential for construction — houses, factories, bridges, roads, airports, dams. Requires bulky and heavy raw materials: limestone, silica, alumina and gypsum, plus coal, electric power and rail transport. Plants in Gujarat have been located strategically for access to the Gulf markets"],
    ] },
    { t: "note", kind: "exam", title: "Map work", html: "Learn the steel plants: <strong>Durgapur, Bokaro, Bhilai, Jamshedpur, Rourkela, Vijaynagar, Salem</strong>. Also cotton textile centres <strong>Mumbai, Indore, Surat, Kanpur, Coimbatore</strong>, and software technology parks at <strong>Noida, Gandhinagar, Mumbai, Pune, Hyderabad, Bengaluru, Chennai, Thiruvananthapuram</strong>." },
    { t: "sim", id: "india-locator" },

    { t: "h", text: "Automobile and IT" },
    { t: "p", html: "<strong>Automobiles</strong> provide vehicles for quick transport of goods, services and passengers. After liberalisation, new and contemporary models stimulated demand, and foreign direct investment brought in new technology. The industry is located around Delhi, Gurugram, Mumbai, Pune, Chennai, Kolkata, Lucknow, Indore, Hyderabad, Jamshedpur and Bengaluru." },
    { t: "p", html: "The <strong>IT and electronics industry</strong> covers everything from transistor sets to televisions, telephones, cellular telecom, pagers, telephone exchanges, radars and computers. <strong>Bengaluru</strong> is the electronic capital of India. Its major impact has been on employment generation, and a distinct feature is the <strong>large number of women employed</strong> — up to 30% of the workforce. Continuing growth in hardware and software is the key to the success of IT in India." },

    { t: "h", text: "Industrial pollution" },
    { t: "table", head: ["Type", "Cause"], rows: [
      ["<strong>Air pollution</strong>", "Undesirable gases like sulphur dioxide and carbon monoxide, airborne particulate materials, dust, sprays, mist and smoke. Chemical and paper factories, brick kilns, refineries and smelting plants, and the burning of fossil fuels in factories that ignore norms. Toxic gas leaks can be immediately disastrous"],
      ["<strong>Water pollution</strong>", "Organic and inorganic industrial wastes and effluents. The main culprits are paper, pulp, chemical, textile and dyeing, petroleum refineries, tanneries and electroplating industries, which discharge dyes, detergents, acids, salts, lead, mercury, pesticides, fertilisers, rubber and plastics into rivers. Fly ash, phosphor gypsum and iron and steel slags are the main solid wastes"],
      ["<strong>Thermal pollution</strong>", "When hot water from factories and thermal plants is drained into rivers and ponds before cooling. Nuclear plants add radioactive waste, causing cancer, birth defects and miscarriages"],
      ["<strong>Noise pollution</strong>", "Industrial and construction activity, machinery, factory equipment, generators, saws and pneumatic drills. Causes irritation, anger, hearing impairment, increased heart rate and blood pressure"],
    ] },
    { t: "note", kind: "idea", title: "What can be done", html: "Minimise water use by reusing and recycling it in two or more successive stages. Harvest rainwater to meet water requirements. Treat hot water and effluents before releasing them, in three phases: <strong>primary</strong> treatment by mechanical means (screening, grinding, flocculation, sedimentation), <strong>secondary</strong> by biological process, and <strong>tertiary</strong> by biological, chemical and physical processes including recycling. Overdrawing of groundwater should be regulated by law. Particulate matter can be reduced by fitting <strong>smoke stacks with electrostatic precipitators, fabric filters, scrubbers and inertial separators</strong>. Machinery can be redesigned, generators fitted with silencers, and earplugs or earphones used." },
    { t: "note", kind: "real", html: "<strong>NTPC</strong> is cited as a power-generating company taking a proactive approach: optimum utilisation of equipment with minimum waste, ash pond management and ash water recycling, ecological monitoring and reviews, and afforestation programmes." },
  ],
  examFocus: [
    "Why manufacturing is called the backbone of development.",
    "Agglomeration economies, and the factors behind industrial location.",
    "Five bases of classification with examples for each.",
    "Cotton textiles: Mumbai 1854, why Mumbai and Ahmedabad, and the weaving-sector weakness.",
    "Jute: Rishra 1855, the location factors along the Hugli, and the National Jute Policy 2005.",
    "Why the sugar industry is shifting to Maharashtra and the south.",
    "Iron and steel: the 4:2:1 ratio, why the Chhotanagpur plateau, and the four problems.",
    "Why India imports all its potash.",
    "The four kinds of industrial pollution and the control measures, including the three treatment phases.",
    "Map work: steel plants, cotton textile centres, software technology parks.",
  ],
  flashcards: [
    { q: "Define manufacturing.", a: "The production of goods in large quantities after processing raw materials into more valuable products." },
    { q: "Why is manufacturing called the backbone of development?", a: "It reduces dependence on agriculture by creating secondary and tertiary jobs, helps eradicate unemployment and poverty, brings foreign exchange through exports, and turns raw material into higher-value finished goods." },
    { q: "What are agglomeration economies?", a: "The benefits industries gain by locating together in and around a large city, sharing its market, banking, insurance, transport, labour and consultancy services." },
    { q: "Where and when was the first successful cotton textile mill established?", a: "Mumbai, in 1854. Mumbai and Ahmedabad grew as centres because of black cotton soil in the hinterland, port facilities, a moist climate, capital and available labour." },
    { q: "Where was India's first jute mill and when?", a: "At Rishra near Kolkata in 1855. Most jute mills are still in a narrow belt along the banks of the Hugli in West Bengal." },
    { q: "Why is the sugar industry shifting to Maharashtra and the south?", a: "The cane there has a higher sucrose content, the cooler climate gives a longer crushing season, and cooperative sugar mills are more successful in those states." },
    { q: "In what ratio are iron ore, coking coal and limestone required for steel?", a: "Approximately 4 : 2 : 1, along with manganese." },
    { q: "Name four problems of the Indian iron and steel industry.", a: "High costs and limited availability of coking coal, lower productivity of labour, irregular supply of energy, and poor infrastructure." },
    { q: "What are the two prime factors in locating an aluminium smelter?", a: "Regular supply of electricity, and an assured source of raw material — bauxite — at minimum cost." },
    { q: "Why does India import all its potash?", a: "Because India has no commercially usable potash or potassium compound mineral reserves." },
    { q: "What is thermal pollution?", a: "Pollution caused when hot water from factories and thermal plants is drained into rivers and ponds before being cooled." },
    { q: "Name the three phases of effluent treatment.", a: "Primary treatment by mechanical means such as screening, grinding, flocculation and sedimentation; secondary treatment by biological process; and tertiary treatment by biological, chemical and physical processes, including recycling." },
  ],
  quiz: [
    { q: "The first successful cotton textile mill in India was set up in:", options: ["Ahmedabad in 1861", "Mumbai in 1854", "Kolkata in 1855", "Kanpur in 1860"], answer: 1, why: "The first successful textile mill was established in Mumbai in 1854." },
    { q: "The first jute mill was set up at:", options: ["Rishra, 1855", "Hugli, 1875", "Titagarh, 1860", "Serampore, 1850"], answer: 0, why: "It was set up at Rishra near Kolkata in 1855, beginning the concentration of jute mills along the Hugli." },
    { q: "Which is a basic or key industry?", options: ["Sugar", "Paper", "Iron and steel", "Toothpaste"], answer: 2, why: "Basic industries supply raw materials to other industries — iron and steel, copper smelting, aluminium smelting." },
    { q: "Amul and the coir industry of Kerala belong to the:", options: ["Public sector", "Private sector", "Joint sector", "Cooperative sector"], answer: 3, why: "Cooperative sector industries are owned and operated by producers or suppliers of raw material, workers, or both." },
    { q: "Iron ore, coking coal and limestone are required in roughly the ratio:", options: ["2 : 1 : 4", "4 : 2 : 1", "1 : 2 : 4", "3 : 3 : 1"], answer: 1, why: "The ratio is approximately 4 : 2 : 1, along with manganese." },
    { q: "The raw material for aluminium smelting is:", options: ["Haematite", "Bauxite", "Manganese", "Mica"], answer: 1, why: "Bauxite, a bulky dark reddish rock, is the ore from which aluminium is obtained." },
    { q: "India imports all its ______ for fertiliser production.", options: ["Nitrogen", "Phosphate", "Potash", "Sulphur"], answer: 2, why: "India has no commercially usable potash or potassium compound reserves." },
    { q: "The electronic capital of India is:", options: ["Hyderabad", "Pune", "Bengaluru", "Chennai"], answer: 2, why: "Bengaluru is described as the electronic capital of India." },
    { q: "Fly ash, phosphor gypsum and iron and steel slags are:", options: ["Air pollutants", "The main solid wastes in India", "Thermal pollutants", "Noise pollutants"], answer: 1, why: "They are named as the main sources of solid waste in India." },
    { q: "Electrostatic precipitators and scrubbers are used to control:", options: ["Water pollution", "Noise pollution", "Particulate matter in the air", "Thermal pollution"], answer: 2, why: "Smoke stacks fitted with electrostatic precipitators, fabric filters, scrubbers and inertial separators reduce particulate matter." },
  ],
  keyTopics: [
    { name: "Factors of industrial location & agglomeration economies", importance: "high", note: "Almost every year's 'explain the factors' or 'why do industries cluster in cities' 3–5 mark question." },
    { name: "Classification of industries — five bases", importance: "high", note: "Ownership and raw-material bases are asked most often, each with named examples." },
    { name: "Iron and steel industry — ratio, location, problems", importance: "high", note: "The 4:2:1 ratio and Chhotanagpur location factors are a recurring 3–5 marker." },
    { name: "Cotton and jute textiles — history and location factors", importance: "high", note: "Mumbai 1854 / Rishra 1855 and the reasons for each region's dominance are classic 3-mark questions." },
    { name: "Industrial pollution — types and control measures", importance: "high", note: "The four kinds of pollution and the three-phase effluent treatment are frequent 3–5 mark answers." },
    { name: "Aluminium smelting — raw material and location factors", importance: "medium", note: "Bauxite and the two prime location factors (electricity, cheap raw material)." },
    { name: "Chemical and fertiliser industries", importance: "medium", note: "Why India imports potash; inorganic vs organic chemicals." },
    { name: "Map work — steel plants, textile centres, software parks", importance: "high", note: "Guaranteed marks; learn the locator list exactly." },
  ],
  written: [
    { q: "Name the first successful cotton textile mill in India and where it was established.", marks: 1, kind: "short", importance: "medium",
      answer: "The first successful cotton textile mill was established in <strong>Mumbai in 1854</strong>." },
    { q: "Name any two agro-based industries.", marks: 1, kind: "short", importance: "medium",
      answer: "Any two of: <strong>cotton textiles, jute textiles, sugar, woollen textiles, silk textiles</strong> — all use raw material produced by agriculture." },
    { q: "What is meant by agglomeration economies?", marks: 2, kind: "short", importance: "high",
      answer: "When a large number of industries locate close together to share the benefits of a common market, banking, insurance, transport and labour available in and around a city, the cost advantages they gain are called <strong>agglomeration economies</strong>. This is why industries and industrial regions grow around cities." },
    { q: "Distinguish between basic (key) industries and consumer industries, with one example each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Basic or key industries</strong> supply their products as raw material to manufacture other goods — for example <strong>iron and steel</strong>, which is used to make machinery. <strong>Consumer industries</strong> produce goods for direct use by consumers — for example <strong>sugar</strong>." },
    { q: "Why is the jute industry concentrated in West Bengal, along the banks of the Hugli?", marks: 2, kind: "short", importance: "high",
      answer: "Because of proximity to the jute-growing areas, inexpensive water transport linking the mills, a dense network of railways, roadways and waterways for collecting raw material, abundant water for processing, and cheap labour available from West Bengal, Bihar, Odisha and Uttar Pradesh, along with Kolkata's port, banking and insurance facilities." },
    { q: "Why has the sugar industry started shifting from Uttar Pradesh and Bihar towards Maharashtra and the southern states?", marks: 2, kind: "short", importance: "medium",
      answer: "The cane grown in Maharashtra and the south has a <strong>higher sucrose content</strong>, the cooler climate there gives a <strong>longer crushing season</strong>, and the cooperative sugar mills in these states are more efficiently managed and successful." },
    { q: "Classify industries on the basis of ownership, explaining each with an example.", marks: 3, kind: "short", importance: "high",
      answer: "<ul><li><strong>Public sector</strong> — owned and run by the government, e.g. <strong>SAIL, BHEL</strong>.</li><li><strong>Private sector</strong> — owned by an individual or a group, e.g. <strong>TISCO, Bajaj Auto, Dabur</strong>.</li><li><strong>Joint sector</strong> — jointly run by the state and private individuals/groups, e.g. <strong>Oil India Limited</strong>.</li><li><strong>Cooperative sector</strong> — owned and run by the producers or suppliers of raw material, workers, or both, e.g. <strong>Amul</strong>, the sugar mills of Maharashtra, and the coir industry of Kerala.</li></ul>" },
    { q: "State three location factors responsible for the concentration of the iron and steel industry in the Chhotanagpur plateau region.", marks: 3, kind: "short", importance: "high",
      answer: "<ul><li>Low cost of iron ore, and the availability of high-grade raw material — iron ore, coking coal and limestone — in close proximity.</li><li>Cheap labour available in the region.</li><li>A vast domestic market to sustain the industry.</li></ul>" },
    { q: "What is industrial pollution? Explain any two types of industrial pollution with their causes.", marks: 3, kind: "long", importance: "high",
      answer: "Industrial pollution is the <strong>contamination of air, water, land or the environment caused by the discharge of harmful waste from industries</strong>. Two examples:<ul><li><strong>Air pollution</strong> — caused by undesirable gases such as sulphur dioxide and carbon monoxide, particulate matter, dust and smoke released by chemical and paper factories, brick kilns, refineries and smelting plants, and by burning fossil fuels.</li><li><strong>Water pollution</strong> — caused by organic and inorganic industrial wastes discharged by paper, chemical, textile, dyeing, petroleum, tannery and electroplating industries into rivers and ponds, carrying dyes, acids, salts, heavy metals and pesticides.</li></ul>" },
    { q: "Explain any five factors that influence the location of an industry.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Availability of raw material</strong> — industries using heavy, weight-losing raw material (like sugar) locate near the source.</li><li><strong>Access to power</strong> — a regular, cheap power supply is essential, especially for aluminium smelting and steel.</li><li><strong>Availability of labour</strong> — cheap and skilled labour reduces production cost.</li><li><strong>Access to market</strong> — nearness to the market where finished goods are sold reduces transport costs and delivery time.</li><li><strong>Transport and capital</strong> — cities offer banking, insurance, transport networks and consultancy services that make them attractive locations, which is also why <strong>agglomeration economies</strong> develop around them.</li></ul>" },
    { q: "Explain any five measures to control industrial pollution.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Minimise use of water</strong> by reusing and recycling it in two or more successive stages.</li><li><strong>Harvest rainwater</strong> to meet water requirements.</li><li>Treat hot water and effluents before releasing them, through <strong>primary</strong> (mechanical — screening, grinding, sedimentation), <strong>secondary</strong> (biological) and <strong>tertiary</strong> (biological, chemical and physical, including recycling) treatment.</li><li>Regulate the <strong>overdrawing of groundwater</strong> by law.</li><li>Fit smoke stacks with <strong>electrostatic precipitators, fabric filters, scrubbers and inertial separators</strong> to reduce particulate matter, and fit generators with silencers to control noise pollution.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Cotton textile mills were historically concentrated around Mumbai and Ahmedabad.",
      reason: "This region had access to black cotton soil in the hinterland, port facilities, a moist climate, capital and available labour.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the factors listed in R are exactly why Mumbai and Ahmedabad grew into the earliest cotton textile centres — R explains A." },
    { assertion: "The chemical industry is regarded as its own largest consumer.",
      reason: "A large share of basic chemicals it produces, such as sulphuric acid and soda ash, are themselves used as raw material to manufacture other chemical products within the industry.",
      answer: 0, importance: "medium",
      why: "Both are true, and the reuse of chemicals like sulphuric acid within the industry (in fertilisers, dyestuffs, paints) is exactly why it consumes so much of its own output — R explains A." },
    { assertion: "India has to import its entire requirement of potash for the fertiliser industry.",
      reason: "India does not possess any commercially usable deposit of potash or potassium compounds.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the lack of workable potash reserves is precisely why India depends entirely on imports — R explains A." },
    { assertion: "Iron and steel is classified as a light industry.",
      reason: "All the inputs and outputs of the iron and steel industry — iron ore, coal, limestone and finished steel — are heavy and bulky, involving heavy transport costs.",
      answer: 3, importance: "high",
      why: "A is false: iron and steel is a classic example of a <strong>heavy</strong> industry, not a light one. R is true — its inputs and outputs are indeed bulky, which is exactly why it is classified as heavy rather than light." },
  ],
  caseStudies: [
    { title: "Locating an iron and steel plant", importance: "high",
      source: "Study the information and answer the questions: the production of one tonne of steel requires iron ore, coking coal and limestone in the approximate ratio of 4 : 2 : 1, along with manganese. Most of India's major integrated steel plants — Bhilai, Durgapur, Rourkela, Jamshedpur and Bokaro — are located in and around the Chhotanagpur plateau region.",
      parts: [
        { q: "In what ratio are iron ore, coking coal and limestone required to produce steel?", marks: 1, answer: "Approximately <strong>4 : 2 : 1</strong>, along with manganese." },
        { q: "Give two reasons why the Chhotanagpur plateau region is favoured for steel plants.", marks: 2, answer: "<strong>(i)</strong> Low-cost iron ore and other high-grade raw material (coking coal, limestone) available in close proximity. <strong>(ii)</strong> Cheap labour and a vast domestic market for steel." },
        { q: "Name any two integrated steel plants located in this region.", marks: 1, answer: "Any two of <strong>Bhilai, Durgapur, Rourkela, Jamshedpur, Bokaro</strong>." },
        { q: "State one problem faced by the Indian iron and steel industry despite these locational advantages.", marks: 1, answer: "High cost and limited availability of coking coal (also acceptable: lower labour productivity, irregular energy supply, or poor infrastructure)." },
      ] },
    { title: "Industrial pollution around a river", importance: "high",
      source: "A textile and dyeing unit located on the bank of a river discharges its untreated effluents directly into the water. Fish are reported dying downstream, and the local population is falling ill after using the river water for drinking and washing.",
      parts: [
        { q: "Which type of industrial pollution is described here?", marks: 1, answer: "<strong>Water pollution</strong> — caused by organic and inorganic industrial waste and effluents released untreated into the river." },
        { q: "Name two industries, other than textile and dyeing, that are major contributors to this kind of pollution.", marks: 1, answer: "Any two of <strong>paper and pulp, chemical, petroleum refining, tanneries, electroplating</strong> industries." },
        { q: "Suggest any two measures the unit could adopt to reduce this pollution.", marks: 2, answer: "<strong>(i)</strong> Treat effluents before release, through primary (mechanical), secondary (biological) and tertiary (chemical/physical, including recycling) treatment. <strong>(ii)</strong> Minimise the use of water by reusing and recycling it in successive stages within the plant." },
      ] },
  ],
};
