import type { Chapter } from "@/lib/types";

export const ch12: Chapter = {
  slug: "lifelines-of-national-economy",
  num: 7,
  title: "Lifelines of National Economy",
  unit: "geography",
  unitName: "Contemporary India — II",
  marks: "Geography · map work only in the board paper",
  minutes: 16,
  blurb: "Roads, rails, pipelines, ports and the internet. Nothing else in the syllabus works without this chapter's contents.",
  bigIdea: "Transport and communication are what turn scattered resources into an economy. Production is pointless if goods cannot reach the people who need them.",
  syllabus: [
    "Roadways, railways, pipelines, waterways and airways",
    "Communication and mass communication",
    "International trade and tourism as a trade",
    "Map work: major seaports, international airports, national highways",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "How this chapter is assessed", html: "In the CBSE board paper this chapter is assessed <strong>only through map work</strong> — you will not get a theory question on it. That does not make it skippable: the map items are guaranteed marks, and the content here underpins the industry and globalisation chapters." },

    { t: "h", text: "Roads" },
    { t: "sim", id: "transport-compare" },
    { t: "p", html: "India has one of the largest road networks in the world. Road transport has grown faster than railways because construction costs are much lower, roads can negotiate <strong>dissected and undulating topography and steeper gradients</strong>, they can serve a few persons economically, they provide <strong>door-to-door service</strong> so loading and unloading costs are lower, and they act as a feeder to other modes — they link railway stations, airports and seaports." },
    { t: "table", head: ["Class", "What it is"], rows: [
      ["<strong>Golden Quadrilateral Super Highways</strong>", "Six-lane highways linking Delhi–Kolkata–Chennai–Mumbai–Delhi, plus the North-South corridor from Srinagar to Kanniyakumari and the East-West corridor from Silchar to Porbandar. Implemented by the National Highway Authority of India. The objective is to reduce the time and distance between mega cities"],
      ["<strong>National Highways</strong>", "Link extreme parts of the country. Primary road systems laid and maintained by the Central Public Works Department (CPWD). The historical <strong>Sher-Shah Suri Marg</strong> — from Delhi to Amritsar — is called <strong>National Highway No. 1</strong>"],
      ["<strong>State Highways</strong>", "Link a state capital with district headquarters. Constructed and maintained by the State Public Works Department"],
      ["<strong>District Roads</strong>", "Connect district headquarters with other places of the district. Maintained by the Zila Parishad"],
      ["<strong>Other/Rural Roads</strong>", "Link rural areas and villages with towns. Given special impetus under the <strong>Pradhan Mantri Grameen Sadak Yojana</strong>, which aims to link every village with a major town by an all-season motorable road"],
      ["<strong>Border Roads</strong>", "Constructed by the <strong>Border Roads Organisation</strong>, a Government of India undertaking established in 1960. They are strategically important in the northern and north-eastern border areas, and have improved accessibility in areas of difficult terrain"],
    ] },
    { t: "note", kind: "trap", html: "<strong>Road density</strong> is the length of road per 100 sq km of area. It is highly variable: <strong>Kerala</strong> has one of the highest densities and <strong>Jammu and Kashmir</strong> one of the lowest, against a national average of around 142 km per 100 sq km." },

    { t: "h", text: "Railways, pipelines, waterways, airways" },
    { t: "list", items: [
      "<strong>Railways</strong> are the principal mode of transportation for freight and passengers, and they bind together the economic life of the country. Indian Railways is the largest public sector undertaking in the country. The distribution pattern is largely influenced by physiographic, economic and administrative factors: the northern plains with their level land, high population density and rich agriculture were most favourable, while the Himalayan terrain, the sandy Rajasthan plain, the swamps of Gujarat, the forested tracts of Madhya Pradesh and the Western Ghats all posed difficulties. The Konkan railway along the west coast has facilitated movement but faces landslides in the monsoon.",
      "<strong>Pipelines</strong> are a new arrival. They transport crude oil, petroleum products and natural gas to refineries, fertiliser factories and big thermal power plants. Solids can also be transported after being converted into slurry. The initial cost is high but subsequent running costs are minimal, and it rules out trans-shipment losses and delays. The three important networks: from the oil field in upper Assam to Kanpur via Guwahati, Barauni and Allahabad; from Salaya in Gujarat to Jalandhar via Viramgam, Mathura, Delhi and Sonipat; and the gas pipeline from Hazira in Gujarat connecting Jagdishpur in Uttar Pradesh via Vijaipur.",
      "<strong>Waterways</strong> are the cheapest for carrying heavy and bulky goods, and are fuel-efficient and environment friendly. India has 14,500 km of navigable waterways. Learn the named National Waterways — the Ganga between Haldia and Allahabad, the Brahmaputra between Sadiya and Dhubri, the West-Coast Canal in Kerala, and the Godavari and Krishna stretches.",
      "<strong>Airways</strong> are the fastest, most comfortable and most prestigious mode. Air travel can cover very difficult terrain like high mountains, dreary deserts, dense forests and long oceanic stretches with great ease. Air travel is <strong>not within the reach of the common people</strong> — that limitation is the standard counterpoint in an answer. It was nationalised in 1953. Pawanhans Helicopters Ltd provides services to petroleum sector and to inaccessible areas, and is used extensively in the north-eastern states and Jammu and Kashmir.",
    ] },
    { t: "note", kind: "real", title: "Ports, west to east", html: "<strong>Kandla</strong> in Kachchh, the first port developed soon after independence, is a tidal port that eased the volume of trade on Mumbai after partition; it is now Deendayal Port. <strong>Mumbai</strong> is the biggest port with a spacious natural and well-sheltered harbour. <strong>Jawaharlal Nehru port</strong> at Nhava Sheva was developed as a satellite port to relieve Mumbai. <strong>Marmagao</strong> in Goa is the premier iron ore exporting port. <strong>New Mangalore</strong> caters to the export of iron ore from Kudremukh. <strong>Kochi</strong> is at the head of a lagoon with a natural harbour. On the east coast: <strong>Tuticorin</strong>, <strong>Chennai</strong> — one of the oldest artificial ports, <strong>Visakhapatnam</strong> — the deepest landlocked and well-protected port, <strong>Paradwip</strong> in Odisha which handles large quantities of iron ore, <strong>Haldia</strong> which relieves pressure on Kolkata, and <strong>Kolkata</strong>, an inland riverine port." },
    { t: "note", kind: "exam", title: "Map work", html: "Major seaports: <strong>Kandla, Mumbai, Marmagao, New Mangalore, Kochi, Tuticorin, Chennai, Visakhapatnam, Paradwip, Haldia</strong>. International airports: <strong>Amritsar (Raja Sansi), Delhi (Indira Gandhi International), Mumbai (Chhatrapati Shivaji), Chennai (Meenam Bakkam), Kolkata (Netaji Subhash Chandra Bose), Hyderabad (Rajiv Gandhi)</strong>." },
    { t: "sim", id: "india-locator" },

    { t: "h", text: "Communication and trade" },
    { t: "p", html: "<strong>Personal communication</strong> is one-to-one; <strong>mass communication</strong> reaches many at once — radio, television, newspapers, magazines, books and films. India has one of the largest postal networks in the world. First-class mail — cards and envelopes — is airlifted between stations covering both land and air. Second-class mail includes book packets, registered newspapers and periodicals, carried by surface mail. India is the largest producer of feature films in the world." },
    { t: "p", html: "<strong>Trade</strong> is the exchange of goods among people, states and countries. The market is the place where this exchange takes place. Trade between two countries is <strong>international trade</strong>, and it is considered the <strong>economic barometer of a country</strong>. The <strong>balance of trade</strong> is the difference between the value of exports and imports: when the value of exports exceeds imports it is a <strong>favourable balance</strong>; when imports exceed exports it is <strong>unfavourable</strong>. India's commodity exchange includes agriculture and allied products, ores and minerals, gems and jewellery, chemicals, engineering goods and petroleum products; imports include petroleum crude and products, gems and jewellery, chemicals, base metals, electronic goods, machinery, agricultural products and edible oils. India has emerged as a software giant, and the exchange of information technology is fast becoming a key element of international trade." },
    { t: "note", kind: "idea", html: "<strong>Tourism as a trade.</strong> Tourism in India has grown substantially and promotes national integration, provides support to local handicrafts and cultural pursuits, and helps in the development of international understanding of our culture and heritage. Foreign tourists visit India for <strong>heritage tourism, eco tourism, adventure tourism, cultural tourism, medical tourism and business tourism</strong>. There is a vast potential for further development." },
  ],
  examFocus: [
    "Six advantages of road transport over railways.",
    "The six classes of roads with the authority responsible for each.",
    "Golden Quadrilateral, the North-South and East-West corridors, and NHAI.",
    "Sher-Shah Suri Marg as National Highway No. 1.",
    "Border Roads Organisation, established 1960.",
    "Road density, and the Kerala versus Jammu and Kashmir contrast.",
    "The physiographic factors shaping railway distribution.",
    "Advantages of pipelines, and the three main networks.",
    "Ports and international airports for map work.",
    "Balance of trade — favourable and unfavourable — and the forms of tourism.",
  ],
  flashcards: [
    { q: "Give four advantages of road transport over railways.", a: "Lower construction cost; ability to negotiate dissected, undulating terrain and steeper gradients; economical for small numbers of people and small quantities of goods; and door-to-door service that cuts loading and unloading costs. Roads also act as feeders to rail, air and sea transport." },
    { q: "What is the Golden Quadrilateral?", a: "Six-lane super highways linking Delhi, Kolkata, Chennai and Mumbai, along with the North-South corridor from Srinagar to Kanniyakumari and the East-West corridor from Silchar to Porbandar, implemented by the National Highway Authority of India to reduce time and distance between mega cities." },
    { q: "What is National Highway No. 1?", a: "The historical Sher-Shah Suri Marg, running from Delhi to Amritsar." },
    { q: "Who maintains national, state and district roads respectively?", a: "National highways by the Central Public Works Department, state highways by the State Public Works Department, and district roads by the Zila Parishad." },
    { q: "What is the Border Roads Organisation?", a: "A Government of India undertaking established in 1960 that constructs and maintains roads in the strategically important northern and north-eastern border areas, improving accessibility in difficult terrain." },
    { q: "Define road density.", a: "The length of road per 100 square kilometres of area. It is highest in states like Kerala and lowest in Jammu and Kashmir." },
    { q: "Which physiographic factors favoured railway development in India?", a: "The level land of the northern plains, with high population density and rich agriculture. The Himalayas, the sandy Rajasthan plain, the swamps of Gujarat, the forested tracts of Madhya Pradesh and the Western Ghats all posed difficulties." },
    { q: "Give three advantages of pipelines.", a: "Running costs are minimal after the high initial cost; they rule out trans-shipment losses and delays; and solids can be carried as slurry alongside liquids and gases." },
    { q: "Why is Visakhapatnam significant among ports?", a: "It is the deepest landlocked and well-protected port in India." },
    { q: "Which port was developed to relieve pressure on Mumbai?", a: "Jawaharlal Nehru port at Nhava Sheva, developed as a satellite port. Kandla was also developed after independence to ease the volume of trade on Mumbai after partition." },
    { q: "What is balance of trade?", a: "The difference between the value of a country's exports and imports. A favourable balance means exports exceed imports; an unfavourable balance means imports exceed exports." },
    { q: "Name the forms of tourism that bring foreign visitors to India.", a: "Heritage tourism, eco tourism, adventure tourism, cultural tourism, medical tourism and business tourism." },
  ],
  quiz: [
    { q: "Which of these is an advantage of roads over railways?", options: ["Lower fuel use per tonne", "Door-to-door service", "Higher speed over long distances", "Ability to carry the heaviest bulk goods"], answer: 1, why: "Road transport provides door-to-door service, so loading and unloading costs are much lower." },
    { q: "The Golden Quadrilateral links:", options: ["Delhi, Kolkata, Chennai and Mumbai", "Srinagar and Kanniyakumari", "Silchar and Porbandar", "Delhi and Amritsar"], answer: 0, why: "The Golden Quadrilateral connects the four mega cities; the other options are the corridors and NH-1." },
    { q: "Sher-Shah Suri Marg is:", options: ["National Highway No. 7", "National Highway No. 1", "The East-West corridor", "A state highway"], answer: 1, why: "The historical Sher-Shah Suri Marg from Delhi to Amritsar is called National Highway No. 1." },
    { q: "The Border Roads Organisation was established in:", options: ["1947", "1953", "1960", "1972"], answer: 2, why: "It was established in 1960 as a Government of India undertaking." },
    { q: "District roads are maintained by the:", options: ["CPWD", "State PWD", "Zila Parishad", "NHAI"], answer: 2, why: "District roads connecting district headquarters with other places in the district are maintained by the Zila Parishad." },
    { q: "Which port is the premier iron ore exporting port of India?", options: ["Kandla", "Marmagao", "Haldia", "Tuticorin"], answer: 1, why: "Marmagao in Goa is the premier iron ore exporting port, handling a large share of India's iron ore exports." },
    { q: "The deepest landlocked and well-protected port is:", options: ["Chennai", "Paradwip", "Visakhapatnam", "Kochi"], answer: 2, why: "Visakhapatnam is described as the deepest landlocked and well-protected port." },
    { q: "Kolkata port is a:", options: ["Tidal port", "Inland riverine port", "Natural harbour", "Satellite port"], answer: 1, why: "Kolkata is an inland riverine port; Haldia was developed to relieve pressure on it." },
    { q: "When exports exceed imports in value, the balance of trade is:", options: ["Unfavourable", "Favourable", "Neutral", "Deficit"], answer: 1, why: "Exports exceeding imports gives a favourable balance of trade." },
    { q: "Air transport was nationalised in India in:", options: ["1947", "1950", "1953", "1960"], answer: 2, why: "Air transport was nationalised in 1953." },
  ],
  keyTopics: [
    { name: "Road classification & Golden Quadrilateral", importance: "high", note: "The six road classes with their maintaining authority, plus the Golden Quadrilateral and the two corridors, are asked as theory even though the board tests this chapter mainly via the map." },
    { name: "Advantages of roads over railways", importance: "high", note: "A standard 'give reasons' 2–3 mark question." },
    { name: "Railways — physiographic & economic factors of distribution", importance: "high", note: "A reliable 5-mark 'explain the factors' long answer." },
    { name: "Pipelines — advantages and the three networks", importance: "medium", note: "3-mark 'advantages of pipeline transport' question." },
    { name: "Ports — location and specialisation", importance: "high", note: "This is exactly where map work and written revision overlap — learn each port's one distinguishing fact." },
    { name: "Balance of trade & international trade", importance: "high", note: "Favourable vs unfavourable balance is a reliable 2-mark definition question." },
    { name: "Tourism as a trade", importance: "medium", note: "Forms of tourism and its contribution to foreign exchange and national integration." },
    { name: "Map work — seaports, international airports, national highways", importance: "high", note: "The ONLY way this chapter is examined in the board paper — do not skip the locator list." },
  ],
  written: [
    { q: "In which year was air transport nationalised in India?", marks: 1, kind: "short", importance: "medium",
      answer: "Air transport in India was nationalised in <strong>1953</strong>." },
    { q: "Name the port on the west coast of India that is the premier iron-ore exporting port.", marks: 1, kind: "short", importance: "high",
      answer: "<strong>Marmagao</strong>, in Goa. It handles nearly fifty per cent of India's iron-ore export shipments." },
    { q: "What is meant by 'balance of trade'? When is it said to be favourable?", marks: 2, kind: "short", importance: "high",
      answer: "The <strong>balance of trade</strong> is the difference between the value of a country's exports and its imports. It is said to be <strong>favourable</strong> when the value of exports is more than the value of imports, and <strong>unfavourable</strong> when imports exceed exports." },
    { q: "Give two reasons why road transport has grown faster than railways in India.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> Roads can negotiate dissected and undulating topography and steeper gradients that railway lines cannot. <strong>(ii)</strong> Roads provide door-to-door service, cutting the cost of loading and unloading, and can serve a small number of people or a small quantity of goods economically — while also acting as feeders to railways, airports and seaports." },
    { q: "Name the states through which the Konkan Railway passes, and mention one difficulty it faces.", marks: 2, kind: "short", importance: "medium",
      answer: "The Konkan Railway runs along India's west coast through <strong>Maharashtra, Goa, Karnataka and Kerala</strong>, and is considered an engineering marvel. It faces frequent <strong>landslides during the monsoon</strong> because of the steep, unstable terrain of the Western Ghats it passes through." },
    { q: "Mention two forms of tourism, other than heritage tourism, through which India earns foreign exchange.", marks: 2, kind: "short", importance: "medium",
      answer: "Any two of: <strong>eco tourism, adventure tourism, cultural tourism, medical tourism, business tourism</strong>." },
    { q: "Explain any three advantages of pipeline transportation.", marks: 3, kind: "short", importance: "high",
      answer: "<ul><li>Running costs are <strong>minimal</strong> once the pipeline is laid, although the initial investment is high.</li><li>Pipelines <strong>rule out trans-shipment losses and delays</strong>, since the product moves directly from source to destination.</li><li>They can carry <strong>liquids and gases directly</strong>, and even solids after converting them into slurry, across difficult terrain with minimal disturbance.</li></ul>" },
    { q: "Describe the significance of the Golden Quadrilateral super highways.", marks: 3, kind: "short", importance: "high",
      answer: "The Golden Quadrilateral consists of <strong>six-lane super highways linking the four mega cities — Delhi, Mumbai, Chennai and Kolkata</strong> — together with the <strong>North-South corridor</strong> (Srinagar to Kanniyakumari) and the <strong>East-West corridor</strong> (Silchar to Porbandar). It is implemented by the <strong>National Highway Authority of India (NHAI)</strong>, and its objective is to reduce the time and distance between the mega cities, boosting trade and industrial movement." },
    { q: "Name the port that was developed to relieve pressure on Mumbai, and the port that relieves pressure on Kolkata. Why were such satellite/relief ports developed?", marks: 3, kind: "short", importance: "high",
      answer: "<strong>Jawaharlal Nehru port</strong> at Nhava Sheva was developed as a satellite port to relieve pressure on Mumbai; <strong>Haldia</strong> port was developed to relieve pressure on Kolkata port. Such ports are developed because the older ports become congested as trade grows, and a nearby dedicated port allows cargo to be handled faster without overloading the original harbour's capacity." },
    { q: "Explain any five physiographic and economic factors that have influenced the distribution pattern of railways in India.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li>The <strong>level land of the northern plains</strong>, with high population density and rich agricultural produce, made railway construction easy and profitable.</li><li>The <strong>mountainous terrain of the Himalayan region</strong> was unfavourable, as tracks are difficult and costly to lay.</li><li>The <strong>sandy plains of Rajasthan</strong> similarly discouraged dense railway construction.</li><li>The <strong>marshy/swampy land of Gujarat</strong> and the <strong>densely forested tracts of the Chhattisgarh, Madhya Pradesh and Odisha uplands</strong> also posed difficulties.</li><li>The <strong>Western Ghats</strong> could be traversed only through gaps or passes, so railway lines follow specific routes such as the Konkan Railway, which nonetheless faces landslides in the monsoon.</li></ul>" },
    { q: "'Different modes of transport are complementary to each other and together support trade and commerce.' Explain this statement with examples of at least four modes of transport.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Roads</strong> act as feeders, linking railway stations, airports and seaports to the interior, and provide the door-to-door service that no other mode can match.</li><li><strong>Railways</strong> carry heavy freight and large numbers of passengers over long distances economically, binding the economic life of the country together.</li><li><strong>Pipelines</strong> move crude oil, petroleum products and natural gas continuously to refineries, fertiliser factories and power plants — a task roads and railways cannot do efficiently.</li><li><strong>Waterways</strong> carry the heaviest and bulkiest cargo most cheaply, especially for international trade through seaports.</li><li><strong>Airways</strong> cover very difficult terrain rapidly and are indispensable for time-sensitive movement of people and high-value goods, though not affordable for the common person.</li></ul>Together, these modes ensure that goods produced anywhere in the country can reach markets and ports, which is essential for both domestic trade and international trade." },
  ],
  assertionReason: [
    { assertion: "Road transport has grown faster than railway transport in India.",
      reason: "Roads can negotiate dissected and undulating topography and steeper gradients more easily than railway lines can.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the ability to handle difficult terrain is one of the key reasons roads have expanded faster than railways — R explains A." },
    { assertion: "Pipelines are an efficient way to transport petroleum products, natural gas and even solids converted into slurry.",
      reason: "The initial cost of laying a pipeline network is very low, though its running costs are high.",
      answer: 2, importance: "high",
      why: "A is true. R is false — it is the opposite: the <strong>initial investment</strong> in laying pipelines is high, while the <strong>subsequent running cost is minimal</strong>." },
    { assertion: "Air transport is not within the reach of the common people in India.",
      reason: "Air transport is far more expensive than other modes of transport such as roads and railways.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the high cost described in R is exactly why air travel remains out of reach for most people — R explains A." },
    { assertion: "International trade is considered the economic barometer of a country.",
      reason: "The nature and magnitude of a country's exports and imports reflect its economic prosperity and its standing in world markets.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the reasoning in R — that trade volume and composition reflect prosperity — is exactly why international trade functions as an economic barometer, as stated in A." },
  ],
  caseStudies: [
    { title: "Choosing the right mode of transport", importance: "high",
      source: "Three businesses have different transport needs. Business A must move a bulky, low-value consignment of machine parts about 2,000 km and is not concerned about delivery time. Business B needs to send an executive from Delhi to Chennai for a same-day meeting. Business C needs to move crude oil continuously from an oilfield to a refinery 500 km away.",
      parts: [
        { q: "Which mode of transport is most suitable for Business A, and why?", marks: 1, answer: "<strong>Waterways</strong> (or railways) — the cheapest way of carrying heavy and bulky goods over long distances, and fuel-efficient and environment-friendly besides." },
        { q: "Which mode should Business B choose, and what is one limitation of this mode for the general population?", marks: 1, answer: "<strong>Airways.</strong> Its limitation is that air travel is very expensive and therefore <strong>not within the reach of the common people</strong>." },
        { q: "Which mode best suits Business C's requirement, and state one advantage of this mode.", marks: 2, answer: "<strong>Pipelines.</strong> Advantage: running costs are minimal after the initial investment, and they rule out trans-shipment losses and delays since the oil flows directly and continuously from field to refinery." },
      ] },
    { title: "Ports along India's coastline", importance: "high",
      source: "Study the table of ports and answer the questions:<br><table><thead><tr><th>Coast</th><th>Port</th></tr></thead><tbody><tr><td>West coast</td><td>Kandla</td></tr><tr><td>West coast</td><td>Mumbai</td></tr><tr><td>East coast</td><td>Paradwip</td></tr><tr><td>East coast</td><td>Haldia</td></tr></tbody></table>",
      parts: [
        { q: "Name the state in which Kandla port is located, and mention one reason for its early development soon after independence.", marks: 2, answer: "Kandla is located in <strong>Gujarat</strong> (in the Kachchh region). It was developed soon after independence to ease the growing volume of trade on Mumbai port, after the partition of the country reduced the use of Karachi port." },
        { q: "Which mineral does Paradwip port mainly handle for export?", marks: 1, answer: "<strong>Iron ore</strong> — Paradwip in Odisha handles large quantities of iron ore for export." },
        { q: "Name the port that was developed to relieve pressure on Kolkata port, and state where it is located.", marks: 1, answer: "<strong>Haldia</strong> port, located downstream of Kolkata on the Hugli, was developed to relieve the pressure of trade on Kolkata port." },
      ] },
  ],
};
