import type { Chapter } from "@/lib/types";

export const ch13: Chapter = {
  slug: "power-sharing",
  num: 1,
  title: "Power Sharing",
  unit: "civics",
  unitName: "Democratic Politics — II",
  marks: "Civics · 20 marks",
  minutes: 14,
  blurb: "Belgium and Sri Lanka started from similar problems and chose opposite answers. One worked. This chapter is about why.",
  bigIdea: "Sharing power is not a weakness of democracy that has to be tolerated. It is what makes democracy work, and refusing to share it is what tears countries apart.",
  syllabus: [
    "Belgium and Sri Lanka — two contrasting responses to diversity",
    "Majoritarianism in Sri Lanka",
    "Accommodation in Belgium",
    "Why power sharing is desirable",
    "Forms of power sharing",
  ],
  blocks: [
    { t: "h", text: "Two small countries, two choices" },
    { t: "table", head: ["", "Belgium", "Sri Lanka"], rows: [
      ["Communities", "In the capital Brussels the population is 80% French-speaking and 20% Dutch-speaking, while in the country as a whole 59% live in the Flemish region and speak Dutch, 40% live in Wallonia and speak French, and 1% speak German", "74% Sinhala-speakers, 18% Tamils. Of the Tamils, 13% are Sri Lankan Tamils (native) and 5% Indian Tamils (brought as plantation workers by the British)"],
      ["The tension", "The French-speaking minority was richer and more powerful, which the Dutch-speaking majority resented after they got the benefit of economic development and education much later", "Sinhala-speakers are concentrated everywhere; Sri Lankan Tamils are concentrated in the north and east"],
      ["The choice made", "<strong>Accommodation.</strong> The constitution was amended four times between 1970 and 1993", "<strong>Majoritarianism.</strong> In 1956 an Act made Sinhala the only official language"],
      ["The result", "Brussels is the headquarters of the European Union, and the arrangement held the country together", "Civil war from the 1980s, thousands killed, families destroyed, and terrible social, cultural and economic cost. It ended in 2009"],
    ] },
    { t: "note", kind: "why", title: "What Sri Lanka actually did", html: "A democratically elected government adopted a series of <strong>majoritarian</strong> measures: the 1956 Act recognising Sinhala as the only official language, preferential policies favouring Sinhala applicants for university positions and government jobs, and a constitution stating that the state shall protect and foster <strong>Buddhism</strong>. Each measure gradually increased the feeling among Sri Lankan Tamils that none of the major political parties led by the Buddhist Sinhala leaders was sensitive to their language and culture — that they were being denied equal political rights, discriminated against in jobs, and ignored in their interests." },
    { t: "note", kind: "trap", html: "The exam loves the phrase <strong>'majoritarianism'</strong>: the belief that the majority community should be able to rule a country in whatever way it wants, disregarding the wishes and needs of the minority. Sri Lanka is majoritarianism; Belgium is accommodation. Do not mix the labels." },
    { t: "note", kind: "real", title: "The Belgian model", html: "Four key elements. First, the number of Dutch and French-speaking ministers in the central government shall be <strong>equal</strong>, and some special laws require the support of the majority of members from each linguistic group — so no single community can make decisions unilaterally. Second, many powers of the central government were given to the <strong>state governments</strong> of the two regions, which are not subordinate to the central government. Third, Brussels has a <strong>separate government</strong> in which both communities have equal representation, because the French-speaking people accepted equal representation in Brussels just as the Dutch-speaking accepted it at the centre. Fourth, apart from the central and state governments there is a <strong>community government</strong>, elected by people belonging to one language community — Dutch, French and German-speaking — no matter where they live, with power over cultural, educational and language-related issues." },

    { t: "h", text: "Why share power at all" },
    { t: "sim", id: "power-sharing-forms" },
    { t: "table", head: ["Reason", "The argument"], rows: [
      ["<strong>Prudential</strong>", "Power sharing is good because it reduces the possibility of conflict between social groups. Since social conflict often leads to violence and political instability, it is a good way to ensure the <strong>stability of political order</strong>. Imposing the will of the majority over others may look attractive in the short run, but in the long run it undermines the unity of the nation. Prudential reasons are based on <strong>careful calculation of gains and losses</strong>"],
      ["<strong>Moral</strong>", "Power sharing is the <strong>very spirit of democracy</strong>. A democratic rule involves sharing power with those affected by its exercise and who have to live with its effects. People have a right to be consulted on how they are to be governed. A legitimate government is one where citizens, through participation, acquire a stake in the system. Moral reasons emphasise the <strong>act of power sharing as valuable in itself</strong>"],
    ] },

    { t: "h", text: "Four forms of power sharing" },
    { t: "list", items: [
      "<strong>Among different organs of government</strong> — legislature, executive and judiciary. This is <em>horizontal distribution</em> of power: organs placed at the same level exercise different powers, and each keeps a check on the others. This results in a system of <strong>checks and balances</strong>. Ministers and government officials exercise power but are answerable to Parliament or state assemblies; judges are appointed by the executive but can check the functioning of executive or the laws made by the legislature.",
      "<strong>Among governments at different levels</strong> — a general government for the entire country and governments at the provincial or regional level. In India we call the general one the <strong>Union or Central Government</strong> and the others State Governments. This is <em>vertical division</em> of power, and when the constitution itself lays down the division, it is called a <strong>federal government</strong>.",
      "<strong>Among different social groups</strong>, such as religious and linguistic groups. The 'community government' in Belgium is an example, and in India <strong>reserved constituencies</strong> in assemblies and the parliament serve this purpose. This method gives space in the government and administration to diverse social groups who otherwise would feel alienated.",
      "<strong>Among political parties, pressure groups and movements.</strong> In a democracy citizens must have freedom to choose among various contenders for power. In contemporary democracies this takes the form of competition among different parties, which ensures power is not concentrated in one hand and is shared among different political parties representing different ideologies. Sometimes this sharing is direct, when two or more parties form an <strong>alliance</strong> to contest elections and form a <strong>coalition government</strong>. Interest groups such as traders, businessmen, industrialists, farmers and industrial workers also share governmental power, either through participation in governmental committees or by influencing the decision-making process.",
    ] },
    { t: "note", kind: "idea", html: "The chapter's move is worth noticing. It begins by saying power sharing is desirable because it prevents conflict and because it is right in itself — and ends by showing that power sharing is not an occasional device but the ordinary structure of every democracy. Every subsequent civics chapter is one of these four forms in detail." },
  ],
  examFocus: [
    "The population figures for Belgium and Sri Lanka, and the difference in Brussels.",
    "Majoritarian measures adopted in Sri Lanka, with the 1956 Act.",
    "The four elements of the Belgian model, especially the community government.",
    "Prudential versus moral reasons for power sharing — and being able to label a given argument.",
    "The four forms of power sharing, with horizontal and vertical division.",
    "Checks and balances as a result of horizontal distribution.",
  ],
  flashcards: [
    { q: "Give the linguistic breakdown of Belgium.", a: "59% live in the Flemish region and speak Dutch, 40% live in Wallonia and speak French, and 1% speak German. In the capital Brussels, 80% are French-speaking and 20% Dutch-speaking." },
    { q: "Give the community breakdown of Sri Lanka.", a: "74% Sinhala-speakers and 18% Tamils. Of the Tamils, 13% are Sri Lankan Tamils and 5% are Indian Tamils, brought by the British as plantation workers." },
    { q: "What is majoritarianism?", a: "The belief that the majority community should be able to rule a country in whatever way it wants, disregarding the wishes and needs of the minority." },
    { q: "Name three majoritarian measures adopted in Sri Lanka.", a: "The 1956 Act recognising Sinhala as the only official language; preferential policies favouring Sinhala applicants for university positions and government jobs; and a constitutional provision that the state shall protect and foster Buddhism." },
    { q: "What is a community government?", a: "A government elected by people belonging to one language community — Dutch, French and German-speaking — no matter where they live in Belgium. It has power over cultural, educational and language-related issues." },
    { q: "Why was equal representation acceptable to both communities in Belgium?", a: "The French-speaking people accepted equal representation in Brussels, where they are the local majority, because the Dutch-speaking accepted equal representation at the central government, where they are the national majority." },
    { q: "What is a prudential reason for power sharing?", a: "That it reduces the possibility of conflict between social groups and so ensures the stability of the political order. Prudential reasons are based on careful calculation of gains and losses." },
    { q: "What is a moral reason for power sharing?", a: "That power sharing is the very spirit of democracy — people have a right to be consulted on how they are governed, and a legitimate government is one in which citizens acquire a stake through participation. It is valuable in itself." },
    { q: "What is horizontal distribution of power?", a: "Sharing power among the legislature, executive and judiciary — organs placed at the same level exercising different powers, each checking the others, producing a system of checks and balances." },
    { q: "What is vertical division of power?", a: "Sharing power among governments at different levels — a general government for the whole country and governments at provincial or regional level. When the constitution lays down this division, it is a federal government." },
    { q: "How is power shared among social groups in India?", a: "Through reserved constituencies in assemblies and Parliament, which give space in government and administration to diverse social groups that would otherwise feel alienated." },
    { q: "What is a coalition government?", a: "A government formed when two or more parties form an alliance to contest elections and, if successful, share power between them." },
  ],
  quiz: [
    { q: "In Brussels, French-speakers form:", options: ["20% of the population", "40%", "59%", "80%"], answer: 3, why: "Brussels is 80% French-speaking and 20% Dutch-speaking, the reverse of the national picture." },
    { q: "The Act making Sinhala the sole official language was passed in:", options: ["1948", "1956", "1972", "1983"], answer: 1, why: "The 1956 Act recognised Sinhala as the only official language, disregarding Tamil." },
    { q: "Indian Tamils in Sri Lanka are descendants of:", options: ["Ancient settlers", "Plantation workers brought by the British", "Buddhist missionaries", "Portuguese traders"], answer: 1, why: "They were brought from India as plantation workers during the colonial period, and form about 5% of the population." },
    { q: "The argument that power sharing reduces conflict and ensures stability is:", options: ["A moral reason", "A prudential reason", "A constitutional reason", "A federal reason"], answer: 1, why: "Prudential reasons are based on careful calculation of gains and losses; moral reasons treat power sharing as valuable in itself." },
    { q: "'Power sharing is the very spirit of democracy' is:", options: ["A prudential reason", "A moral reason", "A legal reason", "A historical claim"], answer: 1, why: "Moral reasons emphasise the act of power sharing as valuable in itself, not for its consequences." },
    { q: "Sharing power among the legislature, executive and judiciary is:", options: ["Vertical division", "Horizontal distribution", "Community government", "Coalition"], answer: 1, why: "Organs at the same level exercising different powers is horizontal distribution, which produces checks and balances." },
    { q: "The community government in Belgium has power over:", options: ["Defence and foreign affairs", "Cultural, educational and language-related issues", "Taxation", "Policing"], answer: 1, why: "It is elected by one language community wherever they live, and handles culture, education and language." },
    { q: "Reserved constituencies in India are an example of power sharing among:", options: ["Organs of government", "Levels of government", "Social groups", "Political parties"], answer: 2, why: "They give space in the legislature to social groups that would otherwise be under-represented." },
    { q: "The Belgian constitution was amended how many times between 1970 and 1993?", options: ["Twice", "Three times", "Four times", "Six times"], answer: 2, why: "Belgian leaders amended their constitution four times to work out an arrangement enabling everyone to live together." },
    { q: "The civil war in Sri Lanka ended in:", options: ["1983", "2000", "2009", "2015"], answer: 2, why: "The civil war that began in the 1980s came to an end in 2009, after enormous social, cultural and economic cost." },
  ],
};
