import type { Chapter } from "@/lib/types";

export const ch14: Chapter = {
  slug: "federalism",
  num: 2,
  title: "Federalism",
  unit: "civics",
  unitName: "Democratic Politics — II",
  marks: "Civics · 20 marks",
  minutes: 16,
  blurb: "How one country holds together twenty-eight states, twenty-two scheduled languages and a great many people who disagree.",
  bigIdea: "India was not made federal because federalism is fashionable. It was made federal because a country this diverse cannot be run from one desk.",
  syllabus: [
    "What is federalism",
    "What makes India a federal country",
    "How federalism is practised — linguistic states, language policy, centre-state relations",
    "Decentralisation in India",
  ],
  blocks: [
    { t: "h", text: "What federalism is" },
    { t: "p", html: "Federalism is a system of government in which power is divided between a central authority and various constituent units of the country. A federation has <strong>two or more levels or tiers</strong> of government, each with its own jurisdiction in matters of legislation, taxation and administration, even though they govern the same citizens." },
    { t: "table", head: ["Feature", "What it means"], rows: [
      ["Two or more levels of government", "Governing the same citizens, but each tier having its own jurisdiction"],
      ["Jurisdictions specified in the constitution", "The existence and authority of each tier is <strong>constitutionally guaranteed</strong>"],
      ["Constitution cannot be changed unilaterally", "Fundamental provisions require the <strong>consent of both levels</strong>"],
      ["Courts settle disputes", "The judiciary interprets the constitution and the powers of different levels; the highest court acts as an umpire"],
      ["Sources of revenue specified", "Each level has clearly specified revenue sources, ensuring its <strong>financial autonomy</strong>"],
      ["Dual objectives", "To safeguard and promote <strong>unity of the country</strong>, while accommodating <strong>regional diversity</strong>"],
    ] },
    { t: "note", kind: "why", title: "Coming together and holding together", html: "<strong>Coming together federations</strong> are formed when independent states come together on their own to form a bigger unit — the USA, Switzerland, Australia. All constituent states usually have <strong>equal power</strong> and are strong vis-à-vis the federal government.<br><br><strong>Holding together federations</strong> are formed when a large country decides to divide its power between constituent states and the national government — India, Spain, Belgium. Here the central government tends to be <strong>more powerful</strong> than the states, and different constituent units may be given <strong>unequal powers</strong>. This distinction is a very common two-mark question." },

    { t: "h", text: "What makes India federal" },
    { t: "sim", id: "federalism-lists" },
    { t: "list", items: [
      "The Constitution declared India a <strong>Union of States</strong>, and originally provided for a two-tier system — Union Government or Central Government, and State Governments. A <strong>third tier</strong> of panchayats and municipalities was added later.",
      "The Constitution specified the powers of the Union and the States in <strong>three lists</strong>. The <strong>Union List</strong> has 97 subjects of national importance — defence, foreign affairs, banking, communications, currency — on which uniform policy is needed, so only the Union Government can make laws. The <strong>State List</strong> has 66 subjects of state and local importance — police, trade, commerce, agriculture, irrigation — on which State Governments alone can make laws. The <strong>Concurrent List</strong> has 47 subjects of common interest to both — education, forest, trade unions, marriage, adoption, succession. Both can make laws, but if their laws conflict, the <strong>law made by the Union Government prevails</strong>.",
      "Subjects that do not fall in any of the three lists — such as computer software, which did not exist when the Constitution was made — are <strong>residuary subjects</strong>, and the power to legislate on them rests with the <strong>Union Government</strong>.",
      "Not every state has identical powers. Some states — Jammu and Kashmir historically, and states in the north-east — enjoy special provisions under Article 371. There are also <strong>Union Territories</strong> such as Chandigarh, Lakshadweep and Delhi, which do not have the powers of a state and where the Central Government has special powers.",
      "This sharing of power is <strong>fundamental to the structure of the Constitution</strong>: it is not easy to change it. Any change has to be first passed by both Houses of Parliament with at least a <strong>two-thirds majority</strong>, and then ratified by the legislatures of at least <strong>half the total states</strong>.",
    ] },
    { t: "note", kind: "trap", html: "Naming just the three lists is not enough for full marks. Say who legislates, give an example subject from each list, and add the two clinchers — the Union law prevails on the Concurrent List, and residuary powers rest with the Union." },

    { t: "h", text: "Federalism in practice" },
    { t: "list", items: [
      "<strong>Linguistic states.</strong> The first and a major test came with the creation of linguistic states. From 1947 to 2019 the boundaries of several old states were changed to create new states, some formed on the basis of language and others to recognise differences based on culture, ethnicity or geography — Nagaland, Uttarakhand, Jharkhand. At the time some national leaders feared it would lead to the disintegration of the country. The experience showed the opposite: it has actually <strong>made the country more united</strong> and made administration easier.",
      "<strong>Language policy.</strong> Hindi was identified as the official language, but it is the mother tongue of only about 40% of Indians — so there were safeguards. Besides Hindi, there are <strong>22 other languages recognised as Scheduled Languages</strong>. A candidate in an examination conducted for the Central Government positions may opt to take the examination in any of these languages. States too have their own official languages, and much government work takes place in the official language of the concerned state. According to the Constitution, the use of English for official purposes was to stop in <strong>1965</strong>, but many non-Hindi speaking states demanded that the use of English continue — in Tamil Nadu this movement took a violent form. The Central Government responded by agreeing to continue the use of English along with Hindi for official purposes. The chapter's point is that <strong>unlike Sri Lanka, the leaders of our country adopted a very cautious attitude in spreading the use of Hindi</strong>.",
      "<strong>Centre-state relations.</strong> For a long time the same party ruled both at the centre and in most of the states, so the Central Government often <strong>misused the Constitution to dismiss state governments that were controlled by rival parties</strong>. This undermined the spirit of federalism. After 1990 the rise of regional political parties and the era of <strong>coalition governments</strong> at the centre led to a new culture of power sharing and respect for the autonomy of State Governments. This trend was supported by a major <strong>judgment of the Supreme Court</strong> that made it difficult for the Central Government to dismiss state governments arbitrarily.",
    ] },

    { t: "h", text: "Decentralisation" },
    { t: "p", html: "When power is taken away from Central and State governments and given to local government, it is called <strong>decentralisation</strong>. The basic idea is that there are a large number of problems and issues best settled at the local level, where people have better knowledge of problems in their localities and better ideas on where to spend money and how to manage things more efficiently. It is also possible for people to <strong>directly participate</strong> in decision making — a foundation of democracy." },
    { t: "note", kind: "real", title: "The 1992 amendment", html: "A major step was taken in <strong>1992</strong> when the Constitution was amended to make the third tier of democracy more powerful and effective. Now it is constitutionally mandatory to hold regular elections to local government bodies. Seats are <strong>reserved for the Scheduled Castes, Scheduled Tribes and Other Backward Classes</strong>. At least <strong>one-third of all positions are reserved for women</strong>. An independent institution, the <strong>State Election Commission</strong>, has been created in each state to conduct panchayat and municipal elections. The State Governments are required to <strong>share some powers and revenue</strong> with local government bodies." },
    { t: "table", head: ["Rural tier", "What it is"], rows: [
      ["<strong>Gram Panchayat</strong>", "The council at village level, with several ward members often called <em>panch</em>, and a president or <em>sarpanch</em>. They are directly elected by all the adult population living in that ward or village. It is the decision-making body for the entire village, and works under the overall supervision of the <strong>Gram Sabha</strong> — all the voters in the village — which must meet at least twice or thrice a year to approve the annual budget and review performance"],
      ["<strong>Panchayat Samiti or Block or Mandal</strong>", "A few gram panchayats grouped together. Its members are elected by all the panchayat members in that area"],
      ["<strong>Zila Parishad</strong>", "All the panchayat samitis in a district together constitute the zila parishad. Most members are elected, and it also includes Members of Parliament and MLAs of that district and some district-level officers. It has a chairperson, its political head"],
    ] },
    { t: "p", html: "Local government bodies exist for urban areas as well. <strong>Municipalities</strong> are set up in towns; big cities are constituted into <strong>municipal corporations</strong>. Both are controlled by elected bodies consisting of people's representatives. The head of a municipality is the <strong>municipal chairperson</strong>; in a municipal corporation the head is the <strong>mayor</strong>." },
    { t: "note", kind: "idea", html: "The honest assessment the chapter gives: the new system has created around <strong>36 lakh elected representatives</strong> in panchayats and municipalities, and has brought a large number of women into the political system. But most state governments have not transferred significant powers or resources to local governments, so the experiment is real but incomplete." },
  ],
  examFocus: [
    "Definition of federalism, and the key features of a federal system.",
    "Coming together versus holding together federations, with examples.",
    "The three lists with subject counts, example subjects, and who legislates.",
    "Residuary powers, and the rule when Concurrent List laws conflict.",
    "The amendment procedure for changing the power-sharing arrangement.",
    "Linguistic states — the fear, and what actually happened.",
    "The language policy, 1965, and the contrast with Sri Lanka.",
    "How centre-state relations changed after 1990.",
    "The 1992 amendment and its provisions, with the three rural tiers.",
  ],
  flashcards: [
    { q: "Define federalism.", a: "A system of government in which power is divided between a central authority and various constituent units of the country, with two or more tiers of government each having its own jurisdiction over the same citizens." },
    { q: "Distinguish coming together and holding together federations.", a: "Coming together federations form when independent states join to make a bigger unit — the USA, Switzerland, Australia — and states have equal, strong powers. Holding together federations form when a large country divides power among constituent states — India, Spain, Belgium — and the central government is more powerful, with units sometimes having unequal powers." },
    { q: "How many subjects are in each of the three lists?", a: "The Union List has 97 subjects, the State List 66, and the Concurrent List 47." },
    { q: "Give three subjects from each list.", a: "Union List: defence, foreign affairs, banking, communications, currency. State List: police, trade, commerce, agriculture, irrigation. Concurrent List: education, forest, trade unions, marriage, adoption and succession." },
    { q: "What happens if Union and State laws conflict on a Concurrent List subject?", a: "The law made by the Union Government prevails." },
    { q: "Who has power over residuary subjects?", a: "The Union Government. Residuary subjects are those not falling in any of the three lists, such as computer software, which did not exist when the Constitution was written." },
    { q: "How can the power-sharing arrangement be changed?", a: "Any change must first be passed by both Houses of Parliament with at least a two-thirds majority, and then ratified by the legislatures of at least half the total states." },
    { q: "What was feared about linguistic states, and what happened?", a: "Some national leaders feared that creating states on the basis of language would lead to the disintegration of the country. In fact it made the country more united and made administration easier." },
    { q: "What was supposed to happen to English in 1965?", a: "The Constitution provided that the use of English for official purposes was to stop in 1965. Non-Hindi speaking states protested — violently in Tamil Nadu — and the Central Government agreed to continue English alongside Hindi." },
    { q: "How did centre-state relations change after 1990?", a: "The rise of regional parties and coalition governments at the centre created a new culture of power sharing and respect for state autonomy, supported by a Supreme Court judgment making it harder to dismiss state governments arbitrarily." },
    { q: "What did the 1992 constitutional amendment do?", a: "It made the third tier of democracy more powerful: regular local elections became mandatory, seats were reserved for SCs, STs and OBCs, at least one-third of positions were reserved for women, a State Election Commission was created in each state, and states were required to share powers and revenue with local bodies." },
    { q: "What is the Gram Sabha?", a: "The body of all the voters in a village. It supervises the gram panchayat and must meet at least twice or thrice a year to approve the annual budget and review the panchayat's performance." },
  ],
  quiz: [
    { q: "India is an example of a:", options: ["Coming together federation", "Holding together federation", "Unitary state", "Confederation"], answer: 1, why: "A large country dividing power among constituent states is a holding together federation, like Spain and Belgium." },
    { q: "The Union List contains:", options: ["47 subjects", "66 subjects", "97 subjects", "22 subjects"], answer: 2, why: "97 subjects of national importance, on which only the Union Government can legislate." },
    { q: "Education is in the:", options: ["Union List", "State List", "Concurrent List", "Residuary powers"], answer: 2, why: "Education, forest, trade unions, marriage, adoption and succession are Concurrent List subjects." },
    { q: "Police is in the:", options: ["Union List", "State List", "Concurrent List", "Residuary powers"], answer: 1, why: "Police, trade, commerce, agriculture and irrigation are State List subjects." },
    { q: "Power over subjects like computer software rests with:", options: ["The states", "The Union Government", "Local government", "The judiciary"], answer: 1, why: "Residuary subjects not in any list fall to the Union Government." },
    { q: "Besides Hindi, how many languages are recognised as Scheduled Languages?", options: ["14", "18", "22", "28"], answer: 2, why: "There are 22 other Scheduled Languages besides Hindi, and central examinations may be taken in any of them." },
    { q: "Changing the power-sharing arrangement requires ratification by:", options: ["All states", "At least half the states", "Two-thirds of states", "No states"], answer: 1, why: "A two-thirds majority in both Houses, followed by ratification by the legislatures of at least half the total states." },
    { q: "The head of a municipal corporation is the:", options: ["Sarpanch", "Chairperson", "Mayor", "Collector"], answer: 2, why: "The head of a municipality is the chairperson; in a municipal corporation it is the mayor." },
    { q: "The 1992 amendment reserved what share of local government seats for women?", options: ["One-fifth", "One-fourth", "One-third", "One-half"], answer: 2, why: "At least one-third of all positions in local bodies are reserved for women." },
    { q: "All the panchayat samitis in a district together form the:", options: ["Gram Sabha", "Zila Parishad", "Municipality", "Mandal"], answer: 1, why: "The zila parishad is constituted by all the panchayat samitis of a district, and includes MPs and MLAs of the district." },
  ],
  keyTopics: [
    { name: "The three lists — Union, State, Concurrent", importance: "high", note: "The most reliably tested feature of the chapter — subject counts, example subjects, who legislates, and the two clinchers (Union law prevails, residuary rests with the Union)." },
    { name: "Coming together vs holding together federations", importance: "high", note: "A standard 2–3 mark distinguish-with-examples question." },
    { name: "Decentralisation and the 1992 constitutional amendment", importance: "high", note: "Frequently a 5-mark question on the three-tier rural structure and the amendment's provisions." },
    { name: "Centre–state relations after 1990", importance: "medium", note: "Tested as a 3-mark 'how have relations changed' question, often paired with coalition politics." },
    { name: "Language policy — Hindi, Scheduled Languages, 1965", importance: "medium", note: "Often compared with Sri Lanka's language policy to bring out why India's federalism succeeded." },
    { name: "Linguistic reorganisation of states", importance: "medium", note: "The fear versus the actual outcome is a common short-answer question." },
    { name: "Residuary powers and the constitutional amendment procedure", importance: "medium", note: "One-mark recall questions that examiners return to every year." },
    { name: "Three-tier rural local government structure", importance: "low", note: "Gram Panchayat, Panchayat Samiti and Zila Parishad, with the Gram Sabha's role." },
  ],
  written: [
    { q: "Define federalism in one sentence.", marks: 1, kind: "short", importance: "high",
      answer: "Federalism is a system of government with two or more levels or tiers, in which power is divided between a central authority and various constituent units of the country, each with its own jurisdiction in matters of legislation, taxation and administration." },
    { q: "What are residuary subjects? Give one example.", marks: 1, kind: "short", importance: "medium",
      answer: "Subjects that do not fall in any of the Union, State or Concurrent Lists. The power to legislate on them rests with the Union Government. Example: <strong>computer software</strong>, which did not exist when the Constitution was framed." },
    { q: "Distinguish between 'coming together' and 'holding together' federations, with one example of each.", marks: 2, kind: "short", importance: "high",
      answer: "In a <strong>coming together</strong> federation, independent states voluntarily come together to form a bigger unit, usually with equal power — for example, the <strong>USA</strong>. In a <strong>holding together</strong> federation, a large country divides power between constituent states and the national government, with the centre usually more powerful and units sometimes unequal — for example, <strong>India</strong>." },
    { q: "Name the three lists into which the Constitution divides legislative subjects, and give one example from each.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>Union List</strong> — e.g. defence; <strong>State List</strong> — e.g. police; <strong>Concurrent List</strong> — e.g. education. The Union and States can make laws on subjects in the first two lists respectively, and both can legislate on the Concurrent List." },
    { q: "What is decentralisation? Why is it considered desirable?", marks: 2, kind: "short", importance: "high",
      answer: "Decentralisation is when power is taken away from Central and State governments and given to local governments. It is desirable because many problems are best settled at the local level, where people have better knowledge of local issues and better ideas on spending and management, and it allows people to participate directly in decision making." },
    { q: "Explain any three key features of a federal system of government.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>There are <strong>two or more levels or tiers</strong> of government, governing the same citizens, but each with its own jurisdiction.</li><li>The jurisdictions of the different tiers are specified in the <strong>constitution</strong>, so the existence and authority of each level is constitutionally guaranteed.</li><li>The fundamental provisions of the constitution <strong>cannot be changed unilaterally</strong> by one level of government; changes require the consent of both levels.</li><li><strong>Courts</strong> have the power to interpret the constitution and the powers of different levels, and act as an umpire if disputes arise.</li></ul>" },
    { q: "Describe the language policy followed by the Indian government since Independence, and explain why it succeeded where Sri Lanka's failed.", marks: 3, kind: "long", importance: "high",
      answer: "Hindi was made the official language, but it is the mother tongue of only about 40% of Indians, so <strong>22 other languages</strong> are recognised as Scheduled Languages, and central examination candidates may take the exam in any of these. States also have their own official languages. The plan to stop using English for official purposes by 1965 was abandoned after protests, and English continued alongside Hindi.<br>Unlike Sri Lanka's leaders, who imposed Sinhala as the sole official language and alienated the Tamil minority, <strong>Indian leaders adopted a cautious, accommodating attitude</strong> in spreading Hindi and were willing to compromise — which is why India's language policy did not produce the resentment and conflict Sri Lanka faced." },
    { q: "Explain any three provisions of the 1992 constitutional amendment (the 73rd and 74th Amendments) that strengthened local government in India.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>It is now <strong>constitutionally mandatory</strong> to hold regular elections to local government bodies.</li><li>Seats are <strong>reserved for Scheduled Castes, Scheduled Tribes and Other Backward Classes</strong>, and at least <strong>one-third of all positions are reserved for women</strong>.</li><li>An independent <strong>State Election Commission</strong> has been created in each state to conduct panchayat and municipal elections.</li><li>State Governments are required to <strong>share some powers and revenue</strong> with local bodies.</li></ul>" },
    { q: "Explain how federalism has been practised in India, with reference to linguistic states, language policy and centre-state relations.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Linguistic states:</strong> from 1947 to 2019, several old state boundaries were redrawn to create states based on language or on culture, ethnicity and geography, such as Nagaland, Uttarakhand and Jharkhand. Feared by some leaders as a threat to unity, this actually made the country more united and administration easier.</li><li><strong>Language policy:</strong> Hindi is the official language but the mother tongue of only about 40%, so 22 other Scheduled Languages are recognised, and the plan to phase out English by 1965 was abandoned after protests — a cautious approach that avoided Sri Lanka's mistake.</li><li><strong>Centre-state relations:</strong> for long periods the Central Government misused its powers to dismiss state governments run by rival parties. After 1990, the rise of regional parties and coalition governments at the centre, supported by a Supreme Court judgment, created a new culture of power sharing and respect for state autonomy.</li></ul>" },
    { q: "Describe the structure of rural local government in India as strengthened by the 1992 amendment.", marks: 5, kind: "long", importance: "high",
      answer: "Rural local government has <strong>three tiers</strong>.<br><ul><li>The <strong>Gram Panchayat</strong> is the village-level council of directly elected ward members (panch) headed by a sarpanch; it works under the supervision of the <strong>Gram Sabha</strong> — all voters of the village — which must meet at least twice or thrice a year to approve the budget and review performance.</li><li>The <strong>Panchayat Samiti or Block/Mandal</strong> groups several gram panchayats together, with members elected by panchayat members of the area.</li><li>The <strong>Zila Parishad</strong> brings together all the panchayat samitis of a district; most members are elected, and it also includes MPs and MLAs of the district, with a chairperson as its political head.</li></ul>The 1992 amendment made elections to these bodies mandatory, reserved seats for SC/ST/OBC and at least one-third for women, and created a State Election Commission in each state to conduct these elections." },
  ],
  assertionReason: [
    { assertion: "India is a 'holding together' federation.",
      reason: "India was formed when several independent, sovereign states voluntarily came together to form a bigger unit.",
      answer: 2, importance: "high",
      why: "A is true. R is false and actually describes a 'coming together' federation like the USA — India was formed the opposite way, by a large country dividing its power between the centre and constituent states." },
    { assertion: "If a law made by a State Legislature on a Concurrent List subject conflicts with a law made by Parliament, the law made by Parliament prevails.",
      reason: "This rule ensures uniformity across the country on subjects of common interest to the Union and the states.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R gives the correct rationale: the Concurrent List covers matters like education and marriage where a single, uniform law is preferred, so the Union law is given precedence." },
    { assertion: "Residuary powers under the Indian Constitution rest with the State Governments.",
      reason: "Subjects such as computer software did not exist at the time the Constitution was framed.",
      answer: 3, importance: "medium",
      why: "A is false — residuary powers rest with the <strong>Union Government</strong>, not the states. R is true on its own: such subjects genuinely did not exist when the Constitution was written." },
    { assertion: "The 1992 constitutional amendment made it mandatory to hold regular elections to local government bodies.",
      reason: "The amendment also created an independent State Election Commission in each state to conduct panchayat and municipal elections.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but R describes a separate, additional provision of the same amendment rather than explaining why regular elections were made mandatory." },
  ],
  caseStudies: [
    { title: "The three lists in action", importance: "high",
      source: "The Indian Constitution specifies the powers of the Union and the States through three lists of subjects. Defence, foreign affairs and currency require a uniform national policy. Police, agriculture and irrigation are best handled locally. Education, forests and trade unions are of common interest to both the Union and the States.",
      parts: [
        { q: "Name the list under which 'defence' falls, and state who can legislate on it.", marks: 1, answer: "The <strong>Union List</strong>; only the Union Government can make laws on it." },
        { q: "Name the list under which 'education' falls, and explain what happens if a State law on it conflicts with a Union law.", marks: 2, answer: "It falls in the <strong>Concurrent List</strong>. Both the Union and State Governments can legislate on it, but if their laws conflict, the <strong>law made by the Union Government prevails</strong>." },
        { q: "Under which category would a newly emerging subject, not foreseen by the Constitution's framers, fall — and who has the power to legislate on it?", marks: 1, answer: "It would be a <strong>residuary subject</strong>, and the power to legislate on it rests with the <strong>Union Government</strong>." },
        { q: "Why does the Constitution provide a Concurrent List at all, instead of dividing every subject only between the Union and the states?", marks: 1, answer: "Because some subjects — like education and marriage — are of common interest to both levels of government, and giving both the power to legislate (with Union law prevailing in case of conflict) balances national uniformity with local responsiveness." },
      ] },
    { title: "Panchayati Raj in a village", importance: "medium",
      source: "In a village, the Gram Sabha meets twice a year to approve the panchayat's budget and review its work. The sarpanch and ward members were directly elected by the villagers, and one-third of the elected seats went to women, with further seats reserved for Scheduled Caste and Scheduled Tribe candidates.",
      parts: [
        { q: "Name the three tiers of rural local government in India.", marks: 1, answer: "The <strong>Gram Panchayat</strong>, the <strong>Panchayat Samiti (Block/Mandal)</strong>, and the <strong>Zila Parishad</strong>." },
        { q: "What is the Gram Sabha, and what must it do at its meetings?", marks: 2, answer: "The Gram Sabha is the body of <strong>all voters in the village</strong>. At its meetings, held at least twice or thrice a year, it must <strong>approve the annual budget</strong> of the gram panchayat and <strong>review its performance</strong>." },
        { q: "What reservation does the Constitution guarantee for women in local bodies, and why is this significant?", marks: 1, answer: "At least <strong>one-third of all seats</strong> are reserved for women, which has brought more than 10 lakh women into elected rural and urban local bodies — a scale of political participation by women found nowhere else in the country's institutions." },
        { q: "Despite these reforms, why is decentralisation in India often described as 'incomplete'?", marks: 1, answer: "Because most State Governments have not transferred significant powers or financial resources to local governments, so local bodies often lack the funds and authority needed to function fully, even though elections and reservations are now in place." },
      ] },
  ],
};
