import type { Chapter } from "@/lib/types";

export const ch15: Chapter = {
  slug: "gender-religion-and-caste",
  num: 3,
  title: "Gender, Religion and Caste",
  unit: "civics",
  unitName: "Democratic Politics — II",
  marks: "Civics · 20 marks",
  minutes: 16,
  blurb: "Three social divisions that politics keeps running into. When politics ignores them nothing changes; when politics is reduced to them, everything breaks.",
  bigIdea: "Social divisions become dangerous not when they are expressed in politics, but when one division is treated as the only one that matters.",
  syllabus: [
    "Gender and politics — public/private division, feminist movements, women's political representation",
    "Religion, communalism and politics — forms of communalism, secularism in the Constitution",
    "Caste and politics — caste inequalities, caste in politics, politics in caste",
  ],
  blocks: [
    { t: "h", text: "Gender" },
    { t: "sim", id: "social-divisions" },
    { t: "p", html: "Gender division is a form of hierarchical social division seen everywhere, but it is <strong>rarely recognised in the study of politics</strong>. It is not based on biology but on <strong>social expectations and stereotypes</strong>. The result is a sexual division of labour in which most work inside the home — cooking, cleaning, washing, tailoring, looking after children — is done by women, or by domestic helpers who are again mostly women. This work is not valued and does not get paid." },
    { t: "list", items: [
      "Because the responsibility of housework was assigned to women, the <strong>public/private division</strong> emerged: women's role was seen as confined to the private or domestic sphere, and politics was seen as a men's affair.",
      "<strong>Feminist movements</strong> agitated for equal rights, and in the more radical women's movements the demand extended to equality in personal and family life as well. A <strong>feminist</strong> is a woman or a man who believes in equal rights and opportunities for women and men.",
      "In India, the literacy rate among women is lower than among men. A smaller proportion of girl students go for higher studies. On average an Indian woman works one hour more per day than a man, yet much of her work is not paid and therefore <strong>often not valued</strong>. The Equal Wages Act provides that equal wages should be paid for equal work, but in almost all areas of work women are paid less than men.",
      "In many parts of India parents prefer to have sons and find ways to have the girl child aborted. Such sex-selective abortion led to a <strong>decline in the child sex ratio</strong> — the number of girl children per thousand boys — to below 930 in the country.",
      "Women face <strong>harassment, exploitation and violence</strong>, and urban areas have become particularly unsafe. Even within the home they are the target of domestic violence.",
    ] },
    { t: "note", kind: "why", title: "Women in politics", html: "The proportion of women in the Lok Sabha has for most of its history been well under 15%, which is among the lowest in the world. Their share in the state assemblies is less than 5%. One way suggested to solve this is to make it <strong>legally binding to have a fair proportion of women in elected bodies</strong>. In panchayats and municipalities <strong>one-third of seats are reserved for women</strong>, and there are now more than 10 lakh elected women representatives in rural and urban local bodies. A bill to reserve one-third of seats in the Lok Sabha and state assemblies has long been pending." },
    { t: "note", kind: "trap", html: "Do not write that gender differences are natural. The chapter is explicit: gender division is <strong>not based on biology but on social expectations and stereotypes</strong>. The unequal roles are a social construction and can therefore be changed." },

    { t: "h", text: "Religion, communalism and secularism" },
    { t: "p", html: "Unlike gender differences, religious differences are often expressed in the field of politics. Gandhiji said that religion can never be separated from politics — by religion he meant not any particular religion but <strong>moral values that inform all religions</strong>. Human rights groups have argued that most victims of communal riots are people of minority communities, and that the state should take special steps to protect them. Women's movements have argued that family laws of all religions discriminate against women, so those laws should be changed. None of this is unhealthy. The problem begins when religion is expressed in politics in <strong>exclusive and partisan terms</strong>, when one religion is seen as superior, when the demands of one group are opposed to another, and when state power is used to establish domination of one religious group over the rest." },
    { t: "table", head: ["Form of communalism", "How it appears"], rows: [
      ["Everyday beliefs", "Religious prejudices, stereotypes of religious communities, and the belief in the superiority of one's religion over others — so common that we often fail to notice it"],
      ["Political dominance", "A desire to form a majoritarian dominance, or a separate political unit for one's own religious community"],
      ["Political mobilisation", "Use of sacred symbols, religious leaders, emotional appeal and plain fear to bring believers of one religion together in the political arena"],
      ["Communal violence", "In its ugliest form, communal riots, massacre and violence. India and Pakistan suffered some of the worst communal riots at the time of Partition"],
    ] },
    { t: "note", kind: "real", title: "What secular means in the Indian Constitution", html: "There is <strong>no official religion</strong> for the Indian state — unlike Buddhism in Sri Lanka, Islam in Pakistan and Christianity in England. The Constitution provides to all individuals and communities <strong>freedom to profess, practise and propagate any religion, or not to follow any</strong>. It <strong>prohibits discrimination on grounds of religion</strong>. And it allows the state to <strong>intervene in matters of religion to ensure equality within religious communities</strong> — for example banning untouchability. Secularism is not an ideology of one party or persons; it is one of the foundations of our country." },

    { t: "h", text: "Caste" },
    { t: "p", html: "Caste division is special to India. Members of the same caste group were believed to form a natural social community and to perform a hereditary occupation, and the practice of untouchability excluded some castes from equal opportunity. Political leaders and social reformers like <strong>Jotiba Phule, Gandhiji, B.R. Ambedkar and Periyar Ramaswami Naicker</strong> advocated and worked to establish a society in which caste inequalities are absent." },
    { t: "list", items: [
      "With economic development, large-scale urbanisation, growth of literacy and education, occupational mobility and the weakening of the position of landlords in villages, the <strong>old notions of caste hierarchy are breaking down</strong>. In urban areas it does not matter much who is walking along next to us on a street or eating at the next table in a restaurant.",
      "But caste has not disappeared. Most people marry within their own caste or tribe. Untouchability has not ended completely despite constitutional prohibition. Effects of centuries of advantage and disadvantage continue to be felt: the caste groups that had access to education under the old system have done very well, while those denied access have lagged behind. In this sense caste continues to be closely linked to <strong>economic status</strong>.",
    ] },
    { t: "note", kind: "idea", title: "Caste in politics, and politics in caste", html: "<strong>Caste in politics:</strong> when parties choose candidates keeping the caste composition of the constituency in mind, when they appeal to caste sentiment to muster support, and when universal adult franchise compels political leaders to mobilise and secure political support.<br><br><strong>Politics in caste:</strong> caste groups themselves get involved in politics — each caste tries to become bigger by incorporating neighbouring castes or sub-castes previously excluded; new kinds of caste groups like 'backward' and 'forward' caste groups come into being.<br><br>The exam asks for both directions. Caste alone cannot determine election results: no parliamentary constituency has a clear majority of one single caste, every party's candidates get some votes from more than one caste, and no party wins all the votes of a caste. If it were otherwise, ruling parties would never lose elections." },
    { t: "note", kind: "trap", html: "Caste politics has both faces. It has helped people from <strong>Dalit and OBC backgrounds gain better access to decision making</strong> and brought forward demands for justice. But it can also divert attention from poverty, development and corruption, and in extreme form lead to tension, conflict and violence. Write both sides." },
  ],
  examFocus: [
    "Why gender division is social, not biological, and the public/private division.",
    "The sexual division of labour and why women's work is unpaid and undervalued.",
    "Women's representation in the Lok Sabha and assemblies versus local bodies.",
    "Communalism in its four forms, from everyday prejudice to violence.",
    "The three components of Indian secularism in the Constitution.",
    "Why caste has weakened, and why it has not disappeared.",
    "Caste in politics versus politics in caste — both directions.",
    "Why caste alone cannot determine an election result.",
  ],
  flashcards: [
    { q: "Why is gender division not natural?", a: "Because it is based on social expectations and stereotypes rather than biology. Roles assigned to women and men are a social construction and can be changed." },
    { q: "What is the sexual division of labour?", a: "An arrangement in which all work inside the home — cooking, cleaning, washing, tailoring, looking after children — is done by women or female domestic helpers, while men do the work outside. The domestic work is not paid and therefore not valued." },
    { q: "What is the public/private division?", a: "The idea that women's role is confined to the private or domestic sphere, while the public sphere of politics and paid work belongs to men." },
    { q: "Who is a feminist?", a: "A woman or a man who believes in equal rights and opportunities for women and men." },
    { q: "What has happened to India's child sex ratio and why?", a: "It has fallen below 930 girls per thousand boys, because a preference for sons has led parents to have the girl child aborted." },
    { q: "How is women's representation in local bodies different from Parliament?", a: "One-third of seats in panchayats and municipalities are reserved for women, producing more than 10 lakh elected women representatives. In the Lok Sabha women have historically held under 15% of seats and under 5% in state assemblies." },
    { q: "What is communalism?", a: "The expression of religion in politics in exclusive and partisan terms — treating one religion as superior, setting one community's demands against another's, and using state power to establish the dominance of one religious group." },
    { q: "Name the forms communalism takes.", a: "Everyday beliefs and religious prejudice; the desire for majoritarian dominance or a separate political unit; political mobilisation using sacred symbols, religious leaders, emotional appeal and fear; and in its ugliest form, communal riots and violence." },
    { q: "What does secular mean in the Indian Constitution?", a: "There is no official state religion; all individuals and communities have freedom to profess, practise and propagate any religion or none; discrimination on grounds of religion is prohibited; and the state may intervene in religion to ensure equality within religious communities, as with the ban on untouchability." },
    { q: "Name four reformers who worked against caste inequality.", a: "Jotiba Phule, Mahatma Gandhi, B.R. Ambedkar and Periyar Ramaswami Naicker." },
    { q: "Distinguish caste in politics from politics in caste.", a: "Caste in politics is parties using caste in choosing candidates and appealing for support. Politics in caste is caste groups themselves entering politics — absorbing neighbouring castes, and forming new groupings such as 'backward' and 'forward' castes." },
    { q: "Why can caste alone not determine election results?", a: "No parliamentary constituency has a clear majority of one caste; every party's candidates get votes from more than one caste; and no party wins all the votes of a caste. Otherwise ruling parties would never lose an election." },
  ],
  quiz: [
    { q: "Gender division is based mainly on:", options: ["Biology", "Social expectations and stereotypes", "Economic status", "Religion"], answer: 1, why: "The chapter is explicit that gender division is not biological but rests on social expectations and stereotypes." },
    { q: "The Equal Wages Act provides that:", options: ["Women must be hired first", "Equal wages should be paid for equal work", "Women get one-third of jobs", "Domestic work must be paid"], answer: 1, why: "Despite the Act, women are paid less than men in almost all areas of work." },
    { q: "What share of seats in local bodies is reserved for women?", options: ["One-fifth", "One-fourth", "One-third", "One-half"], answer: 2, why: "At least one-third of seats in panchayats and municipalities are reserved for women." },
    { q: "India's child sex ratio has fallen below:", options: ["980", "950", "930", "900"], answer: 2, why: "Sex-selective abortion has pushed the number of girl children per thousand boys below 930." },
    { q: "A secular state is one that:", options: ["Bans all religion", "Has no official religion and does not discriminate on religious grounds", "Promotes the majority religion", "Never interferes in religious matters"], answer: 1, why: "The Indian state has no official religion, guarantees freedom of religion, prohibits religious discrimination, and may intervene to ensure equality within communities." },
    { q: "Which country has an official state religion, unlike India?", options: ["France", "Sri Lanka", "Nepal", "Canada"], answer: 1, why: "Buddhism in Sri Lanka, Islam in Pakistan and Christianity in England are named as official religions, unlike in India." },
    { q: "Parties choosing candidates by the caste composition of a constituency is:", options: ["Politics in caste", "Caste in politics", "Communalism", "Casteism only"], answer: 1, why: "That is caste shaping politics. Politics in caste is caste groups themselves changing under political pressure." },
    { q: "Caste continues to be closely linked to:", options: ["Religion", "Economic status", "Language", "Region"], answer: 1, why: "Castes with access to education under the old system have done well; those denied access have lagged behind." },
    { q: "Gandhiji's claim that religion cannot be separated from politics referred to:", options: ["Hinduism specifically", "Moral values that inform all religions", "Religious law", "Communal representation"], answer: 1, why: "By religion he meant not any particular religion but the moral values informing all religions." },
    { q: "A positive effect of caste politics has been:", options: ["Ending untouchability entirely", "Better access to decision making for Dalit and OBC groups", "Removing caste from society", "Ending poverty"], answer: 1, why: "Caste politics has helped people from Dalit and OBC backgrounds gain access to decision making and brought forward demands for justice." },
  ],
  keyTopics: [
    { name: "Gender division as social, not biological — the public/private divide", importance: "high", note: "Nearly every year an answer is expected to explicitly reject the 'natural' framing and explain the public/private split." },
    { name: "Women's political representation — Parliament vs local bodies", importance: "high", note: "The Lok Sabha/assembly figures against the one-third local body reservation is a standard compare-and-explain question." },
    { name: "Forms of communalism — belief, dominance, mobilisation, violence", importance: "high", note: "A frequent 3-mark 'explain any three forms' question, and a favourite for assertion–reason." },
    { name: "Secularism in the Indian Constitution — three features", importance: "high", note: "'What does secular mean in India' is asked almost every cycle, often contrasted with Sri Lanka, Pakistan or England." },
    { name: "Caste in politics vs politics in caste", importance: "medium", note: "A classic 5-mark 'distinguish and explain' question testing both directions of the relationship." },
    { name: "Why caste alone cannot determine an election result", importance: "medium", note: "Tested as a 3-mark justification question and as assertion–reason." },
    { name: "Sexual division of labour and unpaid work", importance: "medium", note: "Short-answer recall, often linking to the Equal Wages Act and the child sex ratio." },
    { name: "Reformers against caste inequality", importance: "low", note: "One-mark recall of Phule, Ambedkar, Gandhiji and Periyar." },
  ],
  written: [
    { q: "Who is a feminist?", marks: 1, kind: "short", importance: "medium",
      answer: "A feminist is a woman or a man who believes in <strong>equal rights and opportunities</strong> for women and men." },
    { q: "Define communalism in one sentence.", marks: 1, kind: "short", importance: "high",
      answer: "Communalism is the belief that expresses religion in politics in <strong>exclusive and partisan terms</strong> — treating one religion as superior and using state power to establish the dominance of one religious group over others." },
    { q: "What is meant by the 'public/private' division of gender roles?", marks: 2, kind: "short", importance: "high",
      answer: "Because housework was assigned almost entirely to women, their role came to be seen as confined to the <strong>private or domestic sphere</strong>, while politics, paid work and public life were seen as a men's affair — the public sphere." },
    { q: "What reservation exists for women in local government bodies, and what has been its effect?", marks: 2, kind: "short", importance: "high",
      answer: "At least <strong>one-third of seats</strong> in panchayats and municipalities are reserved for women. This has resulted in more than <strong>10 lakh elected women representatives</strong> in rural and urban local bodies." },
    { q: "Give any two examples of the sexual division of labour.", marks: 2, kind: "short", importance: "medium",
      answer: "Cooking, cleaning, washing and looking after children inside the home are done mostly by women or female domestic helpers, while paid work outside the home is treated as a man's domain. This unpaid domestic labour is not valued even though, on average, an Indian woman works about an hour more per day than a man." },
    { q: "Explain any three forms in which communalism expresses itself in politics.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Everyday beliefs</strong> — religious prejudices and stereotypes, and belief in the superiority of one's own religion, so common that they often go unnoticed.</li><li><strong>Political dominance</strong> — a desire to establish the dominance of one's own religious community, or a separate political unit for it.</li><li><strong>Political mobilisation</strong> — use of sacred symbols, religious leaders, emotional appeal and fear to bring together believers of one religion in the political arena.</li><li>In its most extreme form, <strong>communal violence</strong>, riots and massacre.</li></ul>" },
    { q: "Describe the three important features of the Indian Constitution that make India a secular state.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>India has <strong>no official religion</strong>, unlike Buddhism in Sri Lanka, Islam in Pakistan or Christianity in England.</li><li>The Constitution gives all individuals and communities <strong>freedom to profess, practise and propagate</strong> any religion, or none, and prohibits discrimination on grounds of religion.</li><li>The state may <strong>intervene in matters of religion</strong> to ensure equality within religious communities — for example, by banning untouchability.</li></ul>" },
    { q: "'Caste alone cannot determine the results of an election in India.' Justify this statement with three reasons.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>No parliamentary constituency in the country has a <strong>clear majority of one single caste</strong>, so every candidate has to seek support beyond their own caste to win.</li><li>Every party puts up candidates belonging to <strong>different castes</strong> in different constituencies, and its candidates get some votes from more than one caste.</li><li><strong>No party wins all the votes</strong> of a caste or community it appeals to, even when it fields candidates from that caste — if it were otherwise, the ruling party or candidate would never lose an election.</li></ul>" },
    { q: "Distinguish between 'caste in politics' and 'politics in caste', and explain the positive and negative effects of the use of caste in politics.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Caste in politics:</strong> when parties choose candidates keeping in mind the caste composition of a constituency, appeal to caste sentiment to gather support, and are compelled by universal adult franchise to mobilise caste groups for political support.<br><strong>Politics in caste:</strong> caste groups themselves get drawn into politics — each caste tries to enlarge itself by absorbing neighbouring castes or sub-castes, and new political groupings such as 'forward' and 'backward' castes emerge.<br><ul><li><strong>Positive effects:</strong> caste politics has helped people from Dalit and OBC backgrounds gain better access to decision making, and has brought demands for justice and equal treatment to the fore.</li><li><strong>Negative effects:</strong> it can divert attention away from other pressing issues like poverty, development and corruption, and in its extreme form can lead to tension, conflict and even violence between caste groups.</li></ul>" },
    { q: "Examine the position of women in India today with reference to literacy, wages, political representation and safety, and suggest two measures to improve their political participation.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li>The <strong>literacy rate</strong> among women remains lower than among men, and fewer girl students go on to higher studies.</li><li>Women's work is <strong>underpaid and undervalued</strong> — an Indian woman works about an hour more per day than a man on average, but much of this labour is unpaid, and even in paid work women are typically paid less than men despite the Equal Wages Act.</li><li>Their <strong>political representation</strong> is low: historically under 15% of the Lok Sabha and under 5% of state assemblies, though one-third of seats in local bodies are reserved for them.</li><li>Women face widespread <strong>harassment, exploitation and violence</strong>, including within the home.</li></ul>Two measures suggested: making it <strong>legally binding</strong> to reserve a fair proportion of seats for women in the Lok Sabha and state assemblies (as already done in local bodies), and ensuring political parties give a <strong>minimum share of election tickets</strong> to women candidates." },
  ],
  assertionReason: [
    { assertion: "Gender division is not based on biology.",
      reason: "It arises out of social expectations and stereotypes about the roles considered suitable for men and women.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains A — the sexual division of labour and the public/private divide are products of social convention, which is exactly why they can be changed." },
    { assertion: "India is a secular state.",
      reason: "The Indian Constitution names Hinduism as the official religion of the country, just as Sri Lanka names Buddhism.",
      answer: 2, importance: "high",
      why: "A is true. R is false: India has <em>no official religion</em> at all — that is precisely what makes it secular, unlike Sri Lanka, Pakistan or England, each of which does have one." },
    { assertion: "Caste determines the outcome of every election in India.",
      reason: "No parliamentary constituency in the country has a clear majority of one single caste.",
      answer: 3, importance: "high",
      why: "A is false — caste alone does not decide election results. R is true on its own, and is in fact one of the reasons <em>why</em> A is false, though as worded A makes the opposite (incorrect) claim." },
    { assertion: "One-third of seats in Panchayats and Municipalities are reserved for women in India.",
      reason: "This reservation has resulted in more than ten lakh women being elected to rural and urban local bodies.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but R describes a <em>consequence</em> of the reservation rather than the reason the reservation itself was introduced, so R does not explain A." },
  ],
  caseStudies: [
    { title: "Women in Indian legislatures", importance: "high",
      source: "For most of its history, the proportion of women members in the Lok Sabha has remained well under 15%, and their share in state assemblies has been under 5% — among the lowest such figures in the world. In panchayats and municipalities, however, one-third of seats are reserved for women, and India today has more than ten lakh elected women representatives at the local level.",
      parts: [
        { q: "Compare the representation of women in Parliament with their representation in local government bodies.", marks: 1, answer: "Women's representation is far higher in local bodies (one-third reserved, over 10 lakh elected) than in the Lok Sabha and state assemblies, where they have historically held under 15% and under 5% of seats respectively." },
        { q: "Name one legal step suggested to increase women's representation in the Lok Sabha and state assemblies.", marks: 1, answer: "Making it <strong>legally binding</strong> to reserve a fair proportion, such as one-third, of seats for women in the Lok Sabha and state assemblies, similar to the reservation already in place for local bodies." },
        { q: "Suggest a reason why reservation has succeeded in raising women's presence at the local level, while a similar law for Parliament has long been pending.", marks: 2, answer: "The 1992 constitutional amendment made local body reservation mandatory and enforceable, backed by regular elections conducted by State Election Commissions, whereas a bill reserving Lok Sabha and assembly seats for women requires political consensus and legislative passage, which has repeatedly been delayed." },
        { q: "What term describes a person, man or woman, who believes in equal rights and opportunities for men and women?", marks: 1, answer: "A <strong>feminist</strong>." },
      ] },
    { title: "When religion turns partisan", importance: "high",
      source: "Before an election in a certain state, some candidates used religious symbols and appealed to a single community to gather votes, and a few political speeches suggested that the interests and policies of the government should favour one religious group over others.",
      parts: [
        { q: "Which form of communalism is illustrated by the use of religious symbols and appeals to gather votes?", marks: 1, answer: "<strong>Political mobilisation</strong> — using sacred symbols, religious leaders, emotional appeal and fear to bring together believers of one religion in politics." },
        { q: "Name one other form in which communalism can express itself, besides political mobilisation.", marks: 1, answer: "Any one of: everyday religious prejudice and belief in the superiority of one's own religion; a desire for political dominance of one community or a separate political unit; or, in its most extreme form, communal violence." },
        { q: "How does the Indian Constitution guard against a government favouring one religious community over others?", marks: 2, answer: "It establishes no official religion, guarantees freedom to all individuals and communities to profess, practise and propagate any religion or none, and prohibits discrimination on grounds of religion — while still allowing the state to intervene to ensure equality within religious communities." },
        { q: "Does Gandhiji's statement that 'religion cannot be separated from politics' support such partisan use of religion? Explain.", marks: 1, answer: "No. By religion Gandhiji meant the <strong>moral values that inform all religions</strong>, not any particular religion — he was not endorsing the exclusive, partisan use of religion that produces communalism." },
      ] },
  ],
};
