import type { Chapter } from "@/lib/types";

export const ch16: Chapter = {
  slug: "political-parties",
  num: 4,
  title: "Political Parties",
  unit: "civics",
  unitName: "Democratic Politics — II",
  marks: "Civics · 20 marks",
  minutes: 16,
  blurb: "Nobody likes political parties much. This chapter argues that a democracy cannot exist without them, and then lists everything wrong with them anyway.",
  bigIdea: "Parties are the most visible face of democracy — and most of what people dislike about democracy is really a complaint about how parties behave.",
  syllabus: [
    "Why we need political parties — meaning and functions",
    "How many parties should we have — party systems",
    "National and state parties in India",
    "Challenges to political parties and how they can be reformed",
  ],
  blocks: [
    { t: "h", text: "What a party is, and what it does" },
    { t: "p", html: "A political party is a group of people who come together to contest elections and hold power in the government. They agree on some policies and programmes for the society with a view to promote the collective good. A party has three components: the <strong>leaders</strong>, the <strong>active members</strong> and the <strong>followers</strong>." },
    { t: "list", items: [
      "<strong>Contest elections.</strong> In most democracies elections are fought mainly among candidates put up by political parties. In India, top party leaders choose candidates for contesting elections.",
      "<strong>Put forward policies and programmes</strong> and ask voters to choose. A party reduces a vast multitude of opinions into a few basic positions which it supports.",
      "<strong>Make laws.</strong> Laws are debated and passed in the legislature, but since members belong to a party, they go by the direction of the party leadership regardless of their personal opinions.",
      "<strong>Form and run governments.</strong> Parties recruit leaders, train them and then make them ministers to run the government in the way they want.",
      "<strong>Play the role of opposition.</strong> Those who lose form the opposition — they voice different views and criticise government for its failures or wrong policies, and mobilise opposition to the government.",
      "<strong>Shape public opinion.</strong> They raise and highlight issues. Parties have lakhs of members and activists spread all over the country. Many pressure groups are the extensions of political parties.",
      "<strong>Provide access to government machinery and welfare schemes.</strong> For an ordinary citizen it is easy to approach a local party leader than a government officer. Parties have to be responsive to people's needs and demands, otherwise people can reject them in the next election.",
    ] },
    { t: "note", kind: "why", title: "Why we need them", html: "Imagine a democracy without parties. Every candidate would be independent, and <strong>nobody would be able to make any promises about any major policy changes</strong>. The government may be formed but its utility would remain uncertain, and <strong>no one would be responsible for how the country is run</strong>. In large societies only political parties can gather different views on various issues and present them to the government. The rise of political parties is directly linked to the emergence of <strong>representative democracies</strong>." },

    { t: "h", text: "How many parties" },
    { t: "sim", id: "party-system" },
    { t: "table", head: ["System", "How it works", "Where"], rows: [
      ["<strong>One-party system</strong>", "Only one party is allowed to control and run the government. This is <strong>not a democratic option</strong>, because any democratic system must allow at least two parties to compete in elections and provide a fair chance for the competing parties to come to power", "China"],
      ["<strong>Two-party system</strong>", "Power usually changes between two main parties. Several other parties may exist and contest, but only the two main parties have a serious chance of winning majority of seats", "The United States of America and the United Kingdom"],
      ["<strong>Multi-party system</strong>", "Several parties compete for power, and more than two parties have a reasonable chance of coming to power either on their own strength or in alliance with others. It often appears messy and leads to political instability, but it allows a variety of interests and opinions to enjoy political representation", "India"],
    ] },
    { t: "note", kind: "trap", html: "The chapter's judgement is important: <strong>party systems are not something a country can choose</strong>. They evolve over a long time, depending on the nature of society, its social and regional divisions, its history of politics and its system of elections. Each country develops a party system that is conditioned by its special circumstances. India evolved a multi-party system because of the enormous social and geographical diversity that is not easily absorbed by two or even three parties." },

    { t: "h", text: "National and state parties" },
    { t: "p", html: "The <strong>Election Commission</strong> registers parties and treats some as recognised political parties, giving them a unique symbol that only the official candidates of that party can use. A party that secures at least <strong>six per cent of the total votes in an election to the Legislative Assembly of a state and wins at least two seats</strong> is recognised as a <strong>State party</strong>. A party that secures at least <strong>six per cent of the total votes in Lok Sabha elections or Assembly elections in four states and wins at least four seats in the Lok Sabha</strong> is recognised as a <strong>National party</strong>." },
    { t: "note", kind: "real", title: "The six recognised national parties", html: "<strong>Aam Aadmi Party (AAP)</strong>, <strong>Bahujan Samaj Party (BSP)</strong>, <strong>Bharatiya Janata Party (BJP)</strong>, <strong>Communist Party of India — Marxist (CPI-M)</strong>, <strong>Indian National Congress (INC)</strong> and <strong>National People's Party (NPP)</strong>. The NPP is the first party from the north-east to be recognised as a national party. State parties — which the chapter prefers to call <strong>regional parties</strong> though many have a national-level political outlook — include the Samajwadi Party, Rashtriya Janata Dal, Biju Janata Dal, All India Trinamool Congress, DMK, AIADMK and many others. Over the last three decades the number and strength of state parties has expanded, making the Parliament of India politically more and more diverse, and no national party has been able to secure a majority on its own for long stretches — leading to coalition governments at the centre." },

    { t: "h", text: "Four challenges" },
    { t: "table", head: ["Challenge", "What it looks like"], rows: [
      ["<strong>Lack of internal democracy</strong>", "Power is concentrated in the hands of one or a few leaders at the top. Parties do not keep membership registers, do not hold organisational meetings, and do not conduct internal elections regularly. Ordinary members have no information about what happens inside, and no means or connections to rise. Leaders assume greater power to make decisions in the name of the party. Those who disagree find it difficult to continue, so they leave and form a new party"],
      ["<strong>Dynastic succession</strong>", "Since most parties do not practise open and transparent procedures, those already in power have an unfair advantage to favour people close to them or even their family members. In many parties the top positions are always controlled by members of one family, which is bad for democracy since people without adequate experience or popular support come to occupy positions of power. This tendency is present all over the world, including in some of the older democracies"],
      ["<strong>Money and muscle power</strong>", "Since parties are focused only on winning elections, they tend to use short-cuts. They nominate those candidates who have or can raise lots of money. Rich people and companies who give funds to parties tend to have influence on the policies and decisions of the party. In some cases parties support criminals who can win elections"],
      ["<strong>No meaningful choice</strong>", "In recent years there has been a decline in the ideological differences among parties in most parts of the world. Those who want really different policies have no option available to them. Sometimes people cannot even elect very different leaders, because the same set of leaders keeps shifting from one party to another"],
    ] },
    { t: "note", kind: "idea", title: "Reforms — what has been done and what is suggested", html: "<strong>Already done:</strong> the Constitution was amended to prevent elected MLAs and MPs from changing parties — the <strong>anti-defection law</strong> — under which an elected representative who changes parties loses the seat. The <strong>Supreme Court</strong> passed an order to reduce the influence of money and criminals: it is now mandatory for every candidate contesting elections to <strong>file an affidavit</strong> giving details of property and criminal cases pending against them. The <strong>Election Commission</strong> passed an order making it necessary for political parties to hold their organisational elections and file their income tax returns.<br><br><strong>Suggested:</strong> a law to regulate the internal affairs of parties — maintaining a register of members, following its own constitution, having an independent authority act as a judge in case of party disputes, and holding open elections to the highest posts; making it mandatory for parties to give a <strong>minimum number of tickets, about one-third, to women candidates</strong>; and <strong>state funding of elections</strong>, where the government gives parties money to support their election expenses, in kind — petrol, paper, telephone — or in cash on the basis of votes secured in the last election." },
    { t: "note", kind: "exam", html: "The chapter ends with two general lines worth borrowing for any answer on reform: <strong>people can put pressure on political parties</strong> through petitions, publicity and agitations, and ordinary citizens, pressure groups, movements and the media can play an important role; and <strong>political parties can improve if those who want this join them</strong> — the quality of democracy depends on the degree of public participation." },
  ],
  examFocus: [
    "Definition of a political party, its three components, and the seven functions.",
    "Why a democracy without parties would not work.",
    "The three party systems with the countries named, and why India has a multi-party system.",
    "The exact recognition criteria for a state party and for a national party.",
    "The six recognised national parties.",
    "The four challenges, especially dynastic succession and lack of internal democracy.",
    "Reforms already carried out — anti-defection law, affidavits, Election Commission orders.",
    "Reforms suggested, including one-third tickets to women and state funding.",
  ],
  flashcards: [
    { q: "Define a political party and name its three components.", a: "A group of people who come together to contest elections and hold power in government, agreeing on policies and programmes to promote the collective good. Its three components are the leaders, the active members and the followers." },
    { q: "Name five functions of political parties.", a: "Contesting elections; putting forward policies and programmes; making laws; forming and running governments; acting as the opposition; shaping public opinion; and providing people access to government machinery and welfare schemes." },
    { q: "What would happen in a democracy without parties?", a: "Every candidate would be independent, nobody could promise major policy changes, the government's utility would remain uncertain, and no one would be responsible for how the country is run." },
    { q: "Why is a one-party system not a democratic option?", a: "Because any democratic system must allow at least two parties to compete in elections and provide a fair chance for competing parties to come to power." },
    { q: "Why does India have a multi-party system?", a: "Because of its enormous social and geographical diversity, which is not easily absorbed by two or even three parties. Party systems are not chosen; they evolve from a country's society, divisions, political history and election system." },
    { q: "What are the criteria for recognition as a state party?", a: "Securing at least six per cent of the total votes in an election to the Legislative Assembly of a state, and winning at least two seats." },
    { q: "What are the criteria for recognition as a national party?", a: "Securing at least six per cent of the total votes in Lok Sabha elections or Assembly elections in four states, and winning at least four seats in the Lok Sabha." },
    { q: "Name the six recognised national parties.", a: "Aam Aadmi Party, Bahujan Samaj Party, Bharatiya Janata Party, Communist Party of India (Marxist), Indian National Congress and National People's Party. The Election Commission reviews this list after each general election, so the names change over time." },
    { q: "What is meant by lack of internal democracy in parties?", a: "Power is concentrated in a few leaders at the top; membership registers are not kept, organisational meetings and internal elections are not held, ordinary members have no information or means to rise, and dissenters leave to form new parties." },
    { q: "What is dynastic succession in political parties?", a: "Because parties lack open and transparent procedures, those in power favour people close to them or their own family members, so top positions in many parties are controlled by one family." },
    { q: "What is the anti-defection law?", a: "A constitutional amendment providing that an elected MLA or MP who changes parties loses their seat in the legislature, introduced to stop defections driven by the lure of office or money." },
    { q: "Name two reforms suggested for political parties.", a: "Making it mandatory for parties to give a minimum number of tickets, about one-third, to women candidates; and state funding of elections, with the government giving parties support in kind or in cash based on votes secured in the last election." },
  ],
  quiz: [
    { q: "The three components of a political party are:", options: ["Leaders, workers and voters", "Leaders, active members and followers", "President, secretary and treasurer", "Candidates, funders and media"], answer: 1, why: "A party consists of the leaders, the active members and the followers." },
    { q: "A one-party system exists in:", options: ["The United Kingdom", "China", "India", "The United States"], answer: 1, why: "China allows only one party to control and run the government, which is not a democratic option." },
    { q: "To be recognised as a state party, a party must win:", options: ["6% of votes and 2 assembly seats", "4% of votes and 4 seats", "6% of votes and 4 Lok Sabha seats", "10% of votes"], answer: 0, why: "At least six per cent of the total votes in a state assembly election, plus at least two seats." },
    { q: "To be a national party, a party needs at least:", options: ["2 Lok Sabha seats", "4 Lok Sabha seats and 6% of votes in four states", "10 Lok Sabha seats", "Recognition in every state"], answer: 1, why: "Six per cent of votes in Lok Sabha or assembly elections in four states, and at least four Lok Sabha seats." },
    { q: "Which is the first party from the north-east to be recognised as a national party?", options: ["AAP", "NPP", "BSP", "CPI-M"], answer: 1, why: "The National People's Party is the first party from the north-east to gain national party status." },
    { q: "The anti-defection law means an elected representative who changes parties:", options: ["Is fined", "Loses their seat", "Cannot contest again", "Must resign from the party"], answer: 1, why: "The constitutional amendment provides that they lose their seat in the legislature." },
    { q: "Candidates must now file an affidavit because of an order by:", options: ["Parliament", "The Election Commission", "The Supreme Court", "The President"], answer: 2, why: "A Supreme Court order made it mandatory for candidates to declare property details and pending criminal cases." },
    { q: "Which challenge involves party tickets going to those who can raise the most money?", options: ["Lack of internal democracy", "Dynastic succession", "Money and muscle power", "No meaningful choice"], answer: 2, why: "Parties focused only on winning nominate candidates who have or can raise large funds, and sometimes support criminals who can win." },
    { q: "'No meaningful choice' refers to:", options: ["Too few candidates", "Declining ideological differences among parties", "Low voter turnout", "Poor candidate quality"], answer: 1, why: "Ideological differences among parties have declined, so those wanting really different policies have no option; leaders also shift between parties." },
    { q: "State funding of elections means:", options: ["Parties fund the state", "Government supports party election expenses in kind or cash", "Only the state government funds elections", "Candidates fund themselves"], answer: 1, why: "The government would give parties money to support election expenses — in kind such as petrol, paper and telephone, or in cash based on votes secured last time." },
  ],
  keyTopics: [
    { name: "Functions of political parties", importance: "high", note: "The most reliably asked question in the chapter — 'explain any five functions' appears almost every year as a 3 or 5-mark question." },
    { name: "Recognition criteria — state and national parties", importance: "high", note: "The exact vote-share and seat thresholds are tested as factual recall and inside case studies." },
    { name: "Four challenges facing political parties", importance: "high", note: "Especially dynastic succession and lack of internal democracy — a favourite 5-mark 'explain the challenges' question." },
    { name: "Reforms already carried out", importance: "high", note: "Anti-defection law, mandatory affidavits and Election Commission orders — tested as recall and as assertion–reason." },
    { name: "Party systems — one, two, multi-party", importance: "medium", note: "'Why does India have a multi-party system' is a standard 3-mark question." },
    { name: "Reforms suggested for the future", importance: "medium", note: "One-third tickets for women and state funding of elections are commonly asked as a 2–3 mark question." },
    { name: "Components of a political party", importance: "low", note: "Leaders, active members and followers — a quick 1-mark recall." },
  ],
  written: [
    { q: "Define a political party.", marks: 1, kind: "short", importance: "high",
      answer: "A political party is a group of people who come together to <strong>contest elections</strong> and <strong>hold power in the government</strong>, agreeing on some policies and programmes for society with a view to promoting the collective good." },
    { q: "What is the anti-defection law?", marks: 1, kind: "short", importance: "high",
      answer: "A constitutional amendment providing that an elected MLA or MP who <strong>changes parties</strong> after the election <strong>loses their seat</strong> in the legislature, introduced to check defections driven by the lure of office or money." },
    { q: "State the criteria for a party to be recognised as a National party by the Election Commission.", marks: 2, kind: "short", importance: "high",
      answer: "A party must secure at least <strong>six per cent of the total votes</strong> in Lok Sabha elections or in Assembly elections held in <strong>four states</strong>, and win at least <strong>four seats in the Lok Sabha</strong>." },
    { q: "Name any two functions performed by political parties in a democracy.", marks: 2, kind: "short", importance: "high",
      answer: "Any two of: contesting elections; putting forward policies and programmes for voters to choose from; making laws in the legislature; forming and running governments; playing the role of opposition; shaping public opinion; and providing citizens access to government machinery and welfare schemes." },
    { q: "What is meant by a 'one-party system'? Name one country that has it.", marks: 2, kind: "short", importance: "medium",
      answer: "A system in which only one party is allowed to control and run the government. This is <strong>not a democratic option</strong>, since a democracy must allow at least two parties a fair chance to compete for power. <strong>China</strong> is an example." },
    { q: "Explain any three functions performed by political parties.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>Parties <strong>contest elections</strong>, and in most democracies elections are fought mainly among candidates put up by them.</li><li>They <strong>put forward policies and programmes</strong>, reducing a vast range of opinions into a few basic positions voters can choose between.</li><li>The party or parties that win form the government, while those that lose play the role of the <strong>opposition</strong>, voicing different views and criticising the government's failures.</li></ul>" },
    { q: "Explain any three major challenges faced by political parties in India today.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Lack of internal democracy</strong> — power is concentrated in one or a few leaders at the top; parties rarely hold internal elections or keep membership registers, so ordinary members have little say.</li><li><strong>Dynastic succession</strong> — since parties lack transparent procedures, those already in power favour family members for top positions, regardless of experience or popular support.</li><li><strong>Money and muscle power</strong> — parties tend to nominate candidates who can raise large sums of money, and sometimes support candidates with criminal backgrounds who can win elections.</li></ul>" },
    { q: "Suggest any three reforms that could strengthen internal democracy within political parties.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>A law requiring parties to maintain a proper <strong>register of members</strong> and follow their own constitution.</li><li>An <strong>independent authority</strong> to act as judge in case of internal party disputes.</li><li>Making it mandatory to hold <strong>open elections</strong> to the highest party posts at regular intervals.</li></ul>" },
    { q: "Explain any five functions performed by political parties in a democracy.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Contest elections</strong> — in most democracies elections are fought mainly among party candidates, and in India top leaders choose who will contest.</li><li><strong>Put forward policies and programmes</strong>, asking voters to choose between a few basic positions rather than a multitude of individual opinions.</li><li><strong>Make laws</strong> — legislators generally follow the direction of their party leadership when laws are debated and passed.</li><li><strong>Form and run governments</strong> — parties recruit and train leaders who then become ministers.</li><li><strong>Play the role of opposition</strong>, voicing alternative views and mobilising criticism of government failures.</li><li>They also <strong>shape public opinion</strong> and provide ordinary citizens easier <strong>access to government machinery</strong> than approaching an official directly.</li></ul>" },
    { q: "Describe the major challenges faced by political parties in India, and explain the reforms already carried out and those still suggested to address them.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Challenges:</strong> lack of internal democracy; dynastic succession, where top positions stay within one family; growing influence of money and muscle power in ticket distribution; and a decline in meaningful ideological choice between parties.<br><strong>Reforms already carried out:</strong> the <strong>anti-defection law</strong>, under which a defecting MLA or MP loses their seat; a <strong>Supreme Court order</strong> making it mandatory for candidates to file an affidavit declaring property and pending criminal cases; and an <strong>Election Commission order</strong> requiring parties to hold organisational elections and file income tax returns.<br><strong>Reforms suggested:</strong> a law regulating parties' internal affairs, including a members' register and open elections to top posts; making it mandatory to give a <strong>minimum share, about one-third, of tickets to women</strong>; and <strong>state funding of elections</strong> to reduce dependence on money power." },
  ],
  assertionReason: [
    { assertion: "India has evolved a multi-party system.",
      reason: "This is because of the country's enormous social and geographical diversity, which cannot easily be absorbed by two or even three parties.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R gives the correct explanation — party systems evolve from a country's social divisions and history, and India's diversity is precisely why a multi-party system took root." },
    { assertion: "An elected MP who defects to another party after the election loses their membership of the House.",
      reason: "The anti-defection law was introduced to reduce the influence of money and criminals in Indian politics.",
      answer: 2, importance: "high",
      why: "A is true — that is exactly what the anti-defection law provides. R is false: it was introduced to check defections caused by the lure of office or money, not to reduce money and criminal influence, which is instead addressed by the mandatory affidavit rule." },
    { assertion: "The Election Commission recognises a party as a State party if it secures at least six per cent of the votes in a Lok Sabha election held in that state.",
      reason: "Recognition as a State party requires securing six per cent of the votes in a state Legislative Assembly election and winning at least two seats.",
      answer: 3, importance: "medium",
      why: "A is false — state party recognition is based on Assembly election performance, not a Lok Sabha election within the state. R correctly states the actual rule." },
    { assertion: "Political parties in India are required to hold their organisational elections and file income tax returns.",
      reason: "This requirement was imposed by an order of the Election Commission of India.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly identifies the source of the requirement — an Election Commission order aimed at making parties more transparent and accountable." },
  ],
  caseStudies: [
    { title: "Recognising political parties", importance: "high",
      source: "The table below shows the performance of three parties.<br><table><thead><tr><th>Party</th><th>Election</th><th>Vote share</th><th>Seats won</th></tr></thead><tbody><tr><td>P</td><td>State Assembly (one state)</td><td>8%</td><td>3</td></tr><tr><td>Q</td><td>Lok Sabha, plus Assembly elections in four states</td><td>7% in each of those four states</td><td>5 Lok Sabha seats</td></tr><tr><td>R</td><td>State Assembly (one state)</td><td>4%</td><td>1</td></tr></tbody></table>",
      parts: [
        { q: "Which party qualifies as a 'State party'? Give the reason.", marks: 1, answer: "<strong>Party P</strong>, since it secured more than six per cent of the votes in a state Assembly election and won at least two seats." },
        { q: "Which party qualifies as a 'National party'? Give the reason.", marks: 2, answer: "<strong>Party Q</strong>, since it secured at least six per cent of the votes in Assembly elections held in four states and won at least four Lok Sabha seats — meeting the Election Commission's criteria for a national party." },
        { q: "Why does Party R fail to gain recognition despite contesting the election?", marks: 1, answer: "It secured only 4% of the vote and just 1 seat, falling short of the required six per cent votes and two seats needed for even State party recognition." },
        { q: "What advantage does a recognised party get from the Election Commission that an unrecognised party does not?", marks: 1, answer: "A <strong>unique election symbol</strong> reserved for the exclusive use of its official candidates." },
      ] },
    { title: "Why parties struggle to reform themselves", importance: "medium",
      source: "In many parties, top leadership positions have stayed within a few families for decades, candidates who can raise large sums of money are preferred over long-serving party workers, and ordinary members rarely get any information about internal decisions or organisational elections.",
      parts: [
        { q: "Name the two challenges to political parties illustrated in the passage.", marks: 2, answer: "<strong>Dynastic succession</strong> (leadership staying within families) and <strong>lack of internal democracy</strong> (members uninformed, no internal elections); the passage also touches on the <strong>money and muscle power</strong> challenge in ticket distribution." },
        { q: "Suggest one legal reform that could address each of the challenges you named.", marks: 2, answer: "For dynastic succession: mandatory open elections to top party posts at regular intervals. For lack of internal democracy: a law requiring parties to maintain a members' register and follow their own constitution, with an independent authority to settle disputes." },
        { q: "Apart from legal reforms, in what other way can political parties be made to work better, according to the chapter?", marks: 1, answer: "Ordinary citizens, pressure groups, movements and the media can put pressure on parties through petitions, publicity and agitation — and parties will improve if those who want change actually join and participate in them." },
      ] },
  ],
};
