import type { Chapter } from "@/lib/types";

export const ch17: Chapter = {
  slug: "outcomes-of-democracy",
  num: 5,
  title: "Outcomes of Democracy",
  unit: "civics",
  unitName: "Democratic Politics — II",
  marks: "Civics · 20 marks",
  minutes: 14,
  blurb: "Does democracy actually deliver? The honest answer, which the chapter gives, is: on some things clearly yes, on others it does no better than the alternatives.",
  bigIdea: "Judge democracy by the right yardstick. It is a better form of government not because it always produces better outcomes, but because it produces a government that is accountable, responsive and legitimate.",
  syllabus: [
    "How do we assess democracy's outcomes",
    "Accountable, responsive and legitimate government",
    "Economic growth and development",
    "Reduction of inequality and poverty",
    "Accommodation of social diversity",
    "Dignity and freedom of the citizens",
  ],
  blocks: [
    { t: "h", text: "The right yardstick" },
    { t: "p", html: "Democracy is a better form of government when compared with dictatorship or any other alternative, because it <strong>promotes equality among citizens</strong>, <strong>enhances the dignity of the individual</strong>, <strong>improves the quality of decision-making</strong>, <strong>provides a method to resolve conflicts</strong>, and <strong>allows room to correct mistakes</strong>." },
    { t: "note", kind: "trap", html: "Two habits of mind the chapter warns against. First, we assess democracy against very high expectations, and are then disappointed — but the fact that we expect more <em>from</em> democracy is itself a sign of its success. Second, an assessment must compare like with like: democracy against the realistic alternative, not against an ideal that no system has achieved." },

    { t: "h", text: "Accountable, responsive and legitimate" },
    { t: "sim", id: "democracy-outcomes" },
    { t: "list", items: [
      "Democracy produces a government that follows procedures and is <strong>accountable to the people</strong>. Citizens have the right and the means to examine the process of decision making — this is called <strong>transparency</strong>. In India the Right to Information Act empowers people to find out what is happening in government.",
      "The record on <strong>responsiveness</strong> is mixed. Formal representative democracy does not always translate into a government sensitive to people's needs. But democracies are the only ones that at least provide the mechanism to be responsive, and they are better than the alternatives at attending to the needs of most people.",
      "Democracies are far better at <strong>legitimacy</strong>. The evidence from surveys across the world is that people wish to be ruled by representatives elected by them, and they believe democracy is suitable for their country. Democracy's ability to generate its own support is itself an outcome that cannot be ignored.",
      "The <strong>cost</strong> is delay. Democratic government will not be able to reach a decision quickly, because it involves deliberation and negotiation. But because it has followed procedures, its decisions may be both more acceptable and more effective.",
    ] },

    { t: "h", text: "Economic growth, inequality and poverty" },
    { t: "note", kind: "why", title: "The uncomfortable finding", html: "If we consider all democracies and all dictatorships for the period from 1950 to 2000, dictatorships have a <strong>slightly higher rate of economic growth</strong>. The difference in the growth rates between the two is negligible. Within poor countries, however, dictatorships have a slightly better record. Given this record, it is <strong>difficult to argue that democracy leads to economic development</strong> — but there are many other factors at work: population size, global situation, cooperation from other countries, economic priorities. The chapter's conclusion is that when we have another factor to consider — the several other positive outcomes — <strong>we would rather prefer democracy to dictatorship</strong>." },
    { t: "p", html: "On <strong>inequality</strong>, democracies are based on political equality — all individuals have equal weight in electing representatives. Yet in actual life, democracies have not been very successful in reducing economic inequalities. A small number of ultra-rich enjoy a highly disproportionate share of wealth and incomes, and their share in the total income of the country has been increasing, while those at the bottom have very little to depend on. On <strong>poverty</strong>, in countries like Bangladesh, Nepal, India and Pakistan, poverty is a big constraint, and democratically elected governments have not addressed it as we would expect them to." },

    { t: "h", text: "Accommodating diversity, and dignity" },
    { t: "list", items: [
      "Democracies usually develop a procedure to <strong>conduct their competition</strong>. This reduces the possibility of tensions becoming explosive or violent. The example the chapter uses is Belgium, which succeeded in negotiating differences among ethnic groups through democratic means — an ability no non-democratic regime can offer.",
      "Two conditions apply. Majority and minority opinions are <strong>not permanent</strong> — a democracy must mean rule by majority opinion, not by a majority community, religion or race. And <strong>rule by majority does not become rule by majority community</strong>; if someone is barred from being in the majority on the basis of birth, then the democratic rule ceases to be accommodative.",
      "Democracies have strengthened claims of the <strong>disadvantaged and discriminated castes</strong>. Their position has become stronger in the competitive party politics, which has ensured that their voice gets heard in the making of public policies.",
      "On <strong>women's dignity</strong>: the case of women's equality is instructive. In most societies, women's role was confined to household work and family; their labour was not respected. Now the demand for equal treatment is supported by a democratic political arrangement. In non-democratic countries this unequal treatment might have been taken for granted and never questioned.",
    ] },
    { t: "note", kind: "idea", html: "The chapter's last move is the one to write in an answer: <strong>expectations from democracy also function as the criteria for judging any democratic country</strong>. When people are dissatisfied, complaints and criticism are a testimony to the success of democracy — they show that people have developed awareness and the ability to look critically at power holders. A public expression of dissatisfaction with democracy shows the <strong>success of the democratic project</strong>, because it transforms people from the status of a subject into that of a citizen." },
  ],
  examFocus: [
    "The five reasons democracy is a better form of government.",
    "Accountability, transparency and the Right to Information.",
    "Why democratic decision making is slower, and why that is acceptable.",
    "The economic growth comparison, 1950–2000, and how to answer it honestly.",
    "Democracy's poor record on economic inequality and poverty.",
    "How democracy accommodates social diversity, with the two conditions.",
    "Why complaints about democracy are evidence of its success.",
  ],
  flashcards: [
    { q: "Give five reasons democracy is a better form of government.", a: "It promotes equality among citizens, enhances the dignity of the individual, improves the quality of decision making, provides a method to resolve conflicts, and allows room to correct mistakes." },
    { q: "What is transparency in a democracy?", a: "The right and the means for citizens to examine the process of decision making. In India the Right to Information Act gives citizens this power." },
    { q: "Why is democratic decision making slow, and why does that not condemn it?", a: "Because it involves deliberation and negotiation among many people. But decisions taken after following procedures are more acceptable to people and more effective." },
    { q: "What does the evidence say about democracy and economic growth?", a: "Between 1950 and 2000, dictatorships had a slightly higher growth rate, and the difference is negligible; within poor countries dictatorships did slightly better. So it is difficult to argue that democracy causes economic development." },
    { q: "Given that record, why prefer democracy?", a: "Because economic growth depends on many other factors — population size, global situation, cooperation from other countries, economic priorities — and because democracy delivers several other positive outcomes that dictatorship cannot." },
    { q: "How have democracies performed on economic inequality?", a: "Poorly. Democracies are founded on political equality, but a small number of ultra-rich hold a highly disproportionate and growing share of wealth and income, while those at the bottom have very little." },
    { q: "How does democracy accommodate social diversity?", a: "By developing procedures to conduct political competition, which reduces the chance that differences and tensions become explosive or violent. Belgium's negotiation of ethnic differences is the standard example." },
    { q: "What are the two conditions for accommodating diversity?", a: "Majority and minority opinions must not be permanent — democracy means rule by majority opinion, not by a majority community; and rule by the majority must not become rule by a majority community, religion or race." },
    { q: "How has democracy affected disadvantaged castes?", a: "It has strengthened the claims of the disadvantaged and discriminated castes, whose position has become stronger in competitive party politics, ensuring their voice is heard in making public policies." },
    { q: "How does democracy relate to women's dignity?", a: "Women's household labour was long unrespected and their subordination taken for granted. Democratic arrangements support the demand for equal treatment; in a non-democratic setting unequal treatment might never have been questioned." },
    { q: "Why are complaints about democracy a sign of its success?", a: "Because they show people have developed the awareness and the ability to look critically at power holders — the transformation of a subject into a citizen." },
    { q: "Why do we judge democracy so harshly?", a: "Because we assess it against very high expectations. The fact that people expect more from democracy is itself a testimony to its success." },
  ],
  quiz: [
    { q: "The Right to Information Act mainly promotes:", options: ["Economic growth", "Transparency", "Political equality", "Social diversity"], answer: 1, why: "It gives citizens the means to examine the process of decision making, which is transparency." },
    { q: "Between 1950 and 2000, economic growth in dictatorships was:", options: ["Far higher", "Slightly higher", "Far lower", "Identical"], answer: 1, why: "Dictatorships had a slightly higher rate of growth, though the difference is negligible." },
    { q: "Democracies have been least successful at reducing:", options: ["Political inequality", "Economic inequality", "Caste discrimination", "Communal violence"], answer: 1, why: "Despite political equality, democracies have not reduced economic inequalities; the share of the ultra-rich has grown." },
    { q: "Democratic decision making is slower because:", options: ["Leaders are inefficient", "It involves deliberation and negotiation", "Laws are complicated", "There are too many parties"], answer: 1, why: "Deliberation and negotiation take time, but make the resulting decisions more acceptable and effective." },
    { q: "Which country is the chapter's example of accommodating social diversity?", options: ["Sri Lanka", "Belgium", "Pakistan", "China"], answer: 1, why: "Belgium negotiated differences among ethnic groups through democratic means." },
    { q: "Democracy must mean rule by:", options: ["The majority community", "Majority opinion", "The largest religion", "The strongest party permanently"], answer: 1, why: "Majority and minority opinions are not permanent; rule by the majority must not become rule by a majority community." },
    { q: "A legitimate government is one that:", options: ["Wins the most seats", "Is people's own government, elected by them", "Grows the economy fastest", "Never faces criticism"], answer: 1, why: "Surveys across the world show people wish to be ruled by representatives elected by them and believe democracy suits their country." },
    { q: "Public complaints about democracy indicate:", options: ["Democracy is failing", "The success of the democratic project", "The need for dictatorship", "Low political awareness"], answer: 1, why: "Complaints show people have the awareness and ability to look critically at power holders — subjects becoming citizens." },
    { q: "Democracy's record on poverty in South Asia has been:", options: ["Excellent", "Not as good as expected", "Irrelevant", "Better than dictatorships everywhere"], answer: 1, why: "In Bangladesh, Nepal, India and Pakistan, poverty remains a big constraint and elected governments have not addressed it as expected." },
    { q: "Which is NOT listed as a reason democracy is better?", options: ["It enhances individual dignity", "It guarantees faster economic growth", "It allows room to correct mistakes", "It provides a method to resolve conflicts"], answer: 1, why: "The evidence on growth is at best neutral; the chapter never claims democracy guarantees faster growth." },
  ],
  keyTopics: [
    { name: "Five reasons democracy is a better form of government", importance: "high", note: "The chapter's opening list is asked almost every year as a direct 3–5 mark recall-and-explain question." },
    { name: "Accountable, responsive and legitimate government", importance: "high", note: "Frequently tested together as a 5-mark question, with transparency and the RTI Act as supporting detail." },
    { name: "Economic growth — democracy vs dictatorship, 1950–2000", importance: "high", note: "The 'uncomfortable finding' is a classic case-study and assertion-reason source; examiners want the honest, nuanced answer, not a one-sided one." },
    { name: "Democracy's record on inequality and poverty", importance: "high", note: "A reliable 3-mark 'has democracy reduced inequality' question, usually answered with the ultra-rich income-share point." },
    { name: "Accommodation of social diversity — Belgium and the two conditions", importance: "high", note: "Tested with the Belgium example and the two conditions for accommodation, often linking back to the Power Sharing chapter." },
    { name: "Dignity and freedom — disadvantaged castes and women", importance: "medium", note: "A supporting point in longer answers on democracy's social outcomes." },
    { name: "Why complaints about democracy are a sign of its success", importance: "medium", note: "The chapter's closing argument, often asked as a standalone 3-mark 'explain' question." },
  ],
  written: [
    { q: "What is transparency in the context of a democratic government?", marks: 1, kind: "short", importance: "high",
      answer: "Transparency is the right and the means available to citizens to <strong>examine the process of decision making</strong> of their government." },
    { q: "Name the Act that empowers Indian citizens to examine government decision-making.", marks: 1, kind: "short", importance: "medium",
      answer: "The <strong>Right to Information (RTI) Act</strong>." },
    { q: "Give the evidence-based comparison of economic growth rates of democracies and dictatorships between 1950 and 2000.", marks: 2, kind: "short", importance: "high",
      answer: "Considering all democracies and all dictatorships over this period, dictatorships recorded a <strong>slightly higher rate of economic growth</strong>, though the difference between the two is negligible. Within poor countries specifically, dictatorships had a marginally better record." },
    { q: "State the two conditions necessary for a democracy to accommodate social diversity successfully.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>(i)</strong> Majority and minority opinions must not be treated as permanent and fixed — democracy must mean rule by majority <em>opinion</em>, not rule by a majority <em>community</em>. <strong>(ii)</strong> Rule by the majority must never become rule by a majority community, religion or race; no one should be permanently barred from being in the majority on the basis of birth." },
    { q: "Why is democratic decision making slower than in other forms of government? Is this necessarily a weakness?", marks: 2, kind: "short", importance: "medium",
      answer: "It is slower because it involves <strong>deliberation and negotiation</strong> among many people and institutions before a decision is reached. This is not simply a weakness, because decisions taken after following due procedure tend to be <strong>more acceptable to people and more effective</strong> in the long run." },
    { q: "Explain, with examples, how democracies have strengthened the claims of disadvantaged castes and women.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>Democracies have strengthened the claims of <strong>disadvantaged and discriminated castes</strong>, whose position has grown stronger through competitive party politics, ensuring their voice is heard in public policymaking.</li><li>On <strong>women's dignity</strong>: women's role was long confined to household work and their labour was undervalued. A democratic political arrangement supports the demand for equal treatment, whereas in a non-democratic society such inequality might never have been questioned at all.</li></ul>" },
    { q: "'Democracy's record in reducing economic inequality has been poor.' Explain this statement with reference to India.", marks: 3, kind: "long", importance: "high",
      answer: "Democracies are founded on <strong>political equality</strong> — every citizen has equal weight in electing representatives — but this has not translated into economic equality. A <strong>small number of ultra-rich</strong> people enjoy a highly disproportionate and growing share of the country's wealth and income, while those at the bottom have very little to depend on. In countries like India, Bangladesh, Nepal and Pakistan, <strong>poverty remains a major constraint</strong>, and democratically elected governments have not addressed it as effectively as expected." },
    { q: "Distinguish between the accountability, responsiveness and legitimacy of a democratic government.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Accountability</strong> means the government follows proper procedures and can be examined by citizens — transparency laws like the RTI Act support this.</li><li><strong>Responsiveness</strong> is mixed: formal representative democracy does not always translate into a government sensitive to people's needs, though democracies at least provide a mechanism for it.</li><li><strong>Legitimacy</strong> is strong: worldwide surveys show people prefer to be ruled by their own elected representatives and believe democracy suits their country, so a democratic government generates its own support even when particular decisions are unpopular.</li></ul>" },
    { q: "Examine democracy as a form of government with reference to the outcomes it is expected to produce, on economic growth, reduction of inequality and accommodation of social diversity.", marks: 5, kind: "long", importance: "high",
      answer: "<ul><li><strong>Economic growth:</strong> between 1950 and 2000, dictatorships had a slightly higher average growth rate than democracies, but the gap is negligible, and growth depends on many other factors — population, global conditions, cooperation from other countries — not on regime type alone.</li><li><strong>Reduction of inequality:</strong> despite political equality, democracies have not been very successful at reducing economic inequality; the share of income going to the ultra-rich has grown while those at the bottom have gained little, and poverty remains a serious constraint in countries like India.</li><li><strong>Accommodation of diversity:</strong> democracies develop procedures to conduct political competition peacefully, reducing the chance that social tensions turn violent — Belgium's negotiated settlement among ethnic groups is the standard example — provided majority rule is understood as rule by majority opinion, not by a fixed majority community.</li></ul>Taken together, democracy does not guarantee superior economic outcomes, but it clearly outperforms dictatorship on legitimacy, accountability and the peaceful accommodation of diversity." },
    { q: "'Every dissatisfaction with democracy in fact reflects an aspiration for democracy.' Explain this statement, and list the reasons why democracy is considered a better form of government than dictatorship.", marks: 5, kind: "long", importance: "high",
      answer: "We tend to judge democracy against very high expectations, and are disappointed when it falls short — but the very fact that we expect so much <em>from</em> democracy is itself testimony to its success. A public expression of dissatisfaction shows that people have developed the <strong>awareness and the ability to look critically</strong> at power holders, transforming them from mere subjects into citizens — this is the success of the democratic project, not its failure.<br><strong>Reasons democracy is considered better:</strong><ul><li>It promotes <strong>equality</strong> among citizens.</li><li>It enhances the <strong>dignity of the individual</strong>.</li><li>It improves the <strong>quality of decision-making</strong> through deliberation.</li><li>It provides a <strong>method to resolve conflicts</strong> peacefully.</li><li>It allows <strong>room to correct mistakes</strong>, since decisions can be revisited and leaders changed through elections.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Between 1950 and 2000, the difference in economic growth rates between democracies and dictatorships was negligible.",
      reason: "Economic growth depends on several factors, such as population size, the global situation and cooperation from other countries, and not only on the type of regime.",
      answer: 0, importance: "high",
      why: "Both statements are true, and R correctly explains why the growth-rate gap is so small — regime type is only one of many factors affecting a country's growth." },
    { assertion: "A democratic government is considered a legitimate government.",
      reason: "This is because every democratic government succeeds in completely eliminating corruption.",
      answer: 2, importance: "high",
      why: "A is true — legitimacy is one of democracy's strongest outcomes. R is false: legitimacy comes from being people's own government, elected by them, not from any claim that democracies eliminate corruption." },
    { assertion: "Rule by majority in a democracy means rule by the majority community.",
      reason: "Majority and minority opinions are not fixed or permanent in a democracy — today's majority can become tomorrow's minority.",
      answer: 3, importance: "high",
      why: "A is false: democracy means rule by majority <em>opinion</em>, and rule by the majority must never become rule by a majority community, religion or race. R is true on its own, and is in fact the reason A is wrong." },
    { assertion: "India has a Right to Information Act that empowers citizens to examine government decisions.",
      reason: "Democracies are better than dictatorships at providing legitimacy, since people prefer to be ruled by representatives elected by them.",
      answer: 1, importance: "medium",
      why: "Both statements are true independently, but R is about legitimacy while A is about transparency — R does not explain why the RTI Act exists or how it works." },
  ],
  caseStudies: [
    { title: "Growth rates: democracy and dictatorship", importance: "high",
      source: "Between 1950 and 2000, if we consider all countries classified as democracies and all classified as dictatorships, the dictatorships recorded a slightly higher average rate of economic growth than the democracies — though the difference between the two was very small. Among poor countries specifically, dictatorships had a marginally better record.",
      parts: [
        { q: "According to this data, which regime type has grown faster on average?", marks: 1, answer: "<strong>Dictatorships</strong>, though only marginally." },
        { q: "Does this mean democracy causes slower economic growth? Give one reason for your answer.", marks: 2, answer: "Not necessarily. The difference in growth rates is negligible, and economic growth is shaped by many factors besides the type of regime, so it is difficult to conclude that democracy itself causes slower growth." },
        { q: "Name two factors, other than the type of regime, that affect a country's economic growth.", marks: 1, answer: "Any two of: population size, the global economic situation, cooperation from other countries, and a country's economic priorities." },
        { q: "Despite this record, why would you still prefer democracy to dictatorship?", marks: 1, answer: "Because democracy delivers several other outcomes dictatorship cannot — greater accountability, legitimacy, dignity for citizens, and peaceful accommodation of social diversity — which matter alongside, and arguably more than, the growth-rate difference." },
      ] },
    { title: "A dispute over faster decisions", importance: "medium",
      source: "A student argues that dictatorship is a better system because it can implement decisions quickly without wasting time on debates in the assembly, while democracy involves prolonged discussion before any decision is taken.",
      parts: [
        { q: "Do you agree that quick decision-making is always desirable? Explain in one line.", marks: 1, answer: "Not necessarily — a quick decision taken without consultation may be less acceptable and harder to correct if it turns out to be wrong." },
        { q: "Why do democratic governments take more time to arrive at decisions?", marks: 1, answer: "Because democratic decision-making involves <strong>deliberation and negotiation</strong> among many representatives and institutions before a decision is finalised." },
        { q: "What advantage does the resulting decision have, despite the delay?", marks: 1, answer: "Because it has followed due procedure, the decision tends to be <strong>more acceptable to people and more effective</strong> once implemented." },
        { q: "Give two reasons, other than speed of decision-making, why a democratic government is considered better than a dictatorship.", marks: 2, answer: "Any two of: it is more accountable to the people; it enjoys greater legitimacy, since people prefer being ruled by their own elected representatives; it enhances the dignity of the individual; and it provides a peaceful method to resolve conflicts and correct mistakes." },
      ] },
  ],
};
