import type { Chapter } from "@/lib/types";

export const ch18: Chapter = {
  slug: "development",
  num: 1,
  title: "Development",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 16,
  blurb: "Everyone wants development, but a landless labourer and a rich farmer want opposite things. This chapter is about how you measure something people define differently.",
  bigIdea: "Income matters, but it is not the whole of development. What people can do and be — live long, stay healthy, learn — matters at least as much.",
  syllabus: [
    "What development promises — different people, different goals",
    "Income and other goals",
    "National development",
    "How to compare different countries or states",
    "Income and other criteria — the Human Development Report",
    "Sustainability of development",
  ],
  blocks: [
    { t: "h", text: "Different people, different goals" },
    { t: "p", html: "Different persons can have different developmental goals, and <strong>what may be development for one may not be development for the other</strong> — it may even be destructive for the other. A landless rural labourer wants more days of work and better wages, and for the local school to teach their children well. A prosperous farmer from the same village wants assured high family income through higher support prices and cheap labourers — which directly conflicts with the labourer's goal. An industrialist wants more electricity and better roads; an Adivasi from Narmada valley may want the dam that provides that electricity not to be built at all." },
    { t: "note", kind: "idea", html: "Two ideas do most of the work in this chapter. First, people seek things that are the <strong>most important for them</strong> — and these need not always be the same. Second, <strong>money cannot buy all the goods and services</strong> you need to live well. Money cannot buy a pollution-free environment, unadulterated medicines, or protection from an infectious disease if your neighbours are not vaccinated. Income is one of the most important components, but along with income people also seek <strong>equal treatment, freedom, security, and respect from others</strong>. They resent discrimination." },

    { t: "h", text: "Comparing countries — the income measure" },
    { t: "sim", id: "development-compare" },
    { t: "p", html: "For comparing countries, their <strong>income</strong> is considered to be one of the most important attributes. Countries with higher income are more developed than others with less income. But the total income of a country is not a useful comparison, because countries have different populations. So we compare the <strong>average income</strong> — the total income of the country divided by its total population, also called <strong>per capita income</strong>." },
    { t: "note", kind: "real", title: "The World Bank classification", html: "The <strong>World Development Report</strong>, brought out by the World Bank, uses per capita income to classify countries. On the 2017 figures the textbook quotes, countries with per capita income of <strong>US$ 12,056 per annum and above</strong> were called <strong>rich countries</strong>, and those with <strong>US$ 955 or less</strong> were called <strong>low-income countries</strong>. India comes in the category of <strong>low middle income countries</strong>, because its per capita income in 2017 was just <strong>US$ 1,820 per annum</strong>. The rich countries, excluding those of West Asia and certain other small countries, are generally called <strong>developed countries</strong>. The World Bank revises the cut-offs every year, so quote the year with the figure — the marks are for the method, not the number." },
    { t: "note", kind: "trap", html: "The core limitation of average income: it <strong>hides disparities</strong>. Two countries with the same average income can be very different — in one, most people have roughly similar incomes; in the other, a few are extremely rich and most are extremely poor. Averages are useful for comparison, but they do not tell us how income is distributed." },

    { t: "h", text: "Beyond income" },
    { t: "table", head: ["Indicator", "What it measures"], rows: [
      ["<strong>Infant Mortality Rate (IMR)</strong>", "The number of children that die before the age of one year as a proportion of <strong>1,000 live children</strong> born in that particular year"],
      ["<strong>Literacy Rate</strong>", "The proportion of literate population in the <strong>7 and above age group</strong>"],
      ["<strong>Net Attendance Ratio</strong>", "The total number of children of age group 6–10 attending school as a percentage of total number of children in the same age group"],
      ["<strong>Body Mass Index (BMI)</strong>", "Weight in kilograms divided by the square of height in metres. Below 18.5 is <strong>undernourished</strong>; above 25 is <strong>overweight</strong>. This is a rough measure and does not apply to growing children"],
      ["<strong>Human Development Index (HDI)</strong>", "Combines per capita income, life expectancy at birth, and the education levels of people, into a single ranking published by the UNDP"],
    ] },
    { t: "note", kind: "why", title: "The Kerala lesson", html: "The comparison the exam always uses: <strong>Haryana has a higher per capita income than Kerala, but Kerala has a lower infant mortality rate and a higher literacy rate</strong>. The reason is that Kerala has a much better performance in terms of <strong>basic health and educational facilities</strong> — the public distribution system, the schools, the primary health centres. Money in your pocket cannot buy you a pollution-free environment or an adequate supply of safe drinking water if the collective facilities do not exist. Development therefore requires <strong>collective provision</strong> alongside individual income." },
    { t: "note", kind: "real", html: "The <strong>Public Distribution System (PDS)</strong> is the ration shop system, and the states where it functions well have better nutrition and health outcomes. Note also that <strong>about half of the children in India are undernourished</strong> despite India being self-sufficient in food grains — a fact that separates food availability from food security." },

    { t: "h", text: "Sustainability" },
    { t: "p", html: "The question of development is not just about the present. <strong>Sustainability of development</strong> asks whether the levels of development we have achieved can be maintained for future generations. Two examples the chapter uses. <strong>Groundwater</strong>: it is a renewable resource, but overuse means it is not being replenished — 300 districts have reported a fall in water levels of over 4 metres during the past 20 years, and nearly one-third of the country is overusing groundwater reserves. <strong>Crude oil</strong>: the reserves will last only a few decades at current rates of use, and it is unevenly distributed, with a very large share in West Asia." },
    { t: "note", kind: "idea", html: "Two points that carry marks. First, the consequences of environmental degradation <strong>do not respect national or state boundaries</strong> — this issue is no longer region- or nation-specific, and our future is linked together. Second, scientists have been warning that the present type and levels of development are not sustainable, so the challenge is to find a path that keeps the resource base intact for the generations that follow." },
  ],
  examFocus: [
    "Conflicting developmental goals — landless labourer versus prosperous farmer, industrialist versus Adivasi.",
    "Why money cannot buy everything people need, with examples.",
    "Average income, its definition, and why it hides disparities.",
    "The World Bank cut-offs and India's classification.",
    "Definitions of IMR, literacy rate, net attendance ratio and BMI.",
    "The Kerala–Haryana comparison and the public provision argument.",
    "What HDI combines, and who publishes it.",
    "Sustainability, with the groundwater and crude oil examples.",
  ],
  flashcards: [
    { q: "Why do different people have different developmental goals?", a: "Because people seek what is most important for them, and these need not be the same. A landless labourer wants more work days and better wages; a prosperous farmer wants higher support prices and cheap labour. What is development for one may be destructive for the other." },
    { q: "Name things money cannot buy that people still need.", a: "A pollution-free environment, unadulterated medicines, protection from infectious disease when neighbours are unvaccinated, and equal treatment, freedom, security and respect from others." },
    { q: "What is average or per capita income?", a: "The total income of a country divided by its total population. It is used to compare countries because total income alone ignores differences in population size." },
    { q: "Give the World Bank income cut-offs used in the chapter.", a: "On the 2017 figures, countries with per capita income of US$ 12,056 per annum and above were called rich countries, and those with US$ 955 or less were called low-income countries. The World Bank revises these cut-offs each year." },
    { q: "Why is India classified as a low middle income country?", a: "Because its per capita income in 2017 was just US$ 1,820 per annum, well below the rich-country threshold." },
    { q: "What is the main limitation of average income?", a: "It hides disparities. Two countries with the same average income can differ completely in how that income is distributed between rich and poor." },
    { q: "Define Infant Mortality Rate.", a: "The number of children that die before the age of one year as a proportion of 1,000 live children born in that particular year." },
    { q: "Define literacy rate and net attendance ratio.", a: "Literacy rate is the proportion of the literate population in the 7-and-above age group. Net attendance ratio is the number of children aged 6 to 10 attending school as a percentage of all children in that age group." },
    { q: "What is BMI and what do its values mean?", a: "Weight in kilograms divided by the square of height in metres. Below 18.5 means undernourished; above 25 means overweight. It is a rough measure and does not apply to growing children." },
    { q: "What does the Human Development Index combine?", a: "Per capita income, life expectancy at birth, and educational levels of the population, published by the UNDP in the Human Development Report." },
    { q: "Why does Kerala do better than Haryana on human development despite lower income?", a: "Because Kerala has far better basic health and educational facilities — schools, primary health centres and an effective public distribution system. Individual income cannot substitute for collective provision." },
    { q: "Give two examples of unsustainable resource use in India.", a: "Groundwater — 300 districts reported water levels falling over 4 metres in twenty years, and about a third of the country is overusing reserves. Crude oil — reserves will last only a few decades and are concentrated in West Asia." },
  ],
  quiz: [
    { q: "Average income is also called:", options: ["Total income", "Per capita income", "National income", "Gross income"], answer: 1, why: "Average income is total income divided by total population, known as per capita income." },
    { q: "India's per capita income in 2017 was about:", options: ["US$ 955", "US$ 1,820", "US$ 12,056", "US$ 500"], answer: 1, why: "That figure places India in the low middle income category." },
    { q: "Infant Mortality Rate is measured per:", options: ["100 live births", "1,000 live births", "10,000 people", "1 lakh people"], answer: 1, why: "It is deaths before age one per 1,000 live children born in that year." },
    { q: "Literacy rate covers the age group:", options: ["6 and above", "7 and above", "10 and above", "15 and above"], answer: 1, why: "It is the proportion of the literate population in the 7-and-above age group." },
    { q: "A BMI below 18.5 indicates a person is:", options: ["Overweight", "Undernourished", "Healthy", "Obese"], answer: 1, why: "Below 18.5 is undernourished; above 25 is overweight. The measure does not apply to growing children." },
    { q: "The Human Development Report is published by:", options: ["The World Bank", "UNDP", "WHO", "The Indian government"], answer: 1, why: "The UNDP publishes the HDR, which ranks countries using income, life expectancy and education." },
    { q: "Kerala has a lower infant mortality rate than Haryana because it has:", options: ["Higher per capita income", "Better basic health and education facilities", "A smaller population", "More industries"], answer: 1, why: "Kerala's public provision of health and education outperforms Haryana's despite Haryana's higher income." },
    { q: "The main limitation of using average income to compare countries is that it:", options: ["Is hard to calculate", "Hides how income is distributed", "Ignores population", "Uses the wrong currency"], answer: 1, why: "Averages conceal disparities between rich and poor within a country." },
    { q: "Roughly what share of Indian children are undernourished?", options: ["One-tenth", "One-quarter", "About half", "Three-quarters"], answer: 2, why: "About half of India's children are undernourished, despite the country being self-sufficient in food grains." },
    { q: "Sustainability of development is mainly about:", options: ["Raising income fastest", "Whether present levels can be maintained for future generations", "Balancing exports and imports", "Reducing unemployment"], answer: 1, why: "It asks whether the resource base supporting current development will still exist for the generations that follow." },
  ],
  keyTopics: [
    { name: "Average / per capita income and the World Bank classification", importance: "high", note: "The standard opening 1–3 mark question, and the base for most numericals in this chapter." },
    { name: "Limitations of using income alone to compare development", importance: "high", note: "Almost always tested — 'averages hide disparities' is the phrase the board wants." },
    { name: "Development indicators beyond income — IMR, literacy rate, net attendance ratio, BMI, HDI", importance: "high", note: "Definitions are reliable 1–2 markers; HDI's three components are a common 2–3 mark question." },
    { name: "The Kerala–Haryana style comparison and the role of public facilities", importance: "high", note: "The go-to case-study and 5-mark 'explain why income is not enough' answer." },
    { name: "Different people, different developmental goals", importance: "medium", note: "Opening-paragraph theme; tested as a 2–3 mark 'explain with example' question." },
    { name: "Sustainability of development — groundwater and crude oil examples", importance: "medium", note: "A reliable 3–5 mark question; know both named examples." },
    { name: "What money cannot buy", importance: "medium", note: "Feeds both the 'different goals' answers and the sustainability argument." },
  ],
  written: [
    { q: "What is per capita income? By what other name is it known?", marks: 1, kind: "short", importance: "high",
      answer: "Per capita income is the total income of a country divided by its total population. It is also called <strong>average income</strong>." },
    { q: "What does the Human Development Index (HDI) measure, and who publishes it?", marks: 1, kind: "short", importance: "high",
      answer: "The HDI combines <strong>per capita income, life expectancy at birth, and educational levels</strong> of a country's people into a single ranking. It is published every year by the <strong>UNDP</strong> in the Human Development Report." },
    { q: "Why do different people have different developmental goals? Illustrate with an example.", marks: 2, kind: "short", importance: "high",
      answer: "People seek what is <strong>most important or valuable for them</strong>, and this need not be the same for everyone — what is development for one person can even be destructive for another.<br><strong>Example:</strong> a landless labourer may want more days of work and higher wages, while a prosperous farmer from the same village wants higher support prices and cheap labour — a goal that directly conflicts with the labourer's." },
    { q: "State two limitations of using average (per capita) income to compare the development of different countries.", marks: 2, kind: "short", importance: "high",
      answer: "<ul><li>It <strong>hides disparities</strong> — two countries with the same average income can have very different distributions of that income between rich and poor.</li><li>It says nothing about <strong>other goals</strong> people value, such as equal treatment, freedom, security, health and education, which money by itself cannot buy.</li></ul>" },
    { q: "The total income of Country X is $40,000 million and its population is 20 million. The total income of Country Y is $30,000 million and its population is 10 million. Calculate the per capita income of each country and state which one would be considered more developed on this basis alone.", marks: 2, kind: "numerical", importance: "high",
      answer: "Per capita income of X = 40,000 ÷ 20 = <strong>$2,000</strong>.<br>Per capita income of Y = 30,000 ÷ 10 = <strong>$3,000</strong>.<br>Even though X has a higher <em>total</em> income, <strong>Country Y has the higher per capita income</strong> and would be considered more developed on this criterion — this is exactly why total income is not used for comparison, only average income." },
    { q: "A person weighs 45 kg and is 1.60 m tall. Calculate the person's BMI and classify their nutritional status. If the same person's weight rises to 55 kg with no change in height, what would their new BMI and status be?", marks: 3, kind: "numerical", importance: "medium",
      answer: "BMI = weight (kg) ÷ [height (m)]².<br>Initially: BMI = 45 ÷ (1.60)² = 45 ÷ 2.56 ≈ <strong>17.6</strong> — below 18.5, so the person is <strong>undernourished</strong>.<br>After weight gain: BMI = 55 ÷ 2.56 ≈ <strong>21.5</strong> — between 18.5 and 25, so the person is now in the <strong>normal/healthy range</strong>.<br>(Note: BMI is a rough measure and does not apply to growing children.)" },
    { q: "Why do we need to look at criteria other than income to judge the development of a state or country? Explain with an example.", marks: 3, kind: "long", importance: "high", years: "AI 2019, 2015",
      answer: "Income alone does not tell us how people actually live, because money cannot buy every good and service needed for a good life — it cannot buy a pollution-free environment or protection from disease if collective facilities are absent. <br><strong>Example:</strong> a state with a higher per capita income can still have a <em>higher</em> infant mortality rate and <em>lower</em> literacy rate than a state with lower income, because the second state provides better public health and education facilities. So criteria like IMR, literacy rate and HDI, alongside income, give a fuller picture of development." },
    { q: "Explain, with examples, why money cannot buy all the goods and services a person needs to live well.", marks: 3, kind: "short", importance: "medium",
      answer: "<ul><li>Money cannot buy a <strong>pollution-free environment</strong> — if the air and water around you are contaminated, no amount of personal income fixes that.</li><li>Money cannot guarantee <strong>unadulterated medicines</strong> or protection from an infectious disease if the neighbourhood is not vaccinated — these depend on collective, public action.</li><li>Along with income, people seek <strong>equal treatment, freedom, security and respect</strong>, none of which can be purchased.</li></ul>" },
    { q: "What is meant by the sustainability of development? Explain with the examples of groundwater and crude oil given in the chapter.", marks: 5, kind: "long", importance: "high", years: "2016, 2013",
      answer: "Sustainability of development asks whether the levels of development achieved today can be <strong>maintained for future generations</strong>, without exhausting the resource base they will need.<ul><li><strong>Groundwater:</strong> it is a renewable resource, but excessive use means it is not being replenished — about 300 districts have reported groundwater levels falling by more than 4 metres over 20 years, and nearly a third of the country is overusing its groundwater reserves.</li><li><strong>Crude oil:</strong> known reserves will last only a few decades at current rates of use, and the reserves are very unevenly distributed, with a large share concentrated in West Asia.</li></ul>Both examples show that if resources are used up faster than they are replenished or discovered, future generations will inherit a poorer resource base — and since environmental degradation does not respect national boundaries, this is a shared global challenge." },
    { q: "\"Income is important, but it is not the only thing people seek from development.\" Explain this statement with examples of other goals people value.", marks: 5, kind: "long", importance: "high",
      answer: "Income is one of the most important components of development, since it allows people to buy goods and services. But alongside income, people seek several other things:<ul><li><strong>Equal treatment</strong> and freedom from discrimination — people resent being treated unequally because of their community, gender or region.</li><li><strong>Security</strong> — job security, and safety from crime and violence.</li><li><strong>Freedom</strong> and <strong>respect from others</strong>, which money cannot buy.</li><li>A <strong>clean environment</strong>, safe drinking water and freedom from disease, which depend on collective public provision rather than individual spending power.</li><li><strong>Basic health and educational facilities</strong> — the Kerala example shows that a state can have lower per capita income yet a much better quality of life because it provides these well.</li></ul>This is why development reports use indicators such as IMR, literacy rate and HDI in addition to per capita income." },
  ],
  assertionReason: [
    { assertion: "Kerala has a lower infant mortality rate than Haryana.",
      reason: "Kerala has a higher per capita income than Haryana.",
      answer: 2, importance: "high",
      why: "A is true — Kerala's IMR is indeed lower. But R is false: Kerala's per capita income is actually <em>lower</em> than Haryana's; Kerala's better outcome comes from superior public health and education facilities, not higher income." },
    { assertion: "Per capita income alone is a sufficient criterion to compare the development of two countries.",
      reason: "Averages can hide how income is actually distributed among the population.",
      answer: 3, importance: "high",
      why: "A is false — per capita income alone is not sufficient, precisely because of the reason given. R is true and explains why average income by itself is an inadequate measure, so it is the correct explanation of why A is false, not of A itself." },
    { assertion: "Along with income, people also seek equal treatment, freedom and security from development.",
      reason: "Money cannot buy all the goods and services necessary to live well, such as a pollution-free environment.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and R correctly explains A: because money cannot secure everything people need, people additionally seek things like equality, freedom and security that only collective provision or fair treatment can give." },
    { assertion: "The Human Development Index is published by the UNDP.",
      reason: "HDI combines per capita income, life expectancy at birth, and the education levels of a country's people.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but R describes what the HDI measures, not why the UNDP is the body that publishes it — so R does not correctly explain A." },
  ],
  caseStudies: [
    { title: "Comparing two states on income and human development", importance: "high",
      source: "Two states in a country report the following figures for a given year:<br><table><thead><tr><th>Indicator</th><th>State P</th><th>State Q</th></tr></thead><tbody><tr><td>Per capita income (₹ per annum)</td><td>1,25,000</td><td>95,000</td></tr><tr><td>Infant Mortality Rate (per 1,000 live births)</td><td>42</td><td>10</td></tr><tr><td>Literacy rate (%)</td><td>68</td><td>94</td></tr></tbody></table>",
      caption: "Modelled on the Kerala–Haryana style comparison used in the chapter.",
      parts: [
        { q: "State P has a total income of ₹3,75,000 crore and a population of 3 crore. Verify that its per capita income matches the figure shown in the table.", marks: 2, answer: "Per capita income = total income ÷ population = 3,75,000 ÷ 3 = <strong>₹1,25,000</strong>, which matches the table. ✓" },
        { q: "Which state performs better on infant mortality rate and literacy rate, despite having the lower per capita income?", marks: 1, answer: "<strong>State Q</strong> performs better on both indicators, even though its per capita income is lower than State P's." },
        { q: "What does this comparison suggest about using per capita income alone as a measure of development?", marks: 1, answer: "It shows that per capita income alone can be <strong>misleading</strong> — a state can have a higher average income yet lag behind on health and education outcomes that matter just as much to people's lives." },
        { q: "Suggest one reason State Q might perform better on health and education despite lower income.", marks: 1, answer: "State Q likely has <strong>better public provision</strong> of basic health and educational facilities — schools, primary health centres and an effective public distribution system — the same reasoning used to explain Kerala's outcomes." },
      ] },
    { title: "Different notions of development", importance: "medium",
      source: "A landless rural labourer wants more days of work and better wages, and hopes the local school will teach his children well. A prosperous farmer from the same village wants an assured high family income through higher support prices for crops and cheap labourers to work his fields. An industrialist wants more electricity and better roads for his factory. A tribal family living near a proposed dam site does not want the dam built at all, since it would submerge their land and displace their community.",
      caption: "Based on the chapter's opening discussion of conflicting developmental goals.",
      parts: [
        { q: "Identify one pair of conflicting developmental goals from the passage.", marks: 2, answer: "The landless labourer wants higher wages and cheap labour is what keeps the farmer's costs low, so the labourer's goal of better wages directly conflicts with the farmer's goal of cheap labour. (Equally valid: the industrialist's need for electricity from the dam conflicts with the tribal family's wish that the dam not be built at all.)" },
        { q: "According to the chapter, what important things can money not buy that people still need?", marks: 1, answer: "A pollution-free environment, unadulterated medicines, protection from infectious disease when others around you are unvaccinated, and equal treatment, freedom, security and respect from others." },
        { q: "Explain, with reference to the passage, why development for one group can be destructive for another.", marks: 2, answer: "Because people's goals depend on their own circumstances and needs, an outcome that benefits one group can directly harm another with a different stake in the same resource. For example, building the dam would supply the industrialist's electricity, but it would submerge the tribal family's land and displace them — so the very same project counts as development for one and destruction for the other." },
      ] },
  ],
};
