import type { Chapter } from "@/lib/types";

export const ch18: Chapter = {
  slug: "development",
  num: 1,
  title: "Development",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 16,
  blurb: "Everyone wants development, but a landless labourer and a rich farmer want opposite things. This chapter is about how you measure something people define differently.",
  bigIdea: "Income matters, but it is not the whole of development. What people can do and be — live long, stay healthy, learn — matters at least as much.",
  syllabus: [
    "What development promises — different people, different goals",
    "Income and other goals",
    "National development",
    "How to compare different countries or states",
    "Income and other criteria — the Human Development Report",
    "Sustainability of development",
  ],
  blocks: [
    { t: "h", text: "Different people, different goals" },
    { t: "p", html: "Different persons can have different developmental goals, and <strong>what may be development for one may not be development for the other</strong> — it may even be destructive for the other. A landless rural labourer wants more days of work and better wages, and for the local school to teach their children well. A prosperous farmer from the same village wants assured high family income through higher support prices and cheap labourers — which directly conflicts with the labourer's goal. An industrialist wants more electricity and better roads; an Adivasi from Narmada valley may want the dam that provides that electricity not to be built at all." },
    { t: "note", kind: "idea", html: "Two ideas do most of the work in this chapter. First, people seek things that are the <strong>most important for them</strong> — and these need not always be the same. Second, <strong>money cannot buy all the goods and services</strong> you need to live well. Money cannot buy a pollution-free environment, unadulterated medicines, or protection from an infectious disease if your neighbours are not vaccinated. Income is one of the most important components, but along with income people also seek <strong>equal treatment, freedom, security, and respect from others</strong>. They resent discrimination." },

    { t: "h", text: "Comparing countries — the income measure" },
    { t: "sim", id: "development-compare" },
    { t: "p", html: "For comparing countries, their <strong>income</strong> is considered to be one of the most important attributes. Countries with higher income are more developed than others with less income. But the total income of a country is not a useful comparison, because countries have different populations. So we compare the <strong>average income</strong> — the total income of the country divided by its total population, also called <strong>per capita income</strong>." },
    { t: "note", kind: "real", title: "The World Bank classification", html: "The <strong>World Development Report</strong>, brought out by the World Bank, uses per capita income to classify countries. On the 2017 figures the textbook quotes, countries with per capita income of <strong>US$ 12,056 per annum and above</strong> were called <strong>rich countries</strong>, and those with <strong>US$ 955 or less</strong> were called <strong>low-income countries</strong>. India comes in the category of <strong>low middle income countries</strong>, because its per capita income in 2017 was just <strong>US$ 1,820 per annum</strong>. The rich countries, excluding those of West Asia and certain other small countries, are generally called <strong>developed countries</strong>. The World Bank revises the cut-offs every year, so quote the year with the figure — the marks are for the method, not the number." },
    { t: "note", kind: "trap", html: "The core limitation of average income: it <strong>hides disparities</strong>. Two countries with the same average income can be very different — in one, most people have roughly similar incomes; in the other, a few are extremely rich and most are extremely poor. Averages are useful for comparison, but they do not tell us how income is distributed." },

    { t: "h", text: "Beyond income" },
    { t: "table", head: ["Indicator", "What it measures"], rows: [
      ["<strong>Infant Mortality Rate (IMR)</strong>", "The number of children that die before the age of one year as a proportion of <strong>1,000 live children</strong> born in that particular year"],
      ["<strong>Literacy Rate</strong>", "The proportion of literate population in the <strong>7 and above age group</strong>"],
      ["<strong>Net Attendance Ratio</strong>", "The total number of children of age group 6–10 attending school as a percentage of total number of children in the same age group"],
      ["<strong>Body Mass Index (BMI)</strong>", "Weight in kilograms divided by the square of height in metres. Below 18.5 is <strong>undernourished</strong>; above 25 is <strong>overweight</strong>. This is a rough measure and does not apply to growing children"],
      ["<strong>Human Development Index (HDI)</strong>", "Combines per capita income, life expectancy at birth, and the education levels of people, into a single ranking published by the UNDP"],
    ] },
    { t: "note", kind: "why", title: "The Kerala lesson", html: "The comparison the exam always uses: <strong>Haryana has a higher per capita income than Kerala, but Kerala has a lower infant mortality rate and a higher literacy rate</strong>. The reason is that Kerala has a much better performance in terms of <strong>basic health and educational facilities</strong> — the public distribution system, the schools, the primary health centres. Money in your pocket cannot buy you a pollution-free environment or an adequate supply of safe drinking water if the collective facilities do not exist. Development therefore requires <strong>collective provision</strong> alongside individual income." },
    { t: "note", kind: "real", html: "The <strong>Public Distribution System (PDS)</strong> is the ration shop system, and the states where it functions well have better nutrition and health outcomes. Note also that <strong>about half of the children in India are undernourished</strong> despite India being self-sufficient in food grains — a fact that separates food availability from food security." },

    { t: "h", text: "Sustainability" },
    { t: "p", html: "The question of development is not just about the present. <strong>Sustainability of development</strong> asks whether the levels of development we have achieved can be maintained for future generations. Two examples the chapter uses. <strong>Groundwater</strong>: it is a renewable resource, but overuse means it is not being replenished — 300 districts have reported a fall in water levels of over 4 metres during the past 20 years, and nearly one-third of the country is overusing groundwater reserves. <strong>Crude oil</strong>: the reserves will last only a few decades at current rates of use, and it is unevenly distributed, with a very large share in West Asia." },
    { t: "note", kind: "idea", html: "Two points that carry marks. First, the consequences of environmental degradation <strong>do not respect national or state boundaries</strong> — this issue is no longer region- or nation-specific, and our future is linked together. Second, scientists have been warning that the present type and levels of development are not sustainable, so the challenge is to find a path that keeps the resource base intact for the generations that follow." },
  ],
  examFocus: [
    "Conflicting developmental goals — landless labourer versus prosperous farmer, industrialist versus Adivasi.",
    "Why money cannot buy everything people need, with examples.",
    "Average income, its definition, and why it hides disparities.",
    "The World Bank cut-offs and India's classification.",
    "Definitions of IMR, literacy rate, net attendance ratio and BMI.",
    "The Kerala–Haryana comparison and the public provision argument.",
    "What HDI combines, and who publishes it.",
    "Sustainability, with the groundwater and crude oil examples.",
  ],
  flashcards: [
    { q: "Why do different people have different developmental goals?", a: "Because people seek what is most important for them, and these need not be the same. A landless labourer wants more work days and better wages; a prosperous farmer wants higher support prices and cheap labour. What is development for one may be destructive for the other." },
    { q: "Name things money cannot buy that people still need.", a: "A pollution-free environment, unadulterated medicines, protection from infectious disease when neighbours are unvaccinated, and equal treatment, freedom, security and respect from others." },
    { q: "What is average or per capita income?", a: "The total income of a country divided by its total population. It is used to compare countries because total income alone ignores differences in population size." },
    { q: "Give the World Bank income cut-offs used in the chapter.", a: "On the 2017 figures, countries with per capita income of US$ 12,056 per annum and above were called rich countries, and those with US$ 955 or less were called low-income countries. The World Bank revises these cut-offs each year." },
    { q: "Why is India classified as a low middle income country?", a: "Because its per capita income in 2017 was just US$ 1,820 per annum, well below the rich-country threshold." },
    { q: "What is the main limitation of average income?", a: "It hides disparities. Two countries with the same average income can differ completely in how that income is distributed between rich and poor." },
    { q: "Define Infant Mortality Rate.", a: "The number of children that die before the age of one year as a proportion of 1,000 live children born in that particular year." },
    { q: "Define literacy rate and net attendance ratio.", a: "Literacy rate is the proportion of the literate population in the 7-and-above age group. Net attendance ratio is the number of children aged 6 to 10 attending school as a percentage of all children in that age group." },
    { q: "What is BMI and what do its values mean?", a: "Weight in kilograms divided by the square of height in metres. Below 18.5 means undernourished; above 25 means overweight. It is a rough measure and does not apply to growing children." },
    { q: "What does the Human Development Index combine?", a: "Per capita income, life expectancy at birth, and educational levels of the population, published by the UNDP in the Human Development Report." },
    { q: "Why does Kerala do better than Haryana on human development despite lower income?", a: "Because Kerala has far better basic health and educational facilities — schools, primary health centres and an effective public distribution system. Individual income cannot substitute for collective provision." },
    { q: "Give two examples of unsustainable resource use in India.", a: "Groundwater — 300 districts reported water levels falling over 4 metres in twenty years, and about a third of the country is overusing reserves. Crude oil — reserves will last only a few decades and are concentrated in West Asia." },
  ],
  quiz: [
    { q: "Average income is also called:", options: ["Total income", "Per capita income", "National income", "Gross income"], answer: 1, why: "Average income is total income divided by total population, known as per capita income." },
    { q: "India's per capita income in 2017 was about:", options: ["US$ 955", "US$ 1,820", "US$ 12,056", "US$ 500"], answer: 1, why: "That figure places India in the low middle income category." },
    { q: "Infant Mortality Rate is measured per:", options: ["100 live births", "1,000 live births", "10,000 people", "1 lakh people"], answer: 1, why: "It is deaths before age one per 1,000 live children born in that year." },
    { q: "Literacy rate covers the age group:", options: ["6 and above", "7 and above", "10 and above", "15 and above"], answer: 1, why: "It is the proportion of the literate population in the 7-and-above age group." },
    { q: "A BMI below 18.5 indicates a person is:", options: ["Overweight", "Undernourished", "Healthy", "Obese"], answer: 1, why: "Below 18.5 is undernourished; above 25 is overweight. The measure does not apply to growing children." },
    { q: "The Human Development Report is published by:", options: ["The World Bank", "UNDP", "WHO", "The Indian government"], answer: 1, why: "The UNDP publishes the HDR, which ranks countries using income, life expectancy and education." },
    { q: "Kerala has a lower infant mortality rate than Haryana because it has:", options: ["Higher per capita income", "Better basic health and education facilities", "A smaller population", "More industries"], answer: 1, why: "Kerala's public provision of health and education outperforms Haryana's despite Haryana's higher income." },
    { q: "The main limitation of using average income to compare countries is that it:", options: ["Is hard to calculate", "Hides how income is distributed", "Ignores population", "Uses the wrong currency"], answer: 1, why: "Averages conceal disparities between rich and poor within a country." },
    { q: "Roughly what share of Indian children are undernourished?", options: ["One-tenth", "One-quarter", "About half", "Three-quarters"], answer: 2, why: "About half of India's children are undernourished, despite the country being self-sufficient in food grains." },
    { q: "Sustainability of development is mainly about:", options: ["Raising income fastest", "Whether present levels can be maintained for future generations", "Balancing exports and imports", "Reducing unemployment"], answer: 1, why: "It asks whether the resource base supporting current development will still exist for the generations that follow." },
  ],
};
