import type { Chapter } from "@/lib/types";

export const ch19: Chapter = {
  slug: "sectors-of-the-indian-economy",
  num: 2,
  title: "Sectors of the Indian Economy",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 18,
  blurb: "India's output moved out of agriculture decades ago. Its workers did not. That single gap explains most of what this chapter is about.",
  bigIdea: "A sector can produce most of the country's output while employing few people, or employ most people while producing little. When those two diverge, you get underemployment.",
  syllabus: [
    "Sectors of economic activities — primary, secondary, tertiary",
    "Comparing the three sectors and GDP",
    "Historical change in sectors",
    "Rising importance of the tertiary sector",
    "Underemployment and how to create more employment",
    "MGNREGA 2005",
    "Organised and unorganised sectors",
    "Public and private sectors",
  ],
  blocks: [
    { t: "h", text: "Three ways of classifying" },
    { t: "table", head: ["Basis", "Categories"], rows: [
      ["Nature of activity", "<strong>Primary</strong> — exploiting natural resources: agriculture, dairy, fishing, forestry, mining. Also called the agriculture and related sector. <strong>Secondary</strong> — turning natural products into other forms through manufacturing; also called the industrial sector. <strong>Tertiary</strong> — activities that help the first two, and are services rather than goods: transport, storage, communication, banking, trade"],
      ["Conditions of employment", "<strong>Organised</strong> — where terms of employment are regular, enterprises are registered by the government and have to follow rules and regulations. <strong>Unorganised</strong> — small and scattered units largely outside government control"],
      ["Ownership of assets", "<strong>Public sector</strong> — the government owns most of the assets and provides all the services. <strong>Private sector</strong> — ownership of assets and delivery of services is in the hands of private individuals or companies"],
    ] },
    { t: "note", kind: "why", title: "Why we count only final goods", html: "<strong>Gross Domestic Product (GDP)</strong> is the value of all <strong>final goods and services</strong> produced within a country during a particular year. Intermediate goods are excluded because their value is already included in the final goods. Counting a farmer's wheat and then the biscuit made from it would count the wheat twice. In India, the task of measuring GDP is undertaken by a <strong>central government ministry</strong>, which collects information from all Indian states and union territories." },

    { t: "h", text: "The historical shift, and the gap" },
    { t: "sim", id: "sectors-economy" },
    { t: "p", html: "The historical pattern is that at initial stages the <strong>primary sector</strong> is the most important sector of economic activity. As methods of farming improve and surplus food is produced, other activities begin, and over time the <strong>secondary sector</strong> becomes the largest producer and employer. In the past 100 years there has been a further shift, with the <strong>tertiary sector</strong> becoming the most important in terms of total production in developed countries." },
    { t: "note", kind: "trap", title: "The one comparison to memorise", html: "In India, over forty years the tertiary sector became the largest producer, overtaking the primary sector in production. But the <strong>primary sector remains the largest employer</strong>. Production in the primary sector grew much less than in the other two, yet more than half of the workers are still employed there. This means workers in agriculture are <strong>underemployed</strong>. If some of them moved out, production would not fall — they are working less than their potential, and this is called <strong>disguised unemployment</strong>." },
    { t: "note", kind: "real", title: "Why the tertiary sector grew", html: "Four reasons. First, basic services such as hospitals, educational institutions, post and telegraph, police stations, courts, transport, banks and insurance are needed, and in a developing country the government has to take responsibility for their provision. Second, the development of agriculture and industry leads to the development of services such as transport, trade and storage — the greater the development of the primary and secondary sectors, the greater the demand for such services. Third, as income levels rise, people begin to demand more services — eating out, tourism, shopping, private hospitals, private schools, professional training. Fourth, over the past decade certain services based on <strong>information and communication technology</strong> have grown rapidly and become important." },
    { t: "note", kind: "idea", title: "Two different tertiary sectors", html: "Do not treat the service sector as uniformly good. At one end are highly skilled and educated workers in services; at the other end are a very large number of workers engaged in services such as small shopkeepers, repair persons and transport persons who barely manage to earn a living. These people perform services because there are no alternative opportunities — so a part of the service sector's growth is <strong>distress-driven</strong>, not prosperity-driven." },

    { t: "h", text: "Creating more employment" },
    { t: "list", items: [
      "Provide <strong>cheap agricultural credit</strong> and construct wells and canals so farmers can grow a second crop.",
      "Improve <strong>transport and storage</strong> so farmers can sell in the market — a small dam or a road can create both employment and future income.",
      "Promote <strong>local industries and services</strong> such as dal mills, cold storages, honey collection centres, and processing of vegetables. This creates jobs where the produce already is.",
      "Improve <strong>education and health</strong>: every child should be sent to school, and every state should run enough schools and health centres. This creates employment directly and raises capability.",
      "Recognise the potential of <strong>tourism, regional craft industry, and new services like IT</strong> to create employment.",
    ] },
    { t: "note", kind: "real", title: "MGNREGA 2005", html: "The central government in India made a law implementing the <strong>Right to Work</strong> in about 625 districts — the <strong>Mahatma Gandhi National Rural Employment Guarantee Act 2005</strong>. Under it, all those who are able to and are in need of work in rural areas are guaranteed <strong>100 days of employment in a year</strong> by the government. If the government fails to provide employment, it must give <strong>unemployment allowances</strong> to the people. The types of work preferred are those that will in the future help increase production from land." },

    { t: "h", text: "Organised and unorganised" },
    { t: "table", head: ["", "Organised sector", "Unorganised sector"], rows: [
      ["Terms of employment", "Regular and secure, with an appointment letter", "Not regular; a person can be asked to leave without reason"],
      ["Hours and pay", "Fixed working hours; overtime paid extra", "Employment is low paid and often not regular; jobs are low paid and often not regular"],
      ["Benefits", "Paid leave, holidays, leave due to sickness, provident fund, gratuity, medical benefits, pension after retirement", "No provision for overtime, paid leave, holidays, leave due to sickness"],
      ["Regulation", "Registered by the government; must follow rules and regulations given in various laws such as the Factories Act, Minimum Wages Act, Payment of Gratuity Act, Shops and Establishments Act", "Small and scattered units largely outside the control of the government; rules exist but are not followed"],
    ] },
    { t: "note", kind: "why", title: "Who needs protection", html: "In the rural areas the unorganised sector largely consists of <strong>landless agricultural labourers, small and marginal farmers, sharecroppers and artisans</strong> such as weavers, blacksmiths, carpenters and goldsmiths. In the urban areas it includes workers in small-scale industry, casual workers in construction, trade and transport, and those who work as street vendors, head load workers, garment makers and rag pickers. A large majority of workers from <strong>Scheduled Castes, Scheduled Tribes and backward communities</strong> find themselves in the unorganised sector, so protecting these workers is a matter of both economic and social justice." },
    { t: "note", kind: "idea", title: "Public and private", html: "In the public sector the purpose is <strong>not just to earn profits</strong>. Governments raise money through taxes and other means to meet expenses on services rendered by the government. There are several things needed by society as a whole which the private sector will not provide at a reasonable cost — construction of roads, bridges, railways, harbours, generating electricity, irrigation through dams. Some activities the government must support: buying food grains from farmers at a fair price, storing them, and selling at a lower price to consumers through ration shops. The government also has to bear part of the cost. Providing health and education facilities for all, running proper schools, and ensuring nutrition and safe drinking water are among its primary responsibilities." },
  ],
  examFocus: [
    "The three sectors by nature of activity, with examples of each.",
    "The definition of GDP, why intermediate goods are excluded, and who measures it in India.",
    "The historical shift, and the divergence between production share and employment share in India.",
    "Underemployment and disguised unemployment, with the farm example.",
    "The four reasons for the rise of the tertiary sector.",
    "Ways to create more employment in rural areas.",
    "MGNREGA 2005 — districts, 100 days, unemployment allowance.",
    "Organised versus unorganised sector, with the named laws.",
    "Why the public sector exists, with examples of what private firms will not provide.",
  ],
  flashcards: [
    { q: "Define the three sectors by nature of activity.", a: "Primary — exploiting natural resources: agriculture, dairy, fishing, forestry, mining. Secondary — turning natural products into other forms through manufacturing. Tertiary — services that support the other two: transport, storage, communication, banking, trade." },
    { q: "What is GDP and why are intermediate goods excluded?", a: "GDP is the value of all final goods and services produced within a country during a particular year. Intermediate goods are excluded because their value is already included in the value of the final goods, so counting both would double count." },
    { q: "Who measures GDP in India?", a: "A central government ministry, which collects information relating to total volume of goods and services and their prices from all Indian states and union territories." },
    { q: "What is the key divergence in the Indian economy?", a: "The tertiary sector has become the largest producer, but the primary sector remains the largest employer — more than half the workers are in agriculture while it produces a much smaller share of output." },
    { q: "What is disguised unemployment?", a: "A situation where more people are working on a job than are needed, so if some were removed production would not fall. Workers appear employed but are working below their potential — common on family farms." },
    { q: "Give the four reasons for the growth of the tertiary sector.", a: "Basic services must be provided by government in a developing country; growth of agriculture and industry raises demand for transport, trade and storage; rising incomes create demand for services like eating out, tourism and private schooling; and information and communication technology services have grown rapidly." },
    { q: "Why is service-sector growth not always a good sign?", a: "Because alongside highly skilled workers there are very large numbers of small shopkeepers, repair persons and transport workers who barely earn a living and do this work only for lack of alternatives." },
    { q: "What is MGNREGA 2005?", a: "The Mahatma Gandhi National Rural Employment Guarantee Act, implementing the Right to Work in about 625 districts, guaranteeing 100 days of employment a year to all rural people able to work and in need of it, with an unemployment allowance if the government fails to provide work." },
    { q: "Give three features of the organised sector.", a: "Regular and secure employment with an appointment letter; fixed working hours with paid overtime; and benefits such as paid leave, provident fund, gratuity, medical benefits and pension." },
    { q: "Name the laws that regulate the organised sector.", a: "The Factories Act, the Minimum Wages Act, the Payment of Gratuity Act and the Shops and Establishments Act." },
    { q: "Who works in the unorganised sector?", a: "In rural areas, landless agricultural labourers, small and marginal farmers, sharecroppers and artisans such as weavers, blacksmiths, carpenters and goldsmiths. In urban areas, small-scale industry workers, casual workers in construction, trade and transport, street vendors, head load workers, garment makers and rag pickers." },
    { q: "Why does the public sector exist if it does not maximise profit?", a: "Because society needs things the private sector will not supply at reasonable cost — roads, bridges, railways, harbours, electricity generation, irrigation dams — and because the government must support activities like buying grain at fair prices and providing health, education, nutrition and safe drinking water." },
  ],
  quiz: [
    { q: "Mining belongs to the:", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Unorganised sector only"], answer: 0, why: "The primary sector exploits natural resources directly — agriculture, dairy, fishing, forestry and mining." },
    { q: "GDP counts:", options: ["All goods produced", "Only final goods and services", "Only manufactured goods", "Only goods that are exported"], answer: 1, why: "Only final goods and services are counted; intermediate goods would be double counted." },
    { q: "In India the largest employer is the:", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Public sector"], answer: 0, why: "More than half of India's workers are still employed in the primary sector, even though it no longer produces the largest share of output." },
    { q: "When four family members work on a farm that two could manage, this is:", options: ["Seasonal unemployment", "Disguised unemployment", "Structural unemployment", "Full employment"], answer: 1, why: "Removing the extra workers would not reduce output, so they are underemployed — disguised unemployment." },
    { q: "MGNREGA guarantees how many days of employment a year?", options: ["50", "100", "180", "365"], answer: 1, why: "It guarantees 100 days of employment a year to rural people able to work and in need of it." },
    { q: "If the government fails to provide work under MGNREGA it must give:", options: ["A loan", "Free food", "Unemployment allowance", "A job in the city"], answer: 2, why: "The Act requires the government to pay unemployment allowances if it cannot provide work." },
    { q: "Which is NOT a feature of the organised sector?", options: ["Appointment letter", "Provident fund", "Employment that can end without notice", "Paid overtime"], answer: 2, why: "Being asked to leave without any reason is a feature of the unorganised sector." },
    { q: "The Factories Act and Minimum Wages Act apply mainly to the:", options: ["Unorganised sector", "Organised sector", "Public sector only", "Primary sector only"], answer: 1, why: "Organised sector enterprises are registered and must follow these laws." },
    { q: "Building roads, bridges and irrigation dams is typically the responsibility of the:", options: ["Private sector", "Public sector", "Unorganised sector", "Tertiary sector alone"], answer: 1, why: "The private sector will not provide these at reasonable cost, so the government does." },
    { q: "Which is a reason for the tertiary sector's growth?", options: ["Falling incomes", "Declining industry", "Rising demand for services as incomes rise", "Shrinking population"], answer: 2, why: "As income levels rise, people demand more services — eating out, tourism, private hospitals and schools, professional training." },
  ],
};
