import type { Chapter } from "@/lib/types";

export const ch19: Chapter = {
  slug: "sectors-of-the-indian-economy",
  num: 2,
  title: "Sectors of the Indian Economy",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 18,
  blurb: "India's output moved out of agriculture decades ago. Its workers did not. That single gap explains most of what this chapter is about.",
  bigIdea: "A sector can produce most of the country's output while employing few people, or employ most people while producing little. When those two diverge, you get underemployment.",
  syllabus: [
    "Sectors of economic activities — primary, secondary, tertiary",
    "Comparing the three sectors and GDP",
    "Historical change in sectors",
    "Rising importance of the tertiary sector",
    "Underemployment and how to create more employment",
    "MGNREGA 2005",
    "Organised and unorganised sectors",
    "Public and private sectors",
  ],
  blocks: [
    { t: "h", text: "Three ways of classifying" },
    { t: "table", head: ["Basis", "Categories"], rows: [
      ["Nature of activity", "<strong>Primary</strong> — exploiting natural resources: agriculture, dairy, fishing, forestry, mining. Also called the agriculture and related sector. <strong>Secondary</strong> — turning natural products into other forms through manufacturing; also called the industrial sector. <strong>Tertiary</strong> — activities that help the first two, and are services rather than goods: transport, storage, communication, banking, trade"],
      ["Conditions of employment", "<strong>Organised</strong> — where terms of employment are regular, enterprises are registered by the government and have to follow rules and regulations. <strong>Unorganised</strong> — small and scattered units largely outside government control"],
      ["Ownership of assets", "<strong>Public sector</strong> — the government owns most of the assets and provides all the services. <strong>Private sector</strong> — ownership of assets and delivery of services is in the hands of private individuals or companies"],
    ] },
    { t: "note", kind: "why", title: "Why we count only final goods", html: "<strong>Gross Domestic Product (GDP)</strong> is the value of all <strong>final goods and services</strong> produced within a country during a particular year. Intermediate goods are excluded because their value is already included in the final goods. Counting a farmer's wheat and then the biscuit made from it would count the wheat twice. In India, the task of measuring GDP is undertaken by a <strong>central government ministry</strong>, which collects information from all Indian states and union territories." },

    { t: "h", text: "The historical shift, and the gap" },
    { t: "sim", id: "sectors-economy" },
    { t: "p", html: "The historical pattern is that at initial stages the <strong>primary sector</strong> is the most important sector of economic activity. As methods of farming improve and surplus food is produced, other activities begin, and over time the <strong>secondary sector</strong> becomes the largest producer and employer. In the past 100 years there has been a further shift, with the <strong>tertiary sector</strong> becoming the most important in terms of total production in developed countries." },
    { t: "note", kind: "trap", title: "The one comparison to memorise", html: "In India, over forty years the tertiary sector became the largest producer, overtaking the primary sector in production. But the <strong>primary sector remains the largest employer</strong>. Production in the primary sector grew much less than in the other two, yet more than half of the workers are still employed there. This means workers in agriculture are <strong>underemployed</strong>. If some of them moved out, production would not fall — they are working less than their potential, and this is called <strong>disguised unemployment</strong>." },
    { t: "note", kind: "real", title: "Why the tertiary sector grew", html: "Four reasons. First, basic services such as hospitals, educational institutions, post and telegraph, police stations, courts, transport, banks and insurance are needed, and in a developing country the government has to take responsibility for their provision. Second, the development of agriculture and industry leads to the development of services such as transport, trade and storage — the greater the development of the primary and secondary sectors, the greater the demand for such services. Third, as income levels rise, people begin to demand more services — eating out, tourism, shopping, private hospitals, private schools, professional training. Fourth, over the past decade certain services based on <strong>information and communication technology</strong> have grown rapidly and become important." },
    { t: "note", kind: "idea", title: "Two different tertiary sectors", html: "Do not treat the service sector as uniformly good. At one end are highly skilled and educated workers in services; at the other end are a very large number of workers engaged in services such as small shopkeepers, repair persons and transport persons who barely manage to earn a living. These people perform services because there are no alternative opportunities — so a part of the service sector's growth is <strong>distress-driven</strong>, not prosperity-driven." },

    { t: "h", text: "Creating more employment" },
    { t: "list", items: [
      "Provide <strong>cheap agricultural credit</strong> and construct wells and canals so farmers can grow a second crop.",
      "Improve <strong>transport and storage</strong> so farmers can sell in the market — a small dam or a road can create both employment and future income.",
      "Promote <strong>local industries and services</strong> such as dal mills, cold storages, honey collection centres, and processing of vegetables. This creates jobs where the produce already is.",
      "Improve <strong>education and health</strong>: every child should be sent to school, and every state should run enough schools and health centres. This creates employment directly and raises capability.",
      "Recognise the potential of <strong>tourism, regional craft industry, and new services like IT</strong> to create employment.",
    ] },
    { t: "note", kind: "real", title: "MGNREGA 2005", html: "The central government in India made a law implementing the <strong>Right to Work</strong> in about 625 districts — the <strong>Mahatma Gandhi National Rural Employment Guarantee Act 2005</strong>. Under it, all those who are able to and are in need of work in rural areas are guaranteed <strong>100 days of employment in a year</strong> by the government. If the government fails to provide employment, it must give <strong>unemployment allowances</strong> to the people. The types of work preferred are those that will in the future help increase production from land." },

    { t: "h", text: "Organised and unorganised" },
    { t: "table", head: ["", "Organised sector", "Unorganised sector"], rows: [
      ["Terms of employment", "Regular and secure, with an appointment letter", "Not regular; a person can be asked to leave without reason"],
      ["Hours and pay", "Fixed working hours; overtime paid extra", "Employment is low paid and often not regular; jobs are low paid and often not regular"],
      ["Benefits", "Paid leave, holidays, leave due to sickness, provident fund, gratuity, medical benefits, pension after retirement", "No provision for overtime, paid leave, holidays, leave due to sickness"],
      ["Regulation", "Registered by the government; must follow rules and regulations given in various laws such as the Factories Act, Minimum Wages Act, Payment of Gratuity Act, Shops and Establishments Act", "Small and scattered units largely outside the control of the government; rules exist but are not followed"],
    ] },
    { t: "note", kind: "why", title: "Who needs protection", html: "In the rural areas the unorganised sector largely consists of <strong>landless agricultural labourers, small and marginal farmers, sharecroppers and artisans</strong> such as weavers, blacksmiths, carpenters and goldsmiths. In the urban areas it includes workers in small-scale industry, casual workers in construction, trade and transport, and those who work as street vendors, head load workers, garment makers and rag pickers. A large majority of workers from <strong>Scheduled Castes, Scheduled Tribes and backward communities</strong> find themselves in the unorganised sector, so protecting these workers is a matter of both economic and social justice." },
    { t: "note", kind: "idea", title: "Public and private", html: "In the public sector the purpose is <strong>not just to earn profits</strong>. Governments raise money through taxes and other means to meet expenses on services rendered by the government. There are several things needed by society as a whole which the private sector will not provide at a reasonable cost — construction of roads, bridges, railways, harbours, generating electricity, irrigation through dams. Some activities the government must support: buying food grains from farmers at a fair price, storing them, and selling at a lower price to consumers through ration shops. The government also has to bear part of the cost. Providing health and education facilities for all, running proper schools, and ensuring nutrition and safe drinking water are among its primary responsibilities." },
  ],
  examFocus: [
    "The three sectors by nature of activity, with examples of each.",
    "The definition of GDP, why intermediate goods are excluded, and who measures it in India.",
    "The historical shift, and the divergence between production share and employment share in India.",
    "Underemployment and disguised unemployment, with the farm example.",
    "The four reasons for the rise of the tertiary sector.",
    "Ways to create more employment in rural areas.",
    "MGNREGA 2005 — districts, 100 days, unemployment allowance.",
    "Organised versus unorganised sector, with the named laws.",
    "Why the public sector exists, with examples of what private firms will not provide.",
  ],
  flashcards: [
    { q: "Define the three sectors by nature of activity.", a: "Primary — exploiting natural resources: agriculture, dairy, fishing, forestry, mining. Secondary — turning natural products into other forms through manufacturing. Tertiary — services that support the other two: transport, storage, communication, banking, trade." },
    { q: "What is GDP and why are intermediate goods excluded?", a: "GDP is the value of all final goods and services produced within a country during a particular year. Intermediate goods are excluded because their value is already included in the value of the final goods, so counting both would double count." },
    { q: "Who measures GDP in India?", a: "A central government ministry, which collects information relating to total volume of goods and services and their prices from all Indian states and union territories." },
    { q: "What is the key divergence in the Indian economy?", a: "The tertiary sector has become the largest producer, but the primary sector remains the largest employer — more than half the workers are in agriculture while it produces a much smaller share of output." },
    { q: "What is disguised unemployment?", a: "A situation where more people are working on a job than are needed, so if some were removed production would not fall. Workers appear employed but are working below their potential — common on family farms." },
    { q: "Give the four reasons for the growth of the tertiary sector.", a: "Basic services must be provided by government in a developing country; growth of agriculture and industry raises demand for transport, trade and storage; rising incomes create demand for services like eating out, tourism and private schooling; and information and communication technology services have grown rapidly." },
    { q: "Why is service-sector growth not always a good sign?", a: "Because alongside highly skilled workers there are very large numbers of small shopkeepers, repair persons and transport workers who barely earn a living and do this work only for lack of alternatives." },
    { q: "What is MGNREGA 2005?", a: "The Mahatma Gandhi National Rural Employment Guarantee Act, implementing the Right to Work in about 625 districts, guaranteeing 100 days of employment a year to all rural people able to work and in need of it, with an unemployment allowance if the government fails to provide work." },
    { q: "Give three features of the organised sector.", a: "Regular and secure employment with an appointment letter; fixed working hours with paid overtime; and benefits such as paid leave, provident fund, gratuity, medical benefits and pension." },
    { q: "Name the laws that regulate the organised sector.", a: "The Factories Act, the Minimum Wages Act, the Payment of Gratuity Act and the Shops and Establishments Act." },
    { q: "Who works in the unorganised sector?", a: "In rural areas, landless agricultural labourers, small and marginal farmers, sharecroppers and artisans such as weavers, blacksmiths, carpenters and goldsmiths. In urban areas, small-scale industry workers, casual workers in construction, trade and transport, street vendors, head load workers, garment makers and rag pickers." },
    { q: "Why does the public sector exist if it does not maximise profit?", a: "Because society needs things the private sector will not supply at reasonable cost — roads, bridges, railways, harbours, electricity generation, irrigation dams — and because the government must support activities like buying grain at fair prices and providing health, education, nutrition and safe drinking water." },
  ],
  quiz: [
    { q: "Mining belongs to the:", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Unorganised sector only"], answer: 0, why: "The primary sector exploits natural resources directly — agriculture, dairy, fishing, forestry and mining." },
    { q: "GDP counts:", options: ["All goods produced", "Only final goods and services", "Only manufactured goods", "Only goods that are exported"], answer: 1, why: "Only final goods and services are counted; intermediate goods would be double counted." },
    { q: "In India the largest employer is the:", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Public sector"], answer: 0, why: "More than half of India's workers are still employed in the primary sector, even though it no longer produces the largest share of output." },
    { q: "When four family members work on a farm that two could manage, this is:", options: ["Seasonal unemployment", "Disguised unemployment", "Structural unemployment", "Full employment"], answer: 1, why: "Removing the extra workers would not reduce output, so they are underemployed — disguised unemployment." },
    { q: "MGNREGA guarantees how many days of employment a year?", options: ["50", "100", "180", "365"], answer: 1, why: "It guarantees 100 days of employment a year to rural people able to work and in need of it." },
    { q: "If the government fails to provide work under MGNREGA it must give:", options: ["A loan", "Free food", "Unemployment allowance", "A job in the city"], answer: 2, why: "The Act requires the government to pay unemployment allowances if it cannot provide work." },
    { q: "Which is NOT a feature of the organised sector?", options: ["Appointment letter", "Provident fund", "Employment that can end without notice", "Paid overtime"], answer: 2, why: "Being asked to leave without any reason is a feature of the unorganised sector." },
    { q: "The Factories Act and Minimum Wages Act apply mainly to the:", options: ["Unorganised sector", "Organised sector", "Public sector only", "Primary sector only"], answer: 1, why: "Organised sector enterprises are registered and must follow these laws." },
    { q: "Building roads, bridges and irrigation dams is typically the responsibility of the:", options: ["Private sector", "Public sector", "Unorganised sector", "Tertiary sector alone"], answer: 1, why: "The private sector will not provide these at reasonable cost, so the government does." },
    { q: "Which is a reason for the tertiary sector's growth?", options: ["Falling incomes", "Declining industry", "Rising demand for services as incomes rise", "Shrinking population"], answer: 2, why: "As income levels rise, people demand more services — eating out, tourism, private hospitals and schools, professional training." },
  ],
  keyTopics: [
    { name: "The three sectors — primary, secondary, tertiary — with examples", importance: "high", note: "The definitional base for almost every other question in the chapter." },
    { name: "GDP — meaning, final vs intermediate goods, who measures it", importance: "high", note: "A reliable 1–2 mark theory question, and the subject of a real 2019 assertion-reason question." },
    { name: "The production–employment gap: primary sector largest employer, tertiary largest producer", importance: "high", note: "The single most important idea in the chapter; underlies disguised unemployment questions." },
    { name: "Underemployment / disguised unemployment", importance: "high", note: "Tested through direct definitions and through numericals on workforce shares." },
    { name: "Organised and unorganised sectors", importance: "high", note: "Point-wise distinguish questions and case studies (a worker denied leave/security) appear almost every year." },
    { name: "MGNREGA 2005", importance: "high", note: "Districts, 100 days, unemployment allowance — precise facts the board rewards." },
    { name: "Reasons for the rising importance of the tertiary sector", importance: "medium", note: "A common 3-mark 'explain any three reasons' question." },
    { name: "Public and private sectors", importance: "medium", note: "Why the public sector exists despite not maximising profit; a 3–5 mark theory question." },
  ],
  written: [
    { q: "Define Gross Domestic Product (GDP).", marks: 1, kind: "short", importance: "high",
      answer: "GDP is the <strong>value of all final goods and services produced within a country during a particular year</strong>." },
    { q: "What is disguised unemployment?", marks: 1, kind: "short", importance: "high",
      answer: "A situation where more people are engaged in a job than are actually needed, so that removing some of them would <strong>not reduce total production</strong> — common on family farms in the primary sector." },
    { q: "Distinguish between the primary sector and the secondary sector, with one example of each.", marks: 2, kind: "short", importance: "high",
      answer: "The <strong>primary sector</strong> produces goods by directly exploiting natural resources — for example, agriculture, fishing, mining and forestry. The <strong>secondary sector</strong> takes natural products and turns them into other forms through manufacturing — for example, converting sugarcane into sugar, or cotton fibre into cloth." },
    { q: "Why are intermediate goods excluded while calculating the GDP of a country?", marks: 2, kind: "short", importance: "high", years: "2019",
      answer: "Intermediate goods are products used as raw material to produce other goods, and their value is <strong>already included</strong> in the value of the final good made from them. Counting both the intermediate good and the final good would <strong>double count</strong> the same value, so GDP counts only final goods and services." },
    { q: "Give two examples each of activities that fall in the organised sector and the unorganised sector.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Organised sector:</strong> a government school teacher, and a worker in a registered factory covered by the Factories Act.<br><strong>Unorganised sector:</strong> a landless agricultural labourer, and a street vendor or head-load worker in a city." },
    { q: "In an economy the primary sector employs 55% of the total workforce but contributes only 20% to GDP, while the tertiary sector employs 25% of the workforce and contributes 50% to GDP. If the total workforce is 8 crore and the GDP is ₹40 lakh crore, calculate (i) the number of people employed in the primary sector, and (ii) the value of GDP contributed by the tertiary sector.", marks: 3, kind: "numerical", importance: "high",
      answer: "(i) People employed in primary sector = 55% of 8 crore = <strong>4.4 crore</strong>.<br>(ii) GDP from tertiary sector = 50% of ₹40 lakh crore = <strong>₹20 lakh crore</strong>.<br>This mismatch — over half the workforce producing only a fifth of GDP — is exactly the underemployment pattern the chapter describes for India's primary sector." },
    { q: "Explain any three reasons for the increasing importance of the tertiary sector in India.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li>In a developing country, <strong>basic services</strong> such as hospitals, schools, courts, transport and banks must largely be provided or supported by the government.</li><li>Development of agriculture and industry itself raises demand for supporting services such as <strong>transport, trade and storage</strong>.</li><li>As incomes rise, people demand more services — <strong>eating out, tourism, private schooling and healthcare</strong>.</li><li>Over the past decades, services based on <strong>information and communication technology</strong> have grown rapidly.</li></ul>(Any three of the above.)" },
    { q: "Distinguish between the organised sector and the unorganised sector on the basis of employment security and social security benefits.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Terms of employment:</strong> organised sector jobs are regular and secure with an appointment letter; unorganised sector jobs are irregular and a worker can be asked to leave without reason.</li><li><strong>Working hours and pay:</strong> organised sector work has fixed hours with paid overtime; unorganised sector work is often low-paid with no overtime.</li><li><strong>Social security:</strong> organised sector workers get paid leave, sick leave, provident fund, gratuity, medical benefits and pension; unorganised sector workers get none of these.</li><li><strong>Regulation:</strong> organised sector enterprises must follow laws like the Factories Act and Minimum Wages Act; unorganised sector units are small, scattered and largely outside government control.</li></ul>" },
    { q: "What is MGNREGA 2005? Explain its main features.", marks: 5, kind: "long", importance: "high",
      answer: "The <strong>Mahatma Gandhi National Rural Employment Guarantee Act, 2005</strong> is a law made by the central government implementing the <strong>Right to Work</strong> in about 625 districts of India.<ul><li>It guarantees <strong>100 days of employment in a year</strong> to all rural people who are able to work and are in need of it.</li><li>If the government is unable to provide employment, it must pay an <strong>unemployment allowance</strong> to the applicants.</li><li>The types of work undertaken are those that will help <strong>increase the productivity of land</strong> in the future — for example building wells, roads or check dams.</li><li>Because the entitlement can be legally claimed, MGNREGA is described as a <strong>rights-based</strong> employment scheme, unlike ordinary welfare programmes.</li></ul>" },
    { q: "Explain why the public sector exists even though its purpose is not to maximise profit. Give examples of what the private sector will not provide.", marks: 5, kind: "long", importance: "high",
      answer: "In the public sector, the government owns the assets and provides the services, and its purpose is <strong>not simply to earn profits</strong> but to serve the wider needs of society; the government raises money through taxes to meet these expenses.<ul><li>Many things needed by society as a whole will not be provided by the private sector at a reasonable cost — <strong>roads, bridges, railways, harbours, electricity generation and irrigation dams</strong> require huge long-term investment with uncertain returns.</li><li>The government must support activities like buying food grains from farmers at a fair price, storing them, and selling them cheaply through <strong>ration shops</strong>.</li><li>Providing <strong>health and education for all</strong>, running schools and health centres, and ensuring nutrition and safe drinking water are core responsibilities that private firms, driven by profit, would neglect for the poor.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "Not every good or service that is produced and sold needs to be counted separately to know the total production of a sector.",
      reason: "The value of final goods already includes the value of all the intermediate goods used to produce them.",
      answer: 0, importance: "high", years: "2019",
      why: "Both statements are true, and R is the correct explanation: since the value of intermediate goods is already built into the final good's price, counting intermediate goods separately would double count production." },
    { assertion: "The primary sector is now the largest producer of GDP in India.",
      reason: "More than half of India's workforce remains employed in the primary sector.",
      answer: 3, importance: "high",
      why: "A is false — the <em>tertiary</em> sector, not the primary sector, is now India's largest producer. R is true: more than half the workforce is indeed still in the primary sector, which is exactly why this mismatch is significant." },
    { assertion: "All service-sector jobs are highly paid and secure.",
      reason: "The tertiary sector includes both highly skilled professionals and a very large number of workers, such as small shopkeepers and repairpersons, who barely manage to earn a living.",
      answer: 3, importance: "medium",
      why: "A is false — service-sector jobs range widely in pay and security. R is true and is precisely why A is false: much of the sector's growth is distress-driven, not prosperity-driven." },
    { assertion: "MGNREGA guarantees 100 days of employment in a year to those in need of work in rural areas.",
      reason: "The Act was implemented by the central government in about 625 districts of the country.",
      answer: 1, importance: "medium",
      why: "Both statements are true, but R describes the geographic coverage of the Act, not the reason the guarantee is fixed at 100 days — so R does not correctly explain A." },
  ],
  caseStudies: [
    { title: "Reading GDP share against workforce share", importance: "high",
      source: "The table below shows the share of different sectors in GDP and in the workforce of a hypothetical economy:<br><table><thead><tr><th>Sector</th><th>Share in GDP (%)</th><th>Share in workforce (%)</th></tr></thead><tbody><tr><td>Primary</td><td>20</td><td>55</td></tr><tr><td>Secondary</td><td>30</td><td>20</td></tr><tr><td>Tertiary</td><td>50</td><td>25</td></tr></tbody></table>",
      caption: "Modelled on the historical-change tables used in the chapter.",
      parts: [
        { q: "Which sector contributes the most to GDP?", marks: 1, answer: "The <strong>tertiary sector</strong>, with 50% of GDP." },
        { q: "Which sector employs the largest share of the workforce?", marks: 1, answer: "The <strong>primary sector</strong>, employing 55% of the workforce." },
        { q: "If the total workforce is 8 crore, calculate the number of people employed in the primary sector.", marks: 2, answer: "55% of 8 crore = <strong>4.4 crore</strong> workers." },
        { q: "What term describes a situation where a sector employs far more people than its output requires?", marks: 1, answer: "<strong>Disguised unemployment</strong> (or underemployment) — workers appear employed but contribute little extra output." },
      ] },
    { title: "A worker in the unorganised sector", importance: "high",
      source: "Rakesh and Raghu work as helpers in a shop owned by Mohan in the local market. During the festive season, when the shop is very busy, they are made to work much longer hours, but their wages are not increased for the extra hours. If either of them falls ill, his wages are cut for the days he is absent, and neither gets any paid leave. Mohan can ask either of them to leave the job at any time, without giving a reason.",
      caption: "A standard board-style scenario on organised versus unorganised employment.",
      parts: [
        { q: "Are Rakesh and Raghu employed in the organised or the unorganised sector? Give one reason from the passage.", marks: 1, answer: "The <strong>unorganised sector</strong> — their employment is not regular or secure, and they can be dismissed without reason, which is a defining feature of this sector." },
        { q: "List two features of this sector illustrated by the passage.", marks: 2, answer: "<ul><li>No overtime pay despite longer working hours during the busy season.</li><li>No paid leave, and wages are cut for days absent due to illness — there is no sick leave provision.</li></ul>" },
        { q: "Name one law that protects organised sector workers but does not typically cover workers like Rakesh and Raghu.", marks: 1, answer: "The <strong>Factories Act</strong> (or the Minimum Wages Act, or the Payment of Gratuity Act) — these apply to registered organised-sector enterprises, not small unregistered shops." },
        { q: "Suggest one step the government could take to improve conditions for workers like Rakesh and Raghu.", marks: 1, answer: "Extend and strictly enforce minimum-wage and working-hours regulations to small unorganised establishments, and provide them access to social security schemes." },
      ] },
  ],
};
