import type { Chapter } from "@/lib/types";

export const ch20: Chapter = {
  slug: "money-and-credit",
  num: 3,
  title: "Money and Credit",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 16,
  blurb: "Credit can build a house or destroy a family. The difference is not the loan — it is the terms, and who is giving it.",
  bigIdea: "Everyone needs credit. The poor mostly get it from moneylenders on terms that trap them, which is why formal credit and self-help groups matter so much.",
  syllabus: [
    "Money as a medium of exchange",
    "Modern forms of money and deposits with banks",
    "Loan activities of banks",
    "Two different credit situations",
    "Terms of credit",
    "Formal and informal sources of credit",
    "Self-Help Groups for the poor",
  ],
  blocks: [
    { t: "h", text: "Why money exists" },
    { t: "p", html: "Money acts as an intermediate in the exchange process, and is therefore called a <strong>medium of exchange</strong>. Before money, exchange was by <strong>barter</strong>, which required a <strong>double coincidence of wants</strong> — what one person desires to sell is exactly what the other wishes to buy. Money removes that requirement: a person holding money can easily exchange it for any commodity or service." },
    { t: "note", kind: "real", html: "Money has taken many forms — grain and cattle in the earliest stages; then metallic coins of gold, silver and copper, a phase that continued well into the last century. Modern currency — paper notes and coins — is <strong>not made of precious metal and has no use of its own</strong>. It is accepted as a medium of exchange because the currency is <strong>authorised by the government of the country</strong>. In India, the <strong>Reserve Bank of India</strong> issues currency notes on behalf of the central government, and the law legalises the use of the rupee as a medium of payment that cannot be refused in settling transactions in India — this is why it is called <strong>legal tender</strong>." },
    { t: "p", html: "The other modern form is <strong>deposits with banks</strong>. People deposit extra cash with banks by opening an account, and banks accept deposits and also pay interest. Because the money is safe and earns interest, this is called a <strong>demand deposit</strong> — it can be withdrawn on demand. Demand deposits share the essential features of money, and the facility of <strong>cheques</strong> against demand deposits makes it possible to settle payments without the use of cash. A cheque is a paper instructing the bank to pay a specific amount from the person's account to the person in whose name the cheque has been issued." },

    { t: "h", text: "What banks do with the money" },
    { t: "sim", id: "money-credit" },
    { t: "p", html: "Banks keep only a small proportion of their deposits as cash with themselves — in India banks hold about <strong>15 per cent of their deposits as cash</strong>. This is kept as a provision to pay the depositors who might come to withdraw money on any given day. Banks use the major portion of the deposits to <strong>extend loans</strong>. Banks charge a higher interest rate on loans than what they offer on deposits, and the <strong>difference between what is charged from borrowers and what is paid to depositors is their main source of income</strong>." },

    { t: "h", text: "Credit: the two situations" },
    { t: "table", head: ["", "Salim, the shoe manufacturer", "Swapna, the small farmer"], rows: [
      ["The loan", "Obtains credit to meet the working capital needs of production — raw material, wages before payment arrives", "Borrows from a moneylender to meet the expenses of cultivation, at a high interest rate"],
      ["What happens", "Production is completed on time, he delivers the order, makes a good profit and repays the money borrowed", "The crop is hit by pests; the harvest is much less than usual. The loan cannot be repaid, and to repay she has to sell part of her land"],
      ["The outcome", "Credit helps him meet the ongoing expenses of production and complete it on time, thereby <strong>increasing his earnings</strong>", "She is caught in a <strong>debt trap</strong> — credit pushes her into a situation from which recovery is very painful"],
    ] },
    { t: "note", kind: "trap", html: "The exam asks: is credit useful or harmful? The correct answer is <strong>both, and it depends on the situation</strong>. Whether credit is useful or not depends on the risks in the situation and whether there is some support in case of loss." },
    { t: "note", kind: "why", title: "Terms of credit", html: "Every loan agreement specifies an <strong>interest rate</strong> which the borrower must pay along with the repayment of the principal. Lenders may demand <strong>collateral</strong> — an asset the borrower owns, such as land, building, vehicle, livestock or deposits with banks — used as a guarantee until the loan is repaid. If the borrower fails to repay, the lender has the right to sell the asset to obtain payment. There may also be <strong>documentation requirements</strong> and a <strong>mode of repayment</strong>. Interest rate, collateral, documentation requirement and the mode of repayment together comprise what is called the <strong>terms of credit</strong>. Terms of credit vary substantially from one credit arrangement to another, and they may vary depending on the nature of the lender and the borrower." },

    { t: "h", text: "Formal and informal sources" },
    { t: "table", head: ["", "Formal sector", "Informal sector"], rows: [
      ["Who lends", "Banks and cooperatives", "Moneylenders, traders, employers, relatives and friends"],
      ["Supervision", "The <strong>Reserve Bank of India</strong> supervises the functioning of formal sources. Banks have to submit information to the RBI on how much they are lending, to whom and at what interest rate", "<strong>No organisation supervises</strong> their credit activities. They can lend at whatever interest rate they choose, and there is no one to stop them from using unfair means to get their money back"],
      ["Interest rate", "Much lower", "Much higher — this means a larger part of the earnings of the borrowers is used to repay the loan"],
      ["Effect", "Credit at a low cost that can help increase incomes", "High cost of borrowing means less income left for the borrower, and can lead to increasing debt and a debt trap"],
    ] },
    { t: "note", kind: "idea", title: "The distribution problem", html: "In the rural areas, the formal sector still meets only about half of the total credit needs. The <strong>richer households</strong> receive most of the formal credit, while the <strong>poor households</strong> depend on informal sources. Compared to formal lenders, most of the informal lenders charge a much higher interest. The reason poor households cannot get bank loans is the requirement of <strong>collateral and documentation</strong>, which they lack. So it is necessary that banks and cooperatives increase their lending, particularly in rural areas, and that everyone receives these loans — not just the well-off." },

    { t: "h", text: "Self-Help Groups" },
    { t: "p", html: "A typical Self-Help Group has <strong>15 to 20 members</strong>, usually belonging to one neighbourhood, who meet and save regularly. Saving per member varies, and members can take small loans from the group itself to meet their needs. The group charges interest on these loans, but this is still <strong>less than what the moneylender charges</strong>. After a year or two, if the group is regular in savings, it becomes eligible for availing a loan from the bank. The loan is sanctioned in the name of the group and is meant to create <strong>self-employment opportunities</strong> for the members — releasing mortgaged land, meeting working capital needs, housing materials, acquiring assets like a sewing machine, handlooms, cattle." },
    { t: "note", kind: "real", html: "The SHG is the building block of organisation of the rural poor. It solves the collateral problem in a clever way: <strong>it is the group which is responsible for the repayment of the loan</strong>. Any case of non-repayment of a bank loan by any one member is followed up seriously by other members in the group, so banks are willing to lend to the poor women when organised in SHGs even though they have no collateral as such. Groups also help members become financially self-reliant, and the regular meetings provide a platform to discuss and act on a variety of social issues such as health, nutrition and domestic violence." },
  ],
  examFocus: [
    "Barter, double coincidence of wants, and how money removes it.",
    "Why modern currency is accepted — government authorisation, RBI, legal tender.",
    "Demand deposits and cheques.",
    "The 15 per cent cash reserve, and how banks earn their income.",
    "The Salim and Swapna contrast, and the conclusion that credit's effect depends on the situation.",
    "The four terms of credit, and what collateral means.",
    "Formal versus informal sources with the RBI's supervisory role.",
    "Why the poor cannot access formal credit, and how SHGs solve it.",
  ],
  flashcards: [
    { q: "What is double coincidence of wants?", a: "A requirement of barter exchange, where what one person wishes to sell is exactly what the other wishes to buy. Money removes this requirement by acting as a medium of exchange." },
    { q: "Why is modern currency accepted when it has no value of its own?", a: "Because it is authorised by the government of the country. In India the Reserve Bank of India issues currency notes on behalf of the central government, and law makes the rupee legal tender that cannot be refused in settling transactions." },
    { q: "What is a demand deposit?", a: "Money deposited with a bank in an account that can be withdrawn on demand. Demand deposits are safe, earn interest, and share the essential features of money." },
    { q: "What is a cheque?", a: "A paper instructing the bank to pay a specific amount from a person's account to the person in whose name the cheque has been issued, allowing payment without the use of cash." },
    { q: "What proportion of deposits do Indian banks hold as cash, and why?", a: "About 15 per cent, kept as a provision to pay depositors who might come to withdraw money on any given day. The rest is lent out." },
    { q: "How do banks earn their income?", a: "From the difference between the higher interest rate they charge borrowers and the lower rate they pay depositors." },
    { q: "Contrast Salim's and Swapna's use of credit.", a: "Salim used credit for working capital, completed his order on time, made a profit and repaid — credit increased his earnings. Swapna borrowed from a moneylender at high interest, her crop failed, and she had to sell land to repay — she fell into a debt trap." },
    { q: "What is a debt trap?", a: "A situation where a borrower cannot repay a loan and has to borrow more or sell assets to do so, leaving them worse off than before." },
    { q: "Name the terms of credit.", a: "Interest rate, collateral, documentation requirement, and mode of repayment." },
    { q: "What is collateral?", a: "An asset the borrower owns — land, building, vehicle, livestock or bank deposits — used as a guarantee to the lender until the loan is repaid. If the borrower fails to repay, the lender can sell it to recover the money." },
    { q: "Who supervises formal credit, and what is unsupervised about informal credit?", a: "The Reserve Bank of India supervises formal lenders, requiring banks to report how much they lend, to whom and at what rate. No organisation supervises informal lenders, who can charge any rate and use unfair means to recover money." },
    { q: "How does a Self-Help Group work?", a: "Fifteen to twenty members from one neighbourhood meet and save regularly, lending small amounts to each other at interest below the moneylender's rate. After a year or two of regular saving the group becomes eligible for a bank loan in the group's name, with the group collectively responsible for repayment — which solves the collateral problem." },
  ],
  quiz: [
    { q: "Barter exchange requires:", options: ["Legal tender", "Double coincidence of wants", "Collateral", "A bank account"], answer: 1, why: "Both parties must want exactly what the other has to offer, which money eliminates." },
    { q: "Currency notes in India are issued by:", options: ["The central government directly", "The Reserve Bank of India on behalf of the central government", "Commercial banks", "The Finance Ministry"], answer: 1, why: "The RBI issues currency notes on behalf of the central government, and law makes the rupee legal tender." },
    { q: "Indian banks hold roughly what share of deposits as cash?", options: ["5%", "15%", "35%", "50%"], answer: 1, why: "About 15 per cent is kept as a provision for depositors who may withdraw on a given day." },
    { q: "Banks' main source of income is:", options: ["Government subsidy", "The difference between lending and deposit interest rates", "Cheque fees", "Selling collateral"], answer: 1, why: "They charge borrowers more than they pay depositors, and the gap is their income." },
    { q: "An asset pledged as a guarantee for a loan is called:", options: ["Interest", "Collateral", "Principal", "Deposit"], answer: 1, why: "Collateral may be land, building, vehicle, livestock or bank deposits, and can be sold if the borrower defaults." },
    { q: "Which is a formal source of credit?", options: ["Moneylender", "Trader", "Cooperative", "Employer"], answer: 2, why: "Banks and cooperatives are formal sources, supervised by the Reserve Bank of India." },
    { q: "The main reason poor households cannot get bank loans is:", options: ["Banks have no money", "Lack of collateral and documentation", "They do not want loans", "The RBI forbids it"], answer: 1, why: "Absence of collateral and the documentation requirement keeps poor households dependent on informal lenders." },
    { q: "A typical Self-Help Group has:", options: ["5 to 10 members", "15 to 20 members", "50 members", "100 members"], answer: 1, why: "Fifteen to twenty members, usually from one neighbourhood, who meet and save regularly." },
    { q: "In an SHG bank loan, who is responsible for repayment?", options: ["The individual borrower", "The group", "The bank", "The government"], answer: 1, why: "The group is collectively responsible, which is why banks lend without conventional collateral." },
    { q: "Credit is harmful when:", options: ["The interest rate is low", "There is collateral", "The borrower faces a loss with no support, leading to a debt trap", "It is used for working capital"], answer: 2, why: "Whether credit helps depends on the risks in the situation and whether there is support in case of loss." },
  ],
};
