import type { Chapter } from "@/lib/types";

export const ch21: Chapter = {
  slug: "globalisation-and-the-indian-economy",
  num: 4,
  title: "Globalisation and the Indian Economy",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 16,
  blurb: "The phone in your hand was designed in one country, assembled in another, from parts made in five more. This chapter is about how that became normal, and who gained.",
  bigIdea: "Globalisation has not been fair. It has benefited well-off consumers and skilled producers; small producers and unorganised workers have mostly paid for it.",
  syllabus: [
    "Production across countries and multinational corporations",
    "Interlinking production across countries",
    "Foreign trade and integration of markets",
    "What is globalisation, and the factors enabling it",
    "World Trade Organisation",
    "Impact of globalisation in India",
    "The struggle for a fair globalisation",
  ],
  blocks: [
    { t: "h", text: "MNCs and how they spread production" },
    { t: "sim", id: "globalisation-chain" },
    { t: "p", html: "A <strong>multinational corporation (MNC)</strong> is a company that owns or controls production in more than one nation. MNCs set up offices and factories for production in regions where they can get <strong>cheap labour and other resources</strong>, so that the cost of production is low and they can earn greater profits. They look for locations close to the markets, where there is skilled and unskilled labour available at low costs, and where the availability of other factors of production is assured. In addition, they look for government policies that look after their interests." },
    { t: "list", items: [
      "Sometimes MNCs set up production <strong>jointly with local companies</strong>. The benefit to the local company is twofold: MNCs can provide money for additional investments, such as buying new machines for faster production, and they may bring with them the latest technology for production.",
      "The most common route for MNC investments is to <strong>buy up local companies and then expand production</strong>. MNCs with huge wealth can quite easily do so — the chapter's example is Cargill Foods buying Parakh Foods, which had four oil refineries and a large marketing network.",
      "A third way is <strong>placing orders with small producers</strong>. Garments, footwear and sports items are industries where production is carried out by a large number of small producers around the world. The products are supplied to the MNCs, which sell them under their own brand names to the customers. These large MNCs have <strong>tremendous power to determine price, quality, delivery and labour conditions</strong> for these distant producers.",
      "Investment made to buy assets such as land, building, machines and other equipment is called <strong>investment</strong>; investment made by MNCs is called <strong>foreign investment</strong>.",
    ] },
    { t: "note", kind: "idea", html: "The key phrase: MNCs are exerting a strong influence on production at these distant locations, and as a result <strong>production in these widely dispersed locations is getting interlinked</strong>. That interlinking is what makes it globalisation rather than merely trade." },

    { t: "h", text: "Foreign trade and globalisation" },
    { t: "p", html: "Foreign trade creates an opportunity for producers to reach <strong>beyond the domestic markets</strong>. Producers can sell their produce not only in markets located within the country but also compete in markets located in other countries. Similarly, for buyers, import of goods produced in another country is one way of expanding the choice of goods beyond what is domestically produced. The chapter's summary: <strong>foreign trade thus results in connecting the markets or integration of markets in different countries</strong>." },
    { t: "p", html: "<strong>Globalisation</strong> is this process of rapid integration or interconnection between countries. MNCs are playing a major role in it, and more and more goods and services, investments and technology are moving between countries. Most regions of the world are in closer contact with each other than a few decades back. Besides goods, services, investments and technology, there is one more way in which countries can be connected — the <strong>movement of people between countries</strong>, usually for better income, better jobs or better education." },

    { t: "h", text: "What made it possible" },
    { t: "table", head: ["Factor", "How it helped"], rows: [
      ["<strong>Technology</strong>", "Rapid improvement in transportation technology has made much faster delivery of goods across long distances possible at lower costs. Even more remarkable have been developments in <strong>information and communication technology</strong> — telecommunication, computers and the internet. Satellite communication devices help contact around the world, and the internet allows us to obtain and share information, send instant electronic mail and talk across the world at negligible costs"],
      ["<strong>Liberalisation of foreign trade and investment policy</strong>", "<strong>Trade barriers</strong> are restrictions such as tax on imports, used by governments to increase or decrease foreign trade and to decide what kinds of goods and how much of each should come into the country. The Indian government after independence had put barriers on foreign trade and investment to protect producers from foreign competition — industries were just coming up in the 1950s and 1960s, and competition from imports would not have allowed them to grow. Around <strong>1991</strong> the barriers were removed to a large extent, because it was felt that Indian producers should compete with producers around the globe to improve quality. Removing barriers or restrictions set by the government is called <strong>liberalisation</strong>. With liberalisation, businesses are allowed to make decisions freely about what they wish to import or export"],
    ] },
    { t: "note", kind: "real", title: "The World Trade Organisation", html: "The <strong>WTO</strong> is an organisation whose aim is to liberalise international trade. Started at the initiative of the <strong>developed countries</strong>, it establishes rules regarding international trade and sees that these rules are obeyed. Over 160 countries of the world are currently members — the exact number creeps up as new members accede, so write &quot;over 160&quot; rather than a figure you might misremember.<br><br>The criticism the chapter makes: though the WTO is supposed to allow free trade for all, in practice <strong>developed countries have unfairly retained trade barriers</strong>. The WTO rules have forced developing countries to remove trade barriers, while developed countries have <strong>continued to provide massive sums of money to their farmers as subsidies</strong>. Because of the subsidies, American farmers sell farm products at abnormally low prices, and Indian farmers face competition from these low-priced imports. This is the standard example, and the exam expects it." },

    { t: "h", text: "The impact, honestly assessed" },
    { t: "table", head: ["Who gained", "Who lost"], rows: [
      ["<strong>Consumers</strong>, particularly the well-off in urban areas, now have greater choice and enjoy improved quality and lower prices for several products", "<strong>Small producers</strong> — batteries, capacitors, plastics, toys, tyres, dairy products and vegetable oil — have been hit hard. Several units shut down, rendering many workers jobless"],
      ["<strong>Top Indian companies</strong> have benefited from increased competition, investing in newer technology and production methods and raising their production standards. Some have gained from successful collaborations with foreign companies", "<strong>Workers</strong> in the unorganised sector face flexible employment: workers are no longer employed on a permanent basis, so employers can adjust employment according to demand. Wages are low, jobs are no longer secure, and workers are forced to work long hours"],
      ["Globalisation has enabled some large Indian companies to emerge as <strong>multinationals themselves</strong> — Tata Motors, Infosys, Ranbaxy, Asian Paints, Sundaram Fasteners", "The pressure of competition has substantially changed the lives of workers, and the chapter states plainly: <strong>globalisation has not been fair</strong>"],
      ["New jobs have been created in <strong>services such as information technology</strong>, and several Indian companies providing services like data entry, accounting, administrative tasks and engineering are now being produced cheaply in India and exported", ""],
    ] },
    { t: "note", kind: "why", title: "Fair globalisation", html: "Fair globalisation would create opportunities for all, and also ensure that the benefits of globalisation are <strong>shared better</strong>. The government can play a major role in making this possible. Its policies must protect the interests not only of the rich and powerful but of all the people in the country. It can ensure that <strong>labour laws are properly implemented and workers get their rights</strong>. It can <strong>support small producers</strong> until they become strong enough to compete. If necessary, the government can <strong>use trade and investment barriers</strong>. It can <strong>negotiate at the WTO for fairer rules</strong>. It can also <strong>align with other developing countries</strong> with similar interests to fight against the domination of developed countries in the WTO." },
    { t: "note", kind: "idea", html: "The chapter also notes that people's movements have played an important part: massive campaigns and representation by people's organisations have influenced important decisions relating to trade and investments at the WTO. The people can play an important role in the struggle for fair globalisation — that is the closing line, and it is worth using." },
  ],
  examFocus: [
    "Definition of an MNC and the three ways they spread production, with Cargill–Parakh as the example.",
    "Why MNCs choose particular locations.",
    "How foreign trade integrates markets.",
    "Definition of globalisation, and the role of movement of people.",
    "The two enabling factors — technology and liberalisation — with 1991.",
    "Trade barriers, why India had them, and what liberalisation means.",
    "The WTO, its purpose, and the subsidy criticism with the American farmer example.",
    "Who benefited and who lost from globalisation in India.",
    "The five things the government can do for fair globalisation.",
  ],
  flashcards: [
    { q: "What is a multinational corporation?", a: "A company that owns or controls production in more than one nation, setting up offices and factories where it can get cheap labour and other resources so production costs are low and profits higher." },
    { q: "What do MNCs look for when choosing a location?", a: "Proximity to markets, skilled and unskilled labour available at low cost, assured availability of other factors of production, and government policies that look after their interests." },
    { q: "Name the three ways MNCs spread production.", a: "Setting up production jointly with local companies, buying up local companies and expanding production, and placing orders with small producers who supply goods sold under the MNC's brand." },
    { q: "Give the example of an MNC buying an Indian company.", a: "Cargill Foods bought Parakh Foods, which had four oil refineries and a large marketing network, making Cargill the largest producer of edible oil in India." },
    { q: "What power do MNCs hold over small producers who supply them?", a: "Tremendous power to determine price, quality, delivery and labour conditions for these distant producers." },
    { q: "How does foreign trade lead to integration of markets?", a: "Producers can sell beyond domestic markets and buyers can choose imported goods, so the prices and choices in different countries become connected." },
    { q: "Define globalisation.", a: "The process of rapid integration or interconnection between countries, in which goods, services, investment, technology and people move increasingly across borders. MNCs play a major role in it." },
    { q: "How has technology enabled globalisation?", a: "Faster and cheaper transportation of goods over long distances, and remarkable developments in information and communication technology — telecommunication, computers, the internet and satellite communication — allowing instant, cheap contact worldwide." },
    { q: "What are trade barriers and why did India have them?", a: "Restrictions such as taxes on imports, used to control what and how much comes into a country. India imposed them after independence to protect producers from foreign competition while industries were coming up in the 1950s and 1960s." },
    { q: "What is liberalisation, and when did India liberalise?", a: "Removing the barriers or restrictions set by the government, so businesses can decide freely what to import and export. India removed barriers to a large extent around 1991." },
    { q: "What is the criticism of the WTO?", a: "Though it is supposed to allow free trade for all, developed countries have unfairly retained trade barriers and continued massive farm subsidies, while WTO rules have forced developing countries to remove theirs. American farmers can then sell at abnormally low prices, undercutting Indian farmers." },
    { q: "Name four things the government can do to make globalisation fairer.", a: "Ensure labour laws are properly implemented and workers get their rights; support small producers until they can compete; use trade and investment barriers where necessary; negotiate at the WTO for fairer rules; and align with other developing countries with similar interests." },
  ],
  quiz: [
    { q: "An MNC is a company that:", options: ["Exports goods", "Owns or controls production in more than one nation", "Has foreign shareholders", "Imports raw material"], answer: 1, why: "Ownership or control of production in more than one nation is the defining feature." },
    { q: "Cargill Foods entered India by:", options: ["Setting up new factories", "Buying Parakh Foods", "Placing orders with small producers", "Exporting to India"], answer: 1, why: "Buying up local companies is the most common route for MNC investment; Cargill bought Parakh Foods with its four refineries." },
    { q: "Investment made by MNCs is called:", options: ["Domestic investment", "Foreign investment", "Portfolio investment", "Public investment"], answer: 1, why: "Investment made by MNCs to buy assets such as land, buildings and machines is foreign investment." },
    { q: "India removed most trade barriers around:", options: ["1947", "1971", "1991", "2001"], answer: 2, why: "Barriers were largely removed around 1991, on the view that Indian producers should compete globally to improve quality." },
    { q: "Removing government restrictions on trade is called:", options: ["Privatisation", "Liberalisation", "Globalisation", "Nationalisation"], answer: 1, why: "Liberalisation is the removal of barriers or restrictions set by the government." },
    { q: "The WTO was started at the initiative of:", options: ["Developing countries", "Developed countries", "The United Nations", "India and China"], answer: 1, why: "It was started at the initiative of developed countries, which the chapter links to its unequal rules." },
    { q: "American farmers can sell at abnormally low prices because of:", options: ["Better technology only", "Massive government subsidies", "Lower wages", "Cheaper land"], answer: 1, why: "Developed countries continue to provide massive sums as farm subsidies, undercutting Indian farmers." },
    { q: "Which group has clearly benefited from globalisation in India?", options: ["Small toy producers", "Unorganised sector workers", "Well-off urban consumers", "Battery manufacturers"], answer: 2, why: "Consumers, particularly the well-off in urban areas, enjoy greater choice, better quality and lower prices." },
    { q: "Flexible employment means:", options: ["Workers choose their hours", "Employers can adjust employment according to demand, so jobs are insecure", "More holidays", "Higher wages"], answer: 1, why: "Workers are no longer employed permanently; wages are low, jobs insecure and hours long." },
    { q: "Which Indian companies are named as having become multinationals?", options: ["Tata Motors, Infosys, Ranbaxy, Asian Paints", "Only public sector firms", "Parakh Foods and Cargill", "None"], answer: 0, why: "Tata Motors, Infosys, Ranbaxy, Asian Paints and Sundaram Fasteners are named as Indian MNCs." },
  ],
  keyTopics: [
    { name: "Multinational corporations — definition and the three ways they spread production", importance: "high", note: "The Cargill–Parakh example is the board's favourite illustration; know all three routes." },
    { name: "Globalisation — definition and the factors enabling it (technology, liberalisation, 1991)", importance: "high", note: "A guaranteed 3–5 mark question; the 1991 date is frequently asked directly." },
    { name: "The World Trade Organisation and the fairness criticism", importance: "high", note: "The farm-subsidy example (developed countries protecting their own farmers) is the standard 3–5 mark answer." },
    { name: "Impact of globalisation — who gained, who lost", importance: "high", note: "A recurring 5-mark 'assess the impact' question; know winners and losers on both sides." },
    { name: "Trade barriers and liberalisation", importance: "medium", note: "Tests why India imposed barriers after independence and why it removed them." },
    { name: "Foreign trade and the integration of markets", importance: "medium", note: "Conceptual link between trade and globalisation." },
    { name: "Steps toward fair globalisation", importance: "medium", note: "A common closing 5-mark 'what can the government do' question." },
  ],
  written: [
    { q: "Define a multinational corporation (MNC).", marks: 1, kind: "short", importance: "high",
      answer: "A company that <strong>owns or controls production in more than one nation</strong>, usually setting up offices and factories in locations where it can access cheap labour and other resources." },
    { q: "What is liberalisation?", marks: 1, kind: "short", importance: "high",
      answer: "The removal of <strong>trade barriers or restrictions</strong> set by the government, so that businesses can decide freely what to import or export." },
    { q: "What is meant by the \"integration of markets\"? How does foreign trade help achieve it?", marks: 2, kind: "short", importance: "medium",
      answer: "Integration of markets means markets in <strong>different countries become connected</strong>, so that similar goods are available to buyers everywhere and producers can sell beyond their own country. Foreign trade brings this about by letting producers compete in markets abroad and letting buyers choose imported goods alongside domestic ones, linking prices and choices across countries." },
    { q: "Give two ways in which multinational corporations interlink production across countries.", marks: 2, kind: "short", importance: "high",
      answer: "<ul><li>Setting up production <strong>jointly with local companies</strong>, providing investment and the latest technology.</li><li><strong>Buying up local companies</strong> and then expanding their production, as Cargill Foods did with Parakh Foods.</li></ul>(A third valid way: placing orders with small producers around the world, who supply goods sold under the MNC's own brand.)" },
    { q: "Name any four Indian companies that have grown into multinationals as a result of globalisation.", marks: 2, kind: "short", importance: "medium",
      answer: "<strong>Tata Motors, Infosys, Ranbaxy and Asian Paints</strong> (Sundaram Fasteners is a fifth commonly cited example)." },
    { q: "In a country, total foreign trade (exports + imports) was ₹5,00,000 crore when its GDP was ₹50,00,000 crore. Five years later, its foreign trade rose to ₹12,50,000 crore while GDP rose to ₹1,00,00,000 crore. Calculate the trade-to-GDP ratio in both years and comment on what the change suggests.", marks: 3, kind: "numerical", importance: "medium",
      answer: "Year 1: trade-to-GDP ratio = 5,00,000 ÷ 50,00,000 = <strong>10%</strong>.<br>Year 2: trade-to-GDP ratio = 12,50,000 ÷ 1,00,00,000 = <strong>12.5%</strong>.<br>Since the ratio rose from 10% to 12.5%, foreign trade is growing <em>faster</em> than the domestic economy — a sign of <strong>deepening integration with the world economy</strong>, i.e. increasing globalisation." },
    { q: "Explain any three factors that have enabled the rapid globalisation of the world economy.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Transport technology</strong> has made faster delivery of goods across long distances possible at lower cost.</li><li><strong>Information and communication technology</strong> — telecommunication, computers and the internet — allows instant, low-cost contact and data transfer across the world.</li><li><strong>Liberalisation</strong> of trade and investment policy: since around <strong>1991</strong>, India removed most of the barriers it had earlier placed on foreign trade and investment, believing that domestic producers should compete globally to improve quality.</li></ul>" },
    { q: "Distinguish between the sections of Indian society that gained and those that lost due to globalisation.", marks: 3, kind: "long", importance: "high",
      answer: "<ul><li><strong>Gained:</strong> well-off urban consumers, who enjoy greater choice, better quality and lower prices; top Indian companies that invested in new technology after facing competition; and some large Indian firms that themselves became multinationals (Tata Motors, Infosys).</li><li><strong>Lost:</strong> small producers of batteries, capacitors, plastics, toys, tyres, dairy products and vegetable oil, many of whom shut down; and unorganised-sector workers, who face flexible, insecure employment with low wages and long hours.</li></ul>" },
    { q: "Explain the role of the World Trade Organisation (WTO) in globalisation. Why is it criticised as being unfair to developing countries?", marks: 5, kind: "long", importance: "high",
      answer: "The WTO is an organisation whose aim is to <strong>liberalise international trade</strong>. Started at the initiative of developed countries, it establishes rules for international trade and ensures they are followed; over 160 countries are currently members.<br><strong>The unfairness:</strong> although the WTO is meant to allow free trade for all, in practice <strong>developed countries have unfairly retained trade barriers</strong>. WTO rules have forced developing countries to remove their barriers, while developed countries have continued to give <strong>massive subsidies to their own farmers</strong>. Because of these subsidies, American farmers can sell farm products at abnormally low prices, and Indian farmers then face unfair competition from these cheap imports. This is why developing countries argue for fairer WTO rules and often align with one another to negotiate collectively." },
    { q: "\"Globalisation has not been fair.\" Discuss this statement, and explain at least four steps the government can take to make globalisation fairer.", marks: 5, kind: "long", importance: "high",
      answer: "Globalisation has mainly benefited <strong>well-off consumers and skilled, educated workers</strong>, while <strong>small producers and unorganised workers</strong> have borne most of its costs — many small units shut down and workers face flexible, insecure employment. Fair globalisation would create opportunities for all and share the benefits more evenly. The government can:<ul><li>Ensure <strong>labour laws are properly implemented</strong> so that workers get the rights and security they are entitled to.</li><li><strong>Support small producers</strong> to raise their production standards until they are strong enough to compete.</li><li>Use <strong>trade and investment barriers</strong> where necessary to protect vulnerable domestic industries.</li><li><strong>Negotiate at the WTO</strong> for rules that are fairer to developing countries.</li><li><strong>Align with other developing countries</strong> with similar interests to jointly resist the domination of developed countries in WTO negotiations.</li></ul>" },
  ],
  assertionReason: [
    { assertion: "The World Trade Organisation aims to liberalise international trade.",
      reason: "It ensures that developed and developing countries follow exactly the same trade rules in practice.",
      answer: 2, importance: "high",
      why: "A is true — liberalising trade is the WTO's stated aim. R is false: in practice, developed countries have retained trade barriers such as farm subsidies while developing countries were made to remove theirs — the rules are not followed equally." },
    { assertion: "India removed most of its trade barriers around 1991.",
      reason: "It was believed that Indian producers should compete with producers around the globe to improve the quality of their products.",
      answer: 0, importance: "high", years: "2019",
      why: "Both statements are true, and R is the correct explanation: this belief was exactly the reasoning behind India's liberalisation of foreign trade and investment policy around 1991." },
    { assertion: "Multinational corporations expand production abroad only by setting up entirely new factories.",
      reason: "MNCs also spread production by buying up local companies and by placing orders with small producers who supply goods under the MNC's own brand.",
      answer: 3, importance: "medium",
      why: "A is false — setting up new factories is only one of three routes. R is true and names the other two routes, which is exactly why A is false." },
    { assertion: "Globalisation has benefited all sections of Indian society equally.",
      reason: "Small producers of goods such as toys, tyres and dairy products faced intense competition after liberalisation, and many of their units had to shut down.",
      answer: 3, importance: "high",
      why: "A is false — the chapter states plainly that globalisation has not been fair. R is true, and it is precisely this kind of outcome that shows why A is false." },
  ],
  caseStudies: [
    { title: "Reading a country's trade balance", importance: "high",
      source: "A country's exports and imports over two years were:<br><table><thead><tr><th>Year</th><th>Exports ($ billion)</th><th>Imports ($ billion)</th></tr></thead><tbody><tr><td>Year 1</td><td>200</td><td>250</td></tr><tr><td>Year 2</td><td>300</td><td>400</td></tr></tbody></table>",
      caption: "A constructed exercise in the style of the chapter's discussion of foreign trade.",
      parts: [
        { q: "Calculate the trade balance (exports minus imports) for both years.", marks: 2, answer: "Year 1: 200 − 250 = <strong>−$50 billion</strong>. Year 2: 300 − 400 = <strong>−$100 billion</strong>." },
        { q: "Is the country running a trade surplus or a trade deficit in both years?", marks: 1, answer: "A <strong>trade deficit</strong> in both years, since imports exceed exports each time." },
        { q: "How does the growth in both exports and imports between the two years reflect increasing globalisation?", marks: 1, answer: "Rising exports and imports show the country's producers and consumers are becoming <strong>more connected with markets abroad</strong> — buying more from and selling more to the rest of the world — which is exactly what integration of markets means." },
        { q: "Suggest one policy tool the government could use if it wanted to reduce this trade deficit by limiting imports.", marks: 1, answer: "Impose or raise a <strong>trade barrier</strong>, such as a tax (tariff) on imports, to make imported goods costlier and less attractive relative to domestic goods." },
      ] },
    { title: "Small producers under competition", importance: "medium",
      source: "Since trade barriers were lowered, several small Indian units producing toys, tyres, batteries and vegetable oil have faced stiff competition from multinational and imported goods, and many units have shut down, rendering many workers jobless. Meanwhile, top Indian companies in the same period have invested in new technology and raised their production standards, and well-off urban consumers now enjoy a wider choice of goods at lower prices.",
      caption: "Based on the chapter's honest assessment of who gained and who lost.",
      parts: [
        { q: "Identify two groups mentioned in the passage that lost out due to globalisation.", marks: 1, answer: "<strong>Small producers</strong> (of toys, tyres, batteries, vegetable oil) and the <strong>workers</strong> who lost their jobs when these units shut down." },
        { q: "Name one group mentioned in the passage that gained from globalisation.", marks: 1, answer: "<strong>Top Indian companies</strong> (or well-off urban consumers)." },
        { q: "What term describes a job situation in which workers are employed only when needed and can be let go without much difficulty?", marks: 1, answer: "<strong>Flexible employment.</strong>" },
        { q: "Suggest two measures the government could adopt to support small producers like these.", marks: 2, answer: "<ul><li>Provide financial and technical support to help them upgrade technology and compete.</li><li>Use trade barriers, where necessary, to give them temporary protection from unequal foreign competition until they are strong enough to compete on their own.</li></ul>" },
      ] },
  ],
};
