import type { Chapter } from "@/lib/types";

export const ch21: Chapter = {
  slug: "globalisation-and-the-indian-economy",
  num: 4,
  title: "Globalisation and the Indian Economy",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · 20 marks",
  minutes: 16,
  blurb: "The phone in your hand was designed in one country, assembled in another, from parts made in five more. This chapter is about how that became normal, and who gained.",
  bigIdea: "Globalisation has not been fair. It has benefited well-off consumers and skilled producers; small producers and unorganised workers have mostly paid for it.",
  syllabus: [
    "Production across countries and multinational corporations",
    "Interlinking production across countries",
    "Foreign trade and integration of markets",
    "What is globalisation, and the factors enabling it",
    "World Trade Organisation",
    "Impact of globalisation in India",
    "The struggle for a fair globalisation",
  ],
  blocks: [
    { t: "h", text: "MNCs and how they spread production" },
    { t: "sim", id: "globalisation-chain" },
    { t: "p", html: "A <strong>multinational corporation (MNC)</strong> is a company that owns or controls production in more than one nation. MNCs set up offices and factories for production in regions where they can get <strong>cheap labour and other resources</strong>, so that the cost of production is low and they can earn greater profits. They look for locations close to the markets, where there is skilled and unskilled labour available at low costs, and where the availability of other factors of production is assured. In addition, they look for government policies that look after their interests." },
    { t: "list", items: [
      "Sometimes MNCs set up production <strong>jointly with local companies</strong>. The benefit to the local company is twofold: MNCs can provide money for additional investments, such as buying new machines for faster production, and they may bring with them the latest technology for production.",
      "The most common route for MNC investments is to <strong>buy up local companies and then expand production</strong>. MNCs with huge wealth can quite easily do so — the chapter's example is Cargill Foods buying Parakh Foods, which had four oil refineries and a large marketing network.",
      "A third way is <strong>placing orders with small producers</strong>. Garments, footwear and sports items are industries where production is carried out by a large number of small producers around the world. The products are supplied to the MNCs, which sell them under their own brand names to the customers. These large MNCs have <strong>tremendous power to determine price, quality, delivery and labour conditions</strong> for these distant producers.",
      "Investment made to buy assets such as land, building, machines and other equipment is called <strong>investment</strong>; investment made by MNCs is called <strong>foreign investment</strong>.",
    ] },
    { t: "note", kind: "idea", html: "The key phrase: MNCs are exerting a strong influence on production at these distant locations, and as a result <strong>production in these widely dispersed locations is getting interlinked</strong>. That interlinking is what makes it globalisation rather than merely trade." },

    { t: "h", text: "Foreign trade and globalisation" },
    { t: "p", html: "Foreign trade creates an opportunity for producers to reach <strong>beyond the domestic markets</strong>. Producers can sell their produce not only in markets located within the country but also compete in markets located in other countries. Similarly, for buyers, import of goods produced in another country is one way of expanding the choice of goods beyond what is domestically produced. The chapter's summary: <strong>foreign trade thus results in connecting the markets or integration of markets in different countries</strong>." },
    { t: "p", html: "<strong>Globalisation</strong> is this process of rapid integration or interconnection between countries. MNCs are playing a major role in it, and more and more goods and services, investments and technology are moving between countries. Most regions of the world are in closer contact with each other than a few decades back. Besides goods, services, investments and technology, there is one more way in which countries can be connected — the <strong>movement of people between countries</strong>, usually for better income, better jobs or better education." },

    { t: "h", text: "What made it possible" },
    { t: "table", head: ["Factor", "How it helped"], rows: [
      ["<strong>Technology</strong>", "Rapid improvement in transportation technology has made much faster delivery of goods across long distances possible at lower costs. Even more remarkable have been developments in <strong>information and communication technology</strong> — telecommunication, computers and the internet. Satellite communication devices help contact around the world, and the internet allows us to obtain and share information, send instant electronic mail and talk across the world at negligible costs"],
      ["<strong>Liberalisation of foreign trade and investment policy</strong>", "<strong>Trade barriers</strong> are restrictions such as tax on imports, used by governments to increase or decrease foreign trade and to decide what kinds of goods and how much of each should come into the country. The Indian government after independence had put barriers on foreign trade and investment to protect producers from foreign competition — industries were just coming up in the 1950s and 1960s, and competition from imports would not have allowed them to grow. Around <strong>1991</strong> the barriers were removed to a large extent, because it was felt that Indian producers should compete with producers around the globe to improve quality. Removing barriers or restrictions set by the government is called <strong>liberalisation</strong>. With liberalisation, businesses are allowed to make decisions freely about what they wish to import or export"],
    ] },
    { t: "note", kind: "real", title: "The World Trade Organisation", html: "The <strong>WTO</strong> is an organisation whose aim is to liberalise international trade. Started at the initiative of the <strong>developed countries</strong>, it establishes rules regarding international trade and sees that these rules are obeyed. Over 160 countries of the world are currently members — the exact number creeps up as new members accede, so write &quot;over 160&quot; rather than a figure you might misremember.<br><br>The criticism the chapter makes: though the WTO is supposed to allow free trade for all, in practice <strong>developed countries have unfairly retained trade barriers</strong>. The WTO rules have forced developing countries to remove trade barriers, while developed countries have <strong>continued to provide massive sums of money to their farmers as subsidies</strong>. Because of the subsidies, American farmers sell farm products at abnormally low prices, and Indian farmers face competition from these low-priced imports. This is the standard example, and the exam expects it." },

    { t: "h", text: "The impact, honestly assessed" },
    { t: "table", head: ["Who gained", "Who lost"], rows: [
      ["<strong>Consumers</strong>, particularly the well-off in urban areas, now have greater choice and enjoy improved quality and lower prices for several products", "<strong>Small producers</strong> — batteries, capacitors, plastics, toys, tyres, dairy products and vegetable oil — have been hit hard. Several units shut down, rendering many workers jobless"],
      ["<strong>Top Indian companies</strong> have benefited from increased competition, investing in newer technology and production methods and raising their production standards. Some have gained from successful collaborations with foreign companies", "<strong>Workers</strong> in the unorganised sector face flexible employment: workers are no longer employed on a permanent basis, so employers can adjust employment according to demand. Wages are low, jobs are no longer secure, and workers are forced to work long hours"],
      ["Globalisation has enabled some large Indian companies to emerge as <strong>multinationals themselves</strong> — Tata Motors, Infosys, Ranbaxy, Asian Paints, Sundaram Fasteners", "The pressure of competition has substantially changed the lives of workers, and the chapter states plainly: <strong>globalisation has not been fair</strong>"],
      ["New jobs have been created in <strong>services such as information technology</strong>, and several Indian companies providing services like data entry, accounting, administrative tasks and engineering are now being produced cheaply in India and exported", ""],
    ] },
    { t: "note", kind: "why", title: "Fair globalisation", html: "Fair globalisation would create opportunities for all, and also ensure that the benefits of globalisation are <strong>shared better</strong>. The government can play a major role in making this possible. Its policies must protect the interests not only of the rich and powerful but of all the people in the country. It can ensure that <strong>labour laws are properly implemented and workers get their rights</strong>. It can <strong>support small producers</strong> until they become strong enough to compete. If necessary, the government can <strong>use trade and investment barriers</strong>. It can <strong>negotiate at the WTO for fairer rules</strong>. It can also <strong>align with other developing countries</strong> with similar interests to fight against the domination of developed countries in the WTO." },
    { t: "note", kind: "idea", html: "The chapter also notes that people's movements have played an important part: massive campaigns and representation by people's organisations have influenced important decisions relating to trade and investments at the WTO. The people can play an important role in the struggle for fair globalisation — that is the closing line, and it is worth using." },
  ],
  examFocus: [
    "Definition of an MNC and the three ways they spread production, with Cargill–Parakh as the example.",
    "Why MNCs choose particular locations.",
    "How foreign trade integrates markets.",
    "Definition of globalisation, and the role of movement of people.",
    "The two enabling factors — technology and liberalisation — with 1991.",
    "Trade barriers, why India had them, and what liberalisation means.",
    "The WTO, its purpose, and the subsidy criticism with the American farmer example.",
    "Who benefited and who lost from globalisation in India.",
    "The five things the government can do for fair globalisation.",
  ],
  flashcards: [
    { q: "What is a multinational corporation?", a: "A company that owns or controls production in more than one nation, setting up offices and factories where it can get cheap labour and other resources so production costs are low and profits higher." },
    { q: "What do MNCs look for when choosing a location?", a: "Proximity to markets, skilled and unskilled labour available at low cost, assured availability of other factors of production, and government policies that look after their interests." },
    { q: "Name the three ways MNCs spread production.", a: "Setting up production jointly with local companies, buying up local companies and expanding production, and placing orders with small producers who supply goods sold under the MNC's brand." },
    { q: "Give the example of an MNC buying an Indian company.", a: "Cargill Foods bought Parakh Foods, which had four oil refineries and a large marketing network, making Cargill the largest producer of edible oil in India." },
    { q: "What power do MNCs hold over small producers who supply them?", a: "Tremendous power to determine price, quality, delivery and labour conditions for these distant producers." },
    { q: "How does foreign trade lead to integration of markets?", a: "Producers can sell beyond domestic markets and buyers can choose imported goods, so the prices and choices in different countries become connected." },
    { q: "Define globalisation.", a: "The process of rapid integration or interconnection between countries, in which goods, services, investment, technology and people move increasingly across borders. MNCs play a major role in it." },
    { q: "How has technology enabled globalisation?", a: "Faster and cheaper transportation of goods over long distances, and remarkable developments in information and communication technology — telecommunication, computers, the internet and satellite communication — allowing instant, cheap contact worldwide." },
    { q: "What are trade barriers and why did India have them?", a: "Restrictions such as taxes on imports, used to control what and how much comes into a country. India imposed them after independence to protect producers from foreign competition while industries were coming up in the 1950s and 1960s." },
    { q: "What is liberalisation, and when did India liberalise?", a: "Removing the barriers or restrictions set by the government, so businesses can decide freely what to import and export. India removed barriers to a large extent around 1991." },
    { q: "What is the criticism of the WTO?", a: "Though it is supposed to allow free trade for all, developed countries have unfairly retained trade barriers and continued massive farm subsidies, while WTO rules have forced developing countries to remove theirs. American farmers can then sell at abnormally low prices, undercutting Indian farmers." },
    { q: "Name four things the government can do to make globalisation fairer.", a: "Ensure labour laws are properly implemented and workers get their rights; support small producers until they can compete; use trade and investment barriers where necessary; negotiate at the WTO for fairer rules; and align with other developing countries with similar interests." },
  ],
  quiz: [
    { q: "An MNC is a company that:", options: ["Exports goods", "Owns or controls production in more than one nation", "Has foreign shareholders", "Imports raw material"], answer: 1, why: "Ownership or control of production in more than one nation is the defining feature." },
    { q: "Cargill Foods entered India by:", options: ["Setting up new factories", "Buying Parakh Foods", "Placing orders with small producers", "Exporting to India"], answer: 1, why: "Buying up local companies is the most common route for MNC investment; Cargill bought Parakh Foods with its four refineries." },
    { q: "Investment made by MNCs is called:", options: ["Domestic investment", "Foreign investment", "Portfolio investment", "Public investment"], answer: 1, why: "Investment made by MNCs to buy assets such as land, buildings and machines is foreign investment." },
    { q: "India removed most trade barriers around:", options: ["1947", "1971", "1991", "2001"], answer: 2, why: "Barriers were largely removed around 1991, on the view that Indian producers should compete globally to improve quality." },
    { q: "Removing government restrictions on trade is called:", options: ["Privatisation", "Liberalisation", "Globalisation", "Nationalisation"], answer: 1, why: "Liberalisation is the removal of barriers or restrictions set by the government." },
    { q: "The WTO was started at the initiative of:", options: ["Developing countries", "Developed countries", "The United Nations", "India and China"], answer: 1, why: "It was started at the initiative of developed countries, which the chapter links to its unequal rules." },
    { q: "American farmers can sell at abnormally low prices because of:", options: ["Better technology only", "Massive government subsidies", "Lower wages", "Cheaper land"], answer: 1, why: "Developed countries continue to provide massive sums as farm subsidies, undercutting Indian farmers." },
    { q: "Which group has clearly benefited from globalisation in India?", options: ["Small toy producers", "Unorganised sector workers", "Well-off urban consumers", "Battery manufacturers"], answer: 2, why: "Consumers, particularly the well-off in urban areas, enjoy greater choice, better quality and lower prices." },
    { q: "Flexible employment means:", options: ["Workers choose their hours", "Employers can adjust employment according to demand, so jobs are insecure", "More holidays", "Higher wages"], answer: 1, why: "Workers are no longer employed permanently; wages are low, jobs insecure and hours long." },
    { q: "Which Indian companies are named as having become multinationals?", options: ["Tata Motors, Infosys, Ranbaxy, Asian Paints", "Only public sector firms", "Parakh Foods and Cargill", "None"], answer: 0, why: "Tata Motors, Infosys, Ranbaxy, Asian Paints and Sundaram Fasteners are named as Indian MNCs." },
  ],
};
