import type { Chapter } from "@/lib/types";

export const ch22: Chapter = {
  slug: "consumer-rights",
  num: 5,
  title: "Consumer Rights",
  unit: "economics",
  unitName: "Understanding Economic Development",
  marks: "Economics · project work",
  minutes: 14,
  formative: true,
  formativeLabel: "project work",
  blurb: "You are a consumer several times a day. This chapter is the short list of what you are legally owed, and what to do when you do not get it.",
  bigIdea: "Markets do not protect buyers on their own. Rights, information and a place to complain are what turn a buyer into a consumer.",
  syllabus: [
    "The consumer in the marketplace",
    "Consumer movement",
    "Consumer rights",
    "Taking the consumer movement forward",
    "Note: assessed through project work, not the written board paper",
  ],
  blocks: [
    { t: "note", kind: "exam", title: "How this chapter is assessed", html: "In the CBSE scheme this chapter is covered through <strong>project work</strong> rather than the written board paper. It still matters — it is examinable in school assessments, and it is the most directly useful chapter in the book." },

    { t: "h", text: "Why the movement began" },
    { t: "p", html: "The consumer movement arose out of <strong>dissatisfaction of the consumers</strong>, as many unfair practices were being indulged in by the sellers. There was no legal system available to consumers to protect them from exploitation in the marketplace. For a long time, when a consumer was not happy with a particular brand or shop, they generally avoided buying that brand, or would stop purchasing from that shop. It was presumed that it was the responsibility of consumers to be careful while buying a commodity or service — <strong>'let the buyer beware'</strong>. It took many years for organisations in India, and around the world, to create awareness amongst people." },
    { t: "note", kind: "real", html: "In India, the consumer movement as a social force originated with the necessity of protecting and promoting the interests of consumers against unethical and unfair trade practices. Rampant food shortages, hoarding, black marketing and adulteration of food and edible oil gave birth to the consumer movement in an organised form in the <strong>1960s</strong>. Till the 1970s consumer organisations were largely engaged in writing articles and holding exhibitions; more recently they have formed <strong>consumer groups that look into malpractices in ration shops and overcrowding in road passenger transport</strong>. In 1985 the United Nations adopted the <strong>UN Guidelines for Consumer Protection</strong>, a tool for nations to adopt measures to protect consumers and for consumer advocacy groups to press their governments." },

    { t: "h", text: "The six rights" },
    { t: "sim", id: "consumer-rights" },
    { t: "table", head: ["Right", "What it means in practice"], rows: [
      ["<strong>Right to Safety</strong>", "While using many goods and services, we as consumers have the right to be protected against the marketing of goods and delivery of services that are hazardous to life and property. Producers need to strictly follow the required safety rules and regulations — a defective pressure cooker or faulty wiring can cause injury or death"],
      ["<strong>Right to be Informed</strong>", "Consumers have the right to be informed about the particulars of goods and services. Rules make it compulsory for manufacturers to display <strong>ingredients used, price, batch number, date of manufacture, expiry date and address of the manufacturer</strong>. When there is a complaint, the product can be sent back. The <strong>Right to Information Act</strong>, passed in <strong>2005</strong>, extends this to information about the functions of government departments"],
      ["<strong>Right to Choose</strong>", "Any consumer who receives a service in whatever capacity, regardless of age, gender and nature of service, has the right to choose whether to continue to receive the service. A gas supply dealer cannot insist that you buy a stove from him as a condition of the connection"],
      ["<strong>Right to Seek Redressal</strong>", "Consumers have the right to seek redressal against unfair trade practices and exploitation. If any damage is done to a consumer, they have the right to get compensation depending on the degree of damage"],
      ["<strong>Right to Represent</strong>", "The right to be heard and represented in bodies that make decisions about consumer welfare. Consumer forums and councils give consumers a voice"],
      ["<strong>Right to Consumer Education</strong>", "The right to acquire the knowledge and skill to be an informed consumer. This is the right that makes all the others usable"],
    ] },
    { t: "note", kind: "why", title: "Where consumers get exploited", html: "The recurring situations: sellers who <strong>weigh less than they should</strong>; shopkeepers who <strong>charge more than the printed retail price</strong>; traders who indulge in <strong>unfair trade practices</strong> such as adding false information about a product; <strong>adulteration</strong> of food and edible oil; and the situation where <strong>producers are few and powerful while consumers are scattered and buy in small amounts</strong> — this happens most in the case of large companies producing goods that are in high demand. Add to this the fact that markets do not work in a fair manner when producers are few and powerful, and the case for legal protection is complete." },

    { t: "h", text: "The redressal machinery" },
    { t: "p", html: "The <strong>Consumer Protection Act (COPRA)</strong> was enacted in <strong>1986</strong>. It led to the setting up of separate departments of consumer affairs in central and state governments, and to a <strong>three-tier quasi-judicial machinery</strong> at the district, state and national levels. A newer Act replaced it in 2019, but the three-tier structure and the rights are what the syllabus tests." },
    { t: "table", head: ["Level", "Jurisdiction"], rows: [
      ["<strong>District</strong> commission", "Claims up to a specified lower limit"],
      ["<strong>State</strong> commission", "Claims above the district limit and up to a higher limit; also hears appeals against district orders"],
      ["<strong>National</strong> commission", "The largest claims; also hears appeals against state orders. If a consumer is not satisfied by the decision of the national commission, they can appeal in the Supreme Court"],
    ] },
    { t: "note", kind: "real", title: "The marks the exam actually wants", html: "<strong>ISI, Agmark and Hallmark</strong> are the logos and certification maintained for the protection of the quality of products. Consumers must look for them while purchasing goods and services. <strong>ISI</strong> for industrial and electrical goods, <strong>Agmark</strong> for agricultural products, and <strong>Hallmark</strong> for gold jewellery. <strong>24 December</strong> is observed as the <strong>National Consumers' Day</strong> in India, because it was on this day in 1986 that the Indian Parliament enacted the Consumer Protection Act. India is one of the countries that have exclusive courts for consumer redressal." },
    { t: "note", kind: "idea", title: "The honest assessment", html: "The chapter does not end triumphantly. Today there are more than 2,000 consumer groups in India, of which only about 50 to 60 are well organised and recognised for their work. The <strong>consumer redressal process is becoming cumbersome, expensive and time-consuming</strong>. Many a times consumers are required to engage lawyers, and these cases require time for filing and attending court proceedings. In most purchases <strong>cash memos are not issued</strong>, so evidence is not easy to gather. Most purchases in the market are small retail sales. The existing laws are also not very clear on the issue of compensation to consumers injured by defective products. The enforcement of laws that protect workers, especially in the unorganised sector, is weak. The chapter's conclusion: consumer awareness has to be spread, and <strong>consumers must become active participants, not passive buyers</strong>." },
  ],
  examFocus: [
    "Why the consumer movement arose, and the phrase 'let the buyer beware'.",
    "The 1960s origin in India, and the UN Guidelines of 1985.",
    "The six consumer rights with a practical example of each.",
    "The common forms of consumer exploitation.",
    "COPRA 1986 and the three-tier redressal machinery, with the appeal to the Supreme Court.",
    "ISI, Agmark and Hallmark, and what each certifies.",
    "24 December as National Consumers' Day and why.",
    "The limitations of the current redressal process.",
  ],
  flashcards: [
    { q: "What does 'let the buyer beware' mean and why is it inadequate?", a: "It presumed that the consumer alone was responsible for being careful while buying. It is inadequate because consumers cannot judge safety, purity or fairness on their own, and producers are few and powerful while consumers are scattered." },
    { q: "What gave rise to the organised consumer movement in India?", a: "Rampant food shortages, hoarding, black marketing and adulteration of food and edible oil, which brought the movement into organised form in the 1960s." },
    { q: "What are the UN Guidelines for Consumer Protection?", a: "Guidelines adopted by the United Nations in 1985, serving as a tool for nations to adopt measures to protect consumers and for consumer advocacy groups to press their governments." },
    { q: "State the Right to Safety.", a: "The right to be protected against the marketing of goods and delivery of services that are hazardous to life and property, with producers required to follow safety rules and regulations strictly." },
    { q: "What must a manufacturer display under the Right to be Informed?", a: "Ingredients used, price, batch number, date of manufacture, expiry date and the address of the manufacturer." },
    { q: "What is the Right to Information Act?", a: "An Act passed in 2005 ensuring citizens can obtain information about the functions of government departments, extending the principle of the right to be informed beyond goods and services." },
    { q: "Give an example of the Right to Choose being violated.", a: "A gas supply dealer insisting that the consumer buy a stove from him as a condition of getting the gas connection." },
    { q: "What is the Right to Seek Redressal?", a: "The right to seek remedy against unfair trade practices and exploitation, and to receive compensation proportionate to the damage suffered." },
    { q: "When was COPRA enacted and what did it set up?", a: "The Consumer Protection Act was enacted in 1986. It led to separate departments of consumer affairs in central and state governments and a three-tier quasi-judicial machinery at district, state and national levels." },
    { q: "What can a consumer do if unsatisfied with the national commission?", a: "Appeal to the Supreme Court of India." },
    { q: "What do ISI, Agmark and Hallmark certify?", a: "ISI certifies industrial and electrical goods, Agmark certifies agricultural products, and Hallmark certifies gold jewellery. All are quality certification marks consumers should look for." },
    { q: "Why is 24 December National Consumers' Day?", a: "Because the Indian Parliament enacted the Consumer Protection Act on that day in 1986. India is one of the few countries with exclusive courts for consumer redressal." },
  ],
  quiz: [
    { q: "'Let the buyer beware' means:", options: ["Sellers must warn buyers", "The consumer alone is responsible for being careful", "Prices must be displayed", "Goods must be tested"], answer: 1, why: "It was the old presumption that the responsibility for a bad purchase lay entirely with the buyer." },
    { q: "The organised consumer movement in India began in the:", options: ["1940s", "1960s", "1986", "2005"], answer: 1, why: "Food shortages, hoarding, black marketing and adulteration brought the movement into organised form in the 1960s." },
    { q: "The UN Guidelines for Consumer Protection were adopted in:", options: ["1960", "1985", "1986", "2005"], answer: 1, why: "The United Nations adopted them in 1985, a year before India's COPRA." },
    { q: "COPRA was enacted in:", options: ["1980", "1985", "1986", "1991"], answer: 2, why: "The Consumer Protection Act was enacted in 1986, and 24 December marks it as National Consumers' Day." },
    { q: "Agmark certifies:", options: ["Electrical goods", "Agricultural products", "Gold jewellery", "Packaged water"], answer: 1, why: "ISI is for industrial and electrical goods, Agmark for agricultural products and Hallmark for gold jewellery." },
    { q: "A dealer insisting you buy a stove to get a gas connection violates the right to:", options: ["Safety", "Choose", "Be informed", "Redressal"], answer: 1, why: "The Right to Choose protects a consumer from being forced to buy a bundled product or continue a service." },
    { q: "Expiry date and batch number on a packet reflect the right to:", options: ["Safety", "Be informed", "Choose", "Represent"], answer: 1, why: "The Right to be Informed makes displaying these particulars compulsory for manufacturers." },
    { q: "Appeals against the national commission go to:", options: ["The state commission", "The High Court", "The Supreme Court", "The consumer forum"], answer: 2, why: "A consumer unsatisfied with the national commission's decision can appeal to the Supreme Court." },
    { q: "National Consumers' Day in India is:", options: ["15 March", "24 December", "5 June", "2 October"], answer: 1, why: "24 December marks the enactment of the Consumer Protection Act in 1986." },
    { q: "A major limitation of the consumer redressal process is that:", options: ["There are no courts", "It is cumbersome, expensive and time-consuming, and cash memos are often not issued", "Consumers have no rights", "Only urban consumers can file"], answer: 1, why: "Consumers often need lawyers, cases take time, and without cash memos evidence is hard to gather." },
  ],
};
