import type { Chapter } from "@/lib/types";

export const ch01: Chapter = {
  slug: "real-numbers",
  num: 1,
  title: "Real Numbers",
  unit: "number",
  unitName: "Number Systems",
  marks: "Unit I · 6 marks",
  minutes: 14,
  blurb: "Every number breaks into primes in exactly one way — and that single fact is what makes HCF, LCM and the irrationality proofs work.",
  bigIdea: "There is only one way to build a number out of primes. Once you accept that, HCF and LCM stop being tricks and become bookkeeping.",
  syllabus: [
    "Fundamental Theorem of Arithmetic — statements and review",
    "Proofs of irrationality of √2, √3, √5",
  ],
  blocks: [
    { t: "h", text: "The Fundamental Theorem of Arithmetic" },
    { t: "p", html: "Take any composite number and break it into primes. You will always get the <em>same</em> primes, in the same amounts, no matter which order you pull it apart in. That is the theorem." },
    { t: "formula", name: "Fundamental Theorem of Arithmetic",
      expr: "Every composite number can be expressed as a product of primes, and this factorisation is <strong>unique</strong>, apart from the order of the factors." },
    { t: "sim", id: "factor-hcf-lcm" },
    { t: "note", kind: "why", title: "Why does uniqueness matter?", html: "Because it means the prime factorisation is a fingerprint. Two numbers share a factor only if they share a prime, so HCF is &ldquo;the primes both have, at the lowest power&rdquo; and LCM is &ldquo;every prime that appears, at the highest power&rdquo;. Without uniqueness, neither definition would even make sense." },
    { t: "table", head: ["", "How to read it off the factorisation"], rows: [
      ["<strong>HCF</strong>", "Product of the <em>common</em> prime factors, each raised to the <em>smallest</em> power in which it appears"],
      ["<strong>LCM</strong>", "Product of <em>all</em> prime factors, each raised to the <em>greatest</em> power in which it appears"],
    ] },
    { t: "formula", name: "The two-number identity", expr: "HCF(a, b) × LCM(a, b) = a × b",
      where: ["Only true for <strong>two</strong> numbers — it fails for three"] },
    { t: "note", kind: "trap", html: "This identity does <strong>not</strong> extend to three numbers. HCF × LCM ≠ a × b × c in general. Examiners set this deliberately, so if a question gives you three numbers, go back to prime factorisation." },

    { t: "steps", title: "Find the HCF and LCM of 96 and 404, and verify the identity.",
      intro: "The standard three-mark question. Factorise, read off, then check.",
      steps: [
        "96 = 2 × 2 × 2 × 2 × 2 × 3 = 2<sup>5</sup> × 3",
        "404 = 2 × 2 × 101 = 2<sup>2</sup> × 101",
        "<strong>HCF</strong>: the only common prime is 2, and the smallest power is 2<sup>2</sup>. So HCF = 4.",
        "<strong>LCM</strong>: take every prime at its highest power — 2<sup>5</sup> × 3 × 101 = 32 × 303 = 9696.",
        "Check: HCF × LCM = 4 × 9696 = 38784, and 96 × 404 = 38784. ✓",
      ],
      answer: "HCF = 4, LCM = 9696, and the identity holds.",
    },

    { t: "h", text: "Rational and irrational" },
    { t: "list", items: [
      "A <strong>rational number</strong> can be written as p/q where p and q are integers and q ≠ 0.",
      "An <strong>irrational number</strong> cannot. Its decimal expansion never terminates and never repeats.",
      "Together they make up the <strong>real numbers</strong>.",
    ] },
    { t: "note", kind: "idea", html: "Useful shortcuts the board expects you to know: <strong>rational + irrational = irrational</strong>. <strong>Rational (non-zero) × irrational = irrational</strong>. So 5 + √3 and 3√2 are both irrational without any further work." },

    { t: "h", text: "Proving √2 is irrational" },
    { t: "p", html: "This is a <strong>proof by contradiction</strong>, and it is the one proof from this chapter that is regularly asked for in full. The method is: assume the opposite, and show it leads somewhere impossible." },
    { t: "steps", title: "Prove that √2 is irrational.",
      intro: "Learn the shape of this argument — the same six steps prove √3 and √5 with only the numbers changed.",
      steps: [
        "Suppose, for contradiction, that √2 <em>is</em> rational. Then √2 = a/b, where a and b are integers with <strong>no common factor</strong> other than 1, and b ≠ 0.",
        "Rearranging: a = √2·b. Squaring both sides gives <strong>a² = 2b²</strong>.",
        "So a² is even, which means <strong>a is even</strong>. (If a were odd, a² would be odd.)",
        "Write a = 2c for some integer c. Substituting: (2c)² = 2b², so 4c² = 2b², so <strong>b² = 2c²</strong>.",
        "By the same reasoning, b² is even, so <strong>b is even</strong>.",
        "But now a and b are both even, so they share the factor 2 — contradicting our assumption that they had no common factor.",
      ],
      answer: "The assumption must be false. Therefore √2 is irrational. (Replace 2 with 3 or 5 throughout for those proofs.)",
    },
    { t: "note", kind: "exam", html: "Two things lose marks here. First, you must state that a and b are <strong>coprime</strong> at the start — the contradiction depends on it. Second, you must justify &ldquo;a² even ⟹ a even&rdquo; rather than asserting it." },
    { t: "note", kind: "memory", html: "Prove-irrational questions are usually dressed up: &ldquo;prove 5 − √3 is irrational&rdquo;. Assume it is rational, rearrange to isolate √3, and you get √3 = (something rational) — which contradicts the fact that √3 is irrational. Always isolate the surd." },
  ],
  formulas: [
    { name: "Fundamental Theorem of Arithmetic", expr: "Every composite number has a unique prime factorisation" },
    { name: "HCF × LCM", expr: "HCF(a,b) × LCM(a,b) = a × b", note: "Two numbers only" },
    { name: "HCF from factorisation", expr: "common primes, smallest powers" },
    { name: "LCM from factorisation", expr: "all primes, greatest powers" },
  ],
  examFocus: [
    "State the Fundamental Theorem of Arithmetic precisely, including the word <em>unique</em>.",
    "Find HCF and LCM by prime factorisation and verify HCF × LCM = product — and know it fails for three numbers.",
    "The full contradiction proof for √2, √3 or √5, including the coprime assumption.",
    "Proving numbers like 5 + √3 or 3√2 are irrational by isolating the surd.",
    "Knowing that rational + irrational is always irrational.",
  ],
  flashcards: [
    { q: "State the Fundamental Theorem of Arithmetic.", a: "Every composite number can be expressed as a product of primes, and this factorisation is unique apart from the order in which the primes are written." },
    { q: "How do you find HCF from prime factorisation?", a: "Take the primes common to both numbers, each raised to the smallest power in which it appears, and multiply them." },
    { q: "How do you find LCM from prime factorisation?", a: "Take every prime that appears in either number, each raised to the greatest power in which it appears, and multiply them." },
    { q: "State the relationship between HCF and LCM of two numbers.", a: "HCF(a,b) × LCM(a,b) = a × b. This holds only for two numbers, not three." },
    { q: "Define a rational and an irrational number.", a: "A rational number can be written as p/q with p, q integers and q ≠ 0. An irrational number cannot; its decimal expansion is non-terminating and non-repeating." },
    { q: "Outline the proof that √2 is irrational.", a: "Assume √2 = a/b with a, b coprime. Then a² = 2b², so a is even; write a = 2c, giving b² = 2c², so b is even too. But then a and b share the factor 2, contradicting coprimality. Hence √2 is irrational." },
    { q: "Why must a and b be taken as coprime in the irrationality proof?", a: "Because the contradiction is precisely that they turn out to share the factor 2. Without assuming coprimality at the start there would be nothing to contradict." },
    { q: "Is the sum of a rational and an irrational number rational or irrational?", a: "Always irrational. So numbers like 5 + √3 or 2 − √7 are irrational." },
    { q: "How do you prove 5 − √3 is irrational?", a: "Assume it is rational, say 5 − √3 = r. Then √3 = 5 − r, which is a difference of two rationals and therefore rational — contradicting the known irrationality of √3." },
    { q: "If a² is even, what can you say about a?", a: "a is even. If a were odd, a² would also be odd, so a² being even forces a to be even." },
    { q: "Find the HCF and LCM of 6 and 20.", a: "6 = 2 × 3, 20 = 2² × 5. HCF = 2. LCM = 2² × 3 × 5 = 60. Check: 2 × 60 = 120 = 6 × 20. ✓" },
    { q: "What are real numbers?", a: "All rational numbers together with all irrational numbers. Every point on the number line corresponds to exactly one real number." },
  ],
  quiz: [
    { q: "The prime factorisation of 156 is:", options: ["2² × 3 × 13", "2 × 3² × 13", "2² × 39", "2 × 78"], answer: 0, why: "156 = 2 × 78 = 2 × 2 × 39 = 2 × 2 × 3 × 13 = 2² × 3 × 13. The other options are not fully factorised into primes." },
    { q: "If HCF(a, b) = 9 and LCM(a, b) = 90, and a = 18, then b is:", options: ["45", "40", "9", "90"], answer: 0, why: "HCF × LCM = a × b, so 9 × 90 = 18 × b, giving 810 = 18b and b = 45." },
    { q: "The LCM of 12 and 18 is:", options: ["6", "36", "72", "216"], answer: 1, why: "12 = 2² × 3, 18 = 2 × 3². Take the highest power of each prime: 2² × 3² = 36." },
    { q: "Which of these is irrational?", options: ["√16", "0.333…", "3 + √5", "22/7"], answer: 2, why: "√16 = 4 is rational, 0.333… is a repeating decimal so rational, and 22/7 is a fraction. Rational + irrational is always irrational, so 3 + √5 is irrational." },
    { q: "In proving √2 is irrational, the assumption made at the start is that:", options: ["√2 is irrational", "√2 = a/b where a and b are coprime", "a is even", "b is odd"], answer: 1, why: "It is a proof by contradiction — you assume √2 is rational and can be written as a/b in lowest terms, then derive an impossibility." },
    { q: "The HCF of two consecutive natural numbers is always:", options: ["2", "1", "their product", "the smaller number"], answer: 1, why: "Consecutive numbers share no prime factor, so their HCF is 1 — they are coprime." },
    { q: "HCF × LCM = product of the numbers is true for:", options: ["Any number of numbers", "Exactly two numbers", "Only prime numbers", "Only even numbers"], answer: 1, why: "The identity holds only for two numbers. For three or more it generally fails." },
    { q: "If a² is divisible by 3, then:", options: ["a is divisible by 3", "a is divisible by 9", "a is even", "nothing can be said"], answer: 0, why: "Since 3 is prime, if 3 divides a² then 3 must divide a. This step is exactly what makes the √3 proof work." },
    { q: "The product of a non-zero rational and an irrational number is:", options: ["Always rational", "Always irrational", "Sometimes rational", "Zero"], answer: 1, why: "If it were rational you could divide by the rational factor and get the irrational number as a ratio of rationals — a contradiction." },
    { q: "The largest number that divides both 70 and 125 leaving remainders 5 and 8 is:", options: ["13", "65", "875", "1750"], answer: 0, why: "It must divide 70 − 5 = 65 and 125 − 8 = 117 exactly. HCF(65, 117): 65 = 5 × 13, 117 = 3² × 13, so HCF = 13." },
    { q: "Two numbers have HCF 27 and LCM 162. One number is 54. The other is:", options: ["81", "162", "27", "108"], answer: 0, why: "27 × 162 = 54 × b, so 4374 = 54b and b = 81." },
    { q: "Which statement is TRUE?", options: ["Every real number is rational", "Every integer is irrational", "√9 is irrational", "Every rational number is a real number"], answer: 3, why: "Real numbers are made up of rationals and irrationals together, so every rational is real. √9 = 3 is rational." },
  ],
  keyTopics: [
    { name: "Fundamental Theorem of Arithmetic — statement and uniqueness", importance: "high", note: "A guaranteed 1–2 mark definition, and the fact every HCF/LCM question quietly relies on." },
    { name: "HCF and LCM by prime factorisation", importance: "high", note: "The most frequent numerical in the chapter — usually 2 or 3 marks, sometimes for three numbers." },
    { name: "HCF(a,b) × LCM(a,b) = a × b, and that it fails for three numbers", importance: "high", note: "Tested directly and as an assertion–reason trap almost every year." },
    { name: "Proof that √2, √3 or √5 is irrational (proof by contradiction)", importance: "high", note: "A near-guaranteed 3–5 mark proof; know the coprime assumption and every step." },
    { name: "Proving expressions like 5 − √3 or 3√2 are irrational", importance: "medium", note: "Reuses the known irrationality of √2/√3/√5 — isolate the surd and contradict." },
    { name: "Real-life HCF/LCM word problems", importance: "medium", note: "Marching columns, packing identical boxes, longest measuring rod — all are just HCF in disguise." },
    { name: "Rational vs irrational — definitions and the sum/product rule", importance: "low", note: "Straightforward 1-mark recall, often folded into an assertion–reason." },
  ],
  written: [
    { q: "State the Fundamental Theorem of Arithmetic.", marks: 1, kind: "short", importance: "high",
      answer: "Every composite number can be expressed as a product of primes, and this factorisation is <strong>unique</strong>, apart from the order in which the prime factors occur." },
    { q: "Find the HCF and LCM of the smallest prime number and the smallest composite number.", marks: 1, kind: "numerical", importance: "medium", years: "2020",
      answer: "The smallest prime number is 2, and the smallest composite number is 4 (= 2²).<br>HCF(2, 4) = <strong>2</strong> &nbsp;·&nbsp; LCM(2, 4) = <strong>4</strong>." },
    { q: "Two numbers are in the ratio 2 : 3 and their LCM is 180. Find their HCF.", marks: 2, kind: "numerical", importance: "high", years: "2018",
      answer: "Let the numbers be 2x and 3x, where x is their HCF (since 2 and 3 share no common factor).<br>LCM of 2x and 3x is 6x. Given LCM = 180, so 6x = 180, giving <strong>x = 30</strong>.<br>So the numbers are 60 and 90, and their <strong>HCF = 30</strong>." },
    { q: "Prove that 3√2 is an irrational number.", marks: 2, kind: "long", importance: "high",
      answer: "Suppose, for contradiction, that 3√2 is rational. Then 3√2 = p/q for some integers p, q (q ≠ 0), so √2 = p/(3q).<br>Since p and 3q are both integers, p/(3q) is rational — meaning √2 would be rational. But √2 is known to be irrational. This is a contradiction.<br>Hence <strong>3√2 is irrational</strong>." },
    { q: "Find the HCF and LCM of 26 and 91 by prime factorisation, and verify that HCF × LCM = product of the two numbers.", marks: 2, kind: "numerical", importance: "high",
      answer: "26 = 2 × 13 &nbsp;·&nbsp; 91 = 7 × 13.<br>Common prime: 13, at the lowest power. <strong>HCF = 13</strong>.<br>Taking every prime at its highest power: 2 × 7 × 13 = <strong>LCM = 182</strong>.<br>Check: HCF × LCM = 13 × 182 = 2366, and 26 × 91 = 2366. ✓ The identity holds." },
    { q: "Given that √3 is irrational, prove that 5 − 2√3 is irrational.", marks: 3, kind: "long", importance: "high", years: "2019",
      answer: "Suppose, for contradiction, that 5 − 2√3 is rational; call it r. Then 5 − 2√3 = r, so <strong>2√3 = 5 − r</strong>, giving √3 = (5 − r)/2.<br>Since r is rational, 5 − r is rational, and so (5 − r)/2 is rational. This means √3 would be rational — contradicting the given fact that √3 is irrational.<br>Hence our assumption was wrong, and <strong>5 − 2√3 is irrational</strong>." },
    { q: "Find the HCF and LCM of 6, 72 and 120 using the prime factorisation method.", marks: 3, kind: "numerical", importance: "high",
      answer: "6 = 2 × 3 &nbsp;·&nbsp; 72 = 2³ × 3² &nbsp;·&nbsp; 120 = 2³ × 3 × 5.<br>Common primes to all three: 2 and 3. Lowest powers: 2¹ and 3¹. <strong>HCF = 2 × 3 = 6</strong>.<br>Every prime at its highest power across the three: 2³ × 3² × 5 = 8 × 9 × 5. <strong>LCM = 360</strong>." },
    { q: "Find the largest number which divides 615 and 963, leaving remainder 6 in each case.", marks: 3, kind: "numerical", importance: "medium",
      answer: "If the required number leaves remainder 6, it must divide 615 − 6 = 609 and 963 − 6 = 957 exactly.<br>609 = 3 × 7 × 29 &nbsp;·&nbsp; 957 = 3 × 11 × 29.<br>Common primes at lowest powers: 3 × 29 = <strong>87</strong>." },
    { q: "Prove that √5 is an irrational number.", marks: 5, kind: "long", importance: "high",
      answer: "Suppose, for contradiction, that √5 is rational. Then √5 = a/b, where a and b are integers with <strong>no common factor other than 1</strong>, and b ≠ 0.<br>Rearranging and squaring: a = √5·b ⟹ <strong>a² = 5b²</strong>.<br>So 5 divides a², and since 5 is prime, 5 must divide a. Write a = 5c for some integer c.<br>Substituting: (5c)² = 5b² ⟹ 25c² = 5b² ⟹ <strong>b² = 5c²</strong>.<br>By the same reasoning, 5 divides b² and so 5 divides b.<br>But then a and b are both divisible by 5, contradicting the assumption that they share no common factor.<br>Hence the assumption is false, and <strong>√5 is irrational</strong>." },
    { q: "The length, breadth and height of a room are 8 m 25 cm, 6 m 75 cm and 4 m 50 cm respectively. Find the longest rod that can measure the three dimensions of the room exactly.", marks: 5, kind: "numerical", importance: "medium", years: "AI 2016",
      answer: "Convert everything to centimetres: 8 m 25 cm = 825 cm, 6 m 75 cm = 675 cm, 4 m 50 cm = 450 cm. The longest such rod is the <strong>HCF</strong> of 825, 675 and 450.<br>825 = 3 × 5² × 11 &nbsp;·&nbsp; 675 = 3³ × 5² &nbsp;·&nbsp; 450 = 2 × 3² × 5².<br>Common primes at their lowest powers: 3¹ and 5². HCF = 3 × 25 = <strong>75</strong>.<br>The longest rod that can measure all three dimensions exactly is <strong>75 cm</strong>." },
  ],
  assertionReason: [
    { assertion: "6ⁿ, where n is a natural number, cannot end with the digit 0.",
      reason: "6ⁿ = 2ⁿ × 3ⁿ, and for a number to end in 0 its prime factorisation must include both 2 and 5.",
      answer: 0, importance: "high", years: "2020, 2023",
      why: "Both statements are true. Since 6ⁿ has no factor of 5 in its prime factorisation, it can never be divisible by 10, so it can never end in 0 — R correctly explains A." },
    { assertion: "√5 is an irrational number.",
      reason: "The sum of a rational number and an irrational number is always irrational.",
      answer: 1, importance: "medium",
      why: "Both statements are true on their own, but R is about sums of numbers — it has nothing to do with why √5 itself is irrational, so it does not explain A." },
    { assertion: "3 + 2√5 is an irrational number.",
      reason: "The sum of two irrational numbers is always an irrational number.",
      answer: 2, importance: "high",
      why: "A is true: 2√5 is irrational, and rational + irrational is always irrational. But R is false — two irrationals can sum to a rational number, e.g. (2 + √5) + (2 − √5) = 4." },
    { assertion: "The HCF of 96 and 404 is 8.",
      reason: "The HCF of two numbers is the product of the smallest power of each common prime factor of the numbers.",
      answer: 3, importance: "medium",
      why: "96 = 2⁵ × 3 and 404 = 2² × 101, so the only common prime is 2 at the lower power 2², giving HCF = 4, not 8 — A is false. R states a correct general rule, so R is true." },
  ],
  caseStudies: [
    { title: "Marching columns and prime factorisation", importance: "high", years: "2023",
      source: "For the school's Republic Day parade, a group of 108 students from Class X and a group of 90 students from Class IX will march behind the school band. Each group must be arranged in the same number of equal-sized columns, with no student left over.",
      parts: [
        { q: "Express 108 and 90 as a product of their prime factors.", marks: 1, answer: "108 = 2² × 3³ &nbsp;·&nbsp; 90 = 2 × 3² × 5." },
        { q: "Find the maximum number of columns in which the two groups can march.", marks: 2, answer: "This is the HCF of 108 and 90. The common prime factors are 2 and 3, at their lowest powers: 2¹ and 3². HCF = 2 × 9 = <strong>18</strong>. So the maximum number of columns is 18." },
        { q: "How many students from each group stand in every column?", marks: 1, answer: "Class X: 108 ÷ 18 = <strong>6</strong> students per column. Class IX: 90 ÷ 18 = <strong>5</strong> students per column." },
        { q: "A third group of 135 NCC cadets joins, and all three groups must now march in the same number of columns. What is the new maximum number of columns?", marks: 1, answer: "135 = 3³ × 5. The only prime common to 108, 90 and 135 is 3, at its lowest power 3². New HCF = <strong>9</strong>, so the maximum number of columns is now 9." },
      ] },
  ],
};
