import type { Chapter } from "@/lib/types";

export const ch01: Chapter = {
  slug: "real-numbers",
  num: 1,
  title: "Real Numbers",
  unit: "number",
  unitName: "Number Systems",
  marks: "Unit I · 6 marks",
  minutes: 14,
  blurb: "Every number breaks into primes in exactly one way — and that single fact is what makes HCF, LCM and the irrationality proofs work.",
  bigIdea: "There is only one way to build a number out of primes. Once you accept that, HCF and LCM stop being tricks and become bookkeeping.",
  syllabus: [
    "Fundamental Theorem of Arithmetic — statements and review",
    "Proofs of irrationality of √2, √3, √5",
  ],
  blocks: [
    { t: "h", text: "The Fundamental Theorem of Arithmetic" },
    { t: "p", html: "Take any composite number and break it into primes. You will always get the <em>same</em> primes, in the same amounts, no matter which order you pull it apart in. That is the theorem." },
    { t: "formula", name: "Fundamental Theorem of Arithmetic",
      expr: "Every composite number can be expressed as a product of primes, and this factorisation is <strong>unique</strong>, apart from the order of the factors." },
    { t: "sim", id: "factor-hcf-lcm" },
    { t: "note", kind: "why", title: "Why does uniqueness matter?", html: "Because it means the prime factorisation is a fingerprint. Two numbers share a factor only if they share a prime, so HCF is &ldquo;the primes both have, at the lowest power&rdquo; and LCM is &ldquo;every prime that appears, at the highest power&rdquo;. Without uniqueness, neither definition would even make sense." },
    { t: "table", head: ["", "How to read it off the factorisation"], rows: [
      ["<strong>HCF</strong>", "Product of the <em>common</em> prime factors, each raised to the <em>smallest</em> power in which it appears"],
      ["<strong>LCM</strong>", "Product of <em>all</em> prime factors, each raised to the <em>greatest</em> power in which it appears"],
    ] },
    { t: "formula", name: "The two-number identity", expr: "HCF(a, b) × LCM(a, b) = a × b",
      where: ["Only true for <strong>two</strong> numbers — it fails for three"] },
    { t: "note", kind: "trap", html: "This identity does <strong>not</strong> extend to three numbers. HCF × LCM ≠ a × b × c in general. Examiners set this deliberately, so if a question gives you three numbers, go back to prime factorisation." },

    { t: "steps", title: "Find the HCF and LCM of 96 and 404, and verify the identity.",
      intro: "The standard three-mark question. Factorise, read off, then check.",
      steps: [
        "96 = 2 × 2 × 2 × 2 × 2 × 3 = 2<sup>5</sup> × 3",
        "404 = 2 × 2 × 101 = 2<sup>2</sup> × 101",
        "<strong>HCF</strong>: the only common prime is 2, and the smallest power is 2<sup>2</sup>. So HCF = 4.",
        "<strong>LCM</strong>: take every prime at its highest power — 2<sup>5</sup> × 3 × 101 = 32 × 303 = 9696.",
        "Check: HCF × LCM = 4 × 9696 = 38784, and 96 × 404 = 38784. ✓",
      ],
      answer: "HCF = 4, LCM = 9696, and the identity holds.",
    },

    { t: "h", text: "Rational and irrational" },
    { t: "list", items: [
      "A <strong>rational number</strong> can be written as p/q where p and q are integers and q ≠ 0.",
      "An <strong>irrational number</strong> cannot. Its decimal expansion never terminates and never repeats.",
      "Together they make up the <strong>real numbers</strong>.",
    ] },
    { t: "note", kind: "idea", html: "Useful shortcuts the board expects you to know: <strong>rational + irrational = irrational</strong>. <strong>Rational (non-zero) × irrational = irrational</strong>. So 5 + √3 and 3√2 are both irrational without any further work." },

    { t: "h", text: "Proving √2 is irrational" },
    { t: "p", html: "This is a <strong>proof by contradiction</strong>, and it is the one proof from this chapter that is regularly asked for in full. The method is: assume the opposite, and show it leads somewhere impossible." },
    { t: "steps", title: "Prove that √2 is irrational.",
      intro: "Learn the shape of this argument — the same six steps prove √3 and √5 with only the numbers changed.",
      steps: [
        "Suppose, for contradiction, that √2 <em>is</em> rational. Then √2 = a/b, where a and b are integers with <strong>no common factor</strong> other than 1, and b ≠ 0.",
        "Rearranging: a = √2·b. Squaring both sides gives <strong>a² = 2b²</strong>.",
        "So a² is even, which means <strong>a is even</strong>. (If a were odd, a² would be odd.)",
        "Write a = 2c for some integer c. Substituting: (2c)² = 2b², so 4c² = 2b², so <strong>b² = 2c²</strong>.",
        "By the same reasoning, b² is even, so <strong>b is even</strong>.",
        "But now a and b are both even, so they share the factor 2 — contradicting our assumption that they had no common factor.",
      ],
      answer: "The assumption must be false. Therefore √2 is irrational. (Replace 2 with 3 or 5 throughout for those proofs.)",
    },
    { t: "note", kind: "exam", html: "Two things lose marks here. First, you must state that a and b are <strong>coprime</strong> at the start — the contradiction depends on it. Second, you must justify &ldquo;a² even ⟹ a even&rdquo; rather than asserting it." },
    { t: "note", kind: "memory", html: "Prove-irrational questions are usually dressed up: &ldquo;prove 5 − √3 is irrational&rdquo;. Assume it is rational, rearrange to isolate √3, and you get √3 = (something rational) — which contradicts the fact that √3 is irrational. Always isolate the surd." },
  ],
  formulas: [
    { name: "Fundamental Theorem of Arithmetic", expr: "Every composite number has a unique prime factorisation" },
    { name: "HCF × LCM", expr: "HCF(a,b) × LCM(a,b) = a × b", note: "Two numbers only" },
    { name: "HCF from factorisation", expr: "common primes, smallest powers" },
    { name: "LCM from factorisation", expr: "all primes, greatest powers" },
  ],
  examFocus: [
    "State the Fundamental Theorem of Arithmetic precisely, including the word <em>unique</em>.",
    "Find HCF and LCM by prime factorisation and verify HCF × LCM = product — and know it fails for three numbers.",
    "The full contradiction proof for √2, √3 or √5, including the coprime assumption.",
    "Proving numbers like 5 + √3 or 3√2 are irrational by isolating the surd.",
    "Knowing that rational + irrational is always irrational.",
  ],
  flashcards: [
    { q: "State the Fundamental Theorem of Arithmetic.", a: "Every composite number can be expressed as a product of primes, and this factorisation is unique apart from the order in which the primes are written." },
    { q: "How do you find HCF from prime factorisation?", a: "Take the primes common to both numbers, each raised to the smallest power in which it appears, and multiply them." },
    { q: "How do you find LCM from prime factorisation?", a: "Take every prime that appears in either number, each raised to the greatest power in which it appears, and multiply them." },
    { q: "State the relationship between HCF and LCM of two numbers.", a: "HCF(a,b) × LCM(a,b) = a × b. This holds only for two numbers, not three." },
    { q: "Define a rational and an irrational number.", a: "A rational number can be written as p/q with p, q integers and q ≠ 0. An irrational number cannot; its decimal expansion is non-terminating and non-repeating." },
    { q: "Outline the proof that √2 is irrational.", a: "Assume √2 = a/b with a, b coprime. Then a² = 2b², so a is even; write a = 2c, giving b² = 2c², so b is even too. But then a and b share the factor 2, contradicting coprimality. Hence √2 is irrational." },
    { q: "Why must a and b be taken as coprime in the irrationality proof?", a: "Because the contradiction is precisely that they turn out to share the factor 2. Without assuming coprimality at the start there would be nothing to contradict." },
    { q: "Is the sum of a rational and an irrational number rational or irrational?", a: "Always irrational. So numbers like 5 + √3 or 2 − √7 are irrational." },
    { q: "How do you prove 5 − √3 is irrational?", a: "Assume it is rational, say 5 − √3 = r. Then √3 = 5 − r, which is a difference of two rationals and therefore rational — contradicting the known irrationality of √3." },
    { q: "If a² is even, what can you say about a?", a: "a is even. If a were odd, a² would also be odd, so a² being even forces a to be even." },
    { q: "Find the HCF and LCM of 6 and 20.", a: "6 = 2 × 3, 20 = 2² × 5. HCF = 2. LCM = 2² × 3 × 5 = 60. Check: 2 × 60 = 120 = 6 × 20. ✓" },
    { q: "What are real numbers?", a: "All rational numbers together with all irrational numbers. Every point on the number line corresponds to exactly one real number." },
  ],
  quiz: [
    { q: "The prime factorisation of 156 is:", options: ["2² × 3 × 13", "2 × 3² × 13", "2² × 39", "2 × 78"], answer: 0, why: "156 = 2 × 78 = 2 × 2 × 39 = 2 × 2 × 3 × 13 = 2² × 3 × 13. The other options are not fully factorised into primes." },
    { q: "If HCF(a, b) = 9 and LCM(a, b) = 90, and a = 18, then b is:", options: ["45", "40", "9", "90"], answer: 0, why: "HCF × LCM = a × b, so 9 × 90 = 18 × b, giving 810 = 18b and b = 45." },
    { q: "The LCM of 12 and 18 is:", options: ["6", "36", "72", "216"], answer: 1, why: "12 = 2² × 3, 18 = 2 × 3². Take the highest power of each prime: 2² × 3² = 36." },
    { q: "Which of these is irrational?", options: ["√16", "0.333…", "3 + √5", "22/7"], answer: 2, why: "√16 = 4 is rational, 0.333… is a repeating decimal so rational, and 22/7 is a fraction. Rational + irrational is always irrational, so 3 + √5 is irrational." },
    { q: "In proving √2 is irrational, the assumption made at the start is that:", options: ["√2 is irrational", "√2 = a/b where a and b are coprime", "a is even", "b is odd"], answer: 1, why: "It is a proof by contradiction — you assume √2 is rational and can be written as a/b in lowest terms, then derive an impossibility." },
    { q: "The HCF of two consecutive natural numbers is always:", options: ["2", "1", "their product", "the smaller number"], answer: 1, why: "Consecutive numbers share no prime factor, so their HCF is 1 — they are coprime." },
    { q: "HCF × LCM = product of the numbers is true for:", options: ["Any number of numbers", "Exactly two numbers", "Only prime numbers", "Only even numbers"], answer: 1, why: "The identity holds only for two numbers. For three or more it generally fails." },
    { q: "If a² is divisible by 3, then:", options: ["a is divisible by 3", "a is divisible by 9", "a is even", "nothing can be said"], answer: 0, why: "Since 3 is prime, if 3 divides a² then 3 must divide a. This step is exactly what makes the √3 proof work." },
    { q: "The product of a non-zero rational and an irrational number is:", options: ["Always rational", "Always irrational", "Sometimes rational", "Zero"], answer: 1, why: "If it were rational you could divide by the rational factor and get the irrational number as a ratio of rationals — a contradiction." },
    { q: "The largest number that divides both 70 and 125 leaving remainders 5 and 8 is:", options: ["13", "65", "875", "1750"], answer: 0, why: "It must divide 70 − 5 = 65 and 125 − 8 = 117 exactly. HCF(65, 117): 65 = 5 × 13, 117 = 3² × 13, so HCF = 13." },
    { q: "Two numbers have HCF 27 and LCM 162. One number is 54. The other is:", options: ["81", "162", "27", "108"], answer: 0, why: "27 × 162 = 54 × b, so 4374 = 54b and b = 81." },
    { q: "Which statement is TRUE?", options: ["Every real number is rational", "Every integer is irrational", "√9 is irrational", "Every rational number is a real number"], answer: 3, why: "Real numbers are made up of rationals and irrationals together, so every rational is real. √9 = 3 is rational." },
  ],
};
