import type { Chapter } from "@/lib/types";

export const ch02: Chapter = {
  slug: "polynomials",
  num: 2,
  title: "Polynomials",
  unit: "algebra",
  unitName: "Algebra",
  marks: "Unit II · 20 marks",
  minutes: 16,
  blurb: "A zero is where the graph crosses the x-axis. Everything else in this chapter is the relationship between those zeros and the coefficients.",
  bigIdea: "You can read the zeros off a graph, and you can read the sum and product of the zeros straight off the coefficients — without ever finding the zeros themselves.",
  syllabus: [
    "Zeros of a polynomial",
    "Relationship between zeros and coefficients of quadratic polynomials",
  ],
  blocks: [
    { t: "h", text: "Degree, and how many zeros to expect" },
    { t: "p", html: "The <strong>degree</strong> of a polynomial is the highest power of x in it. That number caps how many zeros it can have — and, more usefully, it tells you the shape of the graph." },
    { t: "table", head: ["Degree", "Name", "General form", "Shape", "Max zeros"], rows: [
      ["1", "Linear", "ax + b, a ≠ 0", "Straight line", "1"],
      ["2", "Quadratic", "ax² + bx + c, a ≠ 0", "Parabola (U or ∩)", "2"],
      ["3", "Cubic", "ax³ + bx² + cx + d, a ≠ 0", "S-shaped curve", "3"],
    ] },
    { t: "sim", id: "polynomial-graph" },
    { t: "note", kind: "idea", html: "A <strong>zero</strong> of p(x) is a value k for which p(k) = 0. Geometrically it is the x-coordinate of a point where the graph meets the x-axis. So &ldquo;how many zeros does this graph show?&rdquo; is simply &ldquo;how many times does it cross or touch the x-axis?&rdquo;" },
    { t: "note", kind: "exam", html: "Graph-reading questions are almost free marks. A parabola that misses the axis entirely has <strong>zero</strong> real zeros; one that just touches it has <strong>one</strong> (a repeated zero); one that cuts through twice has <strong>two</strong>." },
    { t: "note", kind: "trap", html: "&ldquo;Degree 3&rdquo; means <em>at most</em> three zeros, not exactly three. A cubic can perfectly well have only one real zero — try it in the explorer above." },

    { t: "h", text: "Zeros and coefficients" },
    { t: "p", html: "This is the heart of the chapter. If α and β are the zeros of the quadratic ax² + bx + c, then:" },
    { t: "formula", name: "For a quadratic", expr: "α + β = −b/a &nbsp;&nbsp;·&nbsp;&nbsp; αβ = c/a",
      where: ["α, β = the two zeros", "a, b, c = the coefficients of ax² + bx + c"] },
    { t: "note", kind: "why", title: "Where does that come from?", html: "If α and β are the zeros, the polynomial factorises as a(x − α)(x − β). Expand it: a[x² − (α+β)x + αβ] = ax² − a(α+β)x + aαβ. Comparing with ax² + bx + c gives −a(α+β) = b and aαβ = c, which rearrange to the two formulas." },
    { t: "formula", name: "Building a quadratic from its zeros",
      expr: "p(x) = k[x² − (sum of zeros)x + (product of zeros)]",
      where: ["k is any non-zero constant — usually take k = 1"] },
    { t: "note", kind: "memory", html: "Sum has a <strong>minus</strong>, product does not: <strong>−b/a</strong> and <strong>c/a</strong>. Getting the sign wrong on the sum is the single most common mistake in this chapter." },

    { t: "steps", title: "Find the zeros of x² − 2x − 8 and verify the relationship with its coefficients.",
      intro: "Standard three marks: factorise, then check both relationships.",
      steps: [
        "Split the middle term: we need two numbers multiplying to −8 and adding to −2. Those are −4 and +2.",
        "x² − 4x + 2x − 8 = x(x − 4) + 2(x − 4) = (x − 4)(x + 2).",
        "Setting each factor to zero: <strong>α = 4, β = −2</strong>.",
        "Check the sum: α + β = 4 + (−2) = 2. And −b/a = −(−2)/1 = 2. ✓",
        "Check the product: αβ = 4 × (−2) = −8. And c/a = −8/1 = −8. ✓",
      ],
      answer: "Zeros are 4 and −2, and both relationships hold.",
    },

    { t: "steps", title: "Find a quadratic polynomial whose zeros sum to −3 and multiply to 2.",
      intro: "The reverse direction, and just as commonly asked.",
      steps: [
        "Use p(x) = k[x² − (sum)x + (product)].",
        "Substituting: p(x) = k[x² − (−3)x + 2].",
        "Simplify: p(x) = k[x² + 3x + 2].",
        "Take k = 1 for the simplest answer.",
      ],
      answer: "p(x) = x² + 3x + 2. (Any non-zero multiple of it is also correct.)",
    },

    { t: "h", text: "Questions that look harder than they are" },
    { t: "p", html: "A common four-mark type: given the zeros are α and β, find the value of an expression like α² + β² or 1/α + 1/β — <em>without</em> finding α and β. The trick is always to rewrite the expression in terms of the sum and product." },
    { t: "list", items: [
      "<strong>α² + β²</strong> = (α + β)² − 2αβ",
      "<strong>1/α + 1/β</strong> = (α + β)/αβ",
      "<strong>α − β</strong> = ±√[(α + β)² − 4αβ]",
      "<strong>α³ + β³</strong> = (α + β)³ − 3αβ(α + β)",
    ] },
    { t: "note", kind: "exam", html: "Memorise the first two. They cover most of what is set, and both follow from the identity (α + β)² = α² + 2αβ + β²." },

    { t: "steps", title: "If α and β are the zeros of x² − 5x + 6, find α² + β².",
      intro: "Notice you never need the actual zeros.",
      steps: [
        "From the coefficients: α + β = −(−5)/1 = 5, and αβ = 6/1 = 6.",
        "Use the identity α² + β² = (α + β)² − 2αβ.",
        "Substitute: (5)² − 2(6) = 25 − 12.",
      ],
      answer: "α² + β² = 13.",
    },
  ],
  formulas: [
    { name: "Sum of zeros", expr: "α + β = −b/a", note: "For ax² + bx + c. Note the minus sign." },
    { name: "Product of zeros", expr: "αβ = c/a" },
    { name: "Building from zeros", expr: "p(x) = k[x² − (α+β)x + αβ]", note: "k is any non-zero constant" },
    { name: "Useful identity", expr: "α² + β² = (α+β)² − 2αβ" },
    { name: "Useful identity", expr: "1/α + 1/β = (α+β)/αβ" },
  ],
  examFocus: [
    "Reading the number of zeros straight off a graph.",
    "α + β = −b/a and αβ = c/a — and getting the sign of the sum right.",
    "Finding zeros by splitting the middle term, then verifying both relationships.",
    "Constructing a quadratic from a given sum and product of zeros.",
    "Evaluating α² + β² and 1/α + 1/β without finding the zeros.",
  ],
  flashcards: [
    { q: "What is a zero of a polynomial?", a: "A value k such that p(k) = 0. On the graph, it is the x-coordinate of a point where the curve meets the x-axis." },
    { q: "How many zeros can a polynomial of degree n have?", a: "At most n. It may have fewer — a cubic can have only one real zero, and a quadratic can have none." },
    { q: "For ax² + bx + c with zeros α and β, what are the sum and product?", a: "α + β = −b/a and αβ = c/a." },
    { q: "Why is the sum of the zeros −b/a?", a: "Because p(x) = a(x−α)(x−β) = ax² − a(α+β)x + aαβ. Comparing coefficients of x gives b = −a(α+β), so α + β = −b/a." },
    { q: "How do you build a quadratic from its zeros?", a: "p(x) = k[x² − (sum of zeros)x + (product of zeros)], where k is any non-zero constant. Usually take k = 1." },
    { q: "Express α² + β² in terms of the sum and product of zeros.", a: "α² + β² = (α + β)² − 2αβ." },
    { q: "Express 1/α + 1/β in terms of the sum and product.", a: "1/α + 1/β = (α + β)/αβ." },
    { q: "How many times does the graph of a linear polynomial cross the x-axis?", a: "Exactly once, unless the line is horizontal. A linear polynomial has exactly one zero." },
    { q: "What does it mean when a parabola touches the x-axis at exactly one point?", a: "The quadratic has two equal zeros — a repeated root. Its discriminant is zero." },
    { q: "Find the zeros of x² − 3x − 10.", a: "Split the middle term: x² − 5x + 2x − 10 = x(x−5) + 2(x−5) = (x−5)(x+2). Zeros are 5 and −2. Check: sum = 3 = −(−3)/1, product = −10 = −10/1. ✓" },
    { q: "If the sum of zeros is 0, what can you say about the quadratic?", a: "−b/a = 0, so b = 0. The polynomial has the form ax² + c, and its graph is symmetric about the y-axis." },
    { q: "The graph of a polynomial cuts the x-axis at 3 points. What is the minimum possible degree?", a: "3. A polynomial needs degree at least 3 to have three zeros." },
  ],
  quiz: [
    { q: "If α and β are the zeros of 2x² − 5x + 3, then α + β equals:", options: ["5/2", "−5/2", "3/2", "−3/2"], answer: 0, why: "α + β = −b/a = −(−5)/2 = 5/2." },
    { q: "The product of the zeros of x² + 7x + 12 is:", options: ["−7", "7", "12", "−12"], answer: 2, why: "αβ = c/a = 12/1 = 12. (The zeros are −3 and −4, whose product is indeed 12.)" },
    { q: "A quadratic polynomial whose zeros are 2 and −5 is:", options: ["x² − 3x − 10", "x² + 3x − 10", "x² + 3x + 10", "x² − 3x + 10"], answer: 1, why: "Sum = 2 + (−5) = −3, product = −10. So p(x) = x² − (−3)x + (−10) = x² + 3x − 10." },
    { q: "The graph of a quadratic polynomial does not intersect the x-axis. The number of zeros is:", options: ["0", "1", "2", "cannot be determined"], answer: 0, why: "Zeros are exactly the points where the graph meets the x-axis. No intersection means no real zeros." },
    { q: "If one zero of x² − 4x + k is 3, then k is:", options: ["1", "3", "4", "12"], answer: 1, why: "Substitute x = 3: 9 − 12 + k = 0, so k = 3. (Alternatively the other zero is 1, and product = k = 3.)" },
    { q: "If α and β are the zeros of x² − 6x + 8, then α² + β² is:", options: ["20", "28", "36", "16"], answer: 0, why: "α + β = 6, αβ = 8. So α² + β² = 6² − 2(8) = 36 − 16 = 20." },
    { q: "The maximum number of zeros a cubic polynomial can have is:", options: ["1", "2", "3", "4"], answer: 2, why: "A polynomial of degree n has at most n zeros, so a cubic has at most three." },
    { q: "If the zeros of ax² + bx + c are equal in magnitude but opposite in sign, then:", options: ["a = 0", "b = 0", "c = 0", "a = c"], answer: 1, why: "Equal and opposite zeros sum to 0, so −b/a = 0, giving b = 0." },
    { q: "If α and β are the zeros of x² − 5x + 6, then 1/α + 1/β is:", options: ["5/6", "6/5", "−5/6", "1/6"], answer: 0, why: "1/α + 1/β = (α+β)/αβ = 5/6." },
    { q: "The zeros of x² − 2x are:", options: ["0 and 2", "0 and −2", "2 only", "1 and 2"], answer: 0, why: "x² − 2x = x(x − 2), so the zeros are 0 and 2." },
    { q: "The number of zeros shown by a graph that touches the x-axis at one point and does not cross it is:", options: ["0", "1", "2", "3"], answer: 1, why: "It meets the axis at exactly one point, so there is one zero — a repeated one." },
    { q: "If the product of the zeros of 3x² + 5x + k is 4, then k is:", options: ["4", "12", "−12", "3/4"], answer: 1, why: "αβ = c/a = k/3 = 4, so k = 12." },
  ],
  keyTopics: [
    { name: "Relationship between zeros and coefficients — α+β = −b/a, αβ = c/a", importance: "high", note: "The heart of the chapter; almost every question, worth 2–5 marks, reduces to this." },
    { name: "Finding a quadratic polynomial from a given sum and product of zeros", importance: "high", note: "The reverse-direction question, asked most years as a 2–3 marker." },
    { name: "Finding zeros by splitting the middle term and verifying the relationships", importance: "high", note: "The standard 2–3 mark question, especially with a ≠ 1." },
    { name: "Evaluating α²+β², 1/α+1/β, α³+β³ without finding the zeros", importance: "high", note: "The classic 'looks harder than it is' question, worth 3–5 marks." },
    { name: "Reading the number of zeros off a graph", importance: "medium", note: "Near-free marks once you know degree caps the count and a touch means a repeated zero." },
    { name: "Finding an unknown constant given one zero", importance: "medium", note: "Substitute the known zero into p(x) = 0 and solve." },
    { name: "Definitions — zero of a polynomial, degree, general forms", importance: "low", note: "Straightforward 1-mark recall." },
  ],
  written: [
    { q: "If one zero of the polynomial x² + 3x + k is 2, find the value of k.", marks: 1, kind: "numerical", importance: "high",
      answer: "Since x = 2 is a zero, it satisfies the polynomial: (2)² + 3(2) + k = 0.<br>4 + 6 + k = 0, so <strong>k = −10</strong>." },
    { q: "Write the number of zeros a quadratic polynomial has if its graph does not intersect the x-axis.", marks: 1, kind: "short", importance: "medium",
      answer: "<strong>Zero real zeros.</strong> A zero of a polynomial is the x-coordinate of a point where its graph meets the x-axis, so no intersection means no real zero." },
    { q: "Find the zeros of the quadratic polynomial 6x² − 7x − 3, and verify the relationship between the zeros and the coefficients.", marks: 2, kind: "numerical", importance: "high",
      answer: "Here a = 6, b = −7, c = −3, so ac = −18. Two numbers multiplying to −18 and adding to −7 are −9 and 2.<br>6x² − 9x + 2x − 3 = 3x(2x − 3) + 1(2x − 3) = (2x − 3)(3x + 1).<br>Zeros: <strong>α = 3/2, β = −1/3</strong>.<br>Check sum: 3/2 + (−1/3) = 7/6, and −b/a = 7/6. ✓ Check product: (3/2)(−1/3) = −1/2, and c/a = −3/6 = −1/2. ✓" },
    { q: "If α and β are the zeros of the quadratic polynomial 3x² + 5x − 2, find the value of 1/α + 1/β.", marks: 2, kind: "numerical", importance: "high",
      answer: "α + β = −b/a = −5/3, and αβ = c/a = −2/3.<br>1/α + 1/β = (α + β)/αβ = (−5/3) ÷ (−2/3) = <strong>5/2</strong>." },
    { q: "How many zeros does the graph of a quadratic polynomial show if it touches the x-axis at exactly one point, and if it cuts the x-axis at two distinct points?", marks: 2, kind: "short", importance: "medium",
      answer: "Touching at exactly one point: <strong>one zero</strong> (a repeated/equal zero). Cutting at two distinct points: <strong>two distinct zeros</strong>." },
    { q: "Find a quadratic polynomial whose zeros are (3 + √2) and (3 − √2).", marks: 3, kind: "numerical", importance: "high",
      answer: "Sum of zeros = (3+√2) + (3−√2) = <strong>6</strong>.<br>Product of zeros = (3+√2)(3−√2) = 3² − (√2)² = 9 − 2 = <strong>7</strong>.<br>Required polynomial: p(x) = k[x² − (sum)x + (product)] = <strong>x² − 6x + 7</strong> (taking k = 1)." },
    { q: "If the sum of the zeros of the quadratic polynomial kx² + 2x + 3k is equal to their product, find the value of k.", marks: 3, kind: "numerical", importance: "high",
      answer: "Sum of zeros = −b/a = −2/k. Product of zeros = c/a = 3k/k = 3.<br>Given sum = product: −2/k = 3, so <strong>k = −2/3</strong>." },
    { q: "Find the zeros of the quadratic polynomial 4x² − 4x + 1, and verify the relationship between the zeros and the coefficients.", marks: 3, kind: "numerical", importance: "medium",
      answer: "4x² − 4x + 1 = (2x − 1)², so the zeros are α = β = <strong>1/2</strong> (equal zeros).<br>Check sum: 1/2 + 1/2 = 1, and −b/a = 4/4 = 1. ✓ Check product: (1/2)(1/2) = 1/4, and c/a = 1/4. ✓" },
    { q: "Derive the relationship between the zeros and coefficients of a quadratic polynomial ax² + bx + c (a ≠ 0). Hence find a quadratic polynomial whose zeros are (2 + √3) and (2 − √3).", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Derivation:</strong> if α, β are the zeros, the polynomial factorises as a(x − α)(x − β) = a[x² − (α+β)x + αβ] = ax² − a(α+β)x + aαβ. Comparing with ax² + bx + c: −a(α+β) = b and aαβ = c, giving <strong>α + β = −b/a</strong> and <strong>αβ = c/a</strong>.<br><strong>Application:</strong> sum = (2+√3)+(2−√3) = 4. Product = (2+√3)(2−√3) = 4 − 3 = 1.<br>Required polynomial: <strong>x² − 4x + 1</strong>." },
    { q: "If α and β are the zeros of the polynomial x² − 2x − 15, find the value of α³ + β³.", marks: 5, kind: "numerical", importance: "high",
      answer: "α + β = −b/a = 2, and αβ = c/a = −15.<br>Use the identity α³ + β³ = (α+β)³ − 3αβ(α+β).<br>= (2)³ − 3(−15)(2) = 8 + 90 = <strong>98</strong>.<br>(Check directly: x²−2x−15 = (x−5)(x+3), zeros 5 and −3; 5³+(−3)³ = 125 − 27 = 98. ✓)" },
  ],
  assertionReason: [
    { assertion: "A quadratic polynomial can have at most 2 zeros.",
      reason: "The degree of a quadratic polynomial is 2, and a polynomial of degree n has at most n zeros.",
      answer: 0, importance: "high",
      why: "Both statements are true, and the degree-caps-zeros fact is exactly why a quadratic can have at most 2 zeros — R correctly explains A." },
    { assertion: "The quadratic polynomial x² − 5x + 6 has zeros 2 and 3.",
      reason: "The sum of the zeros of a quadratic polynomial ax² + bx + c is −b/a.",
      answer: 1, importance: "medium",
      why: "Both statements are true — substituting confirms 2 and 3 are the zeros, and the sum formula is correct. But the sum formula alone does not pin down the specific values 2 and 3 (you also need the product, or to factorise); R does not explain A." },
    { assertion: "If the graph of a quadratic polynomial touches the x-axis at exactly one point, the polynomial has two equal real zeros.",
      reason: "A quadratic polynomial always has two distinct real zeros.",
      answer: 2, importance: "high",
      why: "A is true — touching at one point means a repeated (equal) zero. R is false: a quadratic can have two distinct zeros, two equal zeros, or no real zeros at all." },
    { assertion: "The sum of the zeros of the polynomial 2x² − 8x + 6 is 8.",
      reason: "For a quadratic polynomial ax² + bx + c, the sum of the zeros equals −b/a.",
      answer: 3, importance: "medium",
      why: "A is false: the actual sum is −b/a = −(−8)/2 = 4 (the zeros are 1 and 3, and 1+3=4, not 8). R states the correct general formula, so R is true." },
  ],
  caseStudies: [
    { title: "The path of a thrown ball", importance: "high",
      source: "A ball is thrown into the air, and its height h(x) (in metres) after x seconds is modelled by the polynomial h(x) = −x² + 4x + 5.",
      parts: [
        { q: "Find the zeros of h(x), and explain what they represent for the ball's motion.", marks: 2, answer: "Set h(x) = 0: −x² + 4x + 5 = 0 ⟹ x² − 4x − 5 = 0 ⟹ (x−5)(x+1) = 0, so x = 5 or x = −1.<br>Since time cannot be negative, only <strong>x = 5</strong> is valid — the ball hits the ground after <strong>5 seconds</strong>." },
        { q: "Verify the sum and product of the zeros of h(x) using its coefficients.", marks: 2, answer: "With a = −1, b = 4, c = 5: sum = −b/a = −4/−1 = 4, and the actual zeros 5 and −1 sum to 4. ✓ Product = c/a = 5/−1 = −5, and 5 × (−1) = −5. ✓" },
        { q: "What is the maximum height reached by the ball?", marks: 1, answer: "The maximum occurs at x = −b/2a = −4/(2×−1) = 2 seconds. h(2) = −4 + 8 + 5 = <strong>9 metres</strong>." },
      ] },
  ],
};
