import type { Chapter } from "@/lib/types";

export const ch03: Chapter = {
  slug: "pair-of-linear-equations",
  num: 3,
  title: "Pair of Linear Equations in Two Variables",
  unit: "algebra",
  unitName: "Algebra",
  marks: "Unit II · 20 marks",
  minutes: 20,
  blurb: "Two lines on a page can meet once, never, or everywhere. That is the entire chapter — the algebra just tells you which without drawing.",
  bigIdea: "Solving a pair of equations means finding where two lines cross. If they never cross there is no solution; if they lie on top of each other there are infinitely many.",
  syllabus: [
    "Pair of linear equations in two variables",
    "Graphical solution and consistency / inconsistency",
    "Algebraic solutions: substitution and elimination",
    "Situational problems",
  ],
  blocks: [
    { t: "h", text: "Three pictures, three answers" },
    { t: "sim", id: "linear-pair" },
    { t: "p", html: "Every pair of linear equations falls into exactly one of three cases, and you can tell which from the coefficients alone — no graph needed." },
    { t: "table", head: ["Ratios", "Lines", "Solutions", "Called"], rows: [
      ["a₁/a₂ ≠ b₁/b₂", "Intersecting at one point", "Exactly one", "<strong>Consistent</strong>"],
      ["a₁/a₂ = b₁/b₂ = c₁/c₂", "Coincident (same line)", "Infinitely many", "<strong>Consistent</strong> (dependent)"],
      ["a₁/a₂ = b₁/b₂ ≠ c₁/c₂", "Parallel", "None", "<strong>Inconsistent</strong>"],
    ] },
    { t: "note", kind: "trap", html: "Both the first and second rows are <strong>consistent</strong>. Students often assume &ldquo;consistent&rdquo; means &ldquo;one solution&rdquo; — it does not. Consistent simply means at least one solution exists." },
    { t: "note", kind: "memory", html: "Write the equations in the form ax + by + c = 0 <em>before</em> comparing ratios. If one equation is 2x + 3y = 6 and the other 4x − y = 5, rewrite them as 2x + 3y − 6 = 0 and 4x − y − 5 = 0. Mixing up the arrangement is the usual source of error." },

    { t: "h", text: "Substitution method" },
    { t: "steps", title: "Solve: x + 2y = 6 and 3x − y = 4",
      intro: "Best when one variable already has coefficient 1, so isolating it is clean.",
      steps: [
        "From the first equation, make one variable the subject: <strong>x = 6 − 2y</strong>.",
        "Substitute into the second equation: 3(6 − 2y) − y = 4.",
        "Expand and solve: 18 − 6y − y = 4, so −7y = −14, giving <strong>y = 2</strong>.",
        "Put y back into x = 6 − 2y: x = 6 − 4 = <strong>2</strong>.",
        "Check in the equation you did <em>not</em> use for substitution: 3(2) − 2 = 4. ✓",
      ],
      answer: "x = 2, y = 2.",
    },

    { t: "h", text: "Elimination method" },
    { t: "steps", title: "Solve: 2x + 3y = 11 and 2x − 4y = −24",
      intro: "Best when a variable already has matching or easily-matched coefficients.",
      steps: [
        "The coefficients of x are already the same (both 2), so subtract the second equation from the first.",
        "(2x + 3y) − (2x − 4y) = 11 − (−24), which gives 7y = 35.",
        "So <strong>y = 5</strong>.",
        "Substitute into the first equation: 2x + 15 = 11, so 2x = −4 and <strong>x = −2</strong>.",
      ],
      answer: "x = −2, y = 5.",
    },
    { t: "note", kind: "exam", html: "If the coefficients do not match, multiply one or both equations first. To solve 3x + 4y = 10 and 2x + 3y = 7, multiply the first by 2 and the second by 3 to make the x-coefficients both 6, then subtract." },

    { t: "h", text: "Word problems — the part worth the most marks" },
    { t: "p", html: "The mathematics is easy; the marks go on setting up the two equations correctly. The pattern is always the same: name the two unknowns, then turn each sentence into one equation." },
    { t: "steps", title: "The sum of the digits of a two-digit number is 9. If 27 is added to the number, the digits reverse. Find the number.",
      intro: "Two-digit number problems come up almost every year. Set them up the same way each time.",
      steps: [
        "Let the tens digit be x and the units digit be y. Then the <strong>number is 10x + y</strong>, and the reversed number is 10y + x.",
        "&ldquo;Sum of the digits is 9&rdquo; gives the first equation: <strong>x + y = 9</strong>.",
        "&ldquo;Adding 27 reverses the digits&rdquo; gives: (10x + y) + 27 = 10y + x.",
        "Simplify: 9x − 9y = −27, so <strong>x − y = −3</strong>.",
        "Add the two equations: 2x = 6, so x = 3, and then y = 6.",
      ],
      answer: "The number is 10(3) + 6 = 36. (Check: 36 + 27 = 63, digits reversed. ✓)",
    },
    { t: "list", items: [
      "<strong>Two-digit number</strong> with tens digit x and units digit y is <strong>10x + y</strong>, never xy.",
      "<strong>Age problems</strong> — write present ages as x and y, then &ldquo;five years ago&rdquo; is x − 5 and y − 5.",
      "<strong>Speed problems</strong> — upstream speed is (boat − stream), downstream is (boat + stream). Use time = distance ÷ speed.",
      "<strong>Fraction problems</strong> — let the fraction be x/y and form one equation per condition.",
      "<strong>Work problems</strong> — if A finishes in x days, A does 1/x of the work per day.",
    ] },
    { t: "note", kind: "real", html: "The boat-and-stream setup is worth internalising: rowing with the current you go faster, against it slower. If the boat does b km/h in still water and the stream flows at s km/h, downstream speed is b + s and upstream is b − s." },

    { t: "h", text: "Finding k so that a pair behaves in a particular way" },
    { t: "steps", title: "For what value of k does 2x + 3y = 7 and (k−1)x + (k+2)y = 3k have infinitely many solutions?",
      intro: "Infinitely many solutions means all three ratios are equal — that gives you equations in k.",
      steps: [
        "Write both in the standard form and identify: a₁=2, b₁=3, c₁=7 and a₂=k−1, b₂=k+2, c₂=3k.",
        "For infinitely many solutions we need a₁/a₂ = b₁/b₂ = c₁/c₂.",
        "From the first two: 2/(k−1) = 3/(k+2), so 2(k+2) = 3(k−1), giving 2k + 4 = 3k − 3 and <strong>k = 7</strong>.",
        "Verify with the third ratio: 7/(3k) = 7/21 = 1/3, and 2/(k−1) = 2/6 = 1/3. ✓",
      ],
      answer: "k = 7.",
    },
    { t: "note", kind: "trap", html: "For <strong>no solution</strong> the condition is a₁/a₂ = b₁/b₂ <em>but</em> c₁/c₂ different. Students often solve the first part and forget to check that the third ratio genuinely differs — which is where the mark is." },
  ],
  formulas: [
    { name: "Unique solution", expr: "a₁/a₂ ≠ b₁/b₂", note: "Lines intersect — consistent" },
    { name: "Infinitely many solutions", expr: "a₁/a₂ = b₁/b₂ = c₁/c₂", note: "Coincident lines — consistent, dependent" },
    { name: "No solution", expr: "a₁/a₂ = b₁/b₂ ≠ c₁/c₂", note: "Parallel lines — inconsistent" },
    { name: "Two-digit number", expr: "10 × (tens digit) + (units digit)" },
  ],
  examFocus: [
    "The three ratio conditions, and knowing that two of the three cases are 'consistent'.",
    "Substitution and elimination — be able to choose the easier one for a given pair.",
    "Setting up word problems: two-digit numbers, ages, boats and streams, fractions.",
    "Finding k for infinitely many or no solutions, remembering to check the third ratio.",
    "Always verifying the answer in the equation you did not use to substitute.",
  ],
  flashcards: [
    { q: "When does a pair of linear equations have a unique solution?", a: "When a₁/a₂ ≠ b₁/b₂. The lines intersect at exactly one point and the pair is consistent." },
    { q: "When does a pair have infinitely many solutions?", a: "When a₁/a₂ = b₁/b₂ = c₁/c₂. The lines are coincident — the same line written two ways. The pair is consistent and dependent." },
    { q: "When does a pair have no solution?", a: "When a₁/a₂ = b₁/b₂ but ≠ c₁/c₂. The lines are parallel and never meet; the pair is inconsistent." },
    { q: "Does 'consistent' mean exactly one solution?", a: "No. Consistent means at least one solution exists, so it covers both the unique-solution case and the infinitely-many case." },
    { q: "Describe the substitution method.", a: "Make one variable the subject in one equation, substitute that expression into the other equation to get a single-variable equation, solve it, then back-substitute." },
    { q: "Describe the elimination method.", a: "Multiply the equations so that one variable has equal coefficients, then add or subtract to eliminate it, solve for the remaining variable, and back-substitute." },
    { q: "How do you represent a two-digit number algebraically?", a: "If the tens digit is x and the units digit is y, the number is 10x + y. Reversing the digits gives 10y + x." },
    { q: "In a boat-and-stream problem, what are the upstream and downstream speeds?", a: "If the boat does b km/h in still water and the stream flows at s km/h, downstream speed is b + s and upstream speed is b − s." },
    { q: "If A alone finishes a job in x days, how much work does A do per day?", a: "1/x of the job. Work problems are set up by adding the per-day fractions." },
    { q: "Graphically, what does the solution of a pair of linear equations represent?", a: "The point of intersection of the two straight lines — its coordinates are the values of x and y that satisfy both equations." },
    { q: "For what condition are the lines a₁x+b₁y+c₁=0 and a₂x+b₂y+c₂=0 parallel?", a: "a₁/a₂ = b₁/b₂ ≠ c₁/c₂. Equal slopes but different intercepts." },
    { q: "Solve x + y = 5 and x − y = 1 by elimination.", a: "Adding: 2x = 6 so x = 3. Substituting: 3 + y = 5 so y = 2. Solution (3, 2)." },
  ],
  quiz: [
    { q: "The pair 2x + 3y = 7 and 4x + 6y = 14 has:", options: ["A unique solution", "No solution", "Infinitely many solutions", "Exactly two solutions"], answer: 2, why: "2/4 = 3/6 = 7/14 = 1/2, so all three ratios are equal — the lines are coincident and there are infinitely many solutions." },
    { q: "The pair x + 2y = 3 and 2x + 4y = 9 is:", options: ["Consistent with one solution", "Inconsistent", "Consistent with infinite solutions", "Dependent"], answer: 1, why: "1/2 = 2/4 but 3/9 = 1/3 is different. Equal first two ratios with a different third means parallel lines and no solution — inconsistent." },
    { q: "Two lines are coincident. The number of solutions is:", options: ["0", "1", "2", "Infinitely many"], answer: 3, why: "Coincident lines lie exactly on top of each other, so every point on the line satisfies both equations." },
    { q: "Solving x + y = 14 and x − y = 4 gives:", options: ["x = 9, y = 5", "x = 5, y = 9", "x = 10, y = 4", "x = 4, y = 10"], answer: 0, why: "Adding: 2x = 18, so x = 9. Then 9 + y = 14 gives y = 5." },
    { q: "A two-digit number with tens digit x and units digit y is written as:", options: ["xy", "x + y", "10x + y", "10y + x"], answer: 2, why: "The tens digit is worth ten times its face value, so the number is 10x + y." },
    { q: "For what value of k do kx + 2y = 5 and 3x + y = 1 have a unique solution?", options: ["k = 6", "k ≠ 6", "k = 3", "k ≠ 3"], answer: 1, why: "A unique solution needs a₁/a₂ ≠ b₁/b₂, i.e. k/3 ≠ 2/1, so k ≠ 6. Any other value works." },
    { q: "A boat goes 8 km/h in still water and the stream flows at 2 km/h. Its upstream speed is:", options: ["10 km/h", "6 km/h", "8 km/h", "4 km/h"], answer: 1, why: "Upstream means against the current: 8 − 2 = 6 km/h." },
    { q: "The lines representing an inconsistent pair are:", options: ["Intersecting", "Parallel", "Coincident", "Perpendicular"], answer: 1, why: "Inconsistent means no solution, which graphically means the lines never meet — they are parallel." },
    { q: "If the sum of two numbers is 20 and their difference is 4, the larger number is:", options: ["8", "12", "16", "10"], answer: 1, why: "x + y = 20 and x − y = 4. Adding gives 2x = 24, so x = 12." },
    { q: "The condition for the pair a₁x+b₁y+c₁=0, a₂x+b₂y+c₂=0 to have infinitely many solutions is:", options: ["a₁/a₂ ≠ b₁/b₂", "a₁/a₂ = b₁/b₂ ≠ c₁/c₂", "a₁/a₂ = b₁/b₂ = c₁/c₂", "a₁b₂ − a₂b₁ ≠ 0"], answer: 2, why: "All three ratios must be equal, meaning the two equations are multiples of each other." },
    { q: "Five years ago a father was seven times as old as his son. The correct way to write the father's age five years ago, if his present age is x, is:", options: ["x + 5", "x − 5", "5x", "7x"], answer: 1, why: "Five years ago everyone was five years younger, so the father's age then was x − 5." },
    { q: "The graph of x = 4 is:", options: ["A line parallel to the x-axis", "A line parallel to the y-axis", "The x-axis itself", "A line through the origin"], answer: 1, why: "x = 4 fixes x while y takes every value, giving a vertical line — parallel to the y-axis." },
  ],
};
