import type { Chapter } from "@/lib/types";

export const ch04: Chapter = {
  slug: "quadratic-equations",
  num: 4,
  title: "Quadratic Equations",
  unit: "algebra",
  unitName: "Algebra",
  marks: "Unit II · 20 marks",
  minutes: 18,
  blurb: "One number — the discriminant — tells you how many solutions exist before you find any of them.",
  bigIdea: "b² − 4ac decides everything. Positive means two roots, zero means one repeated root, negative means none at all.",
  syllabus: [
    "Standard form ax² + bx + c = 0, a ≠ 0",
    "Solutions by factorisation and by the quadratic formula",
    "Relationship between discriminant and nature of roots",
    "Situational problems based on quadratic equations",
  ],
  blocks: [
    { t: "h", text: "Standard form" },
    { t: "formula", name: "Quadratic equation", expr: "ax² + bx + c = 0, &nbsp;where a ≠ 0",
      where: ["If a = 0 the x² term vanishes and it is no longer quadratic"] },
    { t: "note", kind: "trap", html: "Always rearrange into standard form <strong>before</strong> doing anything else. An equation like x(x + 3) = 10 is not ready — expand and move everything to one side to get x² + 3x − 10 = 0." },

    { t: "h", text: "Method 1 — factorisation by splitting the middle term" },
    { t: "p", html: "Find two numbers that <strong>multiply to ac</strong> and <strong>add to b</strong>. Split the middle term using them, then group." },
    { t: "steps", title: "Solve 2x² − 5x + 3 = 0 by factorisation.",
      intro: "The a ≠ 1 case, which is where students slip.",
      steps: [
        "Here a = 2, b = −5, c = 3, so ac = 6. We need two numbers multiplying to 6 and adding to −5: those are −2 and −3.",
        "Split the middle term: 2x² − 2x − 3x + 3 = 0.",
        "Group in pairs: 2x(x − 1) − 3(x − 1) = 0.",
        "Factor out the common bracket: (x − 1)(2x − 3) = 0.",
        "Set each factor to zero: x − 1 = 0 or 2x − 3 = 0.",
      ],
      answer: "x = 1 or x = 3/2.",
    },
    { t: "note", kind: "memory", html: "Multiply to <strong>ac</strong>, add to <strong>b</strong>. When a = 1 that is just &ldquo;multiply to c, add to b&rdquo;, which is why easy examples feel different." },

    { t: "h", text: "Method 2 — the quadratic formula" },
    { t: "formula", name: "Quadratic formula", expr: "x = [ −b ± √(b² − 4ac) ] / 2a",
      where: ["Works for every quadratic, including ones that do not factorise neatly", "The expression under the root is the discriminant, D"] },
    { t: "note", kind: "exam", html: "Use factorisation if the numbers are friendly and the formula otherwise. If a question says &ldquo;solve by the quadratic formula&rdquo;, you must use the formula even if it factorises — the method is what is being marked." },

    { t: "h", text: "The discriminant" },
    { t: "sim", id: "quadratic-roots" },
    { t: "formula", name: "Discriminant", expr: "D = b² − 4ac" },
    { t: "table", head: ["Discriminant", "Nature of roots", "What the graph does"], rows: [
      ["D &gt; 0", "Two distinct real roots", "Parabola cuts the x-axis at two points"],
      ["D = 0", "Two equal real roots (a repeated root)", "Parabola just touches the x-axis"],
      ["D &lt; 0", "No real roots", "Parabola never meets the x-axis"],
    ] },
    { t: "note", kind: "trap", html: "&ldquo;D = 0&rdquo; means the roots are <strong>real and equal</strong> — not &ldquo;one root&rdquo;. There are still two roots; they simply happen to be the same number, both equal to −b/2a. Write it as &ldquo;real and equal&rdquo; to be safe." },

    { t: "steps", title: "Find k so that 2x² + kx + 3 = 0 has two equal roots.",
      intro: "The single most predictable question in this chapter.",
      steps: [
        "Equal roots means <strong>D = 0</strong>, that is b² − 4ac = 0.",
        "Here a = 2, b = k, c = 3, so k² − 4(2)(3) = 0.",
        "That gives k² − 24 = 0, so k² = 24.",
        "Taking square roots: k = ±√24 = ±2√6.",
      ],
      answer: "k = 2√6 or k = −2√6.",
    },

    { t: "h", text: "Word problems" },
    { t: "p", html: "The setup matters more than the solving. Three patterns cover most of what is set." },
    { t: "list", items: [
      "<strong>Speed and time.</strong> time = distance ÷ speed. If speed increases by 5 km/h, the new speed is (x + 5) and the new time is distance/(x + 5). The condition usually says the journey took some hours less.",
      "<strong>Age.</strong> Products of ages give quadratics — 'the product of Rehman's ages three years ago and five years from now is 30'.",
      "<strong>Area and dimensions.</strong> A rectangular field where the length is 3 more than twice the breadth, and the area is known.",
      "<strong>Two pipes / two workers.</strong> If one takes x hours and the other x + 10, their rates 1/x and 1/(x+10) add to the combined rate.",
    ] },
    { t: "steps", title: "A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less. Find the speed.",
      intro: "The archetypal speed–time problem. Set up the time difference and clear denominators.",
      steps: [
        "Let the original speed be x km/h. Original time = 360/x hours.",
        "New speed = (x + 5), new time = 360/(x + 5) hours.",
        "The new journey is one hour shorter: <strong>360/x − 360/(x+5) = 1</strong>.",
        "Multiply through by x(x + 5): 360(x + 5) − 360x = x(x + 5).",
        "Simplify: 1800 = x² + 5x, so x² + 5x − 1800 = 0.",
        "Factorise: we need two numbers multiplying to −1800 and adding to 5 — that is 45 and −40. So (x + 45)(x − 40) = 0.",
      ],
      answer: "x = 40 or x = −45. Speed cannot be negative, so the speed is 40 km/h.",
    },
    { t: "note", kind: "exam", html: "Always finish by <strong>rejecting the impossible root</strong> and saying why. Speeds, ages, lengths and numbers of people cannot be negative. That sentence carries a mark." },
    { t: "note", kind: "why", title: "Why does a quadratic have at most two roots?", html: "Because if it had three, the polynomial a(x−p)(x−q)(x−r) would have degree 3 — but our polynomial has degree 2. Degree caps the number of roots, which is the same fact you met in the Polynomials chapter." },
  ],
  formulas: [
    { name: "Standard form", expr: "ax² + bx + c = 0, a ≠ 0" },
    { name: "Quadratic formula", expr: "x = [−b ± √(b² − 4ac)] / 2a" },
    { name: "Discriminant", expr: "D = b² − 4ac", note: "D > 0 distinct real · D = 0 real and equal · D < 0 no real roots" },
    { name: "Equal roots", expr: "both roots = −b/2a when D = 0" },
    { name: "Sum and product of roots", expr: "α + β = −b/a, αβ = c/a", note: "Same as for polynomials" },
  ],
  examFocus: [
    "Rearranging into standard form before doing anything else.",
    "Splitting the middle term using 'multiply to ac, add to b'.",
    "The quadratic formula written correctly, including the 2a in the denominator.",
    "The three discriminant cases, with 'real and equal' rather than 'one root'.",
    "Finding k for equal roots by setting D = 0.",
    "Setting up speed–time and area word problems, and rejecting the negative root with a reason.",
  ],
  flashcards: [
    { q: "What is the standard form of a quadratic equation?", a: "ax² + bx + c = 0, where a, b, c are real numbers and a ≠ 0. If a were 0 it would not be quadratic." },
    { q: "State the quadratic formula.", a: "x = [−b ± √(b² − 4ac)] / 2a." },
    { q: "What is the discriminant and what does it tell you?", a: "D = b² − 4ac. If D > 0 the roots are real and distinct; if D = 0 they are real and equal; if D < 0 there are no real roots." },
    { q: "How do you split the middle term?", a: "Find two numbers whose product is ac and whose sum is b, split bx into those two terms, then factorise by grouping." },
    { q: "If D = 0, what are the roots?", a: "Both roots are equal to −b/2a. They are described as real and equal, not as 'one root'." },
    { q: "How do you find k so that a quadratic has equal roots?", a: "Set the discriminant to zero: b² − 4ac = 0, then solve the resulting equation for k." },
    { q: "For ax² + bx + c = 0, what are the sum and product of the roots?", a: "Sum = −b/a and product = c/a — the same relationships as for a quadratic polynomial." },
    { q: "Solve x² − 5x + 6 = 0 by factorisation.", a: "Two numbers multiplying to 6 and adding to −5 are −2 and −3. So x² − 2x − 3x + 6 = x(x−2) − 3(x−2) = (x−2)(x−3) = 0, giving x = 2 or x = 3." },
    { q: "In a word problem, why must you reject a negative root?", a: "Because quantities like speed, age, length and number of items cannot be negative. You must state the rejection and the reason to get full marks." },
    { q: "How do you set up a 'speed increased by k' problem?", a: "Let the speed be x. Original time = distance/x, new time = distance/(x+k). Form an equation from the stated time difference, then clear the denominators." },
    { q: "If two pipes fill a tank in x and x+10 hours, what is their combined rate?", a: "1/x + 1/(x+10) of the tank per hour. Set this equal to 1 divided by the combined time given in the question." },
    { q: "Why can a quadratic equation have at most two roots?", a: "Because the degree of a polynomial caps the number of its roots. A degree-2 polynomial cannot have three distinct factors of the form (x − r)." },
  ],
  quiz: [
    { q: "The discriminant of 2x² − 4x + 3 = 0 is:", options: ["−8", "8", "40", "−40"], answer: 0, why: "D = b² − 4ac = (−4)² − 4(2)(3) = 16 − 24 = −8. Negative, so there are no real roots." },
    { q: "The equation x² + 4x + 4 = 0 has:", options: ["Two distinct real roots", "Two equal real roots", "No real roots", "Three roots"], answer: 1, why: "D = 16 − 16 = 0, so the roots are real and equal. Both are −b/2a = −2." },
    { q: "The roots of x² − 7x + 12 = 0 are:", options: ["3 and 4", "−3 and −4", "2 and 6", "1 and 12"], answer: 0, why: "Two numbers multiplying to 12 and adding to −7 are −3 and −4, giving (x−3)(x−4) = 0." },
    { q: "For what value of k does x² + kx + 9 = 0 have equal roots?", options: ["k = 3", "k = ±6", "k = 9", "k = ±3"], answer: 1, why: "Equal roots means D = 0: k² − 4(1)(9) = 0, so k² = 36 and k = ±6." },
    { q: "Which of these is NOT a quadratic equation?", options: ["x² + 1 = 0", "x(x+1) = 5", "2x + 3 = 0", "(x−1)² = 0"], answer: 2, why: "2x + 3 = 0 has no x² term, so it is linear. All the others reduce to a form with x² and a ≠ 0." },
    { q: "If one root of x² − 6x + k = 0 is 2, then k is:", options: ["4", "8", "12", "6"], answer: 1, why: "Substitute x = 2: 4 − 12 + k = 0, so k = 8. (The other root is then 4, and 2 × 4 = 8 = c/a. ✓)" },
    { q: "The sum of the roots of 3x² − 12x + 7 = 0 is:", options: ["4", "−4", "7/3", "12"], answer: 0, why: "Sum = −b/a = −(−12)/3 = 4." },
    { q: "A quadratic equation has no real roots when:", options: ["b² − 4ac > 0", "b² − 4ac = 0", "b² − 4ac < 0", "a = 0"], answer: 2, why: "A negative discriminant means the square root in the formula is not a real number, so the parabola never touches the x-axis." },
    { q: "The product of two consecutive positive integers is 306. The equation modelling this is:", options: ["x² + x − 306 = 0", "x² − x − 306 = 0", "x² + 306 = 0", "2x + 1 = 306"], answer: 0, why: "Let the integers be x and x + 1. Then x(x+1) = 306, so x² + x − 306 = 0. (x = 17, giving 17 and 18.)" },
    { q: "If the roots of a quadratic are 3 and −5, the equation is:", options: ["x² + 2x − 15 = 0", "x² − 2x − 15 = 0", "x² + 2x + 15 = 0", "x² − 2x + 15 = 0"], answer: 0, why: "Sum = −2, product = −15. So x² − (sum)x + product = x² + 2x − 15 = 0." },
    { q: "In the equation x² + 3x − 10 = 0, splitting the middle term uses the numbers:", options: ["5 and −2", "−5 and 2", "5 and 2", "−5 and −2"], answer: 0, why: "We need two numbers multiplying to ac = −10 and adding to b = 3. Those are 5 and −2." },
    { q: "A rectangular plot has area 528 m² and its length is one more than twice its breadth. If the breadth is x, the equation is:", options: ["2x² + x − 528 = 0", "x² + 2x − 528 = 0", "2x² − x − 528 = 0", "x² − 528 = 0"], answer: 0, why: "Length = 2x + 1, so area = x(2x + 1) = 528, giving 2x² + x − 528 = 0." },
  ],
  keyTopics: [
    { name: "Discriminant and nature of roots (D > 0, D = 0, D < 0)", importance: "high", note: "One of the most heavily tested ideas in Class X algebra — appears as MCQ, short answer, and inside word problems." },
    { name: "Finding an unknown k for equal (real and repeated) roots", importance: "high", note: "Set D = 0 and solve — the single most predictable question type in the chapter." },
    { name: "Solving by factorisation — splitting the middle term", importance: "high", note: "'Multiply to ac, add to b'; the go-to method whenever the numbers are friendly." },
    { name: "The quadratic formula", importance: "high", note: "Needed whenever a question specifies the method, or when the equation does not factorise neatly." },
    { name: "Word problems — speed/time, age, area, work and pipes", importance: "high", note: "Usually the 5-mark question; the equation-setting is what earns the marks, not the solving." },
    { name: "Rejecting the invalid (negative) root with a reason", importance: "medium", note: "A one-line habit that carries a dedicated mark in every word problem." },
    { name: "Standard form and rearranging before solving", importance: "medium", note: "Move everything to one side and confirm a ≠ 0 before applying any method." },
  ],
  written: [
    { q: "Write the discriminant of the quadratic equation x² − 4x + 4 = 0.", marks: 1, kind: "numerical", importance: "medium",
      answer: "D = b² − 4ac = (−4)² − 4(1)(4) = 16 − 16 = <strong>0</strong>." },
    { q: "Write the standard form of a quadratic equation and state the condition on the coefficient 'a'.", marks: 1, kind: "short", importance: "medium",
      answer: "Standard form: <strong>ax² + bx + c = 0</strong>, where a, b, c are real numbers and <strong>a ≠ 0</strong> (if a = 0, the x² term vanishes and the equation is no longer quadratic)." },
    { q: "Find the roots of the quadratic equation x² + 2x − 15 = 0 by factorisation.", marks: 2, kind: "numerical", importance: "high",
      answer: "We need two numbers multiplying to −15 and adding to 2: those are 5 and −3.<br>x² + 5x − 3x − 15 = x(x+5) − 3(x+5) = (x+5)(x−3) = 0.<br>So x = −5 or x = 3. <strong>Roots: x = 3, −5.</strong>" },
    { q: "Find the discriminant of 2x² − 6x + 3 = 0 and hence write the nature of its roots.", marks: 2, kind: "numerical", importance: "high",
      answer: "D = b² − 4ac = (−6)² − 4(2)(3) = 36 − 24 = <strong>12</strong>.<br>Since D &gt; 0, the equation has <strong>two distinct real roots</strong>." },
    { q: "Find the value of k for which the quadratic equation kx(x − 2) + 6 = 0 has two equal roots.", marks: 3, kind: "numerical", importance: "high", years: "2019",
      answer: "Expand: kx² − 2kx + 6 = 0, so a = k, b = −2k, c = 6.<br>Equal roots means D = 0: (−2k)² − 4(k)(6) = 0 ⟹ 4k² − 24k = 0 ⟹ 4k(k − 6) = 0.<br>So k = 0 or k = 6. Since k = 0 would make the equation linear (not quadratic), it is rejected.<br><strong>k = 6.</strong>" },
    { q: "Solve for x using the quadratic formula: 4x² − 4√3 x + 3 = 0.", marks: 3, kind: "numerical", importance: "high",
      answer: "Here a = 4, b = −4√3, c = 3.<br>D = b² − 4ac = 48 − 48 = <strong>0</strong>, so the roots are real and equal.<br>x = −b/2a = 4√3/8 = <strong>√3/2</strong> (repeated root)." },
    { q: "The sum of the squares of two consecutive positive integers is 313. Find the integers.", marks: 3, kind: "numerical", importance: "high",
      answer: "Let the integers be x and x+1.<br>x² + (x+1)² = 313 ⟹ 2x² + 2x + 1 = 313 ⟹ 2x² + 2x − 312 = 0 ⟹ <strong>x² + x − 156 = 0</strong>.<br>Two numbers multiplying to −156 and adding to 1 are 13 and −12: (x+13)(x−12) = 0.<br>So x = 12 or x = −13 (rejected, as the integers must be positive).<br>The integers are <strong>12 and 13</strong>. (Check: 144 + 169 = 313 ✓)" },
    { q: "A motor boat whose speed is 18 km/h in still water takes 1 hour more to go 24 km upstream than to return downstream to the same spot. Find the speed of the stream.", marks: 5, kind: "numerical", importance: "high", years: "2016, Delhi 2017",
      answer: "Let the speed of the stream be x km/h. Upstream speed = (18−x), downstream speed = (18+x).<br>Time upstream − time downstream = 1: 24/(18−x) − 24/(18+x) = 1.<br>24[(18+x) − (18−x)] = (18−x)(18+x) ⟹ 24(2x) = 324 − x² ⟹ 48x = 324 − x².<br>Rearranging: <strong>x² + 48x − 324 = 0</strong>.<br>D = 48² + 4(324) = 2304 + 1296 = 3600, √D = 60.<br>x = (−48 ± 60)/2, giving x = 6 or x = −54 (rejected, speed cannot be negative).<br>Speed of the stream = <strong>6 km/h</strong>." },
    { q: "Two water taps together can fill a tank in 9<sup>3</sup>⁄<sub>8</sub> hours. The tap of larger diameter takes 10 hours less than the smaller one to fill the tank separately. Find the time in which each tap can separately fill the tank.", marks: 5, kind: "numerical", importance: "high", years: "2020",
      answer: "9³⁄₈ hours = 75/8 hours, so the combined rate is 8/75 of the tank per hour.<br>Let the smaller tap take x hours alone; the larger tap then takes (x−10) hours.<br>1/x + 1/(x−10) = 8/75.<br>Multiply through by 75x(x−10): 75(x−10) + 75x = 8x(x−10) ⟹ 75(2x−10) = 8x² − 80x ⟹ 150x − 750 = 8x² − 80x.<br>Rearranging: 8x² − 230x + 750 = 0, or <strong>4x² − 115x + 375 = 0</strong>.<br>D = 115² − 4(4)(375) = 13225 − 6000 = 7225, √D = 85.<br>x = (115 ± 85)/8, giving x = 25 or x = 3.75 (rejected, since x − 10 would be negative).<br>Smaller tap takes <strong>25 hours</strong>; larger tap takes 25 − 10 = <strong>15 hours</strong>." },
  ],
  assertionReason: [
    { assertion: "The quadratic equation 2x² + x − 1 = 0 has two distinct real roots.",
      reason: "For the equation 2x² + x − 1 = 0, the discriminant is positive.",
      answer: 0, importance: "high",
      why: "D = 1² − 4(2)(−1) = 1 + 8 = 9 > 0. Both statements are true, and a positive discriminant is exactly what gives two distinct real roots — R correctly explains A." },
    { assertion: "x = 3 is a root of the quadratic equation x² − 5x + 6 = 0.",
      reason: "The sum of the roots of x² − 5x + 6 = 0 is 5.",
      answer: 1, importance: "medium",
      why: "Both are true: substituting x=3 gives 9−15+6=0, and −b/a = 5. But knowing the sum of the roots is 5 does not by itself explain why x=3 in particular is a root — R does not explain A." },
    { assertion: "The equation x² + 4 = 0 has no real roots.",
      reason: "Every quadratic equation with a positive constant term c has no real roots.",
      answer: 2, importance: "high",
      why: "A is true: D = 0 − 16 = −16 < 0. R is false — for example x² − 5x + 6 = 0 has a positive constant term (c=6) but has two real roots, 2 and 3." },
    { assertion: "The equation 3x² − 6x + 3 = 0 has two distinct real roots.",
      reason: "A quadratic equation ax² + bx + c = 0 has equal roots when b² = 4ac.",
      answer: 3, importance: "medium",
      why: "A is false: dividing through by 3 gives x² − 2x + 1 = (x−1)² = 0, so D = 36 − 36 = 0 — the roots are real and equal, not distinct. R states a correct general condition, so R is true." },
  ],
  caseStudies: [
    { title: "Designing a rectangular park next to a triangular garden", importance: "high", years: "2019",
      source: "A community wants to design a rectangular park whose breadth is 3 m less than its length. Its area must be 4 m² more than the area of an isosceles triangular garden already built alongside, which has base equal to the park's breadth and height 12 m.",
      parts: [
        { q: "Taking the breadth of the rectangular park as x metres, form a quadratic equation using the given information.", marks: 2, answer: "Length = x + 3 (since breadth is 3 m less than length). Area of rectangle = x(x+3).<br>Area of triangle = (1/2) × base × height = (1/2)(x)(12) = 6x.<br>Given: rectangle's area = triangle's area + 4: x(x+3) = 6x + 4 ⟹ x² + 3x = 6x + 4 ⟹ <strong>x² − 3x − 4 = 0</strong>." },
        { q: "Solve the equation to find the breadth and length of the rectangular park.", marks: 2, answer: "x² − 3x − 4 = 0 ⟹ (x−4)(x+1) = 0, so x = 4 or x = −1 (rejected, breadth cannot be negative).<br>Breadth = <strong>4 m</strong>, Length = 4 + 3 = <strong>7 m</strong>." },
        { q: "Find the area of the rectangular park.", marks: 1, answer: "Area = length × breadth = 7 × 4 = <strong>28 m²</strong>. (Check: triangle's area = 6×4 = 24 m², and 24 + 4 = 28. ✓)" },
      ] },
  ],
};
