import type { Chapter } from "@/lib/types";

export const ch05: Chapter = {
  slug: "arithmetic-progressions",
  num: 5,
  title: "Arithmetic Progressions",
  unit: "algebra",
  unitName: "Algebra",
  marks: "Unit II · 20 marks",
  minutes: 16,
  blurb: "Start somewhere, add the same amount each time. Two formulas then answer every question in the chapter.",
  bigIdea: "An AP is the simplest possible pattern — a constant step. Because the step never changes, you can jump straight to the hundredth term without listing the first ninety-nine.",
  syllabus: [
    "Motivation for studying Arithmetic Progression",
    "Derivation of the nth term",
    "Derivation of the sum of the first n terms",
    "Applications in solving daily-life problems",
  ],
  blocks: [
    { t: "h", text: "What makes a sequence an AP" },
    { t: "p", html: "A sequence is an arithmetic progression if the difference between any term and the one before it is always the same. That fixed difference is <strong>d</strong>, the common difference." },
    { t: "formula", name: "Common difference", expr: "d = a₂ − a₁ = a₃ − a₂ = … = a<sub>k+1</sub> − a<sub>k</sub>",
      where: ["d can be positive, negative or zero", "If d is not the same throughout, the sequence is not an AP"] },
    { t: "sim", id: "ap-explorer" },
    { t: "note", kind: "trap", html: "To check whether a sequence is an AP you must test <strong>at least two</strong> differences. 1, 4, 7, 11 fails: 4−1 = 3 but 11−7 = 4. Checking only the first pair is a classic slip." },
    { t: "note", kind: "real", html: "APs are everywhere once you notice: a taxi fare that starts at ₹50 and adds ₹15 per km; savings that grow by a fixed amount each month; the number of seats in each row of an auditorium; a ladder whose rungs shorten by a constant amount." },

    { t: "h", text: "The nth term" },
    { t: "formula", name: "nth term of an AP", expr: "a<sub>n</sub> = a + (n − 1)d",
      where: ["a = first term", "d = common difference", "n = position of the term you want"] },
    { t: "note", kind: "why", title: "Where the (n − 1) comes from", html: "The first term needs <strong>no</strong> steps. The second needs one step of d, the third needs two, and so on. By the time you reach the nth term you have taken (n − 1) steps. That is the entire derivation — and it is worth writing out, because the board asks for it." },
    { t: "note", kind: "memory", html: "The commonest error in the whole chapter is writing a + nd instead of a + (n−1)d. Sanity check by putting n = 1: you should get back a." },

    { t: "steps", title: "Which term of the AP 3, 8, 13, 18, … is 78?",
      intro: "Two marks, and the method is always the same.",
      steps: [
        "Identify a = 3 and d = 8 − 3 = 5.",
        "Set the nth term equal to 78: a + (n−1)d = 78, so 3 + (n−1)(5) = 78.",
        "Solve: (n−1)(5) = 75, so n − 1 = 15.",
        "Therefore n = 16.",
      ],
      answer: "78 is the 16th term.",
    },
    { t: "note", kind: "exam", html: "If solving gives a value of n that is <strong>not a positive whole number</strong>, the answer is that the given value is not a term of that AP at all. That is a legitimate — and quite commonly set — answer." },

    { t: "h", text: "The sum of the first n terms" },
    { t: "formula", name: "Sum of n terms", expr: "S<sub>n</sub> = n/2 [ 2a + (n − 1)d ]",
      where: ["Use this when you know a, d and n"] },
    { t: "formula", name: "Sum when you know the last term", expr: "S<sub>n</sub> = n/2 ( a + l )",
      where: ["l = the last term, a<sub>n</sub>", "Use this when the final term is given instead of d"] },
    { t: "note", kind: "why", title: "Gauss's trick", html: "Write the sum forwards, then write it again backwards underneath and add the two rows. Every column gives the same total, (a + l), and there are n columns. So 2Sₙ = n(a + l), which gives Sₙ = n/2(a + l). Substituting l = a + (n−1)d gives the first form." },
    { t: "note", kind: "idea", html: "A useful consequence: <strong>a<sub>n</sub> = S<sub>n</sub> − S<sub>n−1</sub></strong>. If a question gives you a formula for Sₙ and asks for the nth term, this is the fastest route." },

    { t: "steps", title: "Find the sum of the first 22 terms of the AP 8, 3, −2, …",
      intro: "Note the negative common difference — the terms are falling.",
      steps: [
        "Here a = 8 and d = 3 − 8 = <strong>−5</strong>, with n = 22.",
        "Use Sₙ = n/2 [2a + (n−1)d].",
        "Substitute: S₂₂ = 22/2 [2(8) + 21(−5)].",
        "Simplify inside the bracket: 16 − 105 = −89.",
        "So S₂₂ = 11 × (−89).",
      ],
      answer: "S₂₂ = −979.",
    },

    { t: "h", text: "The question types that actually appear" },
    { t: "list", items: [
      "<strong>Find n given aₙ</strong> — set a + (n−1)d equal to the value and solve.",
      "<strong>Two terms given, find a and d</strong> — write both as equations in a and d and solve the pair simultaneously.",
      "<strong>First negative term</strong> — solve a + (n−1)d &lt; 0 and take the smallest whole n that works.",
      "<strong>Sum of first n natural numbers</strong> — this is the AP 1, 2, 3, … with a = 1, d = 1, giving Sₙ = n(n+1)/2.",
      "<strong>Middle term</strong> — for an odd number of terms, the middle one is the ((n+1)/2)th.",
      "<strong>Three terms in AP</strong> — take them as a − d, a, a + d. The d's cancel when you add, which makes the algebra much shorter.",
    ] },
    { t: "steps", title: "The 4th term of an AP is 11 and the 10th term is 29. Find the AP.",
      intro: "The 'two terms given' type. Write both as equations and subtract.",
      steps: [
        "a₄ = a + 3d = 11 … (i)",
        "a₁₀ = a + 9d = 29 … (ii)",
        "Subtract (i) from (ii): 6d = 18, so <strong>d = 3</strong>.",
        "Substitute back into (i): a + 9 = 11, so <strong>a = 2</strong>.",
      ],
      answer: "The AP is 2, 5, 8, 11, 14, …",
    },
    { t: "note", kind: "memory", html: "When a problem says &ldquo;three numbers are in AP and their sum is 27&rdquo;, take them as <strong>a−d, a, a+d</strong>. The sum immediately becomes 3a = 27, so a = 9 in one line. Choosing the symmetric form saves half the work." },
  ],
  formulas: [
    { name: "Common difference", expr: "d = a₂ − a₁" },
    { name: "nth term", expr: "aₙ = a + (n − 1)d" },
    { name: "Sum of n terms", expr: "Sₙ = n/2 [2a + (n − 1)d]" },
    { name: "Sum with last term known", expr: "Sₙ = n/2 (a + l)" },
    { name: "nth term from sums", expr: "aₙ = Sₙ − Sₙ₋₁" },
    { name: "Sum of first n natural numbers", expr: "n(n + 1)/2" },
  ],
  examFocus: [
    "Checking at least two differences before declaring a sequence an AP.",
    "aₙ = a + (n−1)d — including being able to derive it in words.",
    "Both sum formulas, and knowing which to reach for.",
    "Deriving Sₙ by the write-it-backwards argument.",
    "'Two terms given' problems solved by subtracting the equations.",
    "Taking three terms in AP as a−d, a, a+d.",
    "Recognising when n comes out non-integral, meaning the value is not a term of the AP.",
  ],
  flashcards: [
    { q: "What is an arithmetic progression?", a: "A sequence in which the difference between any term and its preceding term is always the same. That constant is the common difference d." },
    { q: "How do you check whether a sequence is an AP?", a: "Compute at least two consecutive differences. If they are all equal, it is an AP; if any differ, it is not." },
    { q: "State the formula for the nth term.", a: "aₙ = a + (n − 1)d, where a is the first term and d the common difference." },
    { q: "Why is it (n − 1)d and not nd?", a: "The first term requires no steps of d. Reaching the nth term takes n − 1 steps. Check by putting n = 1: you should get a back." },
    { q: "State both formulas for the sum of the first n terms.", a: "Sₙ = n/2 [2a + (n−1)d], and when the last term l is known, Sₙ = n/2 (a + l)." },
    { q: "How is the sum formula derived?", a: "Write the sum forwards and backwards and add. Each column totals (a + l) and there are n columns, so 2Sₙ = n(a + l), giving Sₙ = n/2(a + l)." },
    { q: "How do you find the nth term if you are given a formula for Sₙ?", a: "Use aₙ = Sₙ − Sₙ₋₁." },
    { q: "What is the sum of the first n natural numbers?", a: "n(n + 1)/2 — the AP 1, 2, 3, … with a = 1 and d = 1." },
    { q: "How should you represent three numbers in AP?", a: "As a − d, a and a + d. Their sum is 3a, which removes d immediately and shortens the algebra." },
    { q: "How do you find the first negative term of an AP?", a: "Solve a + (n−1)d < 0 for n and take the smallest positive integer satisfying it." },
    { q: "What does it mean if solving for n gives a fraction?", a: "The given value is not a term of that AP at all — n must be a positive integer." },
    { q: "The 5th term of an AP is 17 and the common difference is 3. What is the first term?", a: "a + 4d = 17, so a + 12 = 17 and a = 5." },
  ],
  quiz: [
    { q: "The common difference of the AP 10, 7, 4, 1, … is:", options: ["3", "−3", "−1", "7"], answer: 1, why: "d = 7 − 10 = −3. The terms are decreasing, so d is negative." },
    { q: "The 10th term of the AP 2, 7, 12, … is:", options: ["45", "47", "52", "50"], answer: 1, why: "a = 2, d = 5. a₁₀ = 2 + 9(5) = 2 + 45 = 47." },
    { q: "Which of these is an AP?", options: ["1, 3, 9, 27", "2, 4, 8, 16", "5, 9, 13, 17", "1, 4, 9, 16"], answer: 2, why: "5, 9, 13, 17 has a constant difference of 4. The others are geometric or squares, where the difference keeps changing." },
    { q: "The sum of the first 10 natural numbers is:", options: ["50", "55", "45", "100"], answer: 1, why: "n(n+1)/2 = 10 × 11 / 2 = 55." },
    { q: "If aₙ = 3n + 2, the common difference is:", options: ["2", "3", "5", "1"], answer: 1, why: "a₁ = 5, a₂ = 8, a₃ = 11. The difference is 3 — which is also the coefficient of n." },
    { q: "How many two-digit numbers are divisible by 3?", options: ["30", "33", "29", "31"], answer: 0, why: "The AP is 12, 15, …, 99 with a = 12, d = 3. 99 = 12 + (n−1)3 gives n − 1 = 29, so n = 30." },
    { q: "The sum of the first 20 terms of the AP 1, 4, 7, … is:", options: ["590", "580", "610", "620"], answer: 0, why: "a = 1, d = 3, n = 20. S = 20/2[2(1) + 19(3)] = 10[2 + 57] = 10 × 59 = 590." },
    { q: "If the 3rd and 9th terms of an AP are 4 and −8, the common difference is:", options: ["2", "−2", "3", "−3"], answer: 1, why: "a + 2d = 4 and a + 8d = −8. Subtracting: 6d = −12, so d = −2." },
    { q: "Three numbers in AP have sum 27. The middle number is:", options: ["7", "8", "9", "12"], answer: 2, why: "Taking them as a−d, a, a+d, the sum is 3a = 27, so a = 9. The middle term is always the sum divided by 3." },
    { q: "The 11th term from the end of the AP 10, 7, 4, …, −62 is:", options: ["−32", "−30", "25", "−25"], answer: 0, why: "From the end, treat −62 as the first term with common difference +3. The 11th term is −62 + 10(3) = −32." },
    { q: "If Sₙ = n² + 3n, then a₁₀ is:", options: ["22", "24", "130", "20"], answer: 0, why: "aₙ = Sₙ − Sₙ₋₁. S₁₀ = 130, S₉ = 81 + 27 = 108. So a₁₀ = 130 − 108 = 22." },
    { q: "In an AP with a = 5 and d = −2, the first negative term is the:", options: ["3rd", "4th", "5th", "6th"], answer: 1, why: "5 + (n−1)(−2) < 0 gives 5 < 2(n−1), so n − 1 > 2.5 and n > 3.5. The smallest integer is n = 4, and a₄ = 5 − 6 = −1." },
  ],
};
