import type { Chapter } from "@/lib/types";

export const ch06: Chapter = {
  slug: "triangles",
  num: 6,
  title: "Triangles",
  unit: "geometry",
  unitName: "Geometry",
  marks: "Unit IV · 15 marks",
  minutes: 20,
  blurb: "Same shape, different size. One theorem you must prove, three criteria you must apply, and a lot of careful naming.",
  bigIdea: "Two triangles are similar when one is a scaled copy of the other. Angles stay identical; every length changes by the same factor.",
  syllabus: [
    "Definitions, examples and counter-examples of similar triangles",
    "Basic Proportionality Theorem — proof required",
    "Converse of the Basic Proportionality Theorem",
    "AAA / AA similarity criterion — statement only",
    "SSS similarity criterion — statement only",
    "SAS similarity criterion — statement only",
  ],
  blocks: [
    { t: "h", text: "Congruent versus similar" },
    { t: "compare",
      left: { title: "Congruent — identical", items: [
        "Same shape <em>and</em> same size",
        "All corresponding sides equal",
        "All corresponding angles equal",
        "Symbol: ≅",
        "Ratio of sides is 1 : 1",
      ] },
      right: { title: "Similar — same shape only", items: [
        "Same shape, possibly different size",
        "Corresponding sides in the <strong>same ratio</strong>",
        "All corresponding angles equal",
        "Symbol: ~",
        "Ratio of sides is k : 1 for some k",
      ] } },
    { t: "note", kind: "idea", html: "Every congruent pair is also similar (with ratio 1), but not the other way round. All circles are similar, and all squares are similar — but two rectangles need not be, because their side ratios can differ." },
    { t: "note", kind: "trap", html: "Order matters when you write similarity. △ABC ~ △PQR means A↔P, B↔Q, C↔R specifically. Writing △ABC ~ △QRP asserts something different and will cost you the mark even if your working is right." },

    { t: "h", text: "The Basic Proportionality Theorem" },
    { t: "sim", id: "similar-triangles" },
    { t: "formula", name: "Basic Proportionality Theorem (Thales)",
      expr: "If a line is drawn parallel to one side of a triangle to intersect the other two sides in distinct points, the other two sides are divided in the same ratio.",
      where: ["In △ABC with DE ∥ BC: <strong>AD/DB = AE/EC</strong>"] },
    { t: "note", kind: "exam", title: "This proof is required", html: "BPT is one of the two proofs in this chapter that the syllabus explicitly demands. Learn it as a sequence — the trick is the pair of triangles that share the same height." },
    { t: "steps", title: "Prove the Basic Proportionality Theorem.",
      intro: "In △ABC, DE ∥ BC meets AB at D and AC at E. Prove AD/DB = AE/EC.",
      steps: [
        "Join BE and CD. Drop perpendiculars EM ⊥ AB and DN ⊥ AC.",
        "Area of △ADE = ½ × AD × EM, and area of △DBE = ½ × DB × EM (they share the same height EM). So <strong>ar(ADE)/ar(DBE) = AD/DB</strong>.",
        "Similarly, using height DN: ar(ADE) = ½ × AE × DN and ar(DEC) = ½ × EC × DN. So <strong>ar(ADE)/ar(DEC) = AE/EC</strong>.",
        "Now △DBE and △DEC lie on the <strong>same base DE</strong> and between the <strong>same parallels DE and BC</strong>. Triangles on the same base and between the same parallels are equal in area, so <strong>ar(DBE) = ar(DEC)</strong>.",
        "Therefore ar(ADE)/ar(DBE) = ar(ADE)/ar(DEC).",
      ],
      answer: "Hence AD/DB = AE/EC. ∎",
    },
    { t: "note", kind: "idea", title: "The converse", html: "If a line divides two sides of a triangle in the same ratio, then that line is <strong>parallel</strong> to the third side. This is what you use when a question asks you to <em>prove</em> two lines are parallel — compute the two ratios and show they are equal." },

    { t: "h", text: "The three similarity criteria" },
    { t: "table", head: ["Criterion", "What you must show", "Written as"], rows: [
      ["<strong>AAA / AA</strong>", "Two angles of one triangle equal two angles of the other (the third then follows automatically)", "∠A = ∠P and ∠B = ∠Q ⟹ △ABC ~ △PQR"],
      ["<strong>SSS</strong>", "All three pairs of corresponding sides are in the same ratio", "AB/PQ = BC/QR = CA/RP ⟹ △ABC ~ △PQR"],
      ["<strong>SAS</strong>", "Two pairs of sides in the same ratio and the <em>included</em> angles equal", "AB/PQ = AC/PR and ∠A = ∠P ⟹ △ABC ~ △PQR"],
    ] },
    { t: "note", kind: "trap", html: "For SAS the angle must be the one <strong>between</strong> the two sides. An equal angle that is not included proves nothing — this is exactly the trap set in multiple-choice questions." },
    { t: "note", kind: "memory", html: "AAA is really AA: once two angles match, the third has no choice, because the angles of a triangle add to 180°. So in an exam you only ever need to find two." },

    { t: "h", text: "Where similarity comes from in a right triangle" },
    { t: "p", html: "Drop a perpendicular from the right angle of a right triangle to the hypotenuse. It creates two smaller triangles, and <strong>all three</strong> triangles in the picture are similar to one another." },
    { t: "note", kind: "why", html: "Each small triangle shares one acute angle with the big one, and both have a right angle. Two angles equal is enough — AA does the rest. This single configuration is behind a large share of the problems set on this chapter." },

    { t: "steps", title: "In △ABC, DE ∥ BC. If AD = 4 cm, DB = 6 cm and AE = 5 cm, find EC.",
      intro: "Direct application of BPT — one of the easiest marks in the paper.",
      steps: [
        "DE ∥ BC, so by the Basic Proportionality Theorem, AD/DB = AE/EC.",
        "Substitute the known values: 4/6 = 5/EC.",
        "Cross-multiply: 4 × EC = 6 × 5 = 30.",
        "So EC = 30/4.",
      ],
      answer: "EC = 7.5 cm.",
    },
    { t: "steps", title: "△ABC ~ △PQR with AB = 6, BC = 8, PQ = 9. Find QR.",
      intro: "Similar triangles: set up the ratio of corresponding sides carefully.",
      steps: [
        "The similarity △ABC ~ △PQR tells you A↔P, B↔Q, C↔R. So AB corresponds to PQ, and BC corresponds to QR.",
        "Therefore AB/PQ = BC/QR.",
        "Substitute: 6/9 = 8/QR.",
        "Cross-multiply: 6 × QR = 72.",
      ],
      answer: "QR = 12.",
    },
    { t: "note", kind: "exam", html: "In every similarity problem, write the correspondence down first — which vertex maps to which. Almost all lost marks in this chapter come from pairing the wrong sides, not from arithmetic." },
  ],
  formulas: [
    { name: "Basic Proportionality Theorem", expr: "DE ∥ BC ⟹ AD/DB = AE/EC" },
    { name: "Converse of BPT", expr: "AD/DB = AE/EC ⟹ DE ∥ BC" },
    { name: "AA similarity", expr: "Two pairs of equal angles ⟹ similar" },
    { name: "SSS similarity", expr: "AB/PQ = BC/QR = CA/RP ⟹ similar" },
    { name: "SAS similarity", expr: "Two sides in ratio + included angles equal ⟹ similar" },
  ],
  examFocus: [
    "The full proof of the Basic Proportionality Theorem, including the equal-area step.",
    "Using the converse of BPT to prove two lines are parallel.",
    "Stating the three similarity criteria correctly — and that SAS needs the <em>included</em> angle.",
    "Writing the similarity correspondence in the right order before setting up ratios.",
    "The three similar triangles formed by the altitude to the hypotenuse of a right triangle.",
    "Knowing that congruent implies similar, but not the reverse.",
  ],
  flashcards: [
    { q: "What does it mean for two triangles to be similar?", a: "Their corresponding angles are equal and their corresponding sides are in the same ratio. They have the same shape but not necessarily the same size." },
    { q: "How do similar and congruent triangles differ?", a: "Congruent triangles are the same shape and size, with sides in ratio 1:1. Similar triangles are the same shape but may be different sizes. Every congruent pair is similar; the converse is false." },
    { q: "State the Basic Proportionality Theorem.", a: "If a line is drawn parallel to one side of a triangle to intersect the other two sides in distinct points, then it divides those two sides in the same ratio." },
    { q: "Outline the proof of BPT.", a: "Join BE and CD, and drop perpendiculars EM and DN. Compare areas: ar(ADE)/ar(DBE) = AD/DB and ar(ADE)/ar(DEC) = AE/EC. Since △DBE and △DEC are on the same base DE and between the same parallels, their areas are equal, so the two ratios must be equal." },
    { q: "State the converse of BPT and say when you use it.", a: "If a line divides two sides of a triangle in the same ratio, it is parallel to the third side. Use it whenever a question asks you to prove two lines are parallel." },
    { q: "State the AA similarity criterion.", a: "If two angles of one triangle are respectively equal to two angles of another, the triangles are similar. The third pair is then automatically equal." },
    { q: "State the SSS similarity criterion.", a: "If the corresponding sides of two triangles are in the same ratio, the triangles are similar." },
    { q: "State the SAS similarity criterion.", a: "If two sides of one triangle are proportional to two sides of another and the angles included between those sides are equal, the triangles are similar." },
    { q: "Why must the angle in SAS be the included angle?", a: "Because with a non-included angle the triangle is not determined — two different triangles can satisfy the conditions, so similarity does not follow." },
    { q: "What happens when you drop a perpendicular from the right angle to the hypotenuse?", a: "It creates two smaller triangles, and all three triangles in the figure are similar to one another, by AA." },
    { q: "Are all squares similar? Are all rectangles?", a: "All squares are similar, since their angles are all 90° and all sides are in a fixed ratio. Rectangles need not be — a 2×3 and a 2×5 rectangle have different side ratios." },
    { q: "Why does the order of letters matter when writing △ABC ~ △PQR?", a: "It specifies the correspondence A↔P, B↔Q, C↔R, which is what tells you which sides are proportional to which. A different order asserts a different — usually false — statement." },
  ],
  quiz: [
    { q: "In △ABC, DE ∥ BC with AD = 3, DB = 5 and AE = 6. Then EC equals:", options: ["10", "8", "3.6", "9"], answer: 0, why: "By BPT, AD/DB = AE/EC, so 3/5 = 6/EC, giving 3·EC = 30 and EC = 10." },
    { q: "Which criterion needs the angle to be between the two sides?", options: ["AA", "SSS", "SAS", "RHS"], answer: 2, why: "SAS similarity requires the equal angles to be the ones included between the proportional sides." },
    { q: "If △ABC ~ △DEF and AB = 4, DE = 6, BC = 6, then EF is:", options: ["4", "9", "8", "12"], answer: 1, why: "AB/DE = BC/EF, so 4/6 = 6/EF, giving 4·EF = 36 and EF = 9." },
    { q: "All ______ are similar.", options: ["Rectangles", "Triangles", "Circles", "Rhombuses"], answer: 2, why: "Every circle has the same shape and differs only by a scale factor. Rectangles and rhombuses can have different proportions or angles." },
    { q: "In △ABC and △DEF, ∠A = ∠D and AB/DE = AC/DF. The triangles are similar by:", options: ["AA", "SSS", "SAS", "They are not similar"], answer: 2, why: "Two pairs of sides are proportional and the angle between them (∠A and ∠D) is equal — that is exactly the SAS similarity criterion." },
    { q: "In a right triangle, the perpendicular from the right angle to the hypotenuse creates:", options: ["Two congruent triangles", "Three mutually similar triangles", "Two equilateral triangles", "No similar triangles"], answer: 1, why: "Each small triangle shares an acute angle with the original and has a right angle, so by AA all three triangles are similar." },
    { q: "The converse of BPT is used to prove that:", options: ["Two triangles are congruent", "A line is parallel to a side", "Two angles are equal", "A triangle is right-angled"], answer: 1, why: "If a line divides two sides in the same ratio, the converse lets you conclude the line is parallel to the third side." },
    { q: "In △ABC, D and E lie on AB and AC with AD = 2, AB = 6, AE = 3, AC = 9. Then DE is:", options: ["Parallel to BC", "Perpendicular to BC", "Equal to BC", "Not determined"], answer: 0, why: "DB = 4 and EC = 6, so AD/DB = 2/4 = 1/2 and AE/EC = 3/6 = 1/2. Equal ratios, so by the converse of BPT, DE ∥ BC." },
    { q: "If two triangles are congruent, they are:", options: ["Never similar", "Always similar", "Similar only if equilateral", "Similar only if right-angled"], answer: 1, why: "Congruence is similarity with ratio 1:1, so congruent triangles are always similar." },
    { q: "△ABC ~ △PQR. If ∠A = 50° and ∠B = 60°, then ∠R equals:", options: ["50°", "60°", "70°", "110°"], answer: 2, why: "∠C = 180 − 50 − 60 = 70°, and C corresponds to R, so ∠R = 70°." },
    { q: "In BPT's proof, the key step is that △DBE and △DEC have equal areas because they:", options: ["Are congruent", "Are on the same base and between the same parallels", "Have equal perimeters", "Are both right-angled"], answer: 1, why: "Triangles on the same base and between the same pair of parallel lines have equal areas — that is what makes the two ratios equal." },
    { q: "A vertical pole 6 m tall casts a 4 m shadow while a tower casts a 28 m shadow at the same time. The tower's height is:", options: ["42 m", "36 m", "18 m", "48 m"], answer: 0, why: "The two triangles are similar (same sun angle). 6/4 = h/28, so h = 6 × 28 / 4 = 42 m." },
  ],
};
