import type { Chapter } from "@/lib/types";

export const ch07: Chapter = {
  slug: "coordinate-geometry",
  num: 7,
  title: "Coordinate Geometry",
  unit: "coord",
  unitName: "Coordinate Geometry",
  marks: "Unit III · 6 marks",
  minutes: 14,
  blurb: "Two formulas — distance and section — and a surprising number of questions you can answer with just those.",
  bigIdea: "Put geometry on a grid and every shape becomes arithmetic. Distance is Pythagoras in disguise; the section formula is a weighted average.",
  syllabus: [
    "Distance formula",
    "Section formula (internal division)",
  ],
  blocks: [
    { t: "h", text: "The distance formula" },
    { t: "sim", id: "coordinate-plane" },
    { t: "formula", name: "Distance between two points",
      expr: "PQ = √[ (x₂ − x₁)² + (y₂ − y₁)² ]",
      where: ["P(x₁, y₁) and Q(x₂, y₂)"] },
    { t: "note", kind: "why", title: "It really is just Pythagoras", html: "Drop a horizontal line from P and a vertical line from Q. They meet at a right angle, forming a right triangle whose legs are |x₂ − x₁| and |y₂ − y₁|. The distance PQ is the hypotenuse — so the formula is Pythagoras with the sides written in coordinates. The dashed triangle in the tool above is exactly that." },
    { t: "formula", name: "Distance from the origin", expr: "OP = √(x² + y²)",
      where: ["Just the general formula with (x₁, y₁) = (0, 0)"] },
    { t: "note", kind: "trap", html: "Because both differences are <strong>squared</strong>, the order of subtraction does not matter. (x₂ − x₁)² gives exactly the same answer as (x₁ − x₂)². Students often waste time worrying about this." },

    { t: "h", text: "What you can prove with distance alone" },
    { t: "table", head: ["To show the points form…", "Show that…"], rows: [
      ["An <strong>isosceles</strong> triangle", "Exactly two of the three sides are equal"],
      ["An <strong>equilateral</strong> triangle", "All three sides are equal"],
      ["A <strong>right-angled</strong> triangle", "The three sides satisfy Pythagoras: a² + b² = c²"],
      ["A <strong>square</strong>", "All four sides equal <em>and</em> the two diagonals equal"],
      ["A <strong>rhombus</strong>", "All four sides equal but the diagonals are <em>unequal</em>"],
      ["A <strong>parallelogram</strong>", "Opposite sides equal (or the diagonals share a midpoint)"],
      ["<strong>Collinear</strong> points", "The longest distance equals the sum of the other two"],
    ] },
    { t: "note", kind: "exam", html: "The square-versus-rhombus distinction is a favourite. Equal sides alone are not enough — you must check the diagonals. Equal diagonals means square; unequal means rhombus." },

    { t: "steps", title: "Show that (1, 7), (4, 2), (−1, −1) and (−4, 4) form a square.",
      intro: "Four sides plus two diagonals — six distance calculations, done systematically.",
      steps: [
        "Call them A(1,7), B(4,2), C(−1,−1), D(−4,4), taken in order around the shape.",
        "AB = √[(4−1)² + (2−7)²] = √(9 + 25) = √34.",
        "BC = √[(−1−4)² + (−1−2)²] = √(25 + 9) = √34. Similarly CD = √34 and DA = √34.",
        "So all four sides are equal — it is at least a rhombus.",
        "Now the diagonals: AC = √[(−1−1)² + (−1−7)²] = √(4 + 64) = √68.",
        "BD = √[(−4−4)² + (4−2)²] = √(64 + 4) = √68. The diagonals are equal.",
      ],
      answer: "Four equal sides and equal diagonals, so ABCD is a square. ∎",
    },

    { t: "h", text: "The section formula" },
    { t: "formula", name: "Point dividing a line segment internally in ratio m : n",
      expr: "P = ( (mx₂ + nx₁)/(m + n) , (my₂ + ny₁)/(m + n) )",
      where: ["The segment joins A(x₁, y₁) to B(x₂, y₂)", "m is the part nearer A's end, n nearer B's"] },
    { t: "note", kind: "memory", html: "Notice the <strong>cross-over</strong>: m pairs with x₂ and n pairs with x₁. Writing mx₁ + nx₂ is the most common error in this chapter. A quick check: if m is large the point should sit close to B — try it in the tool above." },
    { t: "formula", name: "Midpoint formula", expr: "M = ( (x₁ + x₂)/2 , (y₁ + y₂)/2 )",
      where: ["Just the section formula with m : n = 1 : 1"] },
    { t: "note", kind: "idea", html: "The midpoint formula is not a separate thing to memorise — it is the section formula with equal weights. If you ever forget it, set m = n = 1 in the section formula and it falls out." },

    { t: "steps", title: "Find the point that divides the join of (−1, 7) and (4, −3) in the ratio 2 : 3.",
      intro: "Direct substitution — but keep the cross-over straight.",
      steps: [
        "Here (x₁, y₁) = (−1, 7), (x₂, y₂) = (4, −3), m = 2, n = 3.",
        "x-coordinate = (mx₂ + nx₁)/(m+n) = [2(4) + 3(−1)]/5 = (8 − 3)/5 = 1.",
        "y-coordinate = (my₂ + ny₁)/(m+n) = [2(−3) + 3(7)]/5 = (−6 + 21)/5 = 3.",
      ],
      answer: "The point is (1, 3).",
    },
    { t: "steps", title: "In what ratio does the x-axis divide the segment joining (1, −5) and (−4, 5)?",
      intro: "A reverse problem. The key insight: any point on the x-axis has y = 0.",
      steps: [
        "Let the ratio be k : 1. Then the dividing point has y-coordinate [k(5) + 1(−5)]/(k+1).",
        "The point lies on the x-axis, so its y-coordinate is <strong>0</strong>.",
        "Set it to zero: (5k − 5)/(k+1) = 0, which needs 5k − 5 = 0.",
        "So k = 1, and the ratio is 1 : 1.",
      ],
      answer: "The x-axis divides it in the ratio 1 : 1 — that is, at the midpoint.",
    },
    { t: "note", kind: "exam", html: "Two reverse tricks worth knowing. A point on the <strong>x-axis</strong> has y = 0; a point on the <strong>y-axis</strong> has x = 0. Take the unknown ratio as <strong>k : 1</strong> rather than m : n — one unknown instead of two." },

    { t: "h", text: "Points that come up repeatedly" },
    { t: "list", items: [
      "The <strong>centroid</strong> of a triangle with vertices (x₁,y₁), (x₂,y₂), (x₃,y₃) is at ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3) — the average of the vertices.",
      "The diagonals of a <strong>parallelogram bisect each other</strong>, so their midpoints coincide. This is how you find a missing fourth vertex.",
      "<strong>Points of trisection</strong> divide a segment in the ratios 1 : 2 and 2 : 1.",
    ] },
    { t: "note", kind: "real", html: "The section formula is a weighted average, which is why it feels familiar — it is the same arithmetic as working out an average mark where some tests count double." },
  ],
  formulas: [
    { name: "Distance formula", expr: "√[(x₂−x₁)² + (y₂−y₁)²]" },
    { name: "Distance from origin", expr: "√(x² + y²)" },
    { name: "Section formula (m : n)", expr: "((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n))" },
    { name: "Midpoint", expr: "((x₁+x₂)/2, (y₁+y₂)/2)" },
    { name: "Centroid of a triangle", expr: "((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3)" },
    { name: "Points of trisection", expr: "ratios 1 : 2 and 2 : 1" },
  ],
  examFocus: [
    "The distance formula, and recognising it as Pythagoras.",
    "Classifying a quadrilateral: sides <em>and</em> diagonals, to separate square from rhombus.",
    "The section formula with the cross-over (m with x₂) written correctly.",
    "Reverse problems: taking the ratio as k : 1, and using y = 0 on the x-axis.",
    "Using 'diagonals of a parallelogram bisect each other' to find a fourth vertex.",
    "Proving collinearity by showing one distance equals the sum of the other two.",
  ],
  flashcards: [
    { q: "State the distance formula.", a: "The distance between P(x₁,y₁) and Q(x₂,y₂) is √[(x₂−x₁)² + (y₂−y₁)²]." },
    { q: "Why is the distance formula just Pythagoras?", a: "The horizontal and vertical differences form the two legs of a right triangle whose hypotenuse is the required distance." },
    { q: "What is the distance of a point (x, y) from the origin?", a: "√(x² + y²) — the distance formula with the other point taken as (0, 0)." },
    { q: "State the section formula.", a: "The point dividing the join of (x₁,y₁) and (x₂,y₂) internally in the ratio m : n is ((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n))." },
    { q: "What is the commonest error in the section formula?", a: "Forgetting the cross-over. m multiplies x₂ (not x₁) and n multiplies x₁. Check by making m large — the point should move towards the second point." },
    { q: "How is the midpoint formula related to the section formula?", a: "It is the section formula with m : n = 1 : 1, giving ((x₁+x₂)/2, (y₁+y₂)/2)." },
    { q: "How do you show three points are collinear using distances?", a: "Compute all three distances. If the largest equals the sum of the other two, the points lie on a straight line." },
    { q: "How do you distinguish a square from a rhombus using coordinates?", a: "Both have four equal sides. In a square the diagonals are also equal; in a rhombus they are not." },
    { q: "What is the centroid of a triangle?", a: "The point ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3) — the average of the three vertices. It is where the medians meet." },
    { q: "How do you find the fourth vertex of a parallelogram?", a: "Use the fact that the diagonals bisect each other: the midpoint of one diagonal equals the midpoint of the other. Solve for the unknown vertex." },
    { q: "What are the points of trisection?", a: "The two points dividing a segment into three equal parts — they divide it in the ratios 1 : 2 and 2 : 1." },
    { q: "How do you find the ratio in which the x-axis divides a segment?", a: "Take the ratio as k : 1, write the y-coordinate of the dividing point, set it equal to 0 (since any point on the x-axis has y = 0), and solve for k." },
  ],
  quiz: [
    { q: "The distance between (3, 4) and (0, 0) is:", options: ["5", "7", "12", "25"], answer: 0, why: "√(3² + 4²) = √25 = 5 — the classic 3-4-5 triangle." },
    { q: "The midpoint of the segment joining (2, 3) and (6, 7) is:", options: ["(4, 5)", "(8, 10)", "(2, 2)", "(3, 4)"], answer: 0, why: "((2+6)/2, (3+7)/2) = (4, 5)." },
    { q: "The point dividing (2, 3) and (6, 7) in the ratio 1 : 3 is:", options: ["(3, 4)", "(4, 5)", "(5, 6)", "(2.5, 3.5)"], answer: 0, why: "x = (1·6 + 3·2)/4 = 12/4 = 3, y = (1·7 + 3·3)/4 = 16/4 = 4." },
    { q: "The distance between (a, 0) and (0, b) is:", options: ["a + b", "√(a² + b²)", "a − b", "ab"], answer: 1, why: "√[(0−a)² + (b−0)²] = √(a² + b²)." },
    { q: "The point (0, 5) lies on:", options: ["The x-axis", "The y-axis", "Neither axis", "The origin"], answer: 1, why: "Its x-coordinate is 0, and every point with x = 0 lies on the y-axis." },
    { q: "If the points (1,2), (4,y) and (7,8) are collinear and equally spaced, y is:", options: ["4", "5", "6", "3"], answer: 1, why: "(4, y) is the midpoint of (1,2) and (7,8), so y = (2 + 8)/2 = 5." },
    { q: "The centroid of a triangle with vertices (0,0), (6,0) and (0,9) is:", options: ["(2, 3)", "(3, 4.5)", "(6, 9)", "(3, 3)"], answer: 0, why: "((0+6+0)/3, (0+0+9)/3) = (2, 3)." },
    { q: "A quadrilateral has all four sides equal but unequal diagonals. It is a:", options: ["Square", "Rhombus", "Rectangle", "Trapezium"], answer: 1, why: "Equal sides make it a rhombus; only if the diagonals were also equal would it be a square." },
    { q: "The y-axis divides the join of (−3, 4) and (6, −2) in the ratio:", options: ["1 : 2", "2 : 1", "1 : 1", "3 : 2"], answer: 0, why: "Take the ratio k : 1. x-coordinate = (6k − 3)/(k+1) = 0 gives 6k = 3, so k = 1/2 — that is 1 : 2." },
    { q: "The distance between (−2, 3) and (4, 3) is:", options: ["6", "0", "3", "√6"], answer: 0, why: "The y-coordinates are equal, so the points lie on a horizontal line and the distance is just |4 − (−2)| = 6." },
    { q: "If (x, 2) is equidistant from (3, 4) and (−1, 2), then x is:", options: ["1.5", "2", "3", "0"], answer: 0, why: "Square both distances: (x−3)² + (2−4)² = (x+1)² + 0, so x² − 6x + 9 + 4 = x² + 2x + 1. The x² cancels, leaving 13 − 6x = 2x + 1, so 12 = 8x and x = 1.5." },
    { q: "The points of trisection divide a segment in the ratios:", options: ["1:1 and 2:2", "1:2 and 2:1", "1:3 and 3:1", "2:3 and 3:2"], answer: 1, why: "Trisection splits the segment into three equal parts, so the two points are at 1:2 and 2:1 from one end." },
  ],
};
