import type { Chapter } from "@/lib/types";

export const ch08: Chapter = {
  slug: "introduction-to-trigonometry",
  num: 8,
  title: "Introduction to Trigonometry",
  unit: "trig",
  unitName: "Trigonometry",
  marks: "Unit V · 12 marks",
  minutes: 20,
  blurb: "Three fractions of the sides of a right triangle. Learn one table of values and one identity, and most of the chapter is arithmetic.",
  bigIdea: "sin, cos and tan are not mysterious functions — they are just ratios of sides. Fix the angle and the ratios are fixed too, no matter how big the triangle is.",
  syllabus: [
    "Trigonometric ratios of an acute angle in a right-angled triangle",
    "Proof of their existence (well defined)",
    "Values of the ratios at 30°, 45° and 60°",
    "Relationships between the ratios",
    "Proof and applications of the identity sin²A + cos²A = 1",
    "Only simple identities to be given",
  ],
  blocks: [
    { t: "h", text: "The three ratios" },
    { t: "sim", id: "trig-ratios" },
    { t: "formula", name: "The definitions",
      expr: "sin θ = opposite / hypotenuse &nbsp;·&nbsp; cos θ = adjacent / hypotenuse &nbsp;·&nbsp; tan θ = opposite / adjacent",
      where: ["'Opposite' and 'adjacent' are relative to the angle θ you are looking at", "The hypotenuse is always the side facing the right angle"] },
    { t: "note", kind: "memory", html: "<strong>SOH–CAH–TOA</strong>: Sin = Opposite/Hypotenuse, Cos = Adjacent/Hypotenuse, Tan = Opposite/Adjacent. Or the Hindi mnemonic many students use: <em>Pandit Badri Prasad, Har Har Bole</em> — Perpendicular/Hypotenuse, Base/Hypotenuse, Perpendicular/Base." },
    { t: "note", kind: "why", title: "Why do the ratios depend only on the angle?", html: "Draw two right triangles with the same acute angle. They are similar by AA, so their corresponding sides are in the same ratio — which means opposite/hypotenuse comes out identical in both. That is exactly why sin 30° is 1/2 whether the triangle is centimetres or kilometres across." },
    { t: "formula", name: "The three reciprocals",
      expr: "cosec θ = 1/sin θ &nbsp;·&nbsp; sec θ = 1/cos θ &nbsp;·&nbsp; cot θ = 1/tan θ" },
    { t: "note", kind: "trap", html: "The pairings are counter-intuitive: <strong>sec</strong> goes with <strong>cos</strong> and <strong>cosec</strong> goes with <strong>sin</strong>. Read the third letter — se<strong>c</strong> → <strong>c</strong>os. Getting this backwards is a very common slip." },

    { t: "h", text: "The table you must know cold" },
    { t: "table", head: ["", "0°", "30°", "45°", "60°", "90°"], rows: [
      ["<strong>sin</strong>", "0", "1/2", "1/√2", "√3/2", "1"],
      ["<strong>cos</strong>", "1", "√3/2", "1/√2", "1/2", "0"],
      ["<strong>tan</strong>", "0", "1/√3", "1", "√3", "not defined"],
      ["<strong>cosec</strong>", "not defined", "2", "√2", "2/√3", "1"],
      ["<strong>sec</strong>", "1", "2/√3", "√2", "2", "not defined"],
      ["<strong>cot</strong>", "not defined", "√3", "1", "1/√3", "0"],
    ] },
    { t: "note", kind: "memory", title: "How to rebuild the table in ten seconds", html: "Write 0, 1, 2, 3, 4 across the top. Divide each by 4, then take the square root: 0, 1/2, 1/√2, √3/2, 1. That is the <strong>sin</strong> row. The <strong>cos</strong> row is the same list <em>reversed</em>. The <strong>tan</strong> row is sin ÷ cos. You never need to memorise the table itself." },
    { t: "note", kind: "trap", html: "tan 90° and sec 90° are <strong>not defined</strong>, because you would be dividing by cos 90° = 0. Likewise cot 0° and cosec 0° are not defined. Write &ldquo;not defined&rdquo;, never &ldquo;infinity&rdquo;." },

    { t: "h", text: "The identities" },
    { t: "formula", name: "The three identities",
      expr: "sin²A + cos²A = 1 &nbsp;·&nbsp; 1 + tan²A = sec²A &nbsp;·&nbsp; 1 + cot²A = cosec²A",
      where: ["Only the first is required by name in the syllabus, but all three are used constantly"] },
    { t: "note", kind: "why", title: "Proving sin²A + cos²A = 1", html: "In a right triangle with sides p (opposite), b (adjacent) and h (hypotenuse), Pythagoras gives p² + b² = h². Divide every term by h²: (p/h)² + (b/h)² = 1. But p/h is sin A and b/h is cos A, so sin²A + cos²A = 1. The identity <em>is</em> Pythagoras, rewritten." },
    { t: "note", kind: "idea", html: "The other two identities come from the same move. Divide p² + b² = h² by b² to get 1 + tan²A = sec²A; divide by p² to get cot²A + 1 = cosec²A. Three identities, one theorem." },

    { t: "h", text: "Proving identities — the technique" },
    { t: "p", html: "Most of the marks in this chapter come from &ldquo;prove that…&rdquo; questions. There is a reliable method." },
    { t: "list", ordered: true, items: [
      "Start with the <strong>more complicated side</strong> and work towards the simpler one. Never work on both sides at once.",
      "Convert everything into <strong>sin and cos</strong>. This alone solves a large fraction of them.",
      "Look for a chance to use sin²A + cos²A = 1, in either direction — you can replace 1 with sin²A + cos²A whenever it helps.",
      "If you see (1 − cos A) in a denominator, <strong>multiply top and bottom by (1 + cos A)</strong>. The difference of squares turns it into sin²A.",
      "Take LCMs to combine fractions before simplifying.",
    ] },
    { t: "steps", title: "Prove that (1 + sec A)/sec A = sin²A/(1 − cos A).",
      intro: "A typical three-mark identity. Start on the left, convert to sin and cos.",
      steps: [
        "LHS = (1 + sec A)/sec A. Write sec A as 1/cos A.",
        "= (1 + 1/cos A) / (1/cos A) = [(cos A + 1)/cos A] × [cos A/1] = <strong>1 + cos A</strong>.",
        "Now the RHS: sin²A/(1 − cos A). Replace sin²A using the identity: sin²A = 1 − cos²A.",
        "= (1 − cos²A)/(1 − cos A) = [(1 − cos A)(1 + cos A)]/(1 − cos A).",
        "Cancel (1 − cos A): RHS = <strong>1 + cos A</strong>.",
      ],
      answer: "LHS = RHS = 1 + cos A. ∎",
    },
    { t: "note", kind: "exam", html: "When both sides reduce to the same expression, say so explicitly — write &ldquo;LHS = RHS, hence proved&rdquo;. Examiners look for that closing line." },

    { t: "h", text: "Complementary angles" },
    { t: "formula", name: "Ratios of complementary angles",
      expr: "sin(90° − A) = cos A &nbsp;·&nbsp; cos(90° − A) = sin A &nbsp;·&nbsp; tan(90° − A) = cot A",
      where: ["Also sec(90° − A) = cosec A and cosec(90° − A) = sec A"] },
    { t: "note", kind: "why", html: "In a right triangle the two acute angles add to 90°. The side <em>opposite</em> one of them is <em>adjacent</em> to the other — so swapping the angle swaps sin and cos. That is the whole reason for the &ldquo;co&rdquo; in cosine." },
    { t: "steps", title: "Evaluate sin 25° · cos 65° + cos 25° · sin 65°.",
      intro: "Whenever the angles in a question add to 90°, reach for complementary angles.",
      steps: [
        "Notice that 25° + 65° = 90°, so the angles are complementary.",
        "Rewrite cos 65° as cos(90° − 25°) = sin 25°.",
        "Rewrite sin 65° as sin(90° − 25°) = cos 25°.",
        "The expression becomes sin 25°·sin 25° + cos 25°·cos 25° = sin²25° + cos²25°.",
      ],
      answer: "= 1, by the identity sin²A + cos²A = 1.",
    },
    { t: "note", kind: "memory", html: "Two useful facts about ranges: <strong>sin θ and cos θ never exceed 1</strong> (the hypotenuse is always the longest side), while sec θ and cosec θ are never <em>less</em> than 1. A question claiming sin θ = 3/2 has no solution, and saying so is the answer." },
  ],
  formulas: [
    { name: "Definitions", expr: "sin = opp/hyp, cos = adj/hyp, tan = opp/adj" },
    { name: "Reciprocals", expr: "cosec = 1/sin, sec = 1/cos, cot = 1/tan" },
    { name: "Quotient", expr: "tan θ = sin θ / cos θ, cot θ = cos θ / sin θ" },
    { name: "Pythagorean identity", expr: "sin²A + cos²A = 1" },
    { name: "Second identity", expr: "1 + tan²A = sec²A" },
    { name: "Third identity", expr: "1 + cot²A = cosec²A" },
    { name: "Complementary angles", expr: "sin(90°−A) = cos A, tan(90°−A) = cot A" },
  ],
  examFocus: [
    "The full value table at 0°, 30°, 45°, 60°, 90° — and the 0,1,2,3,4 trick for rebuilding it.",
    "Knowing which values are 'not defined' rather than infinite.",
    "The Pythagoras-based proof of sin²A + cos²A = 1.",
    "Identity proofs: work on one side, convert to sin and cos, and close with 'LHS = RHS'.",
    "The multiply-by-the-conjugate trick for (1 ± cos A) denominators.",
    "Spotting complementary angles whenever two angles in a question sum to 90°.",
    "That sin and cos can never exceed 1.",
  ],
  flashcards: [
    { q: "Define sin, cos and tan for an acute angle.", a: "sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent — all with respect to the angle θ in a right-angled triangle." },
    { q: "Why do the trigonometric ratios depend only on the angle, not the size of the triangle?", a: "Two right triangles with the same acute angle are similar by AA, so their corresponding sides are in the same ratio. The ratios therefore come out identical." },
    { q: "Which ratio is the reciprocal of which?", a: "cosec is the reciprocal of sin, sec is the reciprocal of cos, and cot is the reciprocal of tan. Note sec pairs with cos, not sin." },
    { q: "How do you rebuild the sin table quickly?", a: "Write 0, 1, 2, 3, 4; divide each by 4; take square roots. That gives 0, 1/2, 1/√2, √3/2, 1 for 0°, 30°, 45°, 60°, 90°. The cos row is the reverse, and tan is sin ÷ cos." },
    { q: "What is the value of tan 90°?", a: "Not defined. tan = sin/cos, and cos 90° = 0, so it would require division by zero. Write 'not defined', not 'infinity'." },
    { q: "Prove sin²A + cos²A = 1.", a: "In a right triangle with opposite p, adjacent b, hypotenuse h, Pythagoras gives p² + b² = h². Divide by h²: (p/h)² + (b/h)² = 1, which is sin²A + cos²A = 1." },
    { q: "State the other two Pythagorean identities.", a: "1 + tan²A = sec²A and 1 + cot²A = cosec²A. They come from dividing p² + b² = h² by b² and by p² respectively." },
    { q: "What is the standard technique for proving a trigonometric identity?", a: "Work on one side only — the more complicated one — convert everything to sin and cos, use sin²+cos²=1 where useful, and multiply by the conjugate to clear (1 ± cos A) denominators." },
    { q: "State the complementary angle relationships.", a: "sin(90°−A) = cos A, cos(90°−A) = sin A, tan(90°−A) = cot A, sec(90°−A) = cosec A." },
    { q: "Why are sin and cos of complementary angles swapped?", a: "The two acute angles of a right triangle add to 90°, and the side opposite one is adjacent to the other — so the roles of 'opposite' and 'adjacent' swap." },
    { q: "What is the maximum value of sin θ, and why?", a: "1. sin θ = opposite/hypotenuse, and the hypotenuse is always the longest side, so the ratio can never exceed 1." },
    { q: "Evaluate sin 30° · cos 60° + cos 30° · sin 60°.", a: "(1/2)(1/2) + (√3/2)(√3/2) = 1/4 + 3/4 = 1." },
    { q: "If tan A = 3/4, what is sin A?", a: "Opposite = 3, adjacent = 4, so hypotenuse = √(9+16) = 5. Therefore sin A = 3/5." },
  ],
  quiz: [
    { q: "The value of sin 30° is:", options: ["1/2", "√3/2", "1/√2", "1"], answer: 0, why: "From the standard table, sin 30° = 1/2. (Rebuild it with the 0,1,2,3,4 trick if you forget.)" },
    { q: "sec θ is the reciprocal of:", options: ["sin θ", "cos θ", "tan θ", "cot θ"], answer: 1, why: "sec θ = 1/cos θ. Read the third letter: se-c goes with cos." },
    { q: "The value of tan 90° is:", options: ["0", "1", "Infinity", "Not defined"], answer: 3, why: "tan 90° = sin 90°/cos 90° = 1/0, which is undefined. The correct written answer is 'not defined'." },
    { q: "If sin A = 3/5, then cos A is:", options: ["4/5", "5/3", "3/4", "5/4"], answer: 0, why: "sin²A + cos²A = 1, so cos²A = 1 − 9/25 = 16/25 and cos A = 4/5 (taking the positive value for an acute angle)." },
    { q: "sin(90° − θ) equals:", options: ["sin θ", "cos θ", "tan θ", "cosec θ"], answer: 1, why: "Complementary angles swap sine and cosine, so sin(90° − θ) = cos θ." },
    { q: "1 + tan²A equals:", options: ["sin²A", "cos²A", "sec²A", "cosec²A"], answer: 2, why: "This is the second Pythagorean identity, obtained by dividing p² + b² = h² by b²." },
    { q: "The value of sin²60° + cos²60° is:", options: ["1", "3/4", "1/4", "2"], answer: 0, why: "sin²A + cos²A = 1 for every angle A, so no calculation is needed." },
    { q: "If tan θ = 1, then θ (acute) is:", options: ["30°", "45°", "60°", "90°"], answer: 1, why: "tan 45° = 1, since the opposite and adjacent sides of a 45° right triangle are equal." },
    { q: "Which of these is impossible?", options: ["cos θ = 0.8", "sin θ = 1.4", "tan θ = 5", "sec θ = 2"], answer: 1, why: "sin θ can never exceed 1, because the opposite side can never be longer than the hypotenuse. tan and sec have no such upper limit." },
    { q: "cos 65° can be written as:", options: ["sin 25°", "sin 65°", "cos 25°", "tan 25°"], answer: 0, why: "cos 65° = cos(90° − 25°) = sin 25°." },
    { q: "The value of (1 − cos²A) is:", options: ["sin²A", "sec²A", "tan²A", "cot²A"], answer: 0, why: "Rearranging sin²A + cos²A = 1 gives sin²A = 1 − cos²A." },
    { q: "If 3 cot A = 4, then cosec²A equals:", options: ["25/9", "16/9", "25/16", "9/16"], answer: 0, why: "cot A = 4/3, so cot²A = 16/9. Then cosec²A = 1 + cot²A = 1 + 16/9 = 25/9." },
  ],
};
