import type { Chapter } from "@/lib/types";

export const ch09: Chapter = {
  slug: "applications-of-trigonometry",
  num: 9,
  title: "Some Applications of Trigonometry",
  unit: "trig",
  unitName: "Trigonometry",
  marks: "Unit V · 12 marks",
  minutes: 16,
  blurb: "Measuring the height of a tower without climbing it. Every question here is one right triangle — or at most two.",
  bigIdea: "You can find a length you cannot reach by measuring an angle you can. That is the entire practical point of trigonometry.",
  syllabus: [
    "Simple problems on heights and distances",
    "Problems should not involve more than two right triangles",
    "Angles of elevation and depression only of 30°, 45° and 60°",
  ],
  blocks: [
    { t: "h", text: "Elevation and depression" },
    { t: "sim", id: "heights-distances" },
    { t: "list", items: [
      "The <strong>line of sight</strong> is the straight line from the observer's eye to the object.",
      "The <strong>angle of elevation</strong> is the angle between the line of sight and the horizontal, when the object is <em>above</em> eye level — you look up.",
      "The <strong>angle of depression</strong> is the same thing when the object is <em>below</em> eye level — you look down.",
    ] },
    { t: "note", kind: "trap", html: "Both angles are always measured from the <strong>horizontal</strong>, never from the vertical. A very common diagram error is marking the angle against the tower instead of against the ground." },
    { t: "note", kind: "idea", title: "The fact that saves you", html: "The angle of depression from the top of a tower to a point on the ground <strong>equals</strong> the angle of elevation from that point up to the top. They are alternate angles between two parallel horizontals. So whenever a question gives you a depression angle, you can immediately redraw it inside the triangle as an elevation angle — which is usually where you need it." },

    { t: "h", text: "The method, in order" },
    { t: "list", ordered: true, items: [
      "<strong>Draw the diagram.</strong> Mark the right angle, the given angle at the correct vertex, and label every length you know and the one you want. Marks are given for a correct figure.",
      "<strong>Pick the ratio</strong> that connects what you know to what you want. If you have the base and want the height, use tan. If you have the hypotenuse, use sin or cos.",
      "<strong>Substitute the exact value</strong> — √3, 1/√3, 1 — rather than a decimal.",
      "<strong>Rationalise</strong> the denominator at the end, and state the units.",
    ] },
    { t: "table", head: ["You know", "You want", "Use"], rows: [
      ["Base (horizontal distance)", "Height", "<strong>tan</strong> θ = height / base"],
      ["Height", "Base", "<strong>tan</strong> θ, rearranged"],
      ["Hypotenuse (line of sight)", "Height", "<strong>sin</strong> θ = height / hypotenuse"],
      ["Hypotenuse", "Base", "<strong>cos</strong> θ = base / hypotenuse"],
    ] },
    { t: "note", kind: "memory", html: "Nine times out of ten the answer is <strong>tan</strong>, because these problems give you a horizontal distance along the ground and ask for a vertical height. Reach for tan first and check whether it fits." },

    { t: "steps", title: "A tower stands vertically. From a point 15 m away, the angle of elevation of its top is 60°. Find the height.",
      intro: "The single-triangle case — two marks, thirty seconds.",
      steps: [
        "Draw the tower AB with B on the ground, and the observation point C with BC = 15 m and ∠ACB = 60°.",
        "We know the base and want the height, so use tan: tan 60° = AB / BC.",
        "Substitute the exact value: √3 = AB / 15.",
        "So AB = 15√3.",
      ],
      answer: "Height = 15√3 m ≈ 25.98 m.",
    },

    { t: "h", text: "Two-triangle problems" },
    { t: "p", html: "The syllabus allows at most two right triangles. They almost always share a side — usually the height — and that shared side is what lets you eliminate the unknown." },
    { t: "steps", title: "The angle of elevation of the top of a tower from a point is 30°. On walking 40 m towards the tower, it becomes 60°. Find the height.",
      intro: "The classic two-triangle problem. Call the height h and set up two equations.",
      steps: [
        "Let the height be h and let the nearer point be at distance x from the foot. The farther point is then at (x + 40).",
        "From the near point: tan 60° = h/x, so √3 = h/x, giving <strong>x = h/√3</strong>.",
        "From the far point: tan 30° = h/(x + 40), so 1/√3 = h/(x + 40), giving <strong>x + 40 = h√3</strong>.",
        "Substitute the first into the second: h/√3 + 40 = h√3.",
        "Multiply through by √3: h + 40√3 = 3h, so 40√3 = 2h.",
      ],
      answer: "h = 20√3 m ≈ 34.64 m.",
    },
    { t: "note", kind: "exam", html: "Notice the structure: express the shared unknown (x) from the easier equation, then substitute. Trying to solve both equations from scratch usually leads into algebra you do not need." },

    { t: "h", text: "The situations that keep recurring" },
    { t: "list", items: [
      "<strong>A broken tree.</strong> The trunk snaps and the top touches the ground, forming a triangle. The <em>original height</em> is the standing part plus the broken part — and the broken part is the hypotenuse, so remember to add both.",
      "<strong>Two buildings.</strong> Angles of elevation and depression from the top of one to the top and bottom of the other. The horizontal distance between them is shared by both triangles.",
      "<strong>An observer of given height.</strong> If the observer is 1.5 m tall, work with the height <em>above eye level</em> and add 1.5 m at the very end. Forgetting to add it back is the most common mistake in the chapter.",
      "<strong>A moving object.</strong> A boat or an aeroplane observed at two times; the distance travelled is the difference between the two horizontal distances.",
      "<strong>Shadows.</strong> The shadow length is the base of the triangle and the sun's elevation is the angle.",
    ] },
    { t: "note", kind: "real", html: "This is genuinely how heights get measured. A surveyor's theodolite measures exactly one thing — an angle — and the height of a mountain, a building or a transmission mast follows from a tan calculation on paper." },
    { t: "note", kind: "memory", html: "Useful decimal approximations for the final line: <strong>√3 ≈ 1.732</strong> and <strong>√2 ≈ 1.414</strong>. Give the exact surd form first, then the decimal — that way you keep the mark even if the arithmetic slips." },
  ],
  formulas: [
    { name: "Height from base and elevation", expr: "h = d · tan θ" },
    { name: "Base from height and elevation", expr: "d = h / tan θ" },
    { name: "Using the line of sight", expr: "h = (line of sight) · sin θ" },
    { name: "Key equality", expr: "angle of depression = angle of elevation (alternate angles)" },
    { name: "Useful values", expr: "√3 ≈ 1.732, √2 ≈ 1.414" },
  ],
  examFocus: [
    "Drawing a correct labelled figure — it carries marks on its own.",
    "Measuring elevation and depression from the horizontal, never the vertical.",
    "The equality of the angle of depression and the corresponding angle of elevation.",
    "Choosing tan by default, and sin or cos when the hypotenuse is involved.",
    "The two-triangle method: express the shared unknown from one equation and substitute.",
    "Adding the observer's height back at the end.",
    "Leaving answers in exact surd form, then converting.",
  ],
  flashcards: [
    { q: "What is the angle of elevation?", a: "The angle between the horizontal and the line of sight when the object being viewed is above the observer's eye level." },
    { q: "What is the angle of depression?", a: "The angle between the horizontal and the line of sight when the object is below the observer's eye level." },
    { q: "How are the angle of elevation and the angle of depression related?", a: "The angle of depression from the top of a tower to a point equals the angle of elevation from that point to the top — they are alternate angles between parallel horizontal lines." },
    { q: "Which ratio do you usually need in heights-and-distances problems?", a: "tan, because these problems normally give a horizontal distance along the ground and ask for a vertical height." },
    { q: "When would you use sin rather than tan?", a: "When the line of sight (the hypotenuse) is given or required, since sin θ = height / hypotenuse." },
    { q: "A tower's angle of elevation from 15 m away is 60°. What is its height?", a: "tan 60° = h/15, so √3 = h/15 and h = 15√3 ≈ 25.98 m." },
    { q: "How do you handle a problem where the observer has a stated height?", a: "Work out the height above the observer's eye level using the triangle, then add the observer's height at the very end to get the full height." },
    { q: "In a broken-tree problem, what is the original height of the tree?", a: "The height of the standing part plus the length of the broken part. The broken part is the hypotenuse of the triangle, so it must be found separately." },
    { q: "How do you approach a two-triangle problem?", a: "Both triangles share a side, usually the height. Write an equation from each, express the shared unknown from the simpler one, and substitute into the other." },
    { q: "At what angle of elevation does the height of an object equal its distance from the observer?", a: "45°, because tan 45° = 1, so h = d." },
    { q: "What approximations should you know for the final answer?", a: "√3 ≈ 1.732 and √2 ≈ 1.414. Give the exact surd form first, then the decimal value." },
    { q: "Why must the angle be measured from the horizontal?", a: "Because that is how elevation and depression are defined. Measuring from the vertical gives the complementary angle and every subsequent ratio is wrong." },
  ],
  quiz: [
    { q: "The angle of elevation is measured from:", options: ["The vertical", "The horizontal", "The line of sight", "The object"], answer: 1, why: "Both elevation and depression are always measured between the line of sight and the horizontal." },
    { q: "A pole 10 m high casts a shadow 10 m long. The sun's elevation is:", options: ["30°", "45°", "60°", "90°"], answer: 1, why: "tan θ = 10/10 = 1, and tan 45° = 1, so the elevation is 45°." },
    { q: "The angle of elevation of the top of a tower from 30 m away is 30°. Its height is:", options: ["10√3 m", "30√3 m", "15 m", "10 m"], answer: 0, why: "tan 30° = h/30, so 1/√3 = h/30, giving h = 30/√3 = 10√3 m." },
    { q: "The angle of depression from the top of a building to a car equals:", options: ["The angle of elevation from the car to the top", "Twice that angle", "90° minus that angle", "Nothing in particular"], answer: 0, why: "They are alternate angles formed by the line of sight cutting two parallel horizontal lines, so they are equal." },
    { q: "If the angle of elevation of the sun increases, the length of a pole's shadow:", options: ["Increases", "Decreases", "Stays the same", "Becomes zero"], answer: 1, why: "Shadow length = h/tan θ. As θ increases, tan θ increases, so the shadow gets shorter — which is why shadows are shortest at noon." },
    { q: "A ladder 10 m long leans against a wall at 60° to the ground. It reaches a height of:", options: ["5 m", "5√3 m", "10√3 m", "10/√3 m"], answer: 1, why: "The ladder is the hypotenuse, so use sin: sin 60° = h/10, giving h = 10 × √3/2 = 5√3 m." },
    { q: "In a two-triangle problem, the two triangles usually share:", options: ["The same angle", "The height", "The hypotenuse", "Nothing"], answer: 1, why: "The vertical height is common to both, and eliminating it between the two equations is what solves the problem." },
    { q: "An observer 1.5 m tall finds the height above eye level to be 28.5 m. The full height of the tower is:", options: ["27 m", "28.5 m", "30 m", "1.5 m"], answer: 2, why: "Add the observer's height back: 28.5 + 1.5 = 30 m. Forgetting this step is the most common error in the chapter." },
    { q: "The angles of elevation and depression in the syllabus are restricted to:", options: ["0°, 45°, 90°", "30°, 45°, 60°", "Any angle", "15°, 30°, 45°"], answer: 1, why: "CBSE restricts these problems to 30°, 45° and 60°, whose exact ratios you already know." },
    { q: "A tree breaks and its top touches the ground 8 m from the base, making a 30° angle. The broken part is:", options: ["8 m", "16/√3 m", "4 m", "8√3 m"], answer: 1, why: "The broken part is the hypotenuse. cos 30° = 8/hyp, so hyp = 8/cos 30° = 8/(√3/2) = 16/√3 m." },
    { q: "The height of a tower is √3 times the length of its shadow. The sun's elevation is:", options: ["30°", "45°", "60°", "75°"], answer: 2, why: "tan θ = h/shadow = √3, and tan 60° = √3." },
    { q: "Which is the best first step in any heights-and-distances problem?", options: ["Substitute √3 ≈ 1.732", "Draw and label a clear figure", "Guess the ratio", "Convert to radians"], answer: 1, why: "A correct labelled figure carries marks in itself and makes the choice of ratio obvious." },
  ],
};
