import type { Chapter } from "@/lib/types";

export const ch10: Chapter = {
  slug: "circles",
  num: 10,
  title: "Circles",
  unit: "geometry",
  unitName: "Geometry",
  marks: "Unit IV · 15 marks",
  minutes: 16,
  blurb: "Two theorems, both of which you must be able to prove, and both of which say something obvious once you have seen the picture.",
  bigIdea: "A tangent touches a circle at exactly one point, and at that point it is perpendicular to the radius. Almost every circle question in the paper comes back to that right angle.",
  syllabus: [
    "Tangent to a circle at the point of contact",
    "Proof: the tangent at any point of a circle is perpendicular to the radius through the point of contact",
    "Proof: the lengths of tangents drawn from an external point to a circle are equal",
  ],
  blocks: [
    { t: "h", text: "Secant and tangent" },
    { t: "table", head: ["Line", "How many points it shares with the circle", "Called"], rows: [
      ["Passes right through", "Two", "<strong>Secant</strong>"],
      ["Just touches", "One", "<strong>Tangent</strong>"],
      ["Misses entirely", "Zero", "Non-intersecting line"],
    ] },
    { t: "note", kind: "idea", html: "A tangent is what a secant becomes in the limit. Slide a secant outwards and its two intersection points move closer together; the moment they merge into one, the line has become a tangent. That single shared point is the <strong>point of contact</strong>." },
    { t: "note", kind: "exam", html: "Counting facts that get asked directly: a circle has <strong>infinitely many</strong> tangents (one at every point). From a point <strong>inside</strong> the circle there are <strong>no</strong> tangents. From a point <strong>on</strong> the circle there is exactly <strong>one</strong>. From a point <strong>outside</strong> there are exactly <strong>two</strong>." },

    { t: "h", text: "Theorem 1 — tangent ⊥ radius" },
    { t: "sim", id: "circle-tangents" },
    { t: "formula", name: "Theorem 1",
      expr: "The tangent at any point of a circle is perpendicular to the radius through the point of contact." },
    { t: "steps", title: "Prove that the tangent is perpendicular to the radius at the point of contact.",
      intro: "A proof by contradiction, and one of the two the syllabus requires in full.",
      steps: [
        "Let XY be a tangent to a circle with centre O, touching it at P. We must show OP ⊥ XY.",
        "Take any point Q on XY <em>other</em> than P. Since XY is a tangent, it meets the circle only at P — so <strong>Q lies outside</strong> the circle.",
        "Therefore <strong>OQ &gt; OP</strong>, because OP is a radius and Q is beyond the circle.",
        "This is true for <em>every</em> point Q on the line except P. So OP is the <strong>shortest</strong> distance from O to the line XY.",
        "But the shortest distance from a point to a line is always the perpendicular distance.",
      ],
      answer: "Therefore OP ⊥ XY. ∎",
    },
    { t: "note", kind: "memory", html: "The whole proof hangs on one idea: <strong>the shortest distance from a point to a line is the perpendicular</strong>. If you remember that sentence you can reconstruct the argument." },

    { t: "h", text: "Theorem 2 — equal tangents from an external point" },
    { t: "formula", name: "Theorem 2",
      expr: "The lengths of the two tangents drawn from an external point to a circle are equal.",
      where: ["If PA and PB are tangents from P, then <strong>PA = PB</strong>"] },
    { t: "steps", title: "Prove that tangents from an external point are equal.",
      intro: "A congruence proof. Notice that Theorem 1 is used inside it — that is why the order matters.",
      steps: [
        "Let PA and PB be tangents from an external point P to a circle with centre O. Join OA, OB and OP.",
        "By <strong>Theorem 1</strong>, OA ⊥ PA and OB ⊥ PB, so ∠OAP = ∠OBP = 90°.",
        "Now compare △OAP and △OBP. <strong>OA = OB</strong> (both radii).",
        "<strong>OP = OP</strong> (common hypotenuse).",
        "Both triangles are right-angled, so by the <strong>RHS</strong> congruence rule, △OAP ≅ △OBP.",
        "Corresponding parts of congruent triangles are equal, so PA = PB.",
      ],
      answer: "Hence the two tangents are equal in length. ∎ (It also follows that ∠OPA = ∠OPB — OP bisects the angle between the tangents.)",
    },
    { t: "note", kind: "idea", title: "Two free extras", html: "The same congruence gives you two more results that questions often need: <strong>OP bisects ∠APB</strong>, and <strong>OP bisects ∠AOB</strong>. And since OAPB has two right angles, <strong>∠APB + ∠AOB = 180°</strong> — the angle at the external point and the angle at the centre are supplementary." },

    { t: "h", text: "Working with tangent lengths" },
    { t: "formula", name: "Length of a tangent", expr: "PA = √(OP² − r²)",
      where: ["P is external, O the centre, r the radius", "Straight from Pythagoras in the right triangle OAP"] },
    { t: "steps", title: "A tangent from a point P touches a circle of radius 5 cm at A. If OP = 13 cm, find PA.",
      intro: "One mark, if you spot the right angle.",
      steps: [
        "OA is a radius, PA a tangent, so ∠OAP = 90° by Theorem 1.",
        "△OAP is right-angled at A, so Pythagoras applies: OP² = OA² + PA².",
        "Substitute: 13² = 5² + PA², so 169 = 25 + PA².",
        "PA² = 144.",
      ],
      answer: "PA = 12 cm.",
    },
    { t: "note", kind: "memory", html: "Watch for Pythagorean triples in these questions — <strong>3-4-5</strong>, <strong>5-12-13</strong>, <strong>8-15-17</strong> and <strong>7-24-25</strong>. Examiners choose them deliberately so the arithmetic is clean, and spotting one saves time." },

    { t: "h", text: "The quadrilateral result worth knowing" },
    { t: "p", html: "If a quadrilateral ABCD has a circle inscribed in it, touching all four sides, then the tangent lengths from each vertex are equal — and adding them up gives a neat result." },
    { t: "formula", name: "Circumscribed quadrilateral", expr: "AB + CD = BC + AD",
      where: ["The two pairs of opposite sides have equal sums"] },
    { t: "note", kind: "why", html: "Label the tangent lengths from A, B, C, D as p, q, r, s. Then AB = p + q, BC = q + r, CD = r + s and AD = s + p. So AB + CD = p + q + r + s and BC + AD = q + r + s + p. The same four letters — hence equal." },
    { t: "note", kind: "exam", html: "For a parallelogram circumscribing a circle, this forces AB + CD = BC + AD; since opposite sides of a parallelogram are already equal, that gives 2AB = 2BC, so <strong>every parallelogram circumscribing a circle is a rhombus</strong>. That exact question is set regularly." },
  ],
  formulas: [
    { name: "Theorem 1", expr: "Tangent ⊥ radius at the point of contact" },
    { name: "Theorem 2", expr: "Tangents from an external point are equal: PA = PB" },
    { name: "Length of tangent", expr: "PA = √(OP² − r²)" },
    { name: "Supplementary angles", expr: "∠APB + ∠AOB = 180°" },
    { name: "Circumscribed quadrilateral", expr: "AB + CD = BC + AD" },
  ],
  examFocus: [
    "Both proofs in full — they are explicitly named in the syllabus.",
    "The 'shortest distance is the perpendicular' step in Theorem 1.",
    "Using RHS congruence in Theorem 2, and the extras it gives (OP bisects both angles).",
    "Counting tangents from a point inside, on, and outside the circle.",
    "PA = √(OP² − r²) and recognising Pythagorean triples.",
    "AB + CD = BC + AD, and the parallelogram-is-a-rhombus consequence.",
  ],
  flashcards: [
    { q: "What is a tangent to a circle?", a: "A line that touches the circle at exactly one point, called the point of contact." },
    { q: "What is a secant?", a: "A line that intersects the circle at two distinct points. A tangent is the limiting case where those two points merge into one." },
    { q: "How many tangents can be drawn from a point inside, on, and outside a circle?", a: "Inside: none. On the circle: exactly one. Outside: exactly two." },
    { q: "State Theorem 1 for circles.", a: "The tangent at any point of a circle is perpendicular to the radius through the point of contact." },
    { q: "Prove that the tangent is perpendicular to the radius.", a: "Every point Q on the tangent other than the point of contact P lies outside the circle, so OQ > OP. Hence OP is the shortest distance from O to the line, and the shortest distance from a point to a line is the perpendicular. So OP ⊥ tangent." },
    { q: "State Theorem 2 for circles.", a: "The lengths of the two tangents drawn from an external point to a circle are equal." },
    { q: "Prove that tangents from an external point are equal.", a: "In △OAP and △OBP: ∠OAP = ∠OBP = 90° (Theorem 1), OA = OB (radii), OP common. By RHS the triangles are congruent, so PA = PB by CPCT." },
    { q: "What two extra results follow from the proof of Theorem 2?", a: "OP bisects ∠APB and OP bisects ∠AOB. Also ∠APB + ∠AOB = 180°." },
    { q: "How do you find the length of a tangent from an external point?", a: "PA = √(OP² − r²), using Pythagoras in the right triangle formed by the radius, the tangent and the line to the centre." },
    { q: "For a quadrilateral circumscribing a circle, what is the relationship between its sides?", a: "AB + CD = BC + AD — the sums of the two pairs of opposite sides are equal." },
    { q: "Why is a parallelogram circumscribing a circle always a rhombus?", a: "AB + CD = BC + AD, and in a parallelogram AB = CD and BC = AD. So 2AB = 2BC, giving AB = BC — all four sides are equal." },
    { q: "What is the angle between two tangents from an external point, if the angle at the centre is 110°?", a: "70°, since ∠APB + ∠AOB = 180°." },
  ],
  quiz: [
    { q: "A tangent to a circle intersects it at:", options: ["Two points", "One point", "No point", "Three points"], answer: 1, why: "By definition a tangent touches the circle at exactly one point — the point of contact." },
    { q: "How many tangents can be drawn to a circle from a point inside it?", options: ["0", "1", "2", "Infinitely many"], answer: 0, why: "Any line through an interior point must cut the circle at two points, so it is a secant, never a tangent." },
    { q: "The angle between a tangent and the radius at the point of contact is:", options: ["45°", "60°", "90°", "180°"], answer: 2, why: "This is Theorem 1 — the tangent is perpendicular to the radius at the point of contact." },
    { q: "PA and PB are tangents from P to a circle. If PA = 7 cm, then PB is:", options: ["7 cm", "14 cm", "3.5 cm", "Cannot be determined"], answer: 0, why: "Tangents from an external point are equal in length, so PB = PA = 7 cm." },
    { q: "A tangent PA touches a circle of radius 8 cm, with OP = 17 cm. PA equals:", options: ["9 cm", "15 cm", "25 cm", "12 cm"], answer: 1, why: "PA = √(OP² − r²) = √(289 − 64) = √225 = 15 cm. (An 8-15-17 triple.)" },
    { q: "If the angle between two tangents from an external point is 60°, the angle subtended at the centre is:", options: ["60°", "90°", "120°", "150°"], answer: 2, why: "∠APB + ∠AOB = 180°, so ∠AOB = 180 − 60 = 120°." },
    { q: "The proof that the tangent is perpendicular to the radius relies on:", options: ["Congruent triangles", "The shortest distance from a point to a line being the perpendicular", "Similar triangles", "The angle sum property"], answer: 1, why: "Every other point on the tangent lies outside the circle, so OP is the shortest such distance — and the shortest distance is the perpendicular." },
    { q: "Which congruence rule proves that tangents from an external point are equal?", options: ["SSS", "SAS", "ASA", "RHS"], answer: 3, why: "The two triangles are right-angled, share the hypotenuse OP, and have equal radii — that is RHS." },
    { q: "A quadrilateral ABCD circumscribes a circle. If AB = 6, BC = 7 and CD = 4, then AD is:", options: ["3", "5", "9", "8"], answer: 0, why: "AB + CD = BC + AD, so 6 + 4 = 7 + AD, giving AD = 3." },
    { q: "A parallelogram circumscribing a circle must be a:", options: ["Rectangle", "Rhombus", "Square", "Trapezium"], answer: 1, why: "AB + CD = BC + AD combined with opposite sides being equal forces all four sides to be equal — a rhombus." },
    { q: "The number of tangents that can be drawn to a circle is:", options: ["1", "2", "4", "Infinitely many"], answer: 3, why: "There is exactly one tangent at every point of the circle, and there are infinitely many points." },
    { q: "In the figure of two tangents from P, the line OP:", options: ["Bisects ∠APB only", "Bisects ∠AOB only", "Bisects both ∠APB and ∠AOB", "Bisects neither"], answer: 2, why: "The congruence △OAP ≅ △OBP makes the corresponding angles at both P and O equal, so OP bisects both." },
  ],
  keyTopics: [
    { name: "Theorem 1 — tangent ⊥ radius at the point of contact (full proof)", importance: "high", note: "Explicitly named in the syllabus; the 'shortest distance is the perpendicular' argument must be reproduced exactly." },
    { name: "Theorem 2 — tangents from an external point are equal (full proof)", importance: "high", note: "An RHS congruence built on Theorem 1; also gives the angle-bisector and supplementary-angle extras." },
    { name: "Length of a tangent, PA = √(OP² − r²)", importance: "high", note: "Almost always a clean Pythagorean triple — 3-4-5, 5-12-13, 6-8-10, 7-24-25." },
    { name: "Circumscribed quadrilateral: AB + CD = BC + AD", importance: "high", note: "Leads to the classic 'a parallelogram circumscribing a circle is a rhombus' proof." },
    { name: "Two-tangent theorem consequences (angle bisectors, supplementary angles)", importance: "medium", note: "∠APB + ∠AOB = 180°, and OP bisects both ∠APB and ∠AOB." },
    { name: "Counting tangents from points inside, on, and outside a circle", importance: "low", note: "0 from inside, 1 on the circle, 2 from outside — a reliable 1-mark and assertion–reason topic." },
    { name: "Combined tangent-length and altitude-style problems (chords tangent to a smaller circle, etc.)", importance: "medium", note: "Often reuses the same 'altitude to hypotenuse' similar-triangles idea from the Triangles chapter." },
  ],
  written: [
    { q: "How many tangents can be drawn to a circle from a point lying on the circle?", marks: 1, kind: "short", importance: "medium",
      answer: "Exactly <strong>one</strong> tangent — the tangent at that very point." },
    { q: "A tangent PQ touches a circle of radius 6 cm at a point, and meets a line through the centre O at Q such that OQ = 10 cm. Find PQ.", marks: 1, kind: "numerical", importance: "high",
      answer: "Since the tangent is ⊥ to the radius at the point of contact, Pythagoras gives PQ = √(OQ² − r²) = √(10² − 6²) = √(100−36) = √64 = <strong>8 cm</strong> (a 6-8-10 triple)." },
    { q: "State the theorem relating a tangent to a circle and the radius at the point of contact.", marks: 2, kind: "short", importance: "high",
      answer: "<strong>The tangent at any point of a circle is perpendicular to the radius through the point of contact.</strong>" },
    { q: "PA and PB are tangents from an external point P to a circle with centre O. If ∠APB = 70°, find ∠AOB.", marks: 2, kind: "numerical", importance: "high",
      answer: "In quadrilateral OAPB, ∠OAP = ∠OBP = 90° (tangent ⊥ radius), so the remaining two angles are supplementary: ∠APB + ∠AOB = 180°.<br>∠AOB = 180° − 70° = <strong>110°</strong>." },
    { q: "A quadrilateral ABCD circumscribes a circle. If AB = 7 cm, BC = 8 cm and CD = 5 cm, find AD.", marks: 2, kind: "numerical", importance: "high",
      answer: "For a quadrilateral circumscribing a circle, AB + CD = BC + AD.<br>7 + 5 = 8 + AD ⇒ 12 = 8 + AD ⇒ AD = <strong>4 cm</strong>." },
    { q: "Prove that a parallelogram circumscribing a circle is a rhombus.", marks: 3, kind: "long", importance: "high",
      answer: "Let parallelogram ABCD circumscribe a circle, touching AB, BC, CD, DA at P, Q, R, S. Let the tangent lengths from A, B, C, D be p, q, r, s respectively (by the two-tangent theorem, AP = AS = p, BP = BQ = q, CQ = CR = r, DR = DS = s).<br>AB = p+q, BC = q+r, CD = r+s, DA = s+p.<br>AB + CD = p+q+r+s = BC + DA, so <strong>AB + CD = BC + DA</strong> for any tangential quadrilateral.<br>Since ABCD is a parallelogram, AB = CD and BC = DA. Substituting: AB + AB = BC + BC ⇒ 2AB = 2BC ⇒ AB = BC.<br>So AB = BC = CD = DA — <strong>all four sides are equal, hence ABCD is a rhombus. ∎</strong>" },
    { q: "Two concentric circles have radii 5 cm and 3 cm. Find the length of a chord of the larger circle which touches the smaller circle.", marks: 3, kind: "numerical", importance: "high",
      answer: "The chord is tangent to the smaller circle, so the perpendicular distance from the common centre O to the chord equals the smaller radius, 3 cm. This perpendicular bisects the chord.<br>Half-chord = √(R² − r²) = √(5² − 3²) = √(25−9) = √16 = 4 cm.<br>Full chord length = 2 × 4 = <strong>8 cm</strong>." },
    { q: "PQ is a chord of length 8 cm of a circle of radius 5 cm. The tangents at P and Q meet at a point T. Find the length TP.", marks: 3, kind: "numerical", importance: "high",
      answer: "Let M be the midpoint of PQ; OM ⊥ PQ and PM = 4 cm. OM = √(OP² − PM²) = √(25−16) = 3 cm.<br>Since TP = TQ, T lies on line OM extended, so O, M, T are collinear, and PM ⊥ OT — making PM the altitude to the hypotenuse OT in right triangle OPT (right-angled at P).<br>By the geometric-mean relation: OP² = OM × OT ⇒ 25 = 3 × OT ⇒ OT = 25/3.<br>Also PT² = MT × OT, where MT = OT − OM = 25/3 − 3 = 16/3.<br>PT² = (16/3)(25/3) = 400/9 ⇒ PT = <strong>20/3 cm ≈ 6.67 cm</strong>." },
    { q: "Prove that the lengths of tangents drawn from an external point to a circle are equal. Using this result, if two tangents PA and PB are drawn from an external point P such that ∠APB = 80°, find ∠POA (O is the centre).", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Proof:</strong> Join OA, OB, OP. By Theorem 1, OA ⊥ PA and OB ⊥ PB, so ∠OAP = ∠OBP = 90°. In △OAP and △OBP: OA = OB (radii), OP = OP (common), and both are right-angled. By RHS, △OAP ≅ △OBP, so <strong>PA = PB</strong> by CPCT. (It also follows that OP bisects both ∠APB and ∠AOB.)<br><strong>Application:</strong> Since OP bisects ∠APB, ∠OPA = 80°/2 = 40°. In right triangle OAP (right angle at A), the other two angles sum to 90°: ∠OPA + ∠POA = 90° ⇒ ∠POA = 90° − 40° = <strong>50°</strong>. (Check: ∠AOB = 180° − 80° = 100°, and OP bisects it too, giving ∠POA = 50° — consistent.)" },
    { q: "Prove that the tangent at any point of a circle is perpendicular to the radius through the point of contact. Using this result, find the length of the tangent drawn from a point P, 25 cm from the centre O of a circle of radius 7 cm.", marks: 5, kind: "long", importance: "high",
      answer: "<strong>Proof:</strong> Let XY be a tangent touching the circle at P, centre O. Take any point Q on XY other than P; since XY meets the circle only at P, Q lies outside the circle, so OQ &gt; OP. This holds for every point on XY except P, so OP is the <strong>shortest</strong> distance from O to the line XY. Since the shortest distance from a point to a line is always the perpendicular distance, <strong>OP ⊥ XY. ∎</strong><br><strong>Application:</strong> The tangent length PA satisfies PA² = OP² − r² (Pythagoras, since OA ⊥ PA).<br>PA² = 25² − 7² = 625 − 49 = 576 ⇒ PA = <strong>24 cm</strong> (a 7-24-25 triple)." },
  ],
  assertionReason: [
    { assertion: "The tangents drawn at the two ends of a diameter of a circle are parallel to each other.",
      reason: "The tangent to a circle is perpendicular to the radius at the point of contact, and the two radii to the ends of a diameter lie along the same straight line.",
      answer: 0, importance: "high",
      why: "Both are true. Since the two radii are collinear (opposite ends of one straight diameter) and each tangent is perpendicular to its own radius, both tangents are perpendicular to the same line and hence parallel to each other." },
    { assertion: "PA and PB are tangents from an external point P, and ∠AOB = 100°. Then ∠APB = 100°.",
      reason: "In quadrilateral OAPB, the four angles sum to 360°, and the angles at A and B are each 90°.",
      answer: 3, importance: "high",
      why: "R is a true general fact, and it actually gives ∠APB = 360° − 90° − 90° − 100° = 80°, not 100°. So A is false while R is true." },
    { assertion: "From a point inside a circle, exactly one tangent can be drawn to the circle.",
      reason: "Every line through an interior point of a circle meets the circle at exactly two points, making it a secant rather than a tangent.",
      answer: 3, importance: "medium",
      why: "A is false — from an interior point, <strong>no</strong> tangent can be drawn (every line through it is a secant). R is true, and in fact it is the very reason A is false." },
    { assertion: "A line drawn perpendicular to a radius, at the point where the radius meets the circle, is a tangent to that circle.",
      reason: "Any other line through that point, not perpendicular to the radius, would pass inside the circle and cut it again, making it a secant.",
      answer: 0, importance: "medium",
      why: "Both are true — this is the converse of Theorem 1, and R correctly explains why only the perpendicular line avoids cutting the circle a second time." },
  ],
  caseStudies: [
    { title: "A circular pond and its fence", importance: "high",
      source: "A circular pond of radius 9 m stands at the centre of a park. A straight fence, tangent to the pond's boundary, is anchored at a post P that is 15 m from the centre O of the pond.",
      parts: [
        { q: "What is the angle between the fence and the radius at the point of contact?", marks: 1, answer: "<strong>90°</strong>, by the theorem that a tangent is perpendicular to the radius at the point of contact." },
        { q: "Find the length of fence from P to the point where it touches the pond.", marks: 2, answer: "PA = √(OP² − r²) = √(15² − 9²) = √(225−81) = √144 = <strong>12 m</strong> (a 9-12-15 triple)." },
        { q: "A second fence-post P′ is placed exactly 9 m from the centre. How many tangents can be drawn from P′ to the pond's boundary, and why?", marks: 1, answer: "Since 9 m equals the radius, P′ lies <strong>on</strong> the circle, so exactly <strong>one</strong> tangent can be drawn from it." },
        { q: "Two tangent fences are drawn from the original post P, touching the pond at two points. What can you say about their lengths?", marks: 1, answer: "They are <strong>equal</strong> (each 12 m), by the theorem that tangents drawn from an external point to a circle are equal in length." },
      ] },
    { title: "A rangoli with an inscribed circle", importance: "medium",
      source: "For a festival, Meera draws a circular rangoli and borders it with a quadrilateral floral pattern ABCD such that the circle touches all four sides. She measures AB = 9 cm, BC = 7 cm and CD = 6 cm.",
      parts: [
        { q: "State the theorem that lets Meera find the fourth side AD without measuring it.", marks: 1, answer: "For any quadrilateral circumscribing a circle, <strong>AB + CD = BC + AD</strong> (the sums of opposite sides are equal)." },
        { q: "Find AD.", marks: 2, answer: "9 + 6 = 7 + AD ⇒ 15 = 7 + AD ⇒ AD = <strong>8 cm</strong>." },
        { q: "Find the perimeter of the floral border ABCD.", marks: 1, answer: "Perimeter = 9 + 7 + 6 + 8 = <strong>30 cm</strong>." },
      ] },
  ],
};
