import type { Chapter } from "@/lib/types";

export const ch10: Chapter = {
  slug: "circles",
  num: 10,
  title: "Circles",
  unit: "geometry",
  unitName: "Geometry",
  marks: "Unit IV · 15 marks",
  minutes: 16,
  blurb: "Two theorems, both of which you must be able to prove, and both of which say something obvious once you have seen the picture.",
  bigIdea: "A tangent touches a circle at exactly one point, and at that point it is perpendicular to the radius. Almost every circle question in the paper comes back to that right angle.",
  syllabus: [
    "Tangent to a circle at the point of contact",
    "Proof: the tangent at any point of a circle is perpendicular to the radius through the point of contact",
    "Proof: the lengths of tangents drawn from an external point to a circle are equal",
  ],
  blocks: [
    { t: "h", text: "Secant and tangent" },
    { t: "table", head: ["Line", "How many points it shares with the circle", "Called"], rows: [
      ["Passes right through", "Two", "<strong>Secant</strong>"],
      ["Just touches", "One", "<strong>Tangent</strong>"],
      ["Misses entirely", "Zero", "Non-intersecting line"],
    ] },
    { t: "note", kind: "idea", html: "A tangent is what a secant becomes in the limit. Slide a secant outwards and its two intersection points move closer together; the moment they merge into one, the line has become a tangent. That single shared point is the <strong>point of contact</strong>." },
    { t: "note", kind: "exam", html: "Counting facts that get asked directly: a circle has <strong>infinitely many</strong> tangents (one at every point). From a point <strong>inside</strong> the circle there are <strong>no</strong> tangents. From a point <strong>on</strong> the circle there is exactly <strong>one</strong>. From a point <strong>outside</strong> there are exactly <strong>two</strong>." },

    { t: "h", text: "Theorem 1 — tangent ⊥ radius" },
    { t: "sim", id: "circle-tangents" },
    { t: "formula", name: "Theorem 1",
      expr: "The tangent at any point of a circle is perpendicular to the radius through the point of contact." },
    { t: "steps", title: "Prove that the tangent is perpendicular to the radius at the point of contact.",
      intro: "A proof by contradiction, and one of the two the syllabus requires in full.",
      steps: [
        "Let XY be a tangent to a circle with centre O, touching it at P. We must show OP ⊥ XY.",
        "Take any point Q on XY <em>other</em> than P. Since XY is a tangent, it meets the circle only at P — so <strong>Q lies outside</strong> the circle.",
        "Therefore <strong>OQ &gt; OP</strong>, because OP is a radius and Q is beyond the circle.",
        "This is true for <em>every</em> point Q on the line except P. So OP is the <strong>shortest</strong> distance from O to the line XY.",
        "But the shortest distance from a point to a line is always the perpendicular distance.",
      ],
      answer: "Therefore OP ⊥ XY. ∎",
    },
    { t: "note", kind: "memory", html: "The whole proof hangs on one idea: <strong>the shortest distance from a point to a line is the perpendicular</strong>. If you remember that sentence you can reconstruct the argument." },

    { t: "h", text: "Theorem 2 — equal tangents from an external point" },
    { t: "formula", name: "Theorem 2",
      expr: "The lengths of the two tangents drawn from an external point to a circle are equal.",
      where: ["If PA and PB are tangents from P, then <strong>PA = PB</strong>"] },
    { t: "steps", title: "Prove that tangents from an external point are equal.",
      intro: "A congruence proof. Notice that Theorem 1 is used inside it — that is why the order matters.",
      steps: [
        "Let PA and PB be tangents from an external point P to a circle with centre O. Join OA, OB and OP.",
        "By <strong>Theorem 1</strong>, OA ⊥ PA and OB ⊥ PB, so ∠OAP = ∠OBP = 90°.",
        "Now compare △OAP and △OBP. <strong>OA = OB</strong> (both radii).",
        "<strong>OP = OP</strong> (common hypotenuse).",
        "Both triangles are right-angled, so by the <strong>RHS</strong> congruence rule, △OAP ≅ △OBP.",
        "Corresponding parts of congruent triangles are equal, so PA = PB.",
      ],
      answer: "Hence the two tangents are equal in length. ∎ (It also follows that ∠OPA = ∠OPB — OP bisects the angle between the tangents.)",
    },
    { t: "note", kind: "idea", title: "Two free extras", html: "The same congruence gives you two more results that questions often need: <strong>OP bisects ∠APB</strong>, and <strong>OP bisects ∠AOB</strong>. And since OAPB has two right angles, <strong>∠APB + ∠AOB = 180°</strong> — the angle at the external point and the angle at the centre are supplementary." },

    { t: "h", text: "Working with tangent lengths" },
    { t: "formula", name: "Length of a tangent", expr: "PA = √(OP² − r²)",
      where: ["P is external, O the centre, r the radius", "Straight from Pythagoras in the right triangle OAP"] },
    { t: "steps", title: "A tangent from a point P touches a circle of radius 5 cm at A. If OP = 13 cm, find PA.",
      intro: "One mark, if you spot the right angle.",
      steps: [
        "OA is a radius, PA a tangent, so ∠OAP = 90° by Theorem 1.",
        "△OAP is right-angled at A, so Pythagoras applies: OP² = OA² + PA².",
        "Substitute: 13² = 5² + PA², so 169 = 25 + PA².",
        "PA² = 144.",
      ],
      answer: "PA = 12 cm.",
    },
    { t: "note", kind: "memory", html: "Watch for Pythagorean triples in these questions — <strong>3-4-5</strong>, <strong>5-12-13</strong>, <strong>8-15-17</strong> and <strong>7-24-25</strong>. Examiners choose them deliberately so the arithmetic is clean, and spotting one saves time." },

    { t: "h", text: "The quadrilateral result worth knowing" },
    { t: "p", html: "If a quadrilateral ABCD has a circle inscribed in it, touching all four sides, then the tangent lengths from each vertex are equal — and adding them up gives a neat result." },
    { t: "formula", name: "Circumscribed quadrilateral", expr: "AB + CD = BC + AD",
      where: ["The two pairs of opposite sides have equal sums"] },
    { t: "note", kind: "why", html: "Label the tangent lengths from A, B, C, D as p, q, r, s. Then AB = p + q, BC = q + r, CD = r + s and AD = s + p. So AB + CD = p + q + r + s and BC + AD = q + r + s + p. The same four letters — hence equal." },
    { t: "note", kind: "exam", html: "For a parallelogram circumscribing a circle, this forces AB + CD = BC + AD; since opposite sides of a parallelogram are already equal, that gives 2AB = 2BC, so <strong>every parallelogram circumscribing a circle is a rhombus</strong>. That exact question is set regularly." },
  ],
  formulas: [
    { name: "Theorem 1", expr: "Tangent ⊥ radius at the point of contact" },
    { name: "Theorem 2", expr: "Tangents from an external point are equal: PA = PB" },
    { name: "Length of tangent", expr: "PA = √(OP² − r²)" },
    { name: "Supplementary angles", expr: "∠APB + ∠AOB = 180°" },
    { name: "Circumscribed quadrilateral", expr: "AB + CD = BC + AD" },
  ],
  examFocus: [
    "Both proofs in full — they are explicitly named in the syllabus.",
    "The 'shortest distance is the perpendicular' step in Theorem 1.",
    "Using RHS congruence in Theorem 2, and the extras it gives (OP bisects both angles).",
    "Counting tangents from a point inside, on, and outside the circle.",
    "PA = √(OP² − r²) and recognising Pythagorean triples.",
    "AB + CD = BC + AD, and the parallelogram-is-a-rhombus consequence.",
  ],
  flashcards: [
    { q: "What is a tangent to a circle?", a: "A line that touches the circle at exactly one point, called the point of contact." },
    { q: "What is a secant?", a: "A line that intersects the circle at two distinct points. A tangent is the limiting case where those two points merge into one." },
    { q: "How many tangents can be drawn from a point inside, on, and outside a circle?", a: "Inside: none. On the circle: exactly one. Outside: exactly two." },
    { q: "State Theorem 1 for circles.", a: "The tangent at any point of a circle is perpendicular to the radius through the point of contact." },
    { q: "Prove that the tangent is perpendicular to the radius.", a: "Every point Q on the tangent other than the point of contact P lies outside the circle, so OQ > OP. Hence OP is the shortest distance from O to the line, and the shortest distance from a point to a line is the perpendicular. So OP ⊥ tangent." },
    { q: "State Theorem 2 for circles.", a: "The lengths of the two tangents drawn from an external point to a circle are equal." },
    { q: "Prove that tangents from an external point are equal.", a: "In △OAP and △OBP: ∠OAP = ∠OBP = 90° (Theorem 1), OA = OB (radii), OP common. By RHS the triangles are congruent, so PA = PB by CPCT." },
    { q: "What two extra results follow from the proof of Theorem 2?", a: "OP bisects ∠APB and OP bisects ∠AOB. Also ∠APB + ∠AOB = 180°." },
    { q: "How do you find the length of a tangent from an external point?", a: "PA = √(OP² − r²), using Pythagoras in the right triangle formed by the radius, the tangent and the line to the centre." },
    { q: "For a quadrilateral circumscribing a circle, what is the relationship between its sides?", a: "AB + CD = BC + AD — the sums of the two pairs of opposite sides are equal." },
    { q: "Why is a parallelogram circumscribing a circle always a rhombus?", a: "AB + CD = BC + AD, and in a parallelogram AB = CD and BC = AD. So 2AB = 2BC, giving AB = BC — all four sides are equal." },
    { q: "What is the angle between two tangents from an external point, if the angle at the centre is 110°?", a: "70°, since ∠APB + ∠AOB = 180°." },
  ],
  quiz: [
    { q: "A tangent to a circle intersects it at:", options: ["Two points", "One point", "No point", "Three points"], answer: 1, why: "By definition a tangent touches the circle at exactly one point — the point of contact." },
    { q: "How many tangents can be drawn to a circle from a point inside it?", options: ["0", "1", "2", "Infinitely many"], answer: 0, why: "Any line through an interior point must cut the circle at two points, so it is a secant, never a tangent." },
    { q: "The angle between a tangent and the radius at the point of contact is:", options: ["45°", "60°", "90°", "180°"], answer: 2, why: "This is Theorem 1 — the tangent is perpendicular to the radius at the point of contact." },
    { q: "PA and PB are tangents from P to a circle. If PA = 7 cm, then PB is:", options: ["7 cm", "14 cm", "3.5 cm", "Cannot be determined"], answer: 0, why: "Tangents from an external point are equal in length, so PB = PA = 7 cm." },
    { q: "A tangent PA touches a circle of radius 8 cm, with OP = 17 cm. PA equals:", options: ["9 cm", "15 cm", "25 cm", "12 cm"], answer: 1, why: "PA = √(OP² − r²) = √(289 − 64) = √225 = 15 cm. (An 8-15-17 triple.)" },
    { q: "If the angle between two tangents from an external point is 60°, the angle subtended at the centre is:", options: ["60°", "90°", "120°", "150°"], answer: 2, why: "∠APB + ∠AOB = 180°, so ∠AOB = 180 − 60 = 120°." },
    { q: "The proof that the tangent is perpendicular to the radius relies on:", options: ["Congruent triangles", "The shortest distance from a point to a line being the perpendicular", "Similar triangles", "The angle sum property"], answer: 1, why: "Every other point on the tangent lies outside the circle, so OP is the shortest such distance — and the shortest distance is the perpendicular." },
    { q: "Which congruence rule proves that tangents from an external point are equal?", options: ["SSS", "SAS", "ASA", "RHS"], answer: 3, why: "The two triangles are right-angled, share the hypotenuse OP, and have equal radii — that is RHS." },
    { q: "A quadrilateral ABCD circumscribes a circle. If AB = 6, BC = 7 and CD = 4, then AD is:", options: ["3", "5", "9", "8"], answer: 0, why: "AB + CD = BC + AD, so 6 + 4 = 7 + AD, giving AD = 3." },
    { q: "A parallelogram circumscribing a circle must be a:", options: ["Rectangle", "Rhombus", "Square", "Trapezium"], answer: 1, why: "AB + CD = BC + AD combined with opposite sides being equal forces all four sides to be equal — a rhombus." },
    { q: "The number of tangents that can be drawn to a circle is:", options: ["1", "2", "4", "Infinitely many"], answer: 3, why: "There is exactly one tangent at every point of the circle, and there are infinitely many points." },
    { q: "In the figure of two tangents from P, the line OP:", options: ["Bisects ∠APB only", "Bisects ∠AOB only", "Bisects both ∠APB and ∠AOB", "Bisects neither"], answer: 2, why: "The congruence △OAP ≅ △OBP makes the corresponding angles at both P and O equal, so OP bisects both." },
  ],
};
