import type { Chapter } from "@/lib/types";

export const ch11: Chapter = {
  slug: "areas-related-to-circles",
  num: 11,
  title: "Areas Related to Circles",
  unit: "mensur",
  unitName: "Mensuration",
  marks: "Unit VI · 10 marks",
  minutes: 14,
  blurb: "A sector is a fraction of a circle. Work out which fraction and the rest is multiplication.",
  bigIdea: "Everything here is (θ/360) of something you already know. The only real skill is deciding which regions to add and which to subtract.",
  syllabus: [
    "Area of sectors and segments of a circle",
    "Problems based on areas and perimeter / circumference of the above",
    "Central angle restricted to 60°, 90° and 120° only",
  ],
  blocks: [
    { t: "h", text: "Starting facts" },
    { t: "formula", name: "Circle", expr: "Circumference = 2πr &nbsp;·&nbsp; Area = πr²",
      where: ["Use π = 22/7 when the radius is a multiple of 7, and 3.14 otherwise"] },
    { t: "note", kind: "memory", html: "Choose π to make the arithmetic cancel. If the radius is 7, 14 or 21, take <strong>π = 22/7</strong> and the sevens vanish. Otherwise <strong>3.14</strong> is cleaner. If the question specifies a value, use that one." },

    { t: "h", text: "Sector and segment" },
    { t: "sim", id: "sector-segment" },
    { t: "list", items: [
      "A <strong>sector</strong> is the region between two radii and the arc between them — the pizza slice.",
      "A <strong>segment</strong> is the region between a chord and the arc — the slice with its triangle cut off.",
      "The <strong>minor</strong> sector or segment is the smaller one, the <strong>major</strong> the larger. Together they make the whole circle.",
    ] },
    { t: "formula", name: "Sector of angle θ",
      expr: "Area = (θ/360) × πr² &nbsp;·&nbsp; Arc length = (θ/360) × 2πr",
      where: ["θ is the central angle in degrees"] },
    { t: "note", kind: "why", title: "Where the θ/360 comes from", html: "A full turn is 360°. A sector of 90° is therefore exactly a quarter of the circle, so it has a quarter of the area and a quarter of the circumference. θ/360 is simply &ldquo;what fraction of the whole circle this is&rdquo; — nothing more." },
    { t: "formula", name: "Perimeter of a sector", expr: "Perimeter = arc + 2r",
      where: ["The two straight radii must be included — the arc alone is not the perimeter"] },
    { t: "note", kind: "trap", html: "The commonest mistake in the chapter: giving the <strong>arc length</strong> when the question asked for the <strong>perimeter</strong> of the sector. Perimeter means all the way round, so you must add the two radii." },

    { t: "h", text: "Area of a segment" },
    { t: "formula", name: "Minor segment", expr: "Area = area of sector − area of triangle",
      where: ["Area of the triangle = ½ r² sin θ"] },
    { t: "note", kind: "idea", html: "For the three angles the syllabus allows, the triangle is easy: at <strong>60°</strong> it is equilateral with area (√3/4)r²; at <strong>90°</strong> it is a right triangle with area ½r²; at <strong>120°</strong> its area is (√3/4)r² as well. So you rarely need the sine formula at all." },
    { t: "steps", title: "Find the area of the minor segment of a circle of radius 14 cm cut off by a 90° sector. (π = 22/7)",
      intro: "Sector minus triangle — the standard three marks.",
      steps: [
        "Area of the sector = (90/360) × πr² = ¼ × (22/7) × 14 × 14.",
        "= ¼ × 22 × 2 × 14 = 154 cm².",
        "The triangle formed by the two radii and the chord is right-angled at the centre, so its area is ½ × 14 × 14 = 98 cm².",
        "Segment = sector − triangle = 154 − 98.",
      ],
      answer: "Area of the minor segment = 56 cm².",
    },

    { t: "h", text: "Combined figures — the real exam questions" },
    { t: "p", html: "Most questions give you a shaded region made of circles and straight-edged shapes. The method never changes: <strong>name the regions, then add and subtract.</strong>" },
    { t: "list", items: [
      "<strong>Circle inscribed in a square</strong> of side a: the circle's diameter is a, so r = a/2. Shaded corners = a² − π(a/2)².",
      "<strong>Square inscribed in a circle</strong> of radius r: the square's diagonal is 2r, so its side is r√2 and its area is 2r².",
      "<strong>Quadrants at the corners of a square.</strong> Four quadrants of the same radius make exactly <strong>one whole circle</strong> — do not compute them separately.",
      "<strong>Circle inscribed in an equilateral triangle</strong> of side a: r = a/(2√3).",
      "<strong>A running track or a rectangle with semicircular ends</strong>: two semicircles make one circle.",
    ] },
    { t: "note", kind: "memory", html: "&ldquo;Four quadrants make one circle&rdquo; and &ldquo;two semicircles make one circle&rdquo; are the two shortcuts that turn a messy figure into a one-line calculation. Look for them first." },
    { t: "steps", title: "A square of side 14 cm has a quadrant drawn at each corner with radius 7 cm. Find the shaded area outside the quadrants. (π = 22/7)",
      intro: "The classic figure. Spot the shortcut before you start calculating.",
      steps: [
        "Area of the square = 14 × 14 = 196 cm².",
        "The four quadrants all have radius 7 cm, and four quadrants make <strong>one full circle</strong>.",
        "So their combined area = πr² = (22/7) × 7 × 7 = 154 cm².",
        "Shaded area = square − circle = 196 − 154.",
      ],
      answer: "Shaded area = 42 cm².",
    },

    { t: "h", text: "Two applications that come up by name" },
    { t: "list", items: [
      "<strong>Clock hands.</strong> The minute hand sweeps 360° in 60 minutes, so 6° per minute. The area swept in t minutes is a sector of angle 6t°. The hour hand moves 30° per hour, or 0.5° per minute.",
      "<strong>Wheels.</strong> Distance covered in one revolution = circumference. Number of revolutions = total distance ÷ circumference. Watch the units — convert km to cm before dividing.",
    ] },
    { t: "note", kind: "real", html: "The minute-hand question is worth practising because it is pure sector area with a disguised angle. A hand of length 14 cm sweeping 5 minutes covers a 30° sector — nothing more complicated than that." },
    { t: "note", kind: "exam", html: "Always state the units, and use <strong>cm²</strong> for areas and <strong>cm</strong> for lengths. Marks are routinely lost for writing an area with a length unit." },
  ],
  formulas: [
    { name: "Circumference", expr: "2πr" },
    { name: "Area of a circle", expr: "πr²" },
    { name: "Area of a sector", expr: "(θ/360) × πr²" },
    { name: "Length of an arc", expr: "(θ/360) × 2πr" },
    { name: "Perimeter of a sector", expr: "arc + 2r" },
    { name: "Area of a segment", expr: "sector − triangle = (θ/360)πr² − ½r² sin θ" },
    { name: "Equilateral triangle", expr: "(√3/4) × side²", note: "Needed for the 60° segment" },
  ],
  examFocus: [
    "θ/360 as 'what fraction of the circle this is'.",
    "Perimeter of a sector = arc + 2r, not the arc alone.",
    "Segment = sector − triangle, with the easy triangle areas at 60°, 90° and 120°.",
    "Choosing π = 22/7 when the radius is a multiple of 7.",
    "The shortcuts: four quadrants make a circle, two semicircles make a circle.",
    "Clock-hand problems: 6° per minute for the minute hand.",
    "Writing correct units — cm² for area.",
  ],
  flashcards: [
    { q: "What is a sector of a circle?", a: "The region enclosed by two radii and the arc between them — the 'pizza slice'." },
    { q: "What is a segment of a circle?", a: "The region enclosed by a chord and the arc it cuts off. It is the sector with the triangle removed." },
    { q: "Give the formula for the area of a sector.", a: "Area = (θ/360) × πr², where θ is the central angle in degrees." },
    { q: "Give the formula for the length of an arc.", a: "Arc = (θ/360) × 2πr." },
    { q: "What is the perimeter of a sector?", a: "Arc length + 2r. The two straight radii must be included — this is the most commonly missed step." },
    { q: "How do you find the area of a minor segment?", a: "Area of the sector minus the area of the triangle formed by the two radii and the chord. The triangle's area is ½r² sin θ." },
    { q: "What is the area of the triangle in a 60° segment?", a: "The triangle is equilateral with side r, so its area is (√3/4)r²." },
    { q: "When should you use π = 22/7?", a: "When the radius or diameter is a multiple of 7, so the sevens cancel. Otherwise 3.14 is easier — unless the question specifies a value." },
    { q: "How much area do four quadrants of equal radius cover?", a: "Exactly one full circle of that radius. Four quarters make a whole." },
    { q: "If a square of side a has a circle inscribed in it, what is the radius?", a: "r = a/2, because the circle's diameter equals the side of the square." },
    { q: "If a square is inscribed in a circle of radius r, what is its area?", a: "The diagonal of the square is 2r, so the side is r√2 and the area is 2r²." },
    { q: "Through how many degrees does the minute hand of a clock turn in one minute?", a: "6°, since it covers 360° in 60 minutes. In t minutes it sweeps a sector of angle 6t°." },
    { q: "How do you find the number of revolutions a wheel makes over a distance?", a: "Divide the total distance by the circumference of the wheel, after converting both to the same units." },
  ],
  quiz: [
    { q: "The area of a sector of angle 90° in a circle of radius 14 cm (π = 22/7) is:", options: ["154 cm²", "616 cm²", "77 cm²", "308 cm²"], answer: 0, why: "(90/360) × (22/7) × 14 × 14 = ¼ × 616 = 154 cm²." },
    { q: "The perimeter of a sector of radius r and arc length l is:", options: ["l", "l + r", "l + 2r", "2l + r"], answer: 2, why: "The boundary consists of the arc and the two radii, so the perimeter is l + 2r." },
    { q: "The area of a segment equals:", options: ["Sector + triangle", "Sector − triangle", "Circle − sector", "Triangle − sector"], answer: 1, why: "The segment is what is left when the triangle formed by the two radii and the chord is removed from the sector." },
    { q: "Four quadrants of radius 7 cm together have area:", options: ["77 cm²", "154 cm²", "308 cm²", "38.5 cm²"], answer: 1, why: "Four quadrants make one full circle: πr² = (22/7) × 49 = 154 cm²." },
    { q: "The minute hand of a clock turns through how many degrees in 15 minutes?", options: ["30°", "60°", "90°", "180°"], answer: 2, why: "It turns 6° per minute, so 15 × 6 = 90°." },
    { q: "A circle is inscribed in a square of side 14 cm. The radius of the circle is:", options: ["14 cm", "7 cm", "28 cm", "7√2 cm"], answer: 1, why: "The circle's diameter equals the side of the square, so r = 14/2 = 7 cm." },
    { q: "The circumference of a circle of radius 21 cm (π = 22/7) is:", options: ["132 cm", "66 cm", "1386 cm", "44 cm"], answer: 0, why: "2πr = 2 × (22/7) × 21 = 2 × 66 = 132 cm." },
    { q: "The arc length of a 60° sector of a circle of radius 21 cm (π = 22/7) is:", options: ["11 cm", "22 cm", "44 cm", "66 cm"], answer: 1, why: "(60/360) × 2 × (22/7) × 21 = (1/6) × 132 = 22 cm." },
    { q: "A square is inscribed in a circle of radius 10 cm. Its area is:", options: ["100 cm²", "200 cm²", "400 cm²", "50 cm²"], answer: 1, why: "The diagonal is 2r = 20, so the side is 20/√2 and the area is (20/√2)² = 400/2 = 200 cm²." },
    { q: "A wheel of diameter 70 cm covers 11 km. The number of revolutions is (π = 22/7):", options: ["500", "5000", "50", "50000"], answer: 1, why: "Circumference = π × 70 = 220 cm. Distance = 11 km = 1,100,000 cm. 1,100,000 ÷ 220 = 5000." },
    { q: "The area of the triangle in a 90° segment of a circle of radius r is:", options: ["r²", "½r²", "(√3/4)r²", "πr²/4"], answer: 1, why: "It is a right triangle with both legs equal to r, so the area is ½ × r × r = ½r²." },
    { q: "If the radius of a circle is doubled, its area becomes:", options: ["Twice as big", "Three times as big", "Four times as big", "Unchanged"], answer: 2, why: "Area = πr², so doubling r multiplies the area by 2² = 4." },
  ],
};
