import type { Chapter } from "@/lib/types";

export const ch12: Chapter = {
  slug: "surface-areas-and-volumes",
  num: 12,
  title: "Surface Areas and Volumes",
  unit: "mensur",
  unitName: "Mensuration",
  marks: "Unit VI · 10 marks",
  minutes: 18,
  blurb: "Volumes always add. Surface areas do not — the faces that get glued together disappear, and that is where the marks are.",
  bigIdea: "Break the object into shapes you already know. Add the volumes without thinking; count the surfaces very carefully indeed.",
  syllabus: [
    "Surface areas and volumes of combinations of any two of the following: cubes, cuboids, spheres, hemispheres and right circular cylinders / cones",
  ],
  blocks: [
    { t: "h", text: "The formulas you are working from" },
    { t: "table", head: ["Solid", "Volume", "Curved / Lateral SA", "Total SA"], rows: [
      ["<strong>Cube</strong> (side a)", "a³", "4a²", "6a²"],
      ["<strong>Cuboid</strong> (l, b, h)", "lbh", "2h(l + b)", "2(lb + bh + hl)"],
      ["<strong>Cylinder</strong> (r, h)", "πr²h", "2πrh", "2πr(r + h)"],
      ["<strong>Cone</strong> (r, h, slant l)", "⅓πr²h", "πrl", "πr(l + r)"],
      ["<strong>Sphere</strong> (r)", "⁴⁄₃πr³", "4πr²", "4πr²"],
      ["<strong>Hemisphere</strong> (r)", "⅔πr³", "2πr²", "3πr²"],
    ] },
    { t: "formula", name: "Slant height of a cone", expr: "l = √(r² + h²)",
      where: ["Pythagoras on the radius and the vertical height"] },
    { t: "note", kind: "trap", html: "For a cone, always check whether the question gives you the <strong>vertical height h</strong> or the <strong>slant height l</strong>. Volume needs h; curved surface area needs l. Substituting one for the other is the single biggest source of lost marks in this chapter." },
    { t: "note", kind: "memory", html: "A hemisphere has <em>three</em> lots of πr²: two for the curved dome, one for the flat circular face. Hence total surface area 3πr², while curved surface area is only 2πr²." },

    { t: "h", text: "Combining solids" },
    { t: "sim", id: "solids-combo" },
    { t: "note", kind: "idea", title: "The one rule", html: "<strong>Volumes add. Surface areas do not.</strong> When two solids are joined, the faces where they meet are inside the object and cannot be seen or painted — so they must be left out of the surface area." },
    { t: "table", head: ["Object", "Volume", "Surface area (what you can actually see)"], rows: [
      ["Ice-cream cone<br><span class='faint'>cone + hemisphere</span>", "⅓πr²h + ⅔πr³", "πrl + 2πr²"],
      ["Capsule / gas cylinder<br><span class='faint'>cylinder + 2 hemispheres</span>", "πr²h + ⁴⁄₃πr³", "2πrh + 4πr²"],
      ["Circus tent<br><span class='faint'>cylinder + cone</span>", "πr²h + ⅓πr²H", "2πrh + πrl <span class='faint'>(no floor)</span>"],
      ["Toy: cone on hemisphere", "⅓πr²h + ⅔πr³", "πrl + 2πr²"],
      ["Cube with hemispherical depression", "a³ − ⅔πr³", "6a² − πr² + 2πr²"],
    ] },
    { t: "note", kind: "why", title: "Why the tent has no floor", html: "Canvas covers the curved side of the cylinder and the sloping cone, but you do not lay canvas on the ground. So the area of canvas is 2πrh + πrl — no circles at all. Read the wording: &ldquo;area of canvas&rdquo;, &ldquo;cost of painting&rdquo; and &ldquo;cost of polishing&rdquo; each tell you which surfaces to count." },

    { t: "steps", title: "A toy is a cone of radius 3.5 cm and height 12 cm mounted on a hemisphere of the same radius. Find its total surface area. (π = 22/7)",
      intro: "The commonest combination question in the paper.",
      steps: [
        "First find the slant height: l = √(r² + h²) = √(3.5² + 12²) = √(12.25 + 144) = √156.25 = <strong>12.5 cm</strong>.",
        "The visible surfaces are the <strong>curved surface of the cone</strong> and the <strong>curved surface of the hemisphere</strong>. The two flat circles are joined together inside, so they do not count.",
        "Curved SA of cone = πrl = (22/7) × 3.5 × 12.5 = 11 × 12.5 = 137.5 cm².",
        "Curved SA of hemisphere = 2πr² = 2 × (22/7) × 3.5 × 3.5 = 2 × 38.5 = 77 cm².",
        "Total = 137.5 + 77.",
      ],
      answer: "Total surface area = 214.5 cm².",
    },

    { t: "h", text: "Conversion problems — melting and recasting" },
    { t: "p", html: "The other big question type: one solid is melted and recast into another, or a liquid is poured from one container into another. Nothing is lost, so:" },
    { t: "formula", name: "The conservation principle", expr: "Volume before = Volume after",
      where: ["Surface area is <em>not</em> conserved — only volume"] },
    { t: "steps", title: "A metallic sphere of radius 4.2 cm is melted and recast into a cylinder of radius 6 cm. Find the height of the cylinder.",
      intro: "Set the volumes equal and solve. The π cancels every time.",
      steps: [
        "Volume of the sphere = ⁴⁄₃πr³ = ⁴⁄₃ × π × (4.2)³.",
        "Volume of the cylinder = πR²h = π × 6² × h = 36πh.",
        "Melting conserves volume, so: ⁴⁄₃ × π × 74.088 = 36πh.",
        "The π cancels from both sides: ⁴⁄₃ × 74.088 = 36h, so 98.784 = 36h.",
      ],
      answer: "h = 2.744 cm.",
    },
    { t: "note", kind: "memory", html: "In every conversion problem the <strong>π cancels</strong>. Do not substitute 22/7 at the start — leave π as a symbol, cancel it, and the arithmetic gets far easier." },
    { t: "note", kind: "exam", html: "&ldquo;How many small spheres can be made from a large one?&rdquo; is the same idea: <strong>number = volume of the big solid ÷ volume of one small solid</strong>. The answer must be a whole number, so round <em>down</em> — you cannot make a fraction of a ball." },

    { t: "h", text: "Units, and the trap in them" },
    { t: "list", items: [
      "<strong>1 cm³ = 1 millilitre.</strong> So 1000 cm³ = 1 litre.",
      "<strong>1 m³ = 1,000,000 cm³ = 1000 litres.</strong>",
      "Convert <em>before</em> you calculate, never after. Mixing metres and centimetres inside one formula is a guaranteed wrong answer.",
    ] },
    { t: "note", kind: "real", html: "Water-tank questions rely on 1 cm³ = 1 mL. A cylindrical tank of volume 15,400 cm³ holds 15.4 litres — which is why the question is usually phrased in litres while the dimensions are in centimetres." },
  ],
  formulas: [
    { name: "Cube", expr: "V = a³, TSA = 6a²" },
    { name: "Cuboid", expr: "V = lbh, TSA = 2(lb + bh + hl)" },
    { name: "Cylinder", expr: "V = πr²h, CSA = 2πrh, TSA = 2πr(r + h)" },
    { name: "Cone", expr: "V = ⅓πr²h, CSA = πrl, TSA = πr(l + r)" },
    { name: "Sphere", expr: "V = ⁴⁄₃πr³, SA = 4πr²" },
    { name: "Hemisphere", expr: "V = ⅔πr³, CSA = 2πr², TSA = 3πr²" },
    { name: "Slant height", expr: "l = √(r² + h²)" },
    { name: "Conversion", expr: "Volume before = Volume after" },
    { name: "Units", expr: "1 cm³ = 1 mL · 1 m³ = 1000 L" },
  ],
  examFocus: [
    "The whole formula table, and especially the difference between CSA and TSA.",
    "l = √(r² + h²), and never confusing slant height with vertical height.",
    "Volumes add; surface areas leave out the joined faces.",
    "Reading the wording — canvas, painting, polishing — to decide which faces to count.",
    "Melting and recasting: equate volumes and cancel π.",
    "'How many can be made' = big volume ÷ small volume, rounded down.",
    "1 cm³ = 1 mL, and converting units before calculating.",
  ],
  flashcards: [
    { q: "Give the volume and total surface area of a cylinder.", a: "V = πr²h, CSA = 2πrh, TSA = 2πr(r + h) — the curved surface plus the two circular ends." },
    { q: "Give the volume and surface areas of a cone.", a: "V = ⅓πr²h, CSA = πrl, TSA = πr(l + r), where l is the slant height." },
    { q: "Give the volume and surface areas of a hemisphere.", a: "V = ⅔πr³, CSA = 2πr², TSA = 3πr² — the curved dome plus the flat circular base." },
    { q: "How do you find the slant height of a cone?", a: "l = √(r² + h²), by Pythagoras on the radius and the vertical height." },
    { q: "Why is the total surface area of a combined solid not just the sum of the two?", a: "Because the faces where the two solids are joined lie inside the object. They cannot be seen or painted, so they are excluded." },
    { q: "What is the total surface area of a cone mounted on a hemisphere of the same radius?", a: "πrl + 2πr² — the curved surface of the cone plus the curved surface of the hemisphere. The two circular faces are joined and do not count." },
    { q: "What stays constant when a solid is melted and recast?", a: "The volume. Surface area changes, but volume is conserved, so you set volume before = volume after." },
    { q: "Why should you not substitute π = 22/7 at the start of a conversion problem?", a: "Because π appears on both sides and cancels. Leaving it as a symbol makes the arithmetic much simpler." },
    { q: "How do you find how many small spheres can be made from a large solid?", a: "Divide the volume of the large solid by the volume of one small sphere, and round down to a whole number." },
    { q: "What is the relationship between cm³ and millilitres?", a: "1 cm³ = 1 mL, so 1000 cm³ = 1 litre and 1 m³ = 1000 litres." },
    { q: "For a circus tent made of a cylinder topped by a cone, what area of canvas is needed?", a: "2πrh + πrl — the curved surfaces only. No canvas is laid on the ground, so no circular areas are included." },
    { q: "A cube has a hemispherical depression cut into it. What is the remaining volume?", a: "a³ − ⅔πr³. The surface area becomes 6a² − πr² + 2πr², since the flat circle is removed and the curved dome added." },
  ],
  quiz: [
    { q: "The volume of a sphere of radius 3 cm is:", options: ["36π cm³", "27π cm³", "12π cm³", "9π cm³"], answer: 0, why: "V = ⁴⁄₃πr³ = ⁴⁄₃ × π × 27 = 36π cm³." },
    { q: "The total surface area of a hemisphere of radius r is:", options: ["2πr²", "3πr²", "4πr²", "πr²"], answer: 1, why: "2πr² for the curved dome plus πr² for the flat circular face, giving 3πr²." },
    { q: "A cone has radius 3 cm and height 4 cm. Its slant height is:", options: ["5 cm", "7 cm", "12 cm", "25 cm"], answer: 0, why: "l = √(3² + 4²) = √25 = 5 cm — the 3-4-5 triple." },
    { q: "When two solids are joined, which quantity simply adds?", options: ["Surface area", "Volume", "Both", "Neither"], answer: 1, why: "Volumes add exactly. Surface areas do not, because the joined faces are hidden inside." },
    { q: "A sphere is melted and recast into a cylinder. What remains the same?", options: ["Surface area", "Radius", "Volume", "Height"], answer: 2, why: "Melting conserves the amount of material, which is the volume." },
    { q: "The curved surface area of a cylinder of radius 7 cm and height 10 cm (π = 22/7) is:", options: ["440 cm²", "220 cm²", "748 cm²", "154 cm²"], answer: 0, why: "CSA = 2πrh = 2 × (22/7) × 7 × 10 = 440 cm²." },
    { q: "The volume of a cone is what fraction of a cylinder with the same base and height?", options: ["One half", "One third", "Two thirds", "The same"], answer: 1, why: "V(cone) = ⅓πr²h while V(cylinder) = πr²h, so the cone is exactly one third." },
    { q: "1 cubic metre equals:", options: ["100 litres", "1000 litres", "10 litres", "1,000,000 litres"], answer: 1, why: "1 m³ = 1,000,000 cm³, and 1000 cm³ = 1 litre, so 1 m³ = 1000 litres." },
    { q: "A toy is a cone on a hemisphere of the same radius. Its total surface area is:", options: ["πrl + 2πr²", "πrl + 3πr²", "πr(l + r) + 3πr²", "πrl + πr²"], answer: 0, why: "Only the curved surfaces are visible: πrl for the cone and 2πr² for the hemisphere. The joined circles are hidden." },
    { q: "The volume of a cube of side 5 cm is:", options: ["25 cm³", "125 cm³", "150 cm³", "75 cm³"], answer: 1, why: "V = a³ = 5³ = 125 cm³." },
    { q: "If the radius of a sphere is doubled, its volume becomes:", options: ["Twice", "Four times", "Six times", "Eight times"], answer: 3, why: "V ∝ r³, so doubling the radius multiplies the volume by 2³ = 8." },
    { q: "For a canvas tent shaped as a cylinder topped by a cone, the area of canvas required is:", options: ["2πrh + πrl", "2πrh + πrl + πr²", "2πr(r+h) + πrl", "πr²h + ⅓πr²H"], answer: 0, why: "Only the curved surfaces need canvas. There is no floor, so no circular areas are included." },
  ],
};
