import type { Chapter } from "@/lib/types";

export const ch12: Chapter = {
  slug: "surface-areas-and-volumes",
  num: 12,
  title: "Surface Areas and Volumes",
  unit: "mensur",
  unitName: "Mensuration",
  marks: "Unit VI · 10 marks",
  minutes: 18,
  blurb: "Volumes always add. Surface areas do not — the faces that get glued together disappear, and that is where the marks are.",
  bigIdea: "Break the object into shapes you already know. Add the volumes without thinking; count the surfaces very carefully indeed.",
  syllabus: [
    "Surface areas and volumes of combinations of any two of the following: cubes, cuboids, spheres, hemispheres and right circular cylinders / cones",
  ],
  blocks: [
    { t: "h", text: "The formulas you are working from" },
    { t: "table", head: ["Solid", "Volume", "Curved / Lateral SA", "Total SA"], rows: [
      ["<strong>Cube</strong> (side a)", "a³", "4a²", "6a²"],
      ["<strong>Cuboid</strong> (l, b, h)", "lbh", "2h(l + b)", "2(lb + bh + hl)"],
      ["<strong>Cylinder</strong> (r, h)", "πr²h", "2πrh", "2πr(r + h)"],
      ["<strong>Cone</strong> (r, h, slant l)", "⅓πr²h", "πrl", "πr(l + r)"],
      ["<strong>Sphere</strong> (r)", "⁴⁄₃πr³", "4πr²", "4πr²"],
      ["<strong>Hemisphere</strong> (r)", "⅔πr³", "2πr²", "3πr²"],
    ] },
    { t: "formula", name: "Slant height of a cone", expr: "l = √(r² + h²)",
      where: ["Pythagoras on the radius and the vertical height"] },
    { t: "note", kind: "trap", html: "For a cone, always check whether the question gives you the <strong>vertical height h</strong> or the <strong>slant height l</strong>. Volume needs h; curved surface area needs l. Substituting one for the other is the single biggest source of lost marks in this chapter." },
    { t: "note", kind: "memory", html: "A hemisphere has <em>three</em> lots of πr²: two for the curved dome, one for the flat circular face. Hence total surface area 3πr², while curved surface area is only 2πr²." },

    { t: "h", text: "Combining solids" },
    { t: "sim", id: "solids-combo" },
    { t: "note", kind: "idea", title: "The one rule", html: "<strong>Volumes add. Surface areas do not.</strong> When two solids are joined, the faces where they meet are inside the object and cannot be seen or painted — so they must be left out of the surface area." },
    { t: "table", head: ["Object", "Volume", "Surface area (what you can actually see)"], rows: [
      ["Ice-cream cone<br><span class='faint'>cone + hemisphere</span>", "⅓πr²h + ⅔πr³", "πrl + 2πr²"],
      ["Capsule / gas cylinder<br><span class='faint'>cylinder + 2 hemispheres</span>", "πr²h + ⁴⁄₃πr³", "2πrh + 4πr²"],
      ["Circus tent<br><span class='faint'>cylinder + cone</span>", "πr²h + ⅓πr²H", "2πrh + πrl <span class='faint'>(no floor)</span>"],
      ["Toy: cone on hemisphere", "⅓πr²h + ⅔πr³", "πrl + 2πr²"],
      ["Cube with hemispherical depression", "a³ − ⅔πr³", "6a² − πr² + 2πr²"],
    ] },
    { t: "note", kind: "why", title: "Why the tent has no floor", html: "Canvas covers the curved side of the cylinder and the sloping cone, but you do not lay canvas on the ground. So the area of canvas is 2πrh + πrl — no circles at all. Read the wording: &ldquo;area of canvas&rdquo;, &ldquo;cost of painting&rdquo; and &ldquo;cost of polishing&rdquo; each tell you which surfaces to count." },

    { t: "steps", title: "A toy is a cone of radius 3.5 cm and height 12 cm mounted on a hemisphere of the same radius. Find its total surface area. (π = 22/7)",
      intro: "The commonest combination question in the paper.",
      steps: [
        "First find the slant height: l = √(r² + h²) = √(3.5² + 12²) = √(12.25 + 144) = √156.25 = <strong>12.5 cm</strong>.",
        "The visible surfaces are the <strong>curved surface of the cone</strong> and the <strong>curved surface of the hemisphere</strong>. The two flat circles are joined together inside, so they do not count.",
        "Curved SA of cone = πrl = (22/7) × 3.5 × 12.5 = 11 × 12.5 = 137.5 cm².",
        "Curved SA of hemisphere = 2πr² = 2 × (22/7) × 3.5 × 3.5 = 2 × 38.5 = 77 cm².",
        "Total = 137.5 + 77.",
      ],
      answer: "Total surface area = 214.5 cm².",
    },

    { t: "h", text: "Conversion problems — melting and recasting" },
    { t: "p", html: "The other big question type: one solid is melted and recast into another, or a liquid is poured from one container into another. Nothing is lost, so:" },
    { t: "formula", name: "The conservation principle", expr: "Volume before = Volume after",
      where: ["Surface area is <em>not</em> conserved — only volume"] },
    { t: "steps", title: "A metallic sphere of radius 4.2 cm is melted and recast into a cylinder of radius 6 cm. Find the height of the cylinder.",
      intro: "Set the volumes equal and solve. The π cancels every time.",
      steps: [
        "Volume of the sphere = ⁴⁄₃πr³ = ⁴⁄₃ × π × (4.2)³.",
        "Volume of the cylinder = πR²h = π × 6² × h = 36πh.",
        "Melting conserves volume, so: ⁴⁄₃ × π × 74.088 = 36πh.",
        "The π cancels from both sides: ⁴⁄₃ × 74.088 = 36h, so 98.784 = 36h.",
      ],
      answer: "h = 2.744 cm.",
    },
    { t: "note", kind: "memory", html: "In every conversion problem the <strong>π cancels</strong>. Do not substitute 22/7 at the start — leave π as a symbol, cancel it, and the arithmetic gets far easier." },
    { t: "note", kind: "exam", html: "&ldquo;How many small spheres can be made from a large one?&rdquo; is the same idea: <strong>number = volume of the big solid ÷ volume of one small solid</strong>. The answer must be a whole number, so round <em>down</em> — you cannot make a fraction of a ball." },

    { t: "h", text: "Units, and the trap in them" },
    { t: "list", items: [
      "<strong>1 cm³ = 1 millilitre.</strong> So 1000 cm³ = 1 litre.",
      "<strong>1 m³ = 1,000,000 cm³ = 1000 litres.</strong>",
      "Convert <em>before</em> you calculate, never after. Mixing metres and centimetres inside one formula is a guaranteed wrong answer.",
    ] },
    { t: "note", kind: "real", html: "Water-tank questions rely on 1 cm³ = 1 mL. A cylindrical tank of volume 15,400 cm³ holds 15.4 litres — which is why the question is usually phrased in litres while the dimensions are in centimetres." },
  ],
  formulas: [
    { name: "Cube", expr: "V = a³, TSA = 6a²" },
    { name: "Cuboid", expr: "V = lbh, TSA = 2(lb + bh + hl)" },
    { name: "Cylinder", expr: "V = πr²h, CSA = 2πrh, TSA = 2πr(r + h)" },
    { name: "Cone", expr: "V = ⅓πr²h, CSA = πrl, TSA = πr(l + r)" },
    { name: "Sphere", expr: "V = ⁴⁄₃πr³, SA = 4πr²" },
    { name: "Hemisphere", expr: "V = ⅔πr³, CSA = 2πr², TSA = 3πr²" },
    { name: "Slant height", expr: "l = √(r² + h²)" },
    { name: "Conversion", expr: "Volume before = Volume after" },
    { name: "Units", expr: "1 cm³ = 1 mL · 1 m³ = 1000 L" },
  ],
  examFocus: [
    "The whole formula table, and especially the difference between CSA and TSA.",
    "l = √(r² + h²), and never confusing slant height with vertical height.",
    "Volumes add; surface areas leave out the joined faces.",
    "Reading the wording — canvas, painting, polishing — to decide which faces to count.",
    "Melting and recasting: equate volumes and cancel π.",
    "'How many can be made' = big volume ÷ small volume, rounded down.",
    "1 cm³ = 1 mL, and converting units before calculating.",
  ],
  flashcards: [
    { q: "Give the volume and total surface area of a cylinder.", a: "V = πr²h, CSA = 2πrh, TSA = 2πr(r + h) — the curved surface plus the two circular ends." },
    { q: "Give the volume and surface areas of a cone.", a: "V = ⅓πr²h, CSA = πrl, TSA = πr(l + r), where l is the slant height." },
    { q: "Give the volume and surface areas of a hemisphere.", a: "V = ⅔πr³, CSA = 2πr², TSA = 3πr² — the curved dome plus the flat circular base." },
    { q: "How do you find the slant height of a cone?", a: "l = √(r² + h²), by Pythagoras on the radius and the vertical height." },
    { q: "Why is the total surface area of a combined solid not just the sum of the two?", a: "Because the faces where the two solids are joined lie inside the object. They cannot be seen or painted, so they are excluded." },
    { q: "What is the total surface area of a cone mounted on a hemisphere of the same radius?", a: "πrl + 2πr² — the curved surface of the cone plus the curved surface of the hemisphere. The two circular faces are joined and do not count." },
    { q: "What stays constant when a solid is melted and recast?", a: "The volume. Surface area changes, but volume is conserved, so you set volume before = volume after." },
    { q: "Why should you not substitute π = 22/7 at the start of a conversion problem?", a: "Because π appears on both sides and cancels. Leaving it as a symbol makes the arithmetic much simpler." },
    { q: "How do you find how many small spheres can be made from a large solid?", a: "Divide the volume of the large solid by the volume of one small sphere, and round down to a whole number." },
    { q: "What is the relationship between cm³ and millilitres?", a: "1 cm³ = 1 mL, so 1000 cm³ = 1 litre and 1 m³ = 1000 litres." },
    { q: "For a circus tent made of a cylinder topped by a cone, what area of canvas is needed?", a: "2πrh + πrl — the curved surfaces only. No canvas is laid on the ground, so no circular areas are included." },
    { q: "A cube has a hemispherical depression cut into it. What is the remaining volume?", a: "a³ − ⅔πr³. The surface area becomes 6a² − πr² + 2πr², since the flat circle is removed and the curved dome added." },
  ],
  quiz: [
    { q: "The volume of a sphere of radius 3 cm is:", options: ["36π cm³", "27π cm³", "12π cm³", "9π cm³"], answer: 0, why: "V = ⁴⁄₃πr³ = ⁴⁄₃ × π × 27 = 36π cm³." },
    { q: "The total surface area of a hemisphere of radius r is:", options: ["2πr²", "3πr²", "4πr²", "πr²"], answer: 1, why: "2πr² for the curved dome plus πr² for the flat circular face, giving 3πr²." },
    { q: "A cone has radius 3 cm and height 4 cm. Its slant height is:", options: ["5 cm", "7 cm", "12 cm", "25 cm"], answer: 0, why: "l = √(3² + 4²) = √25 = 5 cm — the 3-4-5 triple." },
    { q: "When two solids are joined, which quantity simply adds?", options: ["Surface area", "Volume", "Both", "Neither"], answer: 1, why: "Volumes add exactly. Surface areas do not, because the joined faces are hidden inside." },
    { q: "A sphere is melted and recast into a cylinder. What remains the same?", options: ["Surface area", "Radius", "Volume", "Height"], answer: 2, why: "Melting conserves the amount of material, which is the volume." },
    { q: "The curved surface area of a cylinder of radius 7 cm and height 10 cm (π = 22/7) is:", options: ["440 cm²", "220 cm²", "748 cm²", "154 cm²"], answer: 0, why: "CSA = 2πrh = 2 × (22/7) × 7 × 10 = 440 cm²." },
    { q: "The volume of a cone is what fraction of a cylinder with the same base and height?", options: ["One half", "One third", "Two thirds", "The same"], answer: 1, why: "V(cone) = ⅓πr²h while V(cylinder) = πr²h, so the cone is exactly one third." },
    { q: "1 cubic metre equals:", options: ["100 litres", "1000 litres", "10 litres", "1,000,000 litres"], answer: 1, why: "1 m³ = 1,000,000 cm³, and 1000 cm³ = 1 litre, so 1 m³ = 1000 litres." },
    { q: "A toy is a cone on a hemisphere of the same radius. Its total surface area is:", options: ["πrl + 2πr²", "πrl + 3πr²", "πr(l + r) + 3πr²", "πrl + πr²"], answer: 0, why: "Only the curved surfaces are visible: πrl for the cone and 2πr² for the hemisphere. The joined circles are hidden." },
    { q: "The volume of a cube of side 5 cm is:", options: ["25 cm³", "125 cm³", "150 cm³", "75 cm³"], answer: 1, why: "V = a³ = 5³ = 125 cm³." },
    { q: "If the radius of a sphere is doubled, its volume becomes:", options: ["Twice", "Four times", "Six times", "Eight times"], answer: 3, why: "V ∝ r³, so doubling the radius multiplies the volume by 2³ = 8." },
    { q: "For a canvas tent shaped as a cylinder topped by a cone, the area of canvas required is:", options: ["2πrh + πrl", "2πrh + πrl + πr²", "2πr(r+h) + πrl", "πr²h + ⅓πr²H"], answer: 0, why: "Only the curved surfaces need canvas. There is no floor, so no circular areas are included." },
  ],
  keyTopics: [
    { name: "Combination of solids — surface area (visible faces only)", importance: "high", note: "The single most-tested skill: exclude the faces hidden where two solids are joined." },
    { name: "Combination of solids — volume (always adds)", importance: "high", note: "Unlike surface area, volumes of joined solids simply add — no exclusions." },
    { name: "Standard combinations — cone + hemisphere, cylinder + cone", importance: "high", note: "Ice-cream cones, toys, tents and capsules. Read the wording to know which surfaces to count." },
    { name: "Melting and recasting — conservation of volume", importance: "high", note: "Volume before = volume after; π cancels from both sides almost every time." },
    { name: "Frustum of a cone", importance: "high", note: "Bucket-shaped problems: volume = ⅓πh(R² + Rr + r²), slant height l = √(h² + (R−r)²)." },
    { name: "Slant height vs vertical height of a cone", importance: "medium", note: "l = √(r² + h²). Volume needs h; curved surface area needs l — mixing them up is the commonest error." },
    { name: "Unit conversions (cm³, mL, litres)", importance: "low", note: "1 cm³ = 1 mL; convert before calculating, never after." },
  ],
  written: [
    { q: "Find the volume of a hemisphere of radius 21 cm. (Use π = 22/7)", marks: 1, kind: "numerical", importance: "medium",
      answer: "Volume = (2/3)πr³ = (2/3) × (22/7) × 21 × 21 × 21.<br>21³ = 9261, and 9261/7 = 1323, so (22/7) × 9261 = 22 × 1323 = 29106.<br>Volume = (2/3) × 29106 = <strong>19404 cm³</strong>." },
    { q: "Find the total surface area of a hemisphere of radius 7 cm. (Use π = 22/7)", marks: 1, kind: "numerical", importance: "medium",
      answer: "TSA = 3πr² = 3 × (22/7) × 7 × 7 = 3 × 22 × 7.<br>TSA = <strong>462 cm²</strong>." },
    { q: "A cone has base radius 5 cm and height 12 cm. Find its slant height and curved surface area. (Use π = 3.14)", marks: 2, kind: "numerical", importance: "medium",
      answer: "Slant height l = √(r² + h²) = √(5² + 12²) = √(25 + 144) = √169 = <strong>13 cm</strong> (the 5-12-13 triple).<br>CSA = πrl = 3.14 × 5 × 13 = 3.14 × 65 = <strong>204.1 cm²</strong>." },
    { q: "A cylinder and a cone have the same base radius. The cylinder has height 10 cm, and the cone has the same volume as the cylinder. Find the height of the cone.", marks: 2, kind: "numerical", importance: "medium",
      answer: "Volume of cylinder = πr²(10). Volume of cone = (1/3)πr²H. Equating: πr²(10) = (1/3)πr²H.<br>The πr² cancels from both sides: 10 = H/3 ⇒ H = 30.<br>Height of the cone = <strong>30 cm</strong> (three times the cylinder's height, as expected since V(cone) = ⅓ × base × height)." },
    { q: "The total surface area of a cube is 96 cm². Find its volume.", marks: 2, kind: "numerical", importance: "medium",
      answer: "TSA = 6a² = 96 ⇒ a² = 16 ⇒ a = 4 cm.<br>Volume = a³ = 4³ = <strong>64 cm³</strong>." },
    { q: "An ice-cream cone has a hemispherical top with the same radius as the cone. If the height of the conical part is 8 cm and the common radius is 3 cm, find the total volume of ice-cream (cone + hemisphere) it can hold. (Use π = 3.14)", marks: 3, kind: "numerical", importance: "high",
      answer: "Volume of cone = (1/3)πr²h = (1/3) × 3.14 × 9 × 8 = (1/3) × 226.08 = 75.36 cm³.<br>Volume of hemisphere = (2/3)πr³ = (2/3) × 3.14 × 27 = (2/3) × 84.78 = 56.52 cm³.<br>Total volume = 75.36 + 56.52.<br>Total volume of ice-cream = <strong>131.88 cm³</strong>." },
    { q: "A tent is in the shape of a cylinder of radius 7 m and height 8 m, surmounted by a cone of the same radius and height 24 m. Find the area of canvas required to make the tent (the tent has no floor). (Use π = 22/7)", marks: 3, kind: "numerical", importance: "high",
      answer: "Slant height of cone: l = √(r² + h²) = √(7² + 24²) = √(49 + 576) = √625 = 25 m (the 7-24-25 triple).<br>CSA of cylinder = 2πrh = 2 × (22/7) × 7 × 8 = 2 × 22 × 8 = 352 m².<br>CSA of cone = πrl = (22/7) × 7 × 25 = 22 × 25 = 550 m².<br>Total canvas = 352 + 550.<br>Area of canvas = <strong>902 m²</strong>." },
    { q: "A medicine capsule is in the shape of a cylinder with two hemispherical ends. Its total length is 14 mm and its diameter is 7 mm. Find its surface area. (Use π = 22/7)", marks: 3, kind: "numerical", importance: "medium",
      answer: "Radius r = 3.5 mm. Length of the cylindrical part = total length − 2r = 14 − 7 = 7 mm.<br>CSA of cylindrical part = 2πrh = 2 × (22/7) × 3.5 × 7 = 154 mm².<br>CSA of the two hemispherical ends together = 4πr² = 4 × (22/7) × 3.5 × 3.5 = 154 mm².<br>Total surface area = 154 + 154.<br>Surface area of the capsule = <strong>308 mm²</strong>." },
    { q: "A bucket open at the top is in the form of a frustum of a cone, with radii of the top and bottom as 20 cm and 12 cm, and height 15 cm. Find (i) the volume of the bucket, and (ii) the area of metal sheet required to make it. (Use π = 3.14)", marks: 5, kind: "numerical", importance: "high",
      answer: "(i) Volume = (1/3)πh(R² + Rr + r²) = (1/3) × 15 × (20² + 20×12 + 12²) = 5 × (400 + 240 + 144) = 5 × 784 = 3920.<br>Volume = 3920 × 3.14 = <strong>12308.8 cm³</strong>.<br>(ii) Slant height l = √(h² + (R−r)²) = √(15² + 8²) = √(225 + 64) = √289 = 17 cm.<br>Curved surface area = πl(R + r) = 3.14 × 17 × 32 = 3.14 × 544 = 1708.16 cm².<br>The bucket is open at the top, so we add only the bottom circle: πr² = 3.14 × 144 = 452.16 cm².<br>Metal sheet required = 1708.16 + 452.16 = <strong>2160.32 cm²</strong>." },
    { q: "A solid metallic sphere of radius 10.5 cm is melted and recast into a number of smaller solid cones, each of radius 3.5 cm and height 3 cm. Find the number of cones formed. (Use π = 22/7)", marks: 5, kind: "numerical", importance: "high",
      answer: "Volume of sphere = (4/3)πR³ = (4/3) × (22/7) × 10.5³. Since 10.5 = 21/2, R³ = 9261/8, and 9261/7 = 1323, so (22/7) × 9261 = 29106.<br>Volume of sphere = (4/3) × 29106/8 = (4 × 29106)/(3 × 8) = 116424/24 = 4851 cm³.<br>Volume of one cone = (1/3)πr²h = (1/3) × (22/7) × 3.5 × 3.5 × 3 = (22/7) × 12.25 = 38.5 cm³.<br>Number of cones = volume of sphere ÷ volume of one cone = 4851 ÷ 38.5.<br>Number of cones formed = <strong>126</strong>." },
  ],
  assertionReason: [
    { assertion: "The volume of a solid formed by joining a cone and a hemisphere of the same radius equals the sum of their individual volumes.",
      reason: "The formula for the volume of a hemisphere is (2/3)πr³, and for a cone of the same radius it is (1/3)πr²h.",
      answer: 1, importance: "high",
      why: "Both statements are true — volumes genuinely add when solids are joined, and the two formulas quoted are correct. But the reason only restates the individual formulas; it does not explain WHY volumes are additive when solids are combined." },
    { assertion: "The total surface area of a solid formed by mounting a cone on a hemisphere of the same radius equals the sum of the total surface areas of the cone and the hemisphere taken separately.",
      reason: "When two solids are joined, the flat faces at the junction are hidden inside the new solid and must be excluded from the total surface area.",
      answer: 3, importance: "high",
      why: "The assertion is false — you must add only the curved surfaces (πrl + 2πr²), not the total surface areas, because the flat circular faces where the solids meet are hidden. The reason is true and is exactly why the assertion is wrong." },
    { assertion: "A solid sphere of radius 6 cm, melted and recast into a cylinder of radius 6 cm, gives a cylinder of height 8 cm.",
      reason: "When a solid is melted and recast, both its volume and its total surface area remain unchanged.",
      answer: 2, importance: "high",
      why: "The assertion is true: (4/3)π(6³) = π(6²)h gives h = 4×216/(3×36) = 8 cm. But the reason is false — only the volume is conserved on melting and recasting; the surface area generally changes." },
    { assertion: "For a cone with base radius r and height h, the slant height is given by l = √(r² + h²).",
      reason: "The radius, the vertical height and the slant height of a cone form a right triangle, with the slant height as the hypotenuse.",
      answer: 0, importance: "medium",
      why: "Both statements are true, and the reason correctly explains the assertion — Pythagoras' theorem applied to that right triangle gives exactly l = √(r² + h²)." },
  ],
  caseStudies: [
    { title: "A wooden toy", importance: "high",
      source: "A solid wooden toy is in the shape of a hemisphere surmounted by a right circular cone of the same radius. The common radius is 6 cm and the height of the conical part is 8 cm. (Use π = 3.14)",
      parts: [
        { q: "Find the slant height of the conical part.", marks: 1, answer: "l = √(r² + h²) = √(6² + 8²) = √(36 + 64) = √100 = <strong>10 cm</strong> (the 6-8-10 triple)." },
        { q: "Find the total volume of the toy (cone + hemisphere).", marks: 2, answer: "Volume of cone = (1/3)πr²h = (1/3) × 3.14 × 36 × 8 = 3.14 × 96 = 301.44 cm³.<br>Volume of hemisphere = (2/3)πr³ = (2/3) × 3.14 × 216 = 452.16 cm³.<br>Total volume = 301.44 + 452.16 = <strong>753.6 cm³</strong>." },
        { q: "Find the total surface area of the toy (the visible curved surfaces only).", marks: 2, answer: "CSA of cone = πrl = 3.14 × 6 × 10 = 188.4 cm².<br>CSA of hemisphere = 2πr² = 2 × 3.14 × 36 = 226.08 cm².<br>Visible surface area = 188.4 + 226.08 = <strong>414.48 cm²</strong>." },
      ] },
    { title: "The municipal water tank", importance: "medium",
      source: "A water tank is in the form of a cylinder of radius 21 m and height 10 m, surmounted by a hemispherical dome of the same radius. (Use π = 22/7)",
      parts: [
        { q: "Find the volume of the cylindrical part of the tank.", marks: 1, answer: "Volume = πr²h = (22/7) × 21 × 21 × 10 = 22 × 3 × 21 × 10 = <strong>13860 m³</strong> (using 21/7 = 3)." },
        { q: "Find the volume of the hemispherical dome, and hence the total capacity of the tank.", marks: 2, answer: "Volume of dome = (2/3)πr³ = (2/3) × (22/7) × 9261 = (2/3) × 29106 = 19404 m³ (since 9261/7 = 1323, ×22 = 29106).<br>Total capacity = 13860 + 19404 = <strong>33264 m³</strong>." },
        { q: "The outer curved surfaces of the cylinder and the dome are to be painted (no paint is needed on the base). Find the area to be painted.", marks: 2, answer: "CSA of cylinder = 2πrh = 2 × (22/7) × 21 × 10 = 2 × 22 × 3 × 10 = 1320 m².<br>CSA of dome = 2πr² = 2 × (22/7) × 441 = 2 × 1386 = 2772 m².<br>Area to be painted = 1320 + 2772 = <strong>4092 m²</strong>." },
      ] },
  ],
};
