import type { Chapter } from "@/lib/types";

export const ch13: Chapter = {
  slug: "statistics",
  num: 13,
  title: "Statistics",
  unit: "statprob",
  unitName: "Statistics and Probability",
  marks: "Unit VII · 11 marks",
  minutes: 16,
  blurb: "Three different answers to 'what is a typical value' — and knowing which one a question is actually asking for.",
  bigIdea: "Mean, median and mode all claim to give the typical value, but they measure different things. The mean is the balance point, the median the middle, the mode the most popular.",
  syllabus: [
    "Mean, median and mode of grouped data",
    "Bimodal situation to be avoided",
    "Mean by direct method, assumed mean method and step deviation method",
  ],
  blocks: [
    { t: "h", text: "Why grouped data needs different formulas" },
    { t: "p", html: "Once data is grouped into classes like 10–20 and 20–30, you no longer know the individual values. So you assume every value in a class sits at its midpoint — the <strong>class mark</strong>." },
    { t: "formula", name: "Class mark", expr: "xᵢ = (lower limit + upper limit) / 2" },
    { t: "sim", id: "grouped-data" },

    { t: "h", text: "The mean, three ways" },
    { t: "formula", name: "Direct method", expr: "Mean = Σfᵢxᵢ / Σfᵢ",
      where: ["Use when the class marks are small and easy to multiply"] },
    { t: "formula", name: "Assumed mean method", expr: "Mean = a + (Σfᵢdᵢ / Σfᵢ)",
      where: ["a = assumed mean, usually the middle class mark", "dᵢ = xᵢ − a"] },
    { t: "formula", name: "Step deviation method", expr: "Mean = a + h × (Σfᵢuᵢ / Σfᵢ)",
      where: ["uᵢ = (xᵢ − a) / h", "h = class size — only valid when all classes are the same width"] },
    { t: "note", kind: "idea", html: "All three give <strong>exactly the same answer</strong>. They are not different definitions — just different amounts of arithmetic. Step deviation shrinks the numbers the most, which is why it is preferred when the class marks are large." },
    { t: "note", kind: "trap", html: "Step deviation requires <strong>equal class widths</strong>. If the classes are 0–10, 10–30, 30–35, you cannot use it — fall back to the direct or assumed mean method." },
    { t: "note", kind: "exam", html: "If a question says &ldquo;find the mean by the step deviation method&rdquo;, you must show the uᵢ column. The method is being marked, not just the answer." },

    { t: "h", text: "The median" },
    { t: "formula", name: "Median of grouped data",
      expr: "Median = l + [ (n/2 − cf) / f ] × h",
      where: ["l = lower limit of the median class", "n = Σfᵢ, the total frequency", "cf = cumulative frequency of the class <em>before</em> the median class", "f = frequency of the median class", "h = class size"] },
    { t: "list", ordered: true, items: [
      "Build the <strong>cumulative frequency</strong> column by running totals.",
      "Compute <strong>n/2</strong>.",
      "The <strong>median class</strong> is the first class whose cumulative frequency is <em>greater than or equal to</em> n/2.",
      "Read off l, cf, f and h, and substitute.",
    ] },
    { t: "note", kind: "trap", html: "<strong>cf</strong> in the formula is the cumulative frequency of the class <em>immediately before</em> the median class — not of the median class itself. Picking the wrong row here is the commonest error in the whole chapter." },
    { t: "note", kind: "memory", html: "For the median you do <strong>not</strong> need class marks at all. If a question asks only for the median, skip the xᵢ column entirely and go straight to cumulative frequencies." },

    { t: "steps", title: "Find the median of: 0–10 (5), 10–20 (8), 20–30 (15), 30–40 (12), 40–50 (7), 50–60 (3).",
      intro: "The full method. Cumulative frequencies first, always.",
      steps: [
        "Cumulative frequencies: 5, 13, 28, 40, 47, 50. So <strong>n = 50</strong>.",
        "n/2 = 25.",
        "The first cumulative frequency ≥ 25 is 28, which belongs to the class <strong>20–30</strong>. That is the median class.",
        "Read off: l = 20, cf = 13 (the class before), f = 15, h = 10.",
        "Substitute: Median = 20 + [(25 − 13)/15] × 10 = 20 + (12/15) × 10.",
        "= 20 + 8.",
      ],
      answer: "Median = 28.",
    },

    { t: "h", text: "The mode" },
    { t: "formula", name: "Mode of grouped data",
      expr: "Mode = l + [ (f₁ − f₀) / (2f₁ − f₀ − f₂) ] × h",
      where: ["l = lower limit of the modal class", "f₁ = frequency of the modal class", "f₀ = frequency of the class before it", "f₂ = frequency of the class after it", "h = class size"] },
    { t: "note", kind: "idea", html: "The <strong>modal class</strong> is simply the class with the highest frequency. The formula then nudges the answer towards whichever neighbour is bigger — which is why f₀ and f₂ appear at all." },
    { t: "note", kind: "exam", html: "The syllabus says <strong>bimodal situations are to be avoided</strong>, so you will not be given data with two equally tallest classes. If it looks bimodal, re-check your reading of the table." },

    { t: "h", text: "The empirical relationship" },
    { t: "formula", name: "Empirical relationship", expr: "3 Median = Mode + 2 Mean",
      where: ["Approximate, not exact", "Rearranges to Mode = 3 Median − 2 Mean"] },
    { t: "note", kind: "memory", html: "This is worth memorising because questions often give you two of the three and ask for the third — you can answer in one line without touching a frequency table. Read it as <strong>&ldquo;3M = M + 2M&rdquo;</strong>, with Median on the left." },

    { t: "h", text: "Which average should you actually use?" },
    { t: "table", head: ["Measure", "What it tells you", "Good when", "Weak when"], rows: [
      ["<strong>Mean</strong>", "The balance point — total shared equally", "Data is fairly symmetric", "There are extreme outliers, which drag it"],
      ["<strong>Median</strong>", "The middle value", "Data is skewed or has outliers", "You need to use it in further calculation"],
      ["<strong>Mode</strong>", "The most frequent value", "You want the most typical or popular item", "No value stands out"],
    ] },
    { t: "note", kind: "real", html: "This is why incomes are almost always reported as a <strong>median</strong>. A handful of very large incomes pulls the mean far above what most people actually earn, while the median stays where the middle person is. A shoe shop, by contrast, cares about the <strong>mode</strong> — which size sells most." },
  ],
  formulas: [
    { name: "Class mark", expr: "xᵢ = (lower + upper) / 2" },
    { name: "Mean — direct", expr: "Σfᵢxᵢ / Σfᵢ" },
    { name: "Mean — assumed", expr: "a + Σfᵢdᵢ / Σfᵢ, where dᵢ = xᵢ − a" },
    { name: "Mean — step deviation", expr: "a + h(Σfᵢuᵢ / Σfᵢ), where uᵢ = (xᵢ − a)/h" },
    { name: "Median", expr: "l + [(n/2 − cf)/f] × h" },
    { name: "Mode", expr: "l + [(f₁ − f₀)/(2f₁ − f₀ − f₂)] × h" },
    { name: "Empirical relationship", expr: "3 Median = Mode + 2 Mean" },
  ],
  examFocus: [
    "The class mark, and why grouped data needs it.",
    "All three mean methods — and showing the uᵢ column when step deviation is asked for.",
    "That step deviation needs equal class widths.",
    "Building the cumulative frequency column and identifying the median class correctly.",
    "cf being the cumulative frequency of the class <em>before</em> the median class.",
    "Identifying the modal class as the one with the highest frequency.",
    "3 Median = Mode + 2 Mean for one-line questions.",
  ],
  flashcards: [
    { q: "What is a class mark and why is it needed?", a: "The midpoint of a class: (lower limit + upper limit)/2. Once data is grouped the individual values are unknown, so every value in a class is assumed to sit at its class mark." },
    { q: "State the direct method for the mean of grouped data.", a: "Mean = Σfᵢxᵢ / Σfᵢ, where xᵢ is the class mark and fᵢ the frequency." },
    { q: "State the assumed mean method.", a: "Mean = a + (Σfᵢdᵢ / Σfᵢ), where a is an assumed mean (usually a middle class mark) and dᵢ = xᵢ − a." },
    { q: "State the step deviation method and its condition.", a: "Mean = a + h(Σfᵢuᵢ / Σfᵢ) where uᵢ = (xᵢ − a)/h. It requires all class widths to be equal." },
    { q: "Do the three mean methods give different answers?", a: "No — all three give exactly the same mean. They differ only in how much arithmetic they involve." },
    { q: "State the formula for the median of grouped data.", a: "Median = l + [(n/2 − cf)/f] × h, where l is the lower limit of the median class, cf the cumulative frequency of the preceding class, f the frequency of the median class and h the class size." },
    { q: "How do you identify the median class?", a: "Build the cumulative frequency column, compute n/2, and take the first class whose cumulative frequency is greater than or equal to n/2." },
    { q: "What does cf mean in the median formula?", a: "The cumulative frequency of the class immediately BEFORE the median class — not of the median class itself." },
    { q: "State the formula for the mode of grouped data.", a: "Mode = l + [(f₁ − f₀)/(2f₁ − f₀ − f₂)] × h, where f₁ is the frequency of the modal class and f₀, f₂ those of the classes before and after." },
    { q: "How do you identify the modal class?", a: "It is the class with the highest frequency." },
    { q: "State the empirical relationship between the three averages.", a: "3 Median = Mode + 2 Mean. It is approximate, and rearranges to Mode = 3 Median − 2 Mean." },
    { q: "Why is median preferred to mean for reporting incomes?", a: "A few very high incomes pull the mean well above what a typical person earns. The median is unaffected by extreme values, so it better represents the middle." },
    { q: "When would the mode be the most useful average?", a: "When you want the most frequently occurring item — for example, which shoe size a shop sells most of." },
  ],
  quiz: [
    { q: "The class mark of the class 25–35 is:", options: ["25", "30", "35", "10"], answer: 1, why: "Class mark = (25 + 35)/2 = 30." },
    { q: "In the step deviation method, uᵢ equals:", options: ["xᵢ − a", "(xᵢ − a)/h", "fᵢxᵢ", "xᵢ/h"], answer: 1, why: "uᵢ = (xᵢ − a)/h, where a is the assumed mean and h the common class size." },
    { q: "The step deviation method can be used only when:", options: ["The data is symmetric", "All class sizes are equal", "The frequencies are equal", "The mean is a whole number"], answer: 1, why: "Dividing by a single h only makes sense if every class has that same width." },
    { q: "In the median formula, cf is the cumulative frequency of:", options: ["The median class", "The class before the median class", "The last class", "The modal class"], answer: 1, why: "It is the cumulative frequency of the class immediately preceding the median class." },
    { q: "For the data 0–10 (4), 10–20 (6), 20–30 (10), 30–40 (5), n/2 is:", options: ["10", "12.5", "25", "15"], answer: 1, why: "n = 4 + 6 + 10 + 5 = 25, so n/2 = 12.5." },
    { q: "The modal class is the class with:", options: ["The highest class mark", "The highest frequency", "The highest cumulative frequency", "The largest width"], answer: 1, why: "The mode is about the most frequent value, so the modal class is the one with the greatest frequency." },
    { q: "If mode = 24 and mean = 30, the median is:", options: ["26", "28", "27", "25"], answer: 1, why: "3 Median = Mode + 2 Mean = 24 + 60 = 84, so Median = 28." },
    { q: "Which average is most affected by extreme values?", options: ["Mean", "Median", "Mode", "All equally"], answer: 0, why: "The mean uses every value, so one very large or very small value pulls it noticeably. The median and mode are far more resistant." },
    { q: "The three methods for the mean give:", options: ["Different answers", "The same answer", "Answers within 10% of each other", "Answers depending on h"], answer: 1, why: "They are algebraically equivalent, so they always produce identical results." },
    { q: "In the mode formula, f₀ represents:", options: ["The modal class frequency", "The frequency of the class before the modal class", "The frequency of the class after it", "The total frequency"], answer: 1, why: "f₁ is the modal class frequency, f₀ the class before, and f₂ the class after." },
    { q: "For finding only the median, which column is NOT needed?", options: ["Cumulative frequency", "Frequency", "Class mark", "Class interval"], answer: 2, why: "The median formula uses limits, frequencies and cumulative frequencies. Class marks are needed only for the mean." },
    { q: "Median class of data with cumulative frequencies 5, 13, 28, 40 and n = 40 is the class with cf:", options: ["5", "13", "28", "40"], answer: 2, why: "n/2 = 20, and the first cumulative frequency at or above 20 is 28." },
  ],
};
