import type { Chapter } from "@/lib/types";

export const ch14: Chapter = {
  slug: "probability",
  num: 14,
  title: "Probability",
  unit: "statprob",
  unitName: "Statistics and Probability",
  marks: "Unit VII · 11 marks",
  minutes: 14,
  blurb: "Count the outcomes you want, divide by all the outcomes there are. The difficulty is always in the counting.",
  bigIdea: "Probability is a fraction: favourable outcomes over total outcomes. Every mistake in this chapter is a miscount, never a misuse of the formula.",
  syllabus: [
    "Classical definition of probability",
    "Simple problems on finding the probability of an event",
  ],
  blocks: [
    { t: "h", text: "The definition" },
    { t: "formula", name: "Classical (theoretical) probability",
      expr: "P(E) = (number of outcomes favourable to E) / (total number of possible outcomes)",
      where: ["Valid only when all outcomes are <strong>equally likely</strong>"] },
    { t: "sim", id: "probability-sim" },
    { t: "note", kind: "trap", html: "The formula assumes every outcome is equally likely. A fair die qualifies; a weighted one does not. If a question says a coin or die is &ldquo;fair&rdquo; or &ldquo;unbiased&rdquo;, that word is doing real work." },
    { t: "list", items: [
      "<strong>0 ≤ P(E) ≤ 1</strong> always. A probability can never be negative or greater than 1.",
      "<strong>P(impossible event) = 0.</strong> Getting a 7 on a single die.",
      "<strong>P(sure event) = 1.</strong> Getting a number less than 7 on a single die.",
      "<strong>P(E) + P(not E) = 1.</strong> The complement rule.",
    ] },
    { t: "note", kind: "memory", html: "The complement rule is the biggest time-saver in the chapter. &ldquo;At least one&rdquo; questions are almost always easier as <strong>1 − P(none)</strong> than by counting directly." },

    { t: "h", text: "Counting the total outcomes" },
    { t: "table", head: ["Experiment", "Total outcomes", "Worth remembering"], rows: [
      ["One coin", "2", "H, T"],
      ["Two coins", "4", "HH, HT, TH, TT — note HT and TH are <em>different</em>"],
      ["Three coins", "8", "2³"],
      ["One die", "6", "1 to 6"],
      ["Two dice", "36", "6 × 6, and (2,3) differs from (3,2)"],
      ["Pack of cards", "52", "See the breakdown below"],
    ] },
    { t: "note", kind: "trap", html: "With two coins the answer is <strong>4</strong>, not 3. Many students merge HT and TH into &ldquo;one head one tail&rdquo; and get the wrong denominator. The same applies to two dice: (2,3) and (3,2) are separate outcomes." },

    { t: "h", text: "A pack of playing cards" },
    { t: "p", html: "This appears in nearly every paper, so the structure is worth learning once, properly." },
    { t: "list", items: [
      "<strong>52 cards</strong> in total, in <strong>4 suits</strong> of 13 each.",
      "<strong>Red suits:</strong> hearts and diamonds — <strong>26 red cards</strong>.",
      "<strong>Black suits:</strong> spades and clubs — <strong>26 black cards</strong>.",
      "Each suit has A, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K.",
      "<strong>Face cards</strong> are Jack, Queen and King only — <strong>12 in total</strong>, 3 per suit.",
      "<strong>Aces are not face cards.</strong> There are 4 aces.",
      "<strong>Picture cards</strong> is another name for face cards. But &ldquo;honours&rdquo; sometimes includes the ace — read the question.",
    ] },
    { t: "note", kind: "exam", html: "The single most common card mistake: counting the ace as a face card. Face cards = J, Q, K = <strong>12</strong>. If a question asks for &ldquo;face cards or aces&rdquo;, that is 12 + 4 = 16." },
    { t: "steps", title: "A card is drawn at random. Find P(a red face card).",
      intro: "Break the description into its two conditions and count what satisfies both.",
      steps: [
        "Total outcomes = 52.",
        "Face cards are J, Q, K — three in each suit.",
        "The red suits are hearts and diamonds, so red face cards are J, Q, K of hearts and J, Q, K of diamonds.",
        "That is 3 + 3 = <strong>6</strong> favourable outcomes.",
        "P = 6/52.",
      ],
      answer: "P(red face card) = 3/26.",
    },

    { t: "h", text: "Two dice — the table that answers everything" },
    { t: "p", html: "Whenever two dice are thrown, sketch or picture the 6 × 6 grid of 36 outcomes. Nearly every question is then a matter of counting cells." },
    { t: "table", head: ["Sum", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], rows: [
      ["Ways", "1", "2", "3", "4", "5", "6", "5", "4", "3", "2", "1"],
    ] },
    { t: "note", kind: "why", title: "Why 7 is the most likely sum", html: "A sum of 7 can happen six different ways — (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) — while 2 can only happen as (1,1). Probability counts <em>outcomes</em>, not values, and 7 simply has the most ways of being made. The counts above form a neat triangle, rising to 6 and falling back." },
    { t: "note", kind: "memory", html: "Useful two-dice results: <strong>P(doublet) = 6/36 = 1/6</strong>, <strong>P(sum 7) = 6/36 = 1/6</strong>, <strong>P(sum ≤ 4) = 6/36 = 1/6</strong>. All the ways add to 36 — check your counting against that." },

    { t: "h", text: "Theoretical versus experimental" },
    { t: "compare",
      left: { title: "Theoretical probability", items: [
        "Worked out by counting outcomes",
        "Requires equally likely outcomes",
        "Fixed — does not change with repetition",
        "P(head) = 1/2 for a fair coin",
      ] },
      right: { title: "Experimental (empirical) probability", items: [
        "Worked out by actually doing the trials",
        "= (number of times E happened) / (total trials)",
        "Varies from one set of trials to the next",
        "Approaches the theoretical value as trials increase",
      ] } },
    { t: "note", kind: "real", html: "Toss a coin ten times and seven heads would not surprise anyone. Toss it ten thousand times and you will land very close to half. That convergence is the whole reason theoretical probability is useful — run the simulator above and watch it happen." },

    { t: "h", text: "Question types that keep appearing" },
    { t: "list", items: [
      "<strong>Bag of balls.</strong> Count each colour, sum for the total. If a question says a ball is removed and not replaced, the total drops for the next draw.",
      "<strong>Defective items.</strong> P(defective) and P(not defective) are complements — one subtraction.",
      "<strong>Numbers 1 to n.</strong> Count multiples with care: multiples of 3 up to 20 are 3, 6, 9, 12, 15, 18 — that is 6, not 20/3.",
      "<strong>Days and months.</strong> Probability that a randomly chosen day is a Sunday is 1/7; that a birthday falls in a 31-day month needs a count of such months.",
      "<strong>Geometric probability.</strong> A dart or a coin landing in a region: P = favourable area ÷ total area.",
    ] },
    { t: "steps", title: "A bag has 5 red, 8 white and 7 blue balls. One is drawn at random. Find P(not white).",
      intro: "The complement rule turns two counts into one subtraction.",
      steps: [
        "Total balls = 5 + 8 + 7 = 20.",
        "P(white) = 8/20 = 2/5.",
        "By the complement rule, P(not white) = 1 − P(white).",
        "= 1 − 2/5.",
      ],
      answer: "P(not white) = 3/5. (Check directly: 5 + 7 = 12 non-white balls, and 12/20 = 3/5. ✓)",
    },
    { t: "note", kind: "exam", html: "Always give probability as a <strong>fraction in lowest terms</strong> unless asked otherwise, and never write it as a ratio like 3:5 — that means something different. A probability greater than 1 is a guaranteed sign you have miscounted." },
  ],
  formulas: [
    { name: "Probability of an event", expr: "P(E) = favourable outcomes / total outcomes" },
    { name: "Range", expr: "0 ≤ P(E) ≤ 1" },
    { name: "Complement rule", expr: "P(E) + P(not E) = 1" },
    { name: "Impossible / sure event", expr: "P = 0 / P = 1" },
    { name: "Experimental probability", expr: "(times E occurred) / (total trials)" },
    { name: "Two dice", expr: "36 outcomes; P(doublet) = 1/6; P(sum 7) = 1/6" },
    { name: "Cards", expr: "52 total · 26 red · 12 face (J,Q,K) · 4 aces" },
  ],
  examFocus: [
    "The definition, and that it needs equally likely outcomes.",
    "0 ≤ P ≤ 1, and the complement rule for 'at least one' questions.",
    "Counting total outcomes correctly — two coins give 4, two dice give 36.",
    "The card pack structure, especially that aces are NOT face cards.",
    "The two-dice sum distribution, and why 7 is most likely.",
    "The difference between theoretical and experimental probability.",
    "Giving answers as fractions in lowest terms.",
  ],
  flashcards: [
    { q: "State the classical definition of probability.", a: "P(E) = number of outcomes favourable to E ÷ total number of possible outcomes, provided all outcomes are equally likely." },
    { q: "What is the range of a probability?", a: "0 ≤ P(E) ≤ 1. An impossible event has probability 0 and a sure event has probability 1." },
    { q: "State the complement rule.", a: "P(E) + P(not E) = 1, so P(not E) = 1 − P(E)." },
    { q: "How many outcomes are there when two coins are tossed?", a: "Four: HH, HT, TH and TT. HT and TH are distinct outcomes, which is why the answer is 4, not 3." },
    { q: "How many outcomes are there when two dice are thrown?", a: "36, since each die has 6 faces and (2,3) is different from (3,2)." },
    { q: "Describe the composition of a pack of playing cards.", a: "52 cards in 4 suits of 13. Hearts and diamonds are red (26 cards), spades and clubs black (26). Each suit has A, 2–10, J, Q, K." },
    { q: "How many face cards are there, and do aces count?", a: "12 face cards — Jack, Queen and King in each of the four suits. Aces are NOT face cards; there are 4 of them separately." },
    { q: "What is the probability of drawing a red face card?", a: "Red face cards are J, Q, K of hearts and of diamonds — 6 cards. So P = 6/52 = 3/26." },
    { q: "Why is a sum of 7 the most likely with two dice?", a: "It can be made in six ways: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). No other sum has as many combinations." },
    { q: "What is the probability of getting a doublet with two dice?", a: "The doublets are (1,1) through (6,6) — 6 outcomes out of 36, so P = 1/6." },
    { q: "Differentiate theoretical and experimental probability.", a: "Theoretical probability is calculated by counting equally likely outcomes. Experimental probability is found by performing trials and dividing occurrences by the number of trials. The experimental value approaches the theoretical as the number of trials grows." },
    { q: "How do you handle an 'at least one' probability question?", a: "Use the complement: P(at least one) = 1 − P(none). Counting directly is usually much longer." },
    { q: "How is geometric probability calculated?", a: "As the ratio of the favourable area to the total area — used for problems about a dart or coin landing in a particular region." },
  ],
  quiz: [
    { q: "The probability of an impossible event is:", options: ["1", "0", "1/2", "−1"], answer: 1, why: "An impossible event has no favourable outcomes, so the numerator is 0." },
    { q: "Two coins are tossed. The probability of getting exactly one head is:", options: ["1/4", "1/2", "3/4", "1/3"], answer: 1, why: "The four outcomes are HH, HT, TH, TT. Exactly one head occurs in HT and TH, so P = 2/4 = 1/2." },
    { q: "A card is drawn from a well-shuffled pack. P(a face card) is:", options: ["3/13", "1/13", "4/13", "1/4"], answer: 0, why: "There are 12 face cards (J, Q, K in four suits), so P = 12/52 = 3/13." },
    { q: "The probability of drawing an ace is:", options: ["3/13", "1/13", "1/26", "4/13"], answer: 1, why: "There are 4 aces, so P = 4/52 = 1/13. Aces are separate from face cards." },
    { q: "Two dice are thrown. P(sum = 7) is:", options: ["1/6", "1/12", "5/36", "7/36"], answer: 0, why: "Six of the 36 outcomes give a sum of 7, so P = 6/36 = 1/6." },
    { q: "If P(E) = 0.35, then P(not E) is:", options: ["0.35", "0.65", "1.35", "0.5"], answer: 1, why: "P(not E) = 1 − 0.35 = 0.65." },
    { q: "Which of these cannot be a probability?", options: ["0.7", "3/7", "−0.2", "0"], answer: 2, why: "Probability can never be negative; it must lie between 0 and 1 inclusive." },
    { q: "A bag has 3 red and 5 black balls. P(red) is:", options: ["3/5", "3/8", "5/8", "1/3"], answer: 1, why: "Total = 8 balls, favourable = 3, so P = 3/8." },
    { q: "A number is chosen from 1 to 20. P(it is a multiple of 3) is:", options: ["3/20", "6/20", "1/3", "7/20"], answer: 1, why: "Multiples of 3 up to 20 are 3, 6, 9, 12, 15, 18 — six of them. P = 6/20 = 3/10." },
    { q: "The sum of the probabilities of all elementary outcomes of an experiment is:", options: ["0", "1", "Depends on the experiment", "Between 0 and 1"], answer: 1, why: "One of the outcomes must occur, so their probabilities always total 1." },
    { q: "Two dice are thrown. P(getting a doublet) is:", options: ["1/6", "1/36", "5/36", "1/12"], answer: 0, why: "The six doublets (1,1) to (6,6) out of 36 outcomes give 6/36 = 1/6." },
    { q: "As the number of trials increases, experimental probability:", options: ["Moves away from theoretical", "Approaches theoretical", "Stays constant", "Becomes zero"], answer: 1, why: "With more trials, random fluctuations average out and the experimental value converges towards the theoretical one." },
  ],
};
